from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
commit='31a3267de9b1cf15134707a7916b6d03bd7a4797';prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_157_f3_actual_first24_membership_delivery_v1';P=W/prefix;files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(files)==4
before={n:sha(W/n) for n in files};validator=P/'scripts/validate_fresh157.py';vr=subprocess.run(['python3','-B',str(validator)],capture_output=True,text=True);assert vr.returncode==0 and before=={n:sha(W/n) for n in files}
m=load(P/'metadata/f3-actual-first24-delivery-manifest.json')
for e in m['authoritative_sources'].values():assert sha(e['path'])==e['sha256']
cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_215.json';cp=load(cpp);assert cp['stage1_visual_accepted_complete_independent_cases']==278 and cp['accepted_per_family']['F3']==37
idx=load(root(1249)/'full336-current278-role-aware-registration-progress-index.json');rowmap={r['physical_case_id']:r for r in idx['cases'] if r['family_id']=='F3'};assert len(rowmap)==48
accepted=[(p,load(p)) for p in cp['accepted_decisions'] if load(p)['family_id']=='F3'];assert len(accepted)==37
frozenp=root(1093)/'FIRST8_PER_FAMILY_STAGE1_SUBSET56.json';frozen=load(frozenp)['cases_by_family']['F3'];assert len(frozen)==8
for e in frozen:assert sha(e['path'])==e['sha256']
identity=lambda d:d.get('physical_case_id',d['case_id']);ids8=[identity(load(e['path'])) for e in frozen];ids37=[identity(d) for p,d in accepted];assert len(set(ids8))==8 and set(ids8)<=set(ids37)
actual24=ids8+[pid for pid in ids37 if pid not in set(ids8)][:16];assert len(set(actual24))==24 and actual24==[r['physical_case_id'] for r in m['actual_first24_delivery']['members']]
assert set(actual24)<=set(ids37)<=set(rowmap)
amap={identity(d):(p,d) for p,d in accepted}
for member in m['actual_first24_delivery']['members']:
 pid=member['physical_case_id'];p,d=amap[pid];assert member['case_id']==d['case_id'] and member['accepted_decision']['path']==p and sha(p)==member['accepted_decision']['sha256']
 assert d['status'].startswith('visual-approved') and member['accepted_semantic_scope']['sha256']==d['physical_condition_sha256']
 assert member['actual_native_request_scope']['sha256']==rowmap[pid]['native_request_scope']['sha256']
plan=load(root(1205)/'F3-first8-first24-physical-membership-with-actual-native-request-roles.json');planned={r['physical_case_id'] for r in plan['rows']};assert len(planned)==24 and len(planned-set(actual24))==len(set(actual24)-planned)==5
unknown=m['scope_role_preservation']['historical_original_native_os_unknown_cases'];assert len(unknown)==4
for r in unknown:
 e=rowmap[r['physical_case_id']]['native_request_scope']['evidence']['receipt'];assert sha(e['path'])==e['sha256'];a=load(e['path']);assert a['status']=='running' and a.get('returncode') is None and r['native_completed0'] is False
O=H/'root_stage1_source157_F3_actual_frozen8_plus16_accepted_delivery_first24_semantic_native_roles_preserved_checkpoint_1252';assert not O.exists() and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_216.json').exists();O.mkdir();adopted=[]
for n in files:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
put(O/'source157-exact-adoption-readonly-validator-proof.json',{'source_commit':commit,'adopted_files':adopted,'validator':ref(validator),'returncode':vr.returncode,'stdout':vr.stdout,'stderr':vr.stderr,'source_bytes_unchanged':True})
now=datetime.datetime.now(datetime.timezone.utc).isoformat();manifest=O/'MAIN_F3_ACTUAL_FIRST24_DELIVERED_SUBSET_CURRENT37_FINAL48.json'
put(manifest,{'schema':'ds02.main.F3.actual-first24-delivery.v1','at_utc':now,'frozen_first8_authority':ref(frozenp),'stable_source_authoritative_checkpoint':ref(cpp),'source157_original_manifest':ref(R/prefix/'metadata/f3-actual-first24-delivery-manifest.json'),'actual_first8_physical_case_ids':ids8,'actual_first24_physical_case_ids':actual24,'actual_visual_decisions':[ref(amap[pid][0]) for pid in actual24],'current_F3_accepted':37,'registered_final_F3':48,'first8_subset_actual24_subset_current37_subset_final48':True,'actual_first24_delivered':True,'final48_delivered':False,'source146_original_plan24_preserved':ref(root(1205)/'F3-first8-first24-physical-membership-with-actual-native-request-roles.json'),'planned_only5_not_in_actual24':sorted(planned-set(actual24)),'actual24_additions5_not_in_plan':sorted(set(actual24)-planned),'anchor_accepted_semantic49_and_actual_native86562_roles_preserved':m['scope_role_preservation'],'four_original_native_OS_status_unknown_not_overridden_by_recovered065':True,'main_scientific_payload_IO':False,'new_case_credit':0,'Q_N':0,'Q_E':0,'precision_status':'视觉检查通过、数值精度未验收'})
raw=(D/'runtime/resource-ledger.json').read_bytes();lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;cnt=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;assert free>=500 and gpu<=512 and cpu<=3840 and cnt['qualification']<=1024 and cnt['production']<=720
cp.update(checkpoint=216,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts=dict(cnt),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: original1183 full801 completed0 publication and independentQI1250; source157 actualF3first24 frozen8+16realaccepted materialized, all24actualvisualdecisions/37accepted/48registered roles checked. Planned24 contains5different members preserved separately, no casecredit or native OS-status reclassification.',authorized_work_state='Active278/336. F5original1183 full801QI awaits personal197 then independentacceptance; F2original1169 full401 ongoing, originalF5M094T0951161 nowautomaticallyadmitted. ActualF3first24 complete; actualF5first24prefix15 stillincomplete. Native/scientific numericalprecision unaccepted, all originalguards preserved.')
cp['actual_progress']['source157_F3_actual_first24_delivered']=ref(manifest);cp['source_agents']['production_recovery']='fresh157 actualF3first24 adopted; nextremaining originalF3 publication personalreview';cp['next_executable_tasks']=['Adopt source197 original1183 full801 personal34contacts9keys with1250QI andnativeplanfieldabsence preserved.', 'Finish1251 F2original1169 full401QI after realterminal0, then adopt personal173 with quantified39fluid UID limitations.', 'Continue originalF5M094T0951161 and other originalF3/lastF6 render queue without restarts.', 'Extend actualF5first24 frozen8+realaccepted prefix15; retain cumulativebudgets and Home500GiB floor.']
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_216.json';put(newcp,cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: deliver actual F3 first24 preserving frozen8 and native semantic roles','--',*paths],cwd=R,check=True);print({'checkpoint':216,'accepted':278,'F3_actual_first24':'DELIVERED','HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
