from pathlib import Path
import json,hashlib,runpy,subprocess,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_142_f2_actual_native_typed157_home4gib_v2';commit='993df61a9e64567539c3b352f07e7fcca8328773';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert 15<len(names)<80;adopted=[]
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_F2_source142_eight_actual812_native0_full401_typed157_actual974_decoder_Home4GiB_1020';O.mkdir(exist_ok=True);assert not (O/'controller-config.json').exists();(O/'requests').mkdir(exist_ok=True);validator=W/prefix/'workers/validate_fresh142.py';assert sha(validator)==sha(P/'workers/validate_fresh142.py');result=subprocess.run([str(L/'.venv/bin/python'),'-B',str(validator),'--report',str(O/'actual-source142-original-validator-report.json')],text=True,capture_output=True);assert result.returncode==0,result.stderr
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_146.json');ids={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};oldq=load(next((root(995)/'requests').glob('*.json')));ids.add(oldq['physical_case_id']);
for pq in load(root(1013)/'controller-config.json')['requests']:ids.add(load(pq)['physical_case_id'])
base=oldq;fair=root(928)/'fair_CPU_dispatch.py';controller=O/'batch-typed-controller.py';controller.write_bytes((root(995)/'batch-typed-controller.py').read_bytes());converter=runpy.run_path(str(L/'scripts/ds_data02_direct_convert.py'))
r974q=load(root(974)/'enabled-typed-request.json');r974p=Path(r974q['attempt_root'])/'execution-receipt.json';r974=load(r974p);tools={}
for flag in ['--decoder','--partvtk']:
 p=Path(r974q['command'][r974q['command'].index(flag)+1]);actual=hashlib.sha256(p.resolve().read_bytes()).hexdigest();assert r974['input_hashes_at_launch'][str(p.resolve())]==r974['input_hashes_after_run'][str(p.resolve())]==actual;tools[flag]={'path':str(p),'sha256':actual,'actual_producer_receipt':ref(r974p)}
assert tools['--decoder']['path']=='/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/campaigns/l1-resume/artifacts/bi4_dump'
proof=O/'actual-source142-actual-decoder-grounded974-private-staging-review.json';oldalias=str(L/'campaigns/l1-resume/artifacts/bi4_dump');assert not Path(oldalias).exists();put(proof,{'excluded_wrong_decoder_alias_absent':oldalias,'source142_actual_decoder_and_known_tool_exists_check_passed':True,'actual974_decoder_and_PartVTK':tools,'correct_source142_decoder_already_bound_actual974':True,'original_source_requests_and_validator_unchanged':True,'no_scientific_job_started_with_bad_alias':True,'science_recipe_owner_native_frames_counts_unchanged':True,'actual_future_science_hashes_null':True,'case_credit':0})
qs=[];rows=[]
for sp in sorted((P/'requests/typed').glob('*.json')):
 q=load(sp);assert q['disabled'] and q['source_only'] and q['physical_case_id'] not in ids;ids.add(q['physical_case_id']);nrp=Path(q['actual_native_dependency']['receipt']);nr=load(nrp);qa=load(q['actual_initial_qa_dependency']['report']);gen=load(q['gencase_receipt']);prep=load(q['prepared_input_report'])
 assert all((r['status'],r['returncode'])==('completed',0) for r in [nr,gen,load(q['actual_initial_qa_dependency']['receipt'])]) and qa['status']=='pass' and all(qa['checks'].values())
 assert q['physical_case_id']==nr['request']['physical_case_id'] and q['physical_condition_sha256']==nr['request']['physical_condition_sha256'];assert sha(nrp)==q['actual_native_dependency']['receipt_sha256']
 assert prep['actual_total_particles']==418104 and prep['generated_xml_particle_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21114}
 assert sha(q['generated_xml'])==q['generated_xml_sha256']==nr['input_hashes_at_launch'][q['generated_xml']]==nr['input_hashes_after_run'][q['generated_xml']]
 dr=Path(q['actual_native_dependency']['data_root']);assert sorted(p.name for p in dr.glob('Part_[0-9]*.bi4'))==[f'Part_{i:04d}.bi4' for i in range(401)]
 own=load(q['owner_metadata']);scope=converter['_physical_condition_scope'](own);legacy=converter['canonical_hash'](scope);assert q['actual_converter_scope_sha256_prospective'] is None and q['actual_converter_physical_condition_scope_sha256'] is None and own['actual_converter_physical_condition_scope_sha256'] is None
 cmd=q['command'].copy();md={}
 for p,h in q['input_sha256'].items():
  if p==oldalias:assert h==tools['--decoder']['sha256'];continue
  path=Path(p);assert path.is_file()
  if path.suffix in {'.json','.py','.xml','.md'}:assert sha(path)==h
  else:
   assert q['input_sha256_categories'][p] in {'registered_binary_or_tool_attestation','registered_tool_attestation'};assert hashlib.sha256(path.resolve().read_bytes()).hexdigest()==h
   resolved=str(path.resolve());assert r974['input_hashes_at_launch'][resolved]==r974['input_hashes_after_run'][resolved]==h
  md[p]=h
 for flag,tool in tools.items():cmd[cmd.index(flag)+1]=tool['path'];md[tool['path']]=tool['sha256']
 for p in [sp,controller,fair,proof,O/'actual-source142-original-validator-report.json',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json']:md[str(p)]=sha(p)
 cid=q['case_id'];aid=f'root-stage1-f2-{cid.lower()}-actual812-full401-typed157-home4gib-source142-root1020';ar=D/'families/F2'/cid/aid;assert not ar.exists();staging='/tmp/ds02-nvme-typed-cache-root1020-'+cid.lower();assert not Path(staging).exists();current=f'F2/{cid}/{aid}';cmd[cmd.index('--staging-root')+1]=staging;cmd[cmd.index('--current-attempt-id')+1]=current
 q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']});q.update(tag=cid,attempt_id=aid,attempt_root=str(ar),current_attempt_id=current,command=cmd,input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,conversion_allowed=True,arrays_allowed=True,root_review_required=False,expected_converter_scope_sha256=legacy,estimated_storage_bytes=4*2**30,cpu_threads=2,cpu_task_kind='conversion',root_source_request=ref(sp),root_grounded_actual974_tool_binding=tools,root_actual974_tool_producer_binding=ref(proof),root_unique_private_staging_per_case=True,case_credit=0)
 qp=O/'requests'/(cid+'-enabled-typed-request.json');q['input_sha256_categories']={p:q['input_sha256_categories'].get(p,'root_metadata_current_hash') for p in md};q['input_sha256_provenance']={p:q['input_sha256_provenance'].get(p,'Primary actual immutable metadata or producer binary attestation') for p in md};put(qp,q);qs.append(str(qp));rows.append({'case_id':cid,'physical_case_id':q['physical_case_id'],'actual_native_receipt':ref(nrp),'all401_real_native_filenames_present':True,'canonical_source_scope':q['physical_condition_sha256'],'prospective_unchanged_converter_scope':legacy,'future_hashes_null':q['future_output_hashes'],'enabled_request':ref(qp),'science_payload_IO':False})
assert len(qs)==8
put(O/'controller-config.json',{'requests':qs,'request_sha256':{p:sha(p) for p in qs},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});put(O/'source142-adoption-eight-actual812-native-independent-review.json',{'source_commit':commit,'adopted_files':adopted,'original_validator':ref(O/'actual-source142-original-validator-report.json'),'cases':rows,'actual995_all12_registered1013_and_accepted222_excluded':True,'future_actual_converter_scope_preserved_null_expected_scope_derived_only_from_unchanged_converter_metadata_helper':True,'no_native_reruns':True,'source_bytes_preserved':True,'Home_floor_GiB':500,'per_output_cap_GiB':4,'science_payload_IO':False,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(p['path']).relative_to(R)) for p in adopted]+[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: admit eight existing F2 native0 conversions with actual decoder and bounded private staging','--',*paths],cwd=R,check=True);print({'root':str(O),'requests':len(qs),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
