from pathlib import Path
import json,hashlib,subprocess,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
old=root(993);cfg=load(old/'controller-config.json');a=load(old/'actual-progress.json');assert len(a['results'])==1 and (a['results'][0]['status'],a['results'][0]['returncode'])==('completed',0) and not a['results'][0]['actual_full801_N3_XMF_pass']
first=load(cfg['requests'][0]);ar=Path(first['attempt_root']);rp=ar/'execution-receipt.json';manifest=ar/'xmf/manifest.json';x=load(manifest);b=load(first['command'][first['command'].index('--binding')+1]);t=load(b['conversion_report']);assert load(rp)['status']=='completed' and load(rp)['returncode']==0 and x['frames']==801 and x['particles']==194427 and x['physical_case_id']==first['physical_case_id'] and x['physical_condition_sha256']==first['physical_condition_sha256'] and x['source_h5_sha256']==t['output_sha256']==first['actual_typed_H5_SHA_from_producer_only']
grids=ET.parse(x['xdmf']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(grids)==801 and [float(g.find('Time').get('Value')) for g in grids]==times==[f['time'] for f in t['lifecycle']['frame_summary']] and times[-1]>=16 and x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3] and x['xdmf_sha256']==sha(x['xdmf'])
O=H/'root_stage1_F5_actual993_XMF0_wrong_observer_directory_remaining2_same_requests_recovery_998';O.mkdir(exist_ok=False);proof=O/'actual993-genuine-XMF0-and-observer-output-directory-correction.json';put(proof,{'actual_successful_XMF_receipt':ref(rp),'actual_successful_XMF_manifest':ref(manifest),'actual_successful_XMF_XML':ref(x['xdmf']),'all801_times_typed_XML_manifest_exact_N3':True,'original_false_controller_gate_preserved':ref(old/'actual-progress.json'),'observer_error':'Original controller looked in xdmf/manifest.json while unchanged worker command publishes xmf/manifest.json.','scientific_producer_completed0_not_reclassified_as_failed':True,'first_successful_case_not_repeated':True,'remaining2_original_requests_unchanged_and_not_previously_consumed':True,'scientific_payload_IO_by_primary':False,'repair_number':1,'case_credit':0})
controller=O/'batch-xmf-controller.py';controller.write_text((old/'batch-xmf-controller.py').read_text().replace("/'xdmf/manifest.json'","/'xmf/manifest.json'"));remaining=cfg['requests'][1:];assert len(remaining)==2
for qp in remaining:
 q=load(qp);assert not Path(q['attempt_root']).exists() and sha(qp)==cfg['request_sha256'][qp]
put(O/'controller-config.json',{**cfg,'requests':remaining,'request_sha256':{p:sha(p) for p in remaining},'original_successfully_completed_first_request_not_repeated':cfg['requests'][0]});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify genuine F5 XMF success and resume only two unconsumed requests with correct observer directory','--',*paths],cwd=R,check=True);print({'root':str(O),'first_actual_XMF_completed0':True,'remaining_requests':2,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
