from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');O=H/'root_stage1_F4_delegated114_aligned_lattice_two_actual_metadata_integration_810';O.mkdir(exist_ok=True)
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
def norm(cid):return cid.replace('F4_DROP_B08_','F4_DROP_')
assert not (O/'actual-integration-review.json').exists();prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_102.json')['accepted_decisions'].copy()
for n in [798,799,800,802,803,805,806,807]:prior+=load(root(n)/'actual-integration-review.json')['decisions']
assert len(prior)==127;ids={norm(load(p).get('physical_case_id',load(p)['case_id'])) for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior};decisions=[]
commit=subprocess.run(['git','rev-parse','4be3d45a'],cwd=W,capture_output=True,text=True,check=True).stdout.strip();src=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_114_*'));rel=src.relative_to(W);names=subprocess.run(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,capture_output=True,text=True,check=True).stdout.splitlines();assert names;adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};blob=subprocess.run(['git','show',f'{commit}:{name}'],cwd=W,capture_output=True,check=True).stdout;assert p.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True)
 if dst.exists():assert dst.read_bytes()==blob
 else:dst.write_bytes(blob)
 adopted.append(ref(dst))
P=R/rel;idx=load(P/'metadata/review-index.json');assert len(idx['cases'])==2
for row in idx['cases']:
 cl=P/'metadata'/Path(row['metadata_closure_path']).name;c=load(cl);m=c['producer_metadata'];sc=c['scope_separation'];cid=c['case_id'];pid=c['physical_case_id'];dg=sc['canonical_owner_consumer_physical_binding_sha256'];ev={};assert norm(pid) not in ids and dg not in hashes and row['status']==c['visual_decision']['status']=='visual-approved-by-delegated-agent' and c['reviewer']=='/root/f6_endpoint_initial_qa'
 owner=load(sc['consumer_owner_path']);assert sha(sc['consumer_owner_path'])==sc['consumer_owner_sha256'];assert owner['physical_binding_sha256']==dg and owner['physical_condition_sha256']==sc['source_owner_declared_physical_condition_sha256'];payload=owner['physical_binding'];assert hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg;assert payload['parameters']['gap_m']==row['gap_m'] and payload['parameters']['x_offset_m']==payload['parameters']['y_offset_m']==0 and payload['parameters']['speed_m_per_s']==.5
 for k in ['gencase_receipt','native_receipt','typed_receipt','xmf_receipt','render_receipt']:
  rp=m[k];r=load(rp);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;ev[k]=ref(rp)
 prep=load(m['prepared_input_report']);assert prep['actual_total_particles']==83233 and prep['generated_xml_particle_counts']=={'fixed':24161,'moving':0,'floating':0,'fluid':59072} and prep['actual_generated_constants']['data2d']['value']=='false';assert sha(m['generated_xml_path'])==prep['xml_sha256']==m['generated_xml_sha256_attested_by_qa']
 qa=load(m['initial_native_qa_report']);assert sha(m['initial_native_qa_report'])==m['initial_native_qa_report_sha256'] and qa['pass'] and qa['native_audit_returncode']==0 and qa['total_particles']==83233 and qa['fluid_particles']==59072 and all(qa['checks'].values());qrp=next(p/'execution-receipt.json' for p in Path(m['initial_native_qa_report']).parents if (p/'execution-receipt.json').exists());qr=load(qrp);assert (qr['status'],qr['returncode'])==('completed',0);ev['initial_native_qa_shared_receipt']=ref(qrp)
 t=load(m['conversion_report']);assert sha(m['conversion_report'])==m['conversion_report_sha256'];assert t['conversion_status']=='completed' and t['frames']==1201 and t['particles']==83233 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and t['hash_scopes']['physical_condition_sha256']==dg;assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=1.2 and t['time_evidence']['strictly_increasing']
 x=load(m['xmf_manifest']);assert sha(m['xmf_manifest'])==m['xmf_manifest_sha256'] and x['frames']==1201 and x['particles']==83233 and x['source_h5_sha256']==t['output_sha256'];xf=x['xdmf'];assert sha(xf)==x['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==1201 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='83233 3' for g in gs)
 a=load(m['render_report']);assert sha(m['render_report'])==m['render_report_sha256'];assert a['frames']==a['source_frames']==1201 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(m['xmf_manifest']) and a['xdmf']==xf and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf) and a['source_h5_sha256']==t['output_sha256'];fs=a['frame_diagnostics'];assert len(fs)==1201 and all(f['active']==83233 and f['missing']==0 and f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in fs)
 pngp=P/'metadata'/Path(row['png_hash_manifest']).name;png=load(pngp);assert png['computed_after_view_image'] and c['png_assets']['viewed_with']=='view_image' and len(png['contact_sheets'])==51 and len(png['key_frames'])==9
 for p in png['contact_sheets']+png['key_frames']:assert Path(p['path']).suffix=='.png' and sha(p['path'])==p['sha256']
 for k in ['prepared_input_report','initial_native_qa_report','conversion_report','xmf_manifest','render_report']:ev[k]=ref(m[k])
 ev['xmf']=ref(xf);out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':row['status'],'family_id':'F4','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'physical_condition':payload,'source_review_commit':commit,'source_review_closure':ref(cl),'visual_reviewer':'/root/f6_endpoint_initial_qa','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':c['visual_decision']['observations'],'agent_limitations':c['visual_decision']['limitations'],'scope_separation':sc,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':png,'actual_frames':1201,'actual_particles':83233,'actual_fluid_particles':59072,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'lineage':'independent original aligned-lattice full native cases; not Root638 replacement lineage','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':127+len(decisions),'resulting_count':128+len(decisions)};dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);decisions.append(str(dp));ids.add(norm(pid));hashes.add(dg)
put(O/'actual-integration-review.json',{'source_commit':commit,'adopted_files':adopted,'source_adopted_byte_exact':True,'previous_count':127,'resulting_count':127+len(decisions),'independent_case_increment':len(decisions),'decisions':decisions,'science_payload_not_read_or_hashed':True});print({'new_cases':len(decisions),'accepted':127+len(decisions)})
