from pathlib import Path
import json,hashlib,runpy,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
P=L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_158_m095_t080_typed_downstream_disabled_v1';b=load(L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_159_m086_identity_adapter_disabled_v1/bindings/M086_T085-identity-bound-xmf-binding.json');q=load(P/'requests/M086_T085-full801-xmf-request.json');q['case_id']=b['case_id'];assert b['case_id']==b['producer_case_id']=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M086_T085_NEXT34';worker=Path(q['command'][1]);assert sha(worker)=='aeccc3204d751250bd94ffab704ed65c2c691c4739f4b2f5e0d51aefb21b4e3c';assert (load(b['typed_receipt'])['status'],load(b['typed_receipt'])['returncode'])==('completed',0);assert (load(b['full_native_receipt'])['status'],load(b['full_native_receipt'])['returncode'])==('completed',0);t=load(b['conversion_report']);assert t['frames']==801 and t['particles']==194427 and t['output_sha256']==b['trajectory_h5_sha256'] and t['solver_dimension']['solver_dimension']==3 and t['hash_scopes']['physical_condition_sha256']==b['source_h5_physical_condition_sha256'];assert Path(b['trajectory_h5']).is_file();accepted=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_124.json')['accepted_decisions'];assert b['physical_case_id'] not in {load(p).get('physical_case_id',load(p)['case_id']) for p in accepted}
O=H/'root_stage1_F5_M086T085_actual864_full801_N3_XMF_native_receipt_alias_fairCPU2_963';O.mkdir(exist_ok=False);aid='root-stage1-f5-m086-t085-actual864-full801-N3-XMF-root963';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();b.pop('identity_adapter',None);b.update(native_receipt=b['full_native_receipt'],native_receipt_sha256=b['full_native_receipt_sha256'],disabled=False,source_only=False,execution_allowed=True,launch_allowed=True,full801_authorized=True,root_actual_XMF_attempt_id=aid);bp=O/'enabled-XMF-binding.json';put(bp,b);md=q['input_sha256'].copy()
for p,d in md.items():assert sha(p)==d
controller=O/'fair-XMF-controller.py';controller.write_text("from pathlib import Path\nimport json,runpy\nO=Path(__file__).parent\nc=json.loads((O/'controller-config.json').read_text())\nr=runpy.run_path(c['fair_dispatch']['path'])['dispatch'](c['request'],serial_conversion=True)\nq=json.loads(Path(c['request']).read_text())\nrp=Path(q['attempt_root'])/'execution-receipt.json'\na=json.loads(rp.read_text()) if rp.exists() else {}\nv={'launcher_returncode':r.returncode,'status':a.get('status'),'returncode':a.get('returncode'),'actual_receipt':str(rp),'stdout_tail':r.stdout[-2000:],'stderr_tail':r.stderr[-2000:],'case_credit':0}\n(O/'controller-result.json').write_text(json.dumps(v,indent=2)+'\\n')\nprint(json.dumps(v),flush=True)\nraise SystemExit(r.returncode)\n");compile(controller.read_text(),str(controller),'exec');fair=root(928)/'fair_CPU_dispatch.py'
for p in [bp,controller,fair,root(949)/'actual939-and158-review.json',root(962)/'actual161-adoption-and-main-regression-review.json']:md[str(p)]=sha(p)
md[b['trajectory_h5']]=t['output_sha256'];base=load(root(939)/'enabled-first-typed-request.json');q.update({k:v for k,v in base.items() if k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']});q.update(schema='ds02.runner-request.v2',attempt_id=aid,attempt_root=str(ar),physical_condition_sha256=b['physical_condition_sha256'],binding=str(bp),binding_sha256=sha(bp),command=[str(L/'.venv/bin/python'),str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xmf'],input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,full801_authorized=True,root_independent_case_credit_pending_visual=True);qp=O/'enabled-XMF-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(fair),'case_credit':0});put(O/'metadata-preflight.json',{'actual_typed864_completed0_preserved':True,'original801_native850_not_rerun':True,'N3_from_actual_producer_report':True,'native_receipt_alias_is_exact_original':True,'all_metadata_hashes_verified':True,'source_H5_digest_from_immutable_producer_report_only':True,'main_science_payload_IO':False,'future_XMF_hashes_not_claimed':True,'Home_estimate_GiB':1,'Home_floor_GiB':500,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register true M086 producer full801 XMF after grounded identity adapter verification','--',*paths],cwd=R,check=True);print({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
