from pathlib import Path
import json,hashlib,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_160_m095_m085_terminal_xmf_disabled_v1';commit='a2dfb189451694bd42906e20fef266d96860db54';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();adopted=[]
for name in names:
 assert Path(name).suffix in ['.json','.py','.md'];raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists();p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;b=load(P/'bindings/M095_T080-terminal-xmf-binding.json');q=load(P/'requests/M095_T080-terminal-xmf-request.json');t=load(b['conversion_report']);assert b['native_receipt']==b['full_native_receipt'];assert t['frames']==801 and t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['output_sha256']==b['trajectory_h5_sha256'];assert t['hash_scopes']['physical_condition_sha256']==b['source_h5_physical_condition_sha256'];assert len({b['physical_condition_sha256'],b['source_plan_physical_condition_sha256'],b['source_h5_physical_condition_sha256']})==3
for key in ['native_receipt','typed_receipt','conversion_report','initial_qa_receipt','initial_qa_report']:assert sha(b[key])==b[key+'_sha256']
for key in ['native_receipt','typed_receipt','initial_qa_receipt']:
 a=load(b[key]);assert (a['status'],a['returncode'])==('completed',0)
qa=load(b['initial_qa_report']);assert b['actual_counts']==qa['actual_counts'] and qa['all_basic_placement_checks_pass'];assert b['initial_qa_output_root']==load(b['initial_qa_receipt'])['output_root'];assert qa['numerical_precision_result_accepted'] is False;assert Path(b['trajectory_h5']).is_file();cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_129.json');assert b['physical_case_id'] not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
O=H/'root_stage1_F5_M095T080_actual939_full801_terminal160_N3_XMF_fairCPU2_968';O.mkdir(exist_ok=False);aid='root-stage1-f5-m095-t080-actual939-full801-N3-XMF-root968';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();bp=O/'enabled-XMF-binding.json';b.update(disabled=False,source_only=False,execution_allowed=True,launch_allowed=True,root_actual_XMF_attempt_id=aid);put(bp,b)
controller=O/'fair-XMF-controller.py';controller.write_bytes((root(963)/'fair-XMF-controller.py').read_bytes());fair=root(928)/'fair_CPU_dispatch.py';base=load(root(963)/'enabled-XMF-request.json');md=q['input_sha256'].copy()
for p,d in md.items():assert sha(p)==d
for p in [bp,controller,fair,root(967)/'adoption-and-independent-review.json',P/'metadata/terminal-typed-attestations.json']:md[str(p)]=sha(p)
md[b['trajectory_h5']]=t['output_sha256'];q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','science_input_policy']});q.update(attempt_id=aid,attempt_root=str(ar),binding=str(bp),binding_sha256=sha(bp),command=[str(L/'.venv/bin/python'),q['command'][1],'--binding',str(bp),'--output-dir','{attempt_root}/xmf'],input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,case_credit=0);qp=O/'enabled-XMF-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(fair),'case_credit':0});put(O/'source160-adoption-and-main-metadata-review.json',{'source_commit':commit,'adopted_files':adopted,'source_byte_exact':True,'actual939_full801_typed0':True,'actual808_full801_native0':True,'native_receipt_exact_alias':True,'actual_QA_counts_and_output_root_bound':True,'precision_negative_preserved':True,'scope_separation':{k:b[k] for k in ['physical_condition_sha256','source_plan_physical_condition_sha256','source_h5_physical_condition_sha256']},'science_payload_IO_by_main':False,'H5_digest_from_producer_report_only':True,'M085_already_accepted202_not_rerun':True,'future_XMF_hashes_not_claimed':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(p['path']).relative_to(R)) for p in adopted]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: bind terminal M095 full801 XMF to real typed939 source160 metadata','--',*paths],cwd=R,check=True);print({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
