from pathlib import Path
import json,hashlib,subprocess,datetime,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.log','.txt','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='256afbedf0816519b2ca9810e8521820d5eca537';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_200_f5_assigned_f2_rx061_rot105_actual1154_personal_visual_review_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==8;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh200.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
v=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');chain=load(P/'metadata/physical-stage-closure.json');up=load(P/'metadata/upstream-evidence.json');sr=load(P/'metadata/actual-render-metadata.json');man=load(P/'manifest.json');cid=v['case_id'];pid=v['physical_case_id'];canonical=up['producer_scope_roles']['canonical_native_request_condition_sha256'];legacy=up['producer_scope_roles']['actual_converter_legacy_scope_sha256'];qp=root(1271)/'actual1154-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qp);assert man['assigned_source_worktree_family']==v['assigned_source_worktree_family']==chain['assigned_source_worktree_family']=='F5' and man['physical_case_family']==v['family_id']==chain['family_id']=='F2' and v['review_model']=='GPT-5.6 Luna max' and v['reviewer']=='f5_bed_recovery';assert qi['case_id']==cid==sr['case_id']==chain['case_id']==up['case_id'] and qi['physical_case_id']==pid==sr['physical_case_id']==chain['physical_case_id']==up['physical_case_id'];assert up['main_qi']['path']==str(qp) and up['main_qi']['sha256']==sha(qp)
assert canonical==qi['canonical_actual_native_request_condition_sha256'] and legacy==qi['actual_converter_legacy_scope_sha256'] and canonical!=legacy and not up['producer_scope_roles']['scope_equality_claimed'];assert v['decision']['standalone_first_stage_visual_approved'] and not any(v['decision'][k] for k in ('severe_visual_failure','needs_root_image_intervention','strict_container_guarantee','sub_dp_penetration_absence_claim','numerical_precision_accepted','q_n_granted','q_e_granted','independent_case_count_increment'))
stage=qi['actual_completed_metadata_evidence'];assert up['actual_completed_metadata_evidence']==stage
for fields in stage.values():
 for e in fields.values():assert sha(e['path'])==e['sha256']
 z=load(fields['receipt']['path']);assert (z['status'],z['returncode'])==('completed',0) and z['request']['case_id']==cid
for k in ('execution_receipt','render_report','publish_receipt'):
 e=sr[k];assert sha(e['path'])==e['sha256']
assert up['render_request']['path']==qi['registered_request']['path'] and up['render_request']['sha256']==qi['registered_request']['sha256']==sha(qi['registered_request']['path']);assert sha(up['render_request']['controller_result_path'])==up['render_request']['controller_result_sha256'] and sha(up['render_request']['wrapper_path'])==up['render_request']['wrapper_sha256']
assert qi['frames']==401 and qi['particles']==418104 and qi['all_actual_times_exact_typed_XMF_XML_render'] and qi['all_frames_geometry_velocity_N3_identity_and_finite_active_fields'] and qi['stage1_QI_full_native_identity_and_state_verified'];life=chain['typed_lifecycle'];ql=qi['lifecycle'];assert life['final_missing_particles']==ql['final_missing_particles']==ql['max_missing_per_frame']==9 and life['first_missing_frame']==ql['first_missing_frame']==165 and life['frames_with_any_missing_particle']==ql['frames_with_any_missing_particle']==236 and life['cumulative_particle_frame_omissions']==ql['cumulative_particle_frame_omissions']==1330 and len(ql['final_missing_id_first_producer_attested'])==8 and life['unknown_missing_locations_states_causes'];assert life['final_missing_ids_sha256_producer_attested']==ql['final_missing_ids_sha256_producer_attested'];assert sr['expected_and_actual']['time_window_s']==chain['dimension_and_time']['time_window_s']==qi['actual_time_window_s'];assert up['producer_scope_roles']['native_source_plan_field_present']==qi['native_source_plan_field_present'] and up['producer_scope_roles']['native_source_plan_field_sha256']==qi['native_source_plan_field_sha256'] and up['producer_scope_roles']['xmf_source_plan_field_present']==qi['XMF_source_plan_field_present'] and up['producer_scope_roles']['xmf_source_plan_field_sha256']==qi['XMF_source_plan_field_sha256'];assert not qi['XMF_source_plan_field_present']
sourcebase=D/'families/F2/F2_FIRST48_REMAINING24_SOURCE_ROOT801/root-stage1-f2-first48-remaining24-registered-source-generation-root801/source';mp=sourcebase/'source'/f'{cid}.metadata.json';op=sourcebase/'owners'/f'{cid}.owner.json';meta=load(mp);owner=load(op);gc=load(stage['genuine_gencase']['receipt']['path']);assert sha(mp)==gc['request']['input_sha256'][str(mp)] and sha(op)==gc['request']['input_sha256'][str(op)];assert meta['case_id']==owner['case_id']==cid and meta['physical_case_id']==owner['physical_case_id']==pid and meta['physical_condition_sha256']==owner['physical_condition_sha256']==canonical;params=meta['parameter_values'];motion=meta['motion'];assert params['receiver_x_m']==.61 and params['rotation_duration_s']==motion['rotation_duration_s']==1.05 and motion['static_hold_start_s']==.5 and motion['rotation_stop_s']==1.55 and motion['final_angle_deg']==-105;assert sha(up['source_definition_role']['path'])==up['source_definition_role']['producer_definition_sha256']
pub=load(sr['publish_receipt']['path']);render=load(sr['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sr['render_report']['sha256'];published={e['relative_path']:e for e in pub['files_excluding_receipt']};out=Path(pub['published_output_root']);contacts=png['producer_attested_contact_sheets'];keys=png['producer_attested_keyframes'];assert [e['index'] for e in contacts]==list(range(17)) and [e['frame_index'] for e in keys]==list(range(0,401,50));assert [e['absolute_path'] for e in contacts]==render['outputs']['contact_sheets'] and png['review_coverage']['all_26_images_opened_with_view_image'] and png['review_coverage']['source_agent_computed_png_hashes'] is False
for e in contacts+keys:
 pe=published[str(Path(e['absolute_path']).relative_to(out))];assert e['reviewed'] and sha(e['absolute_path'])==e['sha256']==pe['sha256'] and Path(e['absolute_path']).stat().st_size==e['bytes']==pe['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_226.json';cp=load(cpfile);assert cp['checkpoint']==226 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==286 and cp['accepted_per_family']['F2']==38;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {r.get('physical_case_id',r['case_id']) for r in old};idxp=root(1270)/'full336-current286-actual-final48-delivery-progress-index.json';idx=load(idxp);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical
for row in idx['cases']:
 if row.get('accepted_decision'):assert row.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(v['reviewed_at_utc'].replace('Z','+00:00'))<=now;raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and free>=500
O=H/'root_stage1_source200_assignedF5_actualF2_RX061ROT105_actual1154_full401QI_personal26PNG_quantified9fluid_visual_acceptance_1273';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_227.json';assert not list(H.glob('root*_1273')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'source200-byte-exact-readonly-validation.json';put(vp,{'source_commit':commit,'adopted_source_files':adopted,'source_SHA_before_after':before,'source_bytes_unchanged':True,'validator_returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr,'source_validator_only_checks_package_and_claims_main_independently_verified_actual_stage_refs_and26PNG':True})
ctrl=O/'actual801-controls-and-native-XMF-legacy-role-sidecar.json';put(ctrl,{'source_metadata':ref(mp),'source_owner':ref(op),'own_gencase_receipt':stage['genuine_gencase']['receipt'],'source_metadata_and_owner_bound_to_GenCase_launch':True,'parameter_values':params,'motion_metadata':motion,'motion_DAT_digest_producer_attested_no_payload_IO':True,'actual_native_condition_sha256':canonical,'legacy_typed_render_scope_sha256':legacy,'actual_native_plan_field_present':qi['native_source_plan_field_present'],'actual_native_plan_field_sha256':qi['native_source_plan_field_sha256'],'actual_XMF_plan_field_present':qi['XMF_source_plan_field_present'],'actual_XMF_plan_field_sha256':qi['XMF_source_plan_field_sha256'],'source_render_request_status_false_retained_is_not_execution_status':up['render_request']['status'] is False,'actual_execution_completed_zero':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_assigned_agent_family':'F5','source_family_id_F5_is_assignment_not_actual_case_family':True,'source_review_commit':commit,'source_visual_review':ref(P/'metadata/visual-decision.json'),'source_review_closure':ref(P/'metadata/physical-stage-closure.json'),'source_review_PNG_evidence':ref(P/'metadata/png-visual-evidence.json'),'actual_control_and_scope_roles':ref(ctrl),'independent_full401_QI_proof':ref(qp),'actual_completed_metadata_evidence':stage,'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'lifecycle':ql,'final_UID_sample_count_not_full9':8,'missing_UID_cause_location_state_unknown_preserved':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':png['visual_observations'],'personal_visual_failure_screen':v['decision'],'contact_sheets':contacts,'keyframes':keys,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'source_agent_copied_producer_PNG_hashes_main_independently_computed_all26':True,'all26_PNG_hashes_match_actual_publish':True,'no_zero_fluid_loss_or_strict_container_claim':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source200-actual1154-full401-QI-and-personal-visual-adoption.json';put(proof,{'source_commit':commit,'source_validator':ref(vp),'source_original_bytes_preserved':True,'independent_QI':ref(qp),'new_visual_decision':ref(dp),'actual_controls_and_scope_roles':ref(ctrl),'actual_missing9fluid_and1330_events_unknowns_retained':True,'eight_sample_UIDs_not_complete9':True,'actual26PNG_bound_to_atomic_publish':True,'source_assignment_family_F5_vs_actual_F2_preserved':True,'new_case_credit':1,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp['accepted_per_family']['F2']+=1;newcp.update(checkpoint=227,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=287,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actual F2RX061ROT105 original1154 full401 mainQI1271 + fresh200 personal17contacts9keys accepted;9fluidUID/first165/236frames/1330events and8sample unknowns retained. SourceF5 assignment vsactualF2, nativeplanpresent vsXMFplanabsence, nativecanonical vs typedlegacy separated. Actual1046 F3 and1148F5 verified same live handles, no restart.',authorized_work_state='Active287/336: F2=39,F3=38,F5=19,F6=47,F1/F4/F7=48;49 remaining.');assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==287;newcp['actual_progress']['source200_F2_actual1154_full401_visual_acceptance']=ref(proof);newcp['source_agents']['f5_bed_recovery']='fresh200 accepted287/F2=39; fresh201 F5M098T095 actual1148 same livehandle personal34contacts9keys after atomicpublication';newcp['source_agents']['f6_endpoint_initial_qa']='fresh178 actualfirst24 F2/F3/F6 delivery72 complete pendingmainintegration; fresh177 F3P0800AY0640 original1046 samehandle';newcp['next_executable_tasks']=['Integrate source178 real first24 F2/F3/F6 dynamic delivery72 without duplicatecredit.','After original1046 publication run ownfull836QI1269 and adopt fresh177 personal35contacts9keys.','After original1148 publication run ownfull801QI1272 preserving present native/XMF plan vs distinct bedSourceDef, adopt fresh201 personal34contacts9keys.','Continue remaining original render queue cap2/CPU24, finalF6original951 pending capacity, actualF5prefix19 grows to24.'];put(nextcp,newcp)
idx['previous_index_preserved']=ref(idxp);idx['source_authoritative_checkpoint']=ref(nextcp);idx['at_utc']=now.isoformat();idx['accepted_independent_physical_cases']=287;idx['registered_pending_independent_physical_cases']=49;idx['new_case_credit']=1;targets[0].update(status='visual-approved-in-checkpoint227',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qp));idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if (x.get('physical_case_id') if isinstance(x,dict) else x)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==287;put(O/'full336-current287-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R)),str((root(1154)/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 rx061 rot105 full401 with9 quantified fluid omissions','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':287,'F2':39,'checkpoint':227,'remaining':49,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
