from pathlib import Path
import subprocess,json,hashlib,runpy,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');rel='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_159_m086_identity_adapter_disabled_v1';commit=subprocess.check_output(['git','rev-parse','a3f330e9'],cwd=W,text=True).strip();files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',rel],cwd=W,text=True).splitlines();records=[]
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
for f in files:
 b=subprocess.check_output(['git','show',f'{commit}:{f}'],cwd=W);p=R/f;p.parent.mkdir(parents=True,exist_ok=True);assert not p.exists() or p.read_bytes()==b;p.write_bytes(b);records.append({'path':str(p),'sha256':sha(p)})
P=R/rel;adapter=runpy.run_path(str(P/'workers/identity_bound_bed_audit_fresh159.py'));binding=adapter['adapt_binding'](P/'bindings/M086_T085-identity-bound-bed-binding.json');original=runpy.run_path(str(adapter['ORIGINAL_WORKER']));assert sha(adapter['ORIGINAL_WORKER'])==adapter['ORIGINAL_WORKER_SHA'];error=None
try:original['_verify_bound_metadata'](binding)
except Exception as e:error={'class':type(e).__name__,'message':str(e)}
assert error and error['message']=='F5 case/physical identity mismatch';assert original['CASE_ID']!=binding['case_id']
O=H/'root_stage1_actual159_F5_identity_adapter_source_adoption_metadata_gate_failure_classification_952';O.mkdir(exist_ok=False);proof={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source159_commit':commit,'adopted_files':records,'original_worker':{'path':str(adapter['ORIGINAL_WORKER']),'sha256':sha(adapter['ORIGINAL_WORKER'])},'original_metadata_gate_actually_called':True,'actual_error':error,'original_module_case_id':original['CASE_ID'],'actual_binding_case_id':binding['case_id'],'cause':'fresh159 rebinds binding to actual NEXT34 producer, but leaves delegated original module CASE_ID set to base. Deterministic metadata rejection before science arrays.','source159_preserved_not_enabled':True,'distinct161_repair_requested':'verify original worker SHA and bind only module CASE_ID to true producer; retain all actual receipts and numeric logic; regression must execute delegate metadata gate boundary','grounded_identity_repair_number':1,'max_grounded_repairs':2,'no_science_payload_IO':True,'no_science_job_started':True,'case_credit':0};(O/'actual159-adoption-and-metadata-gate-classification.json').write_text(json.dumps(proof,indent=2)+'\n');(O/'adoption-classification-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(v['path']).relative_to(R)) for v in records]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: preserve F5 identity adapter and classify actual metadata gate before launch','--',*paths],cwd=R,check=True);print({'files':len(records),'actual_metadata_error':error,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
