from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_277.json';cp=load(cpfile);assert cp['checkpoint']==277 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==311
qip=next(root(1363).glob('*proof.json'));qi=load(qip);assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['new_case_credit']==0
for name in ['render_receipt','render_report','render_publish_receipt']:
 e=qi['actual_completed_metadata_evidence'][name];assert sha(e['path'])==e['sha256']
rc=load(qi['actual_completed_metadata_evidence']['render_receipt']['path']);pub=load(qi['actual_completed_metadata_evidence']['render_publish_receipt']['path']);assert rc['status']=='completed' and rc['returncode']==0 and pub['status']=='published_after_atomic_rename' and pub['case_id']==qi['case_id']
F=root(1174);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre)
for e in j.values():
 if isinstance(e,dict) and 'path' in e and 'sha256' in e:assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);n=load(t['source_provenance']['solver_receipt']['path']);nq=n['request'];b=load(load(j['actual_bed_receipt']['path'])['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert n['status']=='completed' and n['returncode']==0
assert (canonical,legacy,sd)==('4e06ddfc9c871e619f543397f8faba245de6e24df33950f0561d34ff6a9eb920','e561820d8792eda4b59e77a36cf41b6b9d07953553851b25eba4ad9938dd64e3','7530ddff20117a6d478fba2fc4ec90a05177a2ffccaec383eaf1fe03fc4139a1')
mask={ns:{k:{'present':k in ob,'value':ob.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,ob in [('native',nq),('XMF',x)]}
for masks in mask.values():assert masks=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}}
assert sha(b['source_definition'])==b['source_definition_sha256']==sd and len({canonical,legacy,sd})==3
live=[]
for original,pid,start in [(1143,621866,'213876084'),(1174,633506,'213987092')]:
 F=root(original);w=load(F/'enabled-render-wrapper.json');P=Path(f'/proc/{pid}');obs=None
 if P.exists():
  st=(P/'stat').read_text().rsplit(')',1)[1].split();assert st[19]==start;cmd=(P/'cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);obs={'pid':pid,'startticks':start,'state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 terminal=F/'controller-result.json';live.append({'original':original,'case_id':w['case_id'],'physical_case_id':w['physical_case_id'],'actual_loaded_wrapper':ref(F/'enabled-render-wrapper.json'),'same_actual_process':obs,'actual_controller_terminal':ref(terminal) if terminal.exists() else None,'case_credit':0,'no_restart':True})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(r['kind'] for r in ld['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ld['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current311_F5_original1188_published_full801QI_source212_visual_active_nextF2_1143_F5_1174_same_live_genuine_plan_namespaces_1369';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_278.json';assert not O.exists() and not np.exists();O.mkdir();pp=O/'current311-F5actual1188-own801QI-nextF2-1143-F5-1174-live-and-plan-role-proof.json';put(pp,{'at_utc':now.isoformat(),'actual_original1188_full801_QI':ref(qip),'actual_original1188_completed0_published':True,'source212_personal34contacts9keys_activated':True,'original_unstarted_F6fresh192_review_transferred_to_F5fresh212_without_duplicate_personal_work':True,'same_actual_next_render_processes':live,'next_originalF5_1174_previsual_dependency_review':ref(pre),'next_originalF5_1174_native_canonical':canonical,'next_originalF5_1174_typed_legacy':legacy,'next_originalF5_1174_bed_SourceDef_FILE':sd,'next_originalF5_1174_actual_native_XMF_plan_field_namespaces':mask,'next_originalF5_1174_XMF_physical_plan_canonical_not_SourceDef':True,'future_own801_QI1371_not_yet_prepared_or_executed':True,'new_case_credit':0,'scientific_payload_IO':False,'no_new_render_or_solver_jobs':True})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=278,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: F5source211 original1164 andF3source177178 original987 personally reviewed and accepted once, total311. OriginalF5 1188 actual0/pub/full801 ownQI1363 completed andsource212 personalreview activated; next originalF5 1174 admitted by unchanged registeredqueue, raw native/XMF physical-plan canonical versus distinct bedSourceDefFILE pinned. F2original1143 full401 metadataQI1366 durable, waiting same livehandle. No scientific reruns or additional cleanup.',authorized_work_state='Active311/336 pending25. F1/F4/F6/F7=48 F2=43 F3=43 F5=33. Source212 personally reviewing publishedF5original1188 afterQI1363. F6source193 boundedwait returned whileF2original1143 samehandlelive; resume afteractual0/pub/QI1366. F3source179 assigned F5original1174, waitingactual0/pub/futureQI1371. Source176 historical42/readinessonly utility preserved; finaldeliveries requireactual48 andindependent mainprimaryintegrity. Homefloor500GiB, cumulativecleanup534.4086GiB preserved.')
new['actual_progress']['actual1188_full801_own_QI']=ref(qip);new['actual_progress']['current311_published1188_QI_nextF2F5_live']=ref(pp);new['source_agents']['f5_bed_recovery']='fresh212 originalF5 1188 actual0/pub/QI1363 supplied, personal34contacts9keys active';new['source_agents']['f6_endpoint_initial_qa']='fresh193 F2original1143 boundedwait returned, re-activate afteractual0/pub/QI1366; fresh192 transferred before any personalwork';new['source_agents']['production_recovery']='fresh179 assigned F5original1174 M102T095 waitingactual0/pub andfutureQI1371; priorfresh177178 accepted'
new['next_executable_tasks']=['Observe same originalF2 1143 PID621866/start213876084; actualcompleted0/pub then Root1365 durable after_original1143_terminal_full401_own_QI.py 1143 1366 once; supply pathSHA andreactivate F6fresh193 personal17contacts9keys.','Adopt source212 F5original1188 afterpersonal34contacts9keys/exactfinalcommit/read-onlyvalidation/ownQI1363, preserving nativephysicalplan canonical versus XMFphysicalplan SourceDefFILE.','Prepare durable own801QI1371 for nextF5original1174 in newRoot1370: native andXMF physicalplans BOTHcanonical4e06, unlike precedingcase; bedSourceDefFILE7530 andtypedlegacye561 remainseparate. Wait samePID633506/start213987092 actual0/pub then ownQI once andsupply source179.','Continue originalregisteredqueues toward336 and finalizeF2/F3/F5 directories at real48 accepted each; source176 referenceassembly followed byindependent fullactualprimary-integrity/runtime-unknown review.','Home500GiB floor, cumulative534.4086GiB cleanupretained, numericalprecision unaccepted QNQE0.'];put(np,new)
ip=root(1368)/'full336-current311-actual-final48-delivery-progress-index.json';idx=load(ip);target=next(r for r in idx['cases'] if r['physical_case_id']==qi['physical_case_id']);assert not target.get('accepted_decision');target.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=ref(qip),current_personal_review_source=212,case_credit=0,prior_controller_observations_are_historical_not_current=True);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[qi['physical_case_id']],current311_published1188_QI_nextF2F5_live=ref(pp));assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==311;put(O/'full336-current311-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: track current311 F5 full801 QI and next F2 F5 original handles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':278,'accepted':311,'pending':25,'live':live,'home_free_GiB':free,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
