from pathlib import Path
import json, hashlib, subprocess, copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003'
root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
pre=Path('/tmp/ds02-next1101-upstream-preflight1426.py');g={'__file__':str(pre)};exec(compile(pre.read_text(),str(pre),'exec'),g)
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_315.json';cp=load(cpfile);assert g['cp']==cp and cp['accepted_per_family']['F3']==47
ip=root(1424)/'full336-current327-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile)
pid=g['pid'];row=next(z for z in idx['cases'] if z['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==g['canonical']
O=H/'root_stage1_current327_lastF3_original1101_full836_UID_N3_native_both_plan_absent_XMF_condition_present_true_parentQA_durable1427_1426';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_316.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1427'));O.mkdir()
entry=O/'after_original1101_terminal_full836_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F3-original1101-full836-own-QI1427.py').read_bytes());compile(entry.read_text(),str(entry),'exec');(O/'upstream-preflight-source.py').write_bytes(pre.read_bytes())
proof=O/'lastF3-original1101-full836-UID-N3-true-QA-native-XMF-plan-roles-and-durable-QI-readiness.json'
put(proof,{'schema':'ds02.lastF3.original1101.full836.previsual-readiness.v1','at_utc':g['now'].isoformat(),'case_id':g['cid'],'physical_case_id':pid,'previsual_dependency_review':ref(g['pre']),'completed_upstream_receipts':g['s'],'typed_XMF_metadata_refs':{k:g['z'][k] for k in ['actual_typed_report','actual_XMF_manifest','actual_XMF_XML']},'genuine_parent_initial_QA_GenCase_and_source704_preparation_refs':g['refs'],'all836_typed_UID_type_N3_finite_monotonic_exact_XMF_times_verified':True,'genuine_completed0_parent_initial_QA_source704_identical_initial_XML_BI4_scope_join_verified':True,'native_initial_XML_BI4_and_changed_forcing_launch_after_input_digests_verified':True,'native_typed_XMF_canonical':g['canonical'],'actual_native_XMF_plan_namespaces':g['mask'],'native_both_plan_fields_true_absence_XMF_condition_plan_present_physical_plan_absent':True,'actual_time_window_s':[g['times'][0],g['times'][-1]],'last_F3_case_unaccepted_count_before_this_package':1,'registered_controller_observation':g['front'],'controller_wait_is_not_completed_render':True,'actual_wrapper_keyframe_indices':g['w']['keyframe_indices'],'durable_entry':ref(entry),'future_ownQI1427_UNEXECUTED_SHA_unknown':True,'command':['python3','-B',str(entry),'1101','1427'],'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(g['raw']);new=copy.deepcopy(cp)
new.update(checkpoint=316,at_utc=g['now'].isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=g['free'],ledger_sha256_at_checkpoint=hashlib.sha256(g['raw']).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=g['ld']['reservations'],attempt_counts=dict(g['ct']),gpu_hours_charged=g['gpu'],cpu_core_hours_charged=g['cpu'],previous_goal_turn_classification='PROGRESS: last unaccepted F3 P1200AY0390 original1101 real native/typed/XMF completed0 verified full836 UID/type/N3/finite monotonic XML exacttimes and parent initialQA/source704 identical initialization scope; native both plan fields absent vs XMF condition7560 present preserved. Existing controller202633/start210026020 confirmed same-live; futureown1427 durable prepared. Original1159 personal review ongoing and1176/1119 render worker handles independently verified live earlier this turn. No new scientific or render job.',authorized_work_state='Active327/336 remaining9. F3=47 and last1101 registered queued; durableown1427 prepared. Actual1159 own1421 complete and personal188/new package active. Original1176 own1423 and original1119 own1425 durable awaiting actual0/pub then delegated review. Final actual primary percase joins still required; no precision credit.')
new['actual_progress']['last_F3_original1101_durable836_QI']=ref(proof)
new['next_executable_tasks'].insert(0,'After lastF3original1101 natural completed0/pub run durableown1427 once, then delegate35contacts and9actualwrapper keys. Deliver actualcomplete F3 final48 from genuine main percase sources, retaining original runtime unknowns and source186187 bounded review time. No duplicate rendering.')
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==327;put(np,new)
row.update(current_upstream_previsual_preparation=ref(proof),future_independent_QI_root=1427,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=g['now'].isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,last_F3_original1101_durable836_QI=ref(proof));assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==327
put(O/'full336-current327-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare last F3 full836 integrity with true parent QA and preserved plan namespaces','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':316,'accepted':327,'lastF3_controller_live':g['front'],'durable_own1427_unexecuted':True,'proof':ref(proof),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
