from pathlib import Path
import json,hashlib,datetime,subprocess,ast
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_F2_actual804_remaining24_initialQA105_registered_CPU2_809';O.mkdir(exist_ok=False)
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
gp=root(804)/'controller-result.json';g=load(gp);assert g['actual_GenCase_pass_count']==g['completed0']==24 and g['pending_held']==0
profile=load(root(801)/'registered-source-generation-request.json');base={k:v for k,v in profile.items() if k.startswith('root_') or k=='resource_window'}
pdir=L/'campaigns/ds-data-02/families/F2/handoff_20261003/root_followup_105_f2_actual_gencase_semantic_adapter_v1/workers';worker=pdir/'fresh105_initial_qa_csv_parser.py';parserbase=pdir/'fresh104_parser_base.py';pv=Path('/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/vendor/official/DualSPHysics_v5.4/bin/linux/PartVTK_linux64');assert sha(pv)=='62630430902484f4aede017108313673fe6414f40fb59b6ae7f14ac23219db00'
(O/'evidence').mkdir();(O/'requests').mkdir();qs=[]
for row in g['results']:
 cid=row['case_id'];r=load(row['actual_receipt']);prep=load(row['prepared_input_report']);qg=load(row['request']);assert (r['status'],r['returncode'])==('completed',0) and r['request_sha256']==sha(row['request']);prefix=prep['prefix'];xml=Path(prefix+'.xml');assert sha(xml)==prep['xml_sha256'] and prep['actual_generated_constants']['data2d']['value']=='false';assert prep['actual_total_particles']==sum(prep['generated_xml_particle_counts'].values()) and prep['generated_xml_particle_counts']['fluid']>0
 ep=O/'evidence'/(cid+'-actual804-gencase-evidence.json');e={'schema':'ds02.f2.stage1.actual804-gencase-evidence.compat105.v1','case_id':cid,'actual_gencase_request':row['request'],'actual_gencase_receipt':row['actual_receipt'],'actual_prepared_input_report':row['prepared_input_report'],'generated_xml_sha256':prep['xml_sha256'],'actual_total_particles':prep['actual_total_particles'],'actual_particle_counts':prep['generated_xml_particle_counts'],'contract_checks':{'root353_solver_dimension_three':True,'actual804_solver_dimension_three':True,'counts_close':True,'generated_xml_digest_matches_prepared_report':True},'legacy_parser_field_semantics':{'root353_solver_dimension_three':'Historical fresh105 parser input field for actual measured producer dimension=3. This sidecar binds completed Root804, and does not claim any Root353 job ran for this new case.'},'scientific_payloads_read_or_hashed_here':False,'native_initial_QA':'pending actual registered PartVTK worker','precision':'not_accepted','independent_case_increment':0};put(ep,e)
 inputs={str(p):sha(p) for p in [worker,parserbase,pv,L/'.venv/bin/python',xml,Path(row['actual_receipt']),Path(row['prepared_input_report']),Path(row['request']),ep,gp,root(803)/'actual-integration-review.json',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',H/'root_stage1_home_floor_inventory_dispatch_142/launch.py',H/'root_stage1_home_floor_inventory_dispatch_142/root_home_floor_inventory_policy.py',H/'root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json']};inputs[prefix+'.bi4']=prep['bi4_sha256']
 for asset in prep['assets']:inputs[asset['copied_to']]=asset['verified_post_gencase_sha256']
 attempt='root-stage1-f2-'+cid.lower()+'-actual804-initial-qa105-root809';ap=D/'families/F2'/cid/attempt;assert not ap.exists()
 q={**base,'schema':'ds02.runner-request.v2','family_id':'F2','case_id':cid,'physical_case_id':qg['physical_case_id'],'physical_condition_sha256':qg['physical_condition_sha256'],'source_plan_physical_condition_sha256':qg['physical_condition_sha256'],'attempt_id':attempt,'attempt_root':str(ap),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':2,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'max_wall_seconds':900,'estimated_storage_bytes':512*1024**2,'command':[str(L/'.venv/bin/python'),str(worker),'--case-id',cid,'--definition',str(xml),'--gencase-receipt',row['actual_receipt'],'--prepared-input-report',row['prepared_input_report'],'--runtime-evidence',str(ep),'--partvtk',str(pv),'--partvtk-output-dir','{attempt_root}/partvtk','--output','{attempt_root}/actual-initial-qa.json'],'input_files':sorted(inputs),'input_sha256':inputs,'expected_particles':prep['actual_total_particles'],'expected_dimension':3,'registered_existing_csv':None,'independent_case_increment':0,'precision_status':'not_accepted','production_approval':'none','producer_science_digests_not_recomputed_by_main':True};qp=O/'requests'/(cid+'-initial-qa-request.json');put(qp,q);qs.append(str(qp))
put(O/'dispatch-config.json',{'requests':qs,'CPU_threads_per_job':2,'maximum_parallel_QA_jobs':1,'reason':'F3 full836 render2×24 and F5 native7×2 leave2 of shared64 cores for QA; no reservation guard bypass','unchanged_parser':str(worker),'expected_actual_QA_cases':24,'independent_case_increment':0})
s=r'''from pathlib import Path
import json,subprocess,time
O=Path(__file__).parent;R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());qs=load(O/'dispatch-config.json')['requests'];rows=[];failed=False
for qp in qs:
 if failed:break
 while sum(x.get('cpu_threads',0) for x in load(D/'runtime/resource-ledger.json')['reservations'])+2>64:time.sleep(2)
 q=load(qp);p=subprocess.run([str(L/'.venv/bin/python'),str(H/'root_stage1_home_floor_inventory_dispatch_142/launch.py'),qp],cwd=L,capture_output=True,text=True);ap=Path(q['attempt_root']);rp=ap/'execution-receipt.json';r=load(rp) if rp.exists() else {};qa=load(ap/'actual-initial-qa.json') if (ap/'actual-initial-qa.json').exists() else {};passed=p.returncode==0 and (r.get('status'),r.get('returncode'))==('completed',0) and qa.get('status')=='pass' and all(qa.get('checks',{}).values());row={'case_id':q['case_id'],'request':qp,'actual_receipt':str(rp),'actual_QA_report':str(ap/'actual-initial-qa.json'),'status':r.get('status'),'returncode':r.get('returncode'),'launcher_returncode':p.returncode,'actual_initial_QA_pass':passed,'independent_case_increment':0,'launcher_error':p.stderr[-1500:]};rows.append(row);print(json.dumps(row),flush=True);failed=not passed
summary={'requested':24,'completed0':sum((x.get('status'),x.get('returncode'))==('completed',0) for x in rows),'actual_initial_QA_pass_count':sum(x['actual_initial_QA_pass'] for x in rows),'pending_held':24-len(rows),'maximum_parallel_QA_jobs':1,'results':rows,'independent_case_increment':0};(O/'controller-result.json').write_text(json.dumps(summary,indent=2)+'\n');raise SystemExit(1 if failed else 0)
'''
ast.parse(s);cp=O/'batch-controller.py';cp.write_text(s);p=subprocess.Popen([str(L/'.venv/bin/python'),str(cp)],cwd=L,stdout=(O/'controller.log').open('ab'),stderr=subprocess.STDOUT,start_new_session=True);fields=(Path('/proc')/str(p.pid)/'stat').read_text().split(') ',1)[1].split();put(O/'controller-launch-process.json',{'pid':p.pid,'proc_start_ticks':fields[19],'controller':str(cp),'controller_sha256':sha(cp),'actual_launched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'detached_parent_session':True});(O/'root-preparation-and-validation.py').write_bytes(Path(__file__).read_bytes());print({'QA_requests':24,'controller_pid':p.pid,'actual804_GenCase_completed0':24})
