from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def put(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='1ca9661ad4a29656b8e2d3d222eb754e5fae359b';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_182_f6_assigned_f2_rx058_rot090_root1099_personal_visual_review_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==3;blobs={};before={}
for name in names:
 b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert (W/name).read_bytes()==b;assert not (R/name).exists() or (R/name).read_bytes()==b;blobs[name]=b;before[name]=sha(W/name)
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh182.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/personal-visual-decision.json');qp=root(1289)/'actual1099-full401-independent-UID-N3-time-scope-QI-proof.json';q=load(qp);c=s['case'];cid=q['case_id'];pid=q['physical_case_id'];canonical=q['canonical_actual_native_request_condition_sha256'];legacy=q['actual_converter_legacy_scope_sha256'];assert s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and s['assigned_family']=='F6' and s['actual_family']=='F2' and c['case_id']==cid and c['physical_case_id']==pid and c['canonical_native_physical_condition_sha256']==canonical and c['typed_legacy_actual_converter_and_xmf_physical_scope_sha256']==legacy and canonical!=legacy
assert s['decision']['status']=='visual-approved-by-delegated-agent' and s['decision']['case_credit']==0 and not s['decision']['q_n_granted'] and not s['decision']['q_e_granted'];assert not any(s['source_boundaries'][k] for k in ['science_payload_read','science_payload_hashed','science_jobs_started','shared_registry_or_ledger_written'])
e=s['evidence'];assert e['main_qi_proof']['path']==str(qp) and e['main_qi_proof']['sha256']==sha(qp)
for v in e.values():check(v)
mapping={'gencase_receipt':('genuine_gencase','receipt'),'generated_xml':('genuine_gencase','generated_xml'),'initial_qa_receipt':('initial_native_qa','receipt'),'initial_qa_report':('initial_native_qa','report'),'native_receipt':('full_native_solver','receipt'),'typed_receipt':('typed_conversion','receipt'),'typed_report':('typed_conversion','report'),'xmf_receipt':('normal_N3_XMF','receipt'),'xmf_manifest':('normal_N3_XMF','manifest'),'xmf_xml':('normal_N3_XMF','xml'),'render_receipt':('full_original_render','receipt'),'render_report':('full_original_render','report'),'publish_receipt':('full_original_render','publish_receipt')}
# Stage naming is read from the independent QI schema; aliases are explicit.
stages=q['actual_completed_metadata_evidence'];aliases={'normal_N3_XMF':'normal_n3_xmf','full_original_render':'full_original_render'}
for name,(stage,field) in mapping.items():
 if stage not in stages:stage=aliases.get(stage,stage)
 if stage not in stages:
  matches=[v for v in stages.values() if isinstance(v,dict) and any(isinstance(z,dict) and z.get('path')==e[name]['path'] for z in v.values())];assert len(matches)==1,(name,list(stages));group=matches[0];matches=[z for z in group.values() if isinstance(z,dict) and z.get('path')==e[name]['path']];assert len(matches)==1;qe=matches[0]
 else:
  group=stages[stage];matches=[z for z in group.values() if isinstance(z,dict) and z.get('path')==e[name]['path']];assert len(matches)==1,(name,list(group));qe=matches[0]
 assert qe['path']==e[name]['path'] and qe['sha256']==e[name]['sha256'];check(qe)
 if name.endswith('_receipt') and name!='publish_receipt':
  rr=load(e[name]['path']);assert (rr['status'],rr['returncode'])==('completed',0) and rr['request']['case_id']==cid
assert q['frames']==401 and q['particles']==418104 and q['all_actual_times_exact_typed_XMF_XML_render'] and q['all_frames_geometry_velocity_N3_identity_and_finite_active_fields'] and q['stage1_QI_full_native_identity_and_state_verified']
assert c['source_plan_field_presence']['native']==q['native_and_XMF_plan_field_namespaces']['native'] and c['source_plan_field_presence']['xmf']==q['native_and_XMF_plan_field_namespaces']['XMF'];assert c['actual_time_s']==q['actual_time_window_s'];life=q['lifecycle']
for k in ['final_missing_particles','final_missing_fraction_initial_fluid','first_missing_frame','max_missing_per_frame','frames_with_any_missing_particle','cumulative_particle_frame_omissions','unknown_missing_locations_states_and_causes']:assert s['lifecycle'][k]==life[k]
assert life['final_missing_particles']==5 and life['first_missing_frame']==159 and life['frames_with_any_missing_particle']==242 and life['cumulative_particle_frame_omissions']==898 and s['lifecycle']['initial_fluid_particles']==21114 and not s['lifecycle']['all_fluid_UIDs_active_or_closed_container_claimed']
r=load(e['render_report']['path']);pub=load(e['publish_receipt']['path']);assert r['frames']==r['source_frames']==401 and r['all_frames_rendered'] and r['actual_times_preserved_exactly'] and r['native_identity_axis_preserved'] and r['nonfinite_active_states']==0 and pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==e['render_report']['sha256'];visual=s['visual_review'];contacts=visual['contact_sheets'];keys=visual['key_frames'];assert visual['personally_viewed_with']=='view_image' and len(contacts)==17 and len(keys)==9 and [x['frame'] for x in keys]==list(range(0,401,50));assert [x['path'] for x in contacts]==r['outputs']['contact_sheets'];published={x['relative_path']:x for x in pub['files_excluding_receipt']};out=Path(pub['published_output_root'])
for v in contacts+keys:
 check(v);z=published[str(Path(v['path']).relative_to(out))];assert z['sha256']==v['sha256'] and z['bytes']==v['bytes']
cf=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_237.json';cp=load(cf);ip=root(1296)/'full336-current293-actual-final48-delivery-progress-index.json';idx=load(ip);assert cp['stage1_visual_accepted_complete_independent_cases']==293 and cp['accepted_per_family']['F2']==39 and idx['source_authoritative_checkpoint']==ref(cf);row=next(x for x in idx['cases'] if x['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical and not any(x.get('accepted_decision') and x.get('native_request_scope',{}).get('sha256')==canonical for x in idx['cases'])
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;vfs=os.statvfs('/home/jade');free=vfs.f_bavail*vfs.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
O=H/'root_stage1_source182_assignedF6_actualF2_RX058ROT090_actual1099_full401QI_personal26PNG_fivefluid_omissions_staleF5block_preserved_visual_acceptance_1299';nf=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_238.json';assert not list(H.glob('root*_1299')) and not nf.exists();now=datetime.datetime.now(datetime.timezone.utc);O.mkdir();adopted=[]
for rel,b in blobs.items():p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
vp=O/'source182-byte-exact-readonly-validation-and-explicit-lifecycle-block-correction.json';put(vp,{'schema':'ds02.source182.actualF2.metadata-authority-sidecar.v1','source_commit':commit,'source_SHA_before_after':before,'source_validator_stdout':rv.stdout,'source_validator_stderr':rv.stderr,'adopted_source_files':adopted,'source_original_bytes_preserved':True,'stale_source_block':{'json_pointer':'/lifecycle_and_limits','original_snapshot':s['lifecycle_and_limits'],'classification':'Copied prior F5 Root1177 block; not actual F2 evidence and not adopted as this case lifecycle authority.'},'actual_F2_authority':{'main_QI':ref(qp),'case_id':cid,'physical_case_id':pid,'actual_time_window_s':q['actual_time_window_s'],'initial_counts':c['declared_counts'],'terminal_counts':c['terminal_render_counts'],'lifecycle':life,'actual_completed_stages':q['actual_completed_metadata_evidence']},'personal_visual_evidence_validated_independently_from_stale_block':True,'all26_published_PNG_SHA_bound_to_atomic_publish':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','assigned_review_family':'F6','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_visual_review':ref(R/prefix/'metadata/personal-visual-decision.json'),'source_metadata_authority_sidecar':ref(vp),'independent_full401_QI':ref(qp),'actual_completed_metadata_evidence':e,'full_native_frames':401,'particles':418104,'actual_physical_window_s':q['actual_time_window_s'],'stage1_QI_full_native_identity_and_state_verified':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'native_and_XMF_plan_field_namespaces':q['native_and_XMF_plan_field_namespaces'],'initial_native_type_counts':q['initial_native_type_counts'],'lifecycle':life,'all_fluid_UIDs_active_or_closed_container_claimed':False,'no_missing_particle_state_reconstructed':True,'no_user_numeric_threshold_inferred':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':visual['observations'],'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source182-actualF2-1099-full401-QI-personal26PNG-adoption.json';put(proof,{'source_sidecar':ref(vp),'independent_QI':ref(qp),'new_visual_decision':ref(dp),'five_fluid_omissions_unknown_cause_preserved':True,'stale_prior_F5_lifecycle_block_not_adopted':True,'case_credit':1,'main_scientific_payload_IO':False});lp=O/'ledger-immutable-snapshot.json';lp.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1;new.update(checkpoint=238,at_utc=now.isoformat(),predecessor=str(cf),predecessor_sha256=sha(cf),stage1_visual_accepted_complete_independent_cases=294,accepted_decisions=cp['accepted_decisions']+[str(dp)],new_accepted_decisions=[str(dp)],active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lp),authorized_work_state='Active294/336; F1/F4/F7=48,F2=40,F3=39,F5=24,F6=47.42 personal visual decisions remain, fullF5actual24 delivery attached.47F6 fulltime rigid export evidence gaps still in work.',previous_goal_turn_classification='PROGRESS: fresh203 F5actual24 accepted and delivered; fresh182 actualF2 original1099 ownfull401QI and personal26PNG accepted294/F2=40 retaining5 fluid omissions and unknown causes, source staleF5 block explicitly excluded via immutable metadata sidecar.')
new['actual_progress']['source182_actualF2_1099_visual_acceptance']=ref(proof);new['source_agents']['f6_endpoint_initial_qa']='fresh182 actualF2 accepted; fresh183 actualF5 M095T100 original1180 personal43PNG after terminal publication';new['next_executable_tasks']=['Observe original1131 M088T095 and1180 M095T100; run prepared ownQI1297/1298 after originalterminalpublication and adopt fresh204/fresh183 personal43PNG.','Integrate fresh168 fulltime FloatingInfo worker/inventory; register tiny47 IBI4 inventory then pilot +46 exports from existing native.','Continue originalF2/F3/F5/F6 remaining42 renderqueue and child personalreviews, preserving distinct conditions and all original negative evidence.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==294;put(nf,new)
idx.update(at_utc=now.isoformat(),previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nf),accepted_independent_physical_cases=294,registered_pending_independent_physical_cases=42,new_case_credit=1);row.update(status='visual-approved-in-checkpoint238',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,actual_full401_QI=ref(qp),precision_status='视觉检查通过、数值精度未验收');idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if (x.get('physical_case_id') if isinstance(x,dict) else x)!=pid];assert sum(bool(x.get('accepted_decision')) for x in idx['cases'])==294;put(O/'full336-current294-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(O.relative_to(R)),str(nf.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 rx058 rot090 preserving fivefluid omissions and stale sourceblock correction','--',*paths],cwd=R,check=True);print({'accepted':294,'F2':40,'remaining':42,'checkpoint':238,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
