from pathlib import Path
import json,hashlib,subprocess,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
old=root(981);cfg=load(old/'controller-config.json');a=load(old/'actual-progress.json');assert len(a['results'])==1 and a['results'][0]['status']=='failed' and a['results'][0]['returncode']==1
rp=Path(a['results'][0]['actual_receipt']);r=load(rp);log=rp.parent/'stdout.log';err=log.read_text();wrong='/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/scripts/l1-resume/artifacts/bi4_dump';correct='/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/campaigns/l1-resume/artifacts/bi4_dump';assert f'upstream decoder is not executable: {wrong}' in err
assert (r['status'],r['returncode'])==('failed',1) and not (rp.parent/'trajectory.h5').exists()
actual=load(Path(load(root(974)/'enabled-typed-request.json')['attempt_root'])/'execution-receipt.json');digest='b8ac8cf4aff68ffd089da6cf3ef19dfd0c6473121475f4c198b720a0ddaa8b2e';assert actual['input_hashes_at_launch'][correct]==actual['input_hashes_after_run'][correct]==sha(correct)==digest and os.access(correct,os.X_OK)
O=H/'root_stage1_F3_actual981_failed_wrong_decoder_CLI_grounded974_binding_repair1_seven_typed157_991';O.mkdir(exist_ok=False);controller=O/'batch-typed-controller.py';controller.write_bytes((old/'batch-typed-controller.py').read_bytes());fair=Path(cfg['fair_dispatch']['path']);proof=O/'actual981-failure-and-grounded974-decoder-CLI-repair.json'
put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_failed_receipt':ref(rp),'actual_failed_stdout':ref(log),'failure_class':'Explicit CLI decoder points to non-existent scripts/l1-resume/artifacts/bi4_dump; not scientific numeric failure','wrong_explicit_decoder_path':wrong,'grounded_actual974_correct_executable':correct,'grounded_actual974_decoder_sha256':digest,'corrected_command_option_only':'--decoder value','correct_tool_added_to_strict_runtime_input_files':True,'repair_number':1,'source124_and_consumed981_unchanged':True,'scientific_worker_unchanged':True,'native_simulations_not_repeated':True,'no_science_payload_IO_by_primary':True,'case_credit':0})
(O/'requests').mkdir();qs=[];rows=[]
for qp in cfg['requests']:
 q=load(qp);assert sha(qp)==cfg['request_sha256'][qp];cmd=q['command'].copy();assert cmd[cmd.index('--decoder')+1]==wrong;cmd[cmd.index('--decoder')+1]=correct
 nref=q['actual_native_dependency']['receipt'];np=nref['path'] if isinstance(nref,dict) else nref;n=load(np);assert (n['status'],n['returncode'])==('completed',0)
 aid=q['attempt_id'].replace('root981','root991-decoder-CLI-repair1');ar=D/'families/F3'/q['case_id']/aid;assert not ar.exists();current=f"F3/{q['case_id']}/{aid}";cmd[cmd.index('--current-attempt-id')+1]=current;cmd[cmd.index('--staging-root')+1]=cmd[cmd.index('--staging-root')+1].replace('root981','root991')
 md=q['input_sha256'].copy();md[correct]=digest
 for p in [qp,proof,controller,fair]:md[str(p)]=sha(p)
 for p,h in md.items():
  if Path(p).suffix in {'.json','.xml','.py','.md','.sh'}:assert sha(p)==h
 assert sha(cmd[1])=='37fe7eaff4405e9ba6d9b7f666a53d7c02ee65fc6f30992fc1a8fdb0d8a61b11'
 q.update(attempt_id=aid,attempt_root=str(ar),current_attempt_id=current,command=cmd,input_files=sorted(md),input_sha256=md,root_actual_decoder_cli_repair1=ref(proof),root_original_consumed_request=ref(qp),case_credit=0)
 new=O/'requests'/(q['case_id']+'-enabled-typed-request.json');put(new,q);qs.append(str(new));rows.append({'case_id':q['case_id'],'enabled_request':ref(new),'actual_native_receipt':ref(np),'science_recipe_unchanged_except_decoder_tool_path':True})
put(O/'controller-config.json',{**cfg,'requests':qs,'request_sha256':{p:sha(p) for p in qs}});put(O/'seven-case-primary-metadata-closure.json',{'cases':rows,'repair1_actual974_tool_metadata_grounded':True,'future_H5_hashes_not_invented':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: preserve actual F3 decoder CLI failure and register seven grounded tool-binding successors','--',*paths],cwd=R,check=True);print({'root':str(O),'cases':len(qs),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
