from pathlib import Path
import json,hashlib,datetime,time,subprocess,fcntl,shutil
O=Path(__file__).parent;R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');SCIENCE={'.h5','.hdf5','.bi4','.ibi4','.dat','.csv','.vtk','.vtu','.npy','.npz'}
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in SCIENCE;return hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,d):Path(p).write_text(json.dumps(d,indent=2)+'\n')
def live(c):
 p=Path('/proc')/str(c['pid'])
 if not p.exists():return False
 f=(p/'stat').read_text().split(') ',1)[1].split();return f[0]!='Z' and f[19]==c['proc_start_ticks']
c=load(O/'dispatch-config.json');source=load(c['actual_source_generation_report']);byid={x['case_id']:x for x in source['cases']};nc=load(c['native_controller']);np=Path(c['native_requests_directory']);base=load(c['cpu_profile_request']);profile={k:v for k,v in base.items() if k.startswith('root_') or k=='resource_window'};keys=('family_id','physical_case_id','lineage_group_id','paired_background_id','mechanism_id','geometry_family_id','geometry','control_family_id','gravity_m_s2','density_kg_m3','parameters','initial_state','continuum_geometry');results=[];done=set(x['case_id'] for x in load(O/'preserved-first3-and-capacity-refusal-proof.json')['successful_existing3']);assert len(done)==3;failed=False
while len(done)<24 and not failed:
 ready=[]
 for qp in np.glob('*request.json'):
  q=load(qp);cid=q['case_id'];rp=Path(q['attempt_root'])/'execution-receipt.json'
  if cid in done or not rp.exists():continue
  r=load(rp)
  if (r['status'],r.get('returncode'))==('completed',0):ready.append((qp,q,rp))
  elif r['status'] in ['failed','terminated','aborted']:failed=True;put(O/'actual-native-upstream-failure-hold.json',{'receipt':str(rp),'status':r['status'],'no_native_restart':True})
 if failed:break
 if not ready:
  if not live(nc):
   assert Path(c['native_controller_result']).exists(),'Actual native controller missing without terminal evidence; no new conversion launch'
   nr=load(c['native_controller_result']);assert nr['actual_full401_native_pass_count']==24,'Upstream full401 batch incomplete'
  time.sleep(3);continue
 qp,q,rp=sorted(ready,key=lambda x:x[1]['case_id'])[0];cid=q['case_id'];src=byid[cid];meta=load(src['metadata']['path']);assert sha(src['metadata']['path'])==src['metadata']['sha256'];prefix=q['command'][1];gp=Path(prefix).parent;prep=gp/'prepared-input-report.json';g=load(prep);xml=Path(prefix+'.xml');assert sha(xml)==g['xml_sha256'];assert g['actual_total_particles']==418104 and g['generated_xml_particle_counts']['fluid']==21114;qrp=Path(q['initial_qa_receipt']);qa=Path(q['initial_qa_report']);assert (load(qrp)['status'],load(qrp)['returncode'])==('completed',0) and load(qa)['status']=='pass';assert len(list((Path(q['attempt_root'])/'solver_output/data').glob('Part_*.bi4')))==401
 owner={'schema':'ds02.f2.stage1.actual812-typed-provenance-owner.v1','family_id':'F2','case_id':cid,'physical_case_id':src['physical_case_id'],'physical_condition_sha256':src['physical_condition_sha256'],'source_plan_physical_condition_sha256':src['physical_condition_sha256'],'geometry':meta['geometry'],'initial_state':meta['initial_state'],'continuum_geometry':{k:meta['physical_condition'][k] for k in ['cup_low_m','cup_size_m','receiver_low_m','receiver_size_m','tray_low_m','tray_size_m']},'mechanism_id':'offset_spill','geometry_family_id':meta['geometry_family_id'],'control_family_id':meta['control_family_id'],'lineage_group_id':meta['lineage_group_id'],'gravity_m_s2':[0,0,-9.81],'density_kg_m3':1000,'parameters':{'receiver_x_m':src['receiver_x_m'],'rotation_duration_s':src['rotation_duration_s'],'rotation_final_angle_deg':-105,'source_motion_sha256':src['motion']['sha256'],'native_control_interpolation':'piecewise linear'},'source_canonical_condition':meta['physical_condition'],'actual_GenCase_receipt':q['gencase_receipt'],'actual_native_receipt':str(rp),'actual_initial_QA_receipt':str(qrp),'scientific_payloads_read_or_hashed_by_owner_builder':False,'q_n':'not_granted','future_conversion_report_sha256':None,'future_trajectory_h5_sha256':None}
 legacy={'schema':'legacy-owner-scope.v0','semantic_binding_status':'legacy_incomplete; no cross-resolution physical claim',**{k:owner[k] for k in keys if k in owner}};ld=hashlib.sha256(json.dumps(legacy,sort_keys=True,separators=(',',':')).encode()).hexdigest();owner['prospective_legacy_converter_scope_sha256']=ld;op=O/'owners'/(cid+'-actual-native-owner.json');assert not op.exists();put(op,owner)
 converter=L/'scripts/ds_data02_nvme_convert_v1.py';direct=L/'scripts/ds_data02_direct_convert.py';audit=L/'scripts/ds_data02_f3_nvme_input_audit_v1.py';decoder=Path('/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/campaigns/l1-resume/artifacts/bi4_dump');pv=Path('/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/vendor/official/DualSPHysics_v5.4/bin/linux/PartVTK_linux64');md={str(p):sha(p) for p in [qp,rp,prep,xml,qrp,qa,Path(src['metadata']['path']),Path(src['owner']['path']),op,O/'dispatch-config.json',O/'preserved-first3-and-capacity-refusal-proof.json',Path(__file__),Path(c['actual_source_generation_report']),Path(c['actual_visual_range_review']),converter,direct,audit,decoder,pv,L/'.venv/bin/python',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',H/'root_stage1_home_floor_inventory_dispatch_142/launch.py',H/'root_stage1_home_floor_inventory_dispatch_142/root_home_floor_inventory_policy.py',H/'root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json']};md[prefix+'.bi4']=g['bi4_sha256']
 for asset in g['assets']:md[asset['copied_to']]=asset['verified_post_gencase_sha256']
 attempt='root-stage1-f2-'+cid.lower()+'-actual812-full401-typed-nvme-Home-admission-root891';ap=D/'families/F2'/cid/attempt;assert not ap.exists();data=Path(q['attempt_root'])/'solver_output/data';cmd=[str(L/'.venv/bin/python'),str(converter),'--staging-root','/tmp/ds02-nvme-conversion','--staging-limit-bytes',str(24*1024**3),'--','--data-root',str(data),'--generated-xml',str(xml),'--output','{attempt_root}/trajectory.h5','--report','{attempt_root}/conversion-report.json','--solver-log',str(data.parent/'Run.out'),'--solver-receipt',str(rp),'--gencase-receipt',q['gencase_receipt'],'--decoder',str(decoder),'--partvtk',str(pv),'--validation-dir','{attempt_root}/partvtk-validation','--owner-metadata',str(op),'--particle-chunk','65536'];tq={**profile,'schema':'ds02.runner-request.v2','family_id':'F2','case_id':cid,'physical_case_id':src['physical_case_id'],'physical_condition_sha256':src['physical_condition_sha256'],'actual_converter_scope_sha256_prospective':ld,'attempt_id':attempt,'attempt_root':str(ap),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':2,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'max_wall_seconds':7200,'estimated_storage_bytes':32*1024**3,'command':cmd,'input_files':sorted(md),'input_sha256':md,'independent_case_increment':0,'production_approval':'none','numerical_precision_status':'not_accepted','expected_frames':401,'expected_particles':418104,'owner_metadata':str(op),'native_receipt':str(rp),'gencase_receipt':q['gencase_receipt'],'source_canonical_vs_legacy_scopes_distinct':True};tqp=O/'requests'/(cid+'-typed-request.json');put(tqp,tq)
 with Path(c['shared_conversion_dispatch_lock']).open('a') as lock:
  fcntl.flock(lock,fcntl.LOCK_EX)
  while True:
   ledger=load(D/'runtime/resource-ledger.json');reserved=sum(x.get('new_storage_bytes',0) for x in ledger['reservations'])
   if sum(x.get('cpu_threads',0) for x in ledger['reservations'])+4<=64 and shutil.disk_usage('/home/jade').free-reserved-tq['estimated_storage_bytes']-16*1024**3>=ledger['limits']['home_min_free_bytes']:break
   time.sleep(3)
  p=subprocess.run([str(L/'.venv/bin/python'),str(H/'root_stage1_home_floor_inventory_dispatch_142/launch.py'),str(tqp)],cwd=L,text=True,capture_output=True)
 trp=ap/'execution-receipt.json';tr=load(trp) if trp.exists() else {};converted=load(ap/'conversion-report.json') if (ap/'conversion-report.json').exists() else {};passed=(tr.get('status'),tr.get('returncode'))==('completed',0) and p.returncode==0 and converted.get('conversion_status')=='completed' and converted.get('frames')==401 and converted.get('particles')==418104 and converted['solver_dimension']['solver_dimension']==3 and converted['partvtk_validation']['all_passed'] and converted['hash_scopes']['physical_condition_sha256']==ld and converted['time_evidence']['last_s']>=4;out={'case_id':cid,'request':str(tqp),'actual_receipt':str(trp),'actual_conversion_report':str(ap/'conversion-report.json'),'status':tr.get('status'),'returncode':tr.get('returncode'),'launcher_returncode':p.returncode,'actual_full401_typed_pass':passed,'source_canonical_condition_sha256':src['physical_condition_sha256'],'actual_converter_legacy_scope_sha256':ld,'independent_case_increment':0,'launcher_error':p.stderr[-1500:]};results.append(out);print(json.dumps(out),flush=True);done.add(cid);failed=not passed
summary={'requested':21,'existing3_preserved_without_rerun':True,'completed0':sum((x['status'],x['returncode'])==('completed',0) for x in results),'actual_full401_typed_pass_count':sum(x['actual_full401_typed_pass'] for x in results),'pending_held':24-len(done),'global_new_conversion_cap':1,'CPU_threads_per_job':2,'results':results,'upstream_failure_hold':failed,'independent_case_increment':0};put(O/'controller-result.json',summary);raise SystemExit(1 if failed else 0)
