from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.py','.md','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'],e['path']
def same(a,b):return all(a[k]==b[k] for k in ['path','sha256'])
def parse(t):return datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',t).replace('Z','+00:00'))
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='9ba0c35f9f003d2b78f6c9b0054414cfa19fb085';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob('root_followup_229_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==8
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names};assert all((W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b) for n,b in blobs.items());before={n:sha(W/n) for n in names};man=load(P/'manifest.json');assert {str(prefix/e['path']) for e in man['files']}==set(names)-{str(prefix/'manifest.json')} and man['manifest_excludes_self']
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh229.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1427)/'actual1101-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';assert sha(qip)=='2d764fca467c180ac070e5f7d9e07e13d77a422c72aaf0bc7f932fd7ef8398a5';qi=load(qip);s=load(P/'metadata/visual-decision.json');sr=load(P/'metadata/actual-render-metadata.json');ev=load(P/'metadata/png-visual-evidence.json');up=load(P/'metadata/upstream-evidence.json');cid=qi['case_id'];pid=qi['physical_case_id']
assert all(z['case_id']==cid and z['physical_case_id']==pid for z in [s,sr,ev,up]);assert same(s['qi_reference'],ref(qip)) and same(up['main_qi'],ref(qip));assert s['reviewer']['model']=='gpt-5.6-luna/max' and not s['reviewer']['recursive_delegation'];assert s['decision']['standalone_first_stage_visual_approved'] and s['decision']['coherent_full_time_wave_mechanism_seen'] and not any(s['decision'][k] for k in ['severe_visual_failure','needs_root_image_intervention','numerical_precision_accepted','q_n_granted','q_e_granted','independent_case_count_increment'])
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'];er={'native_receipt':qi['actual_completed_receipts']['native'],'typed_receipt':qi['actual_completed_receipts']['typed'],'XMF_receipt':qi['actual_completed_receipts']['xmf'],'render_receipt':qi['actual_completed_receipts']['render'],'typed_report':qi['typed_report'],'XMF_manifest':qi['XMF_manifest'],'XMF_XML':qi['XMF_XML'],'render_report':qi['render_report'],'render_publish_receipt':qi['publish'],'parent_initial_QA_report':qi['initial_parent_QA_report'],'parent_initial_QA_receipt':qi['initial_parent_QA_receipt'],'source_preparation_report':qi['source_preparation_report']}
for e in er.values():check(e)
aliases={'xmf_receipt':'XMF_receipt','xmf_manifest':'XMF_manifest','xmf_xml':'XMF_XML','parent_initial_qa_report':'parent_initial_QA_report','parent_initial_qa_receipt':'parent_initial_QA_receipt'}
for k,e in up['actual_completed_metadata_evidence'].items():assert same(e,er[aliases.get(k,k)])
assert same(sr['execution_receipt'],er['render_receipt']) and same(sr['render_report'],er['render_report']) and same(sr['publish_receipt'],er['render_publish_receipt'])
n=load(er['native_receipt']['path']);t=load(er['typed_report']['path']);x=load(er['XMF_manifest']['path']);r=load(er['render_report']['path']);rc=load(er['render_receipt']['path']);pub=load(er['render_publish_receipt']['path']);canonical=qi['native_request_condition_sha256'];assert canonical==n['request']['physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']==sr['scope_roles']['canonical_physical_condition_sha256']
for k in ['native_receipt','typed_receipt','XMF_receipt','render_receipt']:j=load(er[k]['path']);assert (j['status'],j['returncode'])==('completed',0) and j['request']['case_id']==cid
masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces']==sr['scope_roles']['actual_native_XMF_plan_field_namespaces'];assert qi['actual_time_window_s']==sr['expected_and_actual']['time_window_s']==[0.0,8.350008849684302]
reviewed=s['reviewer']['reviewed_at_utc'];assert reviewed==sr['personal_review_scope']['reviewed_at_utc'] and parse(rc['finished_at_utc'])<=parse(reviewed)<=datetime.datetime.now(datetime.timezone.utc);contacts=ev['producer_attested_contact_sheets'];keys=ev['producer_attested_keyframes'];assert len(contacts)==35 and len(keys)==9 and [e['frame_index'] for e in keys]==[0,104,208,312,417,521,626,730,835]
assert sr['personal_review_scope']['reviewed_png_count']==44 and all(e['reviewed'] and e['review_mode']=='view_image' for e in contacts+keys);assert not ev['review_coverage']['source_agent_computed_png_hashes'] and not any(sr['source_agent_science_payload_io'][k] for k in ['raw_h5_bi4_csv_dat_vtk_read','raw_h5_bi4_csv_dat_vtk_hash','scientific_job_started','shared_state_written'])
out=Path(pub['published_output_root']);pf={e['relative_path']:e for e in pub['files_excluding_receipt']};assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['render_report']['path']);jc=[];jk=[]
for e,group in [(e,jc) for e in contacts]+[(e,jk) for e in keys]:
 p=Path(e['absolute_path']);rel=str(p.relative_to(out));dg=sha(p);assert rel==e['relative_path'] and dg==e['sha256']==pf[rel]['sha256'] and p.stat().st_size==e['bytes']==pf[rel]['bytes'];j={**e,'path':str(p),'main_actual_PNG_SHA_verified':True,'viewed':True,'view_method':'view_image'}
 if group is jk:j['frame']=e['frame_index']
 group.append(j)
assert [e['path'] for e in jc]==r['outputs']['contact_sheets'];nav=[]
for frame in [0,100,200,300,400,500,600,700,835]:
 p=out/f'frames/frame_{frame:04d}.png';dg=sha(p);assert dg==pf[str(p.relative_to(out))]['sha256'];nav.append({'path':str(p),'sha256':dg,'bytes':p.stat().st_size,'frame':frame,'actual_time_s':x['actual_time_s'][frame],'role':'published navigation; no new personal review'})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_331.json';cp=load(cpfile);ip=root(1446)/'full336-current334-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==334 and cp['accepted_per_family']['F3']==47;row=next(r for r in idx['cases'] if r['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
oldref=cp['actual_progress']['F3_current47_actual_primary_delivery'];check(oldref);old=load(oldref['path']);check(old['main_independent_verification']);oldrows=old['accepted47_actual_primary_rows'];assert len(oldrows)==47;mem=old['membership'];assert pid in mem['registered_final48_physical_case_ids'] and pid not in {r['physical_case_id'] for r in oldrows}
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_source229_lastF3_actual1101_personal44PNG_full836QI_F3final48_primary_native_both_plan_ABS_XMF_condition_present_1449';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_332.json';assert not O.exists() and not np.exists();O.mkdir()
for name,b in blobs.items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
cv=subprocess.run(['python3','-B',str(R/prefix/'scripts/validate_fresh229.py')],capture_output=True,text=True);assert cv.returncode==0,(cv.stdout,cv.stderr);assert all((R/n).read_bytes()==b and (W/n).read_bytes()==b for n,b in blobs.items())
proof=O/'source229-personal44PNG-main-QI1427-and-finalF3primary48-proof.json';put(proof,{'at_utc':now.isoformat(),'source_commit':commit,'source_exact_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'copied_validator_stdout':cv.stdout,'full836_own_QI':ref(qip),'main44_personally_reviewed_PNG_SHA_actual_publisher_match':True,'personal_UTC':reviewed,'navigation9_PNG_SHA_actual_publisher_match':True,'actual_native_XMF_plan_field_namespaces':masks,'previous47_rows_copied_exactly_not_recertified':True,'original154_typed_runtime_unknown_and_recovery_role_clarification':cp['actual_progress'].get('F3_current47_original154_typed_recovery_role_clarification'),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/(pid+'-delegated-visual-decision.json');put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':canonical,'source_review_commit':commit,'source_review_assigned_family':'F5','source_personal_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'source_review_closure':ref(proof),'independent_full836_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':836,'particle_count':179208,'initial_fluid_particles':67500,'actual_type_counts':{'fixed':111708,'moving':0,'floating':0,'fluid':67500},'actual_physical_window_s':qi['actual_time_window_s'],'all836_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':masks,'strict_container_guarantee':False,'subDP_precision_not_claimed':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':35,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':jc,'keyframes':jk,'visual_observations':s['visual_summary'],'visual_limits':s['evidence_limits'],'main_all44_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
hp=t['output_hdf5'];hm={stage:{'present':hp in rc[field],'value':rc[field].get(hp)} for stage,field in [('launch','input_hashes_at_launch'),('after','input_hashes_after_run')]};assert all(v['present'] and v['value']==t['output_sha256'] for v in hm.values())
products=copy.deepcopy(oldrows)+[{'family_id':'F3','case_id':cid,'physical_case_id':pid,'accepted_visual_decision':ref(dp),'own_completed_full836_QI':ref(qip),'primary_metadata':er,'ParaView_open_XMF':er['XMF_XML'],'actual_time_window_s':qi['actual_time_window_s'],'frames':836,'particles':179208,'all836_UID_type_N3_exact_native_times_render_identity_and_finite_aggregate_verified':True,'initial_geometry_QA_join':{'report':qi['initial_parent_QA_report'],'receipt':qi['initial_parent_QA_receipt'],'shared_parent_geometry_and_initial_BI4_launch_digest_verified_in_own_QI':True,'not_independent_percase_forcing_QA':True},'actual_native_runtime_status':'completed','actual_native_runtime_returncode_field_present':True,'actual_native_runtime_returncode':0,'actual_native_physical_case_id_field_present':True,'actual_native_physical_case_id':pid,'actual_native_condition_sha256':canonical,'actual_XMF_condition_sha256':x['physical_condition_sha256'],'actual_native_XMF_plan_field_namespaces':masks,'native_fields_not_backfilled':True,'render_H5_launch_after_attestation_presence':hm,'atomic_publish_receipt':er['render_publish_receipt'],'atomic_publish_receipt_actual_field_absent':False,'contacts35_actual_SHA_verified':jc,'source_enumerated_keys_preserved':jk,'source_key_field_absence_preserved':False,'navigation_keys9_actual_SHA_verified':nav,'new_case_credit':0,'new_personal_review':False,'Q_N':0,'Q_E':0,'precision_status':'视觉检查通过、数值精度未验收'}];assert products[:47]==oldrows and len(products)==48 and {r['physical_case_id'] for r in products}==set(mem['registered_final48_physical_case_ids'])
product=O/'F3-FINAL48-COMPLETE-ACTUAL836-PRIMARY-DELIVERY.json';put(product,{'schema':'ds02.main.F3.actual-final48-complete-primary.v1','at_utc':now.isoformat(),'predecessor_actual47_product':oldref,'main_independent_verification':ref(proof),'membership':mem,'accepted48_actual_primary_rows':products,'pending_cases':[],'delivery_complete':True,'accepted48_primary_bindings_complete':True,'all48_initial_QA_is_shared_geometry_reuse_not_independent_percase_forcing_QA':True,'original_native_runtime_unknown_and_typed154_recovery_and_legacy_pub_H5_limits_preserved':True,'original154_clarification':cp['actual_progress'].get('F3_current47_original154_typed_recovery_role_clarification'),'new_case_credit':0,'Q_N':0,'Q_E':0,'scientific_payload_IO':False})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F3']+=1;new.update(checkpoint=332,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=335,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: two F5 cases accepted334 and actual47 primary delivered, F2 final48 primary delivered; F3last full836 personally44PNG accepted335 and actualF3final48 primary delivered, lastF5actual1149 naturally completed801QI1447 pending personal206.',authorized_work_state='Active335/336: six families final48 accepted/primary delivered; F5=47 and last1149 completed0/pub/full801QI1447 pending personal206. Goal not complete; final global336 direct file delivery and requirement/physical-distinction audits still required.')
new['actual_progress']['F3_final48_complete_actual_primary_delivery']=ref(product);new['actual_progress']['source229_lastF3_actual1101_visual_acceptance']=ref(dp);new['next_executable_tasks'].insert(0,'Adopt F5personal206 with own1447 QI; extend actualF5primary47 to48; complete actual global336 ParaView navigation + physical-distinction194 and explicit requirement230 completion audits.')
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==335;put(np,new);row.update(status='visual-approved-in-checkpoint332',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,actual_full836_QI=ref(qip),precision_status='视觉检查通过、数值精度未验收');last=next(r for r in idx['cases'] if not r.get('accepted_decision'));f5qi=root(1447)/'actual1149-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';check(ref(f5qi));assert load(f5qi)['physical_case_id']==last['physical_case_id'];last.update(actual_full801_QI=ref(f5qi),personal_visual_status='pending fresh206 personal34contacts9keys')
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=335,registered_pending_independent_physical_cases=1,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[last['physical_case_id']];idx['F3_final48_complete_actual_primary_delivery']=ref(product);assert sum(bool(r.get('accepted_decision')) for r in idx['cases'])==335;put(O/'full336-current335-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('最后F3原1101已通过836帧Q-I与源229个人35总览+9关键帧视觉检查，实际F3最终48主文件完成，总数335/336。保留native两个计划字段缺失、XMF条件计划7560独立值和物理计划缺失、旧native和typed154原运行未知及恢复记录、legacy发布与H5 attestation缺失。严格容器、subDP和数值精度未验收；共享初态几何QA不等于独立forcing QA。最后F5实际1149已801QI1447但个人206尚待接收。\n');paths0=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths0],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept last F3 personal44PNG and deliver actual final48 primary836 at335','--',*paths0],cwd=R,check=True);print(json.dumps({'checkpoint':332,'accepted':335,'F3_primary':48,'pendingF5':1,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
