from pathlib import Path
import json,hashlib,subprocess,datetime,sys,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());producer=int(sys.argv[1]);num=int(sys.argv[2]);suffixes=sys.argv[3:];assert producer in [978,991]
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.txt','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/f'root_stage1_F3_P1200_actual{producer}_{len(suffixes)}_completed_full836_typed_original104_N3_XMF_CPU2_{num}';O.mkdir(exist_ok=False);(O/'requests').mkdir();(O/'bindings').mkdir()
controller=O/'batch-xmf-controller.py';controller.write_bytes((root(1014)/'batch-xmf-controller.py').read_bytes());base=load(root(977)/'enabled-full836-xmf-request.json');worker=Path(base['command'][1]);assert sha(worker)=='da50e26d5322b1b6f1539bca3109dfc115164427b37e1b2f86f56b153f56b0b0';fair=root(928)/'fair_CPU_dispatch.py'
c=load(root(producer)/'controller-config.json');sq={load(p)['case_id']:p for p in c['requests']};rows={z['case_id']:z for z in load(root(producer)/'actual-progress.json')['results']};cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_163.json');ids={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};qs=[];proofs=[]
for suffix in suffixes:
 cid=f'F3_STAGE1_DP006_P1200_AY{suffix}';sp=Path(sq[cid]);tq=load(sp);row=rows[cid];assert row['status']=='completed' and row['returncode']==0
 tr=Path(tq['attempt_root'])/'execution-receipt.json';tp=tr.parent/'conversion-report.json';rec=load(tr);t=load(tp);np=Path(t['source_provenance']['solver_receipt']['path']);nr=load(np)
 assert all((rr['status'],rr['returncode'])==('completed',0) for rr in [rec,nr]) and rec['request_sha256']==sha(sp);assert tq['case_id']==cid and tq['physical_case_id']==nr['request']['physical_case_id'] not in ids
 assert t['conversion_status']=='completed' and t['frames']==836 and t['particles']==179208 and t['solver_dimension']['solver_dimension']==3 and t['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1';scope=t['hash_scopes']['physical_condition_sha256'];pid=nr['request']['physical_case_id'];assert scope==nr['request']['physical_condition_sha256']==tq['physical_condition_sha256'] and t['hash_scopes']['physical_condition']['physical_case_id']==pid
 assert t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']) and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
 md={str(sp):sha(sp),str(tr):sha(tr),str(tp):sha(tp)}
 for k in ['solver_receipt','gencase_receipt','generated_xml','owner_metadata']:
  p=t['source_provenance'][k];assert sha(p['path'])==p['sha256'];md[p['path']]=p['sha256']
 owner=load(t['source_provenance']['owner_metadata']['path']);assert owner['physical_binding']==nr['request']['physical_binding']==t['hash_scopes']['physical_condition'];assert owner['physical_condition_sha256']==scope
 assert nr['request']['nominal_pitch_multiplier']==1.2 and nr['request']['transverse_amplitude_m_s2']==int(suffix)/1000
 assert t['output_hdf5']==str(tr.parent/'trajectory.h5') and Path(t['output_hdf5']).stat().st_size<4*2**30 and len(t['output_sha256'])==64
 fs=t['lifecycle']['frame_summary'];assert len(fs)==836 and fs[0]['time']==0 and fs[-1]['time']>=8.35 and all(a['time']<z['time'] for a,z in zip(fs,fs[1:]));assert all(f['frame']==i and f['active_particles']==179208 and f['missing_particles']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500} for i,f in enumerate(fs))
 data=Path(t['source_provenance']['data_root']);assert len([p for p in data.glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name)])==836
 aid=f'root-stage1-f3-p1200-ay{suffix}-actual{producer}-full836-original104-XMF-root{num}';out=D/'families/F3'/cid/aid;assert not out.exists()
 b={'schema':'ds02.f3.actual-completed-full836-v1-typed-to-XMF-binding.v1','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':scope,'producer_scope_schema':'ds-data-02.physical-binding.v1','actual_converter_scope_sha256':scope,'canonical_source_physical_condition_sha256':nr['request']['physical_condition_sha256'],'source_physical_condition_sha256':nr['request']['physical_condition_sha256'],'source_plan_condition_sha256':tq.get('source_plan_scope_sha256'),'typed_receipt':str(tr),'typed_receipt_sha256':sha(tr),'native_receipt':str(np),'native_receipt_sha256':sha(np),'conversion_report':str(tp),'conversion_report_sha256':sha(tp),'trajectory_h5':t['output_hdf5'],'trajectory_h5_sha256':t['output_sha256'],'expected_frames':836,'expected_particles':179208,'physical_window_s':[0,8.35],'bound_metadata_sha256':md.copy(),'arrays_read':False,'dimension':3,'n3_vector_spec':{'dynamic_shape':'[frames, particles, 3]','components':['x','y','z']},'disabled':False,'source_only':False,'launch_allowed':True,'execution_allowed':True,'future_outputs':{'execution_receipt':str(out/'execution-receipt.json'),'execution_receipt_sha256':None,'manifest':str(out/'xdmf/manifest.json'),'manifest_sha256':None,'xdmf':str(out/'xdmf/case.xmf'),'xdmf_sha256':None},'case_credit':0}
 bp=O/'bindings'/(cid+'-full836-XMF-binding.json');put(bp,b)
 for p in [bp,worker,controller,fair,L/'scripts/ds_data02_strict_dispatch_v1.py',L/'scripts/ds_data02_runtime_v2.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json']:md[str(p)]=sha(p)
 md[t['output_hdf5']]=t['output_sha256'];py=str(L/'.venv/bin/python');md[py]=rec['input_hashes_at_launch'][str(Path(py).resolve())];assert md[py]==rec['input_hashes_after_run'][str(Path(py).resolve())]
 q={k:base[k] for k in ['schema','launch_owner','cwd','worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']};q.update(kind='cpu',cpu_task_kind='audit',cpu_threads=2,max_wall_seconds=7200,estimated_storage_bytes=2**30,family_id='F3',case_id=cid,physical_case_id=pid,physical_condition_sha256=scope,attempt_id=aid,attempt_root=str(out),command=[py,str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xdmf'],disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,input_files=sorted(md),input_sha256=md,actual_typed_H5_SHA_from_producer_only=t['output_sha256'],full836_N3_authorized=True,q_n_granted=False,q_e_granted=False,case_credit=0)
 qp=O/'requests'/(cid+'-enabled-full836-XMF-request.json');put(qp,q);qs.append(str(qp));proofs.append({'case_id':cid,'physical_case_id':pid,'scope_schema':'ds-data-02.physical-binding.v1','native_and_typed_same_scope':scope,'original_typed_request':ref(sp),'typed_receipt':ref(tr),'typed_report':ref(tp),'actual_native_receipt':ref(np),'H5_SHA_producer_only':t['output_sha256'],'all836_UIDs_present_and_native_part_files_stat_only':True,'final_time_s':fs[-1]['time'],'binding':ref(bp),'enabled_request':ref(qp),'scientific_payload_IO':False})
put(O/'controller-config.json',{'requests':qs,'request_sha256':{p:sha(p) for p in qs},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});put(O/'own-actual-completed-full836-independent-QI-XMF-registration.json',{'actual_typed_producer_root':producer,'original104_worker':ref(worker),'cases':proofs,'source_recipe_and_scientific_inputs_unchanged':True,'main_scientific_payload_IO':False,'future_XMF_hashes_null':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register actual full836 P1200 typed results with unchanged104 XMF worker','--',*paths],cwd=R,check=True);print({'root':str(O),'registered_XMF':len(qs),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
