from pathlib import Path
import json,hashlib,ast,sys
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();put=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');sys.path.insert(0,str(L/'scripts'));import ds_data02_runtime_v2 as rt,ds_data02_strict_dispatch_v1 as strict,ds_data02_direct_convert as cv
O=H/'root_stage1_f6_actual_native229_state238_remaining4_typed_392';assert not O.exists();O.mkdir();rows=[]
for s in ['110','130','160','190']:
 p=next((H/'root_stage1_f6_eight_actual_native229_state238_typed_244').glob('*S'+s+'*-typed-request.json'));q=load(p);assert not (D/'families/F6'/q['case_id']/q['attempt_id']).exists();c=q['command'];nr=Path(c[c.index('--solver-receipt')+1]);gr=Path(c[c.index('--gencase-receipt')+1]);op=Path(c[c.index('--owner-metadata')+1]);scope=cv._physical_condition_scope(load(op));assert cv.canonical_hash(scope)==q['physical_condition_sha256'];assert scope['schema']=='ds-data-02.physical-binding.v1'
 for r in [nr,gr,Path(q['actual_state0']['aggregate_execution_receipt'])]:assert (load(r)['status'],load(r)['returncode'])==('completed',0)
 assert load(q['actual_state0']['audit_report'])['status']=='pass' and q['actual_state0']['case_id']==q['case_id'];md=dict(q['input_sha256'])
 for f,digest in md.items():
  assert digest,f
  if Path(f).suffix.lower() not in {'.dat','.h5','.bi4','.vtk','.csv','.npy','.npz','.ibi4'}:assert sha(f)==digest,f
 approval=H/'root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json';md[str(approval)]=sha(approval);md[str(p)]=sha(p);q.update(resource_window=str(approval),resource_window_sha256=sha(approval),input_files=sorted(md),input_sha256=md,source_only=False,disabled=False,launch=True,launch_allowed=True,execution_allowed=True,root_reviewed_source_request=str(p),root_reviewed_source_request_sha256=sha(p),status='root_enabled_actual_native229_and_state238_real_remaining4_typed_pending')
 for k in ['disabled_reason','future_input_files','future_input_sha256']:q.pop(k,None)
 strict.check_registered_hashes(q,rt.validate_request(q));qp=O/(q['case_id']+'-typed-request.json');put(qp,q);rows.append(str(qp))
put(O/'actual-four-native-state0-converter-preflight.json',{'count':4,'each_native_expected_frames':241,'each_expected_particles':417505,'actual_native_and_state0_receipts_completed0':True,'actual_state0_omega_audits_pass':True,'actual_converter_scope_pass':True,'strict_runtime_preflight_pass':True,'scientific_payloads_not_read_by_preparer':True,'parallel_conversion_cap':2,'may_launch_only_after_Root390_terminal':True,'requests':rows,'case_increment':0})
C=H/'root_stage1_f6_remaining4_typed392_guarded_cap2_controller_393';assert not C.exists();C.mkdir();s=(H/'root_stage1_f7_actual24_typed_guarded_cap2_controller_377/batch-controller.py').read_text().replace('root_stage1_f7_actual24_native358_correctedscope077_typed_376',O.name).replace('len(queue)==24','len(queue)==4').replace("'requested':24","'requested':4");a=s.index('def run');s=s[:a]+"assert not json.loads((D/'runtime/resource-ledger.json').read_text())['reservations'], 'Await previous registered jobs terminal; global NVMe cap2'\n"+s[a:];ast.parse(s);(C/'batch-typed-controller.py').write_text(s);print('Root392/393 four F6 real typedpreflight pass; await globalcap2 idle before launch')
