from pathlib import Path
import json,hashlib,copy,datetime,os,collections,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_245.json';cp=load(cpfile);assert cp['checkpoint']==245 and cp['stage1_visual_accepted_complete_independent_cases']==298
ip=root(1317)/'full336-current298-actual-final48-delivery-progress-index.json';index=load(ip);assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==298
by={r['physical_case_id']:r for r in index['cases']};op=root(1261)/'native-request-condition-observations-144-historical-unresolved-vs-actual-absence.json';source=load(op);assert len(source['rows'])==144 and source['actual_native_request_field_present_count']==141 and source['true_actual_field_absence_count']==3
recoveries=[];checked=[];original_statuses=collections.Counter()
for r in source['rows']:
 row=by[r['physical_case_id']];assert row['family_id']==r['family_id'] and row['family_id'] in {'F1','F4','F7'}
 observations=[]
 for e in r['observations']:
  p=Path(e['receipt']['path']);assert sha(p)==e['receipt']['sha256'];v=load(p);q=v['request'];assert q.get('case_id')==e['request_case_id']==r['case_id']
  assert q.get('physical_case_id')==e['request_physical_case_id'] and ('physical_case_id' in q)==e['request_physical_case_id_field_present']
  assert ('physical_condition_sha256' in q)==e['request_condition_field_present'] and q.get('physical_condition_sha256')==e['request_condition_sha256']
  assert v['status']==e['status'] and v.get('returncode')==e['returncode'] and (v['status']=='completed' and v.get('returncode')==0)==e['terminal_completed0_observed']
  original_statuses[f"{v['status']}/{v.get('returncode')}"]+=1
  observations.append({'receipt':ref(p),'actual_request_case_id':q.get('case_id'),'actual_request_physical_case_id_field_present':'physical_case_id' in q,'actual_request_physical_case_id':q.get('physical_case_id'),'actual_request_condition_field_present':'physical_condition_sha256' in q,'actual_request_condition_sha256':q.get('physical_condition_sha256'),'original_status':v['status'],'original_returncode':v.get('returncode'),'original_completed0':v['status']=='completed' and v.get('returncode')==0})
 assert observations and len({e['actual_request_condition_sha256'] for e in observations})==1
 observed=observations[0]['actual_request_condition_sha256'];present=observations[0]['actual_request_condition_field_present'];assert observed==r['actual_native_request_condition_sha256'] and present==r['actual_native_request_field_present']
 old=copy.deepcopy(row['native_request_scope']);assert old.get('sha256') is None or old.get('sha256')==observed
 record={'family_id':row['family_id'],'physical_case_id':row['physical_case_id'],'case_id':r['case_id'],'prior_index_native_request_scope_preserved':old,'actual_request_condition_field_present':present,'actual_request_condition_sha256':observed,'actual_field_absence_not_filled_from_owner_typed_XMF':not present,'actual_native_receipt_observations':observations,'original_nonzero_or_missing_receipt_status_not_promoted':True,'field_role_closure_not_new_native_completion_certificate':True}
 checked.append(record)
 if old.get('sha256') is None and observed is not None:
  recoveries.append(record)
  row['prior_index_native_scope_unresolved_snapshot_preserved']=old
  row['native_request_scope']={'sha256':observed,'role':'actual embedded native receipt request condition directly reverified; original receipt statuses preserved independently; no new completion or precision certificate','actual_native_receipt_observations':observations,'source_original_observation':ref(op),'condition_is_not_inferred_from_accepted_top_or_source_plan':True}
  row['actual_native_condition_field_true_absence']=False
 elif not present:
  row['prior_index_native_scope_unresolved_snapshot_preserved']=old
  row['actual_native_condition_field_true_absence']=True
  row['native_request_scope']={'sha256':None,'role':'true absence of physical_condition_sha256 in actual native request; not filled from accepted top, typed, source plan or XMF','actual_native_receipt_observations':observations,'source_original_observation':ref(op)}
assert len(recoveries)==60 and sum(not r['actual_request_condition_field_present'] for r in checked)==3
before_count=sum(bool(r['native_request_scope'].get('sha256')) for r in load(ip)['cases']);after_count=sum(bool(r['native_request_scope'].get('sha256')) for r in index['cases']);assert before_count==237 and after_count==297
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_F1_F4_F7_actual144_native_request_metadata_roles_60_old_nulls_resolved_three_true_absences_full336_index_reconciled_1319';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_246.json';assert not O.exists() and not np.exists();O.mkdir()
proof={'schema':'ds02.main.actual144-native-role-to-shared-index-reconciliation.v1','at_utc':now.isoformat(),'stable_predecessor_checkpoint':ref(cpfile),'prior_shared_index':ref(ip),'original_actual144_observations_preserved':ref(op),'existing_original_seven_nonterminal_nonzero_and_separate_recovery_roles_preserved':ref(root(1261)/'original-seven-nonterminal-or-nonzero-receipts-and-separate-recovery-preserved.json'),'actual_checked_rows':checked,'old_unresolved_native_digest_count':99,'new_native_digest_unresolved_or_absent_count':39,'newly_independently_resolved_from_actual_requests':60,'true_actual_absences_this144':3,'actual_native_request_digest_available_after':297,'actual_native_original_receipt_status_counts':dict(original_statuses),'native_completion_or_status_promotion':False,'accepted_decisions_unchanged':True,'new_case_credit':0,'new_visual_review':False,'Q_N':0,'Q_E':0,'scientific_payload_IO':False}
pp=O/'actual144-native-role-reverification-and60-index-recoveries-three-true-absences.json';put(pp,proof);snapshot=O/'ledger-immutable-snapshot.json';snapshot.write_bytes(raw)
new=copy.deepcopy(cp);new.update(checkpoint=246,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snapshot),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: prior turn accepted3 actual visual cases295to298 with source183/205/184 and completed fixedactual24F6 particle-rigid delivery. This current checkpoint independently reverified existing144 F1/F4/F7 embedded native requests and reconciled60 previously unresolved shared-index digest roles; three true field absences and original receipt status/recovery roles remain explicit. Accepted298 unchanged, no scientific work repeated.',authorized_work_state='Active298/336,38 visual pending. F1/F4/F7=48,F2=42,F3=39,F5=26,F6=47. Shared index native field digests297 available/39 unresolved or truly absent; no absence promoted from plan/typed/XMF, no new numerical certificate. OriginalF5 1126/1187 live, original951 live waiting fair render admission; source206/185 personal review pending publication, source171 F6 familyfinal48 preparation in progress.')
new['actual_progress']['actual144_native_request_roles_60_shared_index_recoveries_three_true_absences']=ref(pp);new['actual_progress']['nextF5_original1126_1187_exact_scope_live_and_durable_QI_preparation']=ref(root(1318)/'actual-original1126-1187-current-live-scope-preflight-and-futureQI-entrypoints.json');put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,native_request_field_digest_available=after_count,native_request_field_digest_not_available=336-after_count)
index['old_native_request_digest_counters_preserved']={'available':before_count,'not_available':336-before_count,'index':ref(ip)};index['actual144_native_request_role_reconciliation']=ref(pp)
assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==298 and new['accepted_decisions']==cp['accepted_decisions'];put(O/'full336-current298-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('同步已有实际 F1/F4/F7 原生请求条件证据到共享336索引：直接复核144个请求，补齐60个旧未解析摘要，保留3个真实字段缺失。其他39个未解析或缺失状态仍明确保留。旧共享索引、族交付、失败/非终结收据及恢复路径不修改，不宣称原收据状态升级，不新增案例或数值证书。\n');paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: reconcile60 observed native request scopes into full336 shared index','--',*paths],cwd=R,check=True);print({'checkpoint':246,'accepted':298,'native_digests_available':297,'native_digest_unresolved_or_absent':39,'new_case_credit':0,'original_status_counts':dict(original_statuses),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
