from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
commit='bee32b46a55ebbe09fc41318d08cdd15496ec2e9';prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_156_f3_p1200_ay0360_delegated_visual_review_v1';P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==7
before={n:sha(W/n) for n in names};val=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh156.py')],text=True,capture_output=True);assert val.returncode==0 and before=={n:sha(W/n) for n in names}
cid='F3_STAGE1_DP006_P1200_AY0360';vp=P/'metadata/visual-review'/(cid+'-delegated-visual-decision.json');zp=P/'metadata/chain-audit'/(cid+'.json');pp=P/'metadata/png-hashes'/(cid+'.json');v=load(vp);z=load(zp);png=load(pp);pid=v['physical_case_id'];qp=root(1248)/'actual1100-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';qi=load(qp);ar=z['actual_paths']
assert cid==z['case_id']==png['case_id']==qi['case_id'] and pid==z['physical_case_id']==png['physical_case_id']==qi['physical_case_id'];assert v['status']=='visual-approved-by-delegated-agent'
limits=v['review_limits'];assert limits['case_credit']==limits['independent_case_increment']==0 and not any(limits[k] for k in ['global_state_written','scientific_payload_opened_or_hashed_by_this_agent','jobs_started','jobs_restarted','jobs_stopped','q_n_granted','q_e_granted'])
for k,r in qi['actual_completed_receipts'].items():
 assert sha(r['path'])==r['sha256'];a=load(r['path']);assert (a['status'],a['returncode'])==('completed',0) and a['request']['case_id']==cid and ar[k+'_receipt']['path']==r['path'] and ar[k+'_receipt']['sha256']==r['sha256']
for name in ['typed_report','XMF_manifest','XMF_XML','render_report','publish','initial_parent_QA_report','initial_parent_QA_receipt','source_preparation_report']:
 rr=qi[name];assert sha(rr['path'])==rr['sha256']
for name,r in ar.items():
 if isinstance(r,dict) and r.get('path') and r.get('sha256'):assert sha(r['path'])==r['sha256']
assert ar['root1248_previsual_qi_proof']['path']==str(qp) and ar['root1248_previsual_qi_proof']['sha256']==sha(qp)
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'];native=load(qi['actual_completed_receipts']['native']['path']);canonical=native['request']['physical_condition_sha256'];assert canonical==qi['native_request_condition_sha256']==qi['actual_converter_condition_sha256']==v['scope_roles']['native_canonical']['scope_sha256']
x=load(qi['XMF_manifest']['path']);t=load(qi['typed_report']['path']);rr=load(qi['render_report']['path']);pub=load(qi['publish']['path']);assert x['frames']==t['frames']==rr['frames']==rr['source_frames']==836 and x['particles']==t['particles']==179208;assert pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==sha(qi['render_report']['path']);assert t['output_sha256']==x['source_h5_sha256']==rr['source_h5_sha256'];assert x['actual_time_s']==[f['time'] for f in t['lifecycle']['frame_summary']]==[f['actual_time_s'] for f in rr['frame_diagnostics']]
entries=png['entries'];contacts=[e for e in entries if e['role']=='contact_sheet'];keys=[e for e in entries if e['role']=='event_keyframe'];assert len(entries)==44 and len(contacts)==35 and len(keys)==9 and [e['contact_index'] for e in contacts]==list(range(35)) and [e['frame_index'] for e in keys]==[0,104,208,312,417,521,626,730,835];assert [e['path'] for e in contacts]==rr['outputs']['contact_sheets']
pubroot=Path(pub['published_output_root']);published={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in entries:
 path=Path(e['path']);pe=published[str(path.relative_to(pubroot))];assert e['viewed'] and e['view_method']=='view_image' and sha(path)==e['sha256']==pe['sha256'] and path.stat().st_size==e['bytes']==pe['bytes']
assert sorted(p.name for p in Path(rr['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(836)]
cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_213.json';cp=load(cpp);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==277;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {d.get('physical_case_id',d['case_id']) for d in old} and canonical not in {d.get('physical_condition_sha256') for d in old}
ixp=root(1246)/'full336-current277-role-aware-registration-progress-index.json';idx=load(ixp);row=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(row)==1 and not row[0].get('accepted_decision') and row[0]['native_request_scope']['sha256']==canonical
O=H/'root_stage1_source156_F3_P1200AY0360_actual1100_full836_UID_N3_time_QI_personal35contacts_ninekeys_visual_acceptance_1249';assert not O.exists() and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_214.json').exists();O.mkdir();adopted=[]
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert b==(W/n).read_bytes();p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
put(O/'source156-byte-exact-adoption-readonly-validator.json',{'source_commit':commit,'adopted_files':adopted,'validator_returncode':val.returncode,'stdout':val.stdout,'stderr':val.stderr,'source_bytes_unchanged':True})
now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json')
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'family_id':'F3','case_id':cid,'physical_case_id':pid,'status':'visual-approved-by-delegated-agent','physical_condition_sha256':canonical,'actual_converter_scope_sha256':qi['actual_converter_condition_sha256'],'producer_scope_schema':'ds-data-02.physical-binding.v1','source_plan_condition_field_sha256':x['source_plan_condition_sha256'],'source_plan_condition_field_role':'Original XMF producer declared source_plan_condition_sha256; no direct SourceDef-file hash identity inferred','source_review_commit':commit,'source_visual_decision':ref(R/prefix/'metadata/visual-review'/(cid+'-delegated-visual-decision.json')),'source_png_evidence':ref(R/prefix/'metadata/png-hashes'/(cid+'.json')),'source_chain_audit':ref(R/prefix/'metadata/chain-audit'/(cid+'.json')),'actual_completed_metadata_evidence':qi['actual_completed_receipts'],'independent_full836_QI_proof':ref(qp),'full_native_frames':836,'particles':179208,'actual_physical_window_s':qi['actual_time_window_s'],'all836_geometry_velocity_N3_times_UID_finite_verified':True,'all_native_UIDs_active_each_frame':True,'stage1_QI_full_native_identity_and_state_verified':True,'initial_clone_QA':{'report':qi['initial_parent_QA_report'],'receipt':qi['initial_parent_QA_receipt'],'source_preparation_report':qi['source_preparation_report'],'native_changed_forcing_initial_input_digests_unchanged':True},'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['visual_observations'],'contacts_personally_viewed':35,'key_frames_personally_viewed':[0,104,208,312,417,521,626,730,835],'all44_reviewed_PNGs_main_hash_bound_to_actual_publish':True,'visual_review_method':'all chronological contact sheets plus listed event still frames; no continuous playback claim','producer_unknown_exclusions_preserved':rr['unknown_exclusions'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source156-actual1100-full836-personal-visual-independent-adoption-proof.json';put(proof,{'source_commit':commit,'actual_QI_proof':ref(qp),'actual_published_receipt':qi['publish'],'source_original_roles_preserved':v['scope_roles'],'main_declared_source_plan_field_mapping':{'manifest':qi['XMF_manifest'],'field':'source_plan_condition_sha256','sha256':x['source_plan_condition_sha256'],'direct_SourceDef_file_role_not_inferred':True,'native_canonical_and_typed_physicalbinding_role_distinct_from_original_source_plan_declaration':True,'legacy_alias_original_null_status_preserved':v['scope_roles']['legacy_alias']},'new_decision':ref(dp),'new_case_credit':1,'main_scientific_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;cnt=collections.Counter(r['kind'] for r in ledger['attempts']);assert free>=500 and gpu<=512 and cpu<=3840 and cnt['qualification']<=1024 and cnt['production']<=720
cp['accepted_per_family']['F3']+=1;cp.update(checkpoint=214,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),stage1_visual_accepted_complete_independent_cases=278,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts=dict(cnt),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source156 actual1100 full836 completeQI and personal35contacts9keys accepted278/F3=37. Allnative UID active, N3 finite fields, actual times and canonical scope/initialQA/native forcing lineage closed; still visual-approved numerical precision unaccepted.',authorized_work_state='Active278/336 with58 remaining independent visual cases. OriginalF5 M105T1001183 and F2 RX058ROT0751169 samehandles live; F6last951 capacity wait. No controller/request/loadedguard changes, numeric certification or duplicate scientific rerun.')
cp['actual_progress']['source156_F3_actual1100_visual_acceptance']=ref(proof);cp['source_agents']['production_recovery']='fresh156 accepted278/F3=37; next original liveF3/firstpublished successor no duplicate';cp['next_executable_tasks']=['Track original1183 F5M105T100 until completed0 then personal197 review and main801QI.', 'Track original1169 F2RX058ROT075 until completed0 then personal173 review and main401QI retaining real39fluid omissions.', 'Continue originals remainingF3 queue and lastF6original951; preserve allsource bytes and faircap2.', 'Extend real F5first24 prefix15 to24 then final48; maintain cumulative budgets and Home500GiB floor.'];assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==278
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_214.json';put(newcp,cp)
row[0].update(status='visual-approved-in-checkpoint214',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='actual native physicalbinding.v1; original XMF source_plan_condition remains separate',precision_status='视觉检查通过、数值精度未验收')
idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(ixp),accepted_independent_physical_cases=278,registered_pending_independent_physical_cases=58,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if x!=pid];idx['controller_observations_inherited_not_new_live_probe']=True;put(O/'full336-current278-role-aware-registration-progress-index.json',idx)
upper=sum(load(r['latest_registered_render_request']['path'])['estimated_storage_bytes'] for r in idx['cases'] if not r.get('accepted_decision'))/2**30;put(O/'remaining58-render-storage-estimate-vs-home-floor.json',{'at_utc':now,'remaining_registered_visual_cases':58,'sum_original_request_storage_estimates_GiB':upper,'current_home_available_GiB':free,'estimated_remaining_after_all_reserved_outputs_GiB':free-upper,'Home_floor_GiB':500,'conditional_estimate_not_disk_guarantee_for_foreign_writes':True,'no_additional_scientific_storage_allocated':True})
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F3 pitch1200 ay0360 full836 delegated visual with immutable QI','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':278,'F3':37,'remaining':58,'checkpoint':214,'Home_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
