from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
commit='c338172370ae4f7b42f1626464f68f29813d99b1';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_167_f3_assigned_f6_rigid_state_delivery_coverage_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh167.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names};s=load(P/'metadata/f6-final48-rigid-state-coverage.json');plan=load(P/'metadata/full-time-floatinginfo-export-plan.json');ip=next(H.glob('root*_1290'))/'full336-current292-actual-final48-delivery-progress-index.json';idx=load(ip);current={r['physical_case_id']:r for r in idx['cases'] if r['family_id']=='F6'};assert len(current)==48 and set(current)=={r['physical_case_id'] for r in s['cases']};assert sum(bool(r.get('accepted_decision')) for r in current.values())==47;rows=[]
for c in s['cases']:
 pid=c['physical_case_id'];r=c['rigid_state_coverage'];refs={};baseline=r['classification']=='full_time_rigid_state_verified'
 if baseline:
  assert pid=='F6_STAGE1_ANGULAR_RELEASE_OMEGA_BASELINE';report=load(r['report']['path']);assert report['all_actual_checks_passed'] and report['checks']['full241_saved_rigid_history_finite_and_monotone_through12'] and report['checks']['native_and_rigid_rows_same_saved_times'];summary=report['actual_rigid_history']['trajectory_summary'];assert summary['total_frames']==summary['expected_frames']==241 and summary['full_12s_window_complete'] and summary['all_motion_values_finite'];receipt=load(r['full_floatinginfo_receipt']['path']);assert (receipt['status'],receipt['returncode'])==('completed',0);assert Path(r['floatinginfo_file_stat_only']['path']).is_file();refs={'rigid_report':ref(r['report']['path']),'official_full_export_receipt':ref(r['full_floatinginfo_receipt']['path'])};note='Complete existing rigid history, historical actual alias; original current-index native-scope unresolved state preserved, not fabricated from semantic alias.'
 else:
  a=r['state0_evidence'];ap=Path(a['audit_json']['path']);z=load(ap);assert z['status']=='pass' and ('case_id' not in z or z['case_id']==c['case_id']) and z['endpoint']['physical_case_id']==pid and z['floatinginfo']['rows_examined']==2 and z['floatinginfo']['bounded_prefix_only'];cmd=z['official_export_command'];assert '-first:0' in cmd and '-last:1' in cmd and '-savemotion:1' in cmd and '-onlymk:60' in cmd;assert z['floatinginfo']['omega_field_presence']==[True,True,True];nr=Path(z['solver_receipt']['path']);assert sha(nr)==z['solver_receipt']['sha256'];n=load(nr);assert (n['status'],n['returncode'])==('completed',0) and n['request']['case_id']==c['case_id'] and n['request']['physical_case_id']==pid
  data=Path(cmd[cmd.index('-dirdata')+1]);assert sorted(p.name for p in data.glob('Part_*.bi4'))==[f'Part_{i:04d}.bi4' for i in range(241)];assert Path(a['floatinginfo_file_stat_only']['path']).is_file();assert pid in plan['cases_requiring_full_time_export'];refs={'state0_audit':ref(ap),'actual_native_receipt':ref(nr)};note='Actual state0 audit parses only2rows/first0:last1. Native241 filenames preserved; full-time explicit pose/omega/velocity delivery remains unproven by these inputs. This is not a claim of missing native embedded motion states.'
 rows.append({'case_id':c['case_id'],'physical_case_id':pid,'existing_full_rigid_delivery_verified':baseline,'existing_state0_only':not baseline,'actual_evidence':refs,'exact_index_native_scope_preserved':current[pid]['native_request_scope'],'provenance_and_scope_note':note,'source_state0_audit_case_id_field_present':('case_id' in z) if not baseline else None,'new_case_credit':0})
entry=plan['request_contract']['registered_runner'];assert sha(entry['entrypoint'])==entry['sha256'];assert plan['request_contract']['disabled'] and plan['request_contract']['source_only'] and plan['request_contract']['cpu_threads']==2 and plan['future_outputs']['receipt'] is None and plan['future_outputs']['report'] is None and plan['future_outputs']['output_sha256'] is None
O=H/'root_stage1_source167_F6_actual48_rigid_motion_47_state0_only_one_existing_full241_history_missing_delivery_evidence_adoption_1294';assert not list(H.glob('root*_1294'));O.mkdir();adopted=[]
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
put(O/'source167-byte-exact-readonly-validation.json',{'source_commit':commit,'source_files':adopted,'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'validator_scope':'Static source package claims; independent actual JSON/native-filename checks captured in main proof.'});put(O/'F6-final48-fulltime-rigid-state-delivery-evidence-audit.json',{'schema':'ds02.main.F6.final48.fulltime-rigid-delivery-coverage.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_commit':commit,'current_index':ref(ip),'source_coverage':ref(R/prefix/'metadata/f6-final48-rigid-state-coverage.json'),'source_disabled_plan':ref(R/prefix/'metadata/full-time-floatinginfo-export-plan.json'),'final48':48,'existing_full_rigid_delivery_verified':1,'only_state0_export_verified':47,'fulltime_export_evidence_to_supply':47,'cases':rows,'native_embedded_motion_state_missing_not_claimed':True,'future_worker':'fresh168 separately named official full-time FloatingInfo exporter, registeredCPU2; first actuallastF6 then remaining46','solver_rerun_required':False,'source_consumed_H5_or_native_patch_allowed':False,'case_credit':0,'Q_N':0,'Q_E':0,'main_scientific_payload_IO':False});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: audit F6 full-time rigid-motion delivery preserving47 state0-only gaps','--',*paths],cwd=R,check=True);print({'root':str(O),'full_existing':1,'full_export_evidence_to_supply':47,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
