from pathlib import Path
import json,hashlib,subprocess,os,datetime,xml.etree.ElementTree as ET,math
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def check(e):
 assert sha(e['path'])==e['sha256'];assert Path(e['path']).stat().st_size==e['bytes']
commit='7afafe3cabf719a0e5181394507f6552447ecef2';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_180_dzxy_s1375_root951_render_readiness_v1');P=W/prefix;ns=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(ns)==3;blobs={};before={}
for n in ns:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b;before[n]=sha(W/n)
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh180.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in ns}
s=load(P/'metadata/readiness-closure.json');cid=s['case_id'];pid=s['physical_case_id'];assert cid==pid=='F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025';assert s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and s['case_credit']==0 and not s['visual_review_performed']
for e in s['static_inputs'].values():check(e)
receipts={};reports={}
for stage in s['producer_chain']:
 check(stage['execution_receipt']);r=load(stage['execution_receipt']['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid and r['request_sha256']==stage['producer_request_sha256'];receipts[stage['stage']]=r
 if 'metadata_report' in stage:check(stage['metadata_report']);reports[stage['stage']]=load(stage['metadata_report']['path'])
qa=reports['initial_native_qa'];gc=reports['genuine_gencase'];state0=reports['floatinginfo_state0'];t=reports['typed_conversion'];au=reports['typed_h5_integrity_audit'];x=reports['normal_n3_xmf'];native=receipts['full241_native']['request'];xq=receipts['normal_n3_xmf']['request'];canonical=s['scope_roles']['native_initial_qa_and_native_request_scope_sha256'];producer=s['scope_roles']['typed_and_xmf_producer_scope_sha256'];plan=s['scope_roles']['source_plan_condition_sha256']
assert canonical==native['physical_condition_sha256']==qa['physical_condition_sha256']==au['source_canonical_physical_condition_sha256']
assert producer==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']==xq['physical_condition_sha256']==au['producer_physical_condition_sha256'] and producer!=canonical
assert native['source_plan_condition_sha256']==xq['source_plan_condition_sha256']==x['source_plan_condition_sha256']==plan
assert 'source_plan_physical_condition_sha256' not in native and 'source_plan_physical_condition_sha256' not in x
assert qa['pass'] and all(qa['checks'].values());assert gc['actual_total_particles']==417505 and gc['generated_xml_particle_counts']=={'fixed':73441,'moving':0,'floating':16384,'fluid':327680}
assert state0['status']=='pass' and all(state0['checks'].values()) and state0['expected_angular_velocity_rad_s']==[.0825,.11,.165]
assert state0['observed_state0_angular_velocity_rad_s']==s['physical_contract']['observed_state0_angular_velocity_rad_s'];assert all(abs(a-b)<=state0['omega_tolerance_rad_s'] for a,b in zip(state0['observed_state0_angular_velocity_rad_s'],state0['expected_angular_velocity_rad_s']))
assert au['status']=='pass' and all(au['checks'].values());assert au['mass_policy']['physical_mass_kg']==128 and au['mass_policy']['native_support_mass_kg']==256 and au['mass_policy']['normalization']=='none' and not au['mass_policy']['equality_required']
assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected';assert t['solver_dimension']['solver_dimension']==3
assert t['frames']==x['frames']==241 and t['particles']==x['particles']==417505 and t['output_sha256']==x['source_h5_sha256'];assert Path(t['output_hdf5']).is_file()
for k in ('gencase_receipt','solver_receipt','generated_xml','owner_metadata'):
 e=t['source_provenance'][k];assert sha(e['path'])==e['sha256']
xml=s['static_inputs']['case_xmf'];assert x['xdmf']==xml['path'] and x['xdmf_sha256']==xml['sha256'];grids=ET.parse(xml['path']).findall('.//Grid[@GridType="Uniform"]');fs=t['lifecycle']['frame_summary'];af=au['lifecycle']['frames'];mf=au['motion_range']['frame_reports'];times=x['actual_time_s'];assert len(grids)==len(fs)==len(af)==len(mf)==len(times)==241
assert times==[f['time'] for f in fs]==[f['time_s'] for f in af]==[f['time_s'] for f in mf]==[float(g.find('Time').get('Value')) for g in grids];assert all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:])) and times[0]==0 and times[-1]>=12
assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[241,417505,3]
for i,(f,a,g) in enumerate(zip(fs,af,grids)):
 assert f['frame']==a['frame']==i and f['active_particles']==a['active_count'] and f['missing_particles']==a['excluded_count'] and f['active_particles']+f['missing_particles']==417505
 assert f['missing_type_counts']['0']==f['missing_type_counts']['1']==f['missing_type_counts']['2']==0 and f['missing_type_counts']['3']==f['missing_particles'];assert f['type_counts']['0']==73441 and f['type_counts']['2']==16384 and f['type_counts']['3']==327680-f['missing_particles']
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='417505 3';v=next(a for a in g.findall('Attribute') if a.get('Name')=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='417505 3'
native_dir=Path(t['source_provenance']['data_root']);assert sorted(p.name for p in native_dir.glob('Part_*.bi4'))==[f'Part_{i:04d}.bi4' for i in range(241)]
loss={'final_missing_particles':fs[-1]['missing_particles'],'max_missing_per_frame':max(f['missing_particles'] for f in fs),'first_missing_frame':next(f['frame'] for f in fs if f['missing_particles']),'frames_with_any_missing_particle':sum(bool(f['missing_particles']) for f in fs),'cumulative_particle_frame_omissions':sum(f['missing_particles'] for f in fs),'final_missing_type_counts':fs[-1]['missing_type_counts'],'producer_attested_final_Idp_sample':fs[-1]['missing_id_first'],'Idp_sample_not_invented_Zone_Idp_pairs':True,'final_missing_Idp_digest_producer_attested':fs[-1]['missing_ids_sha256'],'audit_excluded_UID_digest_producer_attested':af[-1]['excluded_uid_sha256'],'digest_roles_not_forced_equal':True,'unknown_missing_location_state_cause':True}
assert (loss['final_missing_particles'],loss['max_missing_per_frame'],loss['first_missing_frame'],loss['frames_with_any_missing_particle'],loss['cumulative_particle_frame_omissions'])==(3,3,7,234,700)
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_231.json';cp=load(cpfile);assert cp['accepted_per_family']['F6']==47 and cp['stage1_visual_accepted_complete_independent_cases']==289;idx=load(root(1281)/'full336-current289-actual-final48-delivery-progress-index.json');rows=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(rows)==1 and not rows[0].get('accepted_decision') and rows[0]['native_request_scope']['sha256']==canonical
p=Path('/proc/4004579');assert p.is_dir();st=(p/'stat').read_text().split(') ',1)[1].split();assert st[19]=='207142232' and st[0] not in ('Z','X');assert str(root(951)/'batch-controller.py').encode() in (p/'cmdline').read_bytes();progress=load(root(951)/'actual-progress.json');results=progress.get('results',[]);assert not any(r.get('case_id')==cid for r in results);attempt=Path(s['render_gate']['request_attempt_root']);obs={'pid':4004579,'startticks':st[19],'state':st[0],'live_now':True,'actual_target_in_results':False,'actual_results_rows':len(results),'target_attempt_root_exists':attempt.exists(),'target_execution_receipt_exists':(attempt/'execution-receipt.json').exists(),'target_publish_receipt_exists':(attempt/'render/render-publish-receipt.json').exists(),'mutable_progress_not_hashed':True};assert not obs['target_execution_receipt_exists'] and not obs['target_publish_receipt_exists']
sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert free>=500
O=H/'root_stage1_source180_lastF6_DZXY_S1375_YAWP18_full241_ownUID_N3_missing3fluid_state0_mass_scope_previsual_readiness_adoption_1283';assert not list(H.glob('root*_1283'));O.mkdir();adopted=[]
for rel,b in blobs.items():
 q=R/rel;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(b);adopted.append(ref(q))
vp=O/'source180-byte-exact-readonly-validation.json';put(vp,{'source_commit':commit,'adopted_source_files':adopted,'source_SHA_before_after':before,'source_bytes_unchanged':True,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'source_live_observation_and_gate_nulls_preserved_as_snapshot':True})
proof=O/'actual-lastF6-full241-own-UID-N3-state0-scope-readiness-with-quantified3fluid-omissions.json';put(proof,{'schema':'ds02.main.last-F6-full241-own-metadata-render-readiness.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_validation':ref(vp),'current_acceptance_authority':ref(cpfile),'case_id':cid,'physical_case_id':pid,'all7_producer_stages_actual_completed_zero_case_bound_verified':True,'actual_producer_chain':s['producer_chain'],'all241_actual_times_UID_lifecycle_N3_XMF_geometry_velocity_verified':True,'all241_native_frame_filenames_verified':True,'producer_full241_finite_and_positive_mass_audit_checks':au['checks'],'frames':241,'particles':417505,'actual_time_window_s':[times[0],times[-1]],'lifecycle_omissions':loss,'physical_mass_kg':128,'native_support_mass_kg':256,'no_mass_rescale_or_equality_claim':True,'state0_declared_angular_velocity_rad_s':state0['expected_angular_velocity_rad_s'],'state0_observed_angular_velocity_rad_s':state0['observed_state0_angular_velocity_rad_s'],'no_particle_v0_to_omega_inference':True,'native_canonical_physical_condition_sha256':canonical,'typed_XMF_producer_scope_sha256':producer,'source_plan_condition_sha256_exact_existing_field':plan,'native_source_plan_physical_condition_sha256_field_present':False,'XMF_source_plan_physical_condition_sha256_field_present':False,'source_plan_condition_field_not_substituted_into_absent_physical_field':True,'current_original951_live_observation':obs,'source_prior_wait_reason_not_new_current_diagnosis':s['admission_observation'],'Home_available_GiB':free,'Home_floor_GiB':500,'visual_status':'pending original render completed0 atomicpublication and delegated personal11contacts9keys','future_visual_evidence_not_invented':True,'case_credit':0,'q_n_granted':False,'q_e_granted':False,'main_scientific_payload_IO':False})
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close last F6 full241 readiness retaining3 fluid omissions state0 and mass scope roles','--',*paths],cwd=R,check=True);print({'proof':ref(proof),'case_credit':0,'missing_fluid_final':3,'cumulative_particle_frame_omissions':700,'original951_live':obs,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
