from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,math,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_297.json';cp=load(cpfile);assert cp['checkpoint']==297 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==319
qip=root(1397)/'actual1158-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip);assert sha(qip)=='3749c247bcb282e93e73d659f557c067446685d0f79d7b72dbeffb89ef194ed1' and qi['all801_geometry_velocity_N3_times_UID_finite_verified']
er=qi['actual_completed_metadata_evidence']
for e in er.values():assert sha(e['path'])==e['sha256']
source=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');SP=source/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_182_f3_assigned_f5_m101_t100_actual1158_previsual_primary_namespace_preflight_v1';commit='c9a7268a4ee6d6b93b658af6c241bccf200fd208'
manifest=load(SP/'package-manifest.json');assert manifest['package_manifest_excluded_from_own_hash']
files=[e['path'] for e in manifest['files']]+['package-manifest.json'];assert len(files)==5 and len(set(files))==5
source_before={rel:sha(SP/rel) for rel in files}
for rel in files:
 original_bytes=subprocess.check_output(['git','show',commit+':'+str((SP/rel).relative_to(source))],cwd=source);assert original_bytes==(SP/rel).read_bytes()
for e in manifest['files']:assert sha(SP/e['path'])==e['sha256'] and (SP/e['path']).stat().st_size==e['bytes']
validation=subprocess.run(['python3','-B',str(SP/'validate_fresh182.py')],text=True,capture_output=True,check=True);assert json.loads(validation.stdout)['status']=='PASS'
sj=load(SP/'metadata/M101_T100-previsual-primary-namespace-preflight.json');mr={e['role']:e for e in sj['metadata_refs']}
for e in mr.values():assert sha(e['path'])==e['sha256']
for role,key in [('native receipt','native_receipt'),('typed receipt','typed_receipt'),('typed conversion report','typed_report'),('XMF receipt','xmf_receipt'),('XMF manifest','xmf_manifest'),('XMF XML','xmf_xml'),('bed receipt','bed_receipt'),('bed report','bed_report'),('GenCase receipt','gencase_receipt'),('GenCase generated XML','generated_xml'),('initial QA receipt','initial_qa_receipt'),('initial QA report','initial_qa_report')]:assert mr[role]['path']==er[key]['path'] and mr[role]['sha256']==er[key]['sha256']
assert sj['identity']['physical_case_id']==qi['physical_case_id'] and sj['identity']['case_id']==qi['case_id']
assert sj['namespace_roles']['source_definition']['sha256']==qi['actual_SourceDef']['sha256'] and sj['namespace_roles']['native']['condition_scope']==qi['canonical_actual_native_request_condition_sha256'] and sj['namespace_roles']['typed']['legacy_scope']==qi['actual_converter_legacy_scope_sha256']
assert sj['namespace_roles']['xmf']['source_plan_physical_scope']==qi['canonical_actual_native_request_condition_sha256']
assert sj['namespace_roles']['xmf']['source_plan_file_scope']=='366adc5200604490871116a0a5b8503c9bef4bfb1e72195df94995605fa7d324'
assert not sj['initial_qa']['precision_accepted'] and sj['package_scope']['new_case_credit']==0
F=root(1190);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre);refs={k:e for k,e in j.items() if isinstance(e,dict) and 'path' in e and 'sha256' in e}
for e in refs.values():assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);native_ref=t['source_provenance']['solver_receipt'];assert sha(native_ref['path'])==native_ref['sha256'];n=load(native_ref['path']);nq=n['request'];bedr=load(j['actual_bed_receipt']['path']);b=load(bedr['request']['binding']);bed=load(j['actual_bed_report']['path']);refs['actual_native_receipt']=native_ref;refs['actual_bed_binding']=ref(bedr['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert (canonical,legacy,sd)==('896b3f27d96c56d6cebf978b0eb835a2ccb2ada1b09995a0b157320e1edb27ee','4bd1f1eddd55a7ee52ba0ebc314405777d09a09557b209a0385d4222d550f3b7','4a8aaff4383ee7596c7d50e1f0b991674d10fd63a3445b3b62d2acc450c85701')
mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
for ns,m in mask.items():assert m=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical if ns=='native' else sd}}
source_def=ref(b['source_definition']);assert source_def['sha256']==b['source_definition_sha256']==sd==bed['source_plan_physical_condition_sha256'];plan=ref(b['source_plan_file']);assert plan['sha256']==b['source_plan_file_sha256'] and len({canonical,legacy,sd,plan['sha256']})==4
for rr in [n,bedr]:assert rr['input_hashes_at_launch'][plan['path']]==rr['input_hashes_after_run'][plan['path']]==plan['sha256']
q=load(F/'enabled-full801-render-request.json');w=load(F/'enabled-render-wrapper.json');cid=q['case_id'];pid=q['physical_case_id'];assert pid=='F5_COMPACT_RUNUP_RECOVERY_C082S1_M112_T085' and cid=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M112_T085_NEXT34'
for k,bkey in [('gencase_receipt','gencase_receipt'),('initial_qa_receipt','initial_qa_receipt'),('initial_qa_report','initial_qa_report'),('generated_xml','canonical_generated_xml')]:
 e=ref(b[bkey]);assert e['sha256']==b[bkey+'_sha256'];refs[k]=e
for k in ['gencase_receipt','initial_qa_receipt','actual_native_receipt','actual_typed_receipt','actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
qa=load(refs['initial_qa_report']['path']);assert qa['all_basic_placement_checks_pass'] and all(qa['checks'].values()) and not qa['numerical_precision_result_accepted'];assert t['source_provenance']['gencase_receipt']==refs['gencase_receipt'] and t['source_provenance']['generated_xml']==refs['generated_xml']
assert w['expected_frames']==t['frames']==x['frames']==len(bed['frame_reports'])==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
assert t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected' and t['partvtk_validation']['all_passed'];assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];xp=Path(x['xdmf']);refs['XMF_XML']=ref(xp);assert refs['XMF_XML']['sha256']==x['xdmf_sha256'];grids=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]');assert len(fs)==len(times)==len(grids)==801 and times==[f['time'] for f in fs]==[f['time_s'] for f in bed['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert [times[0],times[-1]]==[0,16.00004580463777] and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
for i,(f,bf,g) in enumerate(zip(fs,bed['frame_reports'],grids)):
 assert f['frame']==bf['frame']==i and f['active_particles']==194427 and f['missing_particles']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658}
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';v=next(z for z in g.findall('Attribute') if z.get('Name')=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='194427 3'
 assert bf['initial_fluid_uid_count']==bf['current_valid_type3_fluid_count']==bf['finite_mass_current_fluid_count']==bf['finite_position_current_fluid_count']==31658 and bf['uid_tracking']['missing_initial_uid']['count']==bf['uid_tracking']['unexpected_current_uid']['count']==bf['nonfinite_mass_current_fluid_count']==bf['nonfinite_position_current_fluid_count']==0 and not bf['uid_tracking']['unexplained'];assert bf['bed_domain']['x_outside_exact_profile_domain_count']==bf['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']==bf['penetration']['depth_unevaluable_current_fluid_count']==0
 for k,th in [('one_dp',.02),('two_dp',.04)]:assert bf['penetration'][k]['threshold_m']==th and bf['penetration'][k]['count']==0 and bf['penetration'][k]['deepest_depth_m'] is None
h5=t['output_hdf5'];assert t['output_sha256']==x['source_h5_sha256']
for k in ['actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
pp=Path('/proc/691863');obs=None
if pp.exists():
 st=(pp/'stat').read_text().rsplit(')',1)[1].split();args=(pp/'cmdline').read_bytes().split(b'\0');assert st[19]=='214553234' and str(F/'enabled-full801-render-request.json').encode() in args;obs={'registered_launch_pid':691863,'startticks':'214553234','state':st[0],'original_request_bound_to_actual_cmdline':True,'no_restart':True}
assert obs is not None or (F/'controller-result.json').exists()
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source182_F5_original1158_actual_full801_own1397_next1190_UID_bed_nativecanonical_XMF_SourceDef_durable1399_1398';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_298.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1399'));dest=R/SP.relative_to(source)
assert not dest.exists()
O.mkdir();dest.mkdir(parents=True)
for rel in files:
 p=dest/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes((SP/rel).read_bytes());assert sha(p)==source_before[rel]
validation_copy=subprocess.run(['python3','-B',str(dest/'validate_fresh182.py')],text=True,capture_output=True,check=True);assert json.loads(validation_copy.stdout)['status']=='PASS'
assert {rel:sha(SP/rel) for rel in files}==source_before
entry=O/'after_original1190_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1190-full801-own-QI1399.py').read_bytes());compile(entry.read_text(),str(entry),'exec')
proof=O/'source182-own1397-next1190-metadata-roles-and-durableQI-proof.json'
put(proof,{'schema':'ds02.source182-own1397-next1190-durableQI.v1','at_utc':now.isoformat(),'source_commit':commit,'source_exact_files':source_before,'source_validator_read_full_before_execute':True,'source_readonly_validation':json.loads(validation.stdout),'copied_readonly_validation':json.loads(validation_copy.stdout),'source_bytes_unchanged_after':True,'actual1158_full801_ownQI':ref(qip),'actual1158_all25_source_primary_metadata_refs_verified':True,'actual1158_source_refs_joined_to_own1397':True,'personal_source184_pending':True,'source182_observations_are_historical_not_new_visual_evidence':True,'next_original1190_upstream_primary_refs':refs,'next_original1190_actual_native_XMF_plan_masks':mask,'next_original1190_native_physical_plan_canonical_XMF_physical_plan_SourceDef_FILE':True,'next_original1190_actual_SourceDef':source_def,'next_original1190_actual_plan_JSON':plan,'next_original1190_full801_UID_N3_times_bed_preflight':True,'next_original1190_genuine_GenCase_QA_and_precision_negative_preserved':True,'next_original1190_time_window':[times[0],times[-1]],'next_original1190_same_live_registered_launch':obs,'durable_entry':ref(entry),'future_own1399_unexecuted_sha_unknown':True,'command':['python3','-B',str(entry),'1190','1399'],'new_case_credit':0,'main_scientific_payload_IO':False,'main_PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=298,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actual F5original1158 own1397 complete801 QI; source182 byte-exact source and all25metadata primary refs independently joined; next1190 actual801 typed UID/N3/time and bed/genuine QA/nativecanonical-XMFSourceDef roles checked, same launch live, durable1399 prepared.',authorized_work_state='Active319/336 pending17. F2original1009 own1392 and F5original1158 own1397 completed published awaiting production personal183 then184. Source196 F3 and218 F5 final tool repair active; next197 F2 separate repair authorized. Next1190 and1031 original registered launches continue; no new scientific or render jobs.')
new['actual_progress']['actual1158_completed_full801_ownQI']=ref(qip);new['actual_progress']['source182_preflight_and_next1190_durableQI']=ref(proof)
new['source_agents']['production_recovery']='fresh182 committed metadata preflight; fresh183 F2actual1009 personal17+9 then fresh184 F5actual1158 personal34+9 authorized'
new['source_agents']['f5_bed_recovery']='fresh218 F5 final tool repair active; oldfresh217 superseded by183 no duplicate'
new['source_agents']['f6_endpoint_initial_qa']='fresh196 F3 final tool repair active; fresh197 separateF2 repair authorized next'
new['next_executable_tasks'].insert(0,'Adopt actual personal183 F2original1009 then184 F5original1158 after source commit/readonlyvalidation/ownQI/publishedPNG verification. After next1190 truecompleted0 publication execute durableown1399 once; preserve actual XMF physicalplan SourceDef FILE vs nativephysicalplan canonical. Continue196/218 and next197 boundedfinaltoolrepair.')
put(np,new)
ip=root(1396)/'full336-current319-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile)
row=next(z for z in idx['cases'] if z['physical_case_id']==qi['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=ref(qip),current_actual_render_receipt=er['render_receipt'],current_atomic_publish_receipt=er['render_publish_receipt'],current_personal_review_source=184,case_credit=0,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=sorted(set(idx['actual_unaccepted_completed0_published_physical_cases']+[qi['physical_case_id']])),source182_preflight_and_next1190_durableQI=ref(proof));assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==319
put(O/'full336-current319-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(p.relative_to(R)) for p in dest.rglob('*') if p.is_file()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: integrate M101 metadata preflight and prepare M112 original1190 full801 integrity','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':298,'accepted':319,'next_original1190_live':obs,'future1399_unexecuted':True,'proof':ref(proof),'free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
