from pathlib import Path
import json, hashlib, subprocess, datetime, math, xml.etree.ElementTree as ET, copy, collections, os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.md','.py'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
F=root(1009);basep=F/'actual1007-full401-XMF-and995-typed-independent-review.json';b=load(basep);refs={k:e for k,e in b.items() if isinstance(e,dict) and 'path' in e and 'sha256' in e}
for e in refs.values():assert sha(e['path'])==e['sha256']
q=load(F/'enabled-full401-render-request.json');w=load(F/'enabled-render-wrapper.json');cid=q['case_id'];pid=q['physical_case_id'];assert pid=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX049_RY014_FILL080_ROT075'
receipts={k:load(refs['actual_'+k+'_receipt']['path']) for k in ['native','typed','XMF']}
for rr in receipts.values():assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
t=load(refs['actual_typed_report']['path']);x=load(refs['actual_XMF_manifest']['path']);n=receipts['native']['request'];xp=Path(refs['actual_XMF_XML']['path']);fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];g=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]')
assert t['frames']==x['frames']==w['expected_frames']==len(fs)==len(times)==len(g)==401 and t['particles']==x['particles']==w['expected_particles']==418104
assert t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected' and t['partvtk_validation']['all_passed']
assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[401,418104,3] and x['source_h5_sha256']==t['output_sha256']
assert times==[z['time'] for z in fs]==[float(z.find('Time').get('Value')) for z in g] and [times[0],times[-1]]==[0,4.00006189848381] and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
for i,(z,grid) in enumerate(zip(fs,g)):
 assert z['frame']==i and z['active_particles']+z['missing_particles']==418104 and z['type_counts']=={'0':372840,'1':24150,'2':0,'3':21114-z['missing_particles']} and z['missing_type_counts']=={'0':0,'1':0,'2':0,'3':z['missing_particles']}
 assert grid.find('Geometry').get('GeometryType')=='XYZ' and grid.find('Geometry/DataItem').get('Dimensions')=='418104 3';v=next(a for a in grid.findall('Attribute') if a.get('Name').lower()=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='418104 3'
canonical=n['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert canonical=='27f952a271ff237e6fe2d09e21047786476f1ce9ad5157c94847097187026fa6' and legacy==x['physical_condition_sha256']==b['physical_condition_sha256']=='208d547c388db7caed982f1d088baf6fb942b46e48e4f8552a0e0cfe21cf1f9b'
masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n),('XMF',x)]};assert masks['native']=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}} and all(v=={'present':False,'value':None} for v in masks['XMF'].values())
for key in ['gencase_receipt','generated_xml','owner_metadata','solver_receipt']:
 e=t['source_provenance'][key];assert sha(e['path'])==e['sha256'];refs['typed_source_'+key]=e
assert t['source_provenance']['solver_receipt']==refs['actual_native_receipt'];gc=load(refs['typed_source_gencase_receipt']['path']);assert gc['status']=='completed' and gc['returncode']==0 and gc['request']['case_id']==cid
for key in ['initial_qa_receipt','initial_qa_report']:
 e=ref(n[key]);assert receipts['native']['input_hashes_at_launch'][e['path']]==receipts['native']['input_hashes_after_run'][e['path']]==e['sha256'];refs[key]=e
qa=load(refs['initial_qa_receipt']['path']);qr=load(refs['initial_qa_report']['path']);assert qa['status']=='completed' and qa['returncode']==0 and qa['request']['case_id']==qr['case_id']==cid and qr['status']=='pass'
assert fs[-1]['missing_particles']==35 and max(z['missing_particles'] for z in fs)==35 and next(z['frame'] for z in fs if z['missing_particles'])==137 and sum(z['missing_particles'] for z in fs)==8397
assert fs[-1]['missing_id_first']==[397016,397025,397188,397192,403605,403609,403611,403829] and fs[-1]['missing_ids_sha256']=='77346a6b93920a09238dc62bedfa2e7b411baf9ecff05a83d71daaaa3f882766'
assert not (F/'controller-result.json').exists();observed=[]
for original,pid0,start in [(1009,678700,'214424193'),(1158,682554,'214459220')]:
 pp=Path('/proc')/str(pid0);stat=(pp/'stat').read_text().rsplit(')',1)[1].split();args=(pp/'cmdline').read_bytes().split(b'\0');assert stat[19]==start and str(root(original)/('enabled-full'+('401' if original==1009 else '801')+'-render-request.json')).encode() in args
 observed.append({'original':original,'actual_registered_launch_pid':pid0,'startticks':start,'state':stat[0],'launch_cmdline_bound_to_original_request':True,'no_restart':True})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_292.json';cp=load(cpfile);ip=root(1390)/'full336-current317-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==317
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current317_nextF2_original1009_full401_thirtyfive_fluid_omissions_actual_native_XMF_roles_genuineQA_durableQI1392_1391';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_293.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1392'));O.mkdir();entry=O/'after_original1009_terminal_full401_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F2-original1009-full401-own-QI1392.py').read_bytes());proof=O/'next-original1009-actual401-thirtyfive-omissions-genuineQA-durableQI-readiness.json'
put(proof,{'schema':'ds02.main.next-original1009.full401.QI-readiness.v1','at_utc':now.isoformat(),'case_id':cid,'physical_case_id':q['physical_case_id'],'upstream_full401_metadata_refs':refs,'prior_previsual_review':ref(basep),'canonical_native_sha256':canonical,'typed_XMF_legacy_sha256':legacy,'actual_native_XMF_plan_field_namespaces':masks,'actual_time_window_s':[times[0],times[-1]],'full401_typed_UID_type_N3_and_XMF_exact_time_verified':True,'genuine_initial_QA_and_GenCase_completed0':True,'fluid_omissions':{'final':35,'first_frame':137,'cumulative_particle_frames':8397,'attested_Idp_sample':fs[-1]['missing_id_first'],'sample_is_partial8_not_all35':True,'attested_final_missing_Idp_digest':fs[-1]['missing_ids_sha256'],'state_location_cause_unknown':True},'same_live_original_registered_launches':observed,'future_ownQI1392_UNEXECUTED_SHA_unknown':True,'durable_entry':ref(entry),'command':['python3','-B',str(entry),'1009','1392'],'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=293,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: next original1009 registered launch PID678700/start214424193 live and future ownQI1392 prepared after true full401 typed/XMF UID/N3/actual time/35 fluid omissions/nativecanonical-typedlegacy/genuineQA metadata verification; next F5original1158 same registered launch live, no restart.',authorized_work_state='Active317/336 pending19. Source216 F2original1097 and source181 F3original1194 personal visuals active after completed own1385/1387; next F2original1009 and F5original1158 same live registered launches. Futureown1392 unexecuted. Source196 F3 repair active, source195 main audit pending, source180 F5 assembly only requires182.');new['actual_progress']['next_original1009_durable401_QI']=ref(proof);new['next_executable_tasks'].insert(0,'After original1009 actual completed0/publication execute Root1391 durable ownQI1392 once, preserving35fluid omissions and partial8UID sample; prepare actual F5original1158 own801QI after source bed lineage/runtime/namespace inspection.');put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,next_original1009_durable401_QI=ref(proof));put(O/'full336-current317-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare next F2 full401 integrity preserving35 fluid omissions and live original launches','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':293,'accepted':317,'future_ownQI1392_unexecuted':True,'proof':ref(proof),'live':observed,'free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
