from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.xml','.xmf','.png','.py','.md','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_170_f2_rx051_rot090_personal_visual_acceptance_v1';commit='1d2ae683ce0b7609892435a570106e2c582e682a';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==3;P=W/prefix;before={n:sha(W/n) for n in names};vld=P/'scripts/validate_fresh170.py';val=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert val.returncode==0 and before=={n:sha(W/n) for n in names};source=load(P/'metadata/personal-visual-decision.json');qi_path=root(1240)/'actual1069-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qi_path);stage=qi['actual_completed_metadata_evidence'];cid=source['case']['case_id'];pid=source['case']['physical_case_id'];assert qi['case_id']==cid and qi['physical_case_id']==pid and qi['frames']==401 and qi['stage1_QI_full_native_identity_and_state_verified'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert source['case']['canonical_source_physical_condition_sha256']==canonical and source['case']['typed_legacy_and_actual_converter_scope_sha256']==legacy;assert source['decision']['status']=='visual-approved-by-delegated-agent' and source['decision']['case_credit']==0 and not source['decision']['global_acceptance'] and not source['decision']['q_n_granted'] and not source['decision']['q_e_granted']
for fields in stage.values():
 for e in fields.values():assert sha(e['path'])==e['sha256']
for e in source['evidence'].values():assert sha(e['path'])==e['sha256']
assert sha(source['predecessor']['path'])==source['predecessor']['sha256'];vr=source['visual_review'];assert vr['personally_viewed_with']=='view_image' and vr['contact_sheet_count']==len(vr['contact_sheets'])==17 and vr['key_frame_count']==len(vr['key_frames'])==9;rr=load(stage['full_render_root1069']['animation_report']['path']);pub=load(stage['full_render_root1069']['publish_receipt']['path']);assert [e['path'] for e in vr['contact_sheets']]==rr['outputs']['contact_sheets'] and [e['frame'] for e in vr['key_frames']]==list(range(0,401,50));published={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in vr['contact_sheets']+vr['key_frames']:
 relative=str(Path(e['path']).relative_to(Path(stage['full_render_root1069']['receipt']['path']).parent/'render'));assert sha(e['path'])==e['sha256']==published[relative]['sha256'] and Path(e['path']).stat().st_size==e['bytes']==published[relative]['bytes']
for i,e in enumerate(vr['contact_sheets']):assert e['frame_start']==i*24 and e['frame_end']==min(i*24+23,400)
assert source['lifecycle_and_render_metadata']['final_missing_particles']==qi['lifecycle']['final_missing_particles']==1 and source['lifecycle_and_render_metadata']['final_missing_fluid_uid']=='403829'
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_206.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==274;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {d.get('physical_case_id',d['case_id']) for d in old};idxp=root(1237)/'full336-current274-role-aware-registration-progress-index.json';idx=load(idxp);target=[d for d in idx['cases'] if d['physical_case_id']==pid];assert len(target)==1 and not target[0].get('accepted_decision') and target[0]['native_request_scope']['sha256']==canonical
for row in idx['cases']:
 if row.get('accepted_decision'):assert row.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
O=H/'root_stage1_source170_F2_RX051ROT090_actual1069_full401_QI_UID_lifecycle_personal17contacts_ninekeys_acceptance_1242';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_207.json').exists();adopted=[]
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'actual-source170-readonly-validator.json';put(vp,{'validator':ref(vld),'returncode':val.returncode,'stdout':val.stdout,'stderr':val.stderr,'source_original_bytes_unchanged':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json');decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'producer_scope_schema_verified_from_actual_report':'legacy-owner-scope.v0','source_assigned_agent_family':'F6','source_family_id_F6_is_assignment_not_physical_case_family':True,'source_review_commit':commit,'source_visual_review':ref(P/'metadata/personal-visual-decision.json'),'source_review_closure':ref(P/'metadata/personal-visual-decision.json'),'independent_full401_QI_proof':ref(qi_path),'actual_completed_metadata_evidence':stage,'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'manifest_dimension_alias_absent_preserved':qi['manifest_dimension_alias_absent_preserved'],'lifecycle':qi['lifecycle'],'missing_UID_cause_location_state_unknown_preserved':True,'legacy_ROT105_or_minus105_field_not_promoted_to_actual_native_ROT090_control':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':vr['observations'],'personal_visual_failure_screen':vr['failure_screen'],'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'all26_PNG_hashes_match_actual_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source170-actual1069-full401-independent-QI-and-personal-visual-adoption.json';put(proof,{'source_commit':commit,'adopted_files':adopted,'source_validator':ref(vp),'original_independent_QI':ref(qi_path),'new_decision':ref(dp),'actual_lifecycle_limits':qi['lifecycle'],'source_family_assignment_role_preserved':True,'actual_personal_PNG_count':26,'canonical_and_legacy_scope_roles_separate':True,'original_source169_wait_snapshot_preserved':source['predecessor'],'new_case_credit':1,'main_scientific_payload_IO':False})
put(O/'actual1068-QI-extra-gate-failure-classification-and-new-proof-role.json',{'original_partial1240_metadata_review':ref(root(1240)/'preparation-failure.json'),'actual1069_valid_QI_written_before_following_case_extra_gate_failure':True,'actual1068_old_extra_0p1percent_gate':'not a user GOAL threshold or numerical qualification; only failed new main metadata script gate, never a scientific attempt failure','actual1068_quantified48fluid_omission_QI':ref(root(1241)/'actual1068-full401-independent-UID-N3-time-scope-QI-proof.json'),'actual1068_personal_visual_adoption_pending':True,'unknown_missing_UID_locations_states_causes_retained':True,'no_precision_certification':True,'new_case_credit_for1068':0})
(root(1240)/'failed-main-metadata-review-source.py').write_bytes(Path('/tmp/ds02-F2-1069-1068-full401-QI-root1240.py').read_bytes())
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);z=os.statvfs('/home/jade');free=z.f_bavail*z.f_frsize/2**30;counts=collections.Counter(d['kind'] for d in ld['attempts']);gpu=sum(d.get('gpu_seconds',0) for d in ld['charges'])/3600;cpu=sum(d.get('cpu_core_seconds',0) for d in ld['charges'])/3600;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
cp=copy.deepcopy(cp);cp['accepted_per_family']['F2']+=1;cp.update(checkpoint=207,at_utc=now,predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=275,accepted_decisions=cp['accepted_decisions']+[str(dp)],new_accepted_decisions=[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='Progress: own actual1069 full401 UID/N3/actualtime/publish metadata QI and fresh170 personal17contacts9keys accepted275/F2=34; actual1068 full401QI closed with quantified48fluid omissions pending171visual. Userfailedcleanup534.4GiB remains preserved. All original scientific/negative receipts retained.',authorized_work_state='Active275/336, F2=34,F5=14,F3=36,F6=47,F1/F4/F7=48. Actual1068 completed0/published,QI1241full401closed,pendingfresh171personalreview; F31100 andF51109 originalrenders live. Fresh195 storage retention0newdelete and154 exactlive observations committed pendingadoption.')
assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==275;cp['actual_progress']['source170_F2_actual1069_visual_acceptance']=ref(proof);cp['actual_progress']['actual1068_F2_full401_QI_previsual']=ref(root(1241)/'actual1068-full401-independent-UID-N3-time-scope-QI-proof.json');cp['source_agents']['f6_endpoint_initial_qa']='fresh170 accepted275/F2=34; fresh171actual1068personalreview';cp['next_executable_tasks']=['Adopt fresh171 actual1068 RX051ROT075 personal17contacts9keys after committed review, using immutable Root1241 full401QI and quantified48missingfluid limits.','Adopt exact source195 F5retention audit; no immediately safe deletion. Source153 consumedF3recovery12GiB retained; user cleanup cumulative534.4GiB completed.','Adopt source15412samePID/startticks F3originalhandle observations as historical snapshot; preserve 801topmetadata vs836actualwrapper discrepancy in sidecar pending155closure.','Continue same live F51109 andF31100 renders; personally review newpublished0 products through child196/155 without scientific reruns.','Grow F5actualfirst24 from existing14accepted using frozenfirst8 and actual acceptance order; complete final336actualvisualcases.'];newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_207.json';put(newcp,cp)
target[0].update(status='visual-approved-in-checkpoint207',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='Own actual native request condition; typed/render legacy separate',precision_status='视觉检查通过、数值精度未验收');idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxp),accepted_independent_physical_cases=275,registered_pending_independent_physical_cases=61,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[p for p in idx['actual_unaccepted_completed0_published_physical_cases'] if p!=pid];idx['actual1068_full401_QI_snapshot']=ref(root(1241)/'actual1068-full401-independent-UID-N3-time-scope-QI-proof.json');put(O/'full336-current275-role-aware-registration-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for nn in (1240,1241,1242) for p in root(nn).iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 RX051 ROT090 full401 personal visual and immutable UID limits','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':207,'accepted':275,'F2':34,'remaining':61,'Home_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
