from pathlib import Path
import json,hashlib,subprocess,re,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
forbidden={'.h5','.hdf5','.bi4','.ibi4','.obi4','.csv','.dat','.vtk','.vtu','.npy','.npz'}
def sha(p):
 p=Path(p);assert p.suffix.lower() not in forbidden;return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_121_f3_actual884_metadata_scope_closure_v1';commit='8823c5a744e94e3c23e49bb6087445d0efa5dedb';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==11;adopted=[]
for name in names:
 assert Path(name).suffix in {'.py','.md','.json'};raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;q=load(next(P.glob('requests/*.json')));b=load(q['binding']);o=load(q['actual_converter_owner']['path']);assert sha(q['actual_converter_owner']['path'])==q['actual_converter_owner']['sha256'];assert 'physical_binding' in o and hashlib.sha256(json.dumps(o['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==q['actual_converter_scope_sha256'];assert b['legacy_converter_scope']['sha256'] is None
native=q['actual_native_dependency'];receipt=load(native['receipt']['path']);assert sha(native['receipt']['path'])==native['receipt']['sha256'];assert (receipt['status'],receipt['returncode'])==('completed',0);assert sha(native['request']['path'])==native['request']['sha256'];files=sorted(p.name for p in Path(native['data_root']).iterdir() if re.fullmatch(r'Part_[0-9]+\.bi4',p.name));assert len(files)==836;assert q['expected_dimension']==3 and q['expected_particles']==179208;assert q['command'][1]==str(L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_157_nvme_typed_home_cap_publish_cleanup_fix_v1/scripts/nvme_convert_home_capped_v2.py');assert sha(q['command'][1])=='37fe7eaff4405e9ba6d9b7f666a53d7c02ee65fc6f30992fc1a8fdb0d8a61b11'
O=H/'root_stage1_F3_actual884_full836_explicit_v1_owner_typed157_Home4GiB_fairCPU2_970';O.mkdir(exist_ok=True);assert not (O/'enabled-typed-request.json').exists();(O/'original-unprefixed-Part-name-preparation.py').write_bytes(Path('/tmp/ds02-root970-original-unprefixed-Part-name-preparation.py').read_bytes());put(O/'prelaunch-frame-filename-correction.json',{'original_failure':'preparation AssertionError before request or launch; wrong PartNNNN filename assumption','actual_metadata_observation':'836 Part_NNNN.bi4 filenames; native receipt completed0 and unchanged','grounded_correction':'match actual numeric Part_ prefix; source121 bytes and scientific inputs unchanged','scientific_jobs_launched_by_failure':0})
for script,args,out in [('validate_fresh121.py',[],O/'actual-source121-validator.json'),('metadata_preflight.py',['--owner-metadata',q['actual_converter_owner']['path']],O/'actual-owner-converter-metadata-preflight.json')]:
 cp=subprocess.run([str(L/'.venv/bin/python'),str((W/prefix if script=='validate_fresh121.py' else P)/'scripts'/script),*args,'--report',str(out)],cwd=R,capture_output=True,text=True);put(O/(script+'.result.json'),{'returncode':cp.returncode,'stdout_tail':cp.stdout[-3000:],'stderr_tail':cp.stderr[-3000:]});assert cp.returncode==0
pre=load(O/'actual-owner-converter-metadata-preflight.json');assert pre['scope_sha256']==q['actual_converter_scope_sha256'] and pre['scope_schema']=='ds-data-02.physical-binding.v1' and pre['payload_opened'] is False
aid='root-stage1-f3-p0800-ay0360-actual884-full836-typed157-home4gib-root970';ar=D/'families/F3'/q['case_id']/aid;assert not ar.exists();controller=O/'fair-typed-controller.py';controller.write_bytes((root(963)/'fair-XMF-controller.py').read_bytes());fair=root(928)/'fair_CPU_dispatch.py';base=load(root(963)/'enabled-XMF-request.json');md=q['input_sha256'].copy()
for p,digest in md.items():assert sha(p)==digest
for p in [controller,fair,*[Path(x['path']) for x in adopted],O/'actual-source121-validator.json',O/'actual-owner-converter-metadata-preflight.json']:md[str(p)]=sha(p)
cmd=q['command'].copy();cmd[cmd.index('--staging-root')+1]='/tmp/ds02-nvme-typed-cache-root970';cmd[cmd.index('--current-attempt-id')+1]=f"F3/{q['case_id']}/{aid}";assert not Path('/tmp/ds02-nvme-typed-cache-root970').exists()
q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']});q.update(attempt_id=aid,attempt_root=str(ar),command=cmd,input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,root_actual_new_output_layout='flat trajectory.h5 and conversion-report.json; source157 private NVMe then capped Home publication',cpu_task_kind='conversion',cpu_threads=2,environment_policy=base['environment_policy'],estimated_storage_bytes=4*1024**3,case_credit=0);qp=O/'enabled-typed-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(fair),'case_credit':0});put(O/'source121-adoption-and-primary-metadata-review.json',{'source_commit':commit,'adopted_files':adopted,'source_byte_exact':True,'native884_completed0_numeric_frame_count':len(files),'expected_3D_particles':179208,'actual_converter_scope':pre,'legacy_scope_not_applicable_not_fabricated':True,'metadata_preflight_only_no_scientific_payload_IO':True,'historical_failed839_not_used_as_native_dependency':True,'actual_gate_requires_future_runtime_report':True,'future_output_hashes_null':q['future_outputs'],'private_NVMe_24GiB_cap_100GiB_floor':True,'Home_publish_4GiB_cap_500GiB_floor_2GiB_headroom':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(x['path']).relative_to(R)) for x in adopted]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register F3 actual884 full836 typed157 with explicit owner scope and hard Home cap','--',*paths],cwd=R,check=True);print(json.dumps({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
