from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');O=H/'root_stage1_f2_delegated095096_actual_existing_pipeline_visual_integration_813';O.mkdir(exist_ok=True)
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
assert not (O/'actual-integration-review.json').exists()
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_102.json')['accepted_decisions'].copy()
for n in [798,799,800,802,803,805,806,807,810]:prior+=load(root(n)/'actual-integration-review.json')['decisions']
assert len(prior)==129;ids={load(p).get('physical_case_id',load(p)['case_id']) for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior}
front=load(root(792)/'actual-frontier-correction.json');byid={x['case_id']:x for x in front['F2_actual16_complete_pipeline_cases']};decisions=[];supporting=[];adopted=[];commits=[]
for n,short in [(95,'be709153be8a839d9af92dbe2943272db750f922'),(96,'31f86b9c06f4a68e0a0cd14b8bf8b2ce1837453b')]:
 commit=subprocess.run(['git','rev-parse',short],cwd=W,capture_output=True,text=True,check=True).stdout.strip();commits.append(commit)
 src=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob(f'root_followup_{n:03d}_*'));rel=src.relative_to(W)
 files=subprocess.run(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,capture_output=True,text=True,check=True).stdout.splitlines();assert files
 for name in files:
  p=W/name;assert p.suffix in {'.json','.py','.md'};blob=subprocess.run(['git','show',f'{commit}:{name}'],cwd=W,capture_output=True,check=True).stdout;assert p.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True)
  if dst.exists():assert dst.read_bytes()==blob
  else:dst.write_bytes(blob)
  adopted.append(ref(dst))
 P=R/rel;idx=load(P/'metadata/visual-frontier-index.json');assert len(idx['batch_cases'])==2
 for entry in idx['batch_cases']:
  dpath=P/entry['decision_path'];d=load(dpath);cid=d['case_id'];f=byid[cid];assert d['status']=='visual-approved-by-delegated-agent' and d['reviewer']['agent']=='/root/production_recovery' and d['review_method']['tool']=='view_image';assert d['review_method']['contact_sheets_reviewed']==17 and d['review_method']['fullsize_keyframes_reviewed']==[0,65,115,400];assert all(d['visual_rejection_checks'][k] is False for k in ['early_termination_or_blank_tail','obvious_bad_initial_state','obvious_explosion_or_nonfinite_visual','obvious_severe_penetration_at_render_resolution','obvious_unbounded_fragmentation']) and d['visual_rejection_checks']['visual_review_passes']
  evidence={}
  for k,v in f['actual_completed_receipts'].items():
   assert sha(v['path'])==v['sha256'];r=load(v['path']);assert r['status']=='completed' and r['returncode']==0;assert r.get('case_id',r.get('request',{}).get('case_id'))==cid;evidence[k]=ref(v['path']);assert sha(d['bindings']['actual_receipts'][k]['path'])==d['bindings']['actual_receipts'][k]['metadata_sha256']
  for k in ['typed_report','xmf_manifest','render_report']:
   v=f[k];assert sha(v['path'])==v['sha256'];evidence[k]=ref(v['path'])
  t=load(f['typed_report']['path']);m=load(f['xmf_manifest']['path']);a=load(f['render_report']['path']);legacy=t['hash_scopes']['physical_condition_sha256'];assert legacy==f['actual_converter_physical_condition_sha256']==d['physical_condition_sha256']==m['physical_condition_sha256'];assert m['actual_converter_physical_condition_sha256'] is None;assert t['conversion_status']=='completed' and t['frames']==401 and t['particles']==418104 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['time_evidence']['strictly_increasing'] and t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=4
  ownerp=m['source_owner_metadata'];owner=load(ownerp);assert sha(ownerp)==m['source_owner_metadata_sha256'];metap=owner['source']['metadata']['path'];meta=load(metap);assert sha(metap)==owner['source']['metadata']['sha256'];payload=meta['physical_condition'];canonical=hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(',',':')).encode()).hexdigest();assert canonical==meta['physical_condition_sha256']==owner['source_plan_physical_condition_sha256'];pid=meta['physical_case_id'];assert pid==d['physical_case_id'];already_accepted=pid in ids;assert already_accepted or canonical not in hashes
  expected_rx=int(cid.split('RX')[1][:3])/100;expected_duration=int(cid.split('ROT')[1][:3])/100;assert payload['receiver_x_m']==expected_rx and payload['rotation_duration_s']==expected_duration and payload['rotation_final_angle_deg']==-105
  prep=load(m['prepared_input_report']);assert sha(m['prepared_input_report'])==m['prepared_input_report_sha256'];assert prep['actual_total_particles']==418104 and prep['generated_xml_particle_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21114} and prep['actual_generated_constants']['data2d']['value']=='false';raw=load(Path(prep['prefix']).parent.parent/'execution-receipt.json');assert raw['status']=='completed' and raw['returncode']==0 and raw['request']['case_id']==cid
  qa=load(m['initial_qa_report']);assert sha(m['initial_qa_report'])==m['initial_qa_report_sha256'] and qa['status']=='pass' and all(qa['checks'].values())
  assert m['frames']==401 and m['particles']==418104 and m['source_h5_sha256']==t['output_sha256'];xf=m['xdmf'];assert sha(xf)==m['xdmf_sha256'];grids=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(grids)==401 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='418104 3' for g in grids)
  assert a['frames']==a['source_frames']==401 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(f['xmf_manifest']['path']) and a['xdmf']==xf and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf) and a['source_h5_sha256']==t['output_sha256']
  fs=t['lifecycle']['frame_summary'];ads=a['frame_diagnostics'];assert len(fs)==len(ads)==401 and t['lifecycle']['introduced_ids']=='rejected';maximum=max(f['missing_particles'] for f in fs);assert maximum==d['uid_and_finiteness_evidence']['framewise_missing_particles_max'] and fs[-1]['missing_particles']==d['uid_and_finiteness_evidence']['framewise_missing_particles_final']
  assert all(x['finite_positions_active'] and x['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in x['finite_fields'].values()) for x in ads);assert all(x['missing_particles']==y['missing'] for x,y in zip(fs,ads))
  contacts=d['bindings']['render']['contact_sheets'];keys=d['bindings']['render']['keyframes'];assert len(contacts)==17 and len(keys)==4 and [x['frame'] for x in keys]==[0,65,115,400]
  for v in contacts+keys:assert Path(v['path']).suffix=='.png' and sha(v['path'])==v['sha256']
  out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':d['status'],'family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'physical_condition':payload,'source_review_commit':commit,'source_review_decision':ref(dpath),'visual_reviewer':'/root/production_recovery','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':d['visual_observations'],'source_scope_correction':{'Root792_and_agent_digest_label':legacy,'actual_converter_legacy_scope_sha256':legacy,'source_canonical_physical_condition_sha256':canonical,'source_owner':ref(ownerp),'source_condition_metadata':ref(metap),'reason':'Root792 used the actual converter legacy namespace for its canonical label; this new sidecar preserves that evidence and records the true source physical payload digest. No raw files changed.'},'actual_completed_metadata_evidence':evidence,'verified_PNG_hashes':{'contact_sheets':contacts,'key_frames':keys},'actual_frames':401,'actual_particles':418104,'actual_fluid_particles':21114,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':maximum,'final_missing_particle_count':fs[-1]['missing_particles'],'final_missing_UIDs':fs[-1]['missing_id_first'],'transient_missing_frame_count':sum(f['missing_particles']>0 for f in fs),'lifecycle_limitation':'Late native identity exclusions retained without filling; causes unqualified; no visually missing bulk in delegated review','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':0 if already_accepted else 1,'existing_case_visual_evidence_refresh_only':already_accepted,'previous_count':129+len(decisions),'resulting_count':129+len(decisions)+(0 if already_accepted else 1)}
  dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);(supporting if already_accepted else decisions).append(str(dp));ids.add(pid);hashes.add(canonical)
put(O/'actual-integration-review.json',{'source_commits':commits,'source_adopted_byte_exact':True,'adopted_files':adopted,'previous_count':129,'resulting_count':129+len(decisions),'independent_case_increment':len(decisions),'decisions':decisions,'already_accepted_case_supporting_sidecars_no_duplicate_credit':supporting,'root_only_metadata_integration':True,'source_namespace_correction_preserved_in_each_decision':True,'actual_four_corner_domain_inherited_from_root803':ref(root(803)/'actual-integration-review.json')})
print(json.dumps({'accepted':129+len(decisions),'new_cases':len(decisions),'existing_case_review_sidecars':len(supporting)}))
