from pathlib import Path
import json,hashlib,subprocess,xml.etree.ElementTree as ET,math,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));cid='F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025';pid=cid
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):assert sha(e['path'])==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
wpath=root(951)/f'wrapper-requests/{cid}-enabled-wrapper.json';w=load(wpath);out=Path(w['home_output']);rp=out.parent/'execution-receipt.json'
if not rp.exists() or load(rp).get('status')=='running':print('WAIT same original951 actual receipt has no terminal; no writes');raise SystemExit(0)
rc=load(rp);assert rc['status']=='completed' and rc['returncode']==0 and rc['request']['case_id']==cid and w['expected_frames']==241 and w['expected_particles']==417505
basep=root(1283)/'actual-lastF6-full241-own-UID-N3-state0-scope-readiness-with-quantified3fluid-omissions.json';base=load(basep);chain={e['stage']:e for e in base['actual_producer_chain']};evidence={'render_receipt':ref(rp),'render_report':ref(out/'paraview-full-animation-report.json'),'render_publish_receipt':ref(out/'render-publish-receipt.json'),'original951_loaded_wrapper':ref(wpath),'original951_outer_request':ref(root(951)/f'requests/{cid}-render-request.json')};receipts={}
for stage,e in chain.items():
 er=e['execution_receipt'];checked(er);r=load(er['path']);assert r['status']=='completed' and r['returncode']==0 and r['request']['case_id']==cid and r['request_sha256']==e['producer_request_sha256'];receipts[stage]=r;evidence[stage+'_receipt']=er
 if 'metadata_report' in e:checked(e['metadata_report']);evidence[stage+'_report']=e['metadata_report']
t=load(chain['typed_conversion']['metadata_report']['path']);x=load(chain['normal_n3_xmf']['metadata_report']['path']);mp=Path(chain['normal_n3_xmf']['metadata_report']['path']);xp=Path(x['xdmf']);evidence['XMF_XML']=ref(xp);nq=receipts['full241_native']['request'];canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert canonical==base['native_canonical_physical_condition_sha256']=='13c383a2ba67e520613cacb83f595a1c0745b2ac8ad2c67c9c6beaf43a6e4640';assert legacy==x['physical_condition_sha256']==base['typed_XMF_producer_scope_sha256']=='a92da26df8424649239124012c23f1f893327573a302dc6914e962ceec5a0d90' and canonical!=legacy
assert nq['physical_case_id']==x['physical_case_id']==pid and x['case_id']==cid and Path(w['manifest'])==mp;mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
for ns in mask:assert mask[ns]['source_plan_condition_sha256']=={'present':True,'value':'c503e879744b5f3e533ebf193b888d7cea57c3cf8a3e0a5c64a831ba8013fc41'} and mask[ns]['source_plan_physical_condition_sha256']=={'present':False,'value':None}
r=load(evidence['render_report']['path']);pub=load(evidence['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(evidence['render_report']['path'])
assert t['frames']==x['frames']==r['frames']==r['source_frames']==241 and t['particles']==x['particles']==417505 and t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)';assert all(e['passed'] and e['identity_type_mk_exact'] for e in t['partvtk_validation']['frames']);assert t['lifecycle']['introduced_ids']=='rejected'
assert r['all_frames_rendered'] and not r['diagnostic_only'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0 and r['source_h5_read_only'];assert r['manifest_sha256']==sha(mp) and r['input_manifest']==str(mp) and x['xdmf_sha256']==sha(xp)==r['xdmf_sha256_before']==r['xdmf_sha256_after'] and r['xdmf']==str(xp);assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256'];hp=t['output_hdf5'];assert Path(hp).is_file()
for rec in [receipts['normal_n3_xmf'],rc]:
 for ih in [rec['input_hashes_at_launch'],rec['input_hashes_after_run']]:assert ih[hp]==t['output_sha256']
for ih in [rc['input_hashes_at_launch'],rc['input_hashes_after_run']]:assert ih[str(mp)]==sha(mp) and ih[str(xp)]==sha(xp)
assert t['source_provenance']['solver_receipt']['path']==chain['full241_native']['execution_receipt']['path'] and t['source_provenance']['solver_receipt']['sha256']==chain['full241_native']['execution_receipt']['sha256'];fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];times=x['actual_time_s'];grids=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]');assert len(fs)==len(ds)==len(times)==len(grids)==241 and times==[e['time'] for e in fs]==[e['actual_time_s'] for e in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]==12.00014173182893 and all(math.isfinite(ti) for ti in times) and all(a<b for a,b in zip(times,times[1:]));assert r['frame_selection']==list(range(241)) and x['fields']['position']['shape']==x['fields']['velocity']['shape']==[241,417505,3]
for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
 assert f['frame']==d['frame']==i and f['active_particles']==d['active'] and f['missing_particles']==d['missing'] and f['active_particles']+f['missing_particles']==417505 and f['type_counts']['0']==73441 and f['type_counts']['1']==0 and f['type_counts']['2']==16384 and f['type_counts']['3']==327680-f['missing_particles'];assert f['missing_type_counts']=={'0':0,'1':0,'2':0,'3':f['missing_particles']};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(e['finite_active'] and e['nonfinite_active']==0 for e in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='417505 3';v=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='417505 3'
missing=base['lifecycle_omissions'];assert sum(f['missing_particles'] for f in fs)==missing['cumulative_particle_frame_omissions']==700 and max(f['missing_particles'] for f in fs)==missing['max_missing_per_frame']==3 and next(f['frame'] for f in fs if f['missing_particles'])==missing['first_missing_frame']==7 and fs[-1]['missing_id_first']==missing['producer_attested_final_Idp_sample'] and fs[-1]['missing_ids_sha256']==missing['final_missing_Idp_digest_producer_attested'];assert missing['unknown_missing_location_state_cause']
rigidp=root(1305)/'F6-FINAL48-FULLTIME-RIGID-MOTION-DELIVERY.json';rig=load(rigidp);a=next(e for e in rig['rows'] if e['physical_case_id']==pid);assert a['actual_native_condition_sha256']==canonical
for k in ['actual_export_receipt','actual_export_report','actual_runner_request','actual_complete_native_receipt']:checked(a[k]);evidence['rigid_'+k]=a[k]
rr=load(a['actual_export_receipt']['path']);report=load(a['actual_export_report']['path']);parse=report['parse'];assert rr['status']=='completed' and rr['returncode']==0 and report['status']=='completed' and report['returncode']==0 and parse['rows_examined']==parse['rigid_fields_finite_rows']==241 and parse['required_rigid_field_count']==17 and parse['part_values_observed']==list(range(241)) and parse['part_column_contract']['frame_identity_from_part'];assert parse['native_time_comparison']['native_times_s']==times and parse['native_time_comparison']['within_tolerance'] and parse['native_time_comparison']['tolerance_s']==1e-6;actual_times=parse['official_times_s'];delta=max(abs(a-b) for a,b in zip(actual_times,times));assert len(actual_times)==241 and delta<=1e-6 and delta==a['max_abs_actual_native_time_delta_s'];csv=Path(report['output']['csv']);assert csv.is_file() and csv.stat().st_size==report['output']['bytes']==a['official_rigid_motion_CSV']['bytes_stat_verified'];assert report['output']['sha256']==a['official_rigid_motion_CSV']['sha256_producer_attested']
assert len(r['outputs']['contact_sheets'])==11 and sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(241)];assert w['keyframe_indices']==[0,30,60,90,120,150,180,210,240];assert all((Path(r['outputs']['frames_dir'])/f'frame_{i:04d}.png').is_file() for i in [0,1,30,60,90,120,150,180,210,240]);assert os.statvfs('/home/jade').f_bavail*os.statvfs('/home/jade').f_frsize>=500*2**30
O=H/'root_stage1_lastF6_actual951_full241_render_particle_UID_N3_three_fluid_omissions_fulltime_rigid_part_times_scope_independent_previsual_QI_1341';assert not O.exists();O.mkdir();proof=O/'actual951-lastF6-full241-render-plus-rigid-QI-three-fluid-omissions-scope-previsual-proof.json';put(proof,{'schema':'ds02.main.lastF6.own241-render-particle-rigid-previsual-QI.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'case_id':cid,'physical_case_id':pid,'actual_completed_metadata_evidence':evidence,'prior_complete_scientific_integrity_proof':ref(basep),'frames':241,'particles':417505,'actual_initial_type_counts':{'fixed':73441,'moving':0,'floating':16384,'fluid':327680,'total':417505},'actual_terminal_type_counts':{'fixed':73441,'moving':0,'floating':16384,'fluid':327677,'total':417502},'all241_geometry_velocity_N3_actual_times_UID_identity_finite_active_states_verified':True,'all_native_UIDs_active_each_frame':False,'lifecycle_omissions':missing,'actual_time_window_s':[times[0],times[-1]],'native_canonical_condition_sha256':canonical,'typed_XMF_actual_producer_condition_sha256':legacy,'actual_native_XMF_plan_field_namespaces':mask,'source_plan_condition_field_not_substituted_into_absent_physical_plan_field':True,'actual_fulltime_rigid_export_metadata':a,'rigid_full241_Part0to240_17_fields_finite_verified':True,'rigid_actual_Time_vs_particle_native_tolerance_s':1e-6,'rigid_actual_Time_max_abs_delta_s':delta,'rigid_actual_times_not_resampled':True,'official_rigid_CSV_payload_read_or_hashed_by_main':False,'physical_mass_kg':base['physical_mass_kg'],'native_support_mass_kg':base['native_support_mass_kg'],'mass_discrepancy_retained_no_rescale':True,'state0_declared_angular_velocity_rad_s':base['state0_declared_angular_velocity_rad_s'],'state0_observed_angular_velocity_rad_s':base['state0_observed_angular_velocity_rad_s'],'no_particle_v0_to_omega_inference':True,'source_wrapper_keyframes_original9_preserved':w['keyframe_indices'],'delegated_review_requested_published_keys10':[0,1,30,60,90,120,150,180,210,240],'published_contacts':11,'visual_status':'pending delegated personal11contacts10keys','strict_container_guarantee':False,'subDP_precision_not_claimed':True,'q_n_granted':False,'q_e_granted':False,'case_credit':0,'scientific_payload_IO':False});(O/'independent-review-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bind lastF6 full241 particle render and actual rigid time with three omissions retained','--',*paths],cwd=R,check=True);print(json.dumps({'proof':ref(proof),'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
