from pathlib import Path
import json,hashlib,copy,datetime,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_272.json';cp=load(cpfile);assert cp['checkpoint']==272 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==309
qip=next(root(1355).glob('*proof.json'));qi=load(qip);assert qi['case_id']=='F3_STAGE1_DP006_P0800_AY0360' and qi['new_case_credit']==0
qp=ref(qip);published=load(root(987)/'controller-result.json');assert published['status']=='completed' and published['returncode']==0
proof987={'original':987,'case_id':qi['case_id'],'physical_case_id':qi['physical_case_id'],'actual_controller_result':ref(root(987)/'controller-result.json'),'own_full836_QI':qp,'case_credit':0,'source_personal_review':177}
live=[]
roles=[]
for original,pid,start,future in [(1164,604869,'213723590',1359),(1188,613708,'213820080',1363)]:
 F=root(original);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre)
 for e in j.values():
  if isinstance(e,dict) and 'path' in e and 'sha256' in e:check(e)
 t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);sr=t['source_provenance']['solver_receipt'];check(sr);nr=load(sr['path']);nq=nr['request'];assert nr['status']=='completed' and nr['returncode']==0
 br=load(j['actual_bed_receipt']['path']);b=load(br['request']['binding']);assert br['status']=='completed' and br['returncode']==0
 canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert len({canonical,legacy,sd})==3 and x['physical_condition_sha256']==x['canonical_physical_condition_sha256']==canonical
 assert sha(b['source_definition'])==b['source_definition_sha256']==sd
 mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
 assert mask['native']['source_plan_condition_sha256']==mask['XMF']['source_plan_condition_sha256']=={'present':False,'value':None}
 assert mask['native']['source_plan_physical_condition_sha256']=={'present':True,'value':canonical} and mask['XMF']['source_plan_physical_condition_sha256']=={'present':True,'value':sd}
 w=load(F/'enabled-render-wrapper.json');assert w['expected_frames']==t['frames']==x['frames']==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
 assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
 if original==1188:assert (canonical,legacy,sd)==('e481fc652a012f05d9532517cf98fc960045cee2e0fde297cc1eb9bdfeba0f61','58adf369413974a2f5498028352e44cec6c05e0ebf40ca65e9dd52aae68399d4','e3f0515522685a28ff3b1f6ab3a59625e3c1adba3db9e089c9fb7e41a889cf86')
 P=Path(f'/proc/{pid}');ls=None;terminal=F/'controller-result.json'
 if P.exists():
  st=P.joinpath('stat').read_text().rsplit(')',1)[1].split();assert st[19]==start;cmd=P.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);ls={'pid':pid,'startticks':start,'state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 live.append({'original':original,'physical_case_id':w['physical_case_id'],'same_actual_process':ls,'authoritative_terminal':ref(terminal) if terminal.exists() else None,'future_own_QI_root':future,'future_own_QI_proof':None,'no_restart':True,'case_credit':0})
 roles.append({'original':original,'physical_case_id':w['physical_case_id'],'native_canonical_sha256':canonical,'typed_legacy_sha256':legacy,'bed_SourceDef_FILE_sha256':sd,'actual_native_XMF_plan_field_namespaces':mask,'source_definition':ref(b['source_definition']),'previsual_dependency_review':ref(pre),'actual_wrapper':ref(F/'enabled-render-wrapper.json')})
guards=[]
for key,p in [('runtime_v2_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:
 assert sha(p)==cp['unmodified_guards'][key];guards.append(ref(p))
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current309_twoF5_personal_accepted_F3_actual987_full836QI_nextF5_1164_1188_same_live_exact_plan_SourceDef_durable801QI_1362';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_273.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1188_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1188-full801-own-QI1363.py').read_bytes());pp=O/'current309-F3-published836QI-next-two-originalF5-live-and-durable1188-QI-readiness.json'
put(pp,{'schema':'ds02.current309-F3ownQI-next-twoF5-durable.v1','at_utc':now.isoformat(),'actual_F3_original987_published_own_QI_visual_pending':proof987,'next_same_original_actual_live_processes':live,'next_originalF5_raw_namespace_proofs':roles,'both_next_F5_native_physical_plan_canonical_XMF_physical_plan_SourceDef_independently_verified':True,'durable_original1188_only_QI_entrypoint':ref(entry),'commands':[['python3','-B',str(entry),'1188','1363']],'guard142_runtime_strict_unchanged':guards,'do_not_rerun_finished_QI':True,'scientific_payload_IO':False,'case_credit':0,'no_new_scientific_or_render_jobs':True})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=273,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active309/336: actualF5 1150/1157 source210/191 personally reviewed and accepted once; F5=32. OriginalF3 987 actual completed0/published/own836QI1355, source177 personally reviewing. Next originalsF5 1164 M114T085 and1188 M110T095 same actual PV handles; futureown801QI1359/1363 durable, personalreviews source211/192 assigned. Source176 completion-only F3builder available but not yet main audited/integrated. Home500GiB floor and historical cleanup534.4086GiB retained.',previous_goal_turn_classification='PROGRESS: two distinct F5 cases personally reviewed and accepted, total309; originalF3 987 full836 actual0/publication independently checked, personalreview activated. Next originalF5 1188 started by unchanged registered queue, raw nativephysical-plan canonical/XMFphysical-plan SourceDef FILE checked and durable futureown801QI1363 prepared without running it.')
new['actual_progress']['actual987_full836_own_QI']=qp;new['actual_progress']['current309_F3published_QI_nextF5two_live_durable1188']=ref(pp);new['source_agents']['production_recovery']='fresh177 original987 actual0/published/full836 ownQI1355 provided; personal35contacts9keys in progress';new['source_agents']['f5_bed_recovery']='fresh211 originalF5 1164 M114T085 waiting actual0/pub and ownQI1359; personally34contacts9keys afterwards';new['source_agents']['f6_endpoint_initial_qa']='fresh192 originalF5 1188 M110T095 waiting actual0/pub and ownQI1363; personally34contacts9keys afterwards'
new['next_executable_tasks']=['Adopt source177 originalF3 987 personal35contacts9keys after read-only validator and exact finalcommit; actual native and XMF both plan fields remain absent/null, old outer801/194427 preserved as historical only.','Observe originalF5 1164 PID604869/start213723590 and1188 PID613708/start213820080; completed0/pub then run durable ownQI1359/1363 once and supply SHA to source211/192.','Read entire source176 F3 completion-only final48 builder/validator, check code and status/primary/runtime-unknown boundaries; current42 readiness must not output partial final48 delivery.','Continue original registered cases toward336; final F2/F3/F5 directories only after real48 accepted per family; retain Home500GiB floor and cumulative534.4086GiB cleanup evidence.'];put(np,new)
ip=root(1358)/'full336-current309-actual-final48-delivery-progress-index.json';index=load(ip);row=next(r for r in index['cases'] if r['physical_case_id']==qi['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=qp,current_personal_review_source=177,case_credit=0,prior_controller_observations_are_historical_not_current=True)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[qi['physical_case_id']],current309_F3published_QI_nextF5two_live_durable1188=ref(pp));assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==309;put(O/'full336-current309-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: track current309 F3 own836 QI and two original F5 live cases','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':273,'accepted':309,'next_live':live,'free_GiB':free,'GPUh':gpu,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
