from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def check(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
commit='391662559fe8fad1329533c9abd8d537e2777b40';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_165_f3_assigned_f5_m115_t080_personal_visual_review_v1');P=W/prefix
ns=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(ns)==5;blobs={};before={}
for n in ns:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b;before[n]=sha(W/n)
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh165.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in ns}
v=load(P/'metadata/f5-m115-t080-visual-review.json');png=load(P/'metadata/png-evidence/f5-m115-t080.json');qp=root(1275)/'actual1186-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qp);cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];SourceDef=qi['actual_SourceDef']['sha256']
assert cid==v['case_id']=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1' and pid==v['physical_case_id']=='F5_COMPACT_RUNUP_RECOVERY_C082S1_M115_T080';assert v['actual_family_id']=='F5' and v['assigned_worktree_family_id']=='F3' and v['reviewer']=='production_recovery';assert v['status']=='visual-approved-by-delegated-agent' and v['case_credit']==v['independent_case_increment']==0 and not any(v[k] for k in ('numerical_precision_accepted','q_n_granted','q_e_granted'))
assert v['main_qi_binding']['path']==str(qp) and v['main_qi_binding']['sha256']==sha(qp);assert qi['full_frames']==801 and qi['particles']==194427 and qi['all_native_UIDs_active_each_frame'] and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['all801_native_Part_BI4_filenames_stat_checked']
roles=v['physical_scope_roles'];assert roles['canonical_actual_native_request_condition_sha256']==canonical and roles['actual_converter_legacy_scope_sha256']==legacy and roles['xmf_and_bed_sourcedef_sha256']==SourceDef
assert not roles['actual_native_source_plan_field_present'] and roles['actual_native_source_plan_condition_sha256'] is None and not qi['actual_native_source_plan_condition_field_present'] and qi['actual_native_source_plan_condition_sha256'] is None;assert qi['XMF_source_plan_condition_field_sha256']==qi['bed_declared_source_plan_field_sha256']==SourceDef and len({canonical,legacy,SourceDef})==3;check(roles['source_def'])
stages=qi['actual_completed_metadata_evidence']
for name,e in stages.items():
 check(e)
 if name.endswith('_receipt') and name!='render_publish_receipt':
  r=load(e['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid
check(v['actual_terminal']['execution_receipt']);assert v['actual_terminal']['execution_receipt']==stages['render_receipt'];check(v['actual_terminal']['atomic_publish']);assert v['actual_terminal']['atomic_publish']['path']==stages['render_publish_receipt']['path']
rb=v['render_binding']
for name,e in rb.items():
 if isinstance(e,dict) and 'path' in e:check(e)
assert rb['report']['path']==stages['render_report']['path'] and all(rb['manifest'][k]==stages['xmf_manifest'][k] and rb['xmf'][k]==stages['xmf_xml'][k] for k in ('path','sha256'))
report=load(rb['report']['path']);manifest=load(rb['manifest']['path']);pub=load(rb['publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==rb['report']['sha256'];assert report['manifest_sha256']==rb['manifest']['sha256'] and report['xdmf']==manifest['xdmf']==rb['xmf']['path'] and report['xdmf_sha256_after']==manifest['xdmf_sha256']==rb['xmf']['sha256'];assert report['frames']==report['source_frames']==manifest['frames']==801 and report['all_frames_rendered'] and report['actual_times_preserved_exactly'] and report['native_identity_axis_preserved'] and report['nonfinite_active_states']==0
assert v['production_dimensions']['actual_time_window_s']==qi['actual_time_window_s'];assert v['visual_review']['contact_sheets']['all_viewed'] and v['visual_review']['keyframes']['all_viewed'] and v['visual_review']['contact_sheets']['view_method']==v['visual_review']['keyframes']['view_method']=='view_image';assert v['retained_limits']['strong_runup_not_claimed'] and v['retained_limits']['historical_negative_evidence_retained']
entries=png['entries'];contacts=sorted((e for e in entries if e['role']=='contact_sheet'),key=lambda e:e['contact_index']);keys=sorted((e for e in entries if e['role']=='event_keyframe'),key=lambda e:e['frame_index']);assert len(entries)==43 and len(contacts)==34 and len(keys)==9;assert [e['path'] for e in contacts]==report['outputs']['contact_sheets'] and [e['frame_index'] for e in keys]==list(range(0,801,100));out=Path(pub['published_output_root']);published={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in entries:
 assert e['viewed'] and e['view_method']=='view_image';check(e);assert str(Path(e['path']).relative_to(out))==e['relative_path'];pe=published[e['relative_path']];assert e['sha256']==pe['sha256'] and e['bytes']==pe['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_231.json';cp=load(cpfile);assert cp['checkpoint']==231 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==289 and cp['accepted_per_family']['F5']==20;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {r.get('physical_case_id',r['case_id']) for r in old}
ip=root(1281)/'full336-current289-actual-final48-delivery-progress-index.json';idx=load(ip);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical;assert all(r.get('native_request_scope',{}).get('sha256')!=canonical for r in idx['cases'] if r.get('accepted_decision'))
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(v['created_at_utc'])<=now;raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
O=H/'root_stage1_source165_assignedF3_actualF5_M115T080_actual1186_full801QI_personal43PNG_sharedcase_uniquePID_nativeplan_absence_visual_acceptance_1284';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_232.json';assert not list(H.glob('root*_1284')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
vp=O/'source165-byte-exact-readonly-validation-and-main-actual43PNG-proof.json';put(vp,{'source_commit':commit,'source_SHA_before_after':before,'source_bytes_unchanged':True,'adopted_source_files':adopted,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'main_all43_actual_published_PNG_SHA_and_bytes_independently_verified':True,'main_completed_stage_metadata_refs_checked_against_ownQI1275':True,'source_assignment_family_F3_is_not_actual_case_family_F5':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_XMF_SourceDef_scope_sha256':SourceDef,'source_assigned_agent_family':'F3','review_model_from_task_assignment':'GPT-5.6 Luna max','source_reviewer':'production_recovery','source_visual_review':ref(R/prefix/'metadata/f5-m115-t080-visual-review.json'),'source_review_PNG_evidence':ref(R/prefix/'metadata/png-evidence/f5-m115-t080.json'),'independent_full801_QI':ref(qp),'actual_completed_metadata_evidence':stages,'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_zero_bins_not_numerical_precision_or_subDP_absence':True,'actual_native_plan_field_present':False,'actual_native_plan_field_value':None,'actual_XMF_plan_field_value':SourceDef,'actual_bed_plan_field_value':SourceDef,'canonical_legacy_SourceDef_roles_distinct':True,'shared_mother_case_id_is_not_duplicate_physical_case_id':True,'deduplication_based_on_unique_physical_case_id_and_own_native_condition':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_review':v['visual_review'],'visual_limits':v['retained_limits'],'strong_runup_not_claimed':True,'historical_precision_and_AB_negative_evidence_retained':True,'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source165-actual1186-full801-QI-personal-visual-adoption.json';put(proof,{'source_validation':ref(vp),'independent_QI':ref(qp),'new_visual_decision':ref(dp),'historical_negatives_and_native_plan_absence_preserved':True,'actual43PNG_bound_to_atomic_publish':True,'shared_mother_case_id_does_not_erase_distinct_actual_native_physical_case_id':True,'case_credit':1,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp['accepted_per_family']['F5']+=1;newcp.update(checkpoint=232,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=290,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source201 actualF5 M098T095 accepted289 in predecessor. Currentturn source180 lastF6 ownfull241UID/N3/state0 and mass roles closed retaining3fluid omissions/first7/234frames/700events; source165 actualF5 M115T080 full801ownQI1275 +43personallyviewedPNG accepted290/F5=21. Samecase mother identity distinguished from uniquePID; nativeplan absence vs XMFbedSourceDef preserved.',authorized_work_state='Active290/336,46 pending; F5=21,F1/F4/F7=48,F2/F3=39,F6=47. Original1156 M098T085 and1177 M114T095 actualrenderlive; fresh202/181 personalreview after publication; lastF6 original951 live.')
newcp['actual_progress']['source165_F5_actual1186_visual_acceptance']=ref(proof);newcp['actual_progress']['source180_lastF6_full241_ownreadiness_missing3fluid_state0_mass_scope']=ref(root(1283)/'actual-lastF6-full241-own-UID-N3-state0-scope-readiness-with-quantified3fluid-omissions.json');newcp['source_agents']['production_recovery']='fresh165 actual1186 accepted F5=21; ready next owned task';newcp['source_agents']['f5_bed_recovery']='fresh202 original1156 corrected privatepath observer626frames at02:38Z; absolute observerdeadline02:53:06Z';newcp['source_agents']['f6_endpoint_initial_qa']='fresh180 lastF6 ownreadiness adopted; fresh181 actualF5 M114T095 original1177 live observer'
newcp['next_executable_tasks']=['After original1156 publication execute prepared full801QI1278 and adopt fresh202 personal43PNG.','After original1177 publication execute prepared full801QI1282 preserving nativeplan canonical vs XMFbed SourceDef and adopt fresh181 personal43PNG.','Continue remaining F2/F3 original full-event render queue; lastF6 original951 source180 ownreadiness complete with3fluid missing unknowns preserved.','Finish F5 actual24 subset delivery when actual accepted prefix reaches24; current actual21, no planned-case substitution.'];assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==290;put(nextcp,newcp)
idx.update(previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nextcp),at_utc=now.isoformat(),accepted_independent_physical_cases=290,registered_pending_independent_physical_cases=46,new_case_credit=1);targets[0].update(status='visual-approved-in-checkpoint232',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qp));idx['actual_unaccepted_completed0_published_physical_cases']=[e for e in idx['actual_unaccepted_completed0_published_physical_cases'] if (e.get('physical_case_id') if isinstance(e,dict) else e)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==290;put(O/'full336-current290-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept distinct F5 m115 t080 full801 preserving native plan absence and scope roles','--',*paths],cwd=R,check=True);print({'checkpoint':232,'accepted':290,'F5':21,'remaining':46,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
