from pathlib import Path
import json,hashlib,time,subprocess,fcntl,shutil,xml.etree.ElementTree as ET
O=Path(__file__).parent;R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def root(n):return next(H.glob(f'root*_{n}'))
SCIENCE={'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'}
def sha(p):
 p=Path(p);assert p.suffix.lower() not in SCIENCE;return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');t.replace(p)
P=L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_138_stage1_f5_remaining10_full801_downstream_disabled_v1';xw=P/'workers/export_xmf_legacy_aware_fresh138.py';original_bed=P/'workers/bed_audit_full801_fresh138.py';bw=O/'next34_identity_bound_original_bed_audit.py';assert sha(xw)=='aeccc3204d751250bd94ffab704ed65c2c691c4739f4b2f5e0d51aefb21b4e3c' and sha(original_bed)=='89be048da1df6bae49627308edb35a8a1936bc0888259cb5ab3d195307b550e2';source=root(823)/'source-plan.json';byid={c['case_id']:c for c in load(source)['candidates']};template=load(next((root(827)/'requests').glob('*request.json')));profile={k:v for k,v in template.items() if k.startswith('root_') or k=='resource_window'};done=set();results=[];partial=False

def run_stage(c,stage,binding,h5,h5sha,md):
 bp=O/'bindings'/(c['tag']+'-'+stage+'-actual-ready-binding.json');put(bp,binding);worker=xw if stage=='xmf' else bw;paths=[bp,worker,original_bed,xw,source,O/'controller-contract.json',Path(__file__),L/'.venv/bin/python',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',next(H.glob('root*064'))/'resource-window-approval.json'];input_md={**md,**{str(p):sha(p) for p in paths},str(h5):h5sha};aid='root-stage1-f5-next34-'+c['tag'].lower()+'-actual872-full801-'+stage+'-root873';ap=D/'families/F5'/c['case_id']/aid;assert not ap.exists()
 if stage=='xmf':cmd=[str(L/'.venv/bin/python'),str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xdmf']
 else:cmd=[str(L/'.venv/bin/python'),str(worker),'--binding',str(bp),'--trajectory-h5',str(h5),'--xdmf',binding['xdmf'],'--output-dir','{attempt_root}/audit-output']
 q={**profile,'schema':'ds02.runner-request.v2','family_id':'F5','case_id':c['case_id'],'physical_case_id':c['physical_case_id'],'physical_condition_sha256':c['physical_condition_sha256'],'attempt_id':aid,'attempt_root':str(ap),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':2,'max_wall_seconds':7200 if stage=='bed' else 1800,'estimated_storage_bytes':1024**3,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'command':cmd,'input_files':sorted(input_md),'input_sha256':input_md,'binding':str(bp),'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'root_review_required':False,'q_n':'not_granted','production_approval':'none','case_credit':0};qp=O/'requests'/(c['tag']+'-'+stage+'-request.json');put(qp,q)
 with (D/'runtime/stage1-fullnative-conversion-dispatch.lock').open('a') as lock:
  fcntl.flock(lock,fcntl.LOCK_EX)
  while True:
   ledger=load(D/'runtime/resource-ledger.json');reserved=sum(x.get('new_storage_bytes',0) for x in ledger['reservations'])
   if sum(x.get('cpu_threads',0) for x in ledger['reservations'])+4<=64 and shutil.disk_usage('/home/jade').free-reserved-q['estimated_storage_bytes']-16*1024**3>=ledger['limits']['home_min_free_bytes']:break
   time.sleep(3)
  p=subprocess.run([str(L/'.venv/bin/python'),str(root(142)/'launch.py'),str(qp)],cwd=L,capture_output=True,text=True)
 rp=ap/'execution-receipt.json';r=load(rp) if rp.exists() else {};out={'tag':c['tag'],'case_id':c['case_id'],'stage':stage,'request':str(qp),'actual_receipt':str(rp),'status':r.get('status'),'returncode':r.get('returncode'),'launcher_returncode':p.returncode,'actual_completed0':p.returncode==0 and (r.get('status'),r.get('returncode'))==('completed',0),'launcher_error':p.stderr[-1500:]};print(json.dumps(out),flush=True);return ap,out
while len(done)<22 and not partial:
 ready=[]
 for tp in (root(872)/'requests').glob('*typed-request.json'):
  tq=load(tp);cid=tq['case_id'];rp=Path(tq['attempt_root'])/'execution-receipt.json'
  if cid in done or not rp.exists():continue
  r=load(rp)
  if (r['status'],r.get('returncode'))==('completed',0):ready.append((tp,tq,rp))
  elif r['status'] in ['failed','terminated','aborted']:partial=True;put(O/'actual-typed-failure-hold.json',{'receipt':ref(rp),'no_restart':True})
 if partial:break
 if not ready:
  terminal=root(872)/'controller-result.json'
  if terminal.exists():
   r=load(terminal)
   if r['actual_full801_typed_pass_count']<22:partial=True;break
   assert len(done)==22,'Full upstream typed complete without consumer requests'
  else:
   lc=load(root(872)/'controller-launch-process.json');p=Path('/proc')/str(lc['pid']);assert p.exists(),'Owned typed controller missing without terminal evidence';f=(p/'stat').read_text().split(') ',1)[1].split();assert f[0]!='Z' and f[19]==lc['proc_start_ticks']
  time.sleep(3);continue
 tp,tq,trp=sorted(ready,key=lambda x:x[1]['case_id'])[0];cid=tq['case_id'];c=byid[cid];cp=Path(tq['attempt_root'])/'typed/conversion-report.json';t=load(cp);legacy=t['hash_scopes']['physical_condition_sha256'];scope=t['hash_scopes']['physical_condition'];assert t['conversion_status']=='completed' and t['frames']==801 and t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and t['time_evidence']['last_s']>=16 and legacy==tq['actual_converter_scope_sha256_prospective'] and scope['schema']=='legacy-owner-scope.v0' and scope['semantic_binding_status']=='legacy_incomplete; no cross-resolution physical claim';h5=Path(t['output_hdf5']);assert h5==Path(tq['attempt_root'])/'typed/trajectory.h5';nr=Path(tq['native_receipt']);n=load(nr);gr=Path(tq['gencase_receipt']);ppr=Path(tq['gencase_prepared_report']);prep=load(ppr);qr=Path(tq['initial_qa_receipt']);qar=Path(tq['initial_qa_report']);qa=load(qar);xml=Path(prep['prefix']+'.xml');assert sha(xml)==prep['xml_sha256'] and (n['status'],n['returncode'])==('completed',0);assert c['physical_condition_sha256']==tq['physical_condition_sha256']!=legacy and sha(c['source_xml'])==c['source_xml_sha256'];md={str(p):sha(p) for p in [tp,trp,cp,nr,gr,ppr,qr,qar,xml,Path(c['source_xml']),Path(c['source_owner']),Path(tq['native_request']),Path(tq['binding'])]}
 b={'schema':'ds02.f5.c082s1.full-event-bed-audit-binding.fresh138.v1','family_id':'F5','case_id':cid,'physical_case_id':c['physical_case_id'],'physical_condition_sha256':c['physical_condition_sha256'],'source_plan_physical_condition_sha256':c['source_xml_sha256'],'source_plan_hash_semantics':'individual source definition XML file SHA; not canonical payload and not batch plan file SHA','source_canonical_physical_condition':c['physical_condition'],'physical_condition_hash_semantics':{'canonical_owner_sha256':c['physical_condition_sha256'],'source_h5_sha256':legacy,'source_h5_scope_schema':scope['schema'],'source_h5_scope_status':scope['semantic_binding_status']},'source_h5_physical_condition_sha256':legacy,'source_h5_scope_schema':scope['schema'],'source_h5_scope_status':scope['semantic_binding_status'],'trajectory_h5':str(h5),'trajectory_h5_sha256':t['output_sha256'],'conversion_report':str(cp),'full_typed_conversion_report':str(cp),'full_typed_conversion_report_sha256':sha(cp),'typed_receipt':str(trp),'native_receipt':str(nr),'full_native_receipt':str(nr),'full_native_receipt_sha256':sha(nr),'full_native_output_root':str(nr.parent),'full_native_data_root':str(nr.parent/'solver_output/data'),'gencase_receipt':str(gr),'gencase_receipt_sha256':sha(gr),'gencase_output_root':str(gr.parent),'gencase_prepared_output_root':str(xml.parent),'gencase_prepared_report':str(ppr),'gencase_prepared_report_sha256':sha(ppr),'canonical_generated_xml':str(xml),'canonical_generated_xml_sha256':sha(xml),'initial_qa_receipt':str(qr),'initial_qa_receipt_sha256':sha(qr),'initial_qa_output_root':str(qr.parent),'initial_qa_report':str(qar),'initial_qa_report_sha256':sha(qar),'actual_counts':qa['actual_counts'],'expected_frames':801,'expected_dimension':3,'expected_particle_axis':194427,'expected_fluid_particles':31658,'expected_fixed_particles':158559,'expected_moving_particles':4210,'expected_floating_particles':0,'native_bed_marker_mk':50,'source_bed_marker_mkbound':40,'physical_window_s':[0,16],'disabled':False,'source_only':False,'launch_allowed':True,'execution_allowed':True,'q_n_granted':False,'case_credit':0}
 xa,xout=run_stage(c,'xmf',b,h5,t['output_sha256'],md);mp=xa/'xdmf/manifest.json';m=load(mp) if mp.exists() else {};passed=xout['actual_completed0'] and m.get('frames')==801 and m.get('particles')==194427 and m.get('physical_condition_sha256')==c['physical_condition_sha256'] and m.get('source_h5_physical_condition_sha256')==legacy and m.get('source_h5_sha256')==t['output_sha256'];result={'tag':c['tag'],'case_id':cid,'xmf':xout,'bed':None,'actual_full801_xmf_bed_complete':False,'case_credit':0}
 if passed:
  xf=Path(m['xdmf']);gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert sha(xf)==m['xdmf_sha256'] and len(gs)==801 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='194427 3' for g in gs);bb={**b,'xmf_manifest':str(mp),'xmf_manifest_sha256':sha(mp),'xmf_receipt':str(xa/'execution-receipt.json'),'xmf_receipt_sha256':sha(xa/'execution-receipt.json'),'xdmf':str(xf),'xdmf_sha256':sha(xf)};extra={**md,**{str(p):sha(p) for p in [mp,xf,xa/'execution-receipt.json']}};ba,bout=run_stage(c,'bed',bb,h5,t['output_sha256'],extra);brp=ba/'audit-output/c082s1-full-event-bed-footprint-audit.json';br=load(brp) if brp.exists() else {};bpass=bout['actual_completed0'] and br.get('physical_condition_sha256')==c['physical_condition_sha256'] and br.get('source_h5_physical_condition_sha256')==legacy and len(br.get('frame_reports',[]))==801;bout.update(actual_report=str(brp),actual_full801_bed_scan_complete=bpass,diagnostic_only=True);result['bed']=bout;result['actual_full801_xmf_bed_complete']=bpass
 results.append(result);done.add(cid);put(O/'actual-progress.json',{'results':results,'remaining':22-len(done),'case_credit':0});print(json.dumps(result),flush=True);partial=not result['actual_full801_xmf_bed_complete']
put(O/'controller-result.json',{'requested':22,'actual_full801_xmf_bed_complete_count':sum(r['actual_full801_xmf_bed_complete'] for r in results),'remaining':22-len(done),'upstream_partial_hold':partial,'results':results,'case_credit':0});raise SystemExit(0 if len(done)==22 and not partial else 1)
