from pathlib import Path
import json,hashlib,copy,datetime,os,subprocess,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob('root_followup_226_*'));prefix=P.relative_to(W);commit='da36598b8c133c18cf8985fa195fdd709c0903c3'
expected={'README.md','manifest.json','metadata/source-provenance.json','metadata/root1436-final48-adoption.json','metadata/f2-final48-products.json','scripts/validate_fresh226.py'}
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names};assert all((W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b) for n,b in blobs.items());before={n:sha(W/n) for n in names}
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh226.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_327.json';cp=load(cpfile);ip=root(1441)/'full336-current332-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile)
qip=root(1442)/'actual1175-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';assert sha(qip)=='9d29b258a8f7c6cbc1cba9595fb622637b3bdb34e064dd493027f4d27fb4c093';qi=load(qip)
assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
for e in qi['actual_completed_metadata_evidence'].values():assert sha(e['path'])==e['sha256']
live=[]
for original,pi,start in [(1101,202633,210026020),(1149,253004,210338104)]:
 F=root(original);req=load(next(F.glob('enabled-*request.json')));rp=Path(req['attempt_root'])/'execution-receipt.json';er=load(rp);p=Path('/proc')/str(pi);s=(p/'stat').read_text();fs=s[s.rindex(')')+2:].split();cmd=(p/'cmdline').read_bytes().replace(b'\0',b' ').decode();assert int(fs[19])==start and str(F) in cmd and er['status']=='running' and 'returncode' not in er and not (rp.parent/'render/render-publish-receipt.json').exists()
 live.append({'original':original,'physical_case_id':req['physical_case_id'],'controller_pid':pi,'controller_start_ticks':start,'same_live_registered_controller_verified':True,'actual_running_receipt_snapshot':er,'actual_running_receipt_snapshot_SHA':sha(rp),'original_receipt_may_naturally_change_after_snapshot':True})
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current332_twoF5_completed_own1440_1442_personal204_228_F2source226_readonly_only_live1101_1149_1443';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_328.json';assert not O.exists() and not np.exists();O.mkdir()
for name,b in blobs.items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
cv=subprocess.run(['python3','-B',str(R/prefix/'scripts/validate_fresh226.py')],capture_output=True,text=True);assert cv.returncode==0,(cv.stdout,cv.stderr);assert all((W/n).read_bytes()==b and (R/n).read_bytes()==b for n,b in blobs.items())
proof=O/'current332-twoF5-completedQI-source226-readonly-only-and-two-live-originals-proof.json'
put(proof,{'schema':'ds02.main.current332.two-completedQI-source226-readonly-frontier.v1','at_utc':now.isoformat(),'source226_commit':commit,'source226_exact_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'source_validator_full_read_only_not_an_independent_48case_runtime_QA_or_PNG_certificate':True,'source_validator_stdout':rv.stdout,'copied_source_validator_stdout':cv.stdout,'F2_actual48_main_independent_primary_audit_complete':False,'F2_actual48_main_primary_audit_next_required':True,'completed1184_own801QI':idx['cases'][next(i for i,r in enumerate(idx['cases']) if r['physical_case_id']=='F5_COMPACT_RUNUP_RECOVERY_C082S1_M095_T090')]['actual_full801_QI'],'completed1175_own801QI':ref(qip),'pending_personal_review_owners':{'actual1184':'f6_endpoint_initial_qa/fresh204','actual1175':'f5_bed_recovery/fresh228'},'registered_live_observations':live,'main_scientific_payload_IO':False,'new_case_credit':0,'Q_N':0,'Q_E':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=328,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: accepted332; F5actual1184 and1175 naturally completed0/pub/full801QI1440/1442 and personal204/228 started; F2source226 exactcopy+readonly validation completed but main48 direct audit still required;1101/1149 registered renders live.',authorized_work_state='Active332/336 remaining4. Two F5completed fullQI pending personal204/228; lastF3 1101 andlastF5 1149 rendering. Complete actual48 F2 mainprimary audit and final global primary delivery193; no new native runs.')
new['actual_progress']['current332_twoF5_completed_QI_source226_readonly_and_live_originals']=ref(proof);new['next_executable_tasks'].insert(0,'Read main old42Root1330 actual refs + fresh226 new6 actualfull401QI; direct full48 XML/time/UID/runtime/QA/PNG join then adopt F2 final48 product; integrate204/228 and extend F5 after personal review; execute1427 after1101 true0/pub.')
put(np,new);rr=next(r for r in idx['cases'] if r['physical_case_id']==qi['physical_case_id']);assert not rr.get('accepted_decision');rr.update(actual_full801_QI=ref(qip),actual_completed0_published_QI=ref(qip),personal_visual_status='pending fresh228 personal review',case_credit_already_in_authoritative_checkpoint=0)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);idx['current332_twoF5_completed_QI_source226_readonly_and_live_originals']=ref(proof);idx['actual_unaccepted_completed0_published_physical_cases']=['F5_COMPACT_RUNUP_RECOVERY_C082S1_M095_T090','F5_COMPACT_RUNUP_RECOVERY_C082S1_M104_T085'];put(O/'full336-current332-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: preserve two completed F5 integrity proofs and exact F2 source226 pending direct48 primary audit','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':328,'accepted':332,'F5_completed_pending_personal':2,'actual_registered_renders_live':[1101,1149],'source226_main_actual48_audit_pending':True,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
