from pathlib import Path
import json,hashlib,datetime,subprocess,shutil,re,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');ref=lambda p:{'path':str(p),'sha256':sha(p)}
q=load(root(965)/'enabled-cleanup-request.json');ar=Path(q['attempt_root']);receipt=load(ar/'execution-receipt.json');result=load(ar/'cleanup/cleanup-result.json');controller=load(root(965)/'controller-result.json');assert receipt['status']=='completed' and receipt['returncode']==0 and result['status']=='completed' and controller['launcher_returncode']==0
plan=load(root(964)/'cleanup-plan.json');assert result['plan_sha256']==sha(root(964)/'cleanup-plan.json')
manifest={f['path']:f for c in plan['eligible_attempts'] for f in c['delete_files']};deleted=[json.loads(x) for x in (ar/'cleanup/deleted-files.jsonl').read_text().splitlines()];assert len(deleted)==len(manifest)==len({x['path'] for x in deleted});assert set(manifest)=={x['path'] for x in deleted};assert sum(x['size'] for x in deleted)==plan['planned_delete_bytes']==result['deleted_payload_bytes'];assert sum(x['blocks_bytes'] for x in deleted)==plan['planned_delete_allocated_bytes']==result['deleted_allocated_bytes'];assert result['deleted_files']==len(deleted)
for x in deleted:assert x['size']==manifest[x['path']]['size'] and not Path(x['path']).exists()
checks=[]
for c in plan['eligible_attempts']:
 assert sha(c['receipt'])==c['receipt_sha256'];rr=load(c['receipt']);assert rr['status']=='failed' and rr['returncode'] not in [None,0]
 assert all(Path(p).is_file() for p in c['preserved_frame_paths']);files=list(Path(c['data_root']).iterdir());remaining=[p for p in files if re.fullmatch(r'Part_\d{4,}\.bi4',p.name)];assert len(remaining)==c['actual_native_frame_file_count']-len(c['delete_files'])
 suffix=collections.Counter(p.suffix for p in files if p.is_file())
 for s in ['.ibi4','.obi4']:assert suffix[s]==c['suffix_count'].get(s,0)
 tomb=Path(c['root'])/'user-authorized-failed-native-cleanup-root965.json';t=load(tomb);assert t['status']=='completed' and t['deleted_files']==len(c['delete_files']);checks.append({'attempt_id':c['id'],'receipt_unchanged':True,'remaining_numeric_native_frames':len(remaining),'initial_and_last_and_dependency_frames_retained':True,'header_counts_unchanged':True,'cleanup_tombstone':ref(tomb),'deleted_payload_GiB':c['delete_bytes']/1024**3})
O=H/'root_stage1_actual965_failed_partial_native_cleanup_independent_closure_storage_recovery_checkpoint_966';O.mkdir(exist_ok=False);free=shutil.disk_usage('/home/jade').free;assert free>=500*1024**3
family_reconciliation=L/'campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_120_f3_qual01_dependency_reconciliation_v1/metadata/qual01-dependency-reconciliation.json';family_audit162=L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_162_storage_cleanup_audit_v1';
review={'F3_QUAL01_historical_request_reference_reconciliation':ref(family_reconciliation),'family_storage_audit162_package':str(family_audit162),'observed_BI4_text_search_PID4038392_owner_unattributed_agent_denies_origin_result_not_used':True,'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'completed_and_independently_verified','actual_registered_cleanup_receipt':ref(ar/'execution-receipt.json'),'actual_cleanup_result':ref(ar/'cleanup/cleanup-result.json'),'deletion_journal':ref(ar/'cleanup/deleted-files.jsonl'),'manifest':ref(root(964)/'cleanup-plan.json'),'failed_attempts_cleaned':len(checks),'deleted_files':len(deleted),'deleted_payload_bytes':result['deleted_payload_bytes'],'deleted_payload_GiB':result['deleted_payload_bytes']/1024**3,'deleted_allocated_bytes':result['deleted_allocated_bytes'],'Home_free_GiB_live':free/1024**3,'Home_floor_GiB':500,'floor_pass':True,'free_delta_not_equal_payload_bytes_due_to_concurrent_writes':True,'accepted_pending_running_and_completed_products_protected':True,'blocked_two_referenced_failed_attempts_retained':plan['blocked_candidates'],'original_failure_receipts_headers_and_initial_last_dependency_frames_preserved':checks,'budget_charges_and_attempt_counters_not_reset':True,'main_and_cleanup_worker_scientific_payload_contents_IO':False,'case_credit':0};put(O/'actual-cleanup-independent-review.json',review);(O/'closure-source.py').write_bytes(Path(__file__).read_bytes())
old=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_127.json';cp=load(old);cp['checkpoint']=128;cp['at_utc']=review['at_utc'];cp['predecessor']=str(old);cp['predecessor_sha256']=sha(old);cp['new_accepted_decisions']=[];cp['authorized_work_state']='active; user-authorized failed unused native cleanup completed; existing scientific queues continue';cp['previous_goal_turn_classification']='Meaningful progress: 439 GiB failed incomplete unused native frames removed under registered CPU job; floor restored and native948 naturally resumed. No case or precision credit from cleanup.'
ledger_path=D/'runtime/resource-ledger.json';ledger_bytes=ledger_path.read_bytes();ledger=json.loads(ledger_bytes);cp['attempt_counts']={k:sum(x['kind']==k for x in ledger['attempts']) for k in ['qualification','production','cpu']};cp['gpu_hours_charged']=sum(v.get('gpu_seconds',0) for v in ledger['charges'])/3600;cp['cpu_core_hours_charged']=sum(v.get('cpu_core_seconds',0) for v in ledger['charges'])/3600;cp['ledger_sha256_at_checkpoint']=hashlib.sha256(ledger_bytes).hexdigest();cp['home_free_gib']=free/1024**3;cp['active_reservations']=ledger['reservations'];cp['actual_progress']={'user_authorized_failed_native_cleanup_independently_closed':ref(O/'actual-cleanup-independent-review.json'),'main_science_payload_IO':False,'main_PNG_personal_review':False,'precision_status':'视觉检查通过、数值精度未验收','pending_fresh130_main_QI_closure':ref(root(961)/'actual130-adoption-and-independent-metadata-closure.json'),'F5_M085_full801_bed0':ref(root(959)/'actual956-all801-bed-independent-review.json'),'F5_M086_case_adapter_repair2_metadata_verified':ref(root(962)/'actual161-adoption-and-main-regression-review.json')}
for n,label in [(948,'F3_native_queue'),(951,'full_native_render_queue'),(960,'F5_M085_full801_render'),(963,'F5_M086_full801_XMF')]:
 for fn in ['actual-progress.json','controller-result.json']:
  p=root(n)/fn
  if p.exists():cp['actual_progress'][label+'_'+fn.replace('.json','')]=ref(p)
cp['next_executable_tasks']=['Integrate delegated fresh131 F6 physical sidecar and F4 full1201 visual decision plus fresh132 F5 M085 full801 visual; independently close metadata/QI and unique case scopes before raising199.', 'Observe same live948 GPU native queue and951 full renderer; do not restart or duplicate completed attempts.', 'Adopt ready F3 typed4GiB source118, resolve actual producer scopes by metadata before new registered full836 conversion.', 'After actual963 XMF0 independently verify and bind corrected161 original bed worker; preserve all801 science settings and immutable execution/source flags.', 'Adopt ready source160 actual939 M095 disabled XMF binding then register downstream full801 job under existing shared budget and Home floor.', 'Keep original precision negatives; stage1 visual decisions do not grant Q-N/Q-E. Cleaned failed sequences remain explicitly marked incomplete and pruned with receipts and first/last states.']
cp['source_agents']={'/root/f5_bed_recovery':'fresh160 ready,161 adopted962,162 user-authorized cleanup metadata-only audit complete; only tiny first frames eligible, retained as failure evidence','/root/production_recovery':'fresh118 ready;119 audited;120 independently reconciles historical QUAL01 registration versus actual GENCASE02 inputs. Observed BI4 text-search owner unattributed, agent denies origin and results excluded.','/root/f6_endpoint_initial_qa':'fresh131 includes130 physical sidecar and full1201 F4 visual; fresh132 full801 F5 visual ready; main case credit pending'};put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_128.json',cp)
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_128.json').relative_to(R))]+[str((root(965)/n).relative_to(R)) for n in ['controller-launch-process.json','controller-result.json']]+[str((root(n)/'controller-launch-process.json').relative_to(R)) for n in [960,963]]+[str((root(n)/'controller-result.json').relative_to(R)) for n in [960,963]]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify authorized failed native cleanup and restored Home headroom','--',*paths],cwd=R,check=True);print({'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'deleted_payload_GiB':review['deleted_payload_GiB'],'Home_free_GiB':review['Home_free_GiB_live'],'accepted':cp['stage1_visual_accepted_complete_independent_cases']})
