from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_145_f7_a031_a031p5_visual_review_v1';O=H/'root_stage1_F7_delegated145_original_A031_visual_and_A031P5_duplicate_review_869';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
commit='c4aa5b874fb2e26eb5db39e0669448fd019e2fd6';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines();adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert p.read_bytes()==b;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==b;dst.write_bytes(b);adopted.append(ref(dst))
P=R/S.relative_to(W);sp=P/'metadata/fresh145-visual-review.json';d=load(sp);assert d['model_profile']=='gpt-5.6-luna/max';prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_113.json')['accepted_decisions'];previous=[load(p) for p in prior];ids={r.get('physical_case_id',r['case_id']):p for r,p in zip(previous,prior)};hashes={r['physical_condition_sha256'] for r in previous};assert len(ids)==169;decisions=[];duplicates=[]
for c in d['cases']:
 cid=c['case_id'];chain=c['producer_chain_metadata'];t=load(chain['typed_report']['path']);m=load(chain['manifest']['path']);a=load(chain['render_report']['path']);sc=c['scope_separation'];digest=t['hash_scopes']['physical_condition_sha256']
 if cid in ids:
  assert load(ids[cid])['physical_condition_sha256']==digest;duplicates.append({'case_id':cid,'existing_decision':ref(ids[cid]),'additional_review':ref(sp),'case_increment':0,'reason':'Root792 historical already_accepted flag is stale; latest checkpoint has actual decision. Source review retained unchanged.'});continue
 assert cid=='F7_OBSTACLE_QUINTIC_B08_A031' and digest not in hashes
 for v in c['metadata_inputs']:assert sha(v['path'])==v['sha256']
 ev={}
 for v in chain['stage_receipts']:
  assert sha(v['path'])==v['sha256'];r=load(v['path']);assert (r['status'],r.get('returncode'))==('completed',0);ev[v['stage']]=ref(v['path'])
 assert t['conversion_status']=='completed' and t['frames']==601 and t['particles']==70179 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=12 and t['time_evidence']['strictly_increasing'];own=load(sc['canonical_owner_path']);actual=hashlib.sha256(json.dumps(own['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert digest==actual==sc['actual_converter_scope_sha256']==sc['canonical_physical_binding_sha256']==m['physical_condition_sha256']==m['canonical_physical_binding_sha256'];assert sha(sc['canonical_owner_path'])==sc['canonical_owner_sha256'];assert sha(sc['batch_source_plan_file'])==sc['batch_source_plan_file_sha256'];assert m['source_plan_condition_sha256']==sc['source_plan_declared_condition_sha256']==own['physical_condition_sha256'];assert own['physical_binding']==m['canonical_owner']['physical_binding'];assert sha(own['source']['source_plan'])==sc['batch_source_plan_file_sha256'];assert own['source']['source_plan_sha256']==sc['batch_source_plan_file_sha256'][:-1];assert sha(own['source']['source_definition'])==sc['source_definition_sha256'];sc={**sc,'original_owner_declared_batch_digest':own['source']['source_plan_sha256'],'actual_batch_file_digest':sc['batch_source_plan_file_sha256'],'historical_batch_digest_erratum':'Original owner stores a 63-character digest missing the final 5; actual batch file64-character SHA verified separately; source owner bytes and physical-binding hash unchanged.'};assert m['source_h5_read_only'] and m['frames']==601 and m['particles']==70179 and m['source_h5_sha256']==t['output_sha256'];xf=Path(m['xdmf']);assert sha(xf)==m['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==601 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='70179 3' for g in gs)
 assert a['frames']==a['source_frames']==601 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(chain['manifest']['path']) and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf) and a['source_h5_sha256']==t['output_sha256'];fs=a['frame_diagnostics'];assert len(fs)==601 and all(x['active']==70179 and x['missing']==0 and x['finite_positions_active'] and x['identity_axis_preserved'] and all(y['finite_active'] and y['nonfinite_active']==0 for y in x['finite_fields'].values()) for x in fs)
 qpath=Path(next(x for x in chain['stage_receipts'] if x['stage']=='native_initial_qa')['output_root'])/'initial-qa/native-initial-qa.json';qa=load(qpath);qc=next(x for x in qa['cases'] if x['case_id']==cid);assert qc['passed'] and qc['native_particles']==70179 and {k:v['count'] for k,v in qc['checks']['native_type_mk_blocks'].items()}=={'fixed':27495,'moving':1984,'fluid':40700};assert all(qc['checks'][k] for k in ['actual_3d','all_13_fields_finite','no_initial_overlap','uid_exact_sorted_unique','xml_contract']);ev['initial_qa_report']=ref(qpath)
 vs=c['visual_scope'];contacts=vs['all_26_contact_sheets'];keys=vs['ten_event_keyframes'];assert vs['reviewed_all_contact_sheets'] and len(vs['reviewed_event_keyframes'])==10 and len(contacts)==26 and len(keys)==10
 for v in contacts+keys:assert sha(v['path'])==v['sha256']
 out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F7','case_id':cid,'physical_case_id':cid,'physical_condition_sha256':digest,'source_review_commit':commit,'source_review':ref(sp),'visual_reviewer':'/root/f5_bed_recovery','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'visual_limitations':'Sparse early out-of-envelope blue points disclosed; strict particle containment and exit routes unqualified. Open top geometry preserved.','agent_observations':vs['visual_observations'],'scope_separation':{**sc,'canonical_recomputed_from_metadata_only':True,'old_original24_batch_scope_retained':True,'source_XML_and_source_declaration_and_actual_converter_and_batch_file_distinct':True},'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':{'contact_sheets':contacts,'key_frames':keys},'actual_frames':601,'actual_particles':70179,'actual_fluid_particles':40700,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'native_control_interpolation':'piecewise linear; no native C2 claim','source_control':m['source_control'],'scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':169,'resulting_count':170};dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);decisions.append(str(dp))
assert len(decisions)==len(duplicates)==1;put(O/'actual-integration-review.json',{'source_commit':commit,'source_adopted_byte_exact':True,'adopted_files':adopted,'previous_count':169,'resulting_count':170,'independent_case_increment':1,'decisions':decisions,'duplicate_reviews_not_counted':duplicates,'Root792_stale_flags_do_not_override_latest_acceptance':True,'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'new_cases':1,'accepted':170,'duplicate_visual_reviews_preserved_not_counted':1}))
