from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='8a95e6ec34a68e27d78022da700dda0f61a570ca';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_194_f6_assigned_f2_completion_only_final48_primary_builder_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==6
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
contract=load(P/'metadata/input-contract.json');inputs={e['role']:e for e in contract['inputs']}
for e in inputs.values():assert sha(e['path'])==e['sha256']
cp0=load(inputs['checkpoint']['path']);i0=load(inputs['current_index']['path']);assert i0['source_authoritative_checkpoint']==ref(inputs['checkpoint']['path']);assert cp0['checkpoint']==282 and cp0['accepted_per_family']['F2']==44
before={n:sha(W/n) for n in names};cmd=['python3','-B',str(P/'scripts/validate_fresh194.py'),'--checkpoint',inputs['checkpoint']['path'],'--current-index',inputs['current_index']['path'],'--membership',inputs['membership']['path'],'--legacy-catalog',inputs['legacy_catalog']['path'],'--package-dir',str(P)]
rv=subprocess.run(cmd,capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
readiness=load(P/'metadata/current-readiness/fresh194-readiness.json');assert readiness['observed_counts']=={'registered_final48':48,'accepted_visual':44,'pending_visual':4} and not readiness['complete_final48_emitted'] and not (P/'F2-FINAL48-COMPLETE-PRIMARY-DELIVERY.json').exists()
defects=[]
for a in readiness['accepted_ref_audit']:
 e=a['actual_render_receipt'];j=load(e['path']);observed=sha(e['path']);assert e.get('sha256',observed)==observed
 assert e['metadata_probe']['json_sha256']==observed
 if j.get('status')!='completed' or j.get('returncode')!=0: defects.append({'physical_case_id':a['physical_case_id'],'source_selected_render_role':e,'actual_schema':j.get('schema'),'actual_status':j.get('status'),'actual_returncode_field_present':'returncode' in j,'actual_returncode':j.get('returncode'),'source_primary_completeness_claim':a['primary_ref_completeness'],'is_execution_receipt':j.get('schema')=='ds02.execution-receipt.v1'})
assert len(defects)==4 and all(a['actual_schema']=='ds02.runner-request.v3' and not a['actual_returncode_field_present'] and not a['is_execution_receipt'] for a in defects)
assert {a['physical_case_id'] for a in defects}=={'F2_STAGE1_FIRST24_OFFSET_OPEN_RIM_RX046_RY014_FILL080_ROT120','F2_STAGE1_FIRST24_OFFSET_OPEN_RIM_RX048_RY014_FILL080_ROT065','F2_STAGE1_FIRST24_OFFSET_OPEN_RIM_RX048_RY014_FILL080_ROT120','F2_STAGE1_FIRST24_OFFSET_OPEN_RIM_RX052_RY014_FILL080_ROT065'}
for a in readiness['accepted_ref_audit']:
 e=a['accepted_decision'];assert e['path'] in cp0['accepted_decisions'] and sha(e['path'])==e['sha256'];d=load(e['path']);assert d['family_id']=='F2' and d['physical_case_id']==a['physical_case_id'] and d['status'] in {'visual-approved-by-root','visual-approved-by-delegated-agent'}
mem=load(inputs['membership']['path']);assert set(mem['frozen_first8_physical_case_ids'])<=set(mem['actual_first24_physical_case_ids'])<=set(mem['registered_final48_physical_case_ids'])
now=datetime.datetime.now(datetime.timezone.utc);O=H/'root_stage1_source194_F2_current44_readiness_authority_gate_checked_four_render_request_as_receipt_fulltime_runtime_gate_missing_repair195_required_1381';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_285.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
pp=O/'source194-byte-exact-readonly-current44-assembly-status-gate-defects-and-required195-repair-audit.json'
put(pp,{'schema':'ds02.source194.assembly-only.main.gate-defect-audit.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'readonly_validator_command':cmd,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'validator_pass_supports':'Current44 assembly/readiness reference presence, JSON SHA, accepted decision authority/status/identity and fixed membership. It does not certify full401 data integrity or actual runtime completion.','source_frozen_inputs':inputs,'source_current_readiness':ref(R/prefix/'metadata/current-readiness/fresh194-readiness.json'),'accepted_F2_at_frozen_boundary':44,'pending_F2_at_frozen_boundary':4,'source_final48_not_emitted':True,'actual_wrong_request_as_render_receipt_rows':defects,'full_builder_and_validator_code_read_by_main':True,'identified_code_gate_gaps':['primary_completeness does not validate real native/typed/XMF/render receipt runtime schema/status/returncode/case binding','primary_completeness does not inspect full401 UID/N3/finite/actual time metadata certificate','merge_missing does not apply known1330 role correction when incorrect existing request path is present','readiness write can overwrite existing output; complete branch unlinks old readiness','missing key paths may be disclosed but are not by themselves full key event delivery proof'],'source_contract_runtime_gate_claim_is_not_implementation_evidence':True,'fresh195_separate_repair_assigned':'Fulltime metadata/runtime gates, known4 request-role corrections, originalP03 typed runtimeunknown with genuine recovery support, immutable output refusal, genuine QA roles and focused negative gates. No science payload IO, no jobs, no shared mutation.','source194_not_approved_as_standalone_final48_builder':True,'source194_bytes_immutable':True,'new_case_credit':0,'q_n_granted':False,'q_e_granted':False,'main_scientific_payload_IO':False,'PNG_payload_IO':False})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_284.json';cp=load(cpfile);assert cp['checkpoint']==284 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==313
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp)
new.update(checkpoint=285,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: preceding turn accepted F2source193 reaching313 and completed independent full801/full836 QIs1371/1373; next two same registeredF5 handles with durable1377/1380. Currentturn mainfullcode and actualsource194 readonlyaudit confirms four request-as-receipt defects and absentfulltime/runtime gates; source195 separate repair assigned, source194 retained as assembly only.',authorized_work_state='Active313/336. Personal179 F5original1174 and213 F3original1033 underway after ownQI1371/1373. F2source194 current44 assembly/readiness frozen accepted/status authority checked; four actualrequest-as-receipt and fulltime/runtime/immutability gate defects not approved forfinal. Source195 fixing independently. SameoriginalF5render1160/1151 continue, durableQI1377/1380 pending actual0/pub; no newSCI jobs.')
new['actual_progress']['source194_assembly_only_gate_defect_audit']=ref(pp);new['source_agents']['f6_endpoint_initial_qa']='fresh195 repairing F2 final48 fulltime/runtime/known4 renderrole/outputimmutable gates; source194 current44 readiness historical assembly only'
new['next_executable_tasks']=['Adopt source179 F5original1174 andsource213 F3original1033 after exactfinalcommit/fullreadonlyvalidator/mainpublishedPNG SHA/ownQI closure.','Audit fresh195 F2 fulltime/runtime/corrected4 renderrole and immutableoutput gates; source194 onlyassembly, no standalonefinal48 claim.','Observe sameF5original1160 PID648352/start214140469 and1151 PID650123/start214158617; actual0/pub then durableownQI1377/1380 once.','After allreal48accepted close F2/F3/F5 actualprimary catalogs including original runtimeunknown/recovery boundaries, and complete global336 independentdelivery audit.']
put(np,new);ip=root(1379)/'full336-current313-actual-final48-delivery-progress-index.json';idx=load(ip);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,source194_F2_current44_assembly_only_gate_defect_audit=ref(pp));assert len(idx['cases'])==336 and sum(bool(a.get('accepted_decision')) for a in idx['cases'])==313
put(O/'full336-current313-actual-final48-delivery-progress-index.json',idx);(O/'audit-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: audit F2 assembly readiness exposing four wrong receipt roles and final gate gaps','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':285,'accepted':313,'source194_readonly_validator':rv.stdout.strip(),'actual_wrong_render_role_rows':len(defects),'fresh195_required':True,'proof':ref(pp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
