from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_193.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==271 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_194.json').exists();family=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003');specs=[(166,'1c3e1032ee487b86aa0e850274afd6351e719088',family/'root_followup_166_f2_native_alias_scope_audit_v1'),(167,'4118f0636445ee5e6e14df6ef6eb592bda3b55b2',family/'root_followup_167_f2_native_actual_json_closure_v1')];files=[];adopt=[]
for n,commit,pkg in specs:
 names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(pkg)],cwd=W,text=True).splitlines();assert len(names)==6;before={}
 for rel in names:
  raw=subprocess.check_output(['git','show',commit+':'+rel],cwd=W);assert raw==(W/rel).read_bytes();dst=R/rel
  if dst.exists():assert dst.read_bytes()==raw
  else:dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(raw)
  before[str(W/rel)]=sha(W/rel);before[str(dst)]=sha(dst)
 rv=subprocess.run(['python3','-B',str(W/pkg/f'scripts/validate_fresh{n}.py')],cwd=W/pkg,text=True,capture_output=True);assert rv.returncode==0,rv.stderr;assert before=={p:sha(p) for p in before};adopt.append({'source_commit':commit,'package':str(pkg),'files':[ref(R/rel) for rel in names],'unchanged_source_and_adopted_hashes':before,'readonly_validator_returncode':rv.returncode,'readonly_validator_stdout':rv.stdout});files+=names
P=W/specs[1][2];closure_path=P/'metadata/f2-native-actual-json-closure.json';cl=load(closure_path);assert len(cl['rows'])==13;base_path=root(1215)/'full336-current271-role-aware-registration-progress-index.json';base=load(base_path);rows=copy.deepcopy(base['cases']);byid={a['physical_case_id']:a for a in rows};native_conditions=0;absent=0;missing=0;diff=0;proof_rows=[]
for row in cl['rows']:
 pid=row['physical_case_id'];idx=byid[pid];assert idx['family_id']=='F2';a=row['accepted_decision'];assert sha(a['path'])==a['declared_sha256']==a['actual_json_sha256'];aa=load(a['path']);assert aa['physical_case_id']==pid and aa['case_id']==row['case_id'];assert idx['accepted_decision']['path']==a['path'];native=row['native_receipt_declarations'];assert len(native)<=1
 for rec in row['actual_completed_receipt_declarations']+native:
  assert sha(rec['path'])==rec['declared_sha256']==rec['actual_json_sha256'];r=load(rec['path']);assert (r['status'],r['returncode'])==('completed',0)
 for conv in row['conversion_report_declarations']:
  assert sha(conv['path'])==conv['declared_sha256']==conv['actual_json_sha256'];t=load(conv['path']);rr=conv['source_provenance_solver_receipt'];assert t['source_provenance']['solver_receipt']['path']==rr['path'] and t['source_provenance']['solver_receipt']['sha256']==sha(rr['path'])==rr['declared_sha256']==rr['actual_json_sha256'];assert t['conversion_status']=='completed' and t['frames']==401
 if native:
  rec=native[0];r=load(rec['path']);q=r['request'];ident=rec['request_identity'];assert q['case_id']==row['case_id'] and q.get('physical_case_id')==ident['physical_case_id']['value'];assert ('physical_condition_sha256' in q)==ident['physical_condition_sha256']['present'];assert q.get('physical_condition_sha256')==ident['physical_condition_sha256']['value'];assert 'physical_binding' not in q
  ev={'receipt':ref(rec['path']),'status':r['status'],'returncode':r['returncode'],'embedded_request_case_id':q['case_id'],'embedded_request_physical_case_id':q.get('physical_case_id'),'embedded_request_condition_sha256':q.get('physical_condition_sha256'),'condition_field_present':'physical_condition_sha256' in q,'actual_physical_binding_field_present':False,'logical_accepted_physical_case_id':pid,'native_request_physical_case_id_equals_accepted_physical_case_id':q.get('physical_case_id')==pid,'accepted_semantic_condition_sha256':aa['physical_condition_sha256'],'case_id_match_does_not_rewrite_physical_ID_alias':True,'own_conversion_solver_receipt_ref_verified':True}
  if 'physical_condition_sha256' in q:
   native_conditions+=1;diff+=q['physical_condition_sha256']!=aa['physical_condition_sha256'];idx['native_request_scope_before_new167_preserved']=idx['native_request_scope'];idx['native_request_scope']={'sha256':q['physical_condition_sha256'],'role':'actual native receipt embedded request field; logical physical ID aliases retained separately','evidence':ev,'condition_not_inferred_from_accepted_top_or_source_plan':True,'source167_raw_actual_JSON_closure':ref(closure_path)}
  else:absent+=1;idx['actual_native_condition_field_true_absence']=ev
  proof_rows.append({'physical_case_id':pid,'actual_native_request_fields':ev})
 else:
  missing+=1;assert not row['conversion_report_declarations'];proof_rows.append({'physical_case_id':pid,'actual_native_ref_missing_in_direct_accepted_chain':True,'no_invented_native_SHA':True,'followup168_deeper_own_metadata_chain':True})
assert (native_conditions,absent,missing,diff)==(9,1,3,4);assert len(rows)==len(byid)==336
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
O=H/'root_stage1_source166167_F2_actual_native_receipt_nine_conditions_four_semantic_role_differences_absences_preserved_checkpoint_1216';O.mkdir(exist_ok=False);put(O/'source166167-byte-exact-readonly-adoption-proof.json',{'sources':adopt,'source1205_snapshot_F2_32_kept_current_F2_33':True,'new_case_credit':0,'scientific_payload_IO':False});proof=O/'actual167-own-native-JSON-field-and-semantic-alias-closure.json';put(proof,{'rows':proof_rows,'actual_native_condition_fields_present':9,'actual_native_condition_field_true_absence':1,'missing_direct_native_receipt_refs_pending168':3,'native_vs_accepted_semantic_condition_differences':4,'missing_binding_fields_not_filled_from_canonical':True,'source166_null_snapshot_preserved_not_final_actual_field_claim':True,'main_scientific_payload_IO':False,'new_case_credit':0})
idxpath=O/'full336-current271-native-request-roles-with-actual167-F2-closure.json';updated={k:v for k,v in base.items() if k!='cases'};updated.update(schema='ds02.stage1.full336.role-aware-progress-index.v4',at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),source_authoritative_checkpoint=ref(cp_path),previous_index_preserved=ref(base_path),new_F2_actual_native_JSON_role_closure=ref(proof),native_request_field_digest_available=sum(a['native_request_scope']['sha256'] is not None for a in rows),native_request_field_digest_not_available=sum(a['native_request_scope']['sha256'] is None for a in rows),controller_observations_inherited_from1215_not_new_live_probe=True,cases=rows);put(idxpath,updated)
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=194,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: exact166167 sourcesadopted; actual13F2acceptedchains inspected9nativeconditionfields retained4differfromacceptedsemantic,1trueabsenceand3directchainmissingrefsexplicit,10conversionnativeJSONrefshashclosed. Newrole-awarefull336indexusesrawactualfieldswithoutnativebindingfabrication, still271 visualcases.',authorized_work_state='Active271/336: actual1152 F5full801published0QIclosedawaiting192personalreview. Original1130/1137F5renderslive. F2actualnative9fieldclosureimproved,3acceptedchainrefsnext168. No numericalcert ornewsciencesolve.')
cp['actual_progress']['source166167_actual_F2_native_JSON_field_role_closure']=ref(proof);cp['actual_progress']['full336_current271_role_aware_native_fields_with_actual167']=ref(idxpath);cp['source_agents']['f6_endpoint_initial_qa']='fresh168 threeRX047075/090/105 deeperownacceptedmetadatanativechainclosure; nexteligiblepersonalF2/lastF6reviewpriority';cp['next_executable_tasks']=['Adopt source192 actual1152personal34contacts9keys thenacceptonlyifownvisualpasses','Afteractual0publish original1130/1137F5personalreviewnext','Fresh168 deeperownmetadataresolve3RX047native refs,1trueconditionabsencepreserved','Fresh150 F1F4F7authoritativefirst8/24/final48membership; nextactualF3publishedreviewpriority','Continue65 registeredrealdeliveries; original951lastF6waiting, Q-N/Q-E0']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_194.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=files+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_194.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: retain actual F2 native request scopes and preserve legacy field absences','--',*paths],cwd=R,check=True);print({'checkpoint':194,'accepted':271,'native_conditions_retained':9,'actual_semantic_differences':4,'true_absence':1,'missing_direct_refs':3,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
