from pathlib import Path
import json,hashlib,copy,datetime,os,collections,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cf=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_246.json';cp=load(cf);assert cp['checkpoint']==246 and cp['stage1_visual_accepted_complete_independent_cases']==298
ip=root(1319)/'full336-current298-actual-final48-delivery-progress-index.json';index=load(ip);by={r['physical_case_id']:r for r in index['cases']};assert len(by)==336
mp=root(1305)/'F6-FINAL48-FULLTIME-RIGID-MOTION-DELIVERY.json';m=load(mp);checked=[];recovered=[];baseline=None
for r in m['rows']:
 row=by[r['physical_case_id']];assert row['family_id']=='F6'
 if 'actual_complete_native_receipt' not in r:baseline=r;continue
 e=r['actual_complete_native_receipt'];assert ref(e['path'])==e;n=load(e['path']);q=n['request'];assert n['status']=='completed' and n['returncode']==0 and q['physical_case_id']==r['physical_case_id'] and q['case_id']==r['case_id'] and q['physical_condition_sha256']==r['actual_native_condition_sha256'];old=copy.deepcopy(row['native_request_scope']);assert old.get('sha256') is None or old.get('sha256')==q['physical_condition_sha256']
 observations={'physical_case_id':r['physical_case_id'],'actual_native_receipt':e,'actual_native_case_id':q['case_id'],'actual_native_physical_case_id':q['physical_case_id'],'actual_native_request_condition_field_present':True,'actual_native_condition_sha256':q['physical_condition_sha256'],'actual_native_status':n['status'],'actual_native_returncode':n['returncode'],'prior_index_native_scope_preserved':old,'fulltime_rigid_export_report':r['actual_export_report']};checked.append(observations)
 if old.get('sha256') is None:
  recovered.append(observations);row['prior_index_native_scope_unresolved_before_actual_rigid_export_binding']=old;row['native_request_scope']={'sha256':q['physical_condition_sha256'],'role':'actual completed native request condition bound independently by official fulltime rigid worker and exact native receipt JSON','actual_native_receipt':e,'actual_completed_native_status':'completed','actual_native_returncode':0,'source_actual_rigid_delivery':ref(mp),'condition_is_not_inferred_from_accepted_top_or_source_plan':True};row['actual_native_condition_field_true_absence']=False
assert len(checked)==47 and len(recovered)==34 and baseline is not None
# F2 and F6 historical baselines have actual native requests but no condition field.
f2p=root(1276)/'F2-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json';f2=load(f2p);f2row=next(r for r in f2['actual_own_primary_rows'] if r['physical_case_id']=='F2H10V2_OFFSET_V1');xp=Path(f2row['actual_xmf_manifest']['path']);assert sha(xp)==f2row['actual_xmf_manifest']['sha256'];x=load(xp)
baseline_sources=[('F2H10V2_OFFSET_V1',Path(x['native_receipt']),{'exact_accepted_F2_first24_row_product':ref(f2p),'actual_own_XMF_manifest':ref(xp),'actual_own_manifest_physical_case_id':x['physical_case_id'],'actual_case_id':f2row['case_id']}),('F6_STAGE1_ANGULAR_RELEASE_OMEGA_BASELINE',Path(root(1313)/'F6-ACTUAL_FIRST24-PARTICLE-RIGID-JOINED-DELIVERY.json'),None)]
legacy_product=load(baseline_sources[1][1]);baseline_sources[1]=('F6_STAGE1_ANGULAR_RELEASE_OMEGA_BASELINE',Path(legacy_product['legacy_baseline_actual_native_fields_and_time_certification_boundary']['native_receipt']['path']),{'existing_F6_first24_joined_product':ref(baseline_sources[1][1]),'historical_scientific_case_alias':'F6_ANGULAR_RELEASE_DP025','actual_complete_rigid_history_existing':baseline})
legacy=[]
for pid,p,authority in baseline_sources:
 n=load(p);q=n['request'];assert n['status']=='completed' and n['returncode']==0 and 'physical_condition_sha256' not in q and by[pid]['native_request_scope'].get('sha256') is None
 obs={'actual_native_receipt':ref(p),'actual_native_request_case_id':q.get('case_id'),'actual_native_request_physical_id_field_present':'physical_case_id' in q,'actual_native_request_physical_id_value':q.get('physical_case_id'),'actual_native_request_condition_field_present':False,'actual_native_request_condition_value':None,'original_status':n['status'],'original_returncode':n['returncode'],'actual_case_alias_authority':authority};legacy.append({'physical_case_id':pid,**obs});row=by[pid];row['prior_index_native_scope_unresolved_before_legacy_absence_check']=copy.deepcopy(row['native_request_scope']);row['native_request_scope']={'sha256':None,'role':'true actual native request physical_condition_sha256 field absence; not filled from accepted top, plan, definition, typed or XMF','actual_native_receipt_observation':obs};row['actual_native_condition_field_true_absence']=True
available=[r['native_request_scope']['sha256'] for r in index['cases'] if r['native_request_scope'].get('sha256')];absent=[r for r in index['cases'] if not r['native_request_scope'].get('sha256')];assert len(available)==len(set(available))==331 and len(absent)==5 and all(r.get('actual_native_condition_field_true_absence') is True for r in absent)
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_F6_47_actual_native_receipts_34_old_nulls_recovered_full336_331_unique_digest_five_true_legacy_absences_1320';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_247.json';assert not O.exists() and not np.exists();O.mkdir()
proof={'schema':'ds02.main.full336-native-condition-field-role-closure.v1','at_utc':now.isoformat(),'stable_predecessor_checkpoint':ref(cf),'prior_shared_index':ref(ip),'full48_official_rigid_product_unchanged':ref(mp),'actual47_F6_native_receipt_checks':checked,'newly_independently_resolved_F6_digest_fields':34,'F2_and_F6_true_legacy_field_absences':legacy,'all336_native_field_roles_resolved_or_true_absence':True,'actual_native_field_digest_available':331,'actual_available_digest_unique':331,'true_actual_native_digest_field_absent_count':5,'true_actual_field_absence_physical_case_ids':[r['physical_case_id'] for r in absent],'unresolved_native_condition_field_roles_remaining':0,'field_role_closure_not_new_numerical_or_native_completed0_certificate_for_all336':True,'accepted_visual_cases_unchanged':298,'new_case_credit':0,'new_visual_review':False,'Q_N':0,'Q_E':0,'main_scientific_payload_IO':False}
pp=O/'full336-native-field-role-closure-331-unique-five-real-absences.json';put(pp,proof);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=247,at_utc=now.isoformat(),predecessor=str(cf),predecessor_sha256=sha(cf),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: prior turn accepted3 visual cases to298 and actual F6fixed24 particle-rigid product. Current turn reverified144 F1/F4/F7 native field roles, recovered60 oldnulls; then reverified actual47 F6 native receipts via completed fulltime rigid exports, recovered34 further oldnulls and proved F2/F6 historical request condition field trueabsence. All336 field roles now331 unique actualdigests plus5 trueabsence, unresolved0; no new native-completion or numerical certificate for all336.',authorized_work_state='Active298/336,38 visual pending; full336 actual native condition field provenance331 unique/5 reallegacyabsences now explicit; accepted count unchanged. OriginalF5 1126/1187 continue rendering and source206/185 wait publication; source171 finalF6 familydelivery47accepted/onepending in progress; original951 lastF6 registeredlivewaiter.')
new['actual_progress']['full336_native_condition_field_role_closure_331_unique_five_real_absences']=ref(pp);put(np,new);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,native_request_field_digest_available=331,native_request_field_digest_not_available=5);index['full336_native_condition_field_role_closure']=ref(pp);index['true_actual_native_condition_field_absence_count']=5;index['unresolved_native_condition_field_roles_remaining']=0;assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==298 and new['accepted_decisions']==cp['accepted_decisions'];put(O/'full336-current298-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('完整336索引的原生条件字段角色闭合：331个实际存在的native请求摘要且互不重复；5个历史真实字段缺失保持null（F2母例、F4母例、F6母例、两个F7母例）。F6已完成官方全时域刚体导出的native收据直接复核47个，补齐34个旧未解析字段。全部历史索引与科学载荷不改，不把字段缺失改成输入不明，也不以字段角色闭合冒充全336求解状态或数值精度认证。\n');paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: close full336 native condition roles with331 unique fields and5 true legacy absences','--',*paths],cwd=R,check=True);print({'checkpoint':247,'accepted':298,'native_unique_fields':331,'true_field_absences':5,'unresolved_field_roles':0,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
