from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):
 assert sha(e['path'])==e['sha256'],e
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def same(e,f):return e['path']==f['path'] and e['sha256']==f['sha256']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
def dt(s):return datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+',r'\1',s).replace('Z','+00:00'))
P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob('root_followup_177_*'));A=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob('root_followup_178_*'));c177='3de2b58b3513182b074156318968d6d0b35f702a';c178='84da29629def6ea9581f452691dac81f93dfec5a';blobs={};origins=[]
for path,commit,count in [(P,c177,6),(A,c178,2)]:
 names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(path.relative_to(W))],cwd=W,text=True).splitlines();assert len(names)==count
 for n in names:
  b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b);blobs[n]=b
 origins.append({'commit':commit,'files':names})
before={n:sha(W/n) for n in blobs};rv=subprocess.run(['python3','-B',str(P/'validate_fresh177.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in blobs}
sp=P/'metadata/actual987-personal-visual-decision.json';s=load(sp);v=load(P/'metadata/png-evidence/actual987.json');akp=A/'fresh177-personal-review-acknowledgement.json';ak=load(akp);qip=next(root(1355).glob('*proof.json'));qi=load(qip);cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_request_condition_sha256'];assert s['case_id']==ak['case_id']==cid and s['physical_case_id']==ak['physical_case_id']==pid
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'] and qi['new_case_credit']==0 and not qi['q_n_granted'] and not qi['q_e_granted']
assert ak['fresh177']['commit']==c177 and same(ak['fresh177']['decision'],ref(sp));check(ak['fresh177']['decision']);assert s['reviewed_date_utc']==ak['fresh177']['recorded_date_utc']=='2026-10-07' and not ak['fresh177']['exact_review_time_present'] and not ak['fresh177']['model_key_present'];assert 'reviewer' not in s and 'model' not in s and 'reviewed_at_utc' not in s
att=ak['personal_review_attestation'];assert att['reviewer_configured_profile']=='gpt-5.6-luna' and att['reasoning_effort']=='max' and att['contact_sheets_personally_viewed']==35 and att['key_frames_personally_viewed']==9 and att['key_frame_indices']==[0,100,200,300,400,500,600,700,835]
for k in ['model_substitution','recursion_or_delegation','repeated_png_view_or_hash','scientific_payload_read_or_hash_for_acknowledgement','new_scientific_job','shared_state_write','q_n_granted','q_e_granted']:assert att[k] is False
assert att['case_credit']==0 and ak['acknowledgement_is_separate_evidence'] and ak['does_not_modify_fresh177'] and ak['does_not_create_catalog']
chain=s['actual_chain'];er={f'{k}_receipt':e for k,e in qi['actual_completed_receipts'].items()};er.update(typed_report=qi['typed_report'],xmf_manifest=qi['XMF_manifest'],xmf_xml=qi['XMF_XML'],render_report=qi['render_report'],render_publish_receipt=qi['publish'],initial_parent_QA_receipt=qi['initial_parent_QA_receipt'],initial_parent_QA_report=qi['initial_parent_QA_report'],source_preparation_report=qi['source_preparation_report'])
for e in er.values():check(e)
for name,src in [('native_receipt',chain['native']),('typed_receipt',chain['typed']['receipt']),('typed_report',chain['typed']['conversion_report']),('xmf_receipt',chain['xmf']['receipt']),('xmf_manifest',chain['xmf']['manifest']),('xmf_xml',chain['xmf']['xml']),('render_receipt',chain['render']['receipt']),('render_report',chain['render']['report']),('render_publish_receipt',chain['render']['atomic_publish'])]:assert same(src,er[name]);check(src)
for name,src in [('initial_parent_QA_receipt',s['reused_initialization']['parent_initial_qa_receipt']),('initial_parent_QA_report',s['reused_initialization']['parent_initial_qa_report']),('source_preparation_report',s['reused_initialization']['source_preparation_report'])]:assert same(src,er[name]);check(src)
arefs=ak['evidence_references']
for name,target in [('root1355_qi_proof',ref(qip)),('actual987_render_receipt',er['render_receipt']),('actual987_atomic_publish_receipt',er['render_publish_receipt'])]:assert same(arefs[name],target);check(arefs[name])
receipts={k:load(er[k+'_receipt']['path']) for k in ['native','typed','xmf','render']}
for r in receipts.values():assert r['status']=='completed' and r['returncode']==0 and r['request']['case_id']==cid
x=load(er['xmf_manifest']['path']);t=load(er['typed_report']['path']);r=load(er['render_report']['path']);pu=load(er['render_publish_receipt']['path']);assert pu['status']=='published_after_atomic_rename' and pu['case_id']==cid and pu['report_sha256_after_rebind']==sha(er['render_report']['path']);assert r['frames']==r['source_frames']==x['frames']==t['frames']==836 and x['particles']==t['particles']==179208 and r['all_frames_rendered'] and not r['diagnostic_only'] and r['nonfinite_active_states']==0
assert canonical==qi['actual_converter_condition_sha256']==s['physical_condition_roles']['native_request_condition_sha256']==s['physical_condition_roles']['actual_converter_scope_sha256']==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']=='7560a18fa29742681ee567b06567ed4052da8ceb138b601e94b5223df22660f5'
rawmask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',receipts['native']['request']),('XMF',x)]};assert rawmask==qi['actual_native_XMF_plan_field_namespaces']
for ns,masks in rawmask.items():
 for k,entry in masks.items():assert entry=={'present':False,'value':None} and s['physical_condition_roles']['native_and_xmf_plan_fields'][('native' if ns=='native' else 'xmf')+'_'+k]==entry
assert s['actual_dimensions']=={'fixed':111708,'floating':0,'fluid':67500,'frames':836,'moving':0,'particles':179208,'time_window_s':qi['actual_time_window_s'],'uid_lifecycle':'all native UIDs active each frame per Root1355 QI','vector_shape':'N x 3'}
vr=s['visual_review'];assert vr['status']=='visual-approved-by-delegated-agent' and vr['screen']=='pass_first_stage' and vr['new_case_credit']==0 and not vr['q_n_granted'] and not vr['q_e_granted'] and not vr['scientific_payload_opened_or_hashed_by_reviewer'] and not vr['scientific_jobs_started_or_restarted'] and not vr['shared_state_modified']
contacts=s['visual_evidence']['contacts'];keys=s['visual_evidence']['keys'];assert len(contacts)==35 and len(keys)==9 and v['contacts']==contacts and v['keys']==keys and [p['relative_path'] for p in contacts]==[f'all_frames_{i:03d}.png' for i in range(35)] and [int(Path(p['relative_path']).stem.split('_')[-1]) for p in keys]==[0,100,200,300,400,500,600,700,835]
published=Path(pu['published_output_root']);files={p['relative_path']:p for p in pu['files_excluding_receipt']};assert [p['path'] for p in contacts]==r['outputs']['contact_sheets']
for p in contacts+keys:
 path=Path(p['path']);entry=files[str(path.relative_to(published))];assert sha(path)==p['declared_sha256']==entry['sha256'] and path.stat().st_size==p['bytes']==entry['bytes'] and p['personally_viewed_with_view_image'] and p['sha256_source']=='render_publish_receipt'
en=s['historical_outer_envelope'];assert (en['outer_request_expected_frames'],en['outer_request_expected_particles'],en['actual_loaded_wrapper_frames'],en['actual_loaded_wrapper_particles'])==(801,194427,836,179208)
now=datetime.datetime.now(datetime.timezone.utc);assert dt(receipts['render']['finished_at_utc'])<=dt(ak['acknowledgement_timestamp_utc'])<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_276.json';cp=load(cpfile);assert cp['checkpoint']==276 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==310 and cp['accepted_per_family']['F3']==42
ip=root(1367)/'full336-current310-actual-final48-delivery-progress-index.json';idx=load(ip);target=next(row for row in idx['cases'] if row['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(p['kind'] for p in ld['attempts']);gpu=sum(p.get('gpu_seconds',0) for p in ld['charges'])/3600;cpu=sum(p.get('cpu_core_seconds',0) for p in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<dt(cp['deadline_utc'])
O=H/'root_stage1_source177178_F3_P0800AY0360_original987_full836QI_personal44PNG_date_only_acknowledgement_native_XMF_both_plan_absence_visual_acceptance_1368';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_277.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source177178-byte-exact-readonly-validation-own836QI-main44publishedPNG-date-only-current-acknowledgement-proof.json';put(vp,{'at_utc':now.isoformat(),'source_origins':origins,'source_files':[ref(R/n) for n in blobs],'before_after_source_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'actual_validator_command':['python3','-B',str(R/P.relative_to(W)/'validate_fresh177.py')],'source_README_stale_scripts_prefix_preserved':True,'own_full836_QI':ref(qip),'personal_review_acknowledgement':ref(R/akp.relative_to(W)),'source_only_review_date':s['reviewed_date_utc'],'source_exact_review_time_absent_and_not_backfilled':True,'acknowledgement_timestamp_is_current_confirmation_not_exact_earlier_review_completion':ak['acknowledgement_timestamp_utc'],'model_profile_confirmation_from_separate_acknowledgement':att,'all44_published_PNG_SHA_match_actual_publish':True,'actual_native_XMF_plan_field_namespaces':rawmask,'scientific_payload_IO':False,'case_credit':0})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':qi['actual_converter_condition_sha256'],'scope_schema':qi['scope_schema'],'source_review_commit':c177,'source_acknowledgement_commit':c178,'source_personal_visual_review':ref(R/sp.relative_to(W)),'source_personal_review_acknowledgement':ref(R/akp.relative_to(W)),'source_reviewed_date_utc':s['reviewed_date_utc'],'source_exact_review_timestamp_absent':True,'configured_reviewer_model':'gpt-5.6-luna','configured_reasoning_effort':'max','recursive_delegation':False,'independent_full836_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':836,'particle_count':179208,'initial_fluid_particles':67500,'actual_type_counts':{'fixed':111708,'moving':0,'floating':0,'fluid':67500,'total':179208},'actual_physical_window_s':qi['actual_time_window_s'],'all836_UID_N3_native_actual_times_finite_active_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':rawmask,'absent_plan_fields_not_filled_from_agreeing_canonical_digests':True,'historical_outer_envelope':en,'reused_parent_initialization_evidence':s['reused_initialization'],'parent_initial_QA_not_relabelled_as_new_percase_QA':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':35,'personal_reviewed_keyframes':9,'contact_sheets':[dict(p,sha256=p['declared_sha256']) for p in contacts],'keyframes':[dict(p,sha256=p['declared_sha256']) for p in keys],'visual_observations':vr['observations'],'visual_limits':vr['limitations'],'strict_container_guarantee':False,'subDP_precision_not_claimed':True,'no_strong_runup_magnitude_claim':True,'main_all44_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source177178-actual987-full836QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new['accepted_per_family']['F3']+=1;new.update(checkpoint=277,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=311,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: originalF3 987 full836 actual0/pub/ownQI1355 and source177 personal44PNG adopted once, with source178 separate current acknowledgement preserving date-only/exact-time/model absences in originalsource. Native/XMFbothplanabsences and staleouter801/194427 preserved. Total311 F3=43.',authorized_work_state='Active311/336 pending25. F1/F4/F6/F7=48 F2=43 F3=43 F5=33. F5original1188 and F2original1143 same real renders continue; durable ownQI1363/1366 after actual0/pub. Fresh192 unstarted F5review transferred to F5fresh212; F6fresh193 F2review boundedwait returned with no visualpackage, re-activate once ownQI ready. Source176 current42 readiness is historical assemblyutility, no new partial final48 claims.')
new['actual_progress']['source177178_actualF3_987_visual_acceptance']=ref(ap);new['source_agents']['production_recovery']='fresh177 personal44PNG andfresh178 date/model/chronology acknowledgement accepted; available for next actualpublished+QI review';new['source_agents']['f5_bed_recovery']='fresh212 originalF5 1188 assigned after explicit transfer from unstarted fresh192; waiting actual0/pub/ownQI1363';new['source_agents']['f6_endpoint_initial_qa']='fresh193 originalF2 1143 bounded wait returned while samehandle live; no package or personalPNG yet; resume after actual0/pub/ownQI1366; fresh192 no longer assigned'
new['next_executable_tasks']=['Observe same original1188 PID613708/start213820080 and1143 PID621866/start213876084; actualcompleted0/pub then durable ownQI1363/1366 once, supply source212 and reactivate source193 personalreviews.','Next real renderer is admitted by original unchanged registered queue; pin samePID/startticks and per-case actual metadata before preparing ownQI; no restarts or completed-QI repeats.','Finish all actual48 F2/F3/F5 families and finalcomplete delivery catalogs only after48 realaccepted; source176 current42 readiness historical reference assembler followed by independent full actual primary integrity/runtimeunknown review.','Home500GiB floor, cumulative failedoutputcleanup534.4086GiB/17203files retained; QNQE0 and precision unknown remain.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==311;put(np,new)
target.update(status='visual-approved-in-checkpoint277',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full836_QI=ref(qip));idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=311,registered_pending_independent_physical_cases=25,new_case_credit=1)
idx['actual_unaccepted_completed0_published_physical_cases']=[p for p in idx['actual_unaccepted_completed0_published_physical_cases'] if (p if isinstance(p,str) else p['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(p.get('accepted_decision')) for p in idx['cases'])==311;put(O/'full336-current311-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F3 original987 full836 preserving plan absences and review acknowledgement','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':277,'accepted':311,'F3':43,'pending':25,'new_decision':ref(dp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
