from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)};rel='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_130_f6_root951_delegated_visual_acceptance_v1';commit=subprocess.check_output(['git','rev-parse','e417d15d'],cwd=W,text=True).strip();files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',rel],cwd=W,text=True).splitlines();adopt=[]
for f in files:
 blob=subprocess.check_output(['git','show',f'{commit}:{f}'],cwd=W);p=R/f;p.parent.mkdir(parents=True,exist_ok=True);assert not p.exists() or p.read_bytes()==blob;p.write_bytes(blob);adopt.append(ref(p))
P=R/rel;c=load(P/'metadata/review-index.json');e=load(P/'metadata/evidence-files.json');assert c['decision']==c['status']=='visual-approved-by-delegated-agent' and c['reviewer']=='/root/f6_endpoint_initial_qa' and not c['case_credit_granted_by_agent'];visual=c['visual_review'];assert visual['all_contact_sheets_viewed'] and visual['all_requested_keyframes_viewed'] and len(visual['contact_sheets'])==11 and len(visual['keyframes'])==9
for v in e['entries']:assert sha(v['path'])==v['sha256']
for v in visual['contact_sheets']+visual['keyframes']:assert sha(v['path'])==v['sha256'] and v['viewed_with']=='view_image'
raw=c['upstream_chain'];q=load(raw['root951_request']['path']);cid=q['case_id'];pid=q['physical_case_id'];t=load(raw['typed_root607_report']['path']);m=load(raw['xmf_root699_manifest']['path']);rr=load(c['render_receipt']['path']);a=load(c['render_report']['path']);xf=raw['xmf_root699_case_xmf']['path'];dg=c['scope']['actual_converter_scope_sha256'];old=[load(p) for p in load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_127.json')['accepted_decisions']];assert len(old)==199 and pid not in {d.get('physical_case_id',d['case_id']) for d in old} and dg not in {d['physical_condition_sha256'] for d in old}
for key in ['native_root563_receipt','typed_root607_receipt','root658_audit_receipt']:
 rc=load(raw[key]['path']);assert (rc['status'],rc['returncode'])==('completed',0) and rc['request']['case_id']==cid
assert (rr['status'],rr['returncode'])==('completed',0) and rr['request_sha256']==sha(raw['root951_request']['path']);assert t['conversion_status']=='completed' and t['frames']==241 and t['particles']==417505 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['hash_scopes']['physical_condition_sha256']==dg and hashlib.sha256(json.dumps(t['hash_scopes']['physical_condition'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg;assert m['frames']==241 and m['particles']==417505 and m['source_h5_sha256']==t['output_sha256'] and m['physical_condition_sha256']==dg;gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==241 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='417505 3' for g in gs);assert [float(g.find('Time').get('Value')) for g in gs]==m['actual_time_s'];assert a['frames']==a['source_frames']==241 and a['all_frames_rendered'] and a['native_identity_axis_preserved'] and a['actual_times_preserved_exactly'] and a['nonfinite_active_states']==0 and a['source_h5_sha256']==t['output_sha256'] and a['manifest_sha256']==sha(raw['xmf_root699_manifest']['path']) and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf);ads=a['frame_diagnostics'];fs=t['lifecycle']['frame_summary'];assert len(ads)==len(fs)==241 and all(v['finite_positions_active'] and v['identity_axis_preserved'] and all(f['finite_active'] and f['nonfinite_active']==0 for f in v['finite_fields'].values()) for v in ads);assert all(v['missing_particles']==d['missing'] for v,d in zip(fs,ads));audit=load(raw['root658_audit_report']['path']);assert audit['status']=='pass' and all(audit['checks'].values()) and audit['checks']['independent_floatinginfo_state0_pass'] and audit['producer_physical_condition_sha256']==dg
O=H/'root_stage1_F6_delegated130_actual951_first_full241_independent_metadata_closure_pending_physical_sidecar_961';O.mkdir(exist_ok=False);out={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_commit':commit,'adopted_files':adopt,'source_byte_exact':True,'family_id':'F6','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'scope_separation':c['scope'],'full241_N3_QI_and_actual_times_and_PartVTK_verified':True,'independent_floatinginfo_state0_audit658_actual0_pass':True,'delegated_all11_contact_and9_keyframes_viewed_and_hashed':True,'main_PNG_personal_review':False,'full_render_receipt':ref(c['render_receipt']['path']),'full_render_report':ref(c['render_report']['path']),'typed_report':ref(raw['typed_root607_report']['path']),'xmf_manifest':ref(raw['xmf_root699_manifest']['path']),'audit658_report':ref(raw['root658_audit_report']['path']),'lifecycle':{'maximum_missing_particles':max(v['missing_particles'] for v in fs),'nonzero_missing_frame_count':sum(v['missing_particles']>0 for v in fs),'missing_events_sum':sum(v['missing_particles'] for v in fs),'final_missing_particle_count':fs[-1]['missing_particles'],'final_missing_UIDs_from_actual_producer':fs[-1]['missing_id_first'],'final_active_particles':fs[-1]['active_particles'],'causes_unassigned':True,'events_not_final_UID_count':True},'delegated_visual_observations':c['visual_observations'],'pending_before_case_credit':'explicit delegated physical-visual sidecar covering wrong initialstate, severe penetration/explosion/earlytermination and visible release/impact/pose mechanism requested within fresh131; camera completeness alone not sufficient','case_credit':0,'prior_accepted_count':199,'main_science_payload_IO':False,'q_n_granted':False,'q_e_granted':False};(O/'actual130-adoption-and-independent-metadata-closure.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(v['path']).relative_to(R)) for v in adopt]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify delegated full241 metadata and retain explicit physical visual closure pending','--',*paths],cwd=R,check=True);print({'metadata_closure_pass':True,'lifecycle':out['lifecycle'],'count199_held_for_physical_visual_sidecar':True,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
