from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');O=H/'root_stage1_F4_delegated116_actual638_two_visual_metadata_integration_825';O.mkdir();load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def norm(cid):return cid.replace('F4_DROP_B08_','F4_DROP_')
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_104.json')['accepted_decisions'];assert len(prior)==137;ids={norm(load(p).get('physical_case_id',load(p)['case_id'])) for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior};decisions=[]
commit=subprocess.check_output(['git','rev-parse','0c6e5df0'],cwd=W,text=True).strip();S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_116_*'));rel=S.relative_to(W);adopted=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
 p=W/name;assert p.suffix in {'.json','.md','.py'};blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert p.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists();dst.write_bytes(blob);adopted.append(ref(dst))
P=R/rel;idx=load(P/'metadata/review-index.json');assert idx['reviewer']=='/root/f6_endpoint_initial_qa' and len(idx['cases'])==2
for row in idx['cases']:
 cl=P/'metadata'/Path(row['metadata_closure_path']).name;c=load(cl);cid=c['case_id'];pid=c['physical_case_id'];m=c['producer_metadata'];sc=c['scope_separation'];dg=sc['actual_converter_physical_condition_sha256'];assert norm(pid) not in ids and dg not in hashes and row['status']==c['visual_decision']['status']=='visual-approved-by-delegated-agent';assert row['root638_lineage'];ev={}
 for k in ['gencase','basic_qa','native','frame0_qa','typed','xmf','render']:
  rp=m[k+'_receipt_path'];r=load(rp);assert sha(rp)==m[k+'_receipt']['sha256'] and (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;ev[k+'_receipt']=ref(rp)
 assert sha(sc['actual_owner_file_path'])==sc['actual_owner_file_sha256'];assert sha(sc['source_owner_path'])==sc['source_owner_sha256'];assert sha(sc['source_definition_path'])==sc['source_definition_sha256'];actualowner=load(sc['actual_owner_file_path']);assert actualowner['physical_condition_sha256']==sc['actual_owner_file_declared_physical_condition_sha256']
 prep=load(m['prepared_input_report_path']);assert prep['actual_total_particles']==83233 and prep['actual_generated_constants']['data2d']['value']=='false';assert sha(m['generated_xml_path'])==m['generated_xml_sha256_attested_by_gencase'];assert m['gencase_counts']['fluid_particles']==59072 and m['gencase_counts']['solver_dimension']==3
 qa=load(m['initial_native_qa_report_path']);q=next(x for x in qa['cases'] if x['case_id']==cid);assert q['pass'] and q['actual_total_particles']==83233 and q['actual_particle_counts']=={'fixed':24161,'moving':0,'floating':0,'fluid':59072}
 t=load(m['conversion_report_path']);assert t['conversion_status']=='completed' and t['frames']==1201 and t['particles']==83233 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and t['hash_scopes']['physical_condition_sha256']==dg;assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=1.2 and t['time_evidence']['strictly_increasing'];assert t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0'
 x=load(m['xmf_manifest_path']);assert x['frames']==1201 and x['particles']==83233 and x['source_h5_sha256']==t['output_sha256'] and x['physical_condition_sha256']==dg;xf=x['xdmf'];assert sha(xf)==x['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==1201 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='83233 3' for g in gs)
 a=load(m['render_report_path']);assert a['frames']==a['source_frames']==1201 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(m['xmf_manifest_path']) and a['source_h5_sha256']==t['output_sha256'] and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf);assert len(a['frame_diagnostics'])==1201 and all(f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in a['frame_diagnostics'])
 fs=t['lifecycle']['frame_summary'];assert len(fs)==1201;maximum=max(f['missing_particles'] for f in fs);events=sum(f['missing_particles']>0 for f in fs);assert maximum<=1 and events in [0,76] and fs[-1]['missing_particles'] in [0,1];pngp=P/'metadata'/Path(row['png_hash_manifest_path']).name;png=load(pngp);assert png['computed_after_view_image'] and png['viewed_with']=='view_image' and len(png['contact_sheets'])==51 and len(png['key_frames'])==9
 for p in png['contact_sheets']+png['key_frames']:assert sha(p['path'])==p['sha256']
 for k in ['prepared_input_report_path','initial_native_qa_report_path','conversion_report_path','xmf_manifest_path','render_report_path']:ev[k]=ref(m[k])
 out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':row['status'],'family_id':'F4','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'source_review_commit':commit,'source_review_closure':ref(cl),'visual_reviewer':idx['reviewer'],'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':c['visual_decision']['observations'],'agent_limitations':c['visual_decision']['limitations'],'scope_separation':sc,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':png,'actual_frames':1201,'actual_particles':83233,'actual_fluid_particles':59072,'actual_last_time_s':t['time_evidence']['last_s'],'delegated_review_lifecycle_original':c['lifecycle'],'root_metadata_derived_lifecycle':{'source':ref(m['conversion_report_path']),'maximum_missing_particles_per_frame':maximum,'missing_frame_event_count':events,'final_missing_particle_count':fs[-1]['missing_particles'],'final_missing_UIDs_producer_report':fs[-1]['missing_id_first'],'not_inferred_from_images':True},'maximum_missing_particles':maximum,'lifecycle_limitation':'1 late native fluid UID exclusion, cause unknown, states unfilled; 76 missing-frame events are separate from distinct missing UID counts' if maximum else 'No native missing particles in producer frame summaries','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':137+len(decisions),'resulting_count':138+len(decisions)}
 dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);decisions.append(str(dp));ids.add(norm(pid));hashes.add(dg)
put(O/'actual-integration-review.json',{'source_commit':commit,'adopted_files':adopted,'source_adopted_byte_exact':True,'previous_count':137,'resulting_count':137+len(decisions),'independent_case_increment':len(decisions),'decisions':decisions,'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'new_cases':len(decisions),'accepted':137+len(decisions)})
