from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.png','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit=subprocess.check_output(['git','rev-parse','c5b5e01a5'],cwd=W,text=True).strip();prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_171_stage1_f5_m086_full801_visual_review_and_bed1012_wait_v1';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==8;adopted=[]
for name in names:
 assert Path(name).suffix in {'.json','.py','.md'};raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_F5_delegated171_M086T085_actual969_full801_bed_QI_visual_scope_dedup_correction_1023';O.mkdir(exist_ok=True);assert not (H/"ROOT_LIVE_RESUMPTION_CHECKPOINT_149.json").exists() and not list(O.glob("*-delegated-visual-decision.json"))
vp=P/'metadata/fresh171-m086-t085-visual-review.json';v=load(vp);a=v['actual_producer'];validator=P/'scripts/validate_fresh171.py';r=subprocess.run([str(L/'.venv/bin/python'),str(validator)],capture_output=True,text=True);put(O/'original-source171-validator-result.json',{'returncode':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'validator':ref(validator),'original_validator_pass_does_not_prove_dedup_booleans':True});assert r.returncode==0
for value in a.values():
 if isinstance(value,dict) and 'path' in value and 'sha256' in value:assert sha(value['path'])==value['sha256']
assert v['no_science_payload_opened_or_hashed_by_source_owner'] and v['no_jobs_started_by_source_owner'];assert v['png_review']['all_34_contact_sheets_reviewed'] and v['png_review']['event_keyframes_reviewed']==[0,97,153,219,400,718,800]
ps=v['png_review'];assert len(ps['all_34_contact_sheets'])==34 and len(ps['event_keyframes'])==7
for p in ps['all_34_contact_sheets']+ps['event_keyframes']:assert Path(p['path']).suffix=='.png' and sha(p['path'])==p['sha256']
assert v['delegated_visual_decision']['decision']=='visual_pass_for_M086_T085_full801' and not v['delegated_visual_decision']['case_credit_granted_by_this_review']
t=load(a['conversion_report']['path']);x=load(a['xmf_manifest']['path']);bed=load(a['bed_report']['path']);br=load(a['bed_receipt']['path']);rs=load(a['render_report']['path']);rr=load(a['execution_receipt']['path']);xr=Path(a['xmf_manifest']['path']).parent.parent/'execution-receipt.json';canonical=a['canonical_physical_condition_sha256'];actual=a['source_h5_legacy_scope_sha256'];plan=a['source_plan_physical_condition_sha256'];pid=v['physical_case_id'];cid=v['case_id'];N=194427;F=801
ch={'gencase':{'execution_receipt':x['gencase_receipt'],'generated_xml':t['source_provenance']['generated_xml']['path'],'prepared_input_report':x['gencase_prepared_report']},'initial_native_qa':{'execution_receipt':x['initial_qa_receipt'],'report':x['initial_qa_report']},'native_full':{'execution_receipt':x['full_native_receipt']},'typed':{'execution_receipt':x['typed_receipt'],'conversion_report':a['conversion_report']['path']},'xmf':{'execution_receipt':str(xr),'manifest':a['xmf_manifest']['path'],'case_xmf':a['xmf_xml']['path']},'bed_audit':{'execution_receipt':a['bed_receipt']['path'],'report':a['bed_report']['path']},'render':{'execution_receipt':a['execution_receipt']['path'],'report':a['render_report']['path'],'publish_receipt':a['render_publish_receipt']['path']}}
receipts={}
for role,c in ch.items():
 z=load(c['execution_receipt']);assert (z['status'],z['returncode'])==('completed',0) and z['request']['case_id']==cid;receipts[role]=z
assert t['source_provenance']['solver_receipt']==ref(ch['native_full']['execution_receipt']) and t['source_provenance']['gencase_receipt']==ref(ch['gencase']['execution_receipt']) and t['source_provenance']['generated_xml']==ref(ch['gencase']['generated_xml'])
assert receipts['native_full']['request']['physical_case_id']==pid and receipts['native_full']['request']['physical_condition_sha256']==canonical
for k in ['full_native_receipt','gencase_receipt','gencase_prepared_report','initial_qa_receipt','initial_qa_report','typed_receipt']:assert sha(x[k])==x[k+'_sha256']
assert bed['bound_actual_inputs']['stage1_placement']['all_basic_placement_checks_pass'] and not bed['bound_actual_inputs']['stage1_placement']['numerical_precision_result_accepted']
for z in bed['bound_actual_inputs']['records']:assert sha(z['path'])==z['sha256']
assert bed['bound_actual_inputs']['physical_case_id']==pid and bed['bound_actual_inputs']['case_id']==cid
assert bed['physical_condition_sha256']==x['physical_condition_sha256']==canonical and bed['source_h5_physical_condition_sha256']==x['source_h5_physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==actual and bed['source_plan_physical_condition_sha256']==x['source_plan_physical_condition_sha256']==plan
assert t['output_sha256']==bed['source']['trajectory_h5_sha256']==x['source_h5_sha256']==rs['source_h5_sha256']==a['typed_h5_sha256_producer_attested']
h=t['output_hdf5'];assert bed['source']['trajectory_h5']==h
for rec in [br,rr]:assert rec['input_hashes_at_launch'][h]==rec['input_hashes_after_run'][h]==rec['request']['input_sha256'][h]==t['output_sha256']
assert rs['manifest_sha256']==sha(a['xmf_manifest']['path']) and x['xdmf_sha256']==sha(a['xmf_xml']['path'])
assert not bed['source_arrays_modified'] and not bed['source_arrays_dropped_or_masked'] and bed['q_n_status']=='not_granted';assert t['conversion_status']=='completed' and t['frames']==rs['frames']==rs['source_frames']==x['frames']==F and t['particles']==x['particles']==N and t['solver_dimension']['solver_dimension']==3
assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
assert t['partvtk_validation']['all_passed'] and all(z['passed'] and z['identity_type_mk_exact'] for z in t['partvtk_validation']['frames'])
assert rs['all_frames_rendered'] and rs['actual_times_preserved_exactly'] and rs['native_identity_axis_preserved'] and rs['nonfinite_active_states']==0
fs=t['lifecycle']['frame_summary'];bf=bed['frame_reports'];ds=rs['frame_diagnostics'];grids=ET.parse(a['xmf_xml']['path']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(bf)==len(ds)==len(grids)==F and times==[z['time'] for z in fs]==[z['time_s'] for z in bf]==[z['actual_time_s'] for z in ds]==[float(g.find('Time').get('Value')) for g in grids] and times[0]==0 and times[-1]>=16 and all(a<b for a,b in zip(times,times[1:]))
maxima={'one_dp':0,'two_dp':0,'missing_initial_fluid':0,'unexpected_uid':0,'nonfinite_position':0,'nonfinite_mass':0,'all_missing':0,'outside_x':0,'outside_y':0}
for i,(f,z,d,g) in enumerate(zip(bf,fs,ds,grids)):
 assert f['frame']==z['frame']==d['frame']==i and f['particle_axis_count']==N and f['initial_fluid_uid_count']==f['current_valid_type3_fluid_count']==31658
 vals={'one_dp':f['penetration']['one_dp']['count'],'two_dp':f['penetration']['two_dp']['count'],'missing_initial_fluid':f['uid_tracking']['missing_initial_uid']['count'],'unexpected_uid':f['uid_tracking']['unexpected_current_uid']['count'],'nonfinite_position':f['nonfinite_position_current_fluid_count'],'nonfinite_mass':f['nonfinite_mass_current_fluid_count'],'all_missing':z['missing_particles'],'outside_x':f['bed_domain']['x_outside_exact_profile_domain_count'],'outside_y':f['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']}
 for k,value in vals.items():maxima[k]=max(maxima[k],value)
 assert not any(vals.values()) and z['active_particles']==d['active']==N and d['missing']==0 and d['identity_axis_preserved'] and d['finite_positions_active'] and all(w['finite_active'] and w['nonfinite_active']==0 for w in d['finite_fields'].values())
 assert d['type_counts_active']=={'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'unknown':0}
 assert f['bed_domain']['finite_bed_footprint_evaluable_count']==31658 and f['bed_domain']['fraction_of_initial_fluid_uid_set']==1 and not f['unexplained_state']['nonfinite_or_lost_initial_uid_present']
 for name,threshold in [('one_dp',0.02),('two_dp',0.04)]:
  b=f['penetration'][name];assert b['threshold_m']==threshold and b['footprint_evaluable_count']==31658 and b['fraction_of_initial_fluid_uid_set']==b['fraction_of_finite_bed_footprint_fluid']==b['fraction_of_current_valid_type3_fluid']==0
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')==f'{N} 3';vv=next(z for z in g.findall('Attribute') if z.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')==f'{N} 3'
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_148.json');old=[load(p) for p in cp['accepted_decisions']];assert len(old)==225 and pid not in {z.get('physical_case_id',z['case_id']) for z in old} and canonical not in {z['physical_condition_sha256'] for z in old}
dedup=load(P/'metadata/fresh171-accepted217-dedup.json');assert dedup['m086_t085_already_accepted'] and not any(dedup['matches'].values())
proof=O/'actual969-full801-bed-QI-972-render-source171-independent-closure.json';put(proof,{'adopted_files':adopted,'actual_completed_chain':ch,'physical_case_id':pid,'diagnostic_maxima':maxima,'all801_native_typed_bed_XMF_XML_render_actual_times_match':True,'all31658_initial_fluid_UIDs_retained_finite_all801':True,'source171_dedup_false_positive_preserved':ref(P/'metadata/fresh171-accepted217-dedup.json'),'dedup_actual_cp148_matches':[],'actual_dedup_by_physical_id_and_canonical_scope':'new independent case','original_disabled_binding_full801_authorized_false_preserved':'outer Root969/972 registered requests authorized by user GOAL; original binding flags remain untouched','original_precision_negative_and_no_pronounced_wave_visual_limit_preserved':v['historical_boundaries'],'visual_limitation':ps['visual_observation'],'main_scientific_payload_IO':False,'new_scientific_attempts':0,'q_n_granted':False,'q_e_granted':False})
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':actual,'source_plan_physical_condition_sha256':plan,'producer_scope_schema_verified_from_actual_report':t['hash_scopes']['physical_condition']['schema'],'source_visual_review':ref(vp),'source_visual_review_commit':commit,'actual_completed_metadata_evidence':ch,'full_native_frames':F,'particles':N,'actual_physical_window_s':[times[0],times[-1]],'lifecycle':{'final_missing_particles':0,'frames_with_any_missing_particle':0,'cumulative_particle_frame_omissions':0,'all_fixed_moving_fluid_UIDs_retained_all801':True},'family_specific_proof':ref(proof),'stage1_QI_full_native_identity_and_state_verified':True,'all_actual_times_exact_typed_XMF_XML_render_bed':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':ps['visual_observation'],'visual_mechanism_limit':v['delegated_visual_decision']['visual_mechanism_strength'],'historical_precision_negative':v['historical_boundaries'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};dp=O/(pid+'-delegated-visual-decision.json');put(dp,decision);cp['accepted_per_family']['F5']+=1
cp.update(checkpoint=149,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_148.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_148.json'),stage1_visual_accepted_complete_independent_cases=226,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=shutil.disk_usage('/home/jade').free/1024**3,previous_goal_turn_classification='Progress: genuine F5 M086T085 full801 existing native/typed/bed/XMF/render0 and source171 personal34contacts7keys independently accepted226; source171 incorrect already-accepted booleans preserved with actual physical-ID/scope dedup correction. Weak bounded surface variation and prior precision-negative retained. Failed-native cleanup439GiB remains protected; no repeat native computation.')
cp['actual_progress']['F5_source171_M086T085_full801_independent_acceptance']=ref(proof);cp['next_executable_tasks']=['Integrate fresh143 two F6 real full241 visual/omega/state0/H5-audit scope closure.','Launch bounded full836 renders only from actual completed XMF1002AY0430 and1010AY0460; preserve live existing jobs.','Adopt source172 real1017native0 F5 typed157 Home4GiB disabled successors, no native reruns.','Observe actual1016 three F5 original138 full801 bed audits and register renders only upon full-frame diagnostic closure.']
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==226
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_149.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(z['path']).relative_to(R)) for z in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_149.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 M086T085 full801 visuals with actual UID bed closure and dedup correction','--',*paths],cwd=R,check=True);print({'accepted':226,'counts':cp['accepted_per_family'],'diagnostic_maxima':maxima,'Home_free_GiB':cp['home_free_gib'],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
