from pathlib import Path
import json,hashlib,ast,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_F5_actual808_remaining9_typed_storage_bound_wait_shared_CPU2_repair1_854';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def root(n):return next(H.glob(f'root*_{n}'))
def sha(p):
 p=Path(p);assert p.suffix not in {'.h5','.bi4','.csv','.dat','.vtk','.vtu'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
old=root(820);res=load(old/'controller-result.json');assert res['actual_full801_typed_pass_count']==1;failure=res['results'][1];r=load(failure['actual_receipt']);assert r['error']=='RuntimeError: Home free-space floor would be crossed' and r.get('pid') is None and r['bytes']==0 and r.get('returncode') is None
success=res['results'][0];sr=load(success['actual_receipt']);cr=load(success['actual_conversion_report']);assert (sr['status'],sr['returncode'])==('completed',0) and cr['frames']==801 and cr['particles']==194427 and cr['conversion_status']=='completed';source=L/'scripts/ds_data02_direct_convert.py';assert 'dtype="f4"' in source.read_text();bound=(801*194427*40+194427*13+801*8);assert bound<8*1024**3 and sr['bytes']<2*1024**3
proof=O/'storage-estimate-and-prelaunch-failure-review.json';put(proof,{'failed_before_worker':ref(failure['actual_receipt']),'original_failed_request':ref(failure['request']),'actual_first_full801_typed_receipt':ref(success['actual_receipt']),'actual_first_conversion_report':ref(success['actual_conversion_report']),'immutable_converter_source':ref(source),'expected_frames':801,'expected_particles':194427,'schema_per_frame_particle_bytes':40,'time_and_initial_metadata_bytes_included':True,'uncompressed_scientific_dataset_bytes':bound,'uncompressed_bound_gib':bound/2**30,'actual_completed_attempt_bytes':sr['bytes'],'actual_h5_stat_bytes':Path(cr['output_hdf5']).stat().st_size,'scientific_payload_not_read_or_hashed':True,'original_estimate_gib':128,'new_conservative_estimate_gib':32,'new_estimate_exceeds_four_times_uncompressed_schema_bound':32*1024**3>4*bound,'NVMe_stage_limit24_and_floor100_unchanged':True,'Home_min_free_gib_unchanged':500,'physics_and_converter_unchanged':True,'distinct_attempts_preserve_old_failure':True})
cfg=load(old/'controller-config.json');rows=[]
for row in cfg['rows']:
 if row['tag']==success['tag']:continue
 qp=Path(row['actual_request']);q=load(qp);arp=Path(q['attempt_root'])/'execution-receipt.json'
 if arp.exists():
  rr=load(arp);assert rr.get('pid') is None and rr['bytes']==0 and rr['status']=='failed'
 q['attempt_id']+='-storage-bound-repair1-root854';q['attempt_root']=str(Path(q['attempt_root']).with_name(q['attempt_id']));assert not Path(q['attempt_root']).exists();q['estimated_storage_bytes']=32*1024**3;q['root_storage_estimate_review']=str(proof);q['root_original_prelaunch_request']=str(qp);q['input_sha256'].update({str(proof):sha(proof),str(qp):sha(qp)});q['input_files']=sorted(q['input_sha256']);nqp=O/'requests'/(row['tag']+'-typed-request.json');nqp.parent.mkdir(exist_ok=True);put(nqp,q);rows.append({**row,'actual_request':str(nqp),'original_root820_request':str(qp)})
assert len(rows)==9;newcfg={**cfg,'rows':rows,'old_820_terminal_result':str(old/'controller-result.json'),'storage_estimate_review':str(proof)};put(O/'controller-config.json',newcfg)
s=(old/'batch-controller.py').read_text();s=s.replace('import json,subprocess,time,fcntl,datetime','import json,subprocess,time,fcntl,datetime,shutil');s=s.replace("while sum(x.get('cpu_threads',0) for x in load(D/'runtime/resource-ledger.json')['reservations'])+2>64:time.sleep(3)","while True:\n   ledger=load(D/'runtime/resource-ledger.json');reserved=sum(x.get('new_storage_bytes',0) for x in ledger['reservations']);free=shutil.disk_usage('/home/jade').free\n   if sum(x.get('cpu_threads',0) for x in ledger['reservations'])+4<=64 and free-reserved-q['estimated_storage_bytes']-16*1024**3>=ledger['limits']['home_min_free_bytes']:break\n   time.sleep(3)")
s=s.replace("'requested':10","'requested':9").replace('10-len(results)','9-len(results)').replace('len(results)==10','len(results)==9');ast.parse(s);put(O/'controller-contract.json',{'distinct_attempts':9,'old_prelaunch_failure_preserved':True,'same_science_workers_inputs':True,'same_shared_conversion_lock':cfg['shared_conversion_dispatch_lock'],'estimated_Home_output_gib':32,'pre_registration_wait_Home_and_CPU':True,'extra_space_wait_margin_gib':16,'shared_CPU_cap':64,'Home_floor_gib':500,'CPU_per_conversion':2,'max_concurrency':1,'case_credit':0});(O/'batch-controller.py').write_text(s);(O/'root-preparation-source.py').write_bytes(Path(__file__).read_bytes());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',str(O.relative_to(R))],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: recover F5 typed queue using schema storage bound and capacity wait'],cwd=R,check=True,stdout=subprocess.DEVNULL);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()
with (O/'controller.log').open('ab') as log:p=subprocess.Popen([str(L/'.venv/bin/python'),str(O/'batch-controller.py')],cwd=L,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
f=(Path('/proc')/str(p.pid)/'stat').read_text().split(') ',1)[1].split();out={'pid':p.pid,'proc_start_ticks':f[19],'controller':str(O/'batch-controller.py'),'controller_sha256':sha(O/'batch-controller.py'),'launch_commit':commit,'actual_launched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()};put(O/'controller-launch-process.json',out);print(json.dumps(out))
