from pathlib import Path
import json,hashlib,datetime,subprocess,copy,os,collections,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='e6027606d5486930436ec5734c94beceb2e56dd1';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob('root_followup_183_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();expected={'README.md','build_fresh183.py','validate_fresh183.py','package-manifest.json','metadata/actual1009-personal-visual-decision.json','metadata/png-evidence/actual1009.json'};assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
man=load(P/'package-manifest.json');assert {e['path'] for e in man['files']}==expected-{'package-manifest.json'} and man['package_manifest_excluded_from_own_hash']
for e in man['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh183.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1392)/'actual1009-full401-own-QI-UID-N3-native-typed-role-thirtyfive-fluid-omissions-previsual-proof.json';qi=load(qip);assert sha(qip)=='486e2a2446d4e0ccc7785d966cd4f0dea016691efadd33ce244f943bb62a71a0'
s=load(P/'metadata/actual1009-personal-visual-decision.json');png=load(P/'metadata/png-evidence/actual1009.json');cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_canonical_condition_sha256'];legacy=qi['typed_XMF_actual_legacy_producer_condition_sha256'];assert s['case_id']==png['case_id']==cid and s['physical_case_id']==png['physical_case_id']==pid and s['actual_case_family']=='F2' and s['assigned_worktree_family']=='F3'
assert s['configured_model']=='gpt-5.6-luna/max' and not s['model_substitution'] and not s['recursive_delegation'];checked(s['provenance']['qi_proof']);assert s['provenance']['qi_proof']['path']==str(qip)
er=qi['actual_completed_metadata_evidence']
for k,e in er.items():
 checked(e)
 if k.endswith('_receipt') and k!='render_publish_receipt':
  rr=load(e['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
for k,e in s['actual_chain'].items():
 checked(e)
 if k in er:assert e['path']==er[k]['path'] and e['sha256']==er[k]['sha256']
assert qi['all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified'] and qi['genuine_initial_QA_receipt_completed0_and_report_pass'] and qi['frames']==401 and qi['particles']==418104
life=qi['lifecycle_omissions'];assert life==s['lifecycle_omissions'] and life['final_missing_particles']==35 and life['first_missing_frame']==137 and life['cumulative_particle_frame_omissions']==8397 and life['max_missing_per_frame']==35 and life['final_Idp_sample_is_partial_not_all35'] and life['missing_location_state_cause_unknown'] and life['final_missing_Idp_digest_producer_attested']=='77346a6b93920a09238dc62bedfa2e7b411baf9ecff05a83d71daaaa3f882766'
dims=s['actual_dimensions'];assert dims['time_window_s']==qi['actual_time_window_s'] and dims['initial_type_counts']==qi['actual_initial_type_counts'] and dims['terminal_type_counts']==qi['actual_terminal_type_counts']
nq=load(er['native_receipt']['path'])['request'];x=load(er['XMF_manifest']['path']);masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};roles=s['physical_condition_roles'];assert masks==qi['actual_native_XMF_plan_field_namespaces']==roles['native_and_xmf_plan_fields'];assert nq['physical_condition_sha256']==canonical==roles['native_canonical_condition_sha256'] and x['physical_condition_sha256']==legacy==roles['xmf_physical_condition_sha256']==roles['typed_legacy_converter_scope_sha256'] and roles['xmf_canonical_source_physical_condition_sha256']==canonical
visual=s['visual_review'];assert visual['status']=='visual-approved-by-delegated-agent' and visual['screen']=='pass_first_stage' and visual['contact_sheets_viewed']==17 and visual['key_frames_viewed']==list(range(0,401,50)) and visual['case_credit']==0 and not visual['q_n_granted'] and not visual['q_e_granted'] and not visual['scientific_payload_opened_or_hashed_by_reviewer']
contacts=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'sheet_index':i,'viewed':e['personally_viewed_with_view_image']} for i,e in enumerate(s['visual_evidence']['contacts'])];keys=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'frame':f,'viewed':e['personally_viewed_with_view_image']} for f,e in zip(range(0,401,50),s['visual_evidence']['keys'])];assert len(contacts)==17 and len(keys)==9 and png['contacts']==s['visual_evidence']['contacts'] and png['keys']==s['visual_evidence']['keys'] and png['personally_viewed_after_atomic_publish']
pub=load(er['render_publish_receipt']['path']);report=load(er['render_report']['path']);receipt=load(er['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['render_report']['path']);pubroot=Path(pub['published_output_root']);pubfiles={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==report['outputs']['contact_sheets']
for e in contacts+keys:
 checked(e);pr=pubfiles[str(Path(e['path']).relative_to(pubroot))];assert e['sha256']==pr['sha256'] and e['bytes']==pr['bytes'] and e['viewed']
reviewed=s['review_completed_at_utc'];now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(receipt['finished_at_utc'])<=datetime.datetime.fromisoformat(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_299.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==319 and cp['accepted_per_family']['F2']==45 and pid not in {load(p)['physical_case_id'] for p in cp['accepted_decisions']};ip=root(1400)/'full336-current319-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);target=next(v for v in idx['cases'] if v['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(v['kind'] for v in ld['attempts']);gpu=sum(v.get('gpu_seconds',0) for v in ld['charges'])/3600;cpu=sum(v.get('cpu_core_seconds',0) for v in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source183_actualF2_RX049ROT075_original1009_full401QI_personal26PNG_thirtyfive_fluid_omissions_genuineQA_native_XMF_roles_visual_acceptance_1402';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_300.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
ack=O/'source183-personal-PNG-viewing-and-unknown-omission-location-scope-clarification.json';put(ack,{'source_commit':commit,'source_bytes_preserved':True,'source_ambiguous_content_read_or_hashed_by_reviewer_false_preserved':True,'source_agent_explicit_final_confirmed_personally_viewed_all17contacts9keys_with_view_image':True,'personal_review_time_utc':reviewed,'stat_and_declared_SHA_only_scope_is_builder_validator_not_personal_visual_view':True,'actual_visual_review_reads_published_PNG_derivatives':True,'main_all26_PNG_hashes_verified':True,'main_personally_viewed_PNGs':False,'main_scientific_payload_IO':False,'visual_detached_points_do_not_establish_missing_UID_location_state_or_cause':True,'unknown_missing_particle_location_state_cause_remains_unknown':True})
proof=O/'source183-byte-exact-readonly-main26publishedPNG-own401QI-genuineQA-proof.json';put(proof,{'schema':'ds02.main.F2.source183.personal26PNG-adoption-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'independent_ownQI':ref(qip),'all26_publishedPNG_hashes_match_actual_atomic_publish':True,'actual_personal_review_time_utc':reviewed,'review_after_completed_publication':True,'actual_native_XMF_plan_field_namespaces':masks,'all_actual_primary_refs_and_genuine_QA_receipts_verified':True,'lifecycle_omissions_retained':life,'source_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F3','source_personal_visual_review':ref(R/prefix/'metadata/actual1009-personal-visual-decision.json'),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':401,'particle_count':418104,'actual_initial_type_counts':qi['actual_initial_type_counts'],'actual_terminal_type_counts':qi['actual_terminal_type_counts'],'actual_type_counts':qi['actual_initial_type_counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all401_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':False,'lifecycle_omissions':life,'actual_native_XMF_plan_field_namespaces':masks,'nativecanonical_and_typedlegacy_distinct_roles':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'actual_personal_review_time_utc':reviewed,'contact_sheets':contacts,'keyframes':keys,'visual_observations':visual['observations'],'visual_limits':visual['physical_screen_limits'],'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'historical_outer_expected_fields':s['historical_outer_envelope'],'main_all26_PNG_hashes_match_actual_atomic_publish':True,'source_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source183-actual1009-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(proof),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1
new.update(checkpoint=300,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=320,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source183 actual F2RX049ROT075 original1009 personal17contacts9keys accepted once after completed own1392 full401/source6exact/readonlyvalidation/all26pubPNG/genuine QA closure. 35fluid omissions first137/cumulative8397 remain unknown location/state/cause and partialsample retained; ambiguous PNG stat flag clarified using explicit personalview confirmation.',authorized_work_state='Active320/336 pending16. F2=46 F3=45 F5=37. Production184 F5original1158 personal43 review active. F5child219 original1190 boundedwait truecompleted0/pub/own1399. Original1031 durable1401 ready; both originals same registeredlaunches live. Source196 F3 repair active; source218 completed tool repair awaits main audit; next197 F2 separate repair authorized.')
new['actual_progress']['source183_F2_actual1009_visual_acceptance']=ref(ap);new['source_agents']['production_recovery']='fresh183 original1009 accepted once; fresh184 F5original1158 personal34+9 active';new['source_agents']['f5_bed_recovery']='fresh218 tool repair committed7b806 awaitingmainaudit; fresh219 original1190 personal34+9 boundedwait actualcompleted0/pub/mainown1399';new['next_executable_tasks'].insert(0,'Adopt source184 F5actual1158 personal visual after completedsource/readonlyvalidation/own1397/publishedPNG closure. After next1190/1031 truecompleted0/pub execute own1399/1401 once; supply personal219/nextF3 review. Audit218/196 once, then main actualprimary joins rather than infinite tool repair.');assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==320;put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=320,registered_pending_independent_physical_cases=16,new_case_credit=1);target.update(status='visual-approved-in-checkpoint300',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip));idx['actual_unaccepted_completed0_published_physical_cases']=[v for v in idx['actual_unaccepted_completed0_published_physical_cases'] if (v if isinstance(v,str) else v['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(v.get('accepted_decision')) for v in idx['cases'])==320;put(O/'full336-current320-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX049 ROT075 personal review preserving35 fluid omissions','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':300,'accepted':320,'F2':46,'pending':16,'decision':ref(dp),'home_free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
