from pathlib import Path
import json,hashlib,runpy,subprocess,xml.etree.ElementTree as ET,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
sourceq=root(1193)/'enabled-full836-audit-qualified-XMF-request.json';xq=load(sourceq);bp=Path(xq['binding_path']);b=load(bp);xr=Path(xq['attempt_root'])/'execution-receipt.json';rec=load(xr);xp=Path(xq['attempt_root'])/'xdmf/manifest.json';x=load(xp);xml=Path(x['xdmf']);tp=Path(b['conversion_report']['path']);t=load(tp);ap=Path(b['artifact_audit_receipt']['path']);audit=load(ap);arp=Path(b['artifact_audit_report']['path']);a=load(arp);np=Path(b['native_receipt']['path']);native=load(np);op=Path(b['original_conversion_receipt']['path']);old=load(op);h5=b['trajectory_h5'];canonical=b['physical_condition_sha256'];actual=b['actual_converter_scope_sha256'];pid=b['physical_case_id']
assert all((r['status'],r['returncode'])==('completed',0) for r in [rec,audit,native]);assert old['status']=='running' and 'returncode' not in old and sha(op)==b['original_conversion_receipt']['sha256'];assert rec['request_sha256']==sha(sourceq)
assert rec['request']['case_id']==x['case_id']==b['case_id']=='F3_STAGE1_DP006_P1000_AY0270';assert rec['request']['physical_case_id']==native['request']['physical_case_id']==audit['request']['physical_case_id']==x['physical_case_id']==pid
assert native['request']['physical_condition_sha256']==audit['request']['physical_condition_sha256']==x['physical_condition_sha256']==x['canonical_source_physical_condition_sha256']==canonical
assert x['actual_converter_scope_sha256']==t['hash_scopes']['physical_condition_sha256']==actual and t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0' and x['source_plan_scope_sha256'] is None
assert x['frames']==t['frames']==a['field_audit']['frames']==836 and x['particles']==t['particles']==a['field_audit']['particles']==179208 and a['approved_temporal_kernel']['checked_transitions']==835
assert x['source_h5_sha256']==t['output_sha256']==a['producer_attestation']['verified_trajectory_sha256']==b['expected_h5_sha256'] and x['source_h5_read_only'];assert rec['input_hashes_at_launch'][h5]==rec['input_hashes_after_run'][h5]==audit['input_hashes_at_launch'][h5]==audit['input_hashes_after_run'][h5]==t['output_sha256']
assert a['field_audit']['uid_lifecycle_missing_count']==0 and a['field_audit']['uid_composite_unique'] and a['field_audit']['type_mk_verified_all_frames'] and a['field_audit']['finite_position_velocity_density_pressure_mass'] and not a['field_audit']['source_arrays_modified'];assert a['source_conversion_lifecycle']['old_os_exit_zero_claim'] is False
assert x['receipt_roles']['original_conversion_receipt']==b['original_conversion_receipt'] and x['receipt_roles']['artifact_audit_receipt']==b['artifact_audit_receipt'] and x['audit_provenance']['old_typed_receipt_is_not_reclassified'];assert sha(xml)==x['xdmf_sha256']
fs=t['lifecycle']['frame_summary'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(grids)==len(fs)==len(times)==836 and times==[f['time'] for f in fs]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=8.35 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[836,179208,3]
for i,(g,f) in enumerate(zip(grids,fs)):
 assert f['frame']==i and f['active_particles']==179208 and f['missing_particles']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500};assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='179208 3';vv=next(v for v in g.findall('Attribute') if v.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='179208 3'
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_180.json');assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
O=H/'root_stage1_F3_AY0270_actual1193_audit_qualified_full836_XMF0_original154_unknown_preserved_original116023_fullrender_1194';O.mkdir(exist_ok=False);proof=O/'actual1193-full836-N3-UID-times-audit-qualified-legacy-native-role-review.json'
put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_XMF_request':ref(sourceq),'actual_XMF_receipt':ref(xr),'actual_XMF_manifest':ref(xp),'actual_XMF_XML':ref(xml),'actual_artifact_audit_receipt':ref(ap),'actual_artifact_audit_report':ref(arp),'original_conversion_receipt':ref(op),'original_conversion_status':'running','original_returncode_field_absent':True,'old_OS_exit_zero_not_claimed':True,'actual_producer_conversion_report':ref(tp),'actual_native_receipt':ref(np),'physical_case_id':pid,'canonical_native_scope':canonical,'actual_converter_legacy_scope':actual,'absent_source_plan_alias_preserved':True,'all836_geometry_velocity_N3_exact_times_UID_present':True,'all836_original_audit_finite_typeMk_composite_UID_and835transitions':True,'H5_actual_strict_pre_post_attestation':t['output_sha256'],'main_scientific_payload_IO':False,'visual_status':'pending registered full836 render then delegated personal35contact9key review','case_credit':0})
base=load(root(984)/'enabled-full801-render-request.json');w=load(base['command'][-1]);worker=Path(base['command'][base['command'].index('--worker')+1]);renderer=Path(w['renderer']);entry=Path(base['command'][1]);assert sha(worker)=='5d577e4b28e62906472bfba30ad445685f804be4ba5d8bab44b4bab3d32e1621' and sha(renderer)=='5e78f7b92ad7c6f1d15902e3ccacc9099affb04b1b992a42f540eb88241bde66' and sha(entry)=='1c950c7456ea3b900b7ab37a6a4c4da7ea15f2e9f2691abca8d78eee347f659c';api=runpy.run_path(str(worker));aid='root-stage1-f3-ay0270-actual1193-audit-qualified-original154-unknown-full836-116023-root1194';ar=D/'families/F3'/b['case_id']/aid;assert not ar.exists();rid=f"F3/{b['case_id']}/{aid}";controller=O/'fair-render-controller.py';controller.write_bytes((root(984)/'fair-render-controller.py').read_bytes())
md={str(p):sha(p) for p in [worker,renderer,Path(w['pvpython']),entry,controller,root(928)/'fair_CPU_dispatch.py',proof,xp,xml,xr,sourceq,bp,np,tp,op,ap,arp,Path(b['adapter_source']['path']),Path(b['upstream_export_xmf']['path']),root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(64)/'resource-window-approval.json']}
w.update(family_id='F3',case_id=b['case_id'],physical_case_id=pid,manifest=str(xp),attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root='/tmp/ds02-visual-render-cache-root1194',expected_frames=836,expected_particles=179208,expected_contact_sheets=35,keyframe_indices=[0,104,208,312,417,521,626,730,835],input_files=sorted(md),input_sha256=md,physical_condition_sha256=canonical,registered_binding=str(bp),future_render_product={'attempt_root':str(ar),'report':str(ar/'render/paraview-full-animation-report.json'),'report_sha256':None},actual_converter_scope_sha256=actual,canonical_source_scope_sha256=canonical,artifact_qualification_role='actual1166 independent full836 scientific audit; original154 converter exit unknown')
api['validate_request'](w,execution=True);assert api['_manifest_metadata'](w)['manifest']==w['manifest'];wp=O/'enabled-render-wrapper.json';put(wp,w);outer={**md,str(wp):sha(wp),h5:t['output_sha256']};q=base.copy();q.update(family_id='F3',case_id=b['case_id'],physical_case_id=pid,attempt_id=aid,attempt_root=str(ar),physical_condition_sha256=canonical,actual_converter_scope_sha256=actual,source_h5_producer_sha256=t['output_sha256'],depends_on_attempts=[native['request']['attempt_id'],audit['request']['attempt_id'],rec['request']['attempt_id']],original_conversion_receipt_unknown_lifecycle_preserved=ref(op),command=[str(L/'.venv/bin/python'),str(entry),'--worker',str(worker),'--request',str(wp)],input_files=sorted(outer),input_sha256=outer,root_scope='Actual1193 full836 audit-qualified XMF with original154 unknown lifecycle preserved, explicit canonical-native vs legacy converter scope; full original116023 render only; no credit/precision before visualreview.',expected_frames=836,expected_particles=179208,expected_contact_sheets=35,full836_authorized=True,case_credit=0)
qp=O/'enabled-full836-render-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close F3 audit-qualified full836 XMF and register bound complete native render','--',*paths],cwd=R,check=True);print({'root':1194,'full836_XMF0_N3_UID_time_scope_closed':True,'full836_render_registered':True,'original154_not_reclassified':True,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
