from pathlib import Path
import json,hashlib,os,collections,datetime,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'))
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_229.json';cp=json.loads(cpfile.read_text());ip=root(1277)/'full336-current288-actual-final48-delivery-progress-index.json';idx=json.loads(ip.read_text());rows=[]
assert cp['stage1_visual_accepted_complete_independent_cases']==288
for r in idx['cases']:
 if r.get('accepted_decision'):continue
 e=r['latest_registered_render_request'];p=Path(e['path']);assert sha(p)==e['sha256'];q=json.loads(p.read_text());cmd=q['command'];w=Path(cmd[cmd.index('--request')+1]);z=json.loads(w.read_text());assert sha(w)==q['input_sha256'][str(w)]
 assert q['physical_case_id']==r['physical_case_id'];assert z['case_id']==r['case_id'] and z['home_free_floor_bytes']==500*2**30
 assert z['home_publish_cap_bytes']==q['estimated_storage_bytes'] and z['home_publish_cap_bytes']>0
 if z['home_reserved_bytes']!=z['home_publish_cap_bytes']:assert r['case_id']=='F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025' and z['home_reserved_bytes']==0
 rows.append({'family_id':r['family_id'],'case_id':r['case_id'],'physical_case_id':r['physical_case_id'],'original_registered_request':e,'actual_loaded_wrapper':ref(w),'declared_Home_publish_cap_bytes':z['home_publish_cap_bytes'],'declared_Home_reserved_bytes':z['home_reserved_bytes'],'declared_NVMe_stage_cap_bytes':z['nvme_stage_cap_bytes'],'Home_output':z['home_output'],'is_estimate_for_remaining_unaccepted_case_not_new_credit':True})
assert len(rows)==len({r['physical_case_id'] for r in rows})==48
s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize;cap=sum(r['declared_Home_publish_cap_bytes'] for r in rows);assert cap==97*2**30 and free-cap>=500*2**30
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
ledger=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(ledger);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;counts=collections.Counter(x['kind'] for x in ld['attempts']);assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
O=H/'root_stage1_remaining48_original_render_Home_caps97GiB_floor500_storage_projection_independent_audit_1279';assert not list(H.glob('root*_1279'));O.mkdir()
proof=O/'remaining48-original-render-Home-storage-projection.json';put(proof,{'schema':'ds02.pending-original-render-storage-metadata-projection.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_checkpoint':ref(cpfile),'source_actual336_progress_index':ref(ip),'actual_accepted_cases':288,'remaining_unaccepted_cases':48,'per_family_pending':dict(collections.Counter(r['family_id'] for r in rows)),'original_request_wrapper_hashes_verified_all48':True,'rows':rows,'sum_Home_publish_caps_GiB':cap/2**30,'Home_available_GiB_at_observation':free/2**30,'Home_projected_available_after_all48_max_publish_GiB':(free-cap)/2**30,'Home_floor_GiB':500,'projection_presumes_other_storage_usage_unchanged':True,'all48_includes_completed_but_unaccepted_outputs_already_using_space_so_conservative_double_reserve_possible':True,'Home_caps_are_enforced_by_existing_wrapper_not_new_cap_changes':True,'NVMe_stage_caps_have_separate_role_not_Home_projection':True,'F6_original_wrapper_Home_reserved0_is_preserved_separate_from_registered_request_estimate3GiB_and_publish_cap3GiB':True,'actual_current_disk_floor_remains_rechecked_by_each_original_admission_publication':'original unmodified guards','no_new_storage_cleanup_needed_under_this_projection':True,'all_accepted_pending_scientific_outputs_retained':True,'new_deletions':0,'new_case_credit':0,'main_scientific_payload_IO':False,'cumulative_GPU_hours_charged':gpu,'cumulative_CPU_core_hours_charged':cpu,'attempt_counts':dict(counts),'resource_window_unchanged':{'GPU_h':512,'CPU_core_h':3840,'qualification_max':1024,'production_max':720,'deadline_utc':'2026-10-14T07:23:48+00:00'},'ledger_snapshot':{'path':str(O/'ledger-immutable-snapshot.json'),'sha256':hashlib.sha256(ledger).hexdigest()}})
(O/'ledger-immutable-snapshot.json').write_bytes(ledger);(O/'audit-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify remaining48 original render Home caps97GiB preserve floor500','--',*paths],cwd=R,check=True);print({'proof':ref(proof),'remaining_publish_caps_GiB':97,'Home_projected_GiB':(free-cap)/2**30,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
