from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() in ['.json','.jsonl','.xml','.xmf','.md','.py','.png','.log','.txt'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
O=H/'root_stage1_delegated131_132_actual_F6_241_F4_1201_F5_801_metadata_QI_identity_and_visual_integration_967';O.mkdir(exist_ok=False);adopted=[];source_commits={131:'1aaa556a',132:'1c617557'}
for n,commit in source_commits.items():
 sp=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob(f'root_followup_{n}_*'));prefix=str(sp.relative_to(W));names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert names
 for name in names:
  p=Path(name);assert p.suffix in ['.json','.py','.md'];raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();dest=R/name;assert not dest.exists();dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(raw);adopted.append(ref(dest))
 pp=R/prefix
 for validator in sorted((pp/'workers').glob('validate*.py')):
  s=subprocess.run([str(L/'.venv/bin/python'),str(validator)],capture_output=True,text=True);assert s.returncode==0,(validator,s.stderr,s.stdout);put(O/(validator.stem+'-actual-result.json'),{'returncode':s.returncode,'stdout':s.stdout,'stderr':s.stderr,'validator':ref(validator),'metadata_and_PNG_only':True});print(s.stdout.strip(),flush=True)
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_128.json');assert cp['stage1_visual_accepted_complete_independent_cases']==199;previous=[load(p) for p in cp['accepted_decisions']];ids={d.get('physical_case_id',d['case_id']) for d in previous};scopes={d['physical_condition_sha256'] for d in previous};decisions=[]
# F6 already independently closed in961; now fill the exact missing physical visual evidence.
proofp=root(961)/'actual130-adoption-and-independent-metadata-closure.json';proof=load(proofp);side=L/'campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_131_f4_root951_delegated_visual_acceptance_v1/metadata/fresh130-physical-visual-sidecar.json';s=load(side);assert s['case_id']==proof['case_id'] and s['visual_evidence']['all_requested_images_viewed'] and s['physical_visual_observation']['mechanism_discerning'];assert all(v is False for k,v in s['physical_visual_observation']['gross_visual_screen'].items() if k.startswith('obvious_'));assert proof['full241_N3_QI_and_actual_times_and_PartVTK_verified'] and proof['independent_floatinginfo_state0_audit658_actual0_pass']
for k in ['full_render_receipt','full_render_report','typed_report','xmf_manifest','audit658_report']:assert sha(proof[k]['path'])==proof[k]['sha256']
d={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F6','case_id':proof['case_id'],'physical_case_id':proof['physical_case_id'],'physical_condition_sha256':proof['physical_condition_sha256'],'full_native_frames':241,'independent_metadata_closure':ref(proofp),'physical_visual_sidecar':ref(side),'source_review_commit':'1aaa556a','scope_separation':proof['scope_separation'],'lifecycle':proof['lifecycle'],'main_science_payload_IO':False,'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'stage1_QI_full_native_identity_and_state_verified':True,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1,'acceptance_scope':'Stage1 qualitative physical visual acceptance; exact initial angular state from audit658, minor four final missing UIDs disclosed without cause assignment'}
assert d['physical_case_id'] not in ids and d['physical_condition_sha256'] not in scopes;ids.add(d['physical_case_id']);scopes.add(d['physical_condition_sha256']);p=O/(d['physical_case_id']+'-delegated-visual-decision.json');put(p,d);decisions.append(str(p))
for n,N,T,particles in [(131,1201,1.2,83233),(132,801,16.0,194427)]:
 pp=next((L/'campaigns/ds-data-02/families/F6/handoff_20261003').glob(f'root_followup_{n}_*'));c=load(pp/'metadata/chain-closure.json');v=load(pp/'metadata/visual-review.json');assert c['status']==v['status']=='visual-approved-by-delegated-agent';assert v['agent_personally_viewed_all_contact_sheets'] and v['agent_personally_viewed_all_key_frames'];assert all(x is False for k,x in v['gross_visual_screen'].items() if k.startswith('obvious_'))
 def verifyrefs(obj):
  if isinstance(obj,dict):
   if isinstance(obj.get('path'),str) and obj.get('sha256'):
    assert sha(obj['path'])==obj['sha256']
    if Path(obj['path']).name=='execution-receipt.json':
     rr=load(obj['path']);assert rr['status']=='completed' and rr['returncode']==0
   for x in obj.values():verifyrefs(x)
  elif isinstance(obj,list):
   for x in obj:verifyrefs(x)
 verifyrefs(c['producer_chain'])
 chain=c['producer_chain'];t=load(chain['typed']['report']['path']);r=load(chain['render']['report']['path']);x=load(chain['xmf']['manifest']['path']);xf=ET.parse(x['xdmf']);grids=xf.findall('.//Grid[@GridType="Uniform"]');assert len(grids)==N
 assert t['frames']==r['frames']==r['source_frames']==x['frames']==N and t['particles']==x['particles']==particles;assert t['solver_dimension']['solver_dimension']==x['expected_dimension']==3 and t['partvtk_validation']['all_passed'];assert all(z['passed'] and z['identity_type_mk_exact'] for z in t['partvtk_validation']['frames']);assert t['lifecycle']['introduced_ids']=='rejected'
 fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];assert len(fs)==len(ds)==N and [f['frame'] for f in fs]==list(range(N)) and [f['frame'] for f in ds]==list(range(N));assert r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0;assert r['source_h5_sha256']==t['output_sha256']==x['source_h5_sha256'];times=x['actual_time_s'];assert times==[f['time'] for f in fs]==[f['actual_time_s'] for f in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=T and all(a<b for a,b in zip(times,times[1:]))
 for f,z,g in zip(fs,ds,grids):
  assert f['missing_particles']==z['missing']==0 and f['active_particles']==z['active']==particles and z['identity_axis_preserved'] and z['finite_positions_active'];assert all(a['finite_active'] and a['nonfinite_active']==0 for a in z['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ';assert g.find('Geometry/DataItem').get('Dimensions')==f'{particles} 3';vv=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')==f'{particles} 3'
 sc=c['scope_separation'].copy();actual=t['hash_scopes']['physical_condition_sha256']
 if n==131:
  canonical=x['physical_condition_sha256'];assert canonical==actual==sc['actual_converter_scope_sha256'];initial=t['hash_scopes']['physical_condition']['initial_state']['velocities_m_per_s'];assert initial=={'mkfluid:0':[0.0,0.0,0.0],'mkfluid:1':[0.0,0.0,-0.6]};sc.update(source_plan_confirmed_from_actual_XMF=x['source_plan_condition_sha256'])
 else:
  canonical=x['physical_condition_sha256'];assert canonical=='0521b11e6a5eab05ca3c8e41058cc55971f6c1dd599650b6947daaaa77837965' and actual==x['source_h5_physical_condition_sha256']==sc['actual_converter_report_scope_sha256'];params=t['hash_scopes']['physical_condition']['parameters']['piston_motion'];assert params['amplitude_scale']==0.85 and params['time_scale']==1.0 and params['duration_s']==16.0
  sc.update(actual_producer_H5_legacy_scope=actual,actual_source_plan_definition_scope=x['source_plan_physical_condition_sha256'],legacy_h5_scope_in_delegated_package_is_prior_forecast_not_actual_H5_scope=True,definition_as_source_plan_role_confirmed_in_actual953_binding=True)
  bedp=root(959)/'actual956-all801-bed-independent-review.json';bed=load(bedp);assert bed['physical_condition_sha256']==canonical;sc['actual_full801_bed_independent_review']=ref(bedp)
 assert c['physical_case_id'] not in ids and canonical not in scopes;ids.add(c['physical_case_id']);scopes.add(canonical)
 d={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':v['status'],'family_id':c['family_id'],'case_id':c['case_id'],'physical_case_id':c['physical_case_id'],'physical_condition_sha256':canonical,'source_review_commit':source_commits[n],'source_review_closure':ref(pp/'metadata/chain-closure.json'),'source_visual_review':ref(pp/'metadata/visual-review.json'),'scope_separation':sc,'agent_observations':v['observations'],'gross_visual_screen':v['gross_visual_screen'],'agent_limitations':v['limitations'],'actual_completed_metadata_evidence':chain,'full_native_frames':N,'particles':particles,'all_actual_times_exact_with_typed_XMF_XML_and_render':True,'actual_physical_window_s':[times[0],times[-1]],'all_geometry_and_velocity_shapes_N3':True,'all_active_states_finite':True,'all_frames_missing_particles_zero':True,'stage1_QI_full_native_identity_and_state_verified':True,'main_science_payload_IO':False,'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};p=O/(d['physical_case_id']+'-delegated-visual-decision.json');put(p,d);decisions.append(str(p));print({'accepted_family':d['family_id'],'frames':N,'case':d['physical_case_id']},flush=True)
put(O/'adoption-and-independent-review.json',{'source_byte_exact_adoptions':adopted,'prior_accepted':199,'new_decisions':decisions,'accepted_after':202,'main_science_payload_IO':False,'main_PNG_personal_review':False,'precision_not_accepted':True});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());cp.update(checkpoint=129,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_128.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_128.json'),stage1_visual_accepted_complete_independent_cases=202,new_accepted_decisions=decisions,accepted_decisions=cp['accepted_decisions']+decisions,previous_goal_turn_classification='Progress: registered failed unused cleanup independently closed; fullvisual F6/F4/F5 exact-chain evidence now integrated to202')
for fam in ['F6','F4','F5']:cp['accepted_per_family'][fam]+=1
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==202;lp=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02/runtime/resource-ledger.json');raw=lp.read_bytes();ledger=json.loads(raw);cp.update(home_free_gib=shutil.disk_usage('/home/jade').free/1024**3,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(z.get('gpu_seconds',0) for z in ledger['charges'])/3600,cpu_core_hours_charged=sum(z.get('cpu_core_seconds',0) for z in ledger['charges'])/3600);cp['actual_progress']={'three_fullvisual_independent_integrations':ref(O/'adoption-and-independent-review.json'),'failed_unused_cleanup_closure':ref(root(966)/'actual-cleanup-independent-review.json'),'main_science_payload_IO':False,'main_PNG_personal_review':False,'F3_native_queue':ref(root(948)/'actual-progress.json'),'render951_queue':ref(root(951)/'actual-progress.json')};cp['next_executable_tasks']=['Integrate delegated133 actual951 F2 full401 visual after metadata/QI and unique physical-scope check.', 'Adopt121 F3 true836 native0 typed157 hard4GiB owner closure, register real stock conversion under current shared budget.', 'Adopt163 M086 actual963 XMF0 downstream corrected161 original bed recipe and register CPU2 actual audit before full801 render.', 'Adopt160 actual939 M095 XMF terminal-bound metadata and register next full801 stage; no duplicate M085 XMF/render.', 'Continue existing live948 native and951 fullrender queues; protect Home500GiB and unchanged cumulative budget/deadline.'];put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_129.json',cp)
paths=[str(Path(z['path']).relative_to(R)) for z in adopted]+[str(p.relative_to(R)) for p in O.iterdir()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_129.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept fullvisual F6 F4 F5 cases with independent identity and event-window closure','--',*paths],cwd=R,check=True);print({'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'accepted':202,'counts':cp['accepted_per_family']})
