from pathlib import Path
import json,hashlib,subprocess,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_164_m095_actual968_bed_binding_disabled_v1';commit='8a660812';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==8;adopted=[]
for name in names:
 assert Path(name).suffix in {'.json','.py','.md'};raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists();p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;bp=P/'bindings/M095_T080-actual968-bed-binding.json';b=load(bp);q=load(P/'requests/M095_T080-actual968-bed-request.json');worker=Path(q['command'][1]);assert sha(worker)=='89be048da1df6bae49627308edb35a8a1936bc0888259cb5ab3d195307b550e2';assert b['disabled'] and b['source_only'] and not b['execution_allowed'] and not b['full801_authorized'];assert b['case_id']==b['producer_case_id']=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1';assert b['worker_identity_adapter_required'] is False
for k in ['xmf_manifest','xdmf','xmf_receipt']:assert sha(b[k])==b[k+'_sha256']
rc=load(b['xmf_receipt']);assert (rc['status'],rc['returncode'])==('completed',0);x=load(b['xmf_manifest']);t=load(b['full_typed_conversion_report']);assert x['frames']==t['frames']==801 and x['particles']==t['particles']==194427 and x['source_h5_sha256']==b['trajectory_h5_sha256']==t['output_sha256'];assert x['case_id']==b['case_id'] and x['root_actual_XMF_attempt_id']==b['xmf_attempt_id']==rc['request']['attempt_id'];assert x['physical_condition_sha256']==b['physical_condition_sha256'] and x['source_h5_physical_condition_sha256']==b['source_h5_physical_condition_sha256'];grids=ET.parse(b['xdmf']).findall('.//Grid[@GridType="Uniform"]');fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];assert len(grids)==len(fs)==801 and times==[f['time'] for f in fs]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=16 and all(u<v for u,v in zip(times,times[1:]));assert t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed']
for i,(g,f) in enumerate(zip(grids,fs)):
 assert f['frame']==i and f['active_particles']==194427 and f['missing_particles']==0;assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';v=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='194427 3'
O=H/'root_stage1_F5_M095_actual968_XMF0_original138_full801_bed_fairCPU2_971';O.mkdir(exist_ok=False);gate=O/'actual-original138-metadata-gate.py';gate.write_text("from pathlib import Path\nimport sys,json,runpy\nm=runpy.run_path(sys.argv[1])\nb=json.loads(Path(sys.argv[2]).read_text())\nr=m['_verify_bound_metadata'](b)\nPath(sys.argv[3]).write_text(json.dumps(r,indent=2)+'\\n')\nprint(json.dumps({'actual_original138_metadata_gate':'pass','case_id':r['case_id'],'native_saved_states':r['full_native_solver']['saved_state_count'],'scientific_payload_IO':False}))\n");result=subprocess.run([str(L/'.venv/bin/python'),str(gate),str(worker),str(bp),str(O/'actual-original138-to-real968-XMF-metadata-proof.json')],capture_output=True,text=True);put(O/'actual-metadata-preflight-result.json',{'returncode':result.returncode,'stdout':result.stdout,'stderr':result.stderr,'main_science_payload_IO':False,'real801_filenames_not_temporary_stubs':True});assert result.returncode==0,(result.stdout,result.stderr)
controller=O/'fair-bed-controller.py';controller.write_bytes((root(963)/'fair-XMF-controller.py').read_bytes());fair=root(928)/'fair_CPU_dispatch.py';aid='root-stage1-f5-m095-t080-actual968-full801-original138-bed-root971';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();md=q['input_sha256'].copy()
for p,digest in md.items():assert Path(p).is_absolute() and sha(p)==digest
for p in [bp,controller,fair,O/'actual-metadata-preflight-result.json',O/'actual-original138-to-real968-XMF-metadata-proof.json']:md[str(p)]=sha(p)
md[b['trajectory_h5']]=t['output_sha256'];base=load(root(963)/'enabled-XMF-request.json');q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','science_input_policy']});q.update(attempt_id=aid,attempt_root=str(ar),binding=str(bp),binding_sha256=sha(bp),command=[str(L/'.venv/bin/python'),str(worker),'--binding',str(bp),'--trajectory-h5',b['trajectory_h5'],'--xdmf',b['xdmf'],'--output-dir','{attempt_root}/audit-output'],input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,full801_authorized=True,case_credit=0);qp=O/'enabled-bed-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(fair),'case_credit':0});put(O/'source164-adoption-and-primary-review.json',{'source_commit':subprocess.check_output(['git','rev-parse',commit],cwd=W,text=True).strip(),'adopted_files':adopted,'source_byte_exact':True,'actual_original138_gate_with_real801_filenames_passed':True,'actual968_all801_XML_N3_geometry_velocity_times_and_identity_verified':True,'actual_end_s':times[-1],'binding_execution_flags_unchanged':True,'outer_registered_runner_authorizes801':True,'actual_converted_source_H5_SHA_report_attested_only':True,'main_scientific_payload_IO':False,'no_precision_claim':True,'future_bed_and_render_hashes_null':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(p['path']).relative_to(R)) for p in adopted]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register actual M095 full801 original bed audit with real native metadata gate','--',*paths],cwd=R,check=True);print({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'actual_metadata_gate':result.stdout.strip()})
