from pathlib import Path
import json,hashlib,datetime,shutil,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_all_legacy_conversion_capacity_waiters_metadata_only_safe_handoff_inventory_935';O.mkdir(exist_ok=False);load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();root=lambda n:next(H.glob(f'root*_{n:03d}'));ledger=load(D/'runtime/resource-ledger.json');numbers=[854,864,872,879,885,891,865,873,877,892];rows=[]
for n in numbers:
 p=root(n);c=load(p/'controller-launch-process.json');pr=Path('/proc')/str(c['pid']);f=(pr/'stat').read_text().split(') ',1)[1].split() if pr.exists() else [];live=bool(f and f[0]!='Z' and f[19]==c['proc_start_ticks']);assert sha(c['controller'])==c['controller_sha256'];assert not live or c['controller'].encode() in (pr/'cmdline').read_bytes();children=sorted({int(x) for t in (pr/'task').iterdir() for x in (t/'children').read_text().split()}) if live else [];reqs=[];ownids=set()
 for qp in sorted(list(p.glob('*request.json'))+list((p/'requests').glob('*request.json'))):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};identity='/'.join([q['family_id'],q['case_id'],q['attempt_id']]);ownids.add(identity);reqs.append({'request':str(qp),'request_sha256':sha(qp),'case_id':q['case_id'],'physical_case_id':q.get('physical_case_id'),'reservation_id':identity,'attempt_root':q['attempt_root'],'receipt':str(rp),'receipt_sha256':sha(rp) if rp.exists() else None,'actual_status':r.get('status','unlaunched'),'actual_returncode':r.get('returncode'),'actual_worker_pid':r.get('pid'),'old_estimated_storage_GiB':q.get('estimated_storage_bytes',0)/1024**3})
 ownres=[r for r in ledger['reservations'] if r.get('id') in ownids];active=[r for r in reqs if r['actual_status'] in ['running','reserved','starting']];complete=[r for r in reqs if (r['actual_status'],r['actual_returncode'])==('completed',0)];neg=[r for r in reqs if r['actual_status'] not in ['unlaunched','completed']];can=live and not children and not ownres and not active and not neg;rows.append({'root':n,'launch':{'path':str(p/'controller-launch-process.json'),'sha256':sha(p/'controller-launch-process.json')},'pid':c['pid'],'ticks':c['proc_start_ticks'],'controller_sha256':c['controller_sha256'],'live_same_handle':live,'state':f[0] if f else None,'all_task_children':children,'own_live_reservations':ownres,'actual_completed0_requests_to_preserve':len(complete),'own_actual_running_requests':len(active),'negative_receipts_retained':neg,'requests':reqs,'eligible_for_frozen_metadata_only_retirement_at_this_snapshot':can,'requires_fresh_same_handle_freeze_and_own_revalidation_before_any_retirement':True})
lock=D/'runtime/stage1-fullnative-conversion-dispatch.lock';inode=lock.stat().st_ino;locks=[line for line in Path('/proc/locks').read_text().splitlines() if f':{inode} ' in line];proof={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'controllers':rows,'conversion_lock':{'path':str(lock),'inode':inode,'actual_proc_lock_rows':locks},'Home_free_GiB':shutil.disk_usage('/home/jade').free/1024**3,'global_reservations_preserved':ledger['reservations'],'global_ledger_empty_not_required_for_own_metadata_retirement':True,'retirement_not_executed_by_this_audit':True,'science_terminated_restarted_or_payload_IO':False,'handoff_protocol':'Retire only freshly proven own metadata processes; freeze all unsafe-capacity lock waiters before releasing original854 holder so another old32GiB waiter cannot immediately occupy global conversion lock. Preserve every completed native/typed/XMF/bed request/receipt/source byte. New producer requests require corrected157 hard4GiB publish protocol and distinct attempt-root, then fair928 serial dispatcher. New downstream must bind actual new typedreceipt/H5/report, never old future files.','case_credit':0};(O/'actual-own-handle-conversion-waiters-audit.json').write_text(json.dumps(proof,indent=2)+'\n');(O/'audit-source.py').write_bytes(Path(__file__).read_bytes());print({'audited':len(rows),'metadata_eligible_at_snapshot':[r['root'] for r in rows if r['eligible_for_frozen_metadata_only_retirement_at_this_snapshot']],'completed0_preserve':{r['root']:r['actual_completed0_requests_to_preserve'] for r in rows},'conversion_lock_rows':locks,'science_touched':False})
