from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,re,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.png','.log','.txt'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_137_f3_p0800_ay0430_delegated_visual_review_v1';commit='b6615477e64361577f0b5b05a176b57c8c429682';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==10;adopted=[]
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_source137_F3_P0800AY0430_actual1025_full836_independent_visual_acceptance_1113';O.mkdir(exist_ok=True);assert not list(O.glob("*-delegated-visual-decision.json"));assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_169.json').exists()
vld=P/'scripts/validate_fresh137.py';rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],capture_output=True,text=True);put(O/'actual-original-source137-validator.json',{'validator':ref(vld),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr});assert rv.returncode==0
for item in load(P/'metadata/package-integrity.json')['files']:
 p=P/item['path'];assert p.stat().st_size==item['bytes'] and sha(p)==item['sha256']
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_168.json');old=[load(p) for p in cp['accepted_decisions']];assert len(old)==sum(cp['accepted_per_family'].values())==258;ids={a.get('physical_case_id',a['case_id']) for a in old};cids={a['case_id'] for a in old};scopes={a['physical_condition_sha256'] for a in old};decisions=[];proofs=[]
for zp in sorted((P/'metadata/chain-audit').glob('*.json')):
 z=load(zp);cid=z['case_id'];vp=P/'metadata/visual-review'/(cid+'-delegated-visual-decision.json');v=load(vp);pngp=P/'metadata/png-hashes'/(cid+'.json');png=load(pngp);assert v['status']=='visual-approved-by-delegated-agent' and v['agent_personally_viewed_all_contacts_and_keys'] and not v['main_personally_viewed_pngs'] and cid not in cids
 assert v['source_review']['sha256']==sha(zp) and sha(v['source_review']['path'])==sha(zp)
 s={role:({**item['receipt'],**{k:val for k,val in item.items() if k!='receipt'}} if 'receipt' in item else item.copy()) for role,item in z['stages'].items()};receipts={}
 for role,p in s.items():
  assert sha(p['path'])==p['sha256'];a=load(p['path']);assert (a['status'],a['returncode'])==('completed',0) and a['request']['case_id']==cid;receipts[role]=a
  if 'report' in p:assert sha(p['report']['path'])==p['report']['sha256']
 t=load(s['typed']['report']['path']);r=load(s['render']['report']['path']);xp=Path(s['xmf']['manifest']['path']);assert sha(xp)==s['xmf']['manifest']['sha256'];x=load(xp);xml=Path(x['xdmf']);assert sha(xml)==x['xdmf_sha256']==r['xdmf_sha256_before']==r['xdmf_sha256_after']
 assert t['frames']==x['frames']==r['frames']==r['source_frames']==836 and t['particles']==x['particles']==179208 and t['solver_dimension']['solver_dimension']==x['dimension']==3
 assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(a['passed'] and a['identity_type_mk_exact'] for a in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
 assert r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0 and not r['diagnostic_only'] and r['source_h5_read_only'];assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256'] and r['manifest_sha256']==sha(xp);h5=t['output_hdf5'];assert Path(h5).is_file()
 legacy_receipt_notes=[]
 for role in ['xmf','render']:
  a=receipts[role]
  if h5 in a['input_hashes_at_launch']:assert a['input_hashes_at_launch'][h5]==a['input_hashes_after_run'][h5]==t['output_sha256']
  else:
   assert role=='xmf';cmd=a['request']['command'];bp=Path(cmd[cmd.index('--binding')+1]);b=load(bp);assert a['input_hashes_at_launch'][str(bp)]==a['input_hashes_after_run'][str(bp)]==sha(bp);assert b['trajectory_h5']==h5 and b['trajectory_h5_sha256']==t['output_sha256'];legacy_receipt_notes.append({'actual_binding':ref(bp),'older_runner_H5_direct_input_hash_absent_preserved':True,'current_actual_renderer_H5_before_after_matches_typed_producer':True})
 for key in ['solver_receipt','gencase_receipt','generated_xml','owner_metadata']:
  p=t['source_provenance'][key];assert sha(p['path'])==p['sha256']
 assert t['source_provenance']['solver_receipt']==ref(s['native']['path']);op=t['source_provenance']['owner_metadata']['path'];o=load(op);nq=receipts['native']['request'];canonical=nq['physical_condition_sha256'];actual=t['hash_scopes']['physical_condition_sha256'];schema=t['hash_scopes']['physical_condition']['schema'];pid=nq['physical_case_id'];assert pid==v['physical_case_id']==x['physical_case_id']==o['physical_case_id']==t['hash_scopes']['physical_condition']['physical_case_id'];assert v['physical_condition_sha256'] in [canonical,actual];assert actual==x['physical_condition_sha256'];assert pid not in ids and canonical not in scopes
 if schema=='legacy-owner-scope.v0':
  assert o['source_canonical_physical_binding']['physical_condition_sha256']==canonical and o['source_canonical_physical_binding']['physical_case_id']==pid and o['source_physical_condition_sha256']==canonical
  assert o['actual_converter_physical_condition_scope']==t['hash_scopes']['physical_condition']==x['actual_converter_physical_condition_scope'];assert x['owner_metadata']==t['source_provenance']['owner_metadata'];assert x['source_canonical_physical_binding'] is None
  assert o['source_plan_binding']['source_plan_condition_sha256']==x['source_plan_condition_sha256']==canonical
  prepared=nq['prepared_input'];assert nq['qa_semantics']=='exact_initial_clone_of_genuine_3d_parent' and prepared['xml_byte_identical_to_baseline'] and prepared['initial_bi4_byte_identical_to_baseline'];assert sha(prepared['report']['path'])==prepared['report']['sha256'];qa_ref=o['parent_initial_qa'];qp=Path(qa_ref['path'])
  inputs={k:prepared[k] for k in ['forcing','generated_xml','initial_bi4']};prep_proof=ref(prepared['report']['path']);scopeproof={'schema':schema,'native_canonical':canonical,'actual_legacy_converter':actual,'separate_manifest_aliases_absent_preserved':True,'owner_source_canonical_binding':o['source_canonical_physical_binding'],'source_plan_role':x['source_plan_condition_sha256']}
 else:
  assert schema=='ds-data-02.physical-binding.v1' and actual==canonical==x['source_physical_condition_sha256']==o['physical_condition_sha256'];assert o['physical_binding']==nq['physical_binding']==t['hash_scopes']['physical_condition']
  prep_path=o['root704_preparation_provenance']['original_report_path'];assert sha(prep_path)==o['root704_preparation_provenance']['original_report_sha256'];prepared=load(prep_path);assert prepared['xml_byte_identical_to_baseline'] and prepared['initial_bi4_byte_identical_to_baseline'];assert prepared['physical_condition_sha256']==canonical and prepared['forcing_transform']['status']=='success';assert prepared['forcing_transform']['source_sha256_before']==prepared['forcing_transform']['source_sha256_after']
  pp=nq['actual_preparation_receipt'];assert sha(pp['path'])==pp['sha256'];pr=load(pp['path']);assert (pr['status'],pr['returncode'])==('completed',0)
  inputs=o['producer_attested_inputs'];qa_ref=nq['genuine_parent_initial_QA'];qp=Path(qa_ref['path']);prep_proof=ref(prep_path);scopeproof={'schema':schema,'native_and_actual_converter_same_scope_verified':actual,'source_owner_scope_unchanged':ref(op),'no_legacy_hash_asserted':True,'actual_preparation_receipt':pp}
 assert sha(qp)==qa_ref['sha256'];qa=load(qp);qar=qp.parent/'execution-receipt.json';qr=load(qar);assert (qr['status'],qr['returncode'])==('completed',0);qa0=next(a for a in qa['cases'] if a['role']=='twoaxis_dp006');assert qa0['passed'] and qa0['actual_3d'] and qa0['native_particles']==179208 and qa0['native_fixed']==111708 and qa0['native_fluid']==67500
 for key in ['forcing','generated_xml','initial_bi4']:
  item=inputs[key];assert receipts['native']['input_hashes_at_launch'][item['path']]==receipts['native']['input_hashes_after_run'][item['path']]==item['sha256']
 assert qa0['generated_xml_sha256']==inputs['generated_xml']['sha256']==sha(inputs['generated_xml']['path']) and qa0['native_initial_BI4_sha256']==inputs['initial_bi4']['sha256'];assert nq['nominal_pitch_multiplier']==int(cid.split('_P')[1].split('_')[0])/1000 and nq['transverse_amplitude_m_s2']==int(cid.split('_AY')[1])/1000
 data=Path(t['source_provenance']['data_root']);frames=sorted(p.name for p in data.glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name));assert len(frames)==836 and frames[0]=='Part_0000.bi4' and frames[-1]=='Part_0835.bi4'
 fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==836;assert times==[f['time'] for f in fs]==[d['actual_time_s'] for d in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=8.35 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[836,179208,3]
 for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
  assert f['frame']==d['frame']==i and f['active_particles']==d['active']==179208 and f['missing_particles']==d['missing']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='179208 3';vv=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='179208 3'
 assert len(png['contact_sheets'])==35 and len(png['keyframes'])==(9 if schema=='ds-data-02.physical-binding.v1' else 6);assert [a['path'] for a in png['contact_sheets']]==r['outputs']['contact_sheets']
 for item in png['contact_sheets']+png['keyframes']:assert sha(item['path'])==item['sha256']
 ch={k:{**v} for k,v in s.items()};ch['chain_audit']=ref(zp);ch['png_sidecar']=ref(pngp);decision={**v,'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_source_reviewed_at_utc_unvalidated':v.get('reviewed_at_utc'),'review_timestamp_note':'Source fixed review timestamp is preserved but not treated as measured clock evidence; independent integration at_utc is actual current UTC.','source_review_commit':commit,'original_source_marker_preserved':v['source_review_commit'],'source_review':ref(zp),'source_visual_decision':ref(vp),'actual_completed_metadata_evidence':ch,'physical_condition_sha256':canonical,'original_source_visual_scope_sha256':v['physical_condition_sha256'],'canonical_scope_sha256':canonical,'actual_converter_scope_sha256':actual,'producer_scope_schema':schema,'actual_scope_schema_closure':scopeproof,'physical_case_aliases':[cid,pid],'full_native_frames':836,'particles':179208,'actual_physical_window_s':[times[0],times[-1]],'all836_geometry_velocity_N3_times_UIDs_finite_verified':True,'stage1_QI_full_native_identity_and_state_verified':True,'initial_clone_QA':{'receipt':ref(qar),'report':ref(qp),'preparation_report':prep_proof,'changed_forcing_and_initial_inputs_actual_native_before_after_digest_verified':True},'older_XMF_receipt_schema_notes':legacy_receipt_notes,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'precision_status':'视觉检查通过、数值精度未验收','q_n_granted':False,'q_e_granted':False,'independent_case_increment':1};dp=O/(cid+'-delegated-visual-decision.json');decisions.append((dp,decision));proofs.append({'case_id':cid,'physical_case_id':pid,'scope_schema':schema,'scope_closure':scopeproof,'frames':836,'all_UIDs_active':True,'contacts_personally_viewed':35,'keys_personally_viewed':len(png['keyframes'])});ids.add(pid);cids.add(cid);scopes.add(canonical)
assert len(decisions)==1
for dp,decision in decisions:put(dp,decision)
dps=[str(dp) for dp,_ in decisions];put(O/'source137-one-full836-independent-QI-and-visual-adoption.json',{'source_commit':commit,'adopted_files':adopted,'validator':ref(O/'actual-original-source137-validator.json'),'cases':proofs,'previous_accepted':258,'new_accepted':259,'main_scientific_payload_IO':False})
cp['accepted_per_family']['F3']+=1;cp.update(checkpoint=169,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_168.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_168.json'),stage1_visual_accepted_complete_independent_cases=259,new_accepted_decisions=dps,accepted_decisions=cp['accepted_decisions']+dps,previous_goal_turn_classification='Progress: actual1025 F3P0800AY0430 full836 personal35contacts9keys independently closed; accepted259/F3=33 with ownv1scope andactualcloneQA/forcing digests. Previous checkpointregistered19owncase downstream products underunchangedcaps, guardedHome500, cleanup515GiB preserved.')
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==259
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);a=json.loads(raw);cp.update(home_free_gib=shutil.disk_usage('/home/jade').free/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),active_reservations=a['reservations'],attempt_counts={k:sum(z['kind']==k for z in a['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(z.get('gpu_seconds',0) for z in a['charges'])/3600,cpu_core_hours_charged=sum(z.get('cpu_core_seconds',0) for z in a['charges'])/3600)
cp['actual_progress']['source137_one_F3_independently_accepted']=ref(O/'source137-one-full836-independent-QI-and-visual-adoption.json');cp['ledger_immutable_snapshot']=ref(O/'resource-ledger-frozen.json')
cp['source_agents']['production_recovery']='fresh137 accepted259/F3=33; next only genuinely completed unaccepted full836 renders'
cp['source_agents']['f5_bed_recovery']='fresh178 acceptedM095T080; fresh179 disabled own-case bed5/render1 metadata active'
cp['source_agents']['f6_endpoint_initial_qa']='fresh151 bounded failed unpublished storage audit active; lastF6Root951 stillpendingactualterminal'
cp['next_executable_tasks']=[s for s in cp['next_executable_tasks'] if 'fresh137' not in s and 'fresh178' not in s]+['Integrate fresh179 disabled owncase bed5/render1, enableonlyactualupstream0 originalsCPU2serial/CPU24shared2. LastF6needsactualRoot951terminal andpersonalvisual; nextF3reviewonlygenuinecompletedunaccepted836. Preservecleanup515GiB and500GiBHomefloor.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_169.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(x['path']).relative_to(R)) for x in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_169.json').relative_to(R))]+[str((next(H.glob(f'root*_{n}'))/'controller-launch-process.json').relative_to(R)) for n in []]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept two F3 full836 visuals with canonical and converter scope proof','--',*paths],cwd=R,check=True);print({'accepted':259,'counts':cp['accepted_per_family'],'home_free_GiB':cp['home_free_gib'],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
