from pathlib import Path
import json,hashlib,datetime,subprocess,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.log','.xml','.xmf'}
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_243_visual_cumulative515GiB_failed_cleanup_two_F5bed_six_F5typed_two_F3render_four_F2XMF_live_checkpoint_1056';assert not O.exists() and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_159.json').exists();O.mkdir()
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_158.json');accepted=[load(p) for p in cp['accepted_decisions']];assert len(accepted)==sum(cp['accepted_per_family'].values())==243
assert len({v.get('physical_case_id',v['case_id']) for v in accepted})==243 and all(not v.get('q_n_granted',False) and not v.get('q_e_granted',False) for v in accepted)
cleanupq=load(root(1054)/'enabled-cleanup-request.json');ar=Path(cleanupq['attempt_root']);rp=ar/'execution-receipt.json';r=load(rp);resultp=ar/'cleanup/cleanup-result.json';result=load(resultp);journalp=ar/'cleanup/deleted-files.jsonl';journal=[json.loads(s) for s in journalp.read_text().splitlines()];plan=load(root(1053)/'partial-cleanup-plan.json')
assert (r['status'],r['returncode'])==('completed',0) and result['status']=='completed' and result['deleted_files']==len(journal)==2
assert result['deleted_allocated_bytes']==plan['planned_allocated_bytes']==82105556992
assert not result['science_payload_contents_read_or_hashed'] and not result['completed_outputs_and_native_raw_deleted']
for v in plan['eligible_files']:
 assert not Path(v['path']).exists() and sha(v['receipt']['path'])==v['receipt']['sha256']
 marker=Path(v['attempt_root'])/'user-authorized-failed-unpublished-partial-cleanup-root1054.json';assert load(marker)['status']=='completed'
 assert r['input_hashes_at_launch'][v['receipt']['path']]==r['input_hashes_after_run'][v['receipt']['path']]==v['receipt']['sha256']
old=load(root(966)/'actual-cleanup-independent-review.json')
for k in ['actual_registered_cleanup_receipt','actual_cleanup_result','deletion_journal','manifest']:assert sha(old[k]['path'])==old[k]['sha256']
oldjournal=[json.loads(s) for s in Path(old['deletion_journal']['path']).read_text().splitlines()];assert len(oldjournal)==15995 and all(not Path(v['path']).exists() for v in oldjournal)
cleanup_review=O/'actual1054-two-failed-partial-cleanup-independent-review.json';put(cleanup_review,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_registered_cleanup_receipt':ref(rp),'actual_result':ref(resultp),'deletion_journal':ref(journalp),'exact_file_plan':ref(root(1053)/'partial-cleanup-plan.json'),'deleted_files_absent':2,'original_failed_receipts_and_logs_preserved':True,'additional_allocated_GiB_freed':result['deleted_allocated_bytes']/2**30,'old965_cleanup_review':ref(root(966)/'actual-cleanup-independent-review.json'),'old15995_deleted_native_files_still_absent':True,'cumulative_deleted_files':15997,'cumulative_freed_allocated_GiB':(old['deleted_allocated_bytes']+result['deleted_allocated_bytes'])/2**30,'valid_native_H5_XMF_render_accepted_pending_live_outputs_preserved':True,'source147_directory_reference_conservative_snapshot_refined_by_actual_exact_temporary_file_closure':ref(root(1053)/'adoption-and-file-level-independent-storage-review.json'),'completed_F3_half_save_H5_preserved_despite_failed_parent_runner':True,'main_and_worker_scientific_payload_contents_IO':False,'case_credit':0})
roles=[]
for qp in load(root(1055)/'controller-config.json')['requests']:
 q=load(qp);b=load(q['binding']);roles.append({'case_id':q['case_id'],'actual_registered_bed_request':ref(qp),'actual_source174_bed_binding_consumed_by_worker_argument':ref(q['binding']),'inherited_binding_field_in_source174_metadata_kept_as_historical_typed165_provenance':ref(b['binding']),'main1055_review_field_source_binding_kept_disabled_points_to_inherited_typed165_field':True,'actual_bed_binding_path_resolved_from_registered_command_and_request_binding':True,'no_source_binding_or_enabled_request_changed':True})
rolep=root(1055)/'actual-source174-bed-binding-versus-inherited-source165-typed-binding-role-sidecar.json';assert not rolep.exists();put(rolep,{'schema':'ds02.source174.inherited-binding-field-role-closure.v1','cases':roles,'main_scientific_payload_IO':False,'only_outer_registered_request_is_execution_authorization':True,'original_source_reports_and_both_metadata_roles_preserved':True})
observations=[];ns=[951,983,984,987,988,991,1003,1006,1008,1009,1010,1013,1014,1015,1016,1020,1025,1026,1028,1031,1032,1033,1034,1035,1036,1037,1038,1045,1046,1047,1048,1049,1050,1051,1054,1055]
for n in ns:
 o=root(n);entry={'root':n,'live':False,'case_credit':0}
 for p in o.glob('*launch*.json'):
  v=load(p)
  if not isinstance(v,dict) or not v.get('pid'):continue
  try:s=Path(f"/proc/{v['pid']}/stat").read_text().split(') ',1)[1].split()
  except FileNotFoundError:continue
  if s[0]!='Z' and s[19]==str(v.get('proc_start_ticks',v.get('start_ticks'))):entry.update(live=True,pid=v['pid'],start_ticks=s[19],actual_launch_receipt=ref(p))
 for name in ['actual-progress.json','controller-result.json']:
  p=o/name
  if p.exists():
   fp=O/f'root{n}-{name}-frozen.json';fp.write_bytes(p.read_bytes());entry[name]=ref(fp)
 cfgp=o/'controller-config.json'
 if cfgp.exists():
  cfg=load(cfgp);rr=[];pending=[]
  for qp in cfg.get('outer_requests',cfg.get('requests',[cfg['request']] if cfg.get('request') else [])):
   q=load(qp);p=Path(q['attempt_root'])/'execution-receipt.json';row={'case_id':q['case_id'],'physical_case_id':q.get('physical_case_id'),'request':ref(qp),'actual_receipt_path':str(p),'case_credit':0}
   if p.exists():
    v=load(p);row.update(status=v['status'],returncode=v.get('returncode'),actual_receipt=ref(p));rr.append(row)
   else:pending.append(row)
  entry['actual_scientific_receipts']=rr;entry['pending_without_terminal_receipt']=pending
 observations.append(entry)
obsp=O/'actual_live_handles_and_terminal_receipts.json';put(obsp,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'processes':observations,'same_live_handles_not_restarted':True,'no_worker_exitcode_alone_grants_case_credit':True,'main_scientific_payload_IO':False,'case_credit':0})
progressp=O/'new-actual-downstream-and-acceptance.json';put(progressp,{'F3_delegated133_three_full836_accepted_to243':ref(root(1052)/'source133-adoption-three-full836-independent-QI-and-visual-review.json'),'F5_source173_six_actual_native1017_full801_typed157_requests':ref(root(1045)/'controller-config.json'),'F3_two_additional_actual_XMF0_full836_render_requests':[ref(root(n)/'enabled-full836-render-request.json') for n in [1046,1047]],'F2_four_actual_typed0_full401_XMF_requests':[ref(root(n)/'controller-config.json') for n in [1048,1049,1050,1051]],'F5_source174_two_actual1008_XMF0_original138_bed_requests':ref(root(1055)/'controller-config.json'),'F5_source174_independent_metadata_review':ref(root(1055)/'source174-two-full801-bed-independent-adoption-review.json'),'actual_source174_bed_binding_role_sidecar':ref(rolep),'new_failed_partial_cleanup_completed0':ref(cleanup_review),'conversion_global_serial_cap':1,'render_global_shared_cap':2,'Home_floor_GiB':500,'q_n_q_e_granted':False,'no_new_native_GPU_simulations_this_turn':True,'case_credit_from_dispatch_alone':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);(O/'resource-ledger-frozen.json').write_bytes(raw);free=shutil.disk_usage('/home/jade').free;assert free>=500*2**30
assert ledger['limits']['qualification_attempts']==1024 and ledger['limits']['production_attempts']==720
cp.update(checkpoint=159,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_158.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_158.json'),new_accepted_decisions=[],home_free_gib=free/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(v['kind']==k for v in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(v.get('gpu_seconds',0) for v in ledger['charges'])/3600,cpu_core_hours_charged=sum(v.get('cpu_core_seconds',0) for v in ledger['charges'])/3600,previous_goal_turn_classification='Progress:three genuine F3 full836 personal visuals and native/typed/XMF/QI/actual cloneQA accepted243. Native-complete F5 six typed1045, two full836 F3 renders1046/1047, four F2 full401 XMF1048..1051 and two F5 full801 bed1055 registered and actual handles revalidated. Two proven failed unpublished H5 partials deleted by actual registered1054 completed0, additional76.467GiB freed, cumulative515.503GiB cleanup independently verified with original receipts preserved. No numerical grant;336-case goal remains active.')
cp['actual_progress']['storage_cleanup_reverification']=ref(cleanup_review);cp['actual_progress']['actual_process_handles_and_frozen_producer_results']=ref(obsp);cp['actual_progress']['243_visual_and_actual_downstream_plus_failed_partial_cleanup']=ref(progressp)
cp['source_agents']={'f5_bed_recovery':'fresh173 independent1044 plus actualtyped1045; fresh174 original138 two metadata gates closed and actualbed1055 live; fresh175 actual1028 three typed0 original129 XMF disabled requests active','f6_endpoint_initial_qa':'fresh147 conservative directory-reference storage audit adopted1053 and exact failed partial-file cleanup1054 completed0; fresh148 three DZXY full241 completed951 personal visuals active','production_recovery':'fresh133 three original P1000 full836 independently accepted243/F3=24; fresh134 actual1026 P0800AY0460 plus up to2 genuine complete unaccepted full836 visuals active'}
cp['next_executable_tasks']=['Integrate fresh148 three completed951 DZXY full241 delegated visuals after independent alltimes/UID/lifecycle/omega state0/H5audit/scopes closure; preserve128kg physical versus256kg native mass and unknown omitted states.','Integrate fresh134 actual1026 P0800AY0460 full836 personal contact/key review; only genuinely completed other renderers accepted, no mother aliases or live restart.','Adopt fresh175 actual1028 M090T080/M090T100/M100T080 typed0 original129 full801 N3 XMF metadata handoff; preserve actual typed complete scope and historical172subset scope separately.','Observe same1016/1055 full801 original138 bed actual diagnostics; complete UID/bed footprint/nonfinite/event bins independent closure enables next116023 boundedrender, worker0 alone gives no physical/visual credit.','Advance genuine completed F2 XMF1036..1038/1048..1051 to original116023 full401 bounded render then delegated visual; no GPU rerun.','Keep sixF5typed1045 and other existing typed/XMF/render same handles, retain source inputs and receipts; convertcap1/rendercap2 stay unchanged.','Preserve cumulative515.503GiB failure cleanup journals and deleted-file absences, accepted/pending/live/reusable outputs protected; Home remains≥500GiB.','Continue to336 independent visually accepted complete3D cases; numerical reference and external validation remain unaccepted; cumulative approved resource window and original deadline not reset.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_159.json',cp);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_159.json').relative_to(R)),str(rolep.relative_to(R))]
for n in [1045,1046,1047,1048,1049,1050,1051,1054,1055]:paths.extend(str(p.relative_to(R)) for p in root(n).glob('*launch*.json'))
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: checkpoint243 complete visuals actual downstream dispatch and cumulative515GiB failed cleanup','--',*paths],cwd=R,check=True)
print({'accepted':243,'counts':cp['accepted_per_family'],'Home_free_GiB':free/2**30,'cumulative_freed_allocated_GiB':(old['deleted_allocated_bytes']+result['deleted_allocated_bytes'])/2**30,'GPU_h':cp['gpu_hours_charged'],'CPU_core_h':cp['cpu_core_hours_charged'],'attempts':cp['attempt_counts'],'live_roots':[v['root'] for v in observations if v['live']],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
