from pathlib import Path
import json,hashlib,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in ['.json','.xml','.xmf','.py'];return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_116.json');accepted=cp['accepted_decisions']+sum([load(root(n)/'actual-integration-review.json')['decisions'] for n in [902,903,904]],[]);a=[load(p) for p in accepted];ids={x['case_id'] for x in a}|{x.get('physical_case_id',x['case_id']) for x in a};digests={x['physical_condition_sha256'] for x in a};rows=[]
for row in load(root(792)/'actual-frontier-correction.json')['F7_actual48_complete_pipeline_cases']:
 cid=row['case_id']
 if cid in ids or row['actual_converter_physical_condition_sha256'] in digests:continue
 for p in row['actual_completed_receipts'].values():assert sha(p['path'])==p['sha256'];r=load(p['path']);assert (r['status'],r.get('returncode'))==('completed',0)
 for key in ['typed_report','xmf_manifest','render_report']:assert sha(row[key]['path'])==row[key]['sha256']
 t=load(row['typed_report']['path']);m=load(row['xmf_manifest']['path']);v=load(row['render_report']['path']);assert t['frames']==m['frames']==v['frames']==v['source_frames']==601 and t['particles']==m['particles']==70179 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert v['all_frames_rendered'] and v['native_identity_axis_preserved'] and v['actual_times_preserved_exactly'] and v['nonfinite_active_states']==0;assert t['time_evidence']['last_s']>=12;assert m['source_h5_sha256']==v['source_h5_sha256']==t['output_sha256'];dg=t['hash_scopes']['physical_condition_sha256'];assert dg==m['physical_condition_sha256']==row['actual_converter_physical_condition_sha256'] and dg not in digests;assert sha(m['xdmf'])==m['xdmf_sha256']==v['xdmf_sha256_before']==v['xdmf_sha256_after'];assert len(v['outputs']['contact_sheets'])==26
 rows.append({'case_id':cid,'physical_condition_sha256':dg,'actual_receipts':row['actual_completed_receipts'],'typed_report':row['typed_report'],'xmf_manifest':row['xmf_manifest'],'render_report':row['render_report'],'actual_frames':601,'actual_particles':70179,'actual_complete_pipeline_confirmed':True,'visual_review_pending':True,'assigned_agent':'/root/f5_bed_recovery' if cid.endswith(('A046','A047')) else '/root/production_recovery' if cid.endswith(('A049P5','A050P5')) else '/root/f6_endpoint_initial_qa' if cid.endswith('A059P5') else 'next explicit delegation after current review','case_credit':0})
assert len(rows)==7;O=H/'root_stage1_F7_actual_remaining7_after188_stock_assignment_proof_905';O.mkdir();(O/'verified-stock.json').write_text(json.dumps({'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'current_total_accepted':188,'current_F7_accepted':41,'remaining_to_F7_48':7,'cases':rows,'old_Root792_already_accepted_flags_ignored':True,'45_degree_mother_reused_not_rerun':True,'science_payload_not_read_or_hashed':True,'Root_personal_PNG_review':False,'case_credit':0},ensure_ascii=False,indent=2)+'\n');(O/'metadata-validation-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'F7_remaining_verified_cases':7,'case_ids':[r['case_id'] for r in rows]}))
