from pathlib import Path
import json,hashlib,datetime,copy,collections,subprocess,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_259.json';cp=load(cpfile);assert cp['checkpoint']==259 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==304 and cp['accepted_per_family']['F5']==30
ip=root(1338)/'full336-current304-actual-final48-delivery-progress-index.json';index=load(ip);rows={r['physical_case_id']:r for r in index['cases']};f6p=root(1341)/'actual951-lastF6-full241-render-plus-rigid-QI-three-fluid-omissions-scope-previsual-proof.json';f6=load(f6p);assert f6['all241_geometry_velocity_N3_actual_times_UID_identity_finite_active_states_verified'] and f6['rigid_full241_Part0to240_17_fields_finite_verified'] and not f6['all_native_UIDs_active_each_frame'] and not rows[f6['physical_case_id']].get('accepted_decision');live=[]
for original,pid,start in [(1102,565610,'213371315'),(1155,571820,'213429031')]:
 p=Path(f'/proc/{pid}');assert p.exists();st=p.joinpath('stat').read_text().split(') ',1)[1].split();assert st[19]==start;cmd=p.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');mp=Path(cmd[cmd.index(b'--manifest')+1].decode());out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);m=load(mp);physical=m['physical_case_id'];assert not rows[physical].get('accepted_decision');count=len(list((out/'frames').glob('frame_*.png')));expected=(836,179208,3) if original==1102 else (401,418104,3);assert tuple(m['fields']['position']['shape'])==tuple(m['fields']['velocity']['shape'])==expected
 live.append({'original':original,'physical_case_id':physical,'actual_pid':pid,'actual_startticks':start,'actual_process_state':st[0],'same_handle_verified_live':True,'own_manifest':ref(mp),'private_frame_filename_stat_count':count,'private_PNG_payload_IO':False,'no_restart':True,'future_own_QI_root':1340 if original==1102 else 1346,'future_own_QI_proof':None,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_two_F5_actual1181_1191_visual_acceptance304_lastF6_actual951_particle_rigid_QI_next_originalF3_1102_F2_1155_live_1343';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_260.json';assert not O.exists() and not np.exists();O.mkdir();proof=O/'current304-two-F5-visual-adoptions-lastF6-own241QI-and-next-original-F3-F2-live-frontier.json';put(proof,{'schema':'ds02.actual304-lastF6-QI-next-original-F3-F2-live-frontier.v1','at_utc':now.isoformat(),'two_new_actual_F5_main_adoptions':[ref(root(1337)/'source188-actual1181-full801QI-personal-visual-adoption.json'),ref(root(1338)/'source208-actual1191-full801QI-personal-visual-adoption.json')],'lastF6_actual_full241_particle_render_and_rigid_QI':ref(f6p),'lastF6_personal_visual_pending':'fresh189','next_original_actual_live_renderers':live,'source208_upstream_legacy_plan_alias_preserved_but_not_raw_native_field_authority':True,'source208_physical_closure_double_namespace_masks_match_actual_native_and_ownQI':True,'no_scientific_payload_IO':True,'checkpoint304_not_completion_of336':True,'new_case_credit_this_frontier':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=260,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active304/336; F5=30 after actual1181/1191 own801QI and source188/208 personal43PNG each, source208 legacy plan alias correction recorded while actualraw masks preserved. LastF6 original951 full241 render completed0/pub, fullrigid Part/Time/QI1341 complete, source189 personally reviewing. Nextsame actual originalF3 1102 and F2 1155 rendering; source209 F3 visual task assigned, source174 F5 catalog28/20 draft awaiting finalcommit.',previous_goal_turn_classification='PROGRESS: two actualF5 full801 independent personal43PNG reviews accepted, authoritative303 then304 cases. LastF6 actual951 completed/published ownfull241 particle/rididmetadataQI1341 verified; three fluid omissions/700 particle-frame omissions and massscope difference retained. Sameactual F3/F2 process PID/startticks live nextcase renders verified; source174 still frozen28/20 while F5main30.')
new['actual_progress']['lastF6_actual951_full241_particle_render_rigid_own_QI']=ref(f6p);new['actual_progress']['current304_visual_acceptances_lastF6_QI_nextF3F2_actual_live_frontier']=ref(proof);new['next_executable_tasks']=['Adopt fresh189 lastF6 personal11contacts10keys after exact finalsourcecommit/ownQI1341/actualpub metadata verification; finalfamily F6 reaches48 only then.','Observe same F3 original1102 PID565610/start213371315, finish original836/publication then run durableownQI1340 once and supply source209; no timeout restarts.','Observe same F2 original1155 PID571820/start213429031, finish original401/publication, independently verify ownmetadataQI1346 with exact nativecanonical/typedlegacy/UID omission roles then assign source175 personal17contacts9keys.','Adopt source174 actualF5 final48 frozen28/20 catalog after finalcommit, append currentmain30/18 sidecar without changing source bytes, preserve alias/namespace/legacy runtime states.','Continue originalregistered queue toward336, Home>=500GiB, preserve534.4086GiB cleanup proof and numerical/external unknown statuses.'];put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);index['lastF6_actual_full241_particle_rigid_QI_pending_visual']=ref(f6p);index['current304_next_actual_F3_F2_live_frontier']=ref(proof);put(O/'full336-current304-actual-final48-delivery-progress-index.json',index);(O/'frontier-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: checkpoint304 two actual F5 accepts and last F6 particle rigid QI','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':260,'accepted':304,'per_family':new['accepted_per_family'],'live_originals':[(r['original'],r['actual_pid'],r['actual_startticks'],r['private_frame_filename_stat_count']) for r in live],'free_GiB':free,'GPUh':gpu,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
