from pathlib import Path
import json,hashlib,subprocess,copy,collections,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit='40a50610edf9d5729452e298a0cb5917fdc3b8a0';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_183_f6_assigned_f5_m095_t100_root1180_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==3
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh183.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/personal-visual-decision.json');e=s['evidence'];c=s['case'];pid=c['physical_case_id'];cid=c['case_id'];qip=root(1298)/'actual1180-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip)
assert s['assigned_family']=='F6' and s['actual_family']=='F5' and s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and not s['recursive_delegation']
assert (pid,cid)==(qi['physical_case_id'],qi['case_id']) and s['decision']['status']=='visual-approved-by-delegated-agent' and s['decision']['case_credit']==0 and not s['decision']['global_acceptance'] and not s['decision']['q_n'] and not s['decision']['q_e']
assert e['root_qi_proof']['path']==str(qip) and e['root_qi_proof']['sha256']==sha(qip)
for k,v in e.items():assert sha(v['path'])==v['sha256'] and Path(v['path']).stat().st_size==v['bytes']
for k,v in qi['actual_completed_metadata_evidence'].items():
 a=e[{'render_publish_receipt':'publish_receipt'}.get(k,k)];assert a['path']==v['path'] and a['sha256']==v['sha256']
 if k.endswith('_receipt') and k!='render_publish_receipt':r=load(v['path']);assert r['status']=='completed' and r['returncode']==0 and r['request']['case_id']==cid
canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];source=qi['actual_SourceDef']['sha256'];assert canonical==c['canonical_native_physical_condition_sha256'] and legacy==c['actual_converter_legacy_scope_sha256'] and source==c['xmf_source_def_scope_sha256'] and len({canonical,legacy,source})==3
assert qi['actual_native_source_plan_condition_field_present'] is c['actual_native_source_plan_field_present'] is False and qi['actual_native_source_plan_condition_sha256'] is c['actual_native_source_plan_physical_condition_sha256'] is None
assert qi['XMF_source_plan_condition_field_sha256']==qi['bed_declared_source_plan_field_sha256']==source and not qi['XMF_source_plan_condition_field_has_native_canonical_role'] and qi['XMF_source_plan_condition_field_has_SourceDef_role']
assert e['source_definition_xml']['path']==qi['actual_SourceDef']['path'] and e['source_definition_xml']['sha256']==source
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all_native_UIDs_active_each_frame'] and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
counts={'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'total':194427};assert c['producer_counts']==counts and c['actual_time_window_s']==qi['actual_time_window_s']
limits=s['lifecycle_and_limits'];assert limits['producer_counts']==counts and limits['actual_time_window_s']==qi['actual_time_window_s'];assert limits['actual_render_receipt']['path']==e['render_receipt']['path'] and limits['controller_result']['path']==e['controller_result']['path'] and limits['atomic_publish']['path']==e['publish_receipt']['path'];assert limits['precision_negative']['initial_qa_precision_accepted'] is False and limits['precision_negative']['historical_A_B_penetration_flags_retained'] is True
vr=s['visual_review'];contacts=vr['contact_sheets'];keys=vr['key_frames'];assert vr['method']=='view_image' and vr['viewed_all_contact_sheets'] and vr['viewed_all_key_frames'] and len(contacts)==34 and len(keys)==9 and [r['sheet_index'] for r in contacts]==list(range(34)) and [r['frame'] for r in keys]==list(range(0,801,100))
pub=load(e['publish_receipt']['path']);render=load(e['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==e['render_report']['sha256'];out=Path(pub['published_output_root']);pubfiles={r['relative_path']:r for r in pub['files_excluding_receipt']};assert [r['path'] for r in contacts]==render['outputs']['contact_sheets']
for r in contacts+keys:
 p=Path(r['path']);v=pubfiles[str(p.relative_to(out))];assert sha(p)==r['sha256']==v['sha256'] and p.stat().st_size==r['bytes']==v['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_242.json';cp=load(cpfile);assert cp['checkpoint']==242 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==295 and cp['accepted_per_family']['F5']==25
assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
ip=root(1313)/'full336-current295-actual-final48-delivery-progress-index.json';index=load(ip);target=[r for r in index['cases'] if r['physical_case_id']==pid];assert len(target)==1 and not target[0].get('accepted_decision') and target[0]['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);attempts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and attempts['qualification']<=1024 and attempts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source183_actualF5_M095T100_original1180_full801QI_personal43PNG_nativeplan_absence_stale_blocks_checked_visual_acceptance_1309';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_243.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source183-byte-exact-readonly-validation-all-case-limits-blocks-and-main43publishedPNG-proof.json';put(vp,{'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'all_case_and_lifecycle_limits_blocks_match_current_actual1180_F5':True,'own_QI1298_inherited_directory_name_semantic_correction':ref(root(1298)/'path-name-semantic-correction.json'),'native_plan_field_actual_absence_not_overridden':True,'main_all43_PNG_bound_to_actual_atomic_publish':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_SourceDef_scope_sha256':source,'source_review_commit':commit,'source_review_assigned_family':'F6','actual_review_family':'F5','source_visual_review':ref(R/prefix/'metadata/personal-visual-decision.json'),'independent_full801_QI':ref(qip),'actual_completed_metadata_evidence':qi['actual_completed_metadata_evidence'],'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_type_counts':counts,'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_and_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_bins_are_diagnostics_not_precision_thresholds':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'actual_native_plan_field_present':False,'actual_native_plan_field_value':None,'actual_XMF_plan_field_value':source,'actual_bed_plan_field_value':source,'canonical_legacy_SourceDef_roles_are_distinct':True,'actual_native_plan_absence_not_filled_from_other_namespace':True,'own_QI_inherited_directory_label_correction':ref(root(1298)/'path-name-semantic-correction.json'),'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':vr['observations'],'visual_limits':limits,'no_strong_runup_or_inundation_magnitude_claim_from_visual_screen':True,'source_personal_visual_decision':s['decision'],'original_AB_penetration_and_precision_negatives_preserved_by_predecessor_and_own_QI':True,'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source183-actual1180-full801QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'actual43PNG_bound_to_atomic_publish':True,'case_credit':1,'main_scientific_payload_IO':False});snapshot=O/'ledger-immutable-snapshot.json';snapshot.write_bytes(raw)
new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=1;new.update(checkpoint=243,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=296,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snapshot),active_reservations=ledger['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source170 actualF6 fixed24 particle+fulltime rigid delivery produced and independently verified; both original F2 1132/1110 actualcompleted0 published and ownQI1307/1308 complete; fresh183 actualF5 full801 personal43PNG now accepted296/F5=26 with nativeplan absence and all case/limits blocks verified.',authorized_work_state='Active296/336,40 pending. F1/F4/F7=48,F2=40,F3=39,F5=26,F6=47. ActualF2 originals1132 and1110 both ownfull401QI complete, fresh205/fresh184 personal26PNG reviews proceeding. Source171 F6 final48 particle+rigid full family catalog47accepted+onepending in progress.')
new['actual_progress']['source183_F5_actual1180_visual_acceptance']=ref(ap);new['actual_progress']['actual1110_full401_own_QI']=ref(root(1308)/'actual1110-full401-independent-UID-N3-time-scope-QI-proof.json');new['source_agents']['f6_endpoint_initial_qa']='fresh183 actualF5 M095T100 accepted F5=26; fresh184 actualF2 RX051ROT105 original1110 ownQI1308 completed then personal26PNG'
new['source_agents']['production_recovery']='fresh170 main fixed24 particle+rigid actual delivery complete; fresh171 F6 final48 catalog47accepted/onepending in progress';new['next_executable_tasks']=['Adopt fresh205 personal26PNG actualF2 RX063ROT075 original1132 using own401QI1307 preserving35fluid omissions.','Adopt fresh184 personal26PNG actualF2 RX051ROT105 original1110 using own401QI1308 preserving3fluid omissions.','Integrate fresh171 F6 final48 particle+fulltime rigid catalog with exact47accepted and lastpending original951, preserving fixed8/24 membership and no fake last visual approval.','Continue remaining40 original full renders and delegated personalreviews toward all336 distinct visual cases.']
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==296;put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=296,registered_pending_independent_physical_cases=40,new_case_credit=1);target[0].update(status='visual-approved-in-checkpoint243',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qip));index['actual_unaccepted_completed0_published_physical_cases']=[r for r in index['actual_unaccepted_completed0_published_physical_cases'] if r['physical_case_id']!=pid];assert sum(bool(r.get('accepted_decision')) for r in index['cases'])==296;put(O/'full336-current296-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F5 M095T100 full801 preserving nativeplan absence and original negatives','--',*paths],cwd=R,check=True);print({'checkpoint':243,'accepted':296,'F5':26,'pending':40,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
