from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,sys
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):assert ref(e['path'])['sha256']==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
mode=int(sys.argv[1]);assert mode in [207,186]
if mode==207:
 wn=5;original=1141;qinum=1324;outnum=1334;oldcp=252;oldcount=300;oldF3=39;tag='P1200AY0640';commit='8d87aa8cbd2c11950d5305e62d993cabed1b0db8';dirname='root_followup_207_f5_assigned_f3_p1200_ay0640_root1141_personal_visual_review_v1';oldroot=1328
else:
 wn=6;original=1135;qinum=1325;outnum=1335;oldcp=253;oldcount=301;oldF3=40;tag='P1200AY0570';commit='7a72914d296d862a2d2fc9e7a3609f0151a5c3f3';dirname='root_followup_186_f6_assigned_f3_p1200_ay0570_root1135_personal_visual_review_v1';oldroot=1334
W=Path(f'/home/jade/.codex/worktrees/ds-data-02-f{wn}/DualSPHysics');prefix=Path(f'lagrangian-fluid-lab/campaigns/ds-data-02/families/F{wn}/handoff_20261003')/dirname;P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==(8 if mode==207 else 4)
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
qip=root(qinum)/f'actual{original}-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';qi=load(qip);cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_request_condition_sha256'];mask=qi['actual_native_XMF_plan_field_namespaces'];counts={'fixed':111708,'moving':0,'floating':0,'fluid':67500,'total':179208}
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'] and qi['actual_converter_condition_sha256']==canonical
assert all(v=={'present':False,'value':None} for v in mask['native'].values()) and mask['XMF']['source_plan_condition_sha256']['present'] and mask['XMF']['source_plan_condition_sha256']['value']!=canonical and mask['XMF']['source_plan_physical_condition_sha256']=={'present':False,'value':None}
qrefs={**{k+'_receipt':e for k,e in qi['actual_completed_receipts'].items()},'typed_report':qi['typed_report'],'xmf_manifest':qi['XMF_manifest'],'xmf_xml':qi['XMF_XML'],'render_report':qi['render_report'],'render_publish_receipt':qi['publish'],'source_preparation_report':qi['source_preparation_report'],'initial_parent_QA_report':qi['initial_parent_QA_report'],'initial_parent_QA_receipt':qi['initial_parent_QA_receipt']}
if mode==207:
 m=load(P/'manifest.json');a=load(P/'metadata/actual-render-metadata.json');u=load(P/'metadata/upstream-evidence.json');v=load(P/'metadata/png-visual-evidence.json');cl=load(P/'metadata/physical-stage-closure.json');s=load(P/'metadata/visual-decision.json')
 for j in [m,a,u,v,cl,s]:assert j['case_id']==cid and j['physical_case_id']==pid
 assert a['family_id']=='F3' and a['assigned_agent_family']=='F5'
 assert a['personal_review_scope']['reviewer_model']==s['reviewer']['model']=='gpt-5.6-luna/max' and not a['personal_review_scope']['recursive_delegation'] and not s['reviewer']['recursive_delegation']
 for e in m['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
 assert u['main_qi']['path']==str(qip);checked(u['main_qi'])
 erefs=u['actual_completed_metadata_evidence']
 for k,e in qrefs.items():x=erefs[{'initial_parent_QA_report':'initial_parent_qa_report','initial_parent_QA_receipt':'initial_parent_qa_receipt'}.get(k,k)];assert x==e
 assert a['producer_counts']=={'fixed':111708,'moving':0,'floating':0,'fluid_initial':67500,'total_initial':179208,'solver_dimension':3,'data2d':False}
 assert cl['counts_and_time']['frames']==836 and cl['counts_and_time']['time_window_s']==qi['actual_time_window_s'] and cl['counts_and_time']['total_initial']==179208
 scopes=u['producer_scope_roles'];assert scopes['native_request_condition_sha256']==scopes['actual_converter_condition_sha256']==scopes['typed_canonical_role']==scopes['xmf_canonical_role']==canonical
 assert not scopes['native_source_plan_condition_field_present'] and scopes['native_source_plan_condition_sha256'] is None and not scopes['native_source_plan_physical_condition_field_present'] and scopes['native_source_plan_physical_condition_sha256'] is None
 assert scopes['xmf_source_plan_condition_field_present'] and scopes['xmf_source_plan_condition_sha256']==mask['XMF']['source_plan_condition_sha256']['value'] and not scopes['xmf_source_plan_physical_condition_field_present'] and scopes['xmf_source_plan_physical_condition_sha256'] is None
 dec=s['decision'];assert dec['standalone_first_stage_visual_approved'] and not dec['severe_visual_failure'] and not dec['needs_root_image_intervention'] and dec['independent_case_count_increment']==0 and not dec['numerical_precision_accepted'] and not dec['q_n_granted'] and not dec['q_e_granted']
 contacts=[{'path':e['absolute_path'],'sha256':e['sha256'],'bytes':e['bytes'],'index':e['index'],'viewed':e['reviewed']} for e in v['producer_attested_contact_sheets']]
 keys=[{'path':e['absolute_path'],'sha256':e['sha256'],'bytes':e['bytes'],'frame':e['frame_index'],'viewed':e['reviewed']} for e in v['producer_attested_keyframes']]
 reviewed=a['personal_review_scope']['reviewed_at_utc'];assert reviewed==s['reviewer']['reviewed_at_utc'];assert 'reviewed_at_utc' not in v['review_coverage'] or v['review_coverage']['reviewed_at_utc']==reviewed;timefield='actual_personal_reviewed_at_utc'
 observations=v['personal_observation'];limits={'source_visual_limits':s['evidence_limits'],'source_physical_closure':cl};sourcevisual=prefix/'metadata/visual-decision.json'
else:
 m=load(P/'manifest.json');s=load(P/'metadata/personal-visual-decision.json');a=m['actual_metadata'];vr=m['visual_review'];erefs=m['producer_chain']
 for j in [m,s]:assert j['case_id']==cid and j['physical_case_id']==pid and j['assigned_family']=='F6' and j['actual_family']=='F3'
 assert m['model']=='gpt-5.6-luna/max' and m['decision']==s['decision']=='visual-approved-by-delegated-agent' and m['case_credit']==s['case_credit']==0 and not m['q_n_granted'] and not m['q_e_granted'] and not m['payload_policy']['scientific_payloads_opened_or_hashed'] and not s['scientific_payloads_opened_or_hashed']
 assert erefs['qi_proof']['path']==str(qip);checked(erefs['qi_proof'])
 for k,e in qrefs.items():
  x=erefs[k];assert x['path']==e['path'] and x['sha256']==e['sha256'];assert 'exists' not in x or x['exists'];assert 'producer_sha256' not in x or x['producer_sha256']==e['sha256'];checked(x)
 for e in erefs.values():
  if isinstance(e,dict) and 'path' in e:assert Path(e['path']).suffix.lower() in {'.json','.xml','.xmf','.py','.md'};checked(e)
 assert a['frames']==836 and a['native_particles']==179208 and a['fixed_particles']==111708 and a['fluid_particles']==67500 and a['moving_particles']==a['floating_particles']==0 and a['dimension']==3 and a['actual_time_window_s']==qi['actual_time_window_s']
 assert a['native_canonical_condition_sha256']==a['actual_converter_condition_sha256']==a['typed_xmf_canonical_condition_sha256']==canonical
 scopes=m['scope_roles'];assert scopes['native_canonical_condition_sha256']==scopes['typed_xmf_canonical_condition_sha256']==canonical
 for ns,prefixns in [('native','native'),('XMF','xmf')]:
  for k,e in mask[ns].items():assert scopes[f'{prefixns}_{k}']==e
 assert vr['all_contact_sheets_viewed'] and vr['all_requested_key_frames_viewed'];contacts=vr['contact_sheets'];keys=vr['key_frames'];reviewed=m['created_at_utc'];timefield='source_package_created_at_utc_not_explicit_review_time';observations=vr['observations'];limits=vr['limitations'];sourcevisual=prefix/'metadata/personal-visual-decision.json'
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/f'scripts/validate_fresh{mode}.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
for k,e in qrefs.items():
 checked(e)
 if k.endswith('_receipt') and k!='render_publish_receipt':rc=load(e['path']);assert rc['status']=='completed' and rc['returncode']==0
assert len(contacts)==35 and len(keys)==9 and [e['index'] for e in contacts]==list(range(35)) and [e['frame'] for e in keys]==[0,100,200,300,400,500,600,700,835]
pub=load(qi['publish']['path']);r=load(qi['render_report']['path']);rc=load(qi['actual_completed_receipts']['render']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(qi['render_report']['path']);out=Path(pub['published_output_root']);published={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==r['outputs']['contact_sheets']
for e in contacts+keys:
 p=Path(e['path']);pr=published[str(p.relative_to(out))];checked(e);assert e['sha256']==pr['sha256'] and e['bytes']==p.stat().st_size==pr['bytes'] and e['viewed']
now=datetime.datetime.now(datetime.timezone.utc);stamp=datetime.datetime.fromisoformat(reviewed.replace('Z','+00:00'));finished=datetime.datetime.fromisoformat(rc['finished_at_utc']);assert finished<=stamp<=now
cpfile=H/f'ROOT_LIVE_RESUMPTION_CHECKPOINT_{oldcp}.json';cp=load(cpfile);assert cp['checkpoint']==oldcp and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==oldcount and cp['accepted_per_family']['F3']==oldF3
assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};ip=root(oldroot)/f'full336-current{oldcount}-actual-final48-delivery-progress-index.json';index=load(ip);target=next(x for x in index['cases'] if x['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);attempts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and attempts['qualification']<=1024 and attempts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/f'root_stage1_source{mode}_actualF3_{tag}_original{original}_full836QI_personal44PNG_exact_native_XMF_plan_absence_visual_acceptance_{outnum}';np=H/f'ROOT_LIVE_RESUMPTION_CHECKPOINT_{oldcp+1}.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/f'source{mode}-byte-exact-readonly-validator-main44publishedPNG-own836QI-proof.json';put(vp,{'schema':'ds02.main.F3.personal44PNG-source-adoption-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'all_actual_source_chain_refs_equal_own_QI':True,'independent_own_QI':ref(qip),'all44_publishedPNG_hashes_match_actual_atomic_publish':True,'actual_source_timestamp_field_role':timefield,'actual_source_timestamp_value':reviewed,'timestamp_after_completed_publication':True,'source_explicit_personal_review_time_field_present':mode==207,'source_explicit_personal_review_time_field_value':reviewed if mode==207 else None,'native_XMF_plan_field_namespace_masks_verified':mask,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_condition_sha256':canonical,'scope_schema':'ds-data-02.physical-binding.v1','source_review_commit':commit,'source_review_assigned_family':f'F{wn}','actual_review_family':'F3','source_personal_visual_review':ref(R/sourcevisual),'independent_full836_QI':ref(qip),'actual_completed_metadata_evidence':qrefs,'full_native_frames':836,'particle_count':179208,'initial_fluid_particles':67500,'actual_type_counts':counts,'actual_physical_window_s':qi['actual_time_window_s'],'all836_UID_type_mk_N3_actual_times_finite_active_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':mask,'native_absence_not_filled_from_XMF_plan_namespace':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':35,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':observations,'visual_limits':limits,'fixed_plus_fluid_mechanism_no_moving_or_floating_body_claim':True,'main_all44_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/f'source{mode}-actual{original}-full836QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new['accepted_per_family']['F3']+=1;new.update(checkpoint=oldcp+1,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=oldcount+1,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification=f'PROGRESS: actual F3 {tag} original{original} full836 ownQI{qinum} and delegated44PNG personal review adopted; native plan field absence and distinct XMF plan namespace preserved; previoussource172 full48 primary39 directory joined with four originalruntime unknown receipts and actualcompleted recovery audits retained.',authorized_work_state=f'Active{oldcount+1}/336, {335-oldcount} pending; F3={oldF3+1}; originalF5 1181 M105T080 and1191 M112T095 automatic rendering, future ownQI1331/1332 and nextfresh188/208 personal34+9 reviews assigned.')
new['actual_progress'][f'source{mode}_F3_actual{original}_visual_acceptance']=ref(ap);new['source_agents']['f5_bed_recovery' if wn==5 else 'f6_endpoint_initial_qa']=f'fresh{mode} actualF3 {tag} accepted; next '+('fresh208 F5 original1191 M112T095' if wn==5 else 'fresh188 F5 original1181 M105T080')+' assigned, same original renderer, ownQI pending'
new['next_executable_tasks']=['Observe originalF5 full801 renders1181 and1191 and run ownmetadataQI only after originalcompleted0/publication; source188/208 personally review34contacts9keys.','Adopt source173 actualF2 final48 catalog42accepted/sixpending preserving fixed8/24 and all scope/legacy/native absence roles.','Continue remaining originalrenders and delegatedpersonal reviews toward all336 cases; finalF6 original951 samehandle live faircapacitywait retained.','Retain user500GiB Home floor,534GiB cleanup audit, historical orphan native process returncode unknowns and original typed154 status unpromoted.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==oldcount+1;put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=oldcount+1,registered_pending_independent_physical_cases=335-oldcount,new_case_credit=1);target.update(status=f'visual-approved-in-checkpoint{oldcp+1}',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full836_QI=ref(qip));index['actual_unaccepted_completed0_published_physical_cases']=[r for r in index['actual_unaccepted_completed0_published_physical_cases'] if r['physical_case_id']!=pid];assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==oldcount+1;put(O/f'full336-current{oldcount+1}-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m',f'DS02: accept F3 {tag} full836 retaining native and XMF plan namespaces','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':oldcp+1,'accepted':oldcount+1,'F3':oldF3+1,'pending':335-oldcount,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
