from pathlib import Path
import json,hashlib,datetime,subprocess,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.py','.md','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'],e['path']
def same(a,b):return all(a[k]==b[k] for k in ['path','sha256'])
def parse(t):return datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',t).replace('Z','+00:00'))
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='87a20f3df60876c02693ef8c90cb451e38b153a1';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_206_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==4
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names};assert all((W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b) for n,b in blobs.items());before={n:sha(W/n) for n in names};man=load(P/'package-manifest.json');assert {str(prefix/e['path']) for e in man['files']}==set(names)-{str(prefix/'package-manifest.json')}
for e in man['files']:assert sha(P/e['path'])==e['sha256']
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh206.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1447)/'actual1149-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';assert sha(qip)=='5a9c1663be4bd400118caafac31d9db40bbcb2712d8e4140baa1a70e2ff0adca';qi=load(qip);s=load(P/'metadata/m106-t085-personal-visual-review.json');cid=qi['case_id'];pid=qi['physical_case_id'];assert s['identity']['case_id']==cid and s['identity']['physical_case_id']==pid and s['assigned_family']=='F6' and s['actual_physical_family']=='F5'
assert s['review_method']['visual_review_complete'] and s['review_method']['tool']=='functions.view_image' and s['review_method']['contact_sheets_viewed']==34 and s['review_method']['key_frames_viewed']==9 and s['review_method']['viewed_from_published_output'];assert not any(s['limitations_and_boundary'][k] for k in ['case_credit','q_n','q_e','strict_containment_claim','subdp_or_numerical_claim','science_payload_opened_or_hashed','new_jobs_started','shared_state_written','rerendered','png_self_hash_by_source_agent'])
er=qi['actual_completed_metadata_evidence']
for e in er.values():check(e)
for k,actual in [('root_qi',ref(qip)),('render_execution_receipt',er['render_receipt']),('render_report',er['render_report']),('publish_receipt',er['render_publish_receipt'])]:assert same(s['producer_chain'][k],actual)
assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['all_native_UIDs_active_each_frame']
n=load(er['native_receipt']['path']);x=load(er['xmf_manifest']['path']);t=load(er['typed_report']['path']);rc=load(er['render_receipt']['path']);r=load(er['render_report']['path']);pub=load(er['render_publish_receipt']['path']);br=load(er['bed_receipt']['path']);binding=load(br['request']['binding']);qa=load(er['initial_qa_report']['path']);sd=qi['actual_SourceDef'];plan=qi['actual_source_plan_JSON_file'];check(sd);check(plan)
for key in ['native_receipt','typed_receipt','xmf_receipt','render_receipt','bed_receipt','gencase_receipt','initial_qa_receipt']:
 j=load(er[key]['path']);assert (j['status'],j['returncode'])==('completed',0) and j['request']['case_id']==cid
assert qa['all_basic_placement_checks_pass'] and not qa['numerical_precision_result_accepted'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert canonical==n['request']['physical_condition_sha256']==x['physical_condition_sha256']==s['scope_roles']['canonical_native_physical_condition_sha256'] and legacy==t['hash_scopes']['physical_condition_sha256']==s['scope_roles']['typed_converter_legacy_scope_sha256'] and sd['sha256']==s['scope_roles']['source_definition_xml_sha256'] and plan['sha256']==s['scope_roles']['source_plan_json_sha256']
assert len({canonical,legacy,sd['sha256'],plan['sha256']})==4 and [s['counts_and_time']['actual_time_first_s'],s['counts_and_time']['actual_time_last_s']]==qi['actual_time_window_s'];masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces']
for k,v in s['scope_roles']['native_request_field_presence'].items():assert v==(k in n['request'])
for k,v in s['scope_roles']['xmf_manifest_field_presence'].items():assert v==(k in x)
assert binding['source_definition']==sd['path'] and binding['source_definition_sha256']==sd['sha256'] and binding['source_plan_file']==plan['path'] and binding['source_plan_file_sha256']==plan['sha256']
for j in [n,br]:assert j['input_hashes_at_launch'][plan['path']]==j['input_hashes_after_run'][plan['path']]==plan['sha256']
reviewed=s['reviewed_at_utc'];assert parse(rc['finished_at_utc'])<=parse(reviewed)<=datetime.datetime.now(datetime.timezone.utc);ev=s['visual_evidence'];contacts=ev['contact_sheets'];keys=ev['key_frames'];assert len(contacts)==34 and len(keys)==9 and ev['all_contact_sheets_viewed'] and ev['all_key_frames_viewed'] and [e['frame_index'] for e in keys]==list(range(0,801,100))
assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['render_report']['path']);out=Path(pub['published_output_root']);pf={e['relative_path']:e for e in pub['files_excluding_receipt']};jc=[];jk=[]
for e,group in [(e,jc) for e in contacts]+[(e,jk) for e in keys]:
 p=Path(e['path']);rel=str(p.relative_to(out));dg=sha(p);assert e['viewed_with']=='functions.view_image' and not e['sha256_computed_by_source_agent'] and rel==e['relative_path'] and dg==e['producer_declared_sha256']==pf[rel]['sha256'] and p.stat().st_size==e['bytes_at_review']==e['producer_declared_bytes']==pf[rel]['bytes'];j={**e,'sha256':dg,'bytes':p.stat().st_size,'main_hash_matches_actual_publisher':True,'viewed':True,'view_method':'view_image'}
 if group is jk:j['frame']=e['frame_index']
 group.append(j)
assert [e['path'] for e in jc]==r['outputs']['contact_sheets'] and len({e['path'] for e in jc+jk})==43
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_332.json';cp=load(cpfile);ip=root(1449)/'full336-current335-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==335 and cp['accepted_per_family']['F5']==47;row=next(e for e in idx['cases'] if e['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
oldref=cp['actual_progress']['F5_current47_actual_primary_bed_delivery'];check(oldref);old=load(oldref['path']);check(old['main_independent_verification']);oldrows=old['accepted47_actual_primary_bed_rows'];assert len(oldrows)==47
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<parse(cp['deadline_utc']) and not ld['reservations']
O=H/'root_stage1_source206_lastF5_actual1149_personal43PNG_full801QI_F5final48_primary_336_visual_records_final_distinction_audit_pending_1450';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_333.json';assert not O.exists() and not np.exists();O.mkdir()
for name,b in blobs.items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
cv=subprocess.run(['python3','-B',str(R/prefix/'scripts/validate_fresh206.py')],capture_output=True,text=True);assert cv.returncode==0,(cv.stdout,cv.stderr);assert all((W/n).read_bytes()==b and (R/n).read_bytes()==b for n,b in blobs.items())
proof=O/'source206-main-personal43PNG-own-QI1447-finalF5primary48-proof.json';put(proof,{'at_utc':now.isoformat(),'source_commit':commit,'source_exact_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'copied_validator_stdout':cv.stdout,'own_full801_QI':ref(qip),'personal_review_UTC':reviewed,'personal43PNG_actual_SHA_publisher_match':True,'actual_native_XMF_plan_field_namespaces':masks,'source_visual_observations':s['observations'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'previous47_rows_copied_exactly_not_recertified':True,'goal_completion_not_granted_by_this_adoption':True})
dp=O/(pid+'-delegated-visual-decision.json');put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_SourceDef_scope_sha256':sd['sha256'],'source_review_commit':commit,'source_review_assigned_family':'F6','actual_review_family':'F5','source_personal_visual_review':ref(R/prefix/'metadata/m106-t085-personal-visual-review.json'),'source_review_closure':ref(proof),'independent_full801_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_type_counts':{'fixed':158559,'moving':4210,'floating':0,'fluid':31658},'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_oneDP_twoDP_diagnostic_counts_zero_verified':True,'actual_native_XMF_plan_field_namespaces':masks,'actual_bed_SourceDef_XML_FILE':sd,'actual_source_plan_JSON_file':plan,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':jc,'keyframes':jk,'visual_observations':s['observations'],'visual_limits':s['limitations_and_boundary'],'historical_negative_flags':qi['historical_negative_flags'],'original_precision_negative':qi['actual_initial_QA_precision_negative'],'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
nav=[{'path':e['path'],'sha256':e['sha256'],'bytes':e['bytes'],'frame':e['frame'],'actual_time_s':x['actual_time_s'][e['frame']],'role':'navigation metadata; no new personal review'} for e in jk];bi=qa['input_provenance']['generated_bi4_sha256'];matches=[p for p,d in n['input_hashes_at_launch'].items() if p.lower().endswith('.bi4') and d==bi];assert matches;hp=t['output_hdf5'];hm={stage:{'present':hp in rc[field],'value':rc[field].get(hp)} for stage,field in [('launch','input_hashes_at_launch'),('after','input_hashes_after_run')]};assert all(v['present'] and v['value']==t['output_sha256'] for v in hm.values())
products=copy.deepcopy(oldrows)+[{'family_id':'F5','case_id':cid,'physical_case_id':pid,'accepted_visual_decision':ref(dp),'own_full801_QI':ref(qip),'primary_metadata':er,'ParaView_open_XMF':er['xmf_xml'],'frames':801,'particles':194427,'actual_time_window_s':qi['actual_time_window_s'],'all801_UID_N3_native_times_finite_render_and_fullbed_metadata_verified':True,'genuine_initial_placement_QA':{'receipt':er['initial_qa_receipt'],'report':er['initial_qa_report'],'GenCase':er['gencase_receipt'],'generated_XML':er['generated_xml'],'native_initial_BI4_launch_matching_paths':matches,'BI4_hash_is_producer_attestation_not_main_payload_IO':True,'numerical_precision_negative_preserved':qa['numerical_precision']},'actual_native_physical_condition_sha256':canonical,'actual_typed_scope_sha256':legacy,'actual_XMF_condition_sha256':x['physical_condition_sha256'],'actual_native_XMF_plan_field_namespaces':masks,'actual_bed_source_plan_physical_condition_field':{'present':True,'value':sd['sha256']},'render_H5_launch_after_field_masks':hm,'atomic_publish_receipt':er['render_publish_receipt'],'legacy_atomic_publish_receipt_absent':False,'contacts34_actual_SHA_verified':jc,'source_personal_key_refs_preserved':jk,'navigation9_actual_SHA_verified':nav,'newly_added_actual_own_QI_limits_preserved':qi,'new_case_credit':0,'new_personal_review':False,'Q_N':0,'Q_E':0,'precision_status':'视觉检查通过、数值精度未验收','zero_bed_bins_are_not_subDP_or_precision_certification':True}];assert products[:47]==oldrows and {r['physical_case_id'] for r in products}==set(old['membership']['registered_final48_physical_case_ids']) and len(products)==48
product=O/'F5-FINAL48-COMPLETE-ACTUAL801-PRIMARY-BED-DELIVERY.json';put(product,{'schema':'ds02.main.F5.actual-final48-complete-primary-bed.v1','at_utc':now.isoformat(),'predecessor_actual47_product':oldref,'main_independent_verification':ref(proof),'membership':old['membership'],'accepted48_actual_primary_bed_rows':products,'pending_cases':[],'delivery_complete':True,'accepted48_primary_bindings_complete':True,'legacy_pub_H5_field_absences_and_source_scope_limits_preserved':True,'new_case_credit':0,'Q_N':0,'Q_E':0,'scientific_payload_IO':False})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=1;new.update(checkpoint=333,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=336,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: lastF3 accepted335 and actual primary48 delivered; this turn lastF5actual1149 personal206 adopted and actual full801 primary-bed final48 complete, all336 visual records complete. Goal completion audit remains unproven until physical distinctions194 and requirement230 resolved and final all336 user direct-file index checked.',authorized_work_state='Active:336/336 records visually accepted and seven final48 primary products available, numerical precision unaccepted. Do not declare full goal achieved yet: physical parameter/geometry difference audit194 has incomplete-signature uncertainties requiring case-bound source repair; explicit requirement230 and global actual336 final navigation/metadata audit remain.')
new['actual_progress']['F5_final48_complete_actual_primary_bed_delivery']=ref(product);new['actual_progress']['source206_lastF5_actual1149_visual_acceptance']=ref(dp);new['goal_completion_audit_status']='unproven: final physical distinction, explicit requirement and all336 direct-delivery audits pending';new['next_executable_tasks'].insert(0,'Complete final all336 direct XMF/time/N3 and preview user delivery using seven current48 products; fix fresh194 source-control signature extraction using exactcase actual native input owner parameters; adopt requirement230 and resolve every missing first-stage requirement before marking goal complete.')
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==336 and all(v==48 for v in new['accepted_per_family'].values());put(np,new);row.update(status='visual-approved-in-checkpoint333',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,actual_full801_QI=ref(qip),precision_status='视觉检查通过、数值精度未验收');idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=336,registered_pending_independent_physical_cases=0,new_case_credit=1,delivery_complete=False,all_visual_records_complete=True,goal_completion_audit_status=new['goal_completion_audit_status']);idx['actual_unaccepted_completed0_published_physical_cases']=[];idx['F5_final48_complete_actual_primary_bed_delivery']=ref(product);assert sum(bool(r.get('accepted_decision')) for r in idx['cases'])==336;put(O/'full336-current336-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('最后F5原1149通过801帧Q-I与fresh206全部34总览+9关键帧个人视觉检查，F5实际最终48主文件与床面产品完成，七族各48视觉记录已齐。此提交不宣告GOAL完成：仍需完成全336实际用户主文件入口、case-bound物理参数差异审计194及显式要求审计230；不完整签名产生的疑似重复不得用uniqueID或摘要布尔值抹平。视觉检查通过、数值精度未验收，QN/QE=0。\n');paths0=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths0],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: complete all336 visual records and actual F5final48 primary preserving final audit pending','--',*paths0],cwd=R,check=True);print(json.dumps({'checkpoint':333,'visual_records':336,'per_family':new['accepted_per_family'],'F5_primary':48,'goal_complete':False,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
