from pathlib import Path
import json,hashlib,subprocess,datetime,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.py','.md','.xml','.xmf','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_205.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==274;decs={p:load(p) for p in cp['accepted_decisions']};frozenfile=root(1093)/'FIRST8_PER_FAMILY_STAGE1_SUBSET56.json';frozen=load(frozenfile);sets={};authorities=[];packages=[]
items=[('ds-data-02-f3','F3',152,'ac0512b26','root_followup_152_f4_actual_delivery24_root1093_cp200_v1','metadata/f4-actual-delivery24-root1093-cp200.json'),('ds-data-02-f6','F6',169,'3794615dc','root_followup_169_f6_authoritative_membership_f2_render_wait_v1','metadata/authoritative-membership.json')]
for wt,assigned,n,short,pkg,meta in items:
 W=Path('/home/jade/.codex/worktrees')/wt/'DualSPHysics';commit=subprocess.check_output(['git','rev-parse',short],cwd=W,text=True).strip();prefix=f'lagrangian-fluid-lab/campaigns/ds-data-02/families/{assigned}/handoff_20261003/{pkg}';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==(4 if n==152 else 3);P=W/prefix;before={name:sha(W/name) for name in names};vld=P/f'scripts/validate_fresh{n}.py';v=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert v.returncode==0 and before=={name:sha(W/name) for name in names};x=load(P/meta);fam='F4' if n==152 else 'F6';rows=x['actual_delivery24']['rows_source_order'] if n==152 else x['first24_actual_visual_membership']['rows'];assert len(rows)==24
 selected=[]
 for row in rows:
  e=row['decision'] if n==152 else row['visual_decision'];assert e['path'] in decs and sha(e['path'])==e['sha256'];d=decs[e['path']];assert d['family_id']==fam and d['status'].startswith('visual-approved');selected.append({'case_id':d['case_id'],'physical_case_id':d.get('physical_case_id',d['case_id']),'actual_visual_decision':ref(e['path']),'source_decision_precision_field_presence_and_value':{k:d[k] for k in ('precision_status','numerical_precision_status','q_n_granted','q_e_granted','q_n','q_e') if k in d},'source_row':row})
 pids=[r['physical_case_id'] for r in selected];assert len(set(pids))==24;ids8=[]
 for e in frozen['cases_by_family'][fam]:
  assert sha(e['path'])==e['sha256'];d=load(e['path']);ids8.append(d.get('physical_case_id',d['case_id']))
 assert len(ids8)==8 and set(ids8)<=set(pids)
 current=[d.get('physical_case_id',d['case_id']) for d in decs.values() if d['family_id']==fam];assert len(current)==cp['accepted_per_family'][fam] and set(pids)<=set(current)
 if n==152:
  assert pids[:8]==ids8;assert x['actual_delivery24']['all_rows_actual_frames_1201'];oldcp=load(x['authorities']['checkpoint200']['path']);ordered=[]
  for p in oldcp['accepted_decisions']:
   d=load(p);pid=d.get('physical_case_id',d['case_id'])
   if d['family_id']=='F4' and pid not in ids8:ordered.append(pid)
  assert pids==ids8+ordered[:16]
 sets[fam]={'actual_first24_count':24,'rows_actual_source_order':selected,'frozen_actual_first8_physical_case_ids':ids8,'frozen_actual_first8_subset_actual_delivery24':True,'actual_delivery24_subset_current_accepted_set':True,'current_accepted_independent_case_count':len(current),'target_final_independent_case_count':48,'current_final48_complete':len(current)==48,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收','source_authority':ref(P/meta)}
 packages.append({'W':W,'prefix':prefix,'commit':commit,'names':names,'validator':ref(vld),'result':{'returncode':v.returncode,'stdout':v.stdout,'stderr':v.stderr},'source_before':before,'n':n,'source_metadata':x})
O=H/'root_stage1_source152169_F4_actual_frozen8_delivery24_subset48_F6_actual24_subset47_one_pending_checkpoint_1238';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_206.json').exists();adopted=[]
for pkg in packages:
 for name in pkg['names']:
  b=subprocess.check_output(['git','show',f"{pkg['commit']}:{name}"],cwd=pkg['W']);assert (pkg['W']/name).read_bytes()==b;p=R/name;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
 sets['F4' if pkg['n']==152 else 'F6']['source_authority']=ref(R/pkg['prefix']/('metadata/f4-actual-delivery24-root1093-cp200.json' if pkg['n']==152 else 'metadata/authoritative-membership.json'))
now=datetime.datetime.now(datetime.timezone.utc).isoformat();actual=O/'MAIN_ACTUAL_FIRST24_F4_F6_SUBSET_CURRENT_ACCEPTED.json';put(actual,{'schema':'ds02.main.actual-first24-staged-delivery-membership.v1','at_utc':now,'frozen_actual_first8_authority':ref(frozenfile),'current_acceptance_authority':ref(cpfile),'families':sets,'F4_selection':'Frozen Root1093 source order first8; append first16 unseen physicalIDs in cp200 actual accepted order','F4_historical_source_plan_exact24_and_candidate8_preserved_distinct':True,'F4_source_plan_exact24_intersection_actual_delivery24':19,'F6_final48_not_complete_actual47_one_pending':True,'precision_status':'视觉检查通过、数值精度未验收','new_case_credit':0,'main_scientific_payload_IO':False})
controller=root(1069)/'controller-result.json';cr=load(controller);assert cr['status']=='completed' and cr['returncode']==0
proof=O/'actual-staged-memberships-and-original-source-wait-snapshot-preserved.json';put(proof,{'source_packages':[{'n':p['n'],'commit':p['commit'],'source_validator':p['validator'],'validator_result':p['result'],'source_original_bytes_unchanged':True} for p in packages],'adopted_files':adopted,'actual_delivery_memberships':ref(actual),'original_source169_f2_frontier':'Historical frozen pre-terminal wait observation retained verbatim; created_at_utc is package creation, not assertion of current terminal absence','actual_current1069_controller':ref(controller),'actual_current1069_completed0_published_needs_personal170_and_main_QI':True,'source169_original_running_receipts_not_relabelled_completed':True,'F6_original951_pending_visual_decision_retained':True,'new_case_credit':0,'main_scientific_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);z=os.statvfs('/home/jade');cp=copy.deepcopy(cp);cp.update(checkpoint=206,at_utc=now,predecessor=str(cpfile),predecessor_sha256=sha(cpfile),home_free_gib=z.f_bavail*z.f_frsize/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(collections.Counter(x['kind'] for x in ld['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600,new_accepted_decisions=[],previous_goal_turn_classification='Progress: source152169 exact immutable adoption closes realF4actualfirst8subset24subset48 and F6actualfirst8subset24subset47(target48onepending), no extra case credit. User cleanup717 actual0/cumulative534.4GiB retained; accepted274/F5=14.')
cp['actual_progress']['F4_F6_actual_staged_memberships']=ref(proof);cp['next_executable_tasks']=[t for t in cp['next_executable_tasks'] if 'fresh152' not in t and 'fresh169' not in t];cp['authorized_work_state']='Active274/336. Actual F1/F4/F7first24 membership delivered within accepted48; F6actualfirst24 within accepted47(target48lastoriginal951pending); F5actualfirst24 growing14/24. PersonalF2actual1069 fresh170 and failed-storage fresh153195 audits active. Originalrender1068/1109 live.';put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_206.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_206.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: adopt actual F4 and F6 first24 delivery memberships preserving frozen subsets','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':206,'accepted':274,'actual_first24_F4':24,'actual_first24_F6':24,'F6_final_count':47,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
