from pathlib import Path
import json,hashlib,subprocess,runpy,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
BAD={'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'}
def sha(p):
 p=Path(p);assert p.is_file() and p.suffix.lower() not in BAD;return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
O=H/'root_stage1_source157159_seven_actual1085_1087_1104_mother_alias_full801_original138_direct_bed_CPU2_1172';assert not O.exists();O.mkdir();(O/'requests').mkdir()
original=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics/lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_138_stage1_f5_remaining10_full801_downstream_disabled_v1/workers/bed_audit_full801_fresh138.py');assert sha(original)=='89be048da1df6bae49627308edb35a8a1936bc0888259cb5ab3d195307b550e2';api=runpy.run_path(str(original));assert api['CASE_ID']=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1'
controller=O/'batch-bed-controller.py';controller.write_bytes((root(1171)/'batch-bed-controller.py').read_bytes());fair=root(928)/'fair_CPU_dispatch.py';assert sha(fair)=='e2796fb88cc989278bcc4d194493f11e5ded7e6d2fb79ef37349d7ae7d8d679f'
base=load(next((root(1144)/'requests').glob('*.json')));cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_178.json');ids={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};seen=set();adopted=[];reviews=[];qps=[];sources=[]
packages=[(157,'root_followup_157_f5_m095_original138_bed_disabled_v1','3bef73079731e49a00678735c42dd590138d822b',15,2),(159,'root_followup_159_f5_m105_m115_original138_bed_disabled_v1','f1338bdc975a8736365c4aa307f152d0de05c2b2',30,5)]
for fresh,dirname,commit,filecount,casecount in packages:
 prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/'+dirname;P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==filecount
 for name in names:
  raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
 before={name:sha(W/name) for name in names};vld=P/f'scripts/validate_fresh{fresh}.py';rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],capture_output=True,text=True);assert rv.returncode==0 and before=={name:sha(W/name) for name in names};vp=O/f'actual-original{fresh}-readonly-validator.json';put(vp,{'source_validator':ref(vld),'stdout':rv.stdout,'stderr':rv.stderr,'returncode':rv.returncode,'source_bytes_unchanged':True,'main_scientific_payload_IO':False});sources.append({'fresh':fresh,'commit':commit,'files':filecount,'validator':ref(vp)})
 source_requests=sorted((P/'requests').glob('*-original138-bed-disabled-request.json'));assert len(source_requests)==casecount
 for source in source_requests:
  q0=load(source);assert q0['disabled'] and not q0['execution_allowed'] and not q0['launch'];b=load(q0['binding']);tag=b['mother_alias'];pid=b['physical_case_id'];assert b['case_id']==api['CASE_ID'] and not b['next34_identity_adapter_used'] and pid not in ids and pid not in seen;seen.add(pid)
  gate=api['_verify_bound_metadata'](b);assert gate['case_id']==b['case_id'] and gate['physical_case_id']==pid;gp=O/(tag+'-actual-original138-metadata-gate.json');put(gp,gate)
  t=load(b['full_typed_conversion_report']);x=load(b['xmf_manifest']);xr=load(b['xmf_receipt']);tr=load(b['full_typed_receipt']);n=load(b['full_native_receipt']);g=load(b['gencase_receipt']);qa=load(b['initial_qa_receipt']);placement=load(b['initial_qa_report'])
  assert all((a['status'],a['returncode'])==('completed',0) for a in [g,qa,n,tr,xr]);assert all(a['request']['case_id']==b['case_id'] for a in [g,n,tr,xr]);assert n['request']['physical_case_id']==tr['request']['physical_case_id']==x['physical_case_id']==pid
  assert placement['all_basic_placement_checks_pass'] and placement['stage1_basic_placement_proof']=='pass_excluding_numerical_precision' and placement['numerical_precision_result_accepted'] is False
  assert x['frames']==t['frames']==801 and x['particles']==t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed']
  assert all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
  canonical=b['physical_condition_sha256'];legacy=b['source_h5_physical_condition_sha256'];definition=b['source_plan_physical_condition_sha256'];assert x['physical_condition_sha256']==x['canonical_physical_condition_sha256']==n['request']['physical_condition_sha256']==canonical
  assert x['source_h5_physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==legacy and t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0' and t['hash_scopes']['physical_condition']['physical_case_id']==pid
  assert sha(b['source_definition'])==b['source_definition_sha256']==definition;producer_binding=load(b['actual983_binding']);assert x['source_plan_physical_condition_sha256']==producer_binding['source_plan_physical_condition_sha256'] and producer_binding['physical_case_id']==pid
  assert t['output_hdf5']==b['trajectory_h5'] and t['output_sha256']==x['source_h5_sha256']==b['trajectory_h5_sha256'] and x['xdmf_sha256']==sha(b['xdmf'])
  assert xr['input_hashes_at_launch'][b['trajectory_h5']]==xr['input_hashes_after_run'][b['trajectory_h5']]==t['output_sha256']
  fs=t['lifecycle']['frame_summary'];grids=ET.parse(b['xdmf']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(grids)==len(times)==801 and times==[f['time'] for f in fs]==[float(f.find('Time').get('Value')) for f in grids]
  assert times[0]==0 and times[-1]>=16 and all(a<c for a,c in zip(times,times[1:])) and x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
  for i,(f,grid) in enumerate(zip(fs,grids)):
   assert f['frame']==i and f['active_particles']==194427 and f['missing_particles']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658};assert grid.find('Geometry').get('GeometryType')=='XYZ' and grid.find('Geometry/DataItem').get('Dimensions')=='194427 3';vel=next(a for a in grid.findall('Attribute') if a.get('Name')=='velocity');assert vel.get('AttributeType')=='Vector' and vel.find('DataItem').get('Dimensions')=='194427 3'
  assert all(v is None for v in q0['future_output_hashes'].values());md={};removed=[]
  for p,digest in q0['input_sha256'].items():
   if digest is None:
    assert p==b['native_output_root'] and Path(p).is_dir();removed.append({'path':p,'source_expected_hash':None,'reason':'source-only uncomputed native directory SHA preserved in source; original138 metadata gate lists frame names, scientific content comes from immutable actual H5 already verified by typed/XMF producer'})
   elif Path(p).suffix.lower() in BAD:assert p==b['trajectory_h5'] and digest==t['output_sha256'];md[p]=digest
   else:assert sha(p)==digest;md[p]=digest
  for p in [source,Path(q0['binding']),original,controller,fair,gp,vp,root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py']:md[str(p)]=sha(p)
  aid=f'root-stage1-f5-{tag.lower()}-actual983-mother-full801-original138-source{fresh}-bed-root1172';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();q=q0.copy();q.update({k:base[k] for k in ['worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']});q.update(kind='cpu',cpu_threads=2,cpu_task_kind='audit',attempt_id=aid,attempt_root=str(ar),tag=tag,command=[str(L/'.venv/bin/python'),str(original),'--binding',q0['binding'],'--trajectory-h5',b['trajectory_h5'],'--xdmf',b['xdmf'],'--output-dir','{attempt_root}/audit-output'],input_files=sorted(md),input_sha256=md,disabled=False,source_only=False,enabled=True,launch=True,run=True,launch_allowed=True,execution_allowed=True,root_review_required=False,full801_authorized=True,case_credit=0,source_scientific_payload_IO_by_main=False,source_only_directory_hash_role_preserved=removed)
  qp=O/'requests'/(tag+'-enabled-bed-request.json');put(qp,q);qps.append(str(qp));reviews.append({'fresh':fresh,'tag':tag,'case_id':b['case_id'],'physical_case_id':pid,'source_request':ref(source),'source_binding':ref(q0['binding']),'original138_metadata_gate':ref(gp),'actual_typed_report':ref(b['full_typed_conversion_report']),'actual_XMF_manifest':ref(b['xmf_manifest']),'source_definition_role_SHA':definition,'actual_XMF_producer_plan_role_SHA':x['source_plan_physical_condition_sha256'],'native_canonical_scope':canonical,'actual_typed_legacy_scope':legacy,'historical_scope':b['source_h5_legacy_scope_sha256'],'all801_UID_N3_actualtimes_preserved':True,'no_NEXT34_adapter':True,'main_scientific_payload_IO':False,'future_bed_hashes_null':True,'enabled_request':ref(qp),'case_credit':0})
assert len(seen)==len(qps)==7
put(O/'controller-config.json',{'requests':qps,'request_sha256':{p:sha(p) for p in qps},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});put(O/'source157159-seven-mother-full801-bed-independent-adoption-review.json',{'sources':sources,'adopted_files':adopted,'cases':reviews,'original138_kernel_SHA':sha(original),'source_metadata_bytes_preserved':True,'same_mother_case_id_not_dedup_identity':True,'distinct_physical_case_IDs':sorted(seen),'original_worker_logic_and_all_scientific_inputs_unchanged':True,'main_scientific_payload_IO':False,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(a['path']).relative_to(R)) for a in adopted]+[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: bind seven distinct mother-alias F5 full801 cases to original138 bed audit','--',*paths],cwd=R,check=True);print({'bed_requests':7,'main_payload_IO':False,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
