from pathlib import Path
import json,hashlib,datetime,subprocess,os,collections,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02')
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.xml','.xmf','.md','.txt','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
root=lambda n:next(H.glob(f'root*_{n}'));cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_218.json';cp=load(cpp);idxp=root(1254)/'full336-current280-role-aware-registration-progress-index.json';idx=load(idxp);assert idx['source_authoritative_checkpoint']==ref(cpp)
pending=[r for r in idx['cases'] if not r.get('accepted_decision')];assert len(pending)==56 and len({r['physical_case_id'] for r in pending})==56
now=datetime.datetime.now(datetime.timezone.utc).isoformat();rows=[];mismatches=[];states=collections.Counter()
for row in pending:
 qr=row['latest_registered_render_request'];assert sha(qr['path'])==qr['sha256'];q=load(qr['path']);cmd=q['command'];wp=Path(cmd[cmd.index('--request')+1]);w=load(wp);assert q['input_sha256'][str(wp)]==sha(wp)
 assert q['physical_case_id']==w['physical_case_id']==row['physical_case_id'] and q['case_id']==w['case_id']==row['case_id']
 mp=Path(w['manifest']);m=load(mp);assert q['input_sha256'][str(mp)]==sha(mp)
 assert w['expected_frames']==m['frames'] and w['expected_particles']==m['particles'] and w['expected_contact_sheets']==(m['frames']+23)//24
 times=m['actual_time_s'];assert len(times)==m['frames'] and all(a<b for a,b in zip(times,times[1:]))
 lp=Path(row['current_controller_observation']['launch']['path']);lr=load(lp);pid=lr['pid'];ps=Path(f'/proc/{pid}/stat');st=ps.read_text().rsplit(')',1)[1].split() if ps.exists() else None;live=bool(st and st[19]==str(lr['proc_start_ticks']) and st[0]!='Z')
 a=Path(q['attempt_root']);er=a/'execution-receipt.json';receipt=load(er) if er.exists() else None;pub=a/'render/render-publish-receipt.json';report=a/'render/paraview-full-animation-report.json';completed=bool(receipt and receipt.get('status')=='completed' and receipt.get('returncode')==0 and pub.is_file() and report.is_file())
 phase='completed0-published-personal-review-needed' if completed else ('actual-render-running' if receipt and receipt.get('status')=='running' else ('original-controller-live-awaiting-admission' if live and not receipt else 'requires-authoritative-inspection'))
 states[phase]+=1;assert live or completed,(row['physical_case_id'],pid,phase)
 historical={'expected_frames':row['expected_frames'],'expected_contact_sheets':row['expected_contact_sheets']};actual={'expected_frames':w['expected_frames'],'expected_particles':w['expected_particles'],'expected_contact_sheets':w['expected_contact_sheets']};different=any(historical[k]!=actual[k] for k in historical)
 if different:mismatches.append({'physical_case_id':row['physical_case_id'],'historical_index_fields':historical,'actual_loaded_wrapper_contract':actual})
 evidence={'physical_case_id':row['physical_case_id'],'family_id':row['family_id'],'registered_outer_request':qr,'actual_loaded_wrapper':ref(wp),'actual_manifest':ref(mp),'historical_index_expected_fields':historical,'actual_wrapper_expected_fields':actual,'actual_manifest_time_window_s':[times[0],times[-1]],'outer_or_old_index_envelope_is_not_actual_render_selection':different,'controller_launch_record':ref(lp),'live_observation':{'at_utc':now,'pid':pid,'recorded_start_ticks':str(lr['proc_start_ticks']),'observed_start_ticks':st[19] if st else None,'process_state':st[0] if st else None,'same_handle_live':live},'worker_status_observation':{'phase':phase,'receipt_path':str(er),'receipt_status':receipt.get('status') if receipt else None,'receipt_returncode':receipt.get('returncode') if receipt else None,'mutable_receipt_observation_only':True,'published0':completed},'case_credit':0,'no_restart_or_source_mutation':True,'science_payload_IO':False};rows.append(evidence)
 row['original_index_expected_fields_preserved']=historical;row['expected_frames']=actual['expected_frames'];row['expected_contact_sheets']=actual['expected_contact_sheets'];row['expected_particles']=actual['expected_particles'];row['expected_fields_authority']='actual loaded render wrapper checked against its bound completed XMF manifest, separate from original outer envelope';row['actual_wrapper_contract_and_live_observation']=evidence
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);z=os.statvfs('/home/jade');free=z.f_bavail*z.f_frsize/2**30;assert free>=500
gpu=sum(c.get('gpu_seconds',0) for c in ld['charges'])/3600;cpu=sum(c.get('cpu_core_seconds',0) for c in ld['charges'])/3600;counts=collections.Counter(c['kind'] for c in ld['attempts']);assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
assert not list(H.glob('root*_1255')) and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_219.json').exists();O=H/'root_stage1_remaining56_actual_loaded_wrapper_contracts_original_live_handles_F2_F3_frame_envelope_sidecars_1255';O.mkdir()
proof=O/'remaining56-actual-wrapper-contracts-and-original-handle-observations.json';put(proof,{'schema':'ds02.remaining-render.actual-loaded-wrapper-contract-and-live-observation.v1','at_utc':now,'stable_predecessor_checkpoint':ref(cpp),'previous_index_preserved':ref(idxp),'pending_physical_cases':56,'actual_wrapper_contracts_verified':len(rows),'historical_envelope_discrepancy_count':len(mismatches),'historical_envelope_discrepancies':mismatches,'actual_phase_counts':dict(states),'cases':rows,'case_credit':0,'original_loaded_sources_and_processes_unchanged':True,'old_receipts_hashes_not_promoted_to_immutable_future_authorities':True,'main_scientific_payload_IO':False})
snap=O/'resource-ledger-frozen.json';snap.write_bytes(raw);cp=copy.deepcopy(cp);cp.update(checkpoint=219,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: previous218 accepted280; independently bind all56 pending originalrequests to actual loadedwrapper/XMF contracts and live PID/startticks, correct misleading historical frame/contact envelopes in a new immutable index; original sources unchanged.',authorized_work_state='Active280/336. Two original F5 renders still live,54 controllers await admission. Child fresh175 prepares actual F1/F4/F7 final48 delivery, fresh198 F5 original1161 personal visual after publish; physical scope and precision limits retained.')
cp['actual_progress']['remaining56_actual_wrapper_contracts_and_same_live_handles']=ref(proof);newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_219.json';put(newcp,cp)
idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxp),new_case_credit=0,actual_pending_wrapper_contract_snapshot=ref(proof));put(O/'full336-current280-actual-wrapper-contract-role-aware-registration-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: bind all remaining render contracts and preserve original live handles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':219,'accepted':280,'remaining':56,'wrapper_contract_corrections':len(mismatches),'states':dict(states),'Home_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
