from pathlib import Path
import json,hashlib,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';O=H/'root_stage1_F6_actual722_24_full241_N3_dynamic_ready_independent_family_dispatch_audit_917';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_120.json');accepted=[load(p) for p in cp['accepted_decisions']];ids={x.get('physical_case_id',x['case_id']) for x in accepted};digests={x['physical_condition_sha256'] for x in accepted};regp=next(H.glob('root*_722'))/'actual-all24-XMF-terminal-registration.json';reg=load(regp);assert len(reg['cases'])==24 and reg['actual_completed0_N3_pass']==24;seen=set();hashes=set();rows=[]
for c in reg['cases']:
 cid=c['case_id'];assert cid not in ids and cid not in seen;seen.add(cid)
 for filekey,hashkey in [('registered_request','registered_request_sha256'),('registered_binding','registered_binding_sha256'),('actual_receipt','actual_receipt_sha256'),('actual_manifest','actual_manifest_sha256'),('actual_case_xmf','actual_case_xmf_sha256')]:assert sha(c[filekey])==c[hashkey]
 r=load(c['actual_receipt']);assert (r['status'],r['returncode'])==('completed',0) and r['request_sha256']==c['registered_request_sha256'];m=load(c['actual_manifest']);t=load(m['conversion_report']);assert sha(m['conversion_report'])==m['conversion_report_sha256'];assert t['conversion_status']=='completed' and t['frames']==241 and t['particles']==417505 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=12 and t['time_evidence']['strictly_increasing'];assert t['output_sha256']==m['source_h5_sha256']==m['producer_h5_sha256_attestation'];assert m['frames']==241 and m['particles']==417505 and m['source_h5_read_only'];g=ET.parse(c['actual_case_xmf']).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(g)==241 and all(x.find('Geometry/DataItem').get('Dimensions')==x.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='417505 3' for x in g)
 receipts={'xmf':ref(c['actual_receipt'])}
 for k in ['typed_receipt','native_receipt']:
  p=m[k];q=load(p);assert sha(p)==m[k+'_sha256'] and (q['status'],q['returncode'])==('completed',0);receipts[k]=ref(p)
 own=load(m['classified_owner']);assert sha(m['classified_owner'])==m['classified_owner_sha256'];digest=hashlib.sha256(json.dumps(own['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert digest==own['physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==m['physical_condition_sha256']==m['classified_physical_condition_sha256'];assert digest not in digests and digest not in hashes;hashes.add(digest);src=load(m['source_canonical_owner']);assert sha(m['source_canonical_owner'])==m['source_canonical_owner_sha256'];sd=hashlib.sha256(json.dumps(src['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert sd==src['physical_condition_sha256']==m['source_canonical_physical_condition_sha256'];assert own['physical_binding']['parameters']==src['physical_binding']['parameters'] and own['physical_binding']['geometry']==src['physical_binding']['geometry'];assert c['actual_input_before_after_equal']
 rows.append({'case_id':cid,'actual_physical_condition_sha256':digest,'source_canonical_physical_condition_sha256':sd,'source_plan_condition_sha256':m['source_plan_condition_sha256'],'classified_owner':ref(m['classified_owner']),'source_owner':ref(m['source_canonical_owner']),'actual_completed_receipts':receipts,'typed_report':ref(m['conversion_report']),'manifest':ref(c['actual_manifest']),'xmf':ref(c['actual_case_xmf']),'producer_H5_sha256':t['output_sha256'],'producer_H5_path':t['output_hdf5'],'H5_stat_size_bytes':Path(t['output_hdf5']).stat().st_size,'source_canonical_and_classified_and_plan_scopes_distinct':True,'actual_frames':241,'particles':417505,'last_time_s':t['time_evidence']['last_s'],'renderer_not_yet_completed':True,'visual_not_accepted':True,'case_increment':0,'q_n':'not_granted','physical_parameters':own['physical_binding']['parameters']})
oldp=next(H.glob('root*_860'))/'controller-launch-process.json';old=load(oldp);p=Path('/proc')/str(old['pid']);f=(p/'stat').read_text().split(') ',1)[1].split();assert f[0]!='Z' and f[19]==old['proc_start_ticks'];assert sha(old['controller'])==old['controller_sha256'];assert not list(oldp.parent.glob('*request.json')) and not list((oldp.parent/'requests').glob('*request.json'))
out={'schema':'ds02.f6.actual24-full241-own-dynamic-assets-ready.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_registration':ref(regp),'accepted_checkpoint':ref(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_120.json'),'actual_cases':24,'all24_unique_actual_canonical_bindings':True,'all24_native_typed_XMF_completed0':True,'source_H5_scientific_payload_not_read_hashed_or_copied_by_main':True,'actual860_controller_same_handle_live':ref(oldp),'actual860_registered_requests_count':0,'current860_cross_family_F4_whole_batch_gate':'present in original immutable controller; new independent bounded renderer successor should consume actual722 directly after separate review/admission','retired_old_controller':False,'new_workers_started':0,'new_visual_case_credit':0,'cases':rows};(O/'actual-ready24-independent-dispatch-audit.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');(O/'audit-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'ready_full241_cases':24,'registered860_renderer_requests':0,'science_payload_read':False}))
