from pathlib import Path
import json,hashlib,datetime,collections,subprocess,os,ast
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_actual135_full_F1_48_F2_24_GenCase_QA_F5_10native_liveGPU_checkpoint_815';O.mkdir(exist_ok=False)
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_102.json';cp=load(prev);new=[]
for n in [798,799,800,802,803,805,806,807,810,813,814]:new+=load(root(n)/'actual-integration-review.json')['decisions']
accepted=cp['accepted_decisions']+new;rows=[load(p) for p in accepted];assert len(accepted)==135 and len(new)==29;assert len({x.get('physical_case_id',x['case_id']).replace('F4_DROP_B08_','F4_DROP_') for x in rows})==135 and len({x['physical_condition_sha256'] for x in rows})==135;counts=dict(collections.Counter(x['family_id'] for x in rows));assert counts=={'F1':48,'F2':16,'F3':8,'F4':18,'F5':4,'F6':24,'F7':17};assert all(load(p)['status']=='visual-approved-by-delegated-agent' and not load(p)['main_personally_viewed_pngs'] for p in new)
controllers=[]
for n in [773,774,783,793,796,804,808,809,811,812]:
 p=root(n);c=load(p/'controller-launch-process.json');proc=Path('/proc')/str(c['pid']);live=False;state=None
 if proc.exists():
  f=(proc/'stat').read_text().split(') ',1)[1].split();assert f[19]==c['proc_start_ticks'];state=f[0];live=state!='Z'
  if live:assert c['controller'].encode() in (proc/'cmdline').read_bytes().split(b'\0')
 assert sha(c['controller'])==c['controller_sha256'];result=p/'controller-result.json';entry={**c,'number':n,'actual_handle_live':live,'actual_state':state,'actual_result':ref(result) if result.exists() else None}
 if not live and not result.exists():assert n==811 and not list((p/'requests').glob('*.json'));entry['actual_prelaunch_failure_preserved']=ref(root(812)/'actual-prelaunch-failure-and-known-literal-repair.json')
 controllers.append(entry)
assert load(root(804)/'controller-result.json')['actual_GenCase_pass_count']==24 and load(root(809)/'controller-result.json')['actual_initial_QA_pass_count']==24 and load(root(808)/'controller-result.json')['actual_full801_native_pass_count']==10
requests=[]
for n in [796,808,812]:
 for qp in list(root(n).glob('*request.json'))+list((root(n)/'requests').glob('*request.json')):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json'
  if not rp.exists():continue
  r=load(rp);proc=Path('/proc')/str(r.get('pid'));live=proc.exists() and (proc/'stat').read_text().split(') ',1)[1].split()[0]!='Z';entry={'root':n,'request':ref(qp),'actual_receipt':ref(rp),'status':r['status'],'returncode':r.get('returncode'),'pid':r.get('pid'),'actual_handle_live':live,'independent_case_increment':0}
  if r['status']=='running' and not live:entry['observation']='process exited before receipt finalization; retained for next same-handle poll, no restart'
  requests.append(entry)
assert any(x['root']==812 and x['status'] in ['running','completed'] for x in requests)
lp=D/'runtime/resource-ledger.json';b=lp.read_bytes();l=json.loads(b);assert l['limits']==cp['limits'] and l['adopted_at_utc']==cp['adopted_at_utc'] and l['deadline_utc']==cp['deadline_utc'];assert sum(x.get('cpu_threads',0) for x in l['reservations'])<=64;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize;assert free>=500*1024**3
for p,expected in [(L/'scripts/ds_data02_runtime_v2.py','5098262e26dc5560487760181466b0a93a0e66239e5e54047dce5e761ae67a60'),(L/'scripts/ds_data02_strict_dispatch_v1.py','81bdd60e5de4fec362807043ab632864405f1667a0658560fb9349025aab75ec'),(H/'root_stage1_home_floor_inventory_dispatch_142/launch.py','708c4c83d22257f7b59bad93cd19915fb66a199a2a5b1291d6ada71bb467ea76'),(H/'root_stage1_native_home_floor_eight_solver_dispatch_230/launch.py','7f703fb94e17c2e2800873f4fcc021f9cd5f8201076afd8e10e3bc6a2d03396e')]:assert sha(p)==expected
inventory=subprocess.run(['nvidia-smi','--query-compute-apps=gpu_uuid,pid,used_memory','--format=csv,noheader'],capture_output=True,text=True,check=True).stdout;put(O/'actual-readonly-GPU-process-inventory.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'compute_apps':inventory,'foreign_processes_protected':True,'foreign_process_outputs_not_inspected':True})
progress={'new_unique_delegated_visual_cases':{'total':29,'accepted_per_family_increment':{'F1':9,'F2':6,'F4':6,'F5':2,'F7':6},'metadata_decisions':[ref(p) for p in new],'Root_personal_PNG_review_claim':False},'F1_first48_complete_visually_accepted':True,'F2_four_corner_visual_release':ref(root(803)/'actual-integration-review.json'),'F2_two_RX046_already_accepted_cases_no_duplicate_credit':load(root(803)/'actual-integration-review.json')['already_accepted_case_supporting_sidecars_no_duplicate_credit'],'F2_source801_actual_registered24':ref(root(801)/'actual-source-generation-review.json'),'F2_actual24_GenCase_completed0':ref(root(804)/'controller-result.json'),'F2_actual24_initialQA_completed0':ref(root(809)/'controller-result.json'),'F2_actual_native_controller812':ref(root(812)/'controller-launch-process.json'),'F2_original811_prelaunch_literal_failure_preserved':ref(root(812)/'actual-prelaunch-failure-and-known-literal-repair.json'),'F5_endpoint_full801_visual_release':ref(root(807)/'actual-integration-review.json'),'F5_actual10_new_full801_native_completed0':ref(root(808)/'controller-result.json'),'F5_endpoint_bed_and_initialQA_direct_metadata_crosscheck':ref(root(808)/'actual-endpoint-audit-crosscheck.json'),'F3_full836_priority_render_controller796':ref(root(796)/'controller-launch-process.json'),'live_and_terminal_controllers':controllers,'actual_scientific_receipt_observations':requests,'renderer_global_cap':2,'shared_CPU_reservation_cap':64,'GPU_native_idle_UUID_parallel_cap':7,'scientific_payloads_opened_or_hashed_by_main':False,'precision_or_QN_not_granted':True,'actual_GPU_inventory':ref(O/'actual-readonly-GPU-process-inventory.json')}
out={k:cp[k] for k in ['schema','target_stage1_independent_cases','numeric_reference_accepted_independent_products','precision_status','limits','user_cumulative_window','latest_user_resource_window_confirmation','deadline_utc','adopted_at_utc','effective_visual_review_policy','effective_agent_model_policy','unmodified_guards']};out.update(checkpoint=103,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(prev),predecessor_sha256=sha(prev),historical_records_preserved_by_reference_no_repeated_snapshot_expansion=True,authorized_work_state='active; actual native batch and priority renderer continue; no user approval blocker',previous_goal_turn_classification='progress: resource-window authorization reaffirmation saved in f385119a without resetting ledger; this continuation delivered29 visual cases plus24 actual GenCase/QA and10 F5 fullnative cases',stage1_visual_accepted_complete_independent_cases=135,accepted_per_family=counts,accepted_decisions=accepted,new_accepted_decisions=new,attempt_counts=dict(collections.Counter(x['kind'] for x in l['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in l['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in l['charges'])/3600,active_reservations=l['reservations'],ledger_sha256_at_checkpoint=hashlib.sha256(b).hexdigest(),home_free_gib=free/1024**3,actual_progress=progress,source_agents={'/root/production_recovery':'fresh097/098 remaining3 F2 expansion stock then old3 offsets; prioritize F3 corners when actual836 render0','/root/f6_endpoint_initial_qa':'fresh115 next2 Root638 gap.24/+x/-y complete1201 visual review','/root/f5_bed_recovery':'fresh138 actual808 ten complete801 downstream typed/XMF/bed/render source, future hashes NULL; no science payload reads'},next_executable_tasks=['Verify actual812 24 F2 native0/full401 and bind downstream to each real native attempt, no source count fabrication or duplicate credit','Adopt fresh138 exact source and launch10 F5 actual808 typed/XMF/bed/render; then delegated visual review, no prematurecredit','F3 actual796 full836 fourcorners0/delegated visual/Root acceptance releases20 independent GPU native cases; watch owned773 futuredispatch resume without signaling scientificworkers','Complete F2 existing expansion andfirst8 offset visual stock to24; fullnew24native/downstream extends48','Continue F7 alreadyexisting complete48 pipeline visual queue, nextA037P5/A038P5 afterfresh137; no more F7 native solves required','F4 visuallypendingexistingstock plus Root77324 render backlog; F6 Root77424 full241 renders follows773','F5 aftercurrent12 amplitude/time cases plus2 earlieraccepted, generate34 further independent source conditions inside approved.85..1.15/.8..1.0 domain toreach48; retainT120longerwindowhold','All current products explicitly visualpass/numericalprecisionnotaccepted; preserve originaldeadline2026-10-14T07:23:48Z andHome500GiB'])
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_103.json',out);(O/'checkpoint-validation-and-build.py').write_bytes(Path(__file__).read_bytes())
scriptmap={798:'/tmp/ds02-root798-f1-adopt.py',799:'/tmp/ds02-root799-f4-adopt.py',800:'/tmp/ds02-root800-f1-original.py',801:'/tmp/ds02-root801-source-generation.py',802:'/tmp/ds02-root802-f4-adopt.py',803:'/tmp/ds02-root803-f2-adopt.py',805:'/tmp/ds02-root805-f1-original.py',806:'/tmp/ds02-root806-f7-adopt.py',807:'/tmp/ds02-root807-f5-adopt.py',810:'/tmp/ds02-root810-f4-adopt.py',813:'/tmp/ds02-root813-f2-adopt.py',814:'/tmp/ds02-root814-f7-adopt.py'}
for n,sp in scriptmap.items():
 dst=root(n)/'root-preparation-and-validation.py'
 if dst.exists():assert dst.read_bytes()==Path(sp).read_bytes()
 else:dst.write_bytes(Path(sp).read_bytes())
paths=[]
for n in range(798,816):
 for p in root(n).rglob('*'):
  if p.is_file() and p.suffix in {'.json','.py','.md'} and '__pycache__' not in p.parts:
   if p.suffix=='.json':load(p)
   if p.suffix=='.py':ast.parse(p.read_text())
   paths.append(str(p.relative_to(R)))
for fam,ns in [('F3',[88,89,90,91,92,93,94,95,96]),('F6',[112,113,114]),('F5',[133,134,135,136,137])]:
 for n in ns:
  p=next((L/'campaigns/ds-data-02/families'/fam/'handoff_20261003').glob(f'root_followup_{n:03d}_*'))
  for f in p.rglob('*'):
   if f.is_file() and f.suffix in {'.json','.py','.md'} and '__pycache__' not in f.parts:paths.append(str(f.relative_to(R)))
paths.append(str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_103.json').relative_to(R)));assert not subprocess.run(['git','diff','--cached','--name-only'],cwd=R,capture_output=True,text=True,check=True).stdout.strip();subprocess.run(['git','add','-f','--',*paths],cwd=R,check=True);r=subprocess.run(['git','diff','--cached','--check'],cwd=R,text=True,capture_output=True);assert r.returncode==0,r.stdout+r.stderr;subprocess.run(['git','commit','-m','Integrate135 visual cases, complete F1 first48 and launch F2/F5 native batches'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'checkpoint':103,'accepted':135,'families':counts,'newvisualcases':29,'localcommit':subprocess.run(['git','rev-parse','HEAD'],cwd=R,capture_output=True,text=True,check=True).stdout.strip(),'scopedfiles':len(paths),'attempts':out['attempt_counts'],'chargedGPUh':out['gpu_hours_charged'],'chargedCPUcoreh':out['cpu_core_hours_charged'],'home_free_gib':out['home_free_gib']}))
