#!/usr/bin/env python3
"""Read-only validator for F6 fresh189; no scientific payload IO."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ALLOWED={".json",".xml",".xmf",".png"}; FORBIDDEN=(".h5",".hdf5",".bi4",".csv",".dat",".vtk",".vtu",".vtp",".pvd",".raw")
CASE="F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025"; CANON="13c383a2ba67e520613cacb83f595a1c0745b2ac8ad2c67c9c6beaf43a6e4640"; LEGACY="a92da26df8424649239124012c23f1f893327573a302dc6914e962ceec5a0d90"; PLAN="c503e879744b5f3e533ebf193b888d7cea57c3cf8a3e0a5c64a831ba8013fc41"; QISHA="6cb873fe6ad08cd9534c3f7c0c937501cb9aabf0457093d21eb4c4e1312710ca"; INIT={"fixed":73441,"moving":0,"floating":16384,"fluid":327680,"total":417505}; TERM={"fixed":73441,"moving":0,"floating":16384,"fluid":327677,"total":417502}
def sha(p):
 h=hashlib.sha256(); f=p.open("rb")
 for b in iter(lambda:f.read(1024*1024),b""):h.update(b)
 f.close(); return h.hexdigest()
def ref(x,kind=None):
 assert isinstance(x,dict) and {"path","sha256","bytes","kind"}<=set(x); p=Path(x["path"]); assert p.is_file(),p; assert p.suffix.lower() in ALLOWED and not any(str(p).lower().endswith(s) for s in FORBIDDEN),p; assert sha(p)==x["sha256"],(p,"sha"); assert p.stat().st_size==x["bytes"],(p,"size");
 if kind: assert x["kind"]==kind
 return p
def completed(x):
 d=json.loads(ref(x,"metadata").read_text()); assert d.get("status")=="completed" and d.get("returncode")==0; return d
def visual(x,files):
 assert x["kind"]=="visualization" and x["viewed"] is True; p=Path(x["path"]); assert p.is_file() and p.suffix.lower()==".png"; assert p.stat().st_size==x["bytes"]; root=p.parent.parent if p.parent.name=="frames" else p.parent; rel=str(p.relative_to(root)); assert rel in files and files[rel]["sha256"]==x["producer_sha256"] and files[rel]["bytes"]==x["bytes"]
def main():
 ap=argparse.ArgumentParser(); ap.add_argument("--package",type=Path,default=Path(__file__).parents[1]); pkg=ap.parse_args().package; d=json.loads((pkg/"metadata/personal-visual-decision.json").read_text()); assert d["schema"]=="ds02.f6.fresh189.f6-last-personal-visual-review.v1" and d["fresh_id"]=="fresh189" and d["family_id"]==d["assigned_family"]==d["actual_family"]=="F6"; assert d["model"]=="gpt-5.6-luna" and d["reasoning_effort"]=="max" and d["recursive_delegation"] is False; p=d["predecessor"]; assert json.loads(ref(p,"metadata").read_text())["fresh_id"]=="fresh188" and p["must_remain_unchanged"] is True
 c=d["case"]; assert c["case_id"]==c["physical_case_id"]==CASE and c["native_canonical_physical_condition_sha256"]==CANON and c["typed_xmf_legacy_producer_scope_sha256"]==LEGACY and c["source_plan_condition_sha256"]==PLAN and c["source_plan_physical_condition_sha256"] is None; s=c["scope_roles"]; assert not s["equality_claimed"] and not s["mass_equality_claimed"]; assert s["native_source_plan_condition_sha256"]=={"present":True,"value":PLAN} and s["xmf_source_plan_condition_sha256"]=={"present":True,"value":PLAN} and s["native_source_plan_physical_condition_sha256"]=={"present":False,"value":None} and s["xmf_source_plan_physical_condition_sha256"]=={"present":False,"value":None}; assert c["declared_counts"]==INIT and c["terminal_counts"]==TERM and c["dimension"]==3 and c["expected_frames"]==241 and c["actual_time_s"]==[0.0,12.00014173182893] and c["physical_mass_kg"]==128 and c["native_support_mass_kg"]==256; assert c["state0_declared_angular_velocity_rad_s"]==[0.0825,0.11,0.165] and c["state0_observed_angular_velocity_rad_s"]==[0.082500003,0.11,0.16500001]; o=c["lifecycle_omissions"]; assert (o["final_missing_particles"],o["max_missing_per_frame"],o["first_missing_frame"],o["frames_with_any_missing_particle"],o["cumulative_particle_frame_omissions"])==(3,3,7,234,700) and o["missing_location_state_cause_unknown"] is True and o["strict_container_guarantee"] is False
 r=d["render_product"]; assert (r["execution_status"],r["publish_status"],r["frames"],r["source_frames"],r["all_frames_rendered"],r["actual_times_preserved_exactly"],r["nonfinite_active_states"],r["source_h5_opened_or_hashed_by_wrapper"])==("completed/0","published_after_atomic_rename",241,241,True,True,0,False); assert r["first_frame_summary"]["counts"]=={"fixed":73441,"moving":0,"floating":16384,"fluid":327680,"unknown":0} and r["terminal_frame_summary"]["counts"]=={"fixed":73441,"moving":0,"floating":16384,"fluid":327677,"unknown":0}
 q=d["decision"]; assert q["status"]=="visual-approved-by-delegated-agent" and q["case_credit"]==0 and not q["global_acceptance"] and q["precision_status"]=="not accepted" and not q["q_n_granted"] and not q["q_e_granted"] and not q["production_approval"] and not q["strict_container_guarantee"]; assert d["source_boundaries"]=={"science_payload_read":False,"science_payload_hashed":False,"science_jobs_started":False,"shared_registry_or_ledger_written":False,"historical_source_changed":False,"model_substitution":False,"recursive_delegation":False}
 ev=d["evidence"]; [ref(x) for x in ev.values()]; [completed(ev[k]) for k in ("gencase_receipt","initial_qa_receipt","native_receipt","state0_receipt","typed_receipt","h5_audit_receipt","xmf_receipt","rigid_export_receipt","render_receipt")]; qi=json.loads(Path(ev["main_qi_proof"]["path"]).read_text()); assert ev["main_qi_proof"]["sha256"]==QISHA and qi["case_id"]==CASE and qi["frames"]==241 and qi["particles"]==417505 and qi["all241_geometry_velocity_N3_actual_times_UID_identity_finite_active_states_verified"] and not qi["all_native_UIDs_active_each_frame"] and not qi["strict_container_guarantee"] and not qi["q_n_granted"] and not qi["q_e_granted"] and qi["case_credit"]==0 and not qi["scientific_payload_IO"]; assert qi["lifecycle_omissions"]["final_missing_particles"]==3 and qi["lifecycle_omissions"]["first_missing_frame"]==7 and qi["lifecycle_omissions"]["cumulative_particle_frame_omissions"]==700 and qi["native_canonical_condition_sha256"]==CANON and qi["typed_XMF_actual_producer_condition_sha256"]==LEGACY and qi["source_plan_condition_field_not_substituted_into_absent_physical_plan_field"] is True
 n=qi["actual_native_XMF_plan_field_namespaces"]; assert n["native"]=={"source_plan_condition_sha256":{"present":True,"value":PLAN},"source_plan_physical_condition_sha256":{"present":False,"value":None}} and n["XMF"]=={"source_plan_condition_sha256":{"present":True,"value":PLAN},"source_plan_physical_condition_sha256":{"present":False,"value":None}}; pub=json.loads(Path(ev["render_publish_receipt"]["path"]).read_text()); assert pub["status"]=="published_after_atomic_rename" and pub["source_h5_opened_or_hashed_by_wrapper"] is False; report=json.loads(Path(ev["render_report"]["path"]).read_text()); assert report["frames"]==report["source_frames"]==241 and report["all_frames_rendered"] and report["actual_times_preserved_exactly"] and report["native_identity_axis_preserved"] and report["nonfinite_active_states"]==0; fs=report["frame_diagnostics"]; assert len(fs)==241 and fs[0]["frame"]==0 and fs[-1]["frame"]==240; assert fs[0]["missing"]==0 and fs[0]["active"]==417505 and fs[0]["type_counts_active"]=={"fixed":73441,"moving":0,"floating":16384,"fluid":327680,"unknown":0}; assert fs[-1]["missing"]==3 and fs[-1]["active"]==417502 and fs[-1]["type_counts_active"]=={"fixed":73441,"moving":0,"floating":16384,"fluid":327677,"unknown":0}; assert all(x["identity_axis_preserved"] and x["finite_positions_active"] and all(v["finite_active"] and v["nonfinite_active"]==0 for v in x["finite_fields"].values()) for x in fs); rigid=json.loads(Path(ev["rigid_export_report"]["path"]).read_text()); assert rigid["status"]=="completed" and rigid["returncode"]==0 and rigid["case"]["physical_case_id"]==CASE; rp=rigid["parse"]; assert rp["part_row_count"]==241 and rp["row_ordinals"]==list(range(241)) and len(rp["official_times_s"])==241 and rp["rigid_fields_finite_rows"]==241 and rp["strictly_increasing_time"] and rp["native_time_comparison"]["max_abs_delta_s"]==4.9897863618753036e-12
 v=d["visual_review"]; assert v["personally_viewed_with"]=="view_image" and len(v["contact_sheets"])==v["contact_sheet_count"]==11 and len(v["key_frames"])==v["key_frame_count"]==10; files={x["relative_path"]:x for x in pub["files_excluding_receipt"]}; [visual(x,files) for x in v["contact_sheets"]+v["key_frames"]]; assert [x["frame"] for x in v["key_frames"]]==[0,1,30,60,90,120,150,180,210,240]; assert all(x["sheet_index"]==i and x["frame_start"]==i*24 and x["frame_end"]==min(i*24+23,240) for i,x in enumerate(v["contact_sheets"])); print("fresh189 validation PASS: Root951 completed/0 atomic publish; 241 frames; 11 contacts + 10 keys viewed; scopes/lifecycle limits preserved; no scientific payload IO; case credit 0")
if __name__=="__main__": main()
