from pathlib import Path
import json,hashlib,datetime,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
rows=[]
for original,pid,start,out in [(1126,517385,212884127,1315),(1187,520260,212902190,1316)]:
 F=root(original);qp=F/'enabled-full801-render-request.json';q=load(qp);oldp=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';review=load(oldp)
 for key in ['actual_bed_receipt','actual_bed_report','actual_typed_receipt','actual_typed_report','actual_XMF_receipt','actual_XMF_manifest']:
  e=review[key];assert ref(e['path'])==e
 t=load(review['actual_typed_report']['path']);x=load(review['actual_XMF_manifest']['path']);bq=load(review['actual_bed_receipt']['path'])['request'];binding=load(bq['binding']);native=t['source_provenance']['solver_receipt'];assert ref(native['path'])==native;n=load(native['path']);nq=n['request'];assert n['status']=='completed' and n['returncode']==0 and nq['case_id']==q['case_id'] and nq['physical_case_id']==q['physical_case_id']==x['physical_case_id']
 canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert canonical==review['source_canonical_scope']==x['physical_condition_sha256'] and legacy==review['actual_H5_legacy_scope']==x['source_h5_physical_condition_sha256']
 source=Path(binding['source_definition']);assert sha(source)==binding['source_definition_sha256']==binding['source_plan_physical_condition_sha256']==bq['input_sha256'][str(source)];assert len({canonical,legacy,sha(source)})==3
 scopes={'native':{k:{'present':k in nq,'value':nq.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']},'XMF':{k:{'present':k in x,'value':x.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']},'bed_source_definition':ref(source),'binding_source_definition_field_present':True}
 if original==1126:assert scopes['native']['source_plan_physical_condition_sha256']=={'present':True,'value':canonical} and x['source_plan_physical_condition_sha256']==canonical
 else:assert scopes['native']['source_plan_physical_condition_sha256']=={'present':False,'value':None} and x['source_plan_physical_condition_sha256']==sha(source)
 assert t['frames']==x['frames']==801 and t['particles']==x['particles']==194427 and t['conversion_status']=='completed'
 st=Path(f'/proc/{pid}/stat');actual=int(st.read_text().rsplit(')',1)[1].split()[19]) if st.exists() else None;assert actual==start
 rows.append({'original_render_root':original,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'registered_original_render_request':ref(qp),'existing_full801_previsual_own_proof':ref(oldp),'actual_native_receipt':native,'native_condition_sha256':canonical,'typed_legacy_scope_sha256':legacy,'actual_native_XMF_bed_SourceDef_namespaces':scopes,'same_current_PV_pid':pid,'same_current_PV_startticks':actual,'same_current_PV_live':True,'private_PNG_filename_count_stat_only':sum(1 for p in Path(f'/tmp/ds02-visual-render-cache-root{original}').rglob('frame_*.png')),'original_authoritative_terminal_present':(F/'controller-result.json').exists(),'future_own_QI_output_root_reserved':out,'future_own_QI_proof_present':False,'new_case_credit':0,'main_scientific_payload_IO':False})
helper=Path('/tmp/ds02-F5-next1126-1187-own-full801-QI.py');compile(helper.read_text(),str(helper),'exec');O=H/'root_stage1_nextF5_original1126_1187_live_exact_native_XMF_SourceDef_namespaces_durable_future801QI_preparation_1318';assert not O.exists();O.mkdir();hp=O/'after_original_terminal_full801_own_QI.py';hp.write_bytes(helper.read_bytes())
proof={'schema':'ds02.main.nextF5.live-preflight-and-durable-future-QI.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stable_current_checkpoint':ref(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_245.json'),'actual_original_live_rows':rows,'prepared_after_terminal_QI_source':ref(hp),'execution_entrypoints':[['python3','-B',str(hp),'1126','1315'],['python3','-B',str(hp),'1187','1316']],'execute_only_after_same_original_terminal_and_atomic_publication':True,'helper_executed_scientific_work':False,'new_case_credit':0,'new_visual_review':False,'Q_N':0,'Q_E':0,'main_scientific_payload_IO':False}
(O/'actual-original1126-1187-current-live-scope-preflight-and-futureQI-entrypoints.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n');(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('两个真实正在运行的原始 F5 全801渲染，预核各自 native / typed legacy / XMF / bed SourceDef 命名空间。1126 case_id含NEXT34后缀，native与XMF plan为canonical；1187 native plan实际缺失，XMF/bed plan为SourceDef FILE SHA。本包不声称渲染已完成或视觉通过，真实终结发布后执行准备好的独立QI入口，输出保留给Root1315/1316。不读取科学载荷、不启动新科学任务、不新增案例信用。\n');rel=str(O.relative_to(R));subprocess.run(['git','add','--',rel],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: preserve nextF5 live scope preflight and durable after-terminal QI entries','--',rel],cwd=R,check=True);print({'prepared':str(O),'actual_live_originals':[r['original_render_root'] for r in rows],'new_case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
