from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
old=root(990);a=load(old/'actual-progress.json');assert len(a['results'])==1 and a['results'][0]['status'] is None and 'Strict dispatch guard must be a digest-bound input' in a['results'][0]['stderr_tail'] and not Path(a['results'][0]['actual_receipt']).exists()
O=H/'root_stage1_F3_actual990_prelaunch_strict_binding_failure_XMF2_actual142_grounded_repair1_997';O.mkdir(exist_ok=False);(O/'requests').mkdir();controller=O/'batch-xmf-controller.py';controller.write_bytes((old/'batch-xmf-controller.py').read_bytes());proof=O/'actual990-strict-prelaunch-failure-and-source-binding-repair1.json';put(proof,{'actual_original_failure':ref(old/'actual-progress.json'),'failure_class':'Strict prelaunch guard rejected missing digest-bound strict dispatcher source; no scientific process or actual receipt existed','repair_number':1,'actual_strict_source':ref(L/'scripts/ds_data02_strict_dispatch_v1.py'),'actual_runtime_source':ref(L/'scripts/ds_data02_runtime_v2.py'),'checks_not_disabled_or_modified':True,'original990_requests_and_binding_bytes_preserved':True,'original104_scientific_worker_and_all_sourceH5_input_scopes_frames_counts_unchanged':True,'case_credit':0})
assert sha(L/'scripts/ds_data02_strict_dispatch_v1.py')=='81bdd60e5de4fec362807043ab632864405f1667a0658560fb9349025aab75ec'
qs=[]
for sp in load(old/'controller-config.json')['requests']:
 q=load(sp);assert not Path(q['attempt_root']).exists();md=q['input_sha256'].copy()
 for p in [L/'scripts/ds_data02_strict_dispatch_v1.py',L/'scripts/ds_data02_runtime_v2.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json',controller,proof,Path(sp)]:md[str(p)]=sha(p)
 q.update(attempt_id=q['attempt_id'].replace('root990','root997-strict-binding-repair1'),attempt_root=q['attempt_root'].replace('root990','root997-strict-binding-repair1'),input_files=sorted(md),input_sha256=md,root_original_prelaunch_rejected_request=ref(sp),root_strict_source_binding_repair1=ref(proof))
 assert not Path(q['attempt_root']).exists();qp=O/'requests'/(q['case_id']+'-enabled-XMF-request.json');put(qp,q);qs.append(str(qp))
put(O/'controller-config.json',{'requests':qs,'request_sha256':{p:sha(p) for p in qs},'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: preserve actual strict prelaunch rejection and bind unchanged guard for two F3 XMF successors','--',*paths],cwd=R,check=True);print({'root':str(O),'cases':len(qs),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
