from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');O=next(H.glob('root*_1108'));prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_179_f5_original138_bed_and_m090_t095_render_disabled_v1';commit='173988a931d97355c16abf6adba6c0c983ab0d66';P=W/prefix
load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
assert not (O/'controller-config.json').exists();qs=sorted((O/'requests').glob('*-enabled-bed-request.json'));assert len(qs)==4;tags={load(p)['tag'] for p in qs};assert tags=={'M092_T085','M092_T095','M094_T085','M098_T085'}
for p in qs:
 q=load(p);assert not Path(q['attempt_root']).exists();b=load(q['binding']);t=load(b['full_typed_conversion_report']);x=load(b['xmf_manifest']);assert b['source_h5_physical_condition_sha256']==x['source_h5_physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256'];assert q['input_sha256'][b['trajectory_h5']]==t['output_sha256']
 for f,h in q['input_sha256'].items():
  if Path(f).suffix.lower() not in {'.h5','.bi4','.dat','.csv','.vtk'}:assert sha(f)==h
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==24
for name in names:assert (R/name).read_bytes()==(W/name).read_bytes()==subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W)
(O/'source179-original-M101T100-prospective-vs-actual-scope-prelaunch-block.json').write_text(json.dumps({'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_immutable_binding':ref(P/'bindings/M101_T100-actual1035-1073-1074-original138-bed-binding.json'),'blocked_tag':'M101_T100','original_prospective_scope':'37c47df9bf900444e6d0dafcb41af77a8a0d9ff9e777fbf8c3cd056512642235','actual_typed_and_XMF_scope':'80039c17cc7a088b7bc0fdc5c7a74d9051aa72763652261e2823635fcd5ad93d','original_source_validator_PASS_does_not_prove_scope_equality':True,'failed_assertion':'source_h5 scope actual typed == actual XMF == binding','scientific_worker_started':False,'no_bad_binding_enabled_or_case_credited':True,'unaffected_cases_registered':sorted(tags),'bounded_fresh180_single_case_metadata_successor_requested':True},ensure_ascii=False,indent=2)+'\n')
fair=next(H.glob('root*_928'))/'fair_CPU_dispatch.py';cfg={'requests':[str(p) for p in qs],'request_sha256':{str(p):sha(p) for p in qs},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0};(O/'controller-config.json').write_text(json.dumps(cfg,indent=2)+'\n');(O/'source179-four-unaffected-full801-bed-independent-adoption-review.json').write_text(json.dumps({'source_commit':commit,'adopted_files':[ref(R/name) for name in names],'original_planned_cases':5,'actual_enabled_case_count':4,'enabled_requests':[ref(p) for p in qs],'actual_original138_metadata_gates':[ref(O/(tag+'-actual-original138-metadata-gate.json')) for tag in sorted(tags)],'original_source_metadata_unchanged':True,'original_kernel_unchanged':True,'all_four_cases_completed_upstream_with_full801_UID_N3_times_and_scope_proof_before_enable':True,'physical_penetration_or_visual_pass_not_granted_before_real_worker_output':True,'main_scientific_payload_IO':False,'case_credit':0},ensure_ascii=False,indent=2)+'\n');(O/'original-preparation-preflight.py').write_bytes(Path('/tmp/ds02-root1108-source179-five-original138-bed.py').read_bytes());(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes())
paths=names+[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register four verified F5 bed audits and preserve fifth scope mismatch','--',*paths],cwd=R,check=True);print({'registered_bed_cases':4,'blocked_unlaunched_case':'M101_T100','commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
