from pathlib import Path
import json,hashlib,datetime,subprocess,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'],e['path']
def same(a,b):return all(a[k]==b[k] for k in ['path','sha256'])
def parse(t):return datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',t).replace('Z','+00:00'))
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_329.json';cp=load(cpfile);ip=root(1444)/'full336-current332-actual-final48-delivery-progress-index.json';idx=load(ip)
assert same(idx['source_authoritative_checkpoint'],ref(cpfile)) and cp['stage1_visual_accepted_complete_independent_cases']==332 and cp['accepted_per_family']['F5']==45
specs=[(204,6,'25464b3285d8be23536755d1e6efba43b346c1d4',1184,1440,'517321e9f5b62b619933c6b17566d2bd02e6626e823458e43ae51f764c5d0029'),(228,5,'c06252fad98dbad7712b401e0f4b80d759ad5621',1175,1442,'9d29b258a8f7c6cbc1cba9595fb622637b3bdb34e064dd493027f4d27fb4c093')]
prepared=[];allnames=[]
for fresh,fam,commit,original,qn,qsha in specs:
 W=Path(f'/home/jade/.codex/worktrees/ds-data-02-f{fam}/DualSPHysics');P=next((W/f'lagrangian-fluid-lab/campaigns/ds-data-02/families/F{fam}/handoff_20261003').glob(f'root_followup_{fresh}_*'));prefix=P.relative_to(W)
 names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==(4 if fresh==204 else 8)
 blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names};assert all((W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b) for n,b in blobs.items());before={n:sha(W/n) for n in names}
 manifest=load(P/('package-manifest.json' if fresh==204 else 'manifest.json'));expected=set(names)-{str(prefix/('package-manifest.json' if fresh==204 else 'manifest.json'))};assert {str(prefix/e['path']) for e in manifest['files']}==expected
 for e in manifest['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
 rv=subprocess.run(['python3','-B',str(P/f'scripts/validate_fresh{fresh}.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
 qip=root(qn)/f'actual{original}-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';assert sha(qip)==qsha;qi=load(qip);er=qi['actual_completed_metadata_evidence'];cid=qi['case_id'];pid=qi['physical_case_id'];row=next(e for e in idx['cases'] if e['physical_case_id']==pid);assert not row.get('accepted_decision')
 assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['all_native_UIDs_active_each_frame'] and not qi['actual_initial_QA_precision_negative']['pass_at_original_threshold']
 for e in er.values():check(e)
 n=load(er['native_receipt']['path']);x=load(er['xmf_manifest']['path']);t=load(er['typed_report']['path']);rc=load(er['render_receipt']['path']);r=load(er['render_report']['path']);pub=load(er['render_publish_receipt']['path']);br=load(er['bed_receipt']['path']);binding=load(br['request']['binding'])
 for key,e in er.items():
  if key.endswith('_receipt') and key!='render_publish_receipt':
   j=load(e['path']);assert (j['status'],j['returncode'])==('completed',0) and j['request']['case_id']==cid
 canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];sd=qi['actual_SourceDef'];plan=qi['actual_source_plan_JSON_file'];check(sd);check(plan)
 assert row['native_request_scope']['sha256']==canonical==n['request']['physical_condition_sha256']==x['physical_condition_sha256'] and legacy==t['hash_scopes']['physical_condition_sha256']==x['source_h5_physical_condition_sha256'] and len({canonical,legacy,sd['sha256'],plan['sha256']})==4
 masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces']
 assert binding['source_definition']==sd['path'] and binding['source_definition_sha256']==binding['source_plan_physical_condition_sha256']==sd['sha256'] and binding['source_plan_file']==plan['path'] and binding['source_plan_file_sha256']==plan['sha256']
 assert br['input_hashes_at_launch'][plan['path']]==br['input_hashes_after_run'][plan['path']]==plan['sha256'] and br['input_hashes_at_launch'][sd['path']]==br['input_hashes_after_run'][sd['path']]==sd['sha256']
 issues=[]
 if fresh==204:
  sp='metadata/m095-t090-personal-visual-review.json';s=load(P/sp);assert s['case_id']==cid and s['physical_case_id']==pid and s['actual_physical_family']=='F5' and s['assigned_family']=='F6'
  assert s['visual_decision']['status']=='visual-approved-by-delegated-agent' and s['flags']['case_credit']==0 and not any(s['flags'][k] for k in ['Q_N','Q_E','precision_accepted','source_agent_read_scientific_payload','source_agent_hashed_scientific_payload','source_agent_hashed_png'])
  assert s['review_method']['tool']=='view_image' and s['review_method']['source_agent_personally_viewed_all_listed_pngs'] and s['review_method']['total_pngs_viewed']==43 and s['review_method']['key_frames_viewed']==list(range(0,801,100));assert s['root_qi_evidence']['proof_path']==str(qip) and s['root_qi_evidence']['proof_sha256']==qsha
  assert s['physical_and_time_metadata']['actual_time_last_s']==qi['actual_time_window_s'][-1] and s['scope_roles']['native_canonical_physical_condition_sha256']==canonical and s['scope_roles']['typed_converter_legacy_scope_sha256']==legacy and s['scope_roles']['source_definition_sha256']==sd['sha256'] and s['scope_roles']['source_plan_json_sha256']==plan['sha256']
  assert s['scope_roles']['xmf_source_plan_field_presence']['source_plan_condition_sha256'] is True and masks['XMF']['source_plan_condition_sha256']=={'present':False,'value':None};issues.append({'source_field':'scope_roles.xmf_source_plan_field_presence.source_plan_condition_sha256','source_value':True,'actual_value':False,'actual_authority':er['xmf_manifest'],'immutable_source_preserved':True})
  assert qi['native_plan_both_fields_actually_absent'] and all(plan['path'] not in n[k] for k in ['input_hashes_at_launch','input_hashes_after_run'])
  reviewed=s['reviewed_at_utc'];observations=s['visual_decision'];limits=s['visual_decision']['limitations'];entries=s['visual_evidence']['items'];contacts=[e for e in entries if e['kind']=='contact_sheet'];keys=[e for e in entries if e['kind']=='key_frame']
  for e in entries:assert e['source_agent_viewed_with_view_image'] and not e['source_agent_hashed_png']
  normalized=[{'path':e['path'],'relative_path':e['relative_path_in_published_root'],'sha256':e['producer_declared_sha256'],'bytes':e['bytes'],'contact':e['kind']=='contact_sheet','source_record':e} for e in entries]
 else:
  sp='metadata/visual-decision.json';s=load(P/sp);render=load(P/'metadata/actual-render-metadata.json');ev=load(P/'metadata/png-visual-evidence.json');up=load(P/'metadata/upstream-evidence.json');assert s['case_id']==cid and s['physical_case_id']==pid and s['reviewer']['model']=='gpt-5.6-luna/max' and not s['reviewer']['recursive_delegation']
  assert s['decision']['standalone_first_stage_visual_approved'] and not any(s['decision'][k] for k in ['severe_visual_failure','numerical_precision_accepted','q_n_granted','q_e_granted','independent_case_count_increment']) and same(s['qi_reference'],ref(qip))
  assert all(same(up['actual_completed_metadata_evidence'][k],e) for k,e in er.items()) and same(render['execution_receipt'],er['render_receipt']) and same(render['publish_receipt'],er['render_publish_receipt'])
  assert render['scope_roles']['canonical_physical_condition_sha256']==canonical and render['scope_roles']['actual_converter_legacy_scope_sha256']==legacy and render['scope_roles']['source_definition_sha256']==sd['sha256'] and render['scope_roles']['source_plan_file_sha256']==plan['sha256']
  assert n['input_hashes_at_launch'][plan['path']]==n['input_hashes_after_run'][plan['path']]==plan['sha256'] and render['scope_roles']['xmf_source_plan_condition_field_present']==masks['XMF']['source_plan_condition_sha256']['present']
  reviewed=s['reviewer']['reviewed_at_utc'];assert reviewed==render['personal_review_scope']['reviewed_at_utc'];observations={'summary':s['visual_summary'],'personal_observation':ev['personal_observation']};limits=s['evidence_limits'];contacts=ev['producer_attested_contact_sheets'];keys=ev['producer_attested_keyframes'];assert [e['frame_index'] for e in keys]==list(range(0,801,100))
  normalized=[{'path':e['absolute_path'],'relative_path':e['relative_path'],'sha256':e['sha256'],'bytes':e['bytes'],'contact':e in contacts,'source_record':e} for e in contacts+keys];assert all(e['reviewed'] and e['review_mode']=='view_image' for e in contacts+keys)
 assert len(contacts)==34 and len(keys)==9 and parse(rc['finished_at_utc'])<=parse(reviewed)<=datetime.datetime.now(datetime.timezone.utc)
 assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['attempt_id']==rc['request']['attempt_id'] and pub['report_sha256_after_rebind']==sha(er['render_report']['path'])
 assert r['frames']==r['source_frames']==801 and r['all_frames_rendered'] and r['actual_times_preserved_exactly'];out=Path(pub['published_output_root']);pf={e['relative_path']:e for e in pub['files_excluding_receipt']};assert len({e['path'] for e in normalized})==43
 assert [e['path'] for e in normalized if e['contact']]==r['outputs']['contact_sheets'] and [e['path'] for e in normalized if not e['contact']]==[str(out/f'frames/frame_{i:04d}.png') for i in range(0,801,100)]
 jc=[];jk=[]
 for e in normalized:
  p=Path(e['path']);rel=str(p.relative_to(out));dg=sha(p);assert e['relative_path']==rel and dg==e['sha256']==pf[rel]['sha256'] and p.stat().st_size==e['bytes']==pf[rel]['bytes'];j={**e,'main_hash_matches_actual_publisher':True,'viewed':True,'view_method':'view_image'}
  if not e['contact']:j['frame']=int(p.stem.split('_')[1])
  (jc if e['contact'] else jk).append(j)
 prepared.append({'fresh':fresh,'family':fam,'commit':commit,'W':W,'prefix':prefix,'blobs':blobs,'before':before,'validator':rv.stdout,'source_decision':str(prefix/sp),'qi':qi,'qip':qip,'er':er,'canonical':canonical,'legacy':legacy,'sd':sd,'plan':plan,'masks':masks,'issues':issues,'reviewed':reviewed,'observations':observations,'limits':limits,'contacts':jc,'keys':jk});allnames+=names
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_sources204_228_twoF5_actual1184_1175_full801QI_personal86PNG_actual_scope_absences_accepted334_1445';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_330.json';assert not O.exists() and not np.exists();O.mkdir();decisions=[];proofs=[]
for a in prepared:
 for name,b in a['blobs'].items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
 cv=subprocess.run(['python3','-B',str(R/a['prefix']/f"scripts/validate_fresh{a['fresh']}.py")],capture_output=True,text=True);assert cv.returncode==0,(cv.stdout,cv.stderr);assert all((R/n).read_bytes()==b and (a['W']/n).read_bytes()==b for n,b in a['blobs'].items())
 qi=a['qi'];pid=qi['physical_case_id'];proof=O/f"source{a['fresh']}-actual-QI-personal43PNG-and-scope-role-adoption-proof.json";put(proof,{'source_commit':a['commit'],'source_exact_files':[ref(R/n) for n in a['blobs']],'source_before_after_SHA':a['before'],'validator_stdout':a['validator'],'copied_validator_stdout':cv.stdout,'full801_own_QI':ref(a['qip']),'all43_unique_publishedPNG_SHA_match_actual_atomic_publish':True,'personal_review_at_utc':a['reviewed'],'actual_native_XMF_plan_field_namespaces':a['masks'],'source_metadata_discrepancies_preserved_and_direct_actual_sidecar':a['issues'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False});proofs.append(ref(proof))
 dp=O/(pid+'-delegated-visual-decision.json');put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':qi['case_id'],'physical_case_id':pid,'physical_condition_sha256':a['canonical'],'actual_converter_scope_sha256':a['legacy'],'bed_SourceDef_scope_sha256':a['sd']['sha256'],'source_review_commit':a['commit'],'source_review_assigned_family':f"F{a['family']}",'actual_review_family':'F5','source_personal_visual_review':ref(R/a['source_decision']),'source_review_closure':ref(proof),'independent_full801_QI':ref(a['qip']),'actual_completed_metadata_evidence':a['er'],'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_type_counts':{'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'unknown':0},'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_bins_are_diagnostics_not_precision_thresholds':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'actual_native_XMF_plan_field_namespaces':a['masks'],'actual_bed_SourceDef_XML_FILE':a['sd'],'actual_source_plan_JSON_file':a['plan'],'binding_source_definition_field_present':qi['binding_source_definition_field_present'],'native_plan_JSON_input_roles_as_actual_QI':{k:qi[k] for k in qi if 'source_plan_JSON' in k},'source_metadata_discrepancies_preserved_and_direct_actual_sidecar':a['issues'],'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':a['reviewed'],'contact_sheets':a['contacts'],'keyframes':a['keys'],'visual_observations':a['observations'],'visual_limits':a['limits'],'historical_negative_flags':qi['historical_negative_flags'],'original_precision_negative':qi['actual_initial_QA_precision_negative'],'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1});decisions.append(str(dp));row=next(e for e in idx['cases'] if e['physical_case_id']==pid);row.update(status='visual-approved-in-checkpoint330',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(a['qip']))
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=2;new.update(checkpoint=330,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=334,new_accepted_decisions=decisions,accepted_decisions=cp['accepted_decisions']+decisions,home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: user-authorized storage cleanup verified and scoped audit committed. This turn F2 actual48 primary delivered; F5personal204/228 accepted two physical cases to334 with original scope limits retained; lastF3 actual1101 naturally completed and full836 QI1427 done.',authorized_work_state='Active334/336: F3=47 F5=47 other five families48. F3actual1101 full836 completedQI pending fresh229 personal; F5actual1149 original render pending completion. Final F5actual47 and global primary joins required.')
new['actual_progress']['sources204_228_F5_two_actual_case_acceptance']=proofs;new['next_executable_tasks'].insert(0,'Extend F5 actual45 primary to47 with1184/1175; adopt F3personal229 after full836 QI1427; inspect1149 natural0/pub then full801QI and delegated review; final336 primary delivery and physical distinction audit194.')
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==334;put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=334,registered_pending_independent_physical_cases=2,new_case_credit=2);idx['actual_unaccepted_completed0_published_physical_cases']=[]
last=next(e for e in idx['cases'] if e['family_id']=='F3' and not e.get('accepted_decision'));f3qi=root(1427)/'actual1101-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';check(ref(f3qi));last.update(actual_full836_QI=ref(f3qi),personal_visual_status='pending fresh229 personal35contacts9keys');idx['actual_unaccepted_completed0_published_physical_cases']=[last['physical_case_id']]
assert len(idx['cases'])==len({e['physical_case_id'] for e in idx['cases']})==336 and sum(bool(e.get('accepted_decision')) for e in idx['cases'])==334;put(O/'full336-current334-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('接收源204和228的全部个人43图视觉审阅，经实际已发布PNG SHA与own801QI绑定，增加两例F5至总334/336。保留M095/T090原native计划字段缺失和源204的XMF条件计划presence错误，主进程实际sidecar依据真实XMF纠正，源字节不改写。M104/T085弱局部响应、未证明大runup限制保留。视觉检查通过、数值精度未验收。\n')
paths=allnames+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept two final F5 personal reviews to334 preserving actual plan absences and visual limits','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':334,'checkpoint':330,'F5':47,'pending':2,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
