from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 if isinstance(e,str):e={'path':e}
 p=Path(e['path']);assert p.is_file()
 if e.get('sha256'):assert sha(p)==e['sha256'],str(p)
 if e.get('bytes') is not None:assert p.stat().st_size==e['bytes'],str(p)
 return ref(p)
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit='658056881076adbb57ec1c2f88805c45afcc5b0d';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_173_f3_assigned_f2_final48_primary_delivery_42accepted_six_pending_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh173.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
for e in load(P/'package-manifest.json')['files']:
 if 'sha256' in e:assert sha(P/e['path'])==e['sha256']
 else:assert e['path']=='package-manifest.json' and e['role']=='package_manifest'
sp=P/'F2-FINAL48-PRIMARY-DELIVERY-42ACCEPTED-SIX-PENDING.json';s=load(sp);cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_255.json';cp=load(cpfile);assert cp['checkpoint']==255 and cp['stage1_visual_accepted_complete_independent_cases']==302 and cp['accepted_per_family']['F2']==42
ip=root(1333)/'full336-current302-actual-final48-delivery-progress-index.json';index=load(ip);current={r['physical_case_id']:r for r in index['cases'] if r['family_id']=='F2'};fixed=load(root(1276)/'F2-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json');member=s['membership'];f8=member['frozen_first8_physical_case_ids'];f24=member['actual_first24_physical_case_ids'];f48=member['registered_final48_physical_case_ids'];assert len(set(f8))==8 and len(set(f24))==24 and len(set(f48))==48 and set(f8)<=set(f24)<=set(f48)==set(current);assert f8==fixed['frozen_first8_physical_case_ids'] and f24==fixed['actual_first24_physical_case_ids']
verified=[];pending=[];corrections=[];typed_unknown=[];contacts=keys=navcount=0;diffs=[];condabs=[];unlisted=[]
for row in s['rows']:
 pid=row['physical_case_id'];a=row.get('accepted_visual_metadata')
 if not a:
  p=row['pending_metadata'];assert not current[pid].get('accepted_decision') and p['accepted_decision'] is None and p['primary_particle_xmf_render_refs'] is None
  for group in ['native_metadata_refs','typed_metadata_refs','xmf_metadata_refs','loaded_wrapper_metadata_refs','artifact_audit_metadata_refs']:
   for e in p[group]:checked(e)
  assert len(p['native_metadata_refs'])==len(p['loaded_wrapper_metadata_refs'])==1;nr=load(p['native_metadata_refs'][0]['path']);nq=nr['request'];assert nr['status']=='completed' and nr['returncode']==0 and nq['physical_case_id']==pid and nq['physical_condition_sha256']==current[pid]['native_request_scope']['sha256'];wr=p['loaded_wrapper_metadata_refs'][0];w=load(wr['path']);mp=Path(w['manifest']);m=load(mp);assert m['physical_case_id']==pid and m['frames']==w['expected_frames']==401 and m['particles']==w['expected_particles']==418104 and m['fields']['position']['shape']==m['fields']['velocity']['shape']==[401,418104,3]
  pending.append({'physical_case_id':pid,'actual_native_completed0':checked(p['native_metadata_refs'][0]),'actual_wrapper':checked(wr),'actual_wrapper_own401_N3_manifest':ref(mp),'native_canonical_scope':nq['physical_condition_sha256'],'XMF_declared_scope':m['physical_condition_sha256'],'scope_roles_kept_separate':True,'own_completed_scientific_metadata_is_readiness_only':True,'source_live_controller_snapshot_is_historical':True,'primary_visual_decision':None,'case_credit':0});continue
 assert a['accepted_decision']==current[pid]['accepted_decision'];checked(a['accepted_decision']);decision=load(a['accepted_decision']['path']);mp=Path(a['actual_xmf_manifest']['path']);xp=Path(a['actual_xmf_xml']['path']);rp=Path(a['actual_render_report']['path']);src_rcp=Path(a['actual_render_receipt']['path'])
 for e in [a['actual_xmf_manifest'],a['actual_xmf_xml'],a['actual_render_report'],a['actual_render_receipt']]:checked(e)
 m=load(mp);r=load(rp);source_rc=load(src_rcp);rcp=src_rcp;correction=None
 if source_rc.get('status')!='completed' or source_rc.get('returncode')!=0:
  assert src_rcp.suffix=='.json' and src_rcp.name.endswith('-render-request.json') and decision['bindings']['render_request']['path']==str(src_rcp);rcp=rp.parent.parent/'execution-receipt.json';assert rcp.is_relative_to(D) and rp.parent.name=='render';actual=load(rcp);assert actual['request']['case_id']==row['case_id'];correction={'physical_case_id':pid,'immutable_source_misclassified_render_request':ref(src_rcp),'source_actual_status':source_rc.get('status'),'source_process_returncode_field_present':'returncode' in source_rc,'source_process_returncode':source_rc.get('returncode'),'actual_same_render_report_attempt_execution_receipt':ref(rcp),'same_case_report_attempt_layout_and_receipt_inputs_independently_bound':True,'source_request_not_promoted_to_completed_receipt':True};corrections.append(correction)
 rc=load(rcp);assert rc['status']=='completed' and rc['returncode']==0 and rc['request']['case_id']==row['case_id'];assert m['physical_case_id']==pid and m['frames']==r['frames']==r['source_frames']==401;particles=m['particles'];assert particles==(421566 if pid=='F2H10V2_OFFSET_V1' else 418104)
 assert r['all_frames_rendered'] and not r['diagnostic_only'] and r['nonfinite_active_states']==0 and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['source_h5_read_only'];assert r['manifest_sha256']==sha(mp) and r['input_manifest']==str(mp) and r['source_h5_sha256']==m['source_h5_sha256'] and m['xdmf_sha256']==sha(xp)==r['xdmf_sha256_before']==r['xdmf_sha256_after'] and r['xdmf']==m['xdmf']==str(xp)
 assert m['fields']['position']['shape']==m['fields']['velocity']['shape']==[401,particles,3];assert r['frame_selection']==list(range(401)) and [e['frame'] for e in r['frame_diagnostics']]==list(range(401)) and [e['actual_time_s'] for e in r['frame_diagnostics']]==m['actual_time_s']
 hp=m.get('trajectory_h5',m.get('source_h5'));assert hp and Path(hp).is_file()
 for ih in [rc['input_hashes_at_launch'],rc['input_hashes_after_run']]:assert ih[hp]==m['source_h5_sha256'] and ih[str(mp)]==sha(mp) and ih[str(xp)]==sha(xp)
 assert len(a['native_refs'])==1;native=checked(a['native_refs'][0]);nr=load(native['path']);nq=nr['request'];assert nr['status']=='completed' and nr['returncode']==0 and nq['physical_case_id']==pid and nq['case_id']==row['case_id'];canonical=nq.get('physical_condition_sha256');roles=a['native_vs_xmf_role_metadata'];assert roles['native_request_physical_condition_field_present']==('physical_condition_sha256' in nq) and roles['native_request_physical_condition_sha256']==canonical and roles['xmf_manifest_physical_condition_sha256']==m['physical_condition_sha256']
 if 'physical_condition_sha256' not in nq:assert pid=='F2H10V2_OFFSET_V1' and canonical is None;condabs.append(pid)
 else:assert canonical==current[pid]['native_request_scope']['sha256'];assert canonical!=m['physical_condition_sha256'];diffs.append(pid)
 typedstates=[]
 for e in a['typed_refs']:
  er=checked(e);tj=load(e['path'])
  if 'request' in tj and 'status' in tj:
   typedstates.append({'receipt':er,'status':tj['status'],'returncode_field_present':'returncode' in tj,'returncode':tj.get('returncode')})
   if tj['status']!='completed':
    assert pid=='F2_STAGE1_OFFSET_P03_OPEN_RIM_RX065_RY014_FILL080' and tj['status']=='running' and 'returncode' not in tj;recovery=m['recovery_provenance'];assert not recovery['original_conversion_completed_claim'] and not recovery['source_receipt_edited'];audit=recovery['artifact_recovery_audit'];checked(audit['receipt']);checked(audit['report']);ar=load(audit['receipt']['path']);assert ar['status']=='completed' and ar['returncode']==0 and audit['verified_frames']==401 and audit['verified_particles']==418104 and audit['verified_trajectory_sha256']==m['source_h5_sha256'];typed_unknown.append({'physical_case_id':pid,'original_unknown_typed_runtime':typedstates[-1],'actual_independent_recovery_audit_receipt':checked(audit['receipt']),'actual_recovery_audit_report':checked(audit['report']),'original_runtime_returncode_not_promoted':True,'scientific_payload_IO':False})
  elif 'conversion_status' in tj:assert tj['output_sha256']==m['source_h5_sha256']
 cpng=a['contact_png_refs'];kpng=a['key_png_refs'];cref=[checked(e) for e in cpng];kref=[checked(e) for e in kpng];assert len(cpng)==17 and [e['path'] for e in cref]==r['outputs']['contact_sheets'];contacts+=len(cref);keys+=len(kref)
 if not kpng:unlisted.append(pid)
 fd=Path(r['outputs']['frames_dir']);assert fd.is_relative_to(D) and sorted(p.name for p in fd.glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(401)];nav=[]
 for i in [0,50,100,150,200,250,300,350,400]:
  fp=fd/f'frame_{i:04d}.png';assert fp.stat().st_size>0;nav.append({**ref(fp),'bytes':fp.stat().st_size,'frame':i,'actual_time_s':m['actual_time_s'][i],'role':'actual_published_navigation_not_new_personal_review'})
 navcount+=len(nav);verified.append({'physical_case_id':pid,'accepted_visual_decision':checked(a['accepted_decision']),'actual_native_receipt':native,'actual_native_condition_field':{'present':'physical_condition_sha256' in nq,'value':canonical},'own_XMF_declared_condition_sha256':m['physical_condition_sha256'],'source_original_render_receipt_role_preserved':checked(a['actual_render_receipt']),'actual_render_receipt':ref(rcp),'source_render_request_role_correction':correction,'primary_XMF_manifest':ref(mp),'primary_XMF_XML':ref(xp),'primary_render_report':ref(rp),'full401_own_times_N3_render_bindings_and_launch_after_producer_attestations_verified':True,'particle_count':particles,'all_native_UIDs_active_not_newly_claimed':True,'existing_particle_exclusions_and_precision_limits_preserved_in_accepted_decision':True,'source_typed_runtime_observations':typedstates,'source_contacts_verified':len(cref),'source_keys_verified':len(kref),'source_unlisted_key_field_preserved':not bool(kpng),'main_contact_refs':cref,'main_source_key_refs':kref,'main_published_navigation_keys':nav,'new_case_credit':0,'new_personal_visual_review':False,'scientific_payload_IO':False})
assert len(verified)==42 and len(pending)==6 and contacts==714 and keys==160 and navcount==378 and len(unlisted)==14 and len(diffs)==41 and condabs==['F2H10V2_OFFSET_V1'] and len(corrections)==4 and len(typed_unknown)==1
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source173_F2_final48_actual42_primary_401frames_baseline421566_four_request_receipt_role_corrections_P03_unknown_typed_recovery_six_pending_1330';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_256.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source173-byte-exact-validator-main42-own-primary-four-actual-receipt-corrections-and6-readiness-proof.json';put(vp,{'schema':'ds02.main.source173.actualF2-final48-primary-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'before_after_SHA':before,'source_validator_stdout':rv.stdout,'source_validator_stderr':rv.stderr,'actual42_primary_bindings':verified,'six_pending_readiness':pending,'four_source_request_misclassified_as_receipt_new_role_sidecars':corrections,'originalP03_unknown_typed_runtime_and_actual_recovery_audit':typed_unknown,'native_vs_XMF_41_role_differences':diffs,'actual_native_condition_field_absences':condabs,'714contacts160keys_and378navigation_PNG_SHA_verified':True,'source14_unlisted_key_cases_preserved':unlisted,'new_case_credit':0,'new_personal_visual_review':False,'scientific_payload_IO':False,'Q_N':0,'Q_E':0})
product=copy.deepcopy(s);product.update(schema='ds02.main.F2.final48.actual42accepted-sixpending-primary-delivery.v1',status='actual42_primary_verified_four_original_request_role_errors_explicitly_corrected_six_visual_pending',at_utc=now.isoformat(),source_original_exact_package=ref(R/prefix/sp.name),stable_predecessor_checkpoint=ref(cpfile),main_independent_verification=ref(vp));product['main_corrected_actual_primary_and_published_navigation_sidecars']=verified;product['main_pending_own401_N3_readiness_sidecars']=pending;pp=O/'F2-FINAL48-ACTUAL42ACCEPTED-SIXPENDING-CORRECTED-PRIMARY-DELIVERY.json';put(pp,product);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new.update(checkpoint=256,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actualF2 final48 primary42/6 delivery independently verified, four source render requests reclassified using same-case actualcompleted execution receipts; baseline421566 distinct from41x418104;41native/XMF role differences and P03 unknown typed original plus completed artifact recovery audit preserved. ActualF5 original1181 completed0 and ownQI1331 verified; fresh188 personal review active.',authorized_work_state='Active302/336; actualF2 final48 primary42accepted/sixpending delivered; F5 original1181 full801 ownQI1331 awaiting fresh188 personal43PNG, original1191 same-handle rendering and futureQI1332. F5 fresh174 final48 source catalog in progress; remaining original render queues preserved.')
new['actual_progress']['F2_final48_actual42_corrected_primary_sixpending_delivery']=ref(pp);new['actual_progress']['F2_final48_actual42_main_proof_four_source_role_corrections']=ref(vp);qip=root(1331)/'actual1181-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';new['actual_progress']['actual1181_full801_own_QI']=ref(qip);new['source_agents']['production_recovery']='fresh173 exact source adopted with main four corrected actualrenderreceipt sidecars; fresh174 actualF5 final48 source catalog28accepted/twentypending active';put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);index['actual_F2_final48_primary42accepted_sixpending_corrected_delivery']=ref(pp)
for r in index['cases']:
 if r['family_id']=='F2':r['actual_F2_final48_primary42accepted_sixpending_corrected_delivery']=ref(pp)
put(O/'full336-current302-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('F2固定8⊂24⊂48，42视觉通过与6待审图。每例实际401帧；baseline421566粒子，其余41例418104。源目录四条所谓render receipt实为旧申请JSON；原字节不修改，新增sidecar绑定本例同一动画实际completed0 executionreceipt，核对XML/manifest/H5生产者运行前后元数据证明。714contact/160源key与378实际发布导航key核对；源14例未枚举key仍保留。P03原typed收据running、返回码缺失，不改判，保留已有完整401产物恢复审计。41例native与XMF角色差异、baseline native条件字段缺失原样保留；本次未读科学payload，新增案例和精度信用均0。\n')
paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: deliver actual F2 final48 primary42 with four corrected receipt roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':256,'accepted':302,'F2_primary_verified':42,'sixpending':6,'four_source_request_role_corrections':4,'contacts':contacts,'sourcekeys':keys,'navigationkeys':navcount,'product':ref(pp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
