from pathlib import Path
import json,hashlib,runpy,tempfile,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,indent=2)+'\n');O=H/'root_stage1_logged114_fullnative_first_recovery_then_shared2_F6_23_F4priority10_F2_3_F5_1_945';O.mkdir(exist_ok=False);(O/'requests').mkdir();(O/'wrapper-requests').mkdir()
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
a=load(root(944)/'actual114-and128-adoption-review.json');worker=Path(a['packages'][0]['package'])/'workers/nvme_render_successor.py';entry=root(944)/'registered_render_entry_with_bounded_diagnostics.py';assert sha(worker)=='99551eec102a5cb596780cc30a2454eb5bb3d9697d89f49959bc62bd4ccef81a';api=runpy.run_path(str(worker));fair=root(928)/'fair_CPU_dispatch.py';oldcfg=load(root(934)/'controller-config.json');oldrows=[load(p) for p in oldcfg['outer_requests']];first=oldrows[0];basew=load(root(934)/'wrapper-requests'/(first['physical_case_id']+'-enabled-wrapper.json'));catalog=load(Path(a['packages'][1]['package'])/'metadata/case-catalog.json');F4=catalog['records']['priority10'];assert len(F4)==10;cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_123.json');accepted={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};assert all(q['physical_case_id'] not in accepted for q in oldrows) and all(r['case_id'] not in accepted for r in F4)
dq=load(root(943)/'enabled-diagnostic-request.json');diag=load(Path(dq['attempt_root'])/'native023-error-diagnostic.json');assert diag['status']=='diagnostic_completed' and diag['returncode']==0 and diag['diagnostic_report']['frame_selection']==[0]
# Independently exercise the registered exit contract and failure diagnostic forwarding.
with tempfile.TemporaryDirectory(prefix='ds02-entry944-toy-') as td:
 t=Path(td);rq=t/'q.json';rq.write_text('{}');fake=t/'worker.py';checks=[]
 for status,floor,rc in [('completed',True,0),('completed',False,1),('renderer_failed',None,1),('rejected_before_publish',None,1)]:
  payload={'status':status,'post_publish_home_floor_rechecked':floor,'renderer_diagnostics':{'stderr_tail':'bounded toy error','returncode':1}};fake.write_text('def execute_request(q, authorized=False):\n return '+repr(payload)+'\n');p=subprocess.run(['/usr/bin/python3',str(entry),'--worker',str(fake),'--request',str(rq)],capture_output=True,text=True);assert p.returncode==rc and json.loads(p.stdout)['renderer_diagnostics']['stderr_tail']=='bounded toy error';checks.append({'status':status,'floor':floor,'actual_exit':p.returncode,'bounded_diagnostics_forwarded':True})
put(root(944)/'main-independent-tests.json',{'source114_toy_tests_pass':10,'registered_entry_exit_forwarding':checks,'science_payload_IO':False,'case_credit':0})
controller=O/'batch-controller.py';controller.write_bytes((root(934)/'batch-controller.py').read_bytes());s=controller.read_text().replace("'requested':27","'requested':37");assert s!=controller.read_text();controller.write_text(s);compile(s,str(controller),'exec')
# One proved first recovery, then two registered renderers, interleaving families.
F6=[q for q in oldrows if q['family_id']=='F6'];others=[q for q in oldrows if q['family_id']!='F6'];order=[('old',F6[0]),('F4',F4[0])]+[('old',q) for q in others];f6=iter(F6[1:]);f4=iter(F4[1:])
for _ in range(22):
 x=next(f6,None);y=next(f4,None)
 if x:order.append(('old',x))
 if y:order.append(('F4',y))
assert len(order)==37;common=[worker,entry,fair,controller,root(944)/'actual114-and128-adoption-review.json',root(944)/'main-independent-tests.json',Path(dq['attempt_root'])/'native023-error-diagnostic.json',root(943)/'enabled-diagnostic-request.json'];paths=[];pre=[]
for typ,row in order:
 if typ=='old':
  q=row.copy();w=load(root(934)/'wrapper-requests'/(q['physical_case_id']+'-enabled-wrapper.json'));metadata=w['input_sha256'].copy();pid=q['physical_case_id'];fam=q['family_id'];cid=q['case_id'];frames=q['expected_frames'];particles=q['expected_particles'];dg=q['physical_condition_sha256'];h5sha=q['source_h5_producer_sha256'];oldorigin=ref(root(934)/'requests'/(pid+'-render-request.json'))
 else:
  pid=cid=row['case_id'];fam='F4';frames=1201;particles=83233;md=row['metadata_inputs'];metadata=basew['input_sha256'].copy();metadata.update({v['path']:v['sha256'] for v in md.values()});w=basew.copy();w['manifest']=md['xmf_manifest']['path'];dg=row['scope_separation']['actual_converter_scope_sha256'];c=load(md['typed_report']['path']);m=load(md['xmf_manifest']['path']);assert c['frames']==frames and c['particles']==particles and c['solver_dimension']['solver_dimension']==3 and c['partvtk_validation']['all_passed'] and c['hash_scopes']['physical_condition_sha256']==dg and m['physical_condition_sha256']==dg;h5sha=c['output_sha256'];q={k:v for k,v in first.items() if k.startswith('root_')};q.update(schema='ds02.runner-request.v2',family_id=fam,case_id=cid,physical_case_id=pid,physical_condition_sha256=dg,actual_converter_scope_sha256=dg,kind='cpu',cpu_task_kind='audit',cpu_threads=24,max_wall_seconds=14400,estimated_storage_bytes=3*1024**3,launch_owner='root',worktree_root=str(R),cwd=str(L),source_h5_producer_sha256=h5sha,expected_frames=frames,expected_particles=particles,expected_contact_sheets=51,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,independent_case_count_increment=0);oldorigin=ref(Path(a['packages'][1]['package'])/'render-templates'/(pid+'.disabled-request.json'));w.update(actual_converter_scope_sha256=dg,canonical_source_scope_sha256=dg,scope_separation=row['scope_separation'])
 for p,d in metadata.items():assert sha(p)==d
 metadata.update({str(p):sha(p) for p in common});metadata[oldorigin['path']]=oldorigin['sha256'];aid='root-stage1-'+fam.lower()+'-'+pid.lower()+'-full'+str(frames)+'-logged114-NVMe3GiB-root945';ar=D/'families'/fam/cid/aid;assert not ar.exists();rid='/'.join([fam,cid,aid]);w.update(schema=api['SCHEMA'],family_id=fam,case_id=cid,physical_case_id=pid,attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root='/tmp/ds02-visual-render-cache-root945',expected_frames=frames,expected_particles=particles,expected_contact_sheets=(frames+23)//24,keyframe_indices=[round(i*(frames-1)/8) for i in range(9)],input_files=sorted(metadata),input_sha256=metadata,source_only=False,disabled=False,launch=True,launch_allowed=True,execution_allowed=True)
 api['validate_request'](w,execution=True);api['_manifest_metadata'](w);wp=O/'wrapper-requests'/(pid+'-enabled-wrapper.json');put(wp,w);manifest=load(w['manifest']);outermd={**metadata,str(wp):sha(wp),manifest['trajectory_h5']:h5sha};q.update(attempt_id=aid,attempt_root=str(ar),command=[str(L/'.venv/bin/python'),str(entry),'--worker',str(worker),'--request',str(wp)],input_files=sorted(outermd),input_sha256=outermd,root_distinct_recovery_of_failed934_only_if_same_case=pid==first['physical_case_id'],root_original_source_request_or_template=oldorigin,source_h5_producer_sha256=h5sha);qp=O/'requests'/(pid+'-render-request.json');put(qp,q);paths.append(str(qp));pre.append({'request':ref(qp),'wrapper':ref(wp),'family_id':fam,'physical_case_id':pid,'frames':frames,'particles':particles,'case_credit':0})
put(O/'controller-config.json',{'outer_requests':paths,'requested':37,'families':{'F6':23,'F4':10,'F2':3,'F5':1},'fair_dispatch_source':ref(fair),'worker':ref(worker),'entry':ref(entry),'first_recovery_case':first['physical_case_id'],'recovery_rationale':'Original023 actualframe0 registereddiagnostic943 completed0 with241timesexact andfinite nativeidentity; distinct114 logging tested andregisteredentry failure1. Root934negative preserved; one full recovery thenpool2 onlyonactualfirstsuccess. Ifnewfirstfails,hold36 andclassify retainederror,neverblindrerun.','case_credit':0});put(O/'enabled37-metadata-preflight.json',{'cases':pre,'requested':37,'F4priority10_only_fallback5_disabled':True,'prior199_excluded':True,'first934_failed_retained_and943_bounded_diagnostic_actual0':True,'CPU24_env2_globalcap2':True,'Home3GiB_hardpublication':True,'Home500GiB_floor':True,'science_payload_main_IO':False,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());print({'enabled':37,'families':{'F6':23,'F4':10,'F2':3,'F5':1},'first_recovery_only_then2':True})
