from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.bi4','.dat','.csv','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
tqp=next((root(995)/'requests').glob('*.json'));tq=load(tqp);tr=Path(tq['attempt_root'])/'execution-receipt.json';tp=tr.parent/'conversion-report.json';rec=load(tr);t=load(tp);nr=Path(tq['native_receipt']);native=load(nr);owner=Path(tq['owner_metadata']);own=load(owner)
assert (rec['status'],rec['returncode'])==(native['status'],native['returncode'])==('completed',0)
assert t['frames']==401 and t['particles']==418104 and t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and t['solver_dimension']['solver_dimension']==3
actual=t['hash_scopes']['physical_condition_sha256'];canonical=tq['physical_condition_sha256'];assert actual==tq['actual_converter_scope_sha256_prospective'] and t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0'
assert t['source_provenance']['solver_receipt']==ref(nr) and native['request']['physical_condition_sha256']==canonical
for key in ['owner_metadata','gencase_receipt','generated_xml']:
 p=t['source_provenance'][key];assert sha(p['path'])==p['sha256']
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_143.json');assert tq['physical_case_id'] not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
O=H/'root_stage1_F2_RX049_ROT075_actual995_typed0_full401_original108_104_N3_XMF_fairCPU2_1007';O.mkdir(exist_ok=False);(O/'requests').mkdir();(O/'bindings').mkdir()
worker=Path(load(root(827)/'controller-config.json')['registered_export_worker']);assert sha(worker)=='da50e26d5322b1b6f1539bca3109dfc115164427b37e1b2f86f56b153f56b0b0'
controller=O/'batch-xmf-controller.py';code=(root(1002)/'batch-xmf-controller.py').read_text().replace('836','401').replace('179208','418104');controller.write_text(code)
proof=O/'actual995-full401-independent-XMF-registration.json';put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_typed_receipt':ref(tr),'actual_typed_report':ref(tp),'actual_native_receipt':ref(nr),'previous_independent_full401_review':ref(root(1005)/'actual995-F2-full401-storage-recovered-typed-independent-review.json'),'actual_converter_legacy_scope':actual,'source_canonical_and_plan_scope':canonical,'source_H5_SHA_actual_producer_attested':t['output_sha256'],'science_payload_IO':False,'case_credit':0})
py=L/'.venv/bin/python';pysha=rec['input_hashes_at_launch'][str(py.resolve())];assert pysha==rec['input_hashes_after_run'][str(py.resolve())]
md={str(p):sha(p) for p in [worker,controller,tqp,tr,tp,nr,owner,proof,root(928)/'fair_CPU_dispatch.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(64)/'resource-window-approval.json']};md[str(py)]=pysha
b={'schema':'ds02.f2.actual995.full401.normal-N3-xmf-binding.v1','family_id':'F2','case_id':tq['case_id'],'physical_case_id':tq['physical_case_id'],'physical_condition_sha256':actual,'producer_scope_schema':t['hash_scopes']['physical_condition']['schema'],'canonical_source_physical_condition_sha256':canonical,'actual_converter_legacy_scope_sha256':actual,'scope_equality_not_claimed':True,'trajectory_h5':t['output_hdf5'],'trajectory_h5_sha256_producer_attested':t['output_sha256'],'conversion_report':str(tp),'conversion_report_sha256':sha(tp),'typed_receipt':str(tr),'native_receipt':str(nr),'expected_frames':401,'physical_window_s':[0,4],'actual_geometry':own['geometry'],'native_type_aliases':{'fixed':[0],'moving':[1],'floating':[2],'fluid':[3]},'full_saved_states':True,'xmf_shape_contract':'full401 position and velocity N3 vectors, XYZ geometry','bound_metadata_sha256':md.copy(),'q_n_granted':False,'precision_status':'not_accepted','production_approval':'none','independent_case_increment':0}
bp=O/'bindings'/(tq['case_id']+'-actual995-full401-xmf-binding.json');put(bp,b);md[str(bp)]=sha(bp);md[t['output_hdf5']]=t['output_sha256'];base=load(root(977)/'enabled-full836-xmf-request.json');q={k:base[k] for k in ['schema','launch_owner','cwd','worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']}
aid='root-stage1-f2-rx049-rot075-actual995-full401-N3-xmf108-root1007';out=D/'families/F2'/tq['case_id']/aid;assert not out.exists()
q.update(kind='cpu',cpu_task_kind='audit',cpu_threads=2,max_wall_seconds=7200,estimated_storage_bytes=2**30,family_id='F2',case_id=tq['case_id'],physical_case_id=tq['physical_case_id'],physical_condition_sha256=actual,canonical_source_physical_condition_sha256=canonical,attempt_id=aid,attempt_root=str(out),command=[str(py),str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xdmf'],disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,depends_on_attempts=[tq['attempt_id'],native['request']['attempt_id']],input_files=sorted(md),input_sha256=md,actual_typed_H5_SHA_from_producer_only=t['output_sha256'],source_scientific_payload_IO_by_main=False,full401_N3_authorized=True,q_n_granted=False,q_e_granted=False,case_credit=0)
qp=O/'requests'/(q['case_id']+'-enabled-full401-xmf-request.json');put(qp,q);put(O/'controller-config.json',{'requests':[str(qp)],'request_sha256':{str(qp):sha(qp)},'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: bind actual recovered F2 full401 typed0 to original108 N3 XMF producer','--',*paths],cwd=R,check=True);print({'root':str(O),'registered':1,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
