from pathlib import Path
import json,hashlib,subprocess,datetime,ast,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_107_f3_internal16_pitch_ay_source_v1';root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in ['.json','.xml','.py','.md'] or p==L/'.venv/bin/python';return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_F3_delegated107_remaining16_pitch_AY_source_adoption_895';O.mkdir();commit='b6c34bba599d3690090234f9ab467e4ef8ba1020';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines();adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert p.read_bytes()==b;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==b;dst.write_bytes(b);adopted.append(ref(dst))
P=R/S.relative_to(W);binding=load(P/'source-binding.json');assert binding['source_only'] and not binding['launch_allowed'];assert len(binding['candidates'])==16;expected={(p,a) for p in [.9,1.1] for a in [.29,.36,.43,.50,.54,.57,.64,.70]};pairs={(c['nominal_pitch_multiplier'],c['transverse_amplitude_m_s2']) for c in binding['candidates']};assert pairs==expected
old=load(root(839)/'actual-four-corner-visual-range-release.json');vr=binding['released_visual_domain_reference'];assert sha(vr['path'])==vr['sha256'];assert vr['nominal_pitch_multiplier_range']==[.8,1.2] and vr['transverse_amplitude_range_m_s2']==[.25,.75];assert all(.8<p<1.2 and .25<a<.75 for p,a in pairs)
for k,v in binding['actual_704_705_proof'].items():
 if isinstance(v,dict) and 'path' in v:assert sha(v['path'])==v['sha256']
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_115.json')['accepted_decisions'];accepted={load(p)['case_id'] for p in prior};reserved={load(p)['case_id'] for n in [839,884] for p in (root(n)/'requests').glob('*native-request.json')};assert all(c['case_id'] not in accepted|reserved and c['future_forcing_sha256'] is None and c['future_physical_condition_sha256'] is None for c in binding['candidates'])
for k in ['baseline_native_receipt','baseline_typed_receipt','baseline_gencase_receipt']:r=load(binding[k]);assert (r['status'],r.get('returncode'))==('completed',0)
init=binding['baseline_initial_reference']['initial_native_verified'];assert init['passed'] and init['actual_3d'] and init['native_particles']==179208 and init['native_fluid']==67500 and init['native_fixed']==111708 and init['native_initial_BI4_sha256']==binding['baseline_bi4_sha256'];assert sha(binding['baseline_prefix']+'.xml')==binding['baseline_xml_sha256'];assert sha(binding['source_builder'])==binding['source_builder_sha256'] and sha(binding['preparation_script'])==binding['preparation_script_sha256'];ast.parse((P/'source/source_builder.py').read_text());ast.parse((P/'source/prepare_pitch_axis.py').read_text())
# Verify original metadata only; new execution request below cannot reuse original704 consumed attempt_root.
original=load(P/'requests/batch-source-preparation-request.json');assert original['disabled'] and not original['launch'] and original['attempt_root']==load(root(704)/'actual-new24-input-preparation-request.json')['attempt_root'];assert 'template_policy' in binding['baseline_physical_binding'];put(O/'actual-source-adoption-review.json',{'source_commit':commit,'adopted_files':adopted,'source_bytes_preserved':True,'candidate_count':16,'exact_parameter_pairs':sorted(pairs),'candidate_ids_distinct_from_actual_accepted_and_next20':True,'future_scientific_hashes_not_claimed':True,'case_credit':0,'no_Root_scientific_payload_read_or_hash':True,'additive_execution_binding_needed':['original disabled batch carries existing consumed704 attempt_root; distinct new attempt required','baseline physical-binding template_policy is source-only annotation and must be outside true v1 scientific physical scope before materializing actual forcing'],'original_disabled_request_not_executed':True});(O/'root-adoption-source.py').write_bytes(Path(__file__).read_bytes())
X=H/'root_stage1_F3_actual107_remaining16_registered_exact_initial_forcing_preparation_896';X.mkdir();actual=json.loads(json.dumps(binding));policy=actual['baseline_physical_binding'].pop('template_policy');actual['source_template_policy']=policy;actual.update(preparation_script=str(P/'source/prepare_pitch_axis.py'),source_builder=str(P/'source/source_builder.py'),execution_binding_status='only Root registered CPU input preparation enabled; native/typed/render disabled',original_source_binding=ref(P/'source-binding.json'),source_adoption=ref(O/'actual-source-adoption-review.json'));bp=X/'actual-input-preparation-binding.json';put(bp,actual)
# Direct converter's unchanged validation checks metadata only; no H5 is opened.
script=L/'scripts/ds_data02_direct_convert.py';check="import sys,json;sys.path.insert(0,sys.argv[1]);from ds_data02_direct_convert import _physical_condition_scope;b=json.load(open(sys.argv[2]));s=_physical_condition_scope({'physical_binding':b['baseline_physical_binding']});assert s['schema']=='ds-data-02.physical-binding.v1';print('true-v1-template-metadata-scope-pass')";subprocess.run([str(L/'.venv/bin/python'),'-c',check,str(L/'scripts'),str(bp)],check=True)
base=load(root(704)/'actual-new24-input-preparation-request.json');profile={k:v for k,v in base.items() if k in ['resource_window'] or k.startswith('root_') and k in ['root_dataset_inventory_profile','root_inventory_profile','root_inventory_policy_source','root_inventory_policy_source_sha256','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']};paths=[bp,Path(__file__),O/'actual-source-adoption-review.json',P/'source-binding.json',P/'source/source_builder.py',P/'source/prepare_pitch_axis.py',Path(binding['forcing_transformer']),Path(binding['baseline_prefix']+'.xml'),Path(binding['baseline_gencase_receipt']),Path(binding['baseline_native_receipt']),Path(binding['baseline_typed_receipt']),Path(binding['baseline_initial_reference']['initial_typed_qa']),Path(vr['path']),root(705)/'actual-new24-exact-initial-forcing-independent-review.json',script,L/'.venv/bin/python',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json'];md={str(p):sha(p) for p in paths};md[binding['baseline_prefix']+'.bi4']=binding['baseline_bi4_sha256'];md[binding['nominal_source_forcing']]=binding['nominal_source_forcing_sha256'];case='F3_STAGE1_INTERNAL16_PITCH_AY_SOURCE_PREPARATION';aid='root-stage1-f3-internal16-exact-initial-forcing-preparation-root896';ap=D/'families/F3'/case/aid;assert not ap.exists();q={**profile,'schema':'ds02.runner-request.v2','family_id':'F3','case_id':case,'attempt_id':aid,'attempt_root':str(ap),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':2,'estimated_storage_bytes':4*1024**3,'max_wall_seconds':7200,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'command':[str(L/'.venv/bin/python'),str(P/'source/source_builder.py'),'--binding',str(bp),'--output-dir','{attempt_root}/prepared'],'input_files':sorted(md),'input_sha256':md,'source_binding':str(bp),'root_source107_adoption':str(O/'actual-source-adoption-review.json'),'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'root_review_required':False,'production_approval':'none','case_credit':0,'future_native_receipt':None,'future_typed_receipt':None,'precision_status':'not_accepted'};put(X/'registered-input-preparation-request.json',q)
# File sizes only: no scientific bytes read by Root. Transformer writes16 bounded text forcings and16 exact initialized BI4 copies.
bi4bytes=Path(binding['baseline_prefix']+'.bi4').stat().st_size;forcingbytes=Path(binding['nominal_source_forcing']).stat().st_size;bound=16*(bi4bytes+4*forcingbytes)+1024**3;assert bound<q['estimated_storage_bytes'];put(X/'input-preparation-storage-bound.json',{'initial_BI4_size_from_stat_only':bi4bytes,'baseline_forcing_size_from_stat_only':forcingbytes,'cases':16,'conservative_source_text_expansion_factor':4,'metadata_overhead_bytes':1024**3,'bound_bytes':bound,'reservation_bytes':q['estimated_storage_bytes'],'source_arrays_not_read_or_hashed_by_Root':True,'no_native_or_typed_output_allocated':True})
assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',str(P.relative_to(R)),str(O.relative_to(R)),str(X.relative_to(R))],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: adopt F3 remaining16 source and bind distinct registered exact initial preparation'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'source_adopted':16,'request':str(X/'registered-input-preparation-request.json'),'registered_preparation_only':True,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
