from pathlib import Path
import json,hashlib,runpy,subprocess,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
bq=load(root(971)/'enabled-bed-request.json');b=load(bq['binding']);cr=load(root(971)/'controller-result.json');recp=Path(cr['actual_receipt']);rec=load(recp);assert (rec['status'],rec['returncode'])==('completed',0);bedp=recp.parent/'audit-output/c082s1-full-event-bed-footprint-audit.json';a=load(bedp);x=load(b['xmf_manifest']);t=load(b['conversion_report']);assert a['physical_condition_sha256']==b['physical_condition_sha256'];assert a['source']['trajectory_h5_sha256']==b['trajectory_h5_sha256']==t['output_sha256']==x['source_h5_sha256'];assert a['source']['xdmf']==b['xdmf'] and a['source']['xdmf_sha256']==sha(b['xdmf']);assert sha(b['xmf_manifest'])==b['xmf_manifest_sha256'];assert len(a['frame_reports'])==a['scan']['frames_scanned']==t['frames']==x['frames']==801 and t['particles']==x['particles']==194427 and t['solver_dimension']['solver_dimension']==3
fs=t['lifecycle']['frame_summary'];grids=ET.parse(b['xdmf']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(grids)==len(fs)==801;assert times==[f['time'] for f in fs]==[f['time_s'] for f in a['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=16 and all(u<v for u,v in zip(times,times[1:]));assert t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert t['lifecycle']['introduced_ids']=='rejected';maxima={'one_dp':0,'two_dp':0,'missing_initial_fluid':0,'unexpected_uid':0,'nonfinite_position':0,'nonfinite_mass':0,'all_missing':0}
for i,(f,g,z) in enumerate(zip(a['frame_reports'],grids,fs)):
 assert f['frame']==z['frame']==i and f['particle_axis_count']==194427 and f['initial_fluid_uid_count']==31658 and f['current_valid_type3_fluid_count']==31658
 vals={'one_dp':f['penetration']['one_dp']['count'],'two_dp':f['penetration']['two_dp']['count'],'missing_initial_fluid':f['uid_tracking']['missing_initial_uid']['count'],'unexpected_uid':f['uid_tracking']['unexpected_current_uid']['count'],'nonfinite_position':f['nonfinite_position_current_fluid_count'],'nonfinite_mass':f['nonfinite_mass_current_fluid_count'],'all_missing':z['missing_particles']}
 for k,v in vals.items():maxima[k]=max(maxima[k],v)
 assert z['active_particles']==194427 and not any(vals.values()) and not f['unexplained_state']['nonfinite_or_lost_initial_uid_present'];assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';vv=next(v for v in g.findall('Attribute') if v.get('Name').lower()=='velocity');assert vv.find('DataItem').get('Dimensions')=='194427 3' and vv.get('AttributeType')=='Vector'
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_133.json');assert b['physical_case_id'] not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};O=H/'root_stage1_F5_M095_actual971_bed0_full801_N3_original116_023_hard2GiB_shared2_render_984';O.mkdir(exist_ok=False);proof=O/'actual971-all801-bed-and968-XMF-independent-review.json';put(proof,{'actual_bed_receipt':ref(recp),'actual_bed_report':ref(bedp),'actual_XMF_manifest':ref(b['xmf_manifest']),'actual_XMF_XML':ref(b['xdmf']),'actual_conversion_report':ref(b['conversion_report']),'physical_case_id':b['physical_case_id'],'physical_condition_sha256':b['physical_condition_sha256'],'diagnostic_maxima':maxima,'full801_N3_actual_times_and_PartVTK_identity_verified':True,'all31658_initial_fluid_UIDs_current_and_finite_all801':True,'bed_diagnostics_do_not_grant_precision_or_visual_acceptance':True,'source_binding_flags_preserved_original_disabled':{k:b.get(k) for k in ['disabled','source_only','execution_allowed','full801_authorized']},'full_execution_authority':'outer Root969 registered request under actual active user goal','main_scientific_payload_IO':False,'case_credit':0})
base=load(root(960)/'enabled-full801-render-request.json');w=load(base['command'][-1]);worker=Path(base['command'][base['command'].index('--worker')+1]);api=runpy.run_path(str(worker));aid='root-stage1-f5-m095-t080-actual971-full801-116-023-nvme-hard2gib-root984';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();rid=f"F5/{b['case_id']}/{aid}";controller=O/'fair-render-controller.py';controller.write_bytes((root(960)/'fair-render-controller.py').read_bytes());md={str(p):sha(p) for p in [worker,Path(w['renderer']),Path(w['pvpython']),Path(base['command'][1]),controller,root(928)/'fair_CPU_dispatch.py',proof,Path(bq['binding']),Path(b['xmf_manifest']),Path(b['xdmf']),Path(b['full_native_receipt']),Path(b['conversion_report']),Path(b['full_typed_receipt']),recp,bedp,root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(64)/'resource-window-approval.json']};w.update(family_id='F5',case_id=b['case_id'],physical_case_id=b['physical_case_id'],manifest=b['xmf_manifest'],attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root='/tmp/ds02-visual-render-cache-root984',input_files=sorted(md),input_sha256=md,actual_converter_scope_sha256=b['source_h5_physical_condition_sha256'],canonical_source_scope_sha256=b['physical_condition_sha256']);api['validate_request'](w,execution=True);assert api['_manifest_metadata'](w)['manifest']==w['manifest'];wp=O/'enabled-render-wrapper.json';put(wp,w);outer={**md,str(wp):sha(wp),b['trajectory_h5']:b['trajectory_h5_sha256']};q=base.copy();q.update(case_id=b['case_id'],physical_case_id=b['physical_case_id'],attempt_id=aid,attempt_root=str(ar),physical_condition_sha256=b['physical_condition_sha256'],actual_converter_scope_sha256=b['source_h5_physical_condition_sha256'],source_h5_producer_sha256=b['trajectory_h5_sha256'],command=[str(L/'.venv/bin/python'),base['command'][1],'--worker',str(worker),'--request',str(wp)],input_files=sorted(outer),input_sha256=outer);qp=O/'enabled-full801-render-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: independently close actual M095 full801 bed and register complete ParaView render','--',*paths],cwd=R,check=True);print({'root':str(O),'diagnostic_maxima':maxima,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
