from pathlib import Path
import json,hashlib,collections,datetime,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_actual197_F6_running_independent_and_F4_16_preserved_successor_checkpoint_922';O.mkdir(exist_ok=False)
load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'));sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_121.json';cp=load(prev);new=load(root(921)/'actual-integration-review.json')['decisions'];assert len(new)==2;accepted=cp['accepted_decisions']+new;rows=[load(p) for p in accepted];counts=dict(collections.Counter(x['family_id'] for x in rows));assert len(rows)==197 and counts=={'F1':48,'F2':24,'F3':12,'F4':37,'F5':4,'F6':24,'F7':48};assert len({r.get('physical_case_id',r['case_id']).replace('F4_DROP_B08_','F4_DROP_') for r in rows})==197 and len({r['physical_condition_sha256'] for r in rows})==197
observations=[]
for n in [854,856,860,864,865,871,872,873,877,879,884,885,886,887,891,892,893,920,923,924]:
 p=root(n);c=load(p/'controller-launch-process.json');pr=Path('/proc')/str(c['pid']);f=(pr/'stat').read_text().split(') ',1)[1].split() if pr.exists() else [];live=bool(f and f[0]!='Z' and f[19]==c['proc_start_ticks']);assert sha(c['controller'])==c['controller_sha256'];assert not live or c['controller'].encode() in (pr/'cmdline').read_bytes();details=[]
 for qp in list(p.glob('*request.json'))+list((p/'requests').glob('*request.json')):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};details.append({'request':ref(qp),'case_id':q['case_id'],'receipt_path':str(rp),'receipt':ref(rp) if rp.exists() else None,'status':r.get('status','not_launched'),'returncode':r.get('returncode'),'worker_pid':r.get('pid'),'visual_case_credit':0})
 observations.append({'root':n,'launch':ref(p/'controller-launch-process.json'),'live_same_handle':live,'state':f[0] if f else None,'requests':details,'scientific_worker_restart':False})
ledgerbytes=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(ledgerbytes);assert ledger['limits']==cp['limits'] and ledger['adopted_at_utc']==cp['adopted_at_utc'] and ledger['deadline_utc']==cp['deadline_utc'];assert sum(x.get('cpu_threads',0) for x in ledger['reservations'])<=64 and sum(x.get('cpu_threads',0)==24 for x in ledger['reservations'])<=2;stat=os.statvfs('/home/jade');free=stat.f_bavail*stat.f_frsize;assert free>=500*1024**3
at=datetime.datetime.now(datetime.timezone.utc).isoformat();put(O/'same-handle-pipeline-observations.json',{'at_utc':at,'controllers':observations,'resource_limits':ledger['limits'],'resource_adopted_at':ledger['adopted_at_utc'],'resource_deadline':ledger['deadline_utc'],'active_reservations':ledger['reservations'],'Home_free_GiB':free/1024**3,'scientific_payload_reads_or_hashes':False})
out={k:v for k,v in cp.items() if k not in ['active_reservations','actual_progress','accepted_decisions','new_accepted_decisions','predecessor','predecessor_sha256']};out.update(checkpoint=122,at_utc=at,predecessor=str(prev),predecessor_sha256=sha(prev),stage1_visual_accepted_complete_independent_cases=197,accepted_per_family=counts,accepted_decisions=accepted,new_accepted_decisions=new,attempt_counts=dict(collections.Counter(x['kind'] for x in ledger['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ledger['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ledger['charges'])/3600,active_reservations=ledger['reservations'],ledger_sha256_at_checkpoint=hashlib.sha256(ledgerbytes).hexdigest(),home_free_gib=free/1024**3,previous_goal_turn_classification='progress: actual197 visual independent cases; first actual F6 full241 renderer running after safe metadata-only retirement of original860 and lock-holding856. Six completed856 results retained and distinct924 queues16 future full1201. Prototype155 publication defect independently held before science. No cumulative budget/deadline reset.',actual_progress={'new_accepted_visual_cases':2,'new_visual_decisions':[ref(p) for p in new],'F6_actual24_ready':ref(root(917)/'actual-ready24-independent-dispatch-audit.json'),'F7_actual48_family_complete':ref(root(914)/'actual-delivery-and-completion-audit.json'),'independent_F6_920_launch':ref(root(920)/'controller-launch-process.json'),'original860_metadata_only_retirement':ref(root(920)/'metadata-only-original860-retirement-proof.json'),'original856_metadata_only_retirement':ref(root(923)/'metadata-only-original856-retirement-proof.json'),'F4_future16_no_completed_rerun_924':ref(root(924)/'controller-launch-process.json'),'F4_zerojob923_metadata_directory_error':ref(root(924)/'zerojob923-path-correction-review.json'),'source155_publication_hold':ref(root(925)/'actual155-publication-source-review.json'),'actual_pipeline_observations':ref(O/'same-handle-pipeline-observations.json'),'scientific_algorithm_changes':False,'Root_scientific_payload_reads_or_hashes':False,'Root_PNG_personal_review':False,'Home_floor_gib':500,'shared_CPU_reservation_cap':64,'renderer_global_cap':2,'extra_persistent_storage_path_question':'pending user information; no scientific history deleted'})
out['source_agents']={'/root/f6_endpoint_initial_qa':'fresh125 two F4actual856 approved and adopted921; fresh126 watches independent920 first2 all241 images','/root/f5_bed_recovery':'fresh156 conversion-lock metadata audit; fresh155 source publication held925, distinct157 full toy publication/cleanup requested','/root/production_recovery':'fresh111 independent review final fresh110 NVMe renderer proposal, no actual producer launch'}
out['next_executable_tasks']=['Observe same920 full241 running receipt, no latency restart; delegate all11contact+9keys only after actual0. Count only after metadata closure and unique actual physical scope.','Observe same924 future16 full1201 renderer, preserve8 completed old773/856 and original immutable requests. Admission keeps original12GiB and shared500GiB floor with2GiB extra margin.','Adopt fresh156 lock audit before retiring any32GiB conversion metadata waiter; protect unrelated920/924 workers. Publishcap typed prototype157 must exercise actual wrapper publication with toy inputs including cleanup, then main independent review before new4GiB registered successor.','Review fresh111 final source110 NVMe renderer; never replace or repeat already completed/running920 cases.','F3 actual896/897 prepared16 remain disabled; new native only after Home and live CPU/GPU allowance; retain original cumulative window/deadline.','Resolve persistent storage pending user information while continuing safe pipeline work. Allcases retain numerical/QN/QE limitations.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_122.json',out);(O/'checkpoint-validation-and-build.py').write_bytes(Path(__file__).read_bytes());paths=[H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_122.json',*O.iterdir(),*root(925).iterdir(),root(924)/'controller-launch-process.json'];assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',*[str(p.relative_to(R)) for p in paths]],cwd=R,check=True);subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True);subprocess.run(['git','commit','-m','Record 197 visual cases and actual independent F6 render under cumulative budget'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'checkpoint':122,'accepted':197,'families':counts,'GPUh':out['gpu_hours_charged'],'CPUcoreh':out['cpu_core_hours_charged'],'attempts':out['attempt_counts'],'HomeGiB':free/1024**3,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
