from pathlib import Path
import json,hashlib,subprocess,datetime,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_189.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==270 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_190.json').exists()
prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_165_f2_first8_first24_final48_membership_audit_v1');commit='53c381850dc47ef3db2ec3bf955e75a84a8b939d';files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(files)==7;before={}
for rel in files:
 raw=subprocess.check_output(['git','show',commit+':'+rel],cwd=W);assert raw==(W/rel).read_bytes();dst=R/rel
 if dst.exists():assert dst.read_bytes()==raw
 else:dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(raw)
 before[str(W/rel)]=sha(W/rel);before[str(dst)]=sha(dst)
P=W/prefix;rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh165.py')],cwd=P,text=True,capture_output=True);assert rv.returncode==0,rv.stderr;assert before=={p:sha(p) for p in before}
m=load(P/'metadata/f2-first8-first24-final48-membership.json');sources=m['authoritative_sources']
for s in sources.values():assert sha(s['path'])==s['sha256']
g=m['groups'];ids={k:{a['physical_case_id'] for a in rows} for k,rows in g.items()};assert len(ids['first8'])==8 and len(ids['first24'])==24 and len(ids['final48'])==48 and ids['first8']<ids['first24']<ids['final48']
registry=load(root(1205)/'full336-role-aware-physical-registration-progress-index.json');assert ids['final48']=={a['physical_case_id'] for a in registry['cases'] if a['family_id']=='F2'}
accepted={}
for path in cp['accepted_decisions']:
 a=load(path)
 if a['family_id']=='F2':assert a['physical_case_id'] not in accepted;accepted[a['physical_case_id']]=(path,a)
assert len(accepted)==33 and ids['first24']<=set(accepted)<=ids['final48'];actual=[]
for x in g['first24']:
 p,a=accepted[x['physical_case_id']];assert a['case_id']==x['case_id'];assert a.get('frames',a.get('full_native_frames'))==401;assert a.get('q_n',a.get('q_n_granted',False)) in (False,0) and a.get('q_e',a.get('q_e_granted',False)) in (False,0)
 status=a['status'];assert 'visual' in status and ('approved' in status or 'pass' in status);actual.append({'case_id':a['case_id'],'physical_case_id':a['physical_case_id'],'accepted_decision':ref(p),'accepted_decision_top_condition_sha256':a['physical_condition_sha256'],'accepted_top_is_not_assumed_native_request_scope':True,'first8_member':a['physical_case_id'] in ids['first8'],'actual_full_native_frames':401,'status':status,'precision_status':'视觉检查通过、数值精度未验收'})
assert len(actual)==24 and sum(a['first8_member'] for a in actual)==8
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
O=H/'root_stage1_source165_F2_authoritative_first8_first24_subset_final48_and_actual24_visual_delivery_closed_checkpoint_1210';O.mkdir(exist_ok=False)
put(O/'source165-exact-adoption-readonly-validator-and-source-hash-proof.json',{'source_commit':commit,'exact_adopted_files':[ref(R/f) for f in files],'source_and_adopted_hashes_unchanged':before,'validator_returncode':rv.returncode,'validator_stdout':rv.stdout,'source186_snapshot_F2_32_preserved':True,'current_cp189_F2_33_independently_verified':True,'all_source_refs':sources,'new_case_credit':0,'main_scientific_payload_IO':False})
proof=O/'F2-first8-first24-final48-physical-membership-and-actual24-visual-delivery.json';put(proof,{'schema':'ds02.stage1.F2.actual24-visual-membership-closure.v1','first8_count':8,'first24_count':24,'final48_count':48,'first8_subset_first24_subset_final48':True,'actual_accepted_first8':8,'actual_accepted_first24':24,'actual_accepted_current_F2':33,'source_explicit_membership':ref(P/'metadata/f2-first8-first24-final48-membership.json'),'case_refs':actual,'full_native_401_case_acceptance_evidence_preserved':True,'per_case_UID_N3_time_scope_proof_remains_in_existing_acceptance_sources':True,'replicas_views_retries_not_counted':True,'first48_source_generation_no_science_case_credit_preserved':True,'native_request_vs_source_declared_vs_accepted_top_roles_separate':True,'Q_N':0,'Q_E':0,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收'})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=190,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: exactsource165 metadataadopted, mainexplicitF2first8/24/final48 physicalmembership subsets independentlyverified. Allfirst24actualaccepted full401cases closedbycurrentcp189 decisionrefs, actualF2=33 vsold18632snapshot preserved. No newcasecredit or numericalreference claim.',authorized_work_state='Active270/336. F2actualfirst24visualdelivery membershipclosed8/24subset48; F2currently33. F3actual1128full836QI0 awaiting148personalreview. F5full801actual1152/1130originalhandleslive, next192personalreview; actualF5second24batch11/24 preservingfrozen8. Original951lastF6stillpending.')
cp['actual_progress']['F2_first8_first24_subset_final48_actual24_visual_delivery']=ref(proof);cp['source_agents']['f6_endpoint_initial_qa']='fresh166 nextpublishedunacceptedF2ororiginal951lastF6personalreview; optionaloldernativealiasesJSONclosurewhilewaiting';cp['next_executable_tasks']=['Adopt fresh148 actual1128 F3personal35contacts9keys andcreditonlyaftervisualpasses','Fresh192 afterreal0publish original1152/1130 F5personal34contacts9keys','Fresh166 nextactualpublishedunacceptedF2orlastF6original951personalreview; neverrestartwaitinghandle','Continue66 realdeliveries, F5actualfirst24extensionkeepsfrozen8 andQ-N/Q-E0']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_190.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=files+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_190.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify F2 actual first24 visual cases and nested final48 membership','--',*paths],cwd=R,check=True);print({'checkpoint':190,'accepted':270,'F2actualfirst24':24,'F2current':33,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
