from pathlib import Path
import json,hashlib,collections,datetime,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_actual176_delegated_F2_F7_visual_and_live_capacity_checkpoint_890';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def root(n):return next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):
 p=Path(p);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');t.replace(p)
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_114.json';cp=load(prev);new=[]
for n in [882,883,888,889]:new+=load(root(n)/'actual-integration-review.json')['decisions']
assert len(new)==6;accepted=cp['accepted_decisions']+new;rows=[load(p) for p in accepted];counts=dict(collections.Counter(x['family_id'] for x in rows));assert len(rows)==176 and counts=={'F1':48,'F2':24,'F3':12,'F4':31,'F5':4,'F6':24,'F7':33};assert len({r.get('physical_case_id',r['case_id']).replace('F4_DROP_B08_','F4_DROP_') for r in rows})==176 and len({r['physical_condition_sha256'] for r in rows})==176;assert all(x<=48 for x in counts.values())
observations=[]
for n in [816,827,832,839,850,854,855,856,860,864,865,866,871,872,873,874,875,876,877,878,879,880,881,884,885,886,887]:
 p=root(n);c=load(p/'controller-launch-process.json');pr=Path('/proc')/str(c['pid']);f=(pr/'stat').read_text().split(') ',1)[1].split() if pr.exists() else [];live=bool(f and f[0]!='Z' and f[19]==c['proc_start_ticks']);assert sha(c['controller'])==c['controller_sha256'];assert not live or c['controller'].encode() in (pr/'cmdline').read_bytes();states=collections.Counter();details=[]
 for qp in list(p.glob('*request.json'))+list((p/'requests').glob('*request.json')):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};status=r.get('status','future request or launcher preflight pending');states[(status,r.get('returncode'))]+=1;worker=r.get('pid');details.append({'request':ref(qp),'physical_case_id':q.get('physical_case_id'),'actual_receipt_path':str(rp),'actual_receipt':ref(rp) if rp.exists() else None,'status':status,'returncode':r.get('returncode'),'error':r.get('error'),'actual_worker_pid':worker,'actual_worker_exists':bool(worker and (Path('/proc')/str(worker)).exists()),'visual_case_credit':0})
 result=p/'controller-result.json';observations.append({'root':n,'actual_launch':ref(p/'controller-launch-process.json'),'pid':c['pid'],'proc_start_ticks':c['proc_start_ticks'],'live_same_handle':live,'state':f[0] if f else None,'terminal_result':ref(result) if result.exists() else None,'request_state_counts':[{'status':k[0],'returncode':k[1],'count':v} for k,v in states.items()],'requests':details,'no_restart_on_IO_or_capacity_wait':True})
ledger_bytes=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(ledger_bytes);assert ledger['limits']==cp['limits'];assert ledger['limits']['gpu_seconds']==512*3600 and ledger['limits']['cpu_core_seconds']==3840*3600 and ledger['limits']['qualification_attempts']==1024 and ledger['limits']['production_attempts']==720;assert ledger['adopted_at_utc']==cp['adopted_at_utc'] and ledger['deadline_utc']==cp['deadline_utc'];assert sum(x.get('cpu_threads',0) for x in ledger['reservations'])<=64;assert sum(x.get('cpu_threads',0)==24 for x in ledger['reservations'])<=2;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize;assert free>=500*1024**3
at=datetime.datetime.now(datetime.timezone.utc).isoformat();put(O/'same-handle-real-pipeline-observations.json',{'at_utc':at,'controllers':observations,'no_Root_scientific_payload_reads_or_hashes':True,'observed_scientific_completion_is_not_visual_approval':True});put(O/'resource-window-confirmation.json',{'limits':ledger['limits'],'adopted_at_utc':ledger['adopted_at_utc'],'deadline_utc':ledger['deadline_utc'],'no_cumulative_usage_or_deadline_reset':True,'home_free_gib':free/1024**3,'CPU_reserved':sum(x.get('cpu_threads',0) for x in ledger['reservations']),'storage_reserved_gib':sum(x.get('new_storage_bytes',0) for x in ledger['reservations'])/1024**3,'renderer_global_cap':2,'latest_user_window_confirmed':True})
# Metadata admission refusal is distinct from a scientific failure, no solver/typed worker ran.
refusals=[r for x in observations if x['root']==816 for r in x['requests'] if r['status']=='failed'];assert len(refusals)==1 and refusals[0]['error']=='RuntimeError: Home free-space floor would be crossed' and refusals[0]['actual_worker_pid'] is None and refusals[0]['returncode'] is None
put(O/'F2_816_no_worker_Home_capacity_hold.json',{'actual_request_and_receipt':refusals[0],'actual_completed_typed_retained':3,'actual_completed_XMF_827_retained':3,'remaining_typed':21,'scientific_failure':False,'original_bytes_preserved':True,'next_action':'Distinct successor for remaining21 with percase live Home reserved storage and CPU admission; preserve existing3 actual typed and XMF and all24 actual native, do not rerun science.'})
out={k:v for k,v in cp.items() if k not in ['active_reservations','actual_progress','accepted_decisions','new_accepted_decisions','predecessor','predecessor_sha256']};out.update(checkpoint=115,at_utc=at,predecessor=str(prev),predecessor_sha256=sha(prev),stage1_visual_accepted_complete_independent_cases=176,accepted_per_family=counts,accepted_decisions=accepted,new_accepted_decisions=new,attempt_counts=dict(collections.Counter(x['kind'] for x in ledger['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ledger['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ledger['charges'])/3600,active_reservations=ledger['reservations'],ledger_sha256_at_checkpoint=hashlib.sha256(ledger_bytes).hexdigest(),home_free_gib=free/1024**3,previous_goal_turn_classification='progress: six distinct F2/F7 full-window delegated visual cases adopted; actual F5 native and typed progress; F3 actual seven native completed; bounded additive metadata and capacity controllers restored without changing scientific workers or rewriting consumed artifacts',actual_progress={'new_accepted_visual_cases':6,'new_visual_decisions':[ref(p) for p in new],'native_typed_XMF_or_bed_results_do_not_grant_case_credit':True,'actual_pipeline_observations':ref(O/'same-handle-real-pipeline-observations.json'),'resource_window_confirmed_without_reset':ref(O/'resource-window-confirmation.json'),'F2_816_Home_prelaunch_hold':ref(O/'F2_816_no_worker_Home_capacity_hold.json'),'F3_original839_completed0':7,'F5_original850_completed0':12,'native_remaining_controllers':[ref(root(n)/'controller-launch-process.json') for n in [871,884]],'typed_XMF_bed_consumers':[ref(root(n)/'controller-launch-process.json') for n in [854,864,865,872,873,877,879,885]],'full_window_renderer_consumers':[ref(root(n)/'controller-launch-process.json') for n in [856,860,886,887]],'scientific_algorithm_changes':False,'Root_scientific_payload_reads_or_hashes':False,'Root_PNG_personal_review':False,'Home_floor_gib':500,'shared_CPU_reservation_cap':64,'renderer_global_cap':2,'conversion_serial_CPU2':True,'extra_persistent_storage_path_question':'pending user information; no scientific history deleted'})
out['source_agents']={'/root/production_recovery':'fresh105106 F2 three complete accepted; fresh107 disabled own F3 remaining16 source underway','/root/f6_endpoint_initial_qa':'fresh122 actual856 firsttwo full1201 renders completed0; delegated51contacts9keys visual review underway','/root/f5_bed_recovery':'fresh146147 A032A033A034 accepted; A031 duplicate preserved zero credit; fresh148 explicit A036A037 review underway'}
out['next_executable_tasks']=['Restore only F2 remaining21 typed/XMF after no-worker Home refusal using percase CPU+storage admission; preserve actual816/827 first3 and actual812 native24; renderer887 actual originals unchanged, additive additional21 consumer needed.','Observe actual F5 native871 remaining22 and F3 native884 remaining13 shared registration capacity waits; preserve actual original12 F5 and original7 F3, no scientific duplicate or stale lease inference.','Observe own full native CPU2 conversion consumers and shared renderer886 F3 percase true-binding full836; F2/F5 renderer887 retains valid old backlog and waits actual860 F6 full241 drain.','Adopt fresh122 full1201 F4 two visual decisions and fresh148 F7 A036A037 independently; per-family accepted cap48 and all-case ID+canonical hash dedup.','Review disabled fresh107 own F3 remaining16 source within actual fourcorners domain; register jobs only with live admission; no Gemini.','Obtain additional persistent storage path if provided; until then Home500GiB floor remains authoritative, retain all prior scientific data and continue admissible independent visual backlog.'];put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_115.json',out);(O/'checkpoint-validation-and-build.py').write_bytes(Path(__file__).read_bytes())
paths=[H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_115.json']+list(O.iterdir())
for n in [882,883,888,889]:paths += [p for p in root(n).rglob('*') if p.is_file()]
for fam,pkg in [('F3','root_followup_105_f2_first24_visual_decisions_v1'),('F3','root_followup_106_f2_first24_visual_decisions_v1'),('F5','root_followup_146_f7_a031_a032_visual_review_v1'),('F5','root_followup_147_f7_a033_a034_visual_review_v1')]:paths += [p for p in (L/'campaigns/ds-data-02/families'/fam/'handoff_20261003'/pkg).rglob('*') if p.is_file()]
for n in [850,880]:paths.append(root(n)/'controller-result.json')
assert all(p.suffix in ['.json','.py','.md'] for p in paths);assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',*[str(p.relative_to(R)) for p in paths]],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: accept176 independent visual cases and confirm cumulative512GPU resource window'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'checkpoint':115,'accepted':176,'families':counts,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'GPUh':out['gpu_hours_charged'],'CPUcoreh':out['cpu_core_hours_charged'],'attempts':out['attempt_counts'],'Home_free_GiB':out['home_free_gib']}))
