from pathlib import Path
import json,hashlib,subprocess,datetime,runpy,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.bi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
import sys
producer,tag,number=sys.argv[1:];producer=int(producer);number=int(number)
qc=load(root(producer)/'controller-config.json');bedqp=next(Path(p) for p in qc['requests'] if load(p)['tag']==tag);bedq=load(bedqp);bp=Path(bedq['binding']);bedbinding=load(bp);bedar=Path(bedq['attempt_root']);bedreceipt=bedar/'execution-receipt.json';bedreport=bedar/'audit-output/c082s1-full-event-bed-footprint-audit.json';assert (load(bedreceipt)['status'],load(bedreceipt)['returncode'])==('completed',0)
base=load(root(984)/'enabled-full801-render-request.json');w=load(base['command'][-1]);O=H/f'root_stage1_F5_{tag}_actual{producer}_bed0_full801_UID_footprint_original116023944_expected34_render_{number}';O.mkdir(exist_ok=False);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_179.json');ids={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};t0=load(bedbinding['full_typed_conversion_report']);x0=load(bedbinding['xmf_manifest']);frozen=O/'completed-bed-progress-frozen.json';frozen.write_bytes((root(producer)/'actual-progress.json').read_bytes());assert any(r.get('tag')==tag and r.get('actual_full801_bed_worker_output0') is True for r in load(frozen)['results']);source=O/'actual-bed0-to-render-input-lineage.json';rb=O/'registered-render-binding.json'
put(rb,{'schema':'ds02.actual-completed-bed-to-full801-render-binding.v1','physical_case_id':bedq['physical_case_id'],'case_id':bedq['case_id'],'canonical_physical_condition_sha256':bedq['physical_condition_sha256'],'actual_converter_scope_sha256':t0['hash_scopes']['physical_condition_sha256'],'original_disabled_bed_binding':ref(bp),'actual_bed_request':ref(bedqp),'actual_bed_receipt':ref(bedreceipt),'actual_bed_report':ref(bedreport),'actual_typed_report':ref(bedbinding['full_typed_conversion_report']),'actual_XMF_manifest':ref(bedbinding['xmf_manifest']),'future_render_hashes':{'receipt':None,'report':None},'no_physical_or_numerical_pass_from_exit_code':True,'case_credit':0})
src={'schema':'ds02.actual-bed0-full801-render-input-lineage.v1','case_id':bedq['case_id'],'physical_case_id':bedq['physical_case_id'],'physical_condition_sha256':bedq['physical_condition_sha256'],'actual_converter_scope_sha256':t0['hash_scopes']['physical_condition_sha256'],'bed_report':str(bedreport),'bed_receipt':str(bedreceipt),'xmf_manifest':bedbinding['xmf_manifest'],'typed_conversion_report':bedbinding['full_typed_conversion_report'],'native_receipt':bedbinding['full_native_receipt'],'typed_receipt':bedbinding['full_typed_receipt'],'xmf_receipt':bedbinding['xmf_receipt'],'trajectory_h5':t0['output_hdf5'],'trajectory_h5_sha256_producer_attested':t0['output_sha256'],'xdmf':x0['xdmf'],'xdmf_sha256':x0['xdmf_sha256'],'renderer_worker':base['command'][base['command'].index('--worker')+1],'renderer_entry':base['command'][1],'renderer':w['renderer'],'pvpython':w['pvpython'],'binding':str(rb),'attempt_root':None,'disabled':True,'source_only':True,'execution_allowed':False,'future_output_hashes':{'receipt':None,'report':None},'expected_contact_sheets':34,'case_credit':0,'input_sha256':{str(p):sha(p) for p in [bedqp,bp,bedreceipt,bedreport,Path(bedbinding['full_typed_conversion_report']),Path(bedbinding['full_typed_receipt']),Path(bedbinding['full_native_receipt']),Path(bedbinding['xmf_manifest']),Path(bedbinding['xmf_receipt']),Path(x0['xdmf']),Path(bedbinding['source_definition']),frozen,rb]}}
src['input_sha256'][t0['output_hdf5']]=t0['output_sha256'];put(source,src)
brp=Path(src['bed_report']);br=load(brp);brec=load(src['bed_receipt']);x=load(src['xmf_manifest']);t=load(src['typed_conversion_report']);nr=load(src['native_receipt']);tr=load(src['typed_receipt']);xr=load(src['xmf_receipt']);pid=src['physical_case_id'];assert pid not in ids
assert all((r['status'],r['returncode'])==('completed',0) for r in [brec,nr,tr,xr]);assert br['status']=='completed_worker_output_pending_root_review' and br['bound_actual_inputs']['case_id']==src['case_id'] and br['bound_actual_inputs']['physical_case_id']==pid
assert br['scan']['frames_scanned']==len(br['frame_reports'])==x['frames']==t['frames']==801 and br['scan']['particle_axis_count']==x['particles']==t['particles']==194427 and br['scan']['initial_fluid_uid_count']==31658
assert br['physical_condition_sha256']==nr['request']['physical_condition_sha256']==x['canonical_physical_condition_sha256']==src['physical_condition_sha256'];assert br['source_h5_physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==x['source_h5_physical_condition_sha256']==src['actual_converter_scope_sha256']
assert t['output_sha256']==x['source_h5_sha256']==src['trajectory_h5_sha256_producer_attested'];h5=t['output_hdf5'];assert h5==src['trajectory_h5']
for rr in [brec,xr]:assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
assert not br['source_arrays_modified'] and not br['source_arrays_dropped_or_masked'] and br['initial_fluid_uid_reference']['all_uids_retained_as_reference_denominator']
times=x['actual_time_s'];grids=ET.parse(src['xdmf']).findall('.//Grid[@GridType="Uniform"]');fs=t['lifecycle']['frame_summary'];assert len(grids)==len(times)==len(fs)==801 and times==[f['time'] for f in fs]==[float(g.find('Time').get('Value')) for g in grids]==[f['time_s'] for f in br['frame_reports']];assert times[0]==0 and times[-1]>=16 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
for i,(f,g,tf) in enumerate(zip(br['frame_reports'],grids,fs)):
 assert f['frame']==tf['frame']==i and f['initial_fluid_uid_count']==f['current_valid_type3_fluid_count']==f['finite_mass_current_fluid_count']==f['finite_position_current_fluid_count']==31658 and f['particle_axis_count']==194427 and tf['active_particles']==194427 and tf['missing_particles']==0
 assert f['nonfinite_mass_current_fluid_count']==f['nonfinite_position_current_fluid_count']==f['nonfinite_initial_fluid_uid_count']==0 and f['uid_tracking']['missing_initial_uid']['count']==f['uid_tracking']['unexpected_current_uid']['count']==0 and not f['uid_tracking']['unexplained'] and not f['unexplained_state']['nonfinite_or_lost_initial_uid_present']
 dom=f['bed_domain'];assert dom['x_bounds_m']==[-.2,4.8] and dom['y_bounds_m']==[-.22,.22] and dom['finite_bed_footprint_evaluable_count']==31658 and dom['x_outside_exact_profile_domain_count']==dom['y_outside_actual_bed_footprint_with_x_in_domain_count']==0
 assert f['penetration']['depth_unevaluable_current_fluid_count']==0 and f['penetration']['only_finite_current_type3_inside_exact_x_y_bed_footprint']
 for name,threshold in [('one_dp',.02),('two_dp',.04)]:
  bin=f['penetration'][name];assert bin['threshold_m']==threshold and bin['count']==0 and bin['deepest_depth_m'] is None and bin['fraction_of_initial_fluid_uid_set']==bin['fraction_of_finite_bed_footprint_fluid']==0
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';vel=next(a for a in g.findall('Attribute') if a.get('Name')=='velocity');assert vel.get('AttributeType')=='Vector' and vel.find('DataItem').get('Dimensions')=='194427 3'
assert sha(src['xdmf'])==x['xdmf_sha256']==src['xdmf_sha256'];proof=O/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';put(proof,{'main_preparation_head':commit,'actual_bed_request':ref(bedqp),'original_disabled_bed_binding':ref(bp),'direct_actual_bed_worker_and_upstream_evidence_closed':True,'source_bytes_preserved':True,'actual_source_request':ref(source),'actual_bed_receipt':ref(src['bed_receipt']),'actual_bed_report':ref(brp),'actual_typed_receipt':ref(src['typed_receipt']),'actual_typed_report':ref(src['typed_conversion_report']),'actual_XMF_receipt':ref(src['xmf_receipt']),'actual_XMF_manifest':ref(src['xmf_manifest']),'all801_UID_fluid31658_finite_and_footprint_checked':True,'observed_counts_above_one_DP_and_two_DP_bins_zero':True,'diagnostic_bins_are_not_numerical_acceptance_thresholds':True,'sub_DP_positive_depth_is_not_quantified_by_zero_bin_counts':True,'bed_own_definition_plan_scope':br['source_plan_physical_condition_sha256'],'XMF_producer_plan_role':x.get('source_plan_physical_condition_sha256'),'source_canonical_scope':br['physical_condition_sha256'],'actual_H5_legacy_scope':br['source_h5_physical_condition_sha256'],'main_scientific_payload_IO':False,'visual_status':'pending actual complete render and personal delegated review','case_credit':0})


worker=Path(src['renderer_worker']);entry=Path(src['renderer_entry']);renderer=Path(src['renderer']);assert sha(worker)=='5d577e4b28e62906472bfba30ad445685f804be4ba5d8bab44b4bab3d32e1621' and sha(entry)=='1c950c7456ea3b900b7ab37a6a4c4da7ea15f2e9f2691abca8d78eee347f659c' and sha(renderer)=='5e78f7b92ad7c6f1d15902e3ccacc9099affb04b1b992a42f540eb88241bde66';api=runpy.run_path(str(worker));controller=O/'fair-render-controller.py';controller.write_bytes((root(984)/'fair-render-controller.py').read_bytes());aid=f'root-stage1-f5-{tag.lower()}-actual{producer}-bed0-full801-original116023-frozen-progress-root{number}';ar=D/'families/F5'/src['case_id']/aid;assert not ar.exists();rid=f"F5/{src['case_id']}/{aid}";md={}
for p,h in src['input_sha256'].items():
 if Path(p).suffix=='.h5':assert p==h5 and h==t['output_sha256']
 elif Path(p).name=='actual-progress.json':
  assert Path(p)==root(1055)/'actual-progress.json';frozen=O/'root1055-completed-progress-frozen.json';frozen.write_bytes(Path(p).read_bytes());md[str(frozen)]=sha(frozen)
 else:assert sha(p)==h;md[p]=h
for p in [source,Path(src['binding']),proof,controller,root(928)/'fair_CPU_dispatch.py',entry,worker,renderer,Path(src['pvpython']),root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(64)/'resource-window-approval.json']:md[str(p)]=sha(p)
roles=O/'original-disabled-planning-versus-enabled-output-roles.json';put(roles,{'original_disabled_source':ref(source),'original_future_planning_attempt_root':src['attempt_root'],'actual_new_enabled_output':str(ar),'physical_case_id':pid,'actual_case_id':src['case_id'],'source_original_bytes_unchanged':True,'immutable_progress_snapshot_bound_instead_of_live_observer':ref(frozen),'source_original_801contact_count_correct34':True,'no_bed_precision_or_visual_acceptance_implied':True});md[str(roles)]=sha(roles)
w.update(family_id='F5',case_id=src['case_id'],physical_case_id=pid,physical_condition_sha256=src['physical_condition_sha256'],actual_converter_scope_sha256=src['actual_converter_scope_sha256'],registered_binding=src['binding'],future_render_product={'attempt_root':str(ar),'report':str(ar/'render/paraview-full-animation-report.json'),'report_sha256':None},manifest=src['xmf_manifest'],disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,future_input_hashes_null=False,attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root=f'/tmp/ds02-visual-render-cache-root{number}',input_files=sorted(md),input_sha256=md,expected_frames=801,expected_particles=194427,expected_contact_sheets=34,keyframe_indices=[0,100,200,300,400,500,600,700,800])
api['validate_request'](w,execution=True);assert api['_manifest_metadata'](w)['manifest']==src['xmf_manifest'];wp=O/'enabled-render-wrapper.json';put(wp,w);outer={**md,str(wp):sha(wp),h5:t['output_sha256']};q=base.copy();q.update(family_id='F5',case_id=src['case_id'],physical_case_id=pid,physical_condition_sha256=src['physical_condition_sha256'],actual_converter_scope_sha256=src['actual_converter_scope_sha256'],source_h5_producer_sha256=t['output_sha256'],expected_frames=801,expected_particles=194427,expected_contact_sheets=34,attempt_id=aid,attempt_root=str(ar),command=[str(L/'.venv/bin/python'),str(entry),'--worker',str(worker),'--request',str(wp)],input_files=sorted(outer),input_sha256=outer,root_scope='Own actual completedfull801 bed diagnostics checked; original116023 fullrender with frozen observer provenance. No precision/visual credit before realoutputreview.',full801_authorized=True,case_credit=0);qp=O/'enabled-full801-render-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close own full801 bed diagnostics and register bounded render','--',*paths],cwd=R,check=True);print({'root':number,'tag':tag,'bed801_checked':True,'contacts':34,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
