from pathlib import Path
import json,hashlib,subprocess,collections,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_176_f3_final48_complete_delivery_builder_v1');P=W/prefix;commit='cb9cec06854ec1790ae900b85471c54b59e41d0f';root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_273.json';ip=root(1362)/'full336-current309-actual-final48-delivery-progress-index.json';mp=root(1276)/'F3-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json';lp=root(1328)/'F3-FINAL48-ACTUAL39ACCEPTED-NINEPENDING-PRIMARY-DELIVERY.json';cp=load(cpfile);idx=load(ip);mem=load(mp)
assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['checkpoint']==273 and cp['stage1_visual_accepted_complete_independent_cases']==309
f3=[r for r in idx['cases'] if r['family_id']=='F3'];accepted=[r for r in f3 if r.get('accepted_decision')];assert len(accepted)==cp['accepted_per_family']['F3']==42 and len(f3)==48 and len(f3)-len(accepted)==6
assert set(r['physical_case_id'] for r in f3)==set(mem['registered_final48_physical_case_ids']) and set(mem['frozen_first8_physical_case_ids'])<=set(mem['actual_first24_physical_case_ids'])<=set(mem['registered_final48_physical_case_ids'])
audits=[]
for r in accepted:
 e=r['accepted_decision'];assert sha(e['path'])==e['sha256'] and e['path'] in cp['accepted_decisions'];d=load(e['path']);assert d['status'] in {'visual-approved-by-root','visual-approved-by-delegated-agent'} and d['family_id']=='F3' and d['physical_case_id']==r['physical_case_id'];audits.append({'physical_case_id':r['physical_case_id'],'actual_accepted_decision':e,'status':d['status']})
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};inputs={k:ref(v) for k,v in [('checkpoint',cpfile),('current_index',ip),('fixed_membership',mp),('legacy_catalog',lp)]}
args=['--checkpoint',str(cpfile),'--current-index',str(ip),'--membership',str(mp),'--legacy-catalog',str(lp)];rv=subprocess.run(['python3','-B',str(P/'validate_fresh176.py'),*args],capture_output=True,text=True)
assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names};result=json.loads(rv.stdout);assert result['status']=='PASS' and result['mode']=='readiness' and result['counts']=={'registered_final48':48,'accepted_visual':42,'pending_visual':6}
assert inputs=={k:ref(v['path']) for k,v in inputs.items()}
O=H/'root_stage1_source176_F3_completion_only_primary_reference_builder_current42_no_final48_independent_authority_status_gate_audit_1361';assert not O.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
now=datetime.datetime.now(datetime.timezone.utc).isoformat();proof=O/'source176-byte-exact-readonly-current42-readiness-and-main-authoritative-status-gate-proof.json'
proof.write_text(json.dumps({'schema':'ds02.main.F3.source176.builder-adoption.v1','at_utc':now,'source_commit':commit,'source_files':[ref(R/n) for n in names],'before_after_source_SHA':before,'inputs':inputs,'main_verified_checkpoint_index_sha_identity':True,'main_verified_all42_decision_SHA_status_and_authoritative_checkpoint_membership':audits,'source_validator_stdout':rv.stdout,'source_validator_stderr':rv.stderr,'actual_observed_readiness_counts':result['counts'],'actual_pending_physical_case_ids':result['pending'],'actual_final48_emitted':False,'new_case_credit':0,'Q_N':0,'Q_E':0,'source_builder_is_primary_reference_assembler_not_standalone_acceptance_or_full_integrity_authority':True,'code_audit_limits':{'source_acceptance_branch_uses_present_decision_dict_and_identity_but_not_status':True,'source_does_not_require_checkpoint_index_SHA_identity':True,'source_primary_completeness_checks_reference_presence_JSON_SHA_and_PNG_stat_not_full836_UID_or_terminal_runtime':True,'main_checked_current_authority_and_status_before_readonly_validation':True,'future_final48_output_requires_independent_main_actual_primary_full836_UID_N3_time_scope_and_runtime_unknown_review':True,'native_unknown_returncodes_and_typed154_unknown_are_not_to_be_promoted':True,'source_legacy_constants_unused_by_explicit_CLI_build_from_inputs':True,'source_completed_catalog_bytes_unchanged':True},'main_scientific_payload_IO':False,'main_personal_PNG_view_or_new_PNG_hash':False,'no_new_scientific_or_render_jobs':True},ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('Source176 is preserved byte for byte as a primary-reference assembly utility. Current real authority is checkpoint273/index309, with F3 42 accepted and 6 pending; the read-only validator emitted only temporary readiness and removed its own temporary outputs. Main independently checked checkpoint/index SHA identity and all accepted decision SHA/status/membership, which the source builder does not itself require. This is not a final48 delivery or a new integrity certificate. A future final48 assembly must first have all48 real accepted decisions and then pass main actual producer/frame/UID/N3/time/scope/runtime-unknown review. Original unknown native/typed returncodes remain unknown. Source209 report transcription corrections and absent plan fields remain explicit; no scientific payload reads, launches, or case increments occurred.\n')
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: integrate F3 completion-only reference builder with main authority gate audit','--',*paths],cwd=R,check=True);print(json.dumps({'source176_current42_pending6_readonly_validation':result,'adoption_proof':ref(proof),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
