from pathlib import Path
import json,hashlib,copy,datetime,subprocess,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
P=R/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_168_f3_assigned_f6_fulltime_floatinginfo_worker_v1';ic=root(1302);stock=load(ic/'enabled-inventory-runner-request.json');cr=load(ic/'controller-result.json');assert (cr['status'],cr['returncode'])==('completed',0);rp=Path(cr['actual_receipt']);ir=load(rp);assert (ir['status'],ir['returncode'])==('completed',0) and ir['request_sha256']==sha(ic/'enabled-inventory-runner-request.json')
for p,v in stock['input_sha256'].items():assert ir['input_hashes_at_launch'][p]==ir['input_hashes_after_run'][p]==v
invp=rp.parent/'inventory/inventory-report.json';inv=load(invp);assert inv['status']=='completed' and inv['returncode']==0 and inv['entry_count']==len(inv['entries'])==47;bm=load(root(1300)/'47-own-full241-native-time-bindings-for-official-rigid-export.json');bindings={x['physical_case_id']:x for x in bm['cases']};srcl=load(P/'requests/f6-final48-fulltime-floatinginfo-disabled-request-index.json')['requests'];native={x['case']['physical_case_id']:x for x in srcl};entries={x['physical_case_id']:x for x in inv['entries']};assert len(entries)==len(native)==len(bindings)==47
for pid,e in entries.items():assert e['bytes_before']==e['bytes_after']==180376 and re.fullmatch('[0-9a-f]{64}',e['sha256']) and e['path']==str(Path(native[pid]['native']['data_root'])/'PartFloatInfo.ibi4')
assert not list(H.glob('root*_1303'));O=H/'root_stage1_F6_last_DZXY_S1375_YAWP18_full241_official_rigid_motion_Part_hypothesis_pilot_inventory47_closed_Root142928_CPU2_1303';O.mkdir();cl=O/'actual47-small-IBI4-inventory-independent-metadata-closure.json';put(cl,{'schema':'ds02.main.F6.IBI4inventory.actual-closure.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'registered_inventory_request':ref(ic/'enabled-inventory-runner-request.json'),'inventory_receipt':ref(rp),'inventory_report':ref(invp),'inventory_controller_result':ref(ic/'controller-result.json'),'registered_metadata_and_guard_input_hashes_match_before_after':True,'actual_entries':47,'total_observed_IBI4_bytes':sum(e['bytes_before'] for e in entries.values()),'worker_only_scientific_payload_hashing':True,'main_scientific_payload_IO':False,'case_credit':0})
pid='F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025';q=copy.deepcopy(native[pid]);b=bindings[pid];e=entries[pid];ar=D/'families/F6'/q['case']['case_id']/'root-stage1-f6-last-dzxy-s1375-yawp18-full241-rigid-history-source168-root1303';assert not ar.exists();q.update(disabled=False,source_only=False,execution_allowed=True,status='root_enabled_pilot_output_contract_under_test');q['native']['rigid_state_input']['inventory_binding'].update(report_path=str(invp),report_sha256=sha(invp),entry_source_sha256=e['sha256']);q['time_contract'].update(native_times_s=b['native_times_s'],native_time_tolerance_s=b['native_time_tolerance_s'],native_time_source=b['manifest']);q['official_export']['part_contract'].update(pilot_required=True,mode='frame_index',expected_values=list(range(241)),authority='Expected0..240 output contract under test by first actual pilot; no prior observed Part proof claimed.');q['output'].update(directory=str(ar/'floatinginfo'),report_path=str(ar/'floatinginfo/fulltime-rigid-motion-report.json'));q['worker']['path']=str(P/'workers/run_fulltime_floatinginfo_fresh168.py');q['worker']['sha256']=sha(q['worker']['path']);q['main_inventory_closure']=ref(cl);q['main_actual_time_binding']=b;sp=O/'enabled-fulltime-floatinginfo-pilot-spec.json';put(sp,q)
controller=O/'registered-pilot-controller.py';controller.write_bytes((ic/'registered-inventory-controller.py').read_bytes());inputs={p:s for p,s in stock['input_sha256'].items() if p.endswith(('fair_CPU_dispatch.py','launch.py','root_home_floor_inventory_policy.py','ds_data02_runtime_v2.py','ds_data02_strict_dispatch_v1.py','resource-window-approval.json'))};inputs.update({str(sp):sha(sp),str(controller):sha(controller),str(cl):sha(cl),str(invp):sha(invp),str(rp):sha(rp),q['worker']['path']:q['worker']['sha256'],e['path']:e['sha256'],q['official_export']['binary_path']:q['official_export']['binary_sha256'],q['official_export']['help_path']:q['official_export']['help_sha256']})
for k in ['native_receipt','manifest','typed_report','xdmf']:inputs[b[k]['path']]=b[k]['sha256']
a={k:copy.deepcopy(stock[k]) for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']};a.update(schema='ds02.runner-request.v2',family_id='F6',case_id=q['case']['case_id'],physical_case_id=pid,attempt_id=ar.name,attempt_root=str(ar),kind='cpu',cpu_task_kind='audit',launch_owner='root',cpu_threads=2,estimated_storage_bytes=536870912,max_wall_seconds=600,cwd=str(L),worktree_root=str(R),command=[str(L/'.venv/bin/python'),q['worker']['path'],'--request',str(sp),'--report','{attempt_root}/floatinginfo/fulltime-rigid-motion-report.json'],input_files=sorted(inputs),input_sha256=inputs,input_sha256_required=True,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,physical_condition_sha256=q['case']['physical_condition_sha256'],case_credit=0);qp=O/'enabled-pilot-runner-request.json';put(qp,a);put(O/'controller-config.json',{'fair_dispatch':str(root(928)/'fair_CPU_dispatch.py'),'request':str(qp)});(O/'registration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(O.relative_to(R)),str((ic/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close47 rigidIBI4 input inventory and register full241 official F6 pilot','--',*paths],cwd=R,check=True);print({'pilot_controller':str(controller),'pilot_request':ref(qp),'actual_inventory_cases':47,'pilot_physical_case_id':pid,'scientific_input_sha_producer_attested':e['sha256'],'case_credit':0})
