from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_282.json';cp=load(cpfile);assert cp['checkpoint']==282 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==313
qis=[]
for original,qnum,source,flag in [(1174,1371,179,'all801_geometry_velocity_N3_times_UID_finite_verified'),(1033,1373,213,'all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified')]:
 p=next(root(qnum).glob('*proof.json'));qi=load(p);assert qi[flag] is True
 if qnum==1371:
  er=qi['actual_completed_metadata_evidence'];rr=er['render_receipt'];rp=er['render_report'];pu=er['render_publish_receipt']
 else:rr=qi['actual_completed_receipts']['render'];rp=qi['render_report'];pu=qi['publish']
 for e in [rr,rp,pu]:assert sha(e['path'])==e['sha256']
 rc=load(rr['path']);pub=load(pu['path']);assert rc['status']=='completed' and rc['returncode']==0 and pub['status']=='published_after_atomic_rename' and pub['case_id']==qi['case_id'] and pub['report_sha256_after_rebind']==rp['sha256']
 qis.append({'original':original,'physical_case_id':qi['physical_case_id'],'main_own_QI':ref(p),'actual_render_receipt':rr,'actual_render_report':rp,'actual_publish_receipt':pu,'actual_native_XMF_plan_field_namespaces':qi['actual_native_XMF_plan_field_namespaces'],'source_personal_review':source,'case_credit':0})
F=root(1160);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre)
for e in j.values():
 if isinstance(e,dict) and 'path' in e and 'sha256' in e:assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);n=load(t['source_provenance']['solver_receipt']['path']);nq=n['request'];b=load(load(j['actual_bed_receipt']['path'])['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert n['status']=='completed' and n['returncode']==0
assert (canonical,legacy,sd)==('a12cc198e6f1b718faa4a4a72e2ab005e83b7d20a4996532bc0cb41c2a0d0e74','d43630eaf02bce43bf1f232b2440059199e1bb76a9bbaf98aecfd422f50773ea','6f1e82d1ce1405aa494cee075d844228711a4324654e81bc846c3c2cef1ae0c6')
mask={ns:{k:{'present':k in ob,'value':ob.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,ob in [('native',nq),('XMF',x)]}
for m in mask.values():assert m=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}}
assert sha(b['source_definition'])==b['source_definition_sha256']==sd and len({canonical,legacy,sd})==3
w=load(F/'enabled-render-wrapper.json');assert w['expected_frames']==t['frames']==x['frames']==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
P=Path('/proc/648352');obs=None
if P.exists():
 st=(P/'stat').read_text().split(') ',1)[1].split();assert st[19]=='214140469';cmd=(P/'cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert 'root1160' in str(out);obs={'pid':648352,'startticks':'214140469','state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
assert obs is not None or (F/'controller-result.json').exists()
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current313_F5_1174_F3_1033_published_ownQIs_personal179213_active_nextF5_1160_native_XMF_physicalplan_canonical_durable801QI_1378';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_283.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1160_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1160-full801-own-QI1377.py').read_bytes());compile(entry.read_text(),str(entry),'exec');pp=O/'current313-two-published-ownQI-personal-active-next-original1160-durable801QI-readiness.json'
put(pp,{'schema':'ds02.current313-two-published-ownQIs-nextF5-durable801QI.v1','at_utc':now.isoformat(),'actual_completed0_published_full_QIs_personal_pending':qis,'next_original1160_previsual':ref(pre),'next_native_canonical':canonical,'next_typed_legacy':legacy,'next_bed_SourceDef_FILE':sd,'next_actual_native_XMF_plan_field_namespaces':mask,'next_XMF_physical_plan_has_native_canonical_role_not_SourceDef_FILE_role':True,'next_same_live_handle':obs,'next_actual_terminal':ref(F/'controller-result.json') if (F/'controller-result.json').exists() else None,'durable_original1160_only_QI_entrypoint':ref(entry),'command':['python3','-B',str(entry),'1160','1377'],'future_ownQI1377_unexecuted_no_proof_SHA':True,'original1371_legacy_named_namespace_flag_has_no_scope_alias_authority':'Use raw native/XMF plan masks and explicit XMF has_native_canonical=True, has_SourceDef=False; separately verified bed SourceDef FILE is distinct. Completed QI1371 bytes remain immutable.','do_not_rerun_completed_QI':[1363,1366,1371,1373],'case_credit':0,'scientific_payload_IO':False,'no_new_solver_or_render_jobs':True})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp)
new.update(checkpoint=283,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source193 F2 original1143 personal review integrated313; originalF5 1174 completed0/published/full801 ownQI1371 and originalF3 1033 completed0/published/full836 ownQI1373. Personal179/213 activated. Next actualF5original1160 genuine samehandle/true native-XMF canonical plan roles bound with durable futureownQI1377; F2 completion-only final48 builder194 preparing. No newSCI jobs.',authorized_work_state='Active313/336; pending23. Source179 actualF5original1174 andsource213 actualF3original1033 personallyreviewing after ownQI1371/1373. Source194 F2 completion-only final48 builder/current44 readiness only. NextF5original1160 samePV648352/start214140469 with futureownQI1377 entry prepared; nextregisteredrenderer automatically admitted without restart. All stage1 precision unaccepted QNQE0/Home500GiB.')
new['actual_progress']['actual1174_full801_own_QI']=qis[0]['main_own_QI'];new['actual_progress']['actual1033_full836_own_QI']=qis[1]['main_own_QI'];new['actual_progress']['current313_two_published_QIs_next1160_durable']=ref(pp)
new['source_agents'].update(production_recovery='fresh179 F5original1174 ownQI1371 supplied; personal34contacts9keys active',f5_bed_recovery='fresh213 F3original1033 ownQI1373 supplied; personal35contacts9keys active',f6_endpoint_initial_qa='fresh194 F2 completion-only final48 builder/current44 readiness; preserve baseline421566 and originaltypedP03 runtimeunknown')
new['next_executable_tasks']=['Adopt source179 F5original1174 andsource213 F3original1033 after actual personalreview/finalcommit/readonlyvalidator; distinct actualplan masks andtimes preserved.','Observe nextF5original1160 samePV648352/start214140469; after actual0/pub execute durableownQI1377 once, assign available personal34contacts9keys.','Inspect next registeredrenderer after originalF31033; preserve samePID/startticks andactualtyped/native/XMF namespace masks before ownQI, no restart onobservation timeout.','Integrate source194 F2 complete-only builder after fullreadonlycodeaudit, current44 readiness historical only; no partialfinal48 publication.','Continue remaining23 actualreviews and F2/F3/F5 complete48 catalogs/global336 delivery; preserve allruntimeunknowns, negativehistory, actual8subset24subset48.']
put(np,new);ip=root(1375)/'full336-current313-actual-final48-delivery-progress-index.json';idx=load(ip)
for obj in qis:
 row=next(a for a in idx['cases'] if a['physical_case_id']==obj['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=obj['main_own_QI'],current_actual_render_receipt=obj['actual_render_receipt'],current_atomic_publish_receipt=obj['actual_publish_receipt'],current_personal_review_source=obj['source_personal_review'],case_credit=0,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[a['physical_case_id'] for a in qis],current313_two_published_QIs_next1160_durable=ref(pp));assert len(idx['cases'])==336 and sum(bool(a.get('accepted_decision')) for a in idx['cases'])==313
put(O/'full336-current313-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bind F5 F3 published ownQIs and durable nextF5 original1160 integrity','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':283,'accepted':313,'ownQIs':[1371,1373],'next1160_live':obs,'free_GiB':free,'CPUh':cpu,'proof':ref(pp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
