from pathlib import Path
import json,hashlib,datetime,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
O=H/'root_stage1_264_visual_F3_AY0270_actual1166_readonly_artifact_audit0_original154_unknown_lifecycle_and_full401_render1169_checkpoint_1170';O.mkdir(exist_ok=False)
q=load(root(1166)/'enabled-full836-readonly-artifact-audit-request.json');ar=Path(q['attempt_root']);receipt=ar/'execution-receipt.json';report=ar/'full836-scientific-artifact-audit.json';r=load(receipt);a=load(report);old_path=q['source_conversion_lifecycle']['receipt_path'];old=load(old_path);old_digest=q['source_conversion_lifecycle']['receipt_sha256'];h5=q['opaque_scientific_inputs']['trajectory_h5']
assert (r['status'],r['returncode'])==('completed',0) and a['artifact_integrity_status']=='completed' and a['worker_returncode']==0
assert r['request']['attempt_id']==q['attempt_id'] and r['request']['physical_case_id']==q['physical_case_id'] and r['request']['physical_condition_sha256']==q['physical_condition_sha256']
assert a['case_id']==q['case_id'] and a['physical_identity']['physical_case_id']==q['physical_case_id'] and a['physical_identity']['canonical_native_condition_sha256']==q['physical_condition_sha256']
assert a['producer_attestation']['verified_trajectory_sha256']==q['H5_expected_SHA_from_completed_producer_report_only']==r['input_hashes_at_launch'][h5]==r['input_hashes_after_run'][h5]
assert a['producer_attestation']['conversion_report_sha256']==q['metadata_only_bindings']['conversion_report']['sha256']
f=a['field_audit'];assert f['frames']==836 and f['particles']==179208 and f['position_shape']==[836,179208,3] and f['uid_lifecycle_missing_count']==0
for k in ['finite_position_velocity_density_pressure_mass','n3_shape_verified','report_frame_ledger_verified','time_axis_verified_against_report','type_mk_verified_all_frames','uid_composite_unique']:assert f[k] is True
assert not f['source_arrays_modified'];assert a['approved_temporal_kernel']['full_temporal_scan'] and a['approved_temporal_kernel']['checked_transitions']==835
assert a['report_frame_ledger']['frames']==836 and a['report_frame_ledger']['missing_particles_all_frames']==0
assert old['status']=='running' and 'returncode' not in old and sha(old_path)==old_digest
assert not a['source_conversion_lifecycle']['source_receipt_edited'] and not a['source_conversion_lifecycle']['source_conversion_reclassified'] and not a['source_conversion_lifecycle']['old_os_exit_zero_claim']
for g in ['root_actual_launch_source','root_actual_launch_source_sha256']:
 assert r['request'][g]==q[g]
for p,digest in q['input_sha256'].items():
 if p!=h5:assert sha(p)==digest,p
proof=O/'actual1166-independent-full836-scientific-artifact-qualification-old-receipt-preserved.json';put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'existing_artifact_qualified_by_new_readonly_full836_audit','actual_audit_receipt':ref(receipt),'actual_full836_audit_report':ref(report),'actual_request':ref(root(1166)/'enabled-full836-readonly-artifact-audit-request.json'),'actual_controller_result':ref(root(1166)/'controller-result.json'),'original_conversion_receipt':ref(old_path),'original_conversion_status':'running','original_returncode_field_absent':True,'old_OS_exit_zero_not_claimed':True,'worker_verified_H5_SHA_and_full836_arrays':a['producer_attestation']['verified_trajectory_sha256'],'main_scientific_payload_IO':False,'full836_N3_UID_time_typeMk_finite_and835transitions':True,'physical_identity':a['physical_identity'],'case_credit':0,'Q_N':0,'Q_E':0,'next_action':'Explicit original-conversion vs new-artifact-audit XMF receipt adapter; original104 currently requires typed_receipt completed0 so source143 must preserve old unknown lifecycle and require actual new audit0.'})
observations=[]
for n in [951,1169]:
 d=root(n);lp=d/'controller-launch-process.json';v=load(lp);stat=Path(f"/proc/{v['pid']}/stat");assert stat.exists();s=stat.read_text().split(') ',1)[1].split();assert s[0]!='Z' and str(s[19])==str(v['proc_start_ticks']);observations.append({'root_number':n,'launch':ref(lp),'actual_pid':v['pid'],'actual_proc_start_ticks':s[19],'verified_live_now':True,'case_credit':0})
put(O/'current-verified-live-951-lastF6-and1169-render-handles.json',observations)
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_177.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==264 and len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==264
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);fs=os.statvfs('/home/jade');free=fs.f_bavail*fs.f_frsize/2**30;assert free>=500
cp.update(checkpoint=178,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,authorized_work_state='Active:264/336. F3 AY0270 existing artifact independently auditedfull836/0 by new1166, original154 running/missing returncode preserved; explicit XMF audit qualification adapter needed. F2 RX058ROT075 render1169 registered and currentlylive. LastF6 Root951 samePID/startticks currentlylive waitingfaircapacity. Other original render queues preserved. Three reused Luna/max agents prepare F3visual142/XMFadapter143, F5bed185, F5mother157.',previous_goal_turn_classification='Progress: accepted one independent F2 actual1098/fresh158 to264/336 with full401 source closure,17contacts9keys and35UIDomissions disclosed; original141 readonly scientific audit1166 completed0 full836/835transitions confirms originalH5hash,N3,UID/typeMk/finite with original154 unknownOSexit preserved; registered real F2actual1091 full401 render1169. Wrong copied unconsumed label1168 preserved and superseded beforedispatch; no scientificrun or casecredit for1168. Cleanup515.503GiB independently reverified, Home500GiBfloor protected.')
cp['actual_progress']['Root1166_existing_F3_artifact_readonly_qualification']=ref(proof);cp['actual_progress']['Root1169_F2_full401_render_registered']=ref(root(1169)/'controller-launch-process.json');cp['actual_progress']['Root1168_unconsumed_label_superseded']=ref(root(1168)/'prelaunch-registration-superseded-metadata-label-correction.json');cp['actual_progress']['current_failed_output_cleanup_reverification']=ref(root(1094)/'current-cleanup-reverification-20261006T211448Z.json');cp['source_agents'].update(production_recovery='fresh142 personal full836 P1200 AY0460 actual1103 visual; then fresh143 explicit original154 unknown vs audit1166 completed0 XMF adapter',f5_bed_recovery='fresh185 actual1125/1133/1146 five own full801 original138 disabledbed; then1072 four',f6_endpoint_initial_qa='fresh158 accepted264; resumed fresh157 M095T090/T100 motheralias original138 beddisabled');cp['next_executable_tasks']=['Adopt final fresh185 own actualXMF0 full801 bed5 through original138 Root142/928 CPU2 serial1','Adopt final fresh142 F3actual1103 personal35contacts9keys then independent full836casecredit','Implement and register explicit artifact-audit-qualified XMF143 for AY0270 without oldreceipt rewriting or auditor-as-converter relabel','Adopt fresh157 motheralias two own full801 bedrequests; preserve original138 science','Observe original live render951/1169 and allother registered fullnative render queues; no restart on wait']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_178.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_178.json').relative_to(R)),str((root(1166)/'controller-launch-process.json').relative_to(R)),str((root(1166)/'controller-result.json').relative_to(R)),str((root(1166)/'actual-progress.json').relative_to(R)),str((root(1169)/'controller-launch-process.json').relative_to(R)),str((root(1168)/'prelaunch-registration-superseded-metadata-label-correction.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close real full836 artifact audit and checkpoint264 accepted with downstream queues','--',*paths],cwd=R,check=True);print({'checkpoint':178,'accepted':264,'families':cp['accepted_per_family'],'F3_artifact_audit':'completed0/full836','Home_free_GiB':free,'cpu_coreh':cp['cpu_core_hours_charged'],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
