from pathlib import Path
import json,hashlib,subprocess,datetime,sys,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit=subprocess.check_output(['git','rev-parse',sys.argv[1]],cwd=W,text=True).strip();prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_168_f3_assigned_f6_fulltime_floatinginfo_worker_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==9;blobs={};before={}
for name in names:
 b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert (W/name).read_bytes()==b;assert not (R/name).exists() or (R/name).read_bytes()==b;blobs[name]=b;before[name]=sha(W/name)
results=[]
for script in ['validate_fresh168.py','tests/test_fulltime_floatinginfo_fresh168.py']:
 rr=subprocess.run(['python3','-B',str(P/script)],capture_output=True,text=True);assert rr.returncode==0,(script,rr.stdout,rr.stderr);results.append({'script':script,'stdout':rr.stdout,'stderr':rr.stderr,'returncode':rr.returncode})
assert before=={name:sha(W/name) for name in names};idx=load(P/'requests/f6-final48-fulltime-floatinginfo-disabled-request-index.json');inv=load(P/'requests/partfloatinfo-inventory-disabled-request.json');tb=root(1300)/'47-own-full241-native-time-bindings-for-official-rigid-export.json';bindings=load(tb);bm={x['physical_case_id']:x for x in bindings['cases']};assert len(idx['requests'])==len(inv['entries'])==len(bm)==47 and not bindings['errors'];assert idx['disabled'] and inv['disabled'] and idx['future_receipt_report_output_hashes'] is None
for q in idx['requests']:
 b=bm[q['case']['physical_case_id']];assert q['native']['receipt_path']==b['native_receipt']['path'] and q['native']['receipt_sha256']==b['native_receipt']['sha256'];n=load(b['native_receipt']['path']);assert n['status']=='completed' and n['returncode']==0 and n['request']['physical_condition_sha256']==q['case']['physical_condition_sha256'];assert q['native']['rigid_state_input']['source_stat_bytes']==(Path(q['native']['data_root'])/'PartFloatInfo.ibi4').stat().st_size==180376
for e in inv['entries']:
 q=next(x for x in idx['requests'] if x['case']['physical_case_id']==e['physical_case_id']);assert e['case_id']==q['case']['case_id'] and e['data_root']==q['native']['data_root'] and e['relative_path']=='PartFloatInfo.ibi4' and e['expected_stat_bytes']==180376
assert not list(H.glob('root*_1301')) and not list(H.glob('root*_1302'));O=H/'root_stage1_source168_F6_fulltime_FloatingInfo_failclosed_native_times_units_Part_contract_and47_small_IBI4_inventory_worker_adoption_1301';O.mkdir();adopted=[]
for name,b in blobs.items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
proof=O/'source168-byte-exact-readonly-validator-toy-tests-and-main47-native-binding-adoption.json';put(proof,{'schema':'ds02.main.source168.fulltime-rigid-export-worker-adoption.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_commit':commit,'source_SHA_before_after':before,'adopted_source_files':adopted,'source_original_bytes_preserved':True,'readonly_validation_and_meaningful_toy_tests':results,'main_own47_native_time_bindings':ref(tb),'input_inventory_bootstrap_policy':'IBI4 input files have no prior per-file SHA attestation. Register worker code, explicit metadata-bound inventory spec, own complete native receipts, and guards. Only the registered worker streams the exact47 small PartFloatInfo.ibi4 files, emits before/after stats and SHA inventory; subsequent export strict requests bind those observed scientific input hashes. No pretended prior science SHA.','Part_first_pilot_policy':'First actual pilot tests expected frame_index0..240 as a declared output contract; only matching observed CSV values become evidence for remaining46. Source null pilot fields remain source snapshots.','disabled_source_requests_and_future_null_hashes_preserved':True,'main_scientific_payload_IO':False,'case_credit':0,'Q_N':0,'Q_E':0});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(O.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: adopt source168 fulltime F6 rigid export and smallIBI4 inventory workers','--',*paths],cwd=R,check=True)
G=H/'root_stage1_F6_47small_PartFloatInfo_IBI4_metadata_bound_inventory_registered_Root142928_CPU2_1302';G.mkdir();stock=load(root(1220)/'enabled-cleanup-request.json');ar=D/'families/infra/F6-fulltime-rigid-inventory/root-stage1-F6-47small-IBI4-inventory-source168-root1302';assert not ar.exists();spec=copy.deepcopy(inv);spec.update(disabled=False,source_only=False,execution_allowed=True,status='root_enabled_metadata_bound_scientific_input_inventory');spec['output'].update(directory=str(ar/'inventory'),report_path=str(ar/'inventory/inventory-report.json'));spec['worker']['path']=str(R/prefix/'workers/run_partfloatinfo_inventory_fresh168.py');spec['worker']['sha256']=sha(spec['worker']['path']);spec['main_bootstrap_provenance']=ref(proof);spec['own_complete_native_bindings']=ref(tb);sp=G/'enabled-partfloatinfo-inventory-spec.json';put(sp,spec)
controller=G/'registered-inventory-controller.py';controller.write_text("from pathlib import Path\nimport json,runpy\nO=Path(__file__).parent\nc=json.loads((O/'controller-config.json').read_text())\nr=runpy.run_path(c['fair_dispatch'])['dispatch'](c['request'],serial_conversion=True)\nq=json.loads(Path(c['request']).read_text())\nrp=Path(q['attempt_root'])/'execution-receipt.json'\na=json.loads(rp.read_text()) if rp.exists() else {}\nv={'launcher_returncode':r.returncode,'status':a.get('status'),'returncode':a.get('returncode'),'actual_receipt':str(rp),'stdout_tail':r.stdout[-2500:],'stderr_tail':r.stderr[-2500:],'case_credit':0}\n(O/'controller-result.json').write_text(json.dumps(v,indent=2)+'\\n')\nprint(json.dumps(v),flush=True)\nraise SystemExit(r.returncode)\n")
fair=root(928)/'fair_CPU_dispatch.py';guardpaths=[Path(stock['root_actual_launch_source']),root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(64)/'resource-window-approval.json',fair];guardshas={str(p):stock['input_sha256'][str(p)] for p in guardpaths};assert all(sha(p)==s for p,s in guardshas.items());inputs={**guardshas,str(sp):sha(sp),str(controller):sha(controller),str(tb):sha(tb),str(proof):sha(proof),spec['worker']['path']:spec['worker']['sha256']}
for x in bm.values():inputs[x['native_receipt']['path']]=x['native_receipt']['sha256']
q={k:copy.deepcopy(stock[k]) for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']};q.update(schema='ds02.runner-request.v2',family_id='infra',case_id='F6-fulltime-rigid-inventory',attempt_id=ar.name,attempt_root=str(ar),kind='cpu',cpu_task_kind='audit',launch_owner='root',cpu_threads=2,estimated_storage_bytes=67108864,max_wall_seconds=600,cwd=str(L),worktree_root=str(R),command=[str(L/'.venv/bin/python'),spec['worker']['path'],'--request',str(sp),'--report','{attempt_root}/inventory/inventory-report.json'],input_files=sorted(inputs),input_sha256=inputs,input_sha256_required=True,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,physical_condition_sha256=sha(sp),physical_condition_hash_semantics='Metadata-bound scientific input inventory specification, no physical case credit or numerical certification',case_credit=0);qp=G/'enabled-inventory-runner-request.json';put(qp,q);put(G/'controller-config.json',{'fair_dispatch':str(fair),'request':str(qp)});put(G/'registered-input-provenance.json',{'source_worker_adoption':ref(proof),'enabled_inventory_spec':ref(sp),'own_complete_native_bindings':ref(tb),'registered_request':ref(qp),'scientific_input_sha_before_first_registered_inventory':None,'scientific_files_metadata_bound_not_pretended_strict_prehashed':True,'explicit_files':47,'total_expected_IBI4_bytes':8477672,'main_scientific_payload_IO':False,'case_credit':0});rel=str(G.relative_to(R));subprocess.run(['git','add','--',rel],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register CPU2 metadata-bound47 small rigid IBI4 SHA inventory','--',rel],cwd=R,check=True);print({'source_commit':commit,'inventory_controller':str(controller),'registered_request':ref(qp),'input_files':len(inputs),'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
