from pathlib import Path
import json,hashlib,runpy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
old=root(945);review=root(950)/'actual116-grounded-path-repair-adoption.json';pkg=Path(load(review)['packages'][0]['package']);worker=pkg/'workers/nvme_render_successor.py';assert sha(worker)=='5d577e4b28e62906472bfba30ad445685f804be4ba5d8bab44b4bab3d32e1621';api=runpy.run_path(str(worker));tests=root(950)/'main-independent-tests.json';put(tests,{'actual_unittest_exit_code':0,'actual_tests_run':10,'runtime_seconds':2.067,'command':['python3','-m','unittest','discover','-s',str(pkg/'tests'),'-v'],'exec_session_id':30215,'science_payload_IO':False,'case_credit':0})
O=H/'root_stage1_grounded116_manifest_path_repair1_full37_first_then_shared2_951';O.mkdir(exist_ok=False);(O/'requests').mkdir();(O/'wrapper-requests').mkdir();controller=O/'batch-controller.py';controller.write_bytes((old/'batch-controller.py').read_bytes());cfg=load(old/'controller-config.json');paths=[];pre=[]
accepted={load(p).get('physical_case_id',load(p)['case_id']) for p in load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_123.json')['accepted_decisions']}
for qp in cfg['outer_requests']:
 q=load(qp);pid=q['physical_case_id'];assert pid not in accepted;w=load(q['command'][-1]);assert q['command'][-2]=='--request';md=w['input_sha256'].copy()
 for p,d in md.items():assert sha(p)==d
 for p in [worker,controller,review,tests,root(946)/'actual-cli-manifest-failure-classification.json',Path(qp),Path(q['command'][-1])]:md[str(p)]=sha(p)
 aid=q['attempt_id'].replace('logged114','grounded116-repair1').replace('root945','root951');assert aid!=q['attempt_id'];ar=D/'families'/q['family_id']/q['case_id']/aid;assert not ar.exists();rid='/'.join([q['family_id'],q['case_id'],aid]);w.update(schema=api['SCHEMA'],attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root='/tmp/ds02-visual-render-cache-root951',input_files=sorted(md),input_sha256=md);api['validate_request'](w,execution=True);m=api['_manifest_metadata'](w);assert m['manifest']==w['manifest'] and Path(m['manifest']).is_absolute();wp=O/'wrapper-requests'/(pid+'-enabled-wrapper.json');put(wp,w);outermd={**md,str(wp):sha(wp),load(w['manifest'])['trajectory_h5']:q['source_h5_producer_sha256']};q.update(attempt_id=aid,attempt_root=str(ar),command=[q['command'][0],q['command'][1],'--worker',str(worker),'--request',str(wp)],input_files=sorted(outermd),input_sha256=outermd,root_grounded_failure_class='manifest_dict_repr_used_as_cli_filename',root_grounded_repair_number=1,root_repair_limit_per_class=2,root_failed945_request_preserved=ref(qp));np=O/'requests'/Path(qp).name;put(np,q);paths.append(str(np));pre.append({'physical_case_id':pid,'family_id':q['family_id'],'request':ref(np),'manifest_cli_is_exact_absolute_source_path':True,'case_credit':0})
assert len(paths)==37;cfg.update(outer_requests=paths,worker=ref(worker),grounded_repair_number=1,recovery_rationale='Root945 actual CLI received 49002-byte dict repr. Corrected116 returns original absolute JSON path; ten real toy tests pass and all37 metadata CLI bindings checked. First full completion0 required before pool2; failures retained and pending held, repair limit2.',case_credit=0);put(O/'controller-config.json',cfg);put(O/'enabled37-metadata-preflight.json',{'cases':pre,'requested':37,'families':cfg['families'],'accepted199_excluded':True,'main_science_payload_IO':False,'Home_floor_GiB':500,'Home_publication_hard_cap_GiB':3,'first_full0_before_parallel2':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());print(str(O))
