from pathlib import Path
import json,hashlib,runpy,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_NVMe3GiB_fullnative_renderer_first1_then_shared2_F6remaining23_F2ready3_F5ready1_934';O.mkdir(exist_ok=False);load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,indent=2)+'\n')
P=L/'campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_112_f3_fresh110_publication_lifecycle_hardening_v1';worker=P/'workers/nvme_render_successor.py';api=runpy.run_path(str(worker));assert sha(worker)=='b9fd883037342e549fcdee9ea61c07cdc6e108dfcb0d92380660c00c3fbd1679';entry=root(932)/'registered_render_entry.py';fair=root(928)/'fair_CPU_dispatch.py';renderer=root(23)/'render.py';assert sha(renderer)=='5e78f7b92ad7c6f1d15902e3ccacc9099affb04b1b992a42f540eb88241bde66';base=load(next(root(856).glob('*render-request.json')));profile={k:v for k,v in base.items() if k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']};template=load(next((P/'requests').glob('*DXYZ_S0625*')));rows=[];completed=load(root(929)/'metadata-only-original920-after1-retirement-proof.json');done={r['case_id'] for r in completed['actual_requests'] if r['status']=='completed'};assert len(done)==1
for r in load(root(917)/'actual-ready24-independent-dispatch-audit.json')['cases']:
 if r['case_id'] in done:continue
 rows.append({'family_id':'F6','case_id':r['case_id'],'physical_case_id':r['case_id'],'manifest':r['manifest'],'actual_xdmf':r['xmf'],'actual_conversion_report':r['typed_report'],'actual_native_receipt':r['actual_completed_receipts']['native_receipt'],'actual_typed_receipt':r['actual_completed_receipts']['typed_receipt'],'actual_xmf_receipt':r['actual_completed_receipts']['xmf'],'frames':241,'particles':417505,'canonical_source_physical_condition_sha256':r['actual_physical_condition_sha256'],'actual_converter_scope_sha256':r['actual_physical_condition_sha256'],'source_canonical_owner_scope_sha256':r['source_canonical_physical_condition_sha256'],'source_plan_condition_sha256':r['source_plan_condition_sha256'],'extra_bindings':[r['classified_owner'],r['source_owner']]})
assert len(rows)==23
ready4=load(root(927)/'actual-independent-four-ready-audit.json')['cases'];adapt=[]
for r in ready4:adapt.append({**r,'manifest':r['actual_manifest'],'actual_converter_scope_sha256':r['actual_converter_legacy_scope_sha256'],'extra_bindings':r['bed_evidence']})
# Validate the common publication protocol first with the next own F6 case,
# then permit two family-independent jobs. The first920 is always excluded.
rows=[rows[0]]+sorted(adapt,key=lambda r:(r['family_id']!='F5',r['physical_case_id']))+rows[1:];assert len(rows)==27 and len({r['physical_case_id'] for r in rows})==27
cfg={'outer_requests':[str(O/'requests'/(r['physical_case_id']+'-render-request.json')) for r in rows],'requested':27,'families':{'F6':23,'F2':3,'F5':1},'first920_completed_case_excluded':sorted(done),'fair_dispatch_source':ref(fair),'worker':ref(worker),'entry':ref(entry),'launch_profile':profile,'case_credit':0};put(O/'controller-config.json',cfg)
s='''from pathlib import Path
from concurrent.futures import ThreadPoolExecutor,wait,FIRST_COMPLETED
import json,runpy
O=Path(__file__).parent;load=lambda p:json.loads(Path(p).read_text());cfg=load(O/'controller-config.json');dispatch=runpy.run_path(cfg['fair_dispatch_source']['path'])['dispatch']
def run(qp):
 q=load(qp);result=dispatch(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};passed=False;error=result.stderr[-2000:]
 if (r.get('status'),r.get('returncode'))==('completed',0):
  a=load(Path(q['attempt_root'])/'render/paraview-full-animation-report.json');pub=load(Path(q['attempt_root'])/'render/render-publish-receipt.json');expected=q['expected_frames'];passed=a['frames']==a['source_frames']==expected and a['all_frames_rendered'] and a['native_identity_axis_preserved'] and a['actual_times_preserved_exactly'] and a['nonfinite_active_states']==0 and a['source_h5_sha256']==q['source_h5_producer_sha256'] and pub['published_bytes_total']<=q['estimated_storage_bytes'] and len(a['outputs']['contact_sheets'])==q['expected_contact_sheets']
 row={'family_id':q['family_id'],'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':str(qp),'actual_receipt':str(rp),'status':r.get('status'),'returncode':r.get('returncode'),'launcher_returncode':result.returncode,'actual_fullnative_render_pass':passed,'launcher_error':error,'case_credit':0};print(json.dumps(row),flush=True);return row
qs=cfg['outer_requests'];rows=[run(qs[0])];failed=not rows[0]['actual_fullnative_render_pass'];index=1
with ThreadPoolExecutor(max_workers=2) as pool:
 active={}
 while active or(index<len(qs) and not failed):
  while len(active)<2 and index<len(qs) and not failed:active[pool.submit(run,qs[index])]=qs[index];index+=1
  done,_=wait(active,return_when=FIRST_COMPLETED)
  for f in done:
   active.pop(f);row=f.result();rows.append(row);failed|=not row['actual_fullnative_render_pass'];(O/'actual-progress.json').write_text(json.dumps({'results':rows,'pending_not_submitted':len(qs)-index,'case_credit':0},indent=2)+'\\n')
summary={'requested':27,'actual_fullnative_completed0':sum(r['actual_fullnative_render_pass'] for r in rows),'pending_held':len(qs)-index,'results':rows,'case_credit':0};(O/'controller-result.json').write_text(json.dumps(summary,indent=2)+'\\n');raise SystemExit(1 if failed else 0)
'''
compile(s,str(O/'batch-controller.py'),'exec');(O/'batch-controller.py').write_text(s);(O/'requests').mkdir();(O/'wrapper-requests').mkdir();proofs=[]
common=[worker,entry,fair,O/'controller-config.json',O/'batch-controller.py',root(932)/'actual112-library-and-entry-adoption-review.json',root(932)/'toy-registered-entry-exit-contract-test.json',root(929)/'metadata-only-original920-after1-retirement-proof.json',root(917)/'actual-ready24-independent-dispatch-audit.json',root(927)/'actual-independent-four-ready-audit.json',L/'.venv/bin/python',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json',renderer,Path(template['pvpython']),Path('/usr/bin/env'),Path('/usr/share/glvnd/egl_vendor.d/50_mesa.json')]
for row,qp in zip(rows,cfg['outer_requests']):
 mp=Path(row['manifest']['path']);assert sha(mp)==row['manifest']['sha256'];m=load(mp);cp=Path(row['actual_conversion_report']['path']);c=load(cp);assert sha(cp)==row['actual_conversion_report']['sha256'];assert c['conversion_status']=='completed' and c['partvtk_validation']['all_passed'] and c['solver_dimension']['solver_dimension']==3 and c['frames']==row['frames'] and c['particles']==row['particles'];assert m['source_h5_read_only'] and m['source_h5_sha256']==c['output_sha256'];dig=row['canonical_source_physical_condition_sha256'];actual=c['hash_scopes']['physical_condition_sha256'];assert actual==row['actual_converter_scope_sha256'];md={str(p):sha(p) for p in common};
 for v in [row['manifest'],row['actual_xdmf'],row['actual_conversion_report'],row['actual_native_receipt'],row['actual_typed_receipt'],row['actual_xmf_receipt'],*row['extra_bindings']]:assert sha(v['path'])==v['sha256'];md[v['path']]=v['sha256']
 for k in ['actual_native_receipt','actual_typed_receipt','actual_xmf_receipt']:
  rr=load(row[k]['path']);assert (rr['status'],rr['returncode'])==('completed',0)
 aid='root-stage1-'+row['family_id'].lower()+'-'+row['physical_case_id'].lower()+'-full'+str(row['frames'])+'-NVMe3GiB-root934';ar=D/'families'/row['family_id']/row['case_id']/aid;assert not ar.exists();rid='/'.join([row['family_id'],row['case_id'],aid]);frames=row['frames'];keys=[round(i*(frames-1)/8) for i in range(9)]
 dq={k:template[k] for k in ['schema','pvpython','home_root','nvme_stage_cap_bytes','nvme_free_floor_bytes','home_publish_cap_bytes','cpu_threads','declared_cpu_cores','environment_threads','max_wall_seconds','global_renderer_cap','home_free_floor_bytes','output_child','render_environment','resource_ledger_lock']};dq.update(family_id=row['family_id'],case_id=row['case_id'],physical_case_id=row['physical_case_id'],attempt_id=aid,manifest=str(mp),renderer=str(renderer),renderer_sha256=sha(renderer),renderer_argv_template=[template['pvpython'],'--force-offscreen-rendering',str(renderer),'--manifest','{manifest}','--output-dir','{stage_render}'],worktree_root=str(R),cwd=str(L),launch_owner='root',home_output=str(ar/'render'),home_reserved_bytes=0,nvme_root='/tmp/ds02-visual-render-cache-root934',expected_frames=frames,expected_particles=row['particles'],expected_contact_sheets=(frames+23)//24,keyframe_indices=keys,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,future_input_hashes_null=False,reservation_id=rid,current_attempt_id=rid,input_files=sorted(md),input_sha256=md,actual_converter_scope_sha256=actual,canonical_source_scope_sha256=dig,no_science_payload_IO_by_source_preparation=True)
 api['validate_request'](dq,execution=True);actualmd=api['_manifest_metadata'](dq);assert actualmd['frames']==frames;wp=O/'wrapper-requests'/(row['physical_case_id']+'-enabled-wrapper.json');put(wp,dq)
 outermd={**md,str(wp):sha(wp),m['trajectory_h5']:c['output_sha256']};q={**profile,'schema':'ds02.runner-request.v2','family_id':row['family_id'],'case_id':row['case_id'],'physical_case_id':row['physical_case_id'],'physical_condition_sha256':dig,'actual_converter_scope_sha256':actual,'attempt_id':aid,'attempt_root':str(ar),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':24,'max_wall_seconds':14400,'estimated_storage_bytes':3*1024**3,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'command':[str(L/'.venv/bin/python'),str(entry),'--worker',str(worker),'--request',str(wp)],'input_files':sorted(outermd),'input_sha256':outermd,'source_h5_producer_sha256':c['output_sha256'],'expected_frames':frames,'expected_particles':row['particles'],'expected_contact_sheets':(frames+23)//24,'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'root_review_required':False,'independent_case_count_increment':0,'registered_nested_paraView_only_inside_shared_CPU_job':True,'full_time_and_native_identity_required':True};put(qp,q);proofs.append({'case_id':row['case_id'],'physical_case_id':row['physical_case_id'],'request':ref(qp),'enabled_wrapper':ref(wp),'metadata_only_preflight_pass':True,'producer_H5_sha256_from_actual_report_only':c['output_sha256'],'frames':frames,'N3':row['particles'],'case_credit':0})
put(O/'actual-metadata-only-enabled27-preflight.json',{'requested':27,'F6_remaining23_F2ready3_F5ready1':True,'first920_actual0_not_rerun':True,'cases':proofs,'Home_reservation_GiB':3,'worker_hard_publish_cap_GiB':3,'Home_floor_GiB':500,'NVMe_only_private_scratch':True,'shared_only142_launch':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());print({'enabled_requests':len(proofs),'families':cfg['families'],'first920_not_rerun':True,'science_jobs_started':0})
