from pathlib import Path
import json,hashlib,copy,collections,datetime,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_229.json';cp=load(cpfile);assert len(cp['accepted_decisions'])==cp['stage1_visual_accepted_complete_independent_cases']==288
ip=root(1277)/'full336-current288-actual-final48-delivery-progress-index.json';idx=load(ip);terminal=[]
for n,qn in ((1148,1272),(1186,1275)):
 qp=next(root(qn).glob(f'actual{n}-full801*proof.json'));qi=load(qp);assert qi['full_frames']==801 and qi['particles']==194427 and qi['all_native_UIDs_active_each_frame'] and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['new_case_credit']==0
 rs=qi['actual_completed_metadata_evidence'];rr=rs['render_receipt'];receipt=load(rr['path']);assert sha(rr['path'])==rr['sha256'];assert (receipt['status'],receipt['returncode'])==('completed',0)
 pr=rs['render_publish_receipt'];pub=load(pr['path']);assert sha(pr['path'])==pr['sha256'] and pub['status']=='published_after_atomic_rename';report=rs['render_report'];assert sha(report['path'])==report['sha256']==pub['report_sha256_after_rebind'];assert pub['case_id']==qi['case_id']
 rows=[r for r in idx['cases'] if r['physical_case_id']==qi['physical_case_id']];assert len(rows)==1 and not rows[0].get('accepted_decision');assert rows[0]['native_request_scope']['sha256']==qi['canonical_actual_native_request_condition_sha256']
 e={'physical_case_id':qi['physical_case_id'],'case_id':qi['case_id'],'family_id':'F5','original_render_root':n,'actual_full801_QI':ref(qp),'actual_completed_render_receipt':rr,'actual_atomic_publish_receipt':pr,'actual_full_animation_report':report,'actual_native_plan_field_present':qi['actual_native_source_plan_condition_field_present'],'actual_native_plan_field_value':qi['actual_native_source_plan_condition_sha256'],'actual_XMF_source_plan_field_value':qi['XMF_source_plan_condition_field_sha256'],'actual_bed_source_plan_field_value':qi['bed_declared_source_plan_field_sha256'],'native_XMF_vs_bed_plan_roles_preserved':True,'visual_status':'pending delegated personal34contacts9keys','new_case_credit':0}
 terminal.append(e);rows[0].update(status='completed0-atomic-published-full801-QI-pending-personal-visual',actual_full801_QI=ref(qp),actual_render_completed0_publication=e)
existing=idx['actual_unaccepted_completed0_published_physical_cases'];existing_pids={e.get('physical_case_id') if isinstance(e,dict) else e for e in existing};existing.extend(e for e in terminal if e['physical_case_id'] not in existing_pids)
live=[]
for n,pv,expected in ((1156,451593,'212252524'),(1177,457418,'212315280')):
 p=Path(f'/proc/{pv}');assert p.is_dir();st=(p/'stat').read_text().split(') ',1)[1].split();assert st[19]==expected and st[0] not in ('Z','X');args=(p/'cmdline').read_bytes().split(b'\0');assert args[0].endswith(b'/pvpython');mp=Path(args[args.index(b'--manifest')+1].decode());out=Path(args[args.index(b'--output-dir')+1].decode());F=root(n);q=load(F/'enabled-full801-render-request.json');manifest=load(mp);assert manifest['case_id']==q['case_id'] and manifest['physical_case_id']==q['physical_case_id'] and manifest['frames']==801 and manifest['particles']==194427
 assert not (F/'controller-result.json').exists();live.append({'original_render_root':n,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'PV_pid':pv,'PV_startticks':expected,'process_state_observed':st[0],'actual_loaded_XMF_manifest':ref(mp),'private_output_dir':str(out),'private_frame_filename_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_contents_read_or_hashed':False,'original_registered_request':ref(F/'enabled-full801-render-request.json'),'controller_terminal_present':False,'observation_timeout_is_not_failure_or_restart':True})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;counts=collections.Counter(x['kind'] for x in ld['attempts']);sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
O=H/'root_stage1_actualF5_1148_1186_full801_QI_published_pendingvisual_and_same1156_1177_live_frontier_1280';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_230.json';assert not list(H.glob('root*_1280')) and not nextcp.exists();O.mkdir();proof=O/'actual2-F5-completed-full801-QI-and-original1156-1177-live-render-frontier.json';put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_completed_and_published_not_yet_visual_accepted':terminal,'same_original_live_render_handles_verified_now':live,'case_credit':0,'main_scientific_payload_IO':False,'storage_remaining48_forecast':ref(root(1279)/'remaining48-original-render-Home-storage-projection.json'),'no_jobs_started_restarted_or_mutated':True})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp.update(checkpoint=230,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actualF3 1046 accepted288 and actual72 first24 products delivered in predecessor; currentturn originalF5 1186 full801 completed0 atomicpublication and ownQI1275 done; all48 original Home publish caps97GiB independently verified with protected floor500; two genuine original live render handles1156/1177 observed, no restarts or scope substitutions.',authorized_work_state='Active288/336,48 remaining; original1148 and1186 completed/published with ownfull801QI, delegated personal visual reviews fresh201/165 pending. Render1156/1177 same actual livehandles; F6 lastcase original951 live.')
newcp['actual_progress']['two_F5_published_QI_pendingvisual_and_two_live_render_frontier']=ref(proof);newcp['actual_progress']['remaining48_original_Home_caps_storage_projection']=ref(root(1279)/'remaining48-original-render-Home-storage-projection.json');newcp['source_agents']['f5_bed_recovery']='fresh201 completed1148 personal43PNG review inprogress; nextsame1156 M098T085 originalhandle';newcp['source_agents']['production_recovery']='fresh165 completed1186 personal43PNG review inprogress, mainQI1275 delivered';newcp['next_executable_tasks']=['Adopt fresh201 actual1148 F5M098T095 personal43PNG with completedownQI1272.','Adopt fresh165 actual1186 F5M115T080 personal43PNG with completedownQI1275; shared mothercase_id not duplicate physicalID.','After original1156 publication run full801QI1278 and delegate fresh202 M098T085 personal43PNG.','Observe original1177 M114T095 and original951 lastF6, maintain sharedrendercap2; no scientific reruns.'];assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==288;put(nextcp,newcp)
idx.update(previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nextcp),at_utc=newcp['at_utc'],new_case_credit=0);idx['actual_F5_completed_full801_QI_pendingvisual_frontier']=ref(proof);assert sum(bool(r.get('accepted_decision')) for r in idx['cases'])==288;put(O/'full336-current288-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close two published F5 full801 integrity chains and preserve original live frontier','--',*paths],cwd=R,check=True);print({'checkpoint':230,'accepted':288,'published_F5_pendingvisual':2,'original_live_render_frontier':live,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
