from pathlib import Path
import json,hashlib,datetime,subprocess,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def same(a,b):return a['path']==b['path'] and a['sha256']==b['sha256']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='7337e30e52a43258ff6d6d2ce7b8f8be21c3d3b2';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_193_f6_assigned_f2_rx063_rot090_root1143_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh193.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
sp=P/'metadata/personal-visual-decision.json';s=load(sp);c=s['case'];v=s['visual_review'];dec=s['decision'];ev=s['evidence']
assert s['actual_family']=='F2' and s['assigned_family']=='F6' and s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and not s['recursive_delegation']
assert dec['status']=='visual-approved-by-delegated-agent' and dec['case_credit']==0 and not dec['global_acceptance'] and not dec['q_n_granted'] and not dec['q_e_granted'] and dec['precision_status']=='not accepted'
assert all(not s['source_boundaries'][k] for k in ['science_payload_read','science_payload_hashed','science_jobs_started','shared_registry_or_ledger_written','historical_source_changed','model_substitution'])
qip=root(1366)/'actual1143-full401-own-QI-UID-N3-native-typed-role-fifteen-fluid-omissions-previsual-proof.json';qi=load(qip);assert same(ev['main_qi_proof'],ref(qip));cid=qi['case_id'];pid=qi['physical_case_id'];assert c['case_id']==cid and c['physical_case_id']==pid
e=qi['actual_completed_metadata_evidence'];canonical=qi['native_canonical_condition_sha256'];legacy=qi['typed_XMF_actual_legacy_producer_condition_sha256'];assert canonical!=legacy
mapped={'gencase_receipt':'typed_source_gencase_receipt','initial_qa_receipt':'initial_qa_receipt','initial_qa_report':'initial_qa_report','native_receipt':'native_receipt','typed_receipt':'typed_receipt','typed_report':'typed_report','xmf_receipt':'XMF_receipt','xmf_manifest':'XMF_manifest','xmf_xml':'XMF_XML','render_receipt':'render_receipt','render_report':'render_report','publish_receipt':'render_publish_receipt'}
for a,b in mapped.items():check(ev[a]);assert same(ev[a],e[b]),(a,b)
for x in ev.values():check(x)
receipts={}
for role in ['gencase','initial_qa','native','typed','xmf','render']:
 receipts[role]=load(ev[role+'_receipt']['path']);assert receipts[role]['status']=='completed' and receipts[role]['returncode']==0 and receipts[role]['request']['case_id']==cid
nq=receipts['native']['request'];x=load(ev['xmf_manifest']['path']);actualmask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
assert actualmask==qi['actual_native_XMF_plan_field_namespaces'];assert c['source_plan_field_presence']['native']==actualmask['native'] and c['source_plan_field_presence']['XMF']==actualmask['XMF']
assert nq['physical_case_id']==pid and nq['physical_condition_sha256']==canonical and x['physical_condition_sha256']==legacy and x['canonical_source_physical_condition_sha256']==canonical
assert c['declared_counts']==qi['actual_initial_type_counts'] and c['terminal_counts']==qi['actual_terminal_type_counts'] and c['actual_time_s']==qi['actual_time_window_s'] and c['lifecycle_omissions']==qi['lifecycle_omissions']
assert qi['all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified'] and not qi['all_native_UIDs_active_each_frame'] and qi['lifecycle_omissions']['final_missing_particles']==15 and qi['lifecycle_omissions']['cumulative_particle_frame_omissions']==2278
assert qi['lifecycle_omissions']['final_Idp_sample_is_partial_not_all15'] and len(qi['lifecycle_omissions']['producer_attested_final_Idp_sample'])==8
assert qi['genuine_initial_QA_receipt_completed0_and_report_pass'] and qi['root_QI_is_independent_proof_not_runner_receipt'] and 'status' not in qi and 'returncode' not in qi
for key in ['initial_qa_receipt','initial_qa_report']:
 rr=ev[key];assert rr['path']==nq[key] and rr['sha256']==receipts['native']['input_hashes_at_launch'][rr['path']]==receipts['native']['input_hashes_after_run'][rr['path']]
assert load(ev['initial_qa_report']['path'])['status']=='pass'
r=load(ev['render_report']['path']);pub=load(ev['publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(ev['render_report']['path'])
assert r['frames']==r['source_frames']==401 and r['all_frames_rendered'] and r['actual_times_preserved_exactly'] and r['native_identity_axis_preserved'] and r['nonfinite_active_states']==0
out=Path(pub['published_output_root']);published={a['relative_path']:a for a in pub['files_excluding_receipt']};contacts=v['contact_sheets'];keys=v['key_frames'];assert len(contacts)==17 and len(keys)==9 and [a['sheet_index'] for a in contacts]==list(range(17)) and [a['frame'] for a in keys]==list(range(0,401,50));assert [a['path'] for a in contacts]==r['outputs']['contact_sheets']
for a in contacts+keys:
 p=Path(a['path']);rel=str(p.relative_to(out));check(a);assert a['sha256']==published[rel]['sha256'] and a['bytes']==published[rel]['bytes'] and a['viewed'] and v['personally_viewed_with']=='view_image'
reviewed=v['reviewed_at_utc'];parse=lambda z:datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',z).replace('Z','+00:00'));now=datetime.datetime.now(datetime.timezone.utc);assert parse(receipts['render']['finished_at_utc'])<=parse(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_281.json';cp=load(cpfile);assert cp['checkpoint']==281 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==312 and cp['accepted_per_family']['F2']==43
ip=root(1374)/'full336-current312-actual-final48-delivery-progress-index.json';index=load(ip);row=next(a for a in index['cases'] if a['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_source193_F2_RX063ROT090_original1143_full401QI_personal26PNG_fifteen_fluid_omissions_genuine_initialQA_visual_acceptance_1375';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_282.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source193-byte-exact-readonly-validator-main26publishedPNG-own401QI-genuine-initialQA-proof.json'
put(vp,{'schema':'ds02.source193.main.actualF2.adoption-integrity.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'source_reviewed_at_utc':reviewed,'personal_review_after_atomic_publication':True,'all26_publishedPNG_SHA_match_atomic_publish':True,'own_QI':ref(qip),'actual_initial_QA_receipt_and_report_completed0_and_pass':True,'own_QI_not_runner_receipt':True,'actual_native_XMF_plan_namespaces':actualmask,'source_legacy_role_correction_needed':False,'main_scientific_payload_IO':False,'new_case_credit':1})
dp=O/(pid+'-delegated-visual-decision.json');normcontacts=[{**a,'producer_sha256':a['sha256'],'index':a['sheet_index'],'role':'contact_sheet','view_method':'view_image'} for a in contacts];normkeys=[{**a,'producer_sha256':a['sha256'],'frame_index':a['frame'],'role':'event_keyframe','view_method':'view_image'} for a in keys]
put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F6','actual_review_family':'F2','source_personal_visual_review':ref(R/prefix/'metadata/personal-visual-decision.json'),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':e,'full_native_frames':401,'particle_count':418104,'initial_fluid_particles':21114,'actual_type_counts':{'initial':qi['actual_initial_type_counts'],'terminal':qi['actual_terminal_type_counts']},'actual_physical_window_s':qi['actual_time_window_s'],'all401_UID_N3_actual_times_finite_active_states_verified':True,'actual_quantified_missing_fluid':qi['lifecycle_omissions'],'all_native_UIDs_active_each_frame':False,'missing_fluid_locations_states_causes_unknown':True,'missing_fluid_states_not_reconstructed':True,'no_user_numeric_threshold_inferred':True,'actual_native_XMF_plan_field_namespaces':actualmask,'genuine_initial_QA_receipt_completed0_and_report_pass':True,'independent_QI_not_runner_receipt':True,'strict_container_guarantee':False,'subDP_precision_not_claimed':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':normcontacts,'keyframes':normkeys,'visual_observations':dec['observations'],'visual_limits':dec,'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source193-actual1143-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1
new.update(checkpoint=282,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=313,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active313/336; F1/F4/F6/F7=48,F2=44,F3=43,F5=34. ActualF2 original1143 ownQI1366 and source193 personal17contacts9keys accepted preserving15fluid omissions/2278 cumulative and genuineinitialQA. Original1174 and1033 same renders advance; durable ownQI1371/1373 prepared; personal179/213 pending actual0/publication/QI.',previous_goal_turn_classification='PROGRESS: current312 original1033 future own836QI1373 durable entry and delegated fresh213 prepared; source193 actualF2 original1143 personal26PNG reviewed, sourcevalidated, trueinitialQA/15fluid metadata bound and independently accepted313.')
new['actual_progress']['source193_actualF2_1143_visual_acceptance']=ref(ap);new['source_agents']['f6_endpoint_initial_qa']='fresh193 accepted F2 original1143; available for next actual published case or complete-only F2 final48 builder.'
new['next_executable_tasks']=['Observe same F5original1174 PID633506/start213987092; after actualcompleted0/pub run durableownQI1371 once, reactivate source179 personal34contacts9keys.','Observe same F3original1033 PID635508/start214008910; after actualcompleted0/pub run durableownQI1373 once, supply active source213 personal35contacts9keys.','Prepare completion-only F2 final48 reference builder with current44 readiness while retaining baseline421566, nativebaseline trueabsence, originaltypedP03 runtimeunknown, and original negative flags.','Continue remaining23 registered actualrenders/reviews to336; finalF2/F3/F5 catalogs require actual48accepted and fullprimary/runtime audit; Home500GiB preserved.']
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==313;put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=313,registered_pending_independent_physical_cases=23,new_case_credit=1);row.update(status='visual-approved-in-checkpoint282',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip))
index['actual_unaccepted_completed0_published_physical_cases']=[a for a in index['actual_unaccepted_completed0_published_physical_cases'] if (a if isinstance(a,str) else a['physical_case_id'])!=pid];assert len(index['cases'])==336 and sum(bool(a.get('accepted_decision')) for a in index['cases'])==313
put(O/'full336-current313-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX063ROT090 personal visual preserving15fluid omissions and genuineQA','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':282,'accepted':313,'F2':44,'pending':23,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
