from pathlib import Path
import json,hashlib,copy,datetime,subprocess,os,collections,math,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xmf','.xml','.py','.md','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'],e['path']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_330.json';cp=load(cpfile);ip=root(1445)/'full336-current334-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile)
assert cp['stage1_visual_accepted_complete_independent_cases']==334 and cp['accepted_per_family']['F5']==47
oldref=cp['actual_progress']['F5_current45_actual_primary_bed_delivery'];check(oldref);old=load(oldref['path']);check(old['main_independent_verification'])
products=copy.deepcopy(old['accepted45_actual_primary_bed_rows']);assert len(products)==45
added=[]
for original,qn,expected in [(1184,1440,'517321e9f5b62b619933c6b17566d2bd02e6626e823458e43ae51f764c5d0029'),(1175,1442,'9d29b258a8f7c6cbc1cba9595fb622637b3bdb34e064dd493027f4d27fb4c093')]:
 qip=root(qn)/f'actual{original}-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';assert sha(qip)==expected;qi=load(qip);pid=qi['physical_case_id'];cid=qi['case_id']
 row=next(r for r in idx['cases'] if r['physical_case_id']==pid);dr=row['accepted_decision'];check(dr);decision=load(dr['path']);assert decision['independent_full801_QI']==ref(qip) and decision['physical_case_id']==pid
 assert decision['agent_personally_viewed_all_contacts_and_keys'] and decision['personal_reviewed_contacts']==34 and decision['personal_reviewed_keyframes']==9
 er=qi['actual_completed_metadata_evidence']
 for e in er.values():check(e)
 assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['all_native_UIDs_active_each_frame']
 n=load(er['native_receipt']['path']);t=load(er['typed_report']['path']);x=load(er['xmf_manifest']['path']);r=load(er['render_report']['path']);rc=load(er['render_receipt']['path']);b=load(er['bed_report']['path']);pub=load(er['render_publish_receipt']['path'])
 for k in ['native_receipt','typed_receipt','xmf_receipt','render_receipt','bed_receipt','gencase_receipt','initial_qa_receipt']:
  j=load(er[k]['path']);assert (j['status'],j['returncode'])==('completed',0) and j['request']['case_id']==cid
 times=x['actual_time_s'];gs=ET.parse(er['xmf_xml']['path']).findall('.//Grid[@GridType="Uniform"]')
 assert len(times)==len(gs)==801 and times==[f['time'] for f in t['lifecycle']['frame_summary']]==[d['actual_time_s'] for d in r['frame_diagnostics']]==[z['time_s'] for z in b['frame_reports']]==[float(g.find('Time').get('Value')) for g in gs]
 assert [times[0],times[-1]]==qi['actual_time_window_s'] and all(math.isfinite(v) for v in times)
 assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256']==b['source']['trajectory_h5_sha256']
 assert pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==sha(er['render_report']['path']) and pub['case_id']==cid
 pf={e['relative_path']:e for e in pub['files_excluding_receipt']};out=Path(pub['published_output_root']);contacts=decision['contact_sheets'];keys=decision['keyframes']
 assert len(contacts)==34 and len(keys)==9 and len({e['path'] for e in contacts+keys})==43
 for e in contacts+keys:
  check(e);p=Path(e['path']);pe=pf[str(p.relative_to(out))];assert sha(p)==pe['sha256'] and p.stat().st_size==pe['bytes']
 nav=[{'path':e['path'],'sha256':e['sha256'],'bytes':Path(e['path']).stat().st_size,'frame':e['frame'],'actual_time_s':times[e['frame']],'role':'navigation metadata, no new personal review'} for e in keys]
 assert [e['frame'] for e in nav]==list(range(0,801,100))
 qa=load(er['initial_qa_report']['path']);assert qa['all_basic_placement_checks_pass'] and not qa['numerical_precision_result_accepted'];bi=qa['input_provenance']['generated_bi4_sha256'];matches=[p for p,dg in n['input_hashes_at_launch'].items() if p.lower().endswith('.bi4') and dg==bi];assert matches
 hp=t['output_hdf5'];hm={stage:{'present':hp in rc.get(field,{}),'value':rc.get(field,{}).get(hp)} for stage,field in [('launch','input_hashes_at_launch'),('after','input_hashes_after_run')]}
 assert all(v['present'] and v['value']==t['output_sha256'] for v in hm.values())
 masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces']
 products.append({'family_id':'F5','case_id':cid,'physical_case_id':pid,'accepted_visual_decision':dr,'own_full801_QI':ref(qip),'primary_metadata':er,'ParaView_open_XMF':er['xmf_xml'],'frames':801,'particles':194427,'actual_time_window_s':qi['actual_time_window_s'],'all801_UID_N3_native_times_finite_render_and_fullbed_metadata_verified':True,'genuine_initial_placement_QA':{'receipt':er['initial_qa_receipt'],'report':er['initial_qa_report'],'GenCase':er['gencase_receipt'],'generated_XML':er['generated_xml'],'native_initial_BI4_launch_matching_paths':matches,'BI4_hash_is_producer_attestation_not_main_payload_IO':True,'numerical_precision_negative_preserved':qa['numerical_precision']},'actual_native_physical_condition_sha256':n['request']['physical_condition_sha256'],'actual_typed_scope_sha256':t['hash_scopes']['physical_condition_sha256'],'actual_XMF_condition_sha256':x['physical_condition_sha256'],'actual_native_XMF_plan_field_namespaces':masks,'actual_bed_source_plan_physical_condition_field':{'present':'source_plan_physical_condition_sha256' in b,'value':b.get('source_plan_physical_condition_sha256')},'render_H5_launch_after_field_masks':hm,'atomic_publish_receipt':er['render_publish_receipt'],'legacy_atomic_publish_receipt_absent':False,'contacts34_actual_SHA_verified':contacts,'source_personal_key_refs_preserved':keys,'navigation9_actual_SHA_verified':nav,'original_legacy30_row_preserved':None,'new14_own_QI_limits_preserved':None,'newly_added_actual_own_QI_limits_preserved':qi,'new_case_credit':0,'new_personal_review':False,'Q_N':0,'Q_E':0,'precision_status':'视觉检查通过、数值精度未验收','zero_bed_bins_are_not_subDP_or_precision_certification':True})
 added.append({'original':original,'accepted_decision':dr,'own_QI':ref(qip),'actual_native_XMF_plan_field_namespaces':masks,'actual_SourceDef':qi['actual_SourceDef'],'actual_source_plan_JSON_file':qi['actual_source_plan_JSON_file']})
accepted={r['physical_case_id'] for r in idx['cases'] if r['family_id']=='F5' and r.get('accepted_decision')};assert {r['physical_case_id'] for r in products}==accepted and len(products)==47
pending=[p for p in old['pending3_registered_physical_cases'] if p['physical_case_id'] not in accepted];assert len(pending)==1
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_F5_actual47_primary801_fullbed_extend45_actual1184_1175_personal86PNG_actual_native_plan_absences_preserved_1446';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_331.json';assert not O.exists() and not np.exists();O.mkdir()
proof=O/'actualF5-primary47-extension45-two-new-ownQI-personal-and-source-role-proof.json';put(proof,{'schema':'ds02.main.F5.actual47.primary-extension-proof.v1','at_utc':now.isoformat(),'inherited45_product':oldref,'inherited45_independent_proof':old['main_independent_verification'],'previous45_rows_copied_exactly_and_not_recertified':products[:45]==old['accepted45_actual_primary_bed_rows'],'newly_added_actual_cases':added,'new_two_personal86PNG_actual_SHA_and_publication_verified':True,'new_two_801_XML_native_exact_times_bed_and_render_metadata_checked':True,'all47_genuine_initial_QA_joins':True,'actual_native_plan_absences_and_SourceDef_FILE_roles_preserved':True,'legacy_atomic_publish_absence_count_retained':4,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'new_case_credit':0,'Q_N':0,'Q_E':0})
product=O/'F5-FINAL48-ACTUAL47ACCEPTED-ONEPENDING-PRIMARY-BED-DELIVERY.json';put(product,{'schema':'ds02.main.F5.actual-final48-primary-bed.47accepted-onepending.v1','at_utc':now.isoformat(),'authoritative_checkpoint':ref(cpfile),'main_independent_verification':ref(proof),'membership':old['membership'],'accepted47_actual_primary_bed_rows':products,'pending1_registered_physical_cases':pending,'delivery_complete':False,'accepted47_primary_bindings_complete':True,'legacy_publication_absences_and_source_field_limits_preserved':True,'new_case_credit':0,'Q_N':0,'Q_E':0,'scientific_payload_IO':False})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=331,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actual F2 final48 primary delivered; F5 two cases accepted334; lastF3 completed836QI. This checkpoint extends actual F5primary45 to47 after both personal43PNG adoptions, preserving genuine QA and original plan-field absences.',authorized_work_state='Active334/336: F3last1101 completedQI pending229 personal, F5last1149 original rendering. Actual F5primary47 delivered; global336 final delivery and physical distinction audit still required.')
new['actual_progress']['F5_current47_actual_primary_bed_delivery']=ref(product);new['next_executable_tasks'].insert(0,'Adopt F3personal229 and extend F3primary47 to48; finish1149 natural0/pub801QI and delegated personal review, extend F5primary47 to48; complete global336 delivery with physical-distinction audit194.')
put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);idx['F5_current47_actual_primary_bed_delivery']=ref(product);put(O/'full336-current334-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: extend actual F5 primary delivery to47 retaining real native-plan absence and visual limits','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':331,'accepted':334,'F5_primary':47,'pendingF5':1,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
