from pathlib import Path
import json,os,signal,time,hashlib,ast,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_F5_actual850_native12_lease_snapshot_race_remaining22_successor_871';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def root(n):return next(H.glob(f'root*_{n}'))
def put(p,d):Path(p).write_text(json.dumps(d,indent=2)+'\n')
def live(c):
 p=Path('/proc')/str(c['pid'])
 if not p.exists():return False
 f=(p/'stat').read_text().split(') ',1)[1].split();return f[0]!='Z' and f[19]==c['proc_start_ticks'] and c['controller'].encode() in (p/'cmdline').read_bytes()
old=load(root(850)/'controller-launch-process.json');assert not live(old);log=(root(850)/'controller.log').read_text();assert 'FileNotFoundError' in log and '/leases/' in log;completed=[];unused=[]
for qp in (root(850)/'requests').glob('*native-request.json'):
 q=load(qp);a=Path(q['attempt_root']);rp=a/'execution-receipt.json'
 if rp.exists():
  r=load(rp);assert (r['status'],r.get('returncode'))==('completed',0);frames=len(list((a/'solver_output/data').glob('Part_*.bi4')));assert frames==801;completed.append({'tag':q['source_condition']['tag'],'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':str(qp),'actual_receipt':str(rp),'status':'completed','returncode':0,'actual_full801_native_pass':True,'native_saved_frame_file_count':frames,'reused_original850_actual':True})
 else:assert not a.exists();unused.append({'request':str(qp),'attempt_id':q['attempt_id'],'attempt_root':str(a),'never_registered':True})
assert len(completed)==12 and len(unused)==1
kept=[]
for n in [864,865,866]:
 c=load(root(n)/'controller-launch-process.json');assert live(c);kept.append({'root':n,**c,'kept_live':True,'no_restart':True})
put(O/'existing-consumers-preserved-review.json',{'reason':'Original native850 actual12 remain valid; consumers864865 process those12 and preserve partial result, successor consumers will handle new22 only','controllers':kept,'metadata_retirement_attempt_aborted_before_any_termination':True,'original864_has_actual_scientific_child_now':True,'all_suspended_handles_resumed':True,'scientific_workers_killed_or_restarted':False})
put(O/'original850-terminal-and-reuse-proof.json',{'original850_actual_launch':old,'original_handle_missing_or_zombie':True,'original_controller_exit_code_unknown':True,'actual12_completed0':completed,'unused_original_request_not_executed':unused,'metadata_failure_tail':log[-1700:],'root_cause':'lease pathname disappears after glob because another completed job removes it; scientific outputs completed0','repair_attempt_for_this_root_cause':1,'shared_runtime_leasing_and_foreign_protection_unchanged':True})
put(root(850)/'controller-result.json',{'requested':34,'actual_full801_native_pass_count':12,'pending_not_launched':22,'results':completed,'status':'scheduler_metadata_failure','original_controller_exit_code':None,'native_scientific_failures':0,'failure_proof':str(O/'original850-terminal-and-reuse-proof.json'),'remaining_successor_root':871,'original12_not_rerun':True,'independent_case_increment':0})
s=(root(850)/'batch-controller.py').read_text().replace('import json,hashlib,subprocess,time,sys,datetime,shutil','import json,hashlib,subprocess,time,sys,datetime,shutil,fcntl')
s=s.replace("aid='root-stage1-f5-next34-'+c['tag'].lower()+'-own848849-full801-native-root850'","aid='root-stage1-f5-next34-'+c['tag'].lower()+'-own848849-full801-native-lease-snapshot-successor-root871'")
s=s.replace("while True:\n  ledger=load(D/'runtime/resource-ledger.json');snap=rt.inventory();leased={load(p)['uuid'] for p in (D/'leases').glob('*.json')}","while True:\n  ledger=load(D/'runtime/resource-ledger.json');snap=rt.inventory();leased=set()\n  for lp in (D/'leases').glob('*.json'):\n   try:leased.add(load(lp)['uuid'])\n   except FileNotFoundError:continue # Lease release between glob/read; shared atomic runner remains authoritative.")
s=s.replace("return {'tag':c['tag'],'case_id':c['case_id'],'request':str(qp),'status':'held_for_home_floor_before_registration','returncode':None,'actual_full801_native_pass':False,'independent_case_increment':0}","time.sleep(3);continue")
s=s.replace("def run(c):\n qp=make_request(c);q=load(qp)\n while True:","def run(c):\n qp=make_request(c);q=load(qp)\n with (D/'runtime/stage1-fullnative-native-registration.lock').open('a') as lock:\n  fcntl.flock(lock,fcntl.LOCK_EX)\n  return registered_run(c,qp,q)\ndef registered_run(c,qp,q):\n while True:")
s=s.replace("-q['estimated_storage_bytes']<", "-q['estimated_storage_bytes']-16*1024**3<")
s=s.replace("p=subprocess.run([str(L/'.venv/bin/python'),str(root(230)/'launch.py'),str(qp)],cwd=L,capture_output=True,text=True);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};", "p=subprocess.Popen([str(L/'.venv/bin/python'),str(root(230)/'launch.py'),str(qp)],cwd=L,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True);rp=Path(q['attempt_root'])/'execution-receipt.json'\n while p.poll() is None:\n  if rp.exists() and load(rp)['status']=='running':break\n  time.sleep(.2)\n fcntl.flock(lock_handle_for_registration,fcntl.LOCK_UN) if False else None\n stdout,stderr=p.communicate();p=subprocess.CompletedProcess(p.args,p.returncode,stdout,stderr);r=load(rp) if rp.exists() else {};")
# Release the registration lock after the actual worker registers, not after full solver completion.
s=s.replace('return registered_run(c,qp,q)','return registered_run(c,qp,q,lock)').replace('def registered_run(c,qp,q):','def registered_run(c,qp,q,registration_lock):').replace('fcntl.flock(lock_handle_for_registration,fcntl.LOCK_UN) if False else None','fcntl.flock(registration_lock,fcntl.LOCK_UN)')
s=s.replace("cases=plan['candidates'];results=[run(cases[0])];", "proof=load(O/'original850-terminal-and-reuse-proof.json');original_results=proof['actual12_completed0'];done_ids={r['case_id'] for r in original_results};cases=[c for c in plan['candidates'] if c['case_id'] not in done_ids];assert len(cases)==22;results=original_results+[run(cases[0])];")
s=s.replace('failed=not results[0]', 'failed=not results[-1]')
s=s.replace("sum(r['actual_full801_native_pass'] for r in results),'pending_not_launched'", "sum(r['actual_full801_native_pass'] for r in results),'original12_reused':12,'new22_requested':22,'pending_not_launched'")
ast.parse(s);(O/'batch-controller.py').write_text(s);(O/'controller-contract.json').write_text(json.dumps({'native_source':850,'original12_reused':12,'remaining22_only':True,'lease_glob_disappearance_skipped_only_for_FileNotFoundError':True,'scientific_algorithm_inputs_window_unchanged':True,'shared_native230_atomic_lease_CPU64_home500_foreign_protection_unchanged':True,'new_attempt_ids_distinct':True,'registration_lock_release_after_actual_worker_running':True,'repair_attempt_for_root_cause':1},indent=2)+'\n');(O/'root-preparation-source.py').write_bytes(Path(__file__).read_bytes());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',str(O.relative_to(R)),str((root(850)/'controller-result.json').relative_to(R))],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: preserve F5 native12 and recover remaining22 after lease snapshot race'],cwd=R,check=True,stdout=subprocess.DEVNULL);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()
with (O/'controller.log').open('ab') as log:p=subprocess.Popen([str(L/'.venv/bin/python'),str(O/'batch-controller.py')],cwd=L,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
f=(Path('/proc')/str(p.pid)/'stat').read_text().split(') ',1)[1].split();out={'pid':p.pid,'proc_start_ticks':f[19],'controller':str(O/'batch-controller.py'),'controller_sha256':hashlib.sha256((O/'batch-controller.py').read_bytes()).hexdigest(),'launch_commit':commit,'actual_launched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()};put(O/'controller-launch-process.json',out);print(json.dumps(out))
