from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.py','.md','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'],e['path']
def same(a,b):return a['path']==b['path'] and a['sha256']==b['sha256']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='fe09b3b8943cbbdf658a15cb4da8844c949d04d1';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob('root_followup_223_*'));prefix=P.relative_to(W)
expected={'README.md','manifest.json','metadata/upstream-evidence.json','metadata/visual-evidence.json','metadata/visual-decision.json','metadata/physical-closure.json','scripts/validate_fresh223.py'}
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names};assert all((W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b) for n,b in blobs.items())
before={n:sha(W/n) for n in names};man=load(P/'manifest.json');assert man['manifest_excludes_self'] and {e['path'] for e in man['files']}==expected-{'manifest.json'}
for e in man['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh223.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
u=load(P/'metadata/upstream-evidence.json');v=load(P/'metadata/visual-evidence.json');s=load(P/'metadata/visual-decision.json');closure=load(P/'metadata/physical-closure.json')
qip=root(1425)/'actual1119-full401-own-QI-UID-N3-native-typed-role-one-fluid-omission-previsual-proof.json';assert sha(qip)=='288e88942e32c46bb7465a9eb63e9ed8614a04b0bf8f9f931942b210c29f889d';qi=load(qip);cid=qi['case_id'];pid=qi['physical_case_id'];er=qi['actual_completed_metadata_evidence']
assert all(j['case_id']==cid and j['physical_case_id']==pid for j in [u,v,s,closure])
assert cid=='F2_STAGE1_FIRST48_EXPANSION_RX061_RY014_FILL080_ROT090_DP010_SPATIAL_REFERENCE_SAVE010' and pid=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX061_RY014_FILL080_ROT090'
assert u['assigned_family_id']=='F5' and u['actual_physical_family_id']=='F2' and u['model']==s['reviewer_model']==v['reviewer_model']=='gpt-5.6-luna/max'
assert s['personal_visual_review_completed'] and closure['personal_visual_review_completed'] and s['coherent_motion_observed'] and not s['severe_visual_failure_observed'] and not s['renderer_failure_observed'] and not s['root_image_intervention_required']
assert s['screening_decision']=='nonblocking_visual_screening_with_disclosed_open_rim_dispersion' and s['localized_or_open_rim_dispersion_observed']
for j in [s,closure]:assert j['case_credit_increment']==0 and not j['q_n_granted'] and not j['q_e_granted'] and not j['numerical_precision_accepted'] and not j['strict_container_guarantee']
assert not u['recursive_delegation'] and closure['producer_payload_not_read_or_hashed_by_source_agent']
chain={e['role']:e for e in u['external_metadata_refs']};assert len(chain)==len(u['external_metadata_refs'])
for e in chain.values():check(e)
assert same(chain['main_own_qi'],ref(qip)) and same(u['main_own_qi']['proof'],ref(qip))
for k,e in er.items():check(e)
roles={'native_receipt':'native_receipt','typed_receipt':'typed_receipt','typed_report':'typed_report','XMF_receipt':'xmf_receipt','XMF_manifest':'xmf_manifest','XMF_XML':'xmf_xml','initial_qa_receipt':'initial_qa_receipt','initial_qa_report':'initial_qa_report','typed_source_gencase_receipt':'gencase_receipt','typed_source_generated_xml':'generated_xml','render_receipt':'render_execution_receipt','render_report':'render_report','render_publish_receipt':'render_publish_receipt'}
for k,r0 in roles.items():assert same(er[k],chain[r0])
for k in ['native_receipt','typed_receipt','XMF_receipt','render_receipt','initial_qa_receipt','typed_source_gencase_receipt']:
 j=load(er[k]['path']);assert (j['status'],j['returncode'])==('completed',0) and j['request']['case_id']==cid
assert qi['all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified'] and qi['genuine_initial_QA_receipt_completed0_and_report_pass'] and not qi['all_native_UIDs_active_each_frame']
canonical=qi['native_canonical_condition_sha256'];legacy=qi['typed_XMF_actual_legacy_producer_condition_sha256'];n=load(er['native_receipt']['path']);x=load(er['XMF_manifest']['path']);t=load(er['typed_report']['path']);r=load(er['render_report']['path']);rc=load(er['render_receipt']['path']);pub=load(er['render_publish_receipt']['path'])
assert canonical==n['request']['physical_condition_sha256']==closure['native_canonical_scope_sha256']=='d5554e9607723d41638618937d2c681cfdec3084b54297bf0e75b4f82a9885bc'
assert legacy==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']==closure['typed_xmf_legacy_scope_sha256']=='cb836db0de7dd6e6b9e2beef7f8dbffb85a461af59aa8db10feccdcde9ec11e7'
assert canonical!=legacy and not closure['scope_equality_claimed']
masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces']==closure['native_xmf_plan_masks']
assert masks['native']==u['scope_roles']['native_plan_masks'] and masks['XMF']==u['scope_roles']['xmf_plan_masks']
assert closure['lifecycle_omissions']==u['lifecycle_omissions']==qi['lifecycle_omissions'];om=qi['lifecycle_omissions'];assert om['final_missing_particles']==om['max_missing_per_frame']==1 and om['first_missing_frame']==157 and om['cumulative_particle_frame_omissions']==244 and om['producer_attested_final_Idp_sample']==[403829] and om['missing_location_state_cause_unknown']
assert closure['initial_type_counts']==qi['actual_initial_type_counts'] and closure['terminal_type_counts']==qi['actual_terminal_type_counts']
assert u['actual_shape']['time_window_s']==qi['actual_time_window_s']==[0.0,4.000022778759003] and closure['actual_end_time_s']==qi['actual_time_window_s'][-1]
assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256']==u['producer_attested_h5_sha256']==closure['producer_attested_h5_sha256']
assert r['frames']==r['source_frames']==401 and r['all_frames_rendered'] and r['manifest_sha256']==sha(er['XMF_manifest']['path']) and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0
assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['attempt_id']==rc['request']['attempt_id'] and pub['report_sha256_after_rebind']==sha(er['render_report']['path'])
contacts=[e for e in v['published_pngs'] if e['role']=='contact_sheet'];keys=[e for e in v['published_pngs'] if e['role']=='keyframe'];assert [e['index'] for e in contacts]==list(range(17)) and [e['index'] for e in keys]==list(range(0,401,50)) and len({e['absolute_path'] for e in contacts+keys})==26
out=Path(pub['published_output_root']);pf={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['absolute_path'] for e in contacts]==r['outputs']['contact_sheets'] and [e['absolute_path'] for e in keys]==[str(out/f'frames/frame_{i:04d}.png') for i in range(0,401,50)]
jc=[];jk=[]
for e,group in [(e,jc) for e in contacts]+[(e,jk) for e in keys]:
 p=Path(e['absolute_path']);rel=str(p.relative_to(out));decl=pf[rel];dg=sha(p);assert e['relative_path']==rel and e['viewed_by_source_agent'] and not e['sha256_computed_by_source_agent'] and dg==e['producer_sha256']==decl['sha256'] and p.stat().st_size==e['observed_stat_bytes']==e['producer_bytes']==decl['bytes']
 row0={**e,'path':str(p),'sha256':dg,'bytes':p.stat().st_size,'viewed':True,'view_method':'view_image','main_hash_matches_actual_publisher':True}
 if group is jk:row0['frame']=e['index']
 group.append(row0)
now=datetime.datetime.now(datetime.timezone.utc);reviewed=s['review_completed_at_utc'];assert reviewed==v['review_completed_at_utc'] and datetime.datetime.fromisoformat(rc['finished_at_utc'])<=datetime.datetime.fromisoformat(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_319.json';cp=load(cpfile);ip=root(1431)/'full336-current329-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==329 and cp['accepted_per_family']['F2']==46
row=next(e for e in idx['cases'] if e['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(e['kind'] for e in ld['attempts']);gpu=sum(e.get('gpu_seconds',0) for e in ld['charges'])/3600;cpu=sum(e.get('cpu_core_seconds',0) for e in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source223_actualF2_RX061ROT090_original1119_full401QI_personal26PNG_open_rim_dispersion_one_UID_omission_truthful_visual_acceptance_1432';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_320.json';assert not O.exists() and not np.exists();O.mkdir()
for name,b in blobs.items():p=R/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
cv=subprocess.run(['python3','-B',str(R/prefix/'scripts/validate_fresh223.py')],capture_output=True,text=True);assert cv.returncode==0,(cv.stdout,cv.stderr);assert all((R/name).read_bytes()==b and (W/name).read_bytes()==b for name,b in blobs.items())
proof=O/'source223-byte-exact-readonly-validator-main26publishedPNG-full401QI-nonblocking-review-and-scope-proof.json'
put(proof,{'schema':'ds02.source223.main.actualF2.visual-adoption.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/name) for name in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'copied_validator_stdout':cv.stdout,'full401_own_QI':ref(qip),'all26_unique_publishedPNG_SHA_match_actual_atomic_publish':True,'source_literal_screening_decision':s['screening_decision'],'main_stage1_acceptance_basis':'Delegated full-sequence/keyframe personal screening declares coherent motion and no severe failure; disclosed open-rim dispersion and one unknown fluid omission remain explicit limitations, without strict containment or numerical accuracy certification.','source_model':s['reviewer_model'],'actual_native_XMF_plan_namespaces':masks,'actual_personal_review_time_utc':reviewed,'review_after_actual_publication':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/(pid+'-delegated-visual-decision.json');put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F5','actual_review_family':'F2','source_personal_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'source_review_closure':ref(proof),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':401,'particle_count':418104,'actual_initial_type_counts':qi['actual_initial_type_counts'],'actual_terminal_type_counts':qi['actual_terminal_type_counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all401_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':False,'lifecycle_omissions':om,'actual_native_XMF_plan_field_namespaces':masks,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':jc,'keyframes':jk,'source_literal_screening_decision':s['screening_decision'],'visual_observations':v['observations'],'visual_limits':s['limitations'],'localized_or_open_rim_dispersion_observed':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source223-actual1119-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(proof),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1;new.update(checkpoint=320,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=330,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source189/201 F5 actual1159/1176 accepted328/329, source223 F2 actual1119 accepted330 preserving open-rim dispersion and one unknown fluid omission. Original1063/1189 registered renders live, no new simulations.',authorized_work_state='Active330/336 remaining6. F1/F4/F6/F7=48 F2=47 F3=47 F5=44. Final actual family/global primary files still required; original1063 and1101 futureQI entries ready after actual0/pub.')
new['actual_progress']['source223_F2_actual1119_visual_acceptance']=ref(ap);new['source_agents']['f5_bed_recovery']='fresh223 actual1119 accepted330; next F2 actual47 primary manual delivery available';new['next_executable_tasks'].insert(0,'Complete F2/F3/F5 actual primary delivery joins; after registered1063/1189 renders complete verify fullQI then delegate personal review. Preserve final336 scope.')
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==330;put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=330,registered_pending_independent_physical_cases=6,new_case_credit=1);row.update(status='visual-approved-in-checkpoint320',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip))
idx['actual_unaccepted_completed0_published_physical_cases']=[e for e in idx['actual_unaccepted_completed0_published_physical_cases'] if (e if isinstance(e,str) else e['physical_case_id'])!=pid]
assert len(idx['cases'])==len({e['physical_case_id'] for e in idx['cases']})==336 and sum(bool(e.get('accepted_decision')) for e in idx['cases'])==330
put(O/'full336-current330-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX061 ROT090 personal26PNG preserving open-rim dispersion and one fluid omission','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':320,'accepted':330,'F2':47,'pending':6,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
