from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 if isinstance(e,str):e={'path':e}
 assert Path(e['path']).is_file()
 if e.get('sha256'):assert sha(e['path'])==e['sha256'],e['path']
 if e.get('bytes') is not None:assert Path(e['path']).stat().st_size==e['bytes']
 return ref(e['path'])
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit='8ca49a8e37846f817144579992c540af6aae3969';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_174_f3_assigned_f5_final48_primary_delivery_28accepted_twenty_pending_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh174.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
for e in load(P/'package-manifest.json')['files']:
 if e['path']=='package-manifest.json':assert e.get('sha256') in {None,'self-hash-omitted-until-final-blob'}
 else:assert sha(P/e['path'])==e['sha256']
sp=P/'F5-FINAL48-PRIMARY-DELIVERY-28ACCEPTED-TWENTY-PENDING.json';s=load(sp);cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_260.json';cp=load(cpfile);assert cp['checkpoint']==260 and cp['stage1_visual_accepted_complete_independent_cases']==304 and cp['accepted_per_family']['F5']==30;ip=root(1343)/'full336-current304-actual-final48-delivery-progress-index.json';index=load(ip);current={r['physical_case_id']:r for r in index['cases'] if r['family_id']=='F5'};fixed=load(root(1293)/'F5-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json');member=s['membership'];f8=member['frozen_first8_physical_case_ids'];f24=member['actual_first24_physical_case_ids'];f48=member['registered_final48_physical_case_ids'];assert len(set(f8))==8 and len(set(f24))==24 and len(set(f48))==48 and set(f8)<=set(f24)<=set(f48)==set(current);assert f8==fixed['frozen_first8_physical_case_ids'] and f24==fixed['actual_first24_physical_case_ids'];src={r['physical_case_id']:r for r in s['rows']};assert len(src)==48
verified=[];pending=[];recovered_rc=[];pubabs=[];contacts=keys=navcount=0;newvsfreeze=[];maskdiff=[]
for pid,cur in current.items():
 a=src[pid].get('accepted_visual_metadata');dp=cur.get('accepted_decision')
 if not dp:
  p=src[pid]['pending_metadata'];assert p['accepted_decision'] is None and p['primary_particle_xmf_render_refs'] is None
  for group in ['native_metadata_refs','typed_metadata_refs','xmf_metadata_refs','loaded_wrapper_metadata_refs','artifact_audit_metadata_refs']:
   for e in p[group]:checked(e)
  assert len(p['native_metadata_refs'])==len(p['loaded_wrapper_metadata_refs'])==1;nr=load(p['native_metadata_refs'][0]['path']);nq=nr['request'];wr=p['loaded_wrapper_metadata_refs'][0];w=load(wr['path']);m=load(w['manifest']);assert nr['status']=='completed' and nr['returncode']==0 and nq['physical_case_id']==m['physical_case_id']==pid and nq['physical_condition_sha256']==cur['native_request_scope']['sha256'];assert w['expected_frames']==m['frames']==801 and w['expected_particles']==m['particles']==194427 and m['fields']['position']['shape']==m['fields']['velocity']['shape']==[801,194427,3]
  pending.append({'physical_case_id':pid,'actual_native_completed0':checked(p['native_metadata_refs'][0]),'actual_wrapper':checked(wr),'actual_wrapper_own801_N3_manifest':ref(w['manifest']),'native_actual_condition_sha256':nq['physical_condition_sha256'],'XMF_own_declared_condition_sha256':m['physical_condition_sha256'],'source_historical_snapshot_not_current_visual_acceptance':True,'accepted_decision':None,'new_case_credit':0});continue
 checked(dp);d=load(dp['path']);assert d['physical_case_id']==pid and d['family_id']=='F5';er=d.get('actual_completed_metadata_evidence',{})
 if a:
  assert a['accepted_decision']==dp
  for group in ['native_refs','typed_refs','bed_refs']:
   for e in a[group]:checked(e)
  mr=a['actual_xmf_manifest'];xr=a['actual_xmf_xml'];rr=a['actual_render_report'];sr=a['actual_render_receipt'];cpng=a['contact_png_refs'];kpng=a['key_png_refs']
 else:
  assert pid in {'F5_COMPACT_RUNUP_RECOVERY_C082S1_M105_T080','F5_COMPACT_RUNUP_RECOVERY_C082S1_M112_T095'};mr=er['xmf_manifest'];xr=er['xmf_xml'];rr=er['render_report'];sr=er['render_receipt'];cpng=d['contact_sheets'];kpng=d['keyframes'];newvsfreeze.append(pid)
 for e in [mr,xr,rr]:checked(e)
 mp=Path(mr['path']);xp=Path(xr['path']);rp=Path(rr['path']);m=load(mp);r=load(rp);assert m['physical_case_id']==pid and m['frames']==r['frames']==r['source_frames']==801 and m['particles']==194427 and m['fields']['position']['shape']==m['fields']['velocity']['shape']==[801,194427,3];assert r['all_frames_rendered'] and not r['diagnostic_only'] and r['nonfinite_active_states']==0 and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['source_h5_read_only'];assert r['input_manifest']==str(mp) and r['manifest_sha256']==sha(mp) and m['xdmf']==r['xdmf']==str(xp) and m['xdmf_sha256']==sha(xp)==r['xdmf_sha256_before']==r['xdmf_sha256_after'];assert [f['frame'] for f in r['frame_diagnostics']]==list(range(801)) and [f['actual_time_s'] for f in r['frame_diagnostics']]==m['actual_time_s']
 nrp=Path(m['native_receipt']);nr=load(nrp);nq=nr['request'];tp=Path(m['conversion_report']);t=load(tp);assert nr['status']=='completed' and nr['returncode']==0 and nq['physical_case_id']==pid and nq['physical_condition_sha256']==cur['native_request_scope']['sha256'];assert t['output_sha256']==m['source_h5_sha256']==r['source_h5_sha256'] and t['source_provenance']['solver_receipt']==ref(nrp);canonical=nq['physical_condition_sha256'];typed=t['hash_scopes']['physical_condition_sha256'];assert m['source_h5_physical_condition_sha256']==typed
 rcp=Path(sr['path']) if sr else rp.parent.parent/'execution-receipt.json';rc=load(rcp);assert rc['status']=='completed' and rc['returncode']==0 and rc['request']['case_id']==nq['case_id']==m['case_id']
 if sr:checked(sr)
 else:recovered_rc.append({'physical_case_id':pid,'source_terminal_receipt_field':{'present':False,'value':None},'actual_same_report_attempt_receipt':ref(rcp),'actual_runtime_receipt_recovered_not_atomic_publish_receipt_invented':True})
 hp=t['output_hdf5'];assert Path(hp).is_file()
 attestations={}
 for role,path,digest in [('H5',hp,t['output_sha256']),('manifest',str(mp),sha(mp)),('XML',str(xp),sha(xp))]:
  masks={stage:{'present':path in rc[key],'value':rc[key].get(path)} for stage,key in [('launch','input_hashes_at_launch'),('after','input_hashes_after_run')]}
  for msk in masks.values():
   if msk['present']:assert msk['value']==digest
  attestations[role]={'path':path,'actual_receipt_masks':masks,'both_actual_receipt_attestations_present':all(msk['present'] for msk in masks.values()),'absences_not_filled_from_report_or_producer':True}
 bedref=er.get('bed_report',er.get('bed_audit_report'));bedrc=None
 if er.get('bed_receipt'):bedrc=er['bed_receipt']
 if not bedref:
  candidates=[]
  for e in a['bed_refs']:
   j=load(e['path'])
   if 'frame_reports' in j:candidates.append(e)
   elif 'actual_bed_report' in j:
    v=j['actual_bed_report'];candidates.append(v if isinstance(v,dict) else {'path':v,'sha256':j['actual_bed_report_sha256']});v=j.get('actual_receipt');bedrc=v if isinstance(v,dict) else bedrc
   elif 'rows' in j:
    row=next(z for z in j['rows'] if pid==f"F5_COMPACT_RUNUP_RECOVERY_C082S1_{z['tag']}");candidates.append({'path':row['actual_bed_report'],'sha256':row['actual_bed_report_sha256']});bedrc={'path':row['actual_bed_receipt'],'sha256':row['actual_bed_receipt_sha256']}
  paths={e['path']:e for e in candidates};assert len(paths)==1,(pid,paths);bedref=next(iter(paths.values()))
 checked(bedref);bp=Path(bedref['path']);bed=load(bp)
 if bedrc is None:bedrc=ref(bp.parent.parent/'execution-receipt.json')
 checked(bedrc);bc=load(bedrc['path']);assert bc['status']=='completed' and bc['returncode']==0 and bc['request']['case_id']==nq['case_id'];assert bed['scan']['frames_scanned']==len(bed['frame_reports'])==801 and bed['scan']['particle_axis_count']==194427 and bed['scan']['initial_fluid_uid_count']==31658;assert bed['bound_actual_inputs']['physical_case_id']==pid and not bed['source_arrays_modified'] and not bed['source_arrays_dropped_or_masked']
 source_def=bed.get('source_plan_physical_condition_sha256');mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',m)]};actualroles={'native_canonical':{'present':'physical_condition_sha256' in nq,'value':canonical},'native_plan_namespaces':mask['native'],'typed_actual_converter':{'present':'physical_condition_sha256' in t['hash_scopes'],'value':typed,'schema':t['hash_scopes']['physical_condition']['schema']},'XMF_declared_condition':{'present':'physical_condition_sha256' in m,'value':m.get('physical_condition_sha256')},'XMF_source_h5_condition':{'present':'source_h5_physical_condition_sha256' in m,'value':m.get('source_h5_physical_condition_sha256')},'XMF_plan_namespaces':mask['XMF'],'bed_declared_SourceDef_plan':{'present':'source_plan_physical_condition_sha256' in bed,'value':source_def}}
 if a:
  source_roles=a['role_field_presence'];comparable=[('native_canonical',actualroles['native_canonical']),('typed_legacy',actualroles['typed_actual_converter']),('xmf_declared_canonical',actualroles['XMF_declared_condition']),('xmf_source_h5',actualroles['XMF_source_h5_condition']),('bed_source_def',actualroles['bed_declared_SourceDef_plan'])];different=[key for key,v in comparable if source_roles[key]['present']!=v['present'] or source_roles[key]['value']!=v['value']]
  if different:maskdiff.append({'physical_case_id':pid,'source_decision_scoped_presence_roles_preserved':source_roles,'actual_raw_role_masks':actualroles,'different_role_keys':different,'source_decision_mask_not_used_as_raw_native_typed_XMF_bed_field_authority':True})
 pubp=rp.parent/'render-publish-receipt.json';pubref=None
 if pubp.is_file():
  pub=load(pubp);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==nq['case_id'] and pub['report_sha256_after_rebind']==sha(rp);pubref=ref(pubp)
 else:pubabs.append(pid)
 cr=[checked(e) for e in cpng];kr=[checked(e) for e in kpng];assert len(cr)==34 and [e['path'] for e in cr]==r['outputs']['contact_sheets'];contacts+=len(cr);keys+=len(kr);fd=Path(r['outputs']['frames_dir']);assert fd.is_relative_to(D) and sorted(p.name for p in fd.glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(801)];nav=[]
 for i in [0,100,200,300,400,500,600,700,800]:
  fp=fd/f'frame_{i:04d}.png';assert fp.stat().st_size>0;nav.append({**ref(fp),'bytes':fp.stat().st_size,'frame':i,'actual_time_s':m['actual_time_s'][i],'role':'published_navigation_not_new_personal_review'})
 navcount+=len(nav);verified.append({'physical_case_id':pid,'actual_native_case_id':nq['case_id'],'mother_case_id_alias_is_not_distinct_physical_case_identity':True,'accepted_visual_decision':checked(dp),'actual_native_receipt':ref(nrp),'primary_typed_report':ref(tp),'primary_XMF_manifest':ref(mp),'primary_XMF_XML':ref(xp),'primary_render_report':ref(rp),'actual_render_execution_receipt':ref(rcp),'actual_receipt_producer_launch_after_attestation_masks':attestations,'source_render_execution_receipt_field_absent':sr is None,'actual_atomic_publish_receipt':pubref,'actual_atomic_publish_receipt_field_present':pubref is not None,'legacy_direct_render_publish_receipt_not_invented':pubref is None,'actual_full801_bed_receipt':checked(bedrc),'actual_full801_bed_report':checked(bedref),'actual_native_typed_XMF_bed_raw_role_masks':actualroles,'source_decision_presence_matrix_is_not_raw_producer_field_authority':bool(a),'all801_native_particle_geometry_velocity_N3_times_identity_render_bindings_verified':True,'existing_bed_precision_negatives_retained_not_new_numerical_certification':True,'actual_source_contacts':cr,'actual_source_keys':kr,'source_unlisted_key_field_preserved':not bool(kpng),'main_actual_published_navigation_keys':nav,'new_case_credit':0,'new_personal_review':False,'scientific_payload_IO':False})
assert len(verified)==30 and len(pending)==18 and len(newvsfreeze)==2 and len(recovered_rc)==2 and contacts==1020 and keys==257 and navcount==270;assert set(pubabs)=={'F5_COMPACT_RUNUP_RECOVERY_C082S1_A080','F5_COMPACT_RUNUP_RECOVERY_C082S1_A120','F5_COMPACT_RUNUP_RECOVERY_C082S1_M085_T080','F5_COMPACT_RUNUP_RECOVERY_C082S1_M115_T100'}
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source174_F5_final48_current30accepted18pending_own801_bed_raw_roles_two_original_runtime_receipt_recoveries_four_publish_absences_1344';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_261.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source174-byte-exact-main-current30-own801-primary-bed-raw-role-and18pending-proof.json';put(vp,{'schema':'ds02.main.F5.current30-final48-own-primary-bed-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_SHA_before_after':before,'source_validator_stdout':rv.stdout,'source_validator_stderr':rv.stderr,'source_original_freeze_28accepted20pending_not_overwritten':True,'current_main_accepted30_verified':verified,'current_main_pending18':pending,'two_accepted_since_source_freeze':newvsfreeze,'two_actual_runtime_receipts_recovered_from_same_report_attempt':recovered_rc,'four_original_atomic_publish_receipt_absences_preserved':pubabs,'source_decision_presence_roles_vs_actual_raw_role_differences':maskdiff,'source_decision_presence_roles_not_raw_authority':True,'main1020contact257sourcekey270publishednavigation_SHA_verified':True,'new_case_credit':0,'new_personal_visual_review':False,'scientific_payload_IO':False,'Q_N':0,'Q_E':0})
pp=O/'F5-FINAL48-CURRENT30ACCEPTED18PENDING-ACTUAL801-PRIMARY-BED-DELIVERY.json';put(pp,{'schema':'ds02.main.F5.final48.current30accepted18pending.actual801.primary-bed-delivery.v1','at_utc':now.isoformat(),'source_original_exact_frozen28_20_catalog':ref(R/prefix/sp.name),'stable_predecessor_checkpoint':ref(cpfile),'main_independent_verification':ref(vp),'membership':member,'current_accepted_count':30,'current_pending_count':18,'main_current_accepted30_actual_primary_rows':verified,'main_current_pending18_readiness_rows':pending,'four_legacy_atomic_publish_receipt_absences':pubabs,'source_original_metadata_bytes_unchanged':True,'scope_masks_derived_from_actual_raw_native_typed_XMF_bed_not_decision_aliases':True,'new_case_credit':0,'Q_N':0,'Q_E':0,'scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new.update(checkpoint=261,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source174 F5 final48 current30accepted18pending main delivery bound to own801/194427 particle, bed and actualraw scope masks; source28/20 frozen unchanged, two old actualruntime receipt references recovered while four atomicpublish absences preserved. LastF6 ownQI1341 personal189 in progress; originalF3 1102 and originalF2 1155 same live renderers; nextF2 source175 personally review after actualownQI1346.',authorized_work_state='Active304/336; currentF5 final48 actualprimary30accepted/18pending delivered, originalsource17428/20 historical freeze retained. LastF6 personal189 visual pending; F3 personal209 original1102 and F2 personal175 original1155 awaiting original actualpublication/ownQI.')
new['actual_progress']['F5_final48_actual_current30accepted18pending_primary_bed_delivery']=ref(pp);new['actual_progress']['F5_final48_main_actualraw_scope_roles_source174_proof']=ref(vp);new['source_agents']['production_recovery']='source174 final48 source frozen28/20 exact adopted with actualcurrent30/18 main sidecar; fresh175 F2 original1155 RX063 ROT105 personal task assigned';put(np,new);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);index['actual_F5_final48_current30accepted18pending_primary_bed_delivery']=ref(pp)
for row in index['cases']:
 if row['family_id']=='F5':row['actual_F5_final48_current30accepted18pending_primary_bed_delivery']=ref(pp)
put(O/'full336-current304-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: deliver F5 final48 current30 with raw scope roles and four publication absences','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':261,'accepted':304,'F5_primary_actual':30,'F5_pending':18,'four_pub_absences':len(pubabs),'two_source_runtime_ref_absences_corrected':len(recovered_rc),'decision_raw_scope_mask_differences':len(maskdiff),'contacts':contacts,'sourcekeys':keys,'navigationkeys':navcount,'product':ref(pp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
