from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.py','.md','.xml','.xmf','.sh','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_168_f2_rx047_native_chain_reference_closure_v1';commit='26b1efbf1c343b9a45ebf4a889f36430c0981f67';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==4;before={n:sha(W/n) for n in names};P=W/prefix;vld=P/'scripts/validate_fresh168.py';vr=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert vr.returncode==0 and before=={n:sha(W/n) for n in names};source=load(P/'metadata/rx047-native-chain-closure.json');assert len(source['cases'])==3 and source['new_case_credit']==0
idxp=root(1225)/'full336-current272-role-aware-registration-progress-index.json';idx=load(idxp);cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_199.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==272;actual=[]
for row in source['cases']:
 role=row['native_actual_role'];rp=Path(role['receipt']['path']);qp=Path(role['request']['path']);assert sha(rp)==role['receipt']['actual_sha256'] and sha(qp)==role['request']['actual_sha256'];n=load(rp);q=n['request'];assert n['status']=='completed' and n['returncode']==0 and n['request_sha256']==sha(qp) and q['physical_case_id']==row['physical_case_id'] and q['case_id']==row['case_id'];assert q['expected_native_frames']==401 and q['expected_dimension']==3
 dr=Path(row['accepted_decision']['path']);assert str(dr) in cp['accepted_decisions'] and sha(dr)==row['accepted_decision']['actual_sha256'];ad=load(dr);assert ad['physical_case_id']==q['physical_case_id'];tr=Path(row['typed_conversion']['report']['path']);assert sha(tr)==row['typed_conversion']['report']['actual_sha256'];t=load(tr);assert t['conversion_status']=='completed' and t['frames']==401 and t['solver_dimension']['solver_dimension']==3 and t['source_provenance']['solver_receipt']==ref(rp)
 assert not role['receipt_identity']['physical_binding_present'] and 'physical_binding' not in q
 entries=[x for x in idx['cases'] if x['physical_case_id']==q['physical_case_id']];assert len(entries)==1 and entries[0].get('accepted_decision');dest=entries[0];old=dest.get('native_request_scope');field=q.get('physical_condition_sha256');assert isinstance(field,str) and len(field)==64
 evidence={'receipt':ref(rp),'status':n['status'],'returncode':n['returncode'],'returncode_field_present':'returncode' in n,'native_completed0':True,'embedded_request_case_id':q['case_id'],'embedded_request_physical_case_id':q['physical_case_id'],'embedded_request_condition_sha256':field,'receipt_request_sha256':n['request_sha256'],'physical_binding_field_present':False,'request_metadata':ref(qp)}
 dest['native_request_scope']={'sha256':field,'role':'actual native receipt embedded request condition','evidence':evidence,'condition_is_not_inferred_from_accepted_top_or_source_plan':True};dest['previous_native_scope_preserved_snapshot']=old;dest['top_or_render_declared_condition_equals_actual_native_request']=ad['physical_condition_sha256']==field;dest['source168_original_missing_producer_chain_preserved']=row['native_actual_role']['chain_native_ref_present_in_source_chain_json'];actual.append({'physical_case_id':q['physical_case_id'],'actual_native_receipt':ref(rp),'actual_request':ref(qp),'actual_native_condition_field':field,'accepted_semantic_condition':ad['physical_condition_sha256'],'observed_semantic_native_equal':ad['physical_condition_sha256']==field,'typed_report':ref(tr),'typed_report_native_receipt_ref_exact':True,'actual_physical_binding_field_present':False,'source168_role_fields':row['scope_roles'],'original_chain_native_ref_present':role['chain_native_ref_present_in_source_chain_json'],'original_native_resolution_source':role['native_request_resolution_source'],'original_missing_native_index_snapshot_preserved':old})
O=H/'root_stage1_source168_F2_RX047_three_actual_native_condition_and_converter_refs_closed_absence_preserved_checkpoint_1228';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_200.json').exists();adopt=[]
for n in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert raw==(W/n).read_bytes();p=R/n;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopt.append(ref(p))
put(O/'actual-source168-readonly-validator.json',{'validator':ref(vld),'returncode':vr.returncode,'stdout':vr.stdout,'stderr':vr.stderr,'source_original_bytes_unchanged':True});proof=O/'actual168-own-native-request-and-typed-provenance-closure.json';put(proof,{'source_commit':commit,'adopted_files':adopt,'source_validator':ref(O/'actual-source168-readonly-validator.json'),'actual_cases':actual,'true_absence_guard_original':source['untouched_true_absence_guard'],'no_source_or_native_receipt_mutation':True,'no_semantic_condition_as_native_substitute':True,'main_scientific_payload_IO':False,'new_case_credit':0,'accepted_cases':272});now=datetime.datetime.now(datetime.timezone.utc).isoformat();lb=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(lb);lf=O/'resource-ledger-frozen.json';lf.write_bytes(lb);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500
cp.update(checkpoint=200,at_utc=now,predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(lb).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ld['reservations'],attempt_counts=dict(collections.Counter(x['kind'] for x in ld['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600,previous_goal_turn_classification='Progress: source192 accepted272/F5=12 and actual1130 full801QI closed. Source168 closes own three RX047 actual-native embedded fields+typed-native receipt refs; preserves one coarse true absence and missing ROT090 producer_chain, no new case credit or numerical certification.');cp['actual_progress']['source168_F2_RX047_three_actual_native_JSON_roles_closed']=ref(proof);cp['source_agents']['f6_endpoint_initial_qa']='fresh168 adopted; fresh169 actualF6first8/24/final48 and new actualF2published0 visual priority';cp['next_executable_tasks'][2]='Adopt source150 and151 authoritative actual F1/F4/F7 batch membership; finish source169 F6 batch relations.';newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_200.json';put(newcp,cp);idx.update(schema='ds02.stage1.full336.role-aware-progress-index.v6',at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxp),new_F2_actual_native_JSON_role_closure=ref(proof),native_request_field_digest_available=sum(isinstance(x.get('native_request_scope',{}).get('sha256'),str) for x in idx['cases']),native_request_field_digest_not_available=sum(not isinstance(x.get('native_request_scope',{}).get('sha256'),str) for x in idx['cases']),new_case_credit=0);put(O/'full336-current272-native-request-roles-with-actual168-F2-closure.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopt]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close three accepted RX047 actual native provenance roles without new credit','--',*paths],cwd=R,check=True);print({'accepted':272,'checkpoint':200,'actual_native_field_known':idx['native_request_field_digest_available'],'missing':idx['native_request_field_digest_not_available'],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
