from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit=subprocess.check_output(['git','rev-parse','91d3a98c5'],cwd=W,text=True).strip();prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_196_f6_assigned_f3_final48_fulltime_runtime_primary_gate_repair_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==6
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
manifest=load(P/'package-manifest.json');assert {e['path'] for e in manifest['files']}=={str(Path(n).relative_to(prefix)) for n in names if not n.endswith('package-manifest.json')}
for e in manifest['files']:assert sha(P/e['path'])==e['sha256']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_309.json';cp=load(cpfile);ip=root(1416)/'full336-current324-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile)
assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==324
f3=[e for e in idx['cases'] if e['family_id']=='F3'];assert len(f3)==48 and len({e['physical_case_id'] for e in f3})==48;accepted=[e for e in f3 if e.get('accepted_decision')];pending=[e for e in f3 if not e.get('accepted_decision')];assert len(accepted)==cp['accepted_per_family']['F3']==46 and len(pending)==2
frozen=load(P/'metadata/current-readiness/fresh196-readiness.json');assert frozen['complete_final48_emitted'] is False
code=(P/'scripts/build_fresh196.py').read_text();critical=[(1831,1906),(2086,2138),(2289,2480)];lines=code.splitlines();reviewed='\n\n'.join(f'LINES {a}-{z}\n'+'\n'.join(lines[a-1:z]) for a,z in critical)+'\n'
assert 'launch_digest = isinstance(launch_hashes, dict)' in code and 'checks["key_png_refs"] = isinstance(keys, list) and bool(keys)' in code
O=H/'root_stage1_source196_F3_bounded_static_primary_QA_scope_runtime_digest_preview_cardinality_NaN_time_gate_defects_manual_final_primary_1418';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_310.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
assert all((W/n).read_bytes()==b and (R/n).read_bytes()==b for n,b in blobs.items())
(O/'reviewed-critical-functions.txt').write_text(reviewed)
proof=O/'source196-byte-exact-bounded-static-final-primary-gate-audit.json';now=datetime.datetime.now(datetime.timezone.utc)
put(proof,{'schema':'ds02.main.source196.bounded-static-primary-gate-review.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_metadata_manifest_byte_exact_verified':True,'source_preserved_fixed_readiness':ref(R/prefix/'metadata/current-readiness/fresh196-readiness.json'),'source_fixed_observed_counts':frozen['observed_counts'],'main_current_F3_actual_boundary':{'registered':48,'accepted':46,'pending':2},'source_fixed_readiness_not_relabelled_as_main_current_readiness':True,'critical_function_lines_read':critical,'full_builder_or_validator_not_executed_by_main':True,'static_review_sufficient_to_disqualify_strong_final_primary_certification':True,'remaining_code_findings':[
 {'issue':'receipt gate only tests digest snapshots presence; does not compare SHA values or input/output request/producer-consumer join','function':'_f3_receipt_certificate','lines':[1831,1870,1894]},
 {'issue':'primary preview gate needs merely one contact; missing keys produces false boolean but no failure reason; no35/9 cardinality, unique indexed paths, publisher SHA/report join or personal timestamp binding','function':'_f3_primary_completeness','lines':[2438,2459,2470]},
 {'issue':'QA receipt binding called with expected case and physical IDs both None; report passes from generic counts or one direct key, without genuine source704 input SHA/XML/BI4/forcing/parent-case linkage','function':'_f3_qa_certificate','lines':[2289,2304,2318,2335]},
 {'issue':'XML float nan bypasses >= monotonicity and abs difference comparisons; no explicit finite time guard','function':'_f3_xml_certificate','lines':[2086,2107,2126,2130]},
 {'issue':'XMF execution receipt path derived only from xdmf layout; legitimate xmf/manifest.json layouts rejected','function':'_f3_xmf_execution_certificate','lines':[2345,2350,2358]},
 {'issue':'render/XMF join compares paths but omits report/manifest/XMF SHA and producer H5 digest joins','function':'_f3_fulltime_runtime_gate','lines':[2375,2396,2401]},
 {'issue':'original nonterminal native or typed attempts are disclosed but primary gate lacks explicit approved physical-completion recovery handling; preserving unknown runtime must not erase actual fulltime completion evidence','function':'_f3_fulltime_runtime_gate','lines':[2375,2410,2420]}],
 'executed_component_false_positive_tests':False,'no_claim_of_source_validator_PASS_by_main':True,'adoption_scope':'immutable source readiness/reference only; not final48 certification','bounded_repair_no_third_tool_repair':True,'main_actual_cases_are_not_revoked_by_source_gate_lookup_or_schema_gaps':True,'final_primary_route':'manual authoritative fulltime QI/real GenCase-parentQA-source704/actual runtime-original versus recovery/native-typed-XMF namespace roles/published unique navigation and personal timestamp joins per case','original_native059_running_no_RC_and_actual065_physical_completion_runtime_finalization_unknown_preserved':True,'original_typed154_running_no_RC_and_actual1166_artifact1193_XMF_recovery_preserved':True,'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(e['kind'] for e in ld['attempts']);gpu=sum(e.get('gpu_seconds',0) for e in ld['charges'])/3600;cpu=sum(e.get('cpu_core_seconds',0) for e in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30
assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=310,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source197 bounded audit completed with actual falsepositives and separate actual primary route; actual1136 ownQI1412 completed and personal199 active. Source186 original1129 completion/image evidence ready but actual review timestamp final-message/source conflict caught before any shared credit; fresh187 semantic acknowledgment active. Source196 critical gate static review disqualifies final primary certificate; no unsafe fullbuilder execution or thirdrepair.',authorized_work_state='Active324/336 pending12. Production187 actual186 timestamp acknowledgment required before source186 credit. F6fresh199 personalF5original1136 active after own1412. F5fresh221 original1139 waits actual0/pub/own1415. Source196 static bounded audit and197/218 executed bounded audits all readiness/reference-only, manualactual finalprimary joins remain. No new native/render jobs.')
new['actual_progress']['source196_F3_bounded_static_final_gate_audit']=ref(proof);new['actual_progress']['original1136_full801_own_QI1412']=ref(root(1412)/'actual1136-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json')
new['source_agents'].update(production_recovery='fresh186 personal44PNG source/message UTC conflict pending187 actual timestamp acknowledgment; no credit yet',f6_endpoint_initial_qa='fresh199 actual1136 personal43PNG active after completed own1412',f5_bed_recovery='fresh221 original1139 waiting actual0/pub and own1415')
new['next_executable_tasks'].insert(0,'Integrate actual186 only after independent source187 acknowledgment of real personal review UTC; source186 bytes remain immutable. Integrate199 actual1136 after personal43PNG. Observe same1139 worker730565/start214910480 then durableown1415 once after0/pub and personal221; next1159 actualworker739634/start215004646 live needs durableownQI preparation. All finalprimary tools now bounded-reviewed, manual actual percase joins required.')
put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,source196_F3_bounded_static_final_gate_audit=ref(proof));assert len(idx['cases'])==336 and sum(bool(e.get('accepted_decision')) for e in idx['cases'])==324
put(O/'full336-current324-actual-final48-delivery-progress-index.json',idx);(O/'audit-source.py').write_bytes(Path(__file__).read_bytes())
paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bound static F3 source196 audit and preserve actual primary delivery route','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':310,'accepted':324,'F3':46,'source196':'static_readiness_reference_only','proof':ref(proof),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
