from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics')
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
commit='2a0e93288724a68df6b7b963c24f0ae16c1c40fe';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_166_f3_remaining9_pipeline_census_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==4;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};v=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh166.py')],capture_output=True,text=True);assert v.returncode==0,(v.stdout,v.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/f3-remaining9-pipeline-census.json');ip=next(H.glob('root*_1285'))/'full336-current291-actual-final48-delivery-progress-index.json';idx=load(ip);pending={r['case_id']:r for r in idx['cases'] if r['family_id']=='F3' and not r.get('accepted_decision')};assert set(pending)=={c['case_id'] for c in s['cases']} and len(pending)==9;rows=[]
for c in s['cases']:
 cid=c['case_id'];pid=c['physical_case_id'];assert pending[cid]['physical_case_id']==pid;nr=load(c['native']['receipt_path']);assert sha(c['native']['receipt_path'])==c['native']['receipt_sha256_recorded'];assert (nr['status'],nr['returncode'])==('completed',0);nq=nr['request'];assert nq['case_id']==cid and nq['physical_case_id']==pid and nq['expected_saved_frames']==836 and nq['physical_condition_sha256']==c['native']['condition_sha256'];assert nq['nominal_pitch_multiplier']==c['native']['nominal_pitch_multiplier'] and nq['transverse_amplitude_m_s2']==c['native']['transverse_amplitude_m_s2']
 for e in c['native']['metadata_input_hash_closure']:
  assert sha(e['path'])==e['launch_sha256_recorded']==e['after_sha256_recorded'];assert nr['input_hashes_at_launch'][e['path']]==nr['input_hashes_after_run'][e['path']]==e['launch_sha256_recorded']
 tr=load(c['typed']['typed_receipt_path']);t=load(c['typed']['conversion_report_path']);xr=load(c['xmf']['receipt_path']);x=load(c['xmf']['manifest_path']);assert (xr['status'],xr['returncode'])==('completed',0) and xr['request']['case_id']==cid
 refs={k:ref(p) for k,p in {'native_receipt':c['native']['receipt_path'],'typed_receipt':c['typed']['typed_receipt_path'],'typed_report':c['typed']['conversion_report_path'],'xmf_receipt':c['xmf']['receipt_path'],'xmf_manifest':c['xmf']['manifest_path']}.items()}
 if cid.endswith('AY0270'):
  assert tr['status']=='running' and 'returncode' not in tr;ar=load(c['typed']['artifact_audit']['receipt_path']);a=load(c['typed']['artifact_audit']['report_path']);assert (ar['status'],ar['returncode'])==('completed',0) and ar['request']['case_id']==cid and a['case_id']==cid and a['worker_returncode']==0;assert a['field_audit']['frames']==836 and a['field_audit']['particles']==179208 and a['field_audit']['n3_shape_verified'] and a['field_audit']['uid_lifecycle_missing_count']==0 and a['approved_temporal_kernel']['checked_transitions']==835 and a['report_frame_ledger']['missing_particles_all_frames']==0
  refs.update(artifact_audit_receipt=ref(c['typed']['artifact_audit']['receipt_path']),artifact_audit_report=ref(c['typed']['artifact_audit']['report_path']))
 else:assert (tr['status'],tr['returncode'])==('completed',0) and tr['request']['case_id']==cid
 assert t['frames']==x['frames']==836 and t['particles']==x['particles']==179208 and t['solver_dimension']['solver_dimension']==3 and t['source_provenance']['solver_receipt']==ref(c['native']['receipt_path']);assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and t['output_sha256']==x['source_h5_sha256']
 times=x['actual_time_s'];fs=t['lifecycle']['frame_summary'];assert len(fs)==len(times)==836 and times==[f['time'] for f in fs] and times[0]==0 and times[-1]>=8.35 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[836,179208,3];assert all(f['frame']==i and f['active_particles']==179208 and f['missing_particles']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500} for i,f in enumerate(fs))
 xml=Path(x['xdmf']);assert sha(xml)==x['xdmf_sha256'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');assert len(grids)==836
 for i,g in enumerate(grids):
  assert float(g.find('Time').get('Value'))==times[i] and g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='179208 3';vel=next(a for a in g.findall('Attribute') if a.get('Name')=='velocity');assert vel.get('AttributeType')=='Vector' and vel.find('DataItem').get('Dimensions')=='179208 3'
 refs['xmf_xml']=ref(xml);sr=c['xmf']['scope_roles'];assert x['physical_condition_sha256']==sr['manifest_physical_condition_sha256'] and x.get('canonical_source_physical_condition_sha256')==sr['manifest_canonical_source_physical_condition_sha256'];assert ('source_plan_condition_sha256' in x)==sr['manifest_source_plan_condition_sha256_key_present'];assert x.get('source_plan_condition_sha256')==sr['manifest_source_plan_condition_sha256']
 wrapper=c['render']['loaded_wrapper'];assert sha(wrapper['path'])==wrapper['sha256_recorded'];w=load(wrapper['path']);assert w['expected_frames']==836 and w['expected_particles']==179208 and w['expected_contact_sheets']==35 and w['global_renderer_cap']==2 and w['cpu_threads']==24 and w['environment_threads']==2;refs['loaded_render_wrapper']=ref(wrapper['path']);launch=c['render']['controller_launch'];assert sha(launch['path'])==launch['sha256_recorded'];p=Path('/proc')/str(launch['pid']);ob={'pid':launch['pid'],'expected_start_ticks':launch['recorded_start_ticks'],'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'live':False}
 try:
  raw=(p/'stat').read_text();ticks=raw[raw.rfind(')')+2:].split()[19];cmd=(p/'cmdline').read_bytes().replace(b'\0',b' ').decode(errors='replace');ob.update(observed_start_ticks=ticks,same_start_ticks=ticks==launch['recorded_start_ticks'],state=raw[raw.rfind(')')+2:].split()[0],command_matches=launch['controller'] in cmd);ob['live']=ob['same_start_ticks'] and ob['command_matches'] and ob['state']!='Z'
 except OSError:pass
 receipt=Path(c['render']['registered_receipt']['path']);ob['render_receipt_exists']=receipt.exists();ob['published_receipt_exists']=(receipt.parent/'render/render-publish-receipt.json').exists();refs['original_outer_request']=ref(c['render']['registered_outer_request']['path'])
 rows.append({'case_id':cid,'physical_case_id':pid,'actual_metadata_evidence':refs,'native_condition_sha256':nq['physical_condition_sha256'],'all836_native_UID_N3_exact_times':True,'no_missing_UIDs_in_typed_frame_ledger':True,'source_scope_roles_preserved':sr,'actual_XMF_exact_plan_field_namespaces':{k:{'present':k in x,'value':x.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']},'source_native_scope_roles_preserved':{k:c['native'][k] for k in ['physical_binding_schema','physical_binding_source_plan_key_present','physical_binding_source_plan_condition_sha256','source_condition_template_FILE_sha256','source_condition_template_FILE_role']},'native_initial_QA_role':'reused exact parent initial QA; not independent case QA','original_typed_receipt_still_unknown':cid.endswith('AY0270'),'source_report_digest_fields_absent_or_null_preserved':{'typed_report_SHA_recorded':c['typed']['conversion_report_sha256_recorded'],'XMF_manifest_SHA_recorded':c['xmf']['manifest_sha256_recorded']},'outer_envelope_stale':c['render']['outer_envelope_is_stale_vs_loaded_wrapper'],'fresh_main_controller_observation':ob,'visual_credit':0})
O=H/'root_stage1_source166_remaining9_actualF3_full836_own_metadata_UID_N3_unknown154_audit_recovery_scope_discrepancies_readiness_1287';assert not list(H.glob('root*_1287'));O.mkdir();adopt=[]
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopt.append(ref(p))
put(O/'source166-byte-exact-readonly-validator.json',{'source_commit':commit,'source_files':adopt,'source_before_after_SHA':before,'validator_stdout':v.stdout,'validator_stderr':v.stderr,'main_own_metadata_XML_checks_independent_of_source_boolean_validator':True});put(O/'remaining9-F3-full836-own-metadata-readiness-adoption.json',{'schema':'ds02.main.f3.remaining9.metadata-readiness.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_commit':commit,'source_snapshot':ref(R/prefix/'metadata/f3-remaining9-pipeline-census.json'),'current_full336_index':ref(ip),'cases':rows,'native_completed0':9,'standard_typed_completed0':8,'independent_artifact_audit_completed0':1,'xmf_completed0':9,'visual_credit':0,'scientific_payload_IO':False,'source_plan_discrepancies_preserved':'P1200 AY0390/0430 source-plan differs native and source condition; AY0540/0570/0640 equals source-condition FILE but not actual native/converter roles. No field patched.'});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: adopt remaining9 F3 full836 readiness preserving recovered audit and scope discrepancies','--',*paths],cwd=R,check=True);print({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'live_controllers':sum(r['fresh_main_controller_observation']['live'] for r in rows),'case_credit':0})
