from pathlib import Path
import json,hashlib,subprocess,sys,datetime,runpy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
commit,prefix=sys.argv[1:];P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)>=9
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw)
bp=P/'metadata/ay0270-artifact-audit-xmf-binding.json';b=load(bp);qp0=P/'requests/ay0270_artifact_audit_full836_xmf.disabled-request.json';q0=load(qp0);worker=Path(b['adapter_source']['path']);api=runpy.run_path(str(worker));assert api['xmf_metadata_names'](b['expected_fields'])==('time','position',*b['expected_fields'])
assert b['source_only'] and b['disabled'] and not b['execution_allowed'] and b['cpu_threads']==2 and b['serial_cap']==1 and all(v is None for v in b['future_outputs'].values());assert 'typed_receipt' not in b
for p,digest in b['metadata_input_sha256'].items():assert sha(p)==digest,p
assert sha(worker)==b['adapter_source']['sha256'];assert b['upstream_export_xmf']['sha256']=='da50e26d5322b1b6f1539bca3109dfc115164427b37e1b2f86f56b153f56b0b0'
old=load(b['original_conversion_receipt']['path']);audit=load(b['artifact_audit_receipt']['path']);a=load(b['artifact_audit_report']['path']);native=load(b['native_receipt']['path']);t=load(b['conversion_report']['path']);h5=b['trajectory_h5']
assert old['status']=='running' and 'returncode' not in old and sha(b['original_conversion_receipt']['path'])=='efdc68f97eb55486dbef66fe25bf97bc9aabb4cb92dbe9cbeafb7465f065bcc7'
assert all((r['status'],r['returncode'])==('completed',0) for r in [audit,native]);assert a['artifact_integrity_status']=='completed' and a['worker_returncode']==0
assert native['request']['physical_case_id']==audit['request']['physical_case_id']==a['physical_identity']['physical_case_id']==b['physical_case_id'];assert native['request']['physical_condition_sha256']==audit['request']['physical_condition_sha256']==a['physical_identity']['canonical_native_condition_sha256']==b['canonical_source_physical_condition_sha256']==b['physical_condition_sha256']
assert a['field_audit']['frames']==t['frames']==b['expected_frames']==836 and a['field_audit']['particles']==t['particles']==b['expected_particles']==179208 and a['field_audit']['position_shape']==[836,179208,3] and a['approved_temporal_kernel']['checked_transitions']==835
assert a['field_audit']['uid_lifecycle_missing_count']==0 and a['field_audit']['uid_composite_unique'] and a['field_audit']['finite_position_velocity_density_pressure_mass'] and a['field_audit']['type_mk_verified_all_frames'] and not a['field_audit']['source_arrays_modified']
assert a['producer_attestation']['verified_trajectory_sha256']==t['output_sha256']==b['expected_h5_sha256']==audit['input_hashes_at_launch'][h5]==audit['input_hashes_after_run'][h5];assert t['hash_scopes']['physical_condition_sha256']==b['actual_converter_scope_sha256'] and t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0'
assert b['source_plan_scope_sha256'] is None and t['partvtk_validation']['all_passed'];assert a['source_conversion_lifecycle']['old_os_exit_zero_claim'] is False
O=H/'root_stage1_F3_AY0270_audit1166_qualified_original154_unknown_lifecycle_successor144_full836_original104_XMF_CPU2_1193';O.mkdir(exist_ok=False)
validator=P/'scripts/validate_fresh144.py';before={name:sha(W/name) for name in names};rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(validator)],capture_output=True,text=True);assert rv.returncode==0 and before=={name:sha(W/name) for name in names};put(O/'actual-original144-readonly-validator.json',{'validator':ref(validator),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr,'source_bytes_preserved':True})
pre=subprocess.run([str(L/'.venv/bin/python'),'-B',str(worker),'--binding',str(bp),'--metadata-preflight'],capture_output=True,text=True);assert pre.returncode==0 and json.loads(pre.stdout)['scientific_payload_opened'] is False
put(O/'actual144-metadata-only-adapter-preflight.json',{'worker':ref(worker),'binding':ref(bp),'returncode':pre.returncode,'stdout':pre.stdout,'stderr':pre.stderr,'scientific_payload_IO':False})
proof=O/'source144-independent-audit-qualified-XMF-adoption-role-review.json';put(proof,{'source_commit':commit,'exact_adopted_files':[ref(R/name) for name in names],'original_disabled_binding':ref(bp),'original_conversion_receipt':ref(b['original_conversion_receipt']['path']),'artifact_audit_receipt':ref(b['artifact_audit_receipt']['path']),'artifact_audit_report':ref(b['artifact_audit_report']['path']),'native_receipt':ref(b['native_receipt']['path']),'conversion_report':ref(b['conversion_report']['path']),'canonical_native_scope':b['physical_condition_sha256'],'actual_converter_legacy_scope':b['actual_converter_scope_sha256'],'source_plan_scope_absent_preserved':True,'artifact_audit_is_not_relabelled_as_original_converter_exit':True,'old_conversion_OS_exit_zero_not_claimed':True,'original104_scientific_fields_and_XMF_kernel_preserved':True,'position_manifest_metadata_contract_closed':True,'main_scientific_payload_IO':False,'case_credit':0})
controller=O/'batch-xmf-controller.py';controller.write_text('''from pathlib import Path
import json,runpy,hashlib
O=Path(__file__).parent;c=json.loads((O/'controller-config.json').read_text());assert hashlib.sha256(Path(c['fair_dispatch']['path']).read_bytes()).hexdigest()==c['fair_dispatch']['sha256'];dispatch=runpy.run_path(c['fair_dispatch']['path'])['dispatch'];results=[]
for qp in c['requests']:
 assert hashlib.sha256(Path(qp).read_bytes()).hexdigest()==c['request_sha256'][qp]
 q=json.loads(Path(qp).read_text());r=dispatch(qp,serial_conversion=True);ar=Path(q['attempt_root']);rp=ar/'execution-receipt.json';mp=ar/'xdmf/manifest.json';a=json.loads(rp.read_text()) if rp.exists() else {};m=json.loads(mp.read_text()) if mp.exists() else {}
 passed=r.returncode==0 and a.get('status')=='completed' and a.get('returncode')==0 and m.get('frames')==836 and m.get('particles')==179208 and m.get('fields',{}).get('position',{}).get('shape')==[836,179208,3] and m.get('physical_case_id')==q['physical_case_id'] and m.get('physical_condition_sha256')==q['physical_condition_sha256'] and m.get('actual_converter_scope_sha256')==q['actual_converter_scope_sha256'] and m.get('source_h5_sha256')==q['expected_h5_sha256_from_audit_attestation']
 z={'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':qp,'actual_receipt':str(rp),'actual_manifest':str(mp),'status':a.get('status'),'returncode':a.get('returncode'),'launcher_returncode':r.returncode,'actual_full836_audit_qualified_XMF_output0':passed,'stdout_tail':r.stdout[-1600:],'stderr_tail':r.stderr[-1600:],'case_credit':0};results.append(z);(O/'actual-progress.json').write_text(json.dumps({'results':results,'case_credit':0},indent=2)+'\\n');print(json.dumps(z),flush=True)
 if not passed:
  (O/'controller-result.json').write_text(json.dumps({'status':'stopped_for_primary_failure_classification','returncode':r.returncode or 1,'case_credit':0},indent=2)+'\\n');raise SystemExit(r.returncode or 1)
(O/'controller-result.json').write_text(json.dumps({'status':'completed','returncode':0,'actual_full836_XMF_completed0':len(results),'case_credit':0},indent=2)+'\\n')
''');compile(controller.read_text(),str(controller),'exec')
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_180.json');
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
base=load(root(1166)/'enabled-full836-readonly-artifact-audit-request.json');q=q0.copy();aid='root-stage1-f3-ay0270-audit1166-qualified-original154-unknown-full836-XMF-fresh144-root1193';ar=D/'families/F3'/b['case_id']/aid;assert not ar.exists()
q.update({k:base[k] for k in ['worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']});q.update(attempt_id=aid,attempt_root=str(ar),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,request_status='enabled_registered_artifact_audit_qualified_XMF',command=[str(L/'.venv/bin/python'),'-B',str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xdmf'],depends_on_attempts=[native['request']['attempt_id'],audit['request']['attempt_id']],original_unresolved_conversion_dependency_preserved_as_evidence_reference=ref(b['original_conversion_receipt']['path']),root_enablement={'actual_audit0_qualifies_existing_artifact':True,'old_conversion_OS_exit_zero_not_inferred':True,'registered_worker_only_scientific_IO':True,'original_disabled_source_request':ref(qp0)})
md=dict(b['metadata_input_sha256'])
for p in [bp,qp0,worker,controller,proof,root(928)/'fair_CPU_dispatch.py',root(64)/'resource-window-approval.json',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_180.json',O/'actual-original144-readonly-validator.json',O/'actual144-metadata-only-adapter-preflight.json',*list(R/name for name in names)]:md[str(p)]=sha(p)
md[h5]=b['expected_h5_sha256'];q['input_files']=sorted(md);q['input_sha256']=md;assert q['cpu_threads']==2 and all(Path(p).is_file() for p in q['input_files'])
qp=O/'enabled-full836-audit-qualified-XMF-request.json';put(qp,q);put(O/'controller-config.json',{'requests':[str(qp)],'request_sha256':{str(qp):sha(qp)},'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'effective_serial_conversion_cap':1,'case_credit':0});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register audit-qualified F3 full836 XMF preserving original unknown converter lifecycle','--',*paths],cwd=R,check=True);print({'root':1193,'source_files':len(names),'case_credit':0,'scientific_payload_IO_by_main':False,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
