from pathlib import Path
import json,runpy,hashlib
O=Path(__file__).parent;c=json.loads((O/'controller-config.json').read_text());assert hashlib.sha256(Path(c['fair_dispatch']['path']).read_bytes()).hexdigest()==c['fair_dispatch']['sha256'];dispatch=runpy.run_path(c['fair_dispatch']['path'])['dispatch'];results=[]
for qp in c['requests']:
 assert hashlib.sha256(Path(qp).read_bytes()).hexdigest()==c['request_sha256'][qp]
 q=json.loads(Path(qp).read_text());r=dispatch(qp,serial_conversion=True);rp=Path(q['attempt_root'])/'execution-receipt.json';a=json.loads(rp.read_text()) if rp.exists() else {};mp=Path(q['attempt_root'])/'full836-scientific-artifact-audit.json';m=json.loads(mp.read_text()) if mp.exists() else {};p=m.get('physical_identity',{});old=m.get('source_conversion_lifecycle',{})
 passed=r.returncode==0 and a.get('status')=='completed' and a.get('returncode')==0 and m.get('artifact_integrity_status')=='completed' and m.get('worker_returncode')==0 and m.get('case_id')==q['case_id'] and p.get('physical_case_id')==q['physical_case_id'] and p.get('canonical_native_condition_sha256')==q['physical_condition_sha256'] and m.get('producer_attestation',{}).get('verified_trajectory_sha256')==q['H5_expected_SHA_from_completed_producer_report_only'] and m.get('report_frame_ledger',{}).get('frames')==836 and m.get('approved_temporal_kernel',{}).get('checked_transitions')==835 and old.get('source_receipt_edited') is False and old.get('source_conversion_reclassified') is False and old.get('old_os_exit_zero_claim') is False
 z={'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':qp,'actual_receipt':str(rp),'actual_report':str(mp),'status':a.get('status'),'returncode':a.get('returncode'),'launcher_returncode':r.returncode,'actual_full836_readonly_artifact_audit_pass':passed,'stdout_tail':r.stdout[-1800:],'stderr_tail':r.stderr[-1800:],'case_credit':0};results.append(z);(O/'actual-progress.json').write_text(json.dumps({'results':results,'not_submitted':len(c['requests'])-len(results),'case_credit':0},indent=2)+'\n');print(json.dumps(z),flush=True)
 if not passed:
  (O/'controller-result.json').write_text(json.dumps({'status':'stopped_for_primary_failure_classification','returncode':r.returncode or 1,'case_credit':0},indent=2)+'\n');raise SystemExit(r.returncode or 1)
(O/'controller-result.json').write_text(json.dumps({'status':'completed','returncode':0,'actual_completed_full836_artifact_audits':len(results),'case_credit':0},indent=2)+'\n')
