from pathlib import Path
import json,hashlib,subprocess,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics')
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_141_f3_ay0270_full836_artifact_audit_v1';commit='2d0807a1aa84fb99fa376c2581025d5f452435df';P=W/prefix;O=H/'root_stage1_F3_AY0270_original154_unknown_OS_exit_readonly_full836_scientific_artifact_audit_original141_Root142928_CPU2_1166';O.mkdir(exist_ok=True)
assert not (O/'controller-config.json').exists()
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==9
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw)
q0=load(P/'requests/ay0270_full836_scientific_artifact_audit.disabled-request.json');b=load(P/'metadata/ay0270-audit-binding.json');old_ref=b['metadata_refs']['old_typed_receipt'];old=load(old_ref['path']);oldid=b['expected']['old_attempt_id'];h5=b['h5_producer_attestation']['path'];t=load(b['metadata_refs']['conversion_report']['path']);n=load(b['metadata_refs']['native_receipt']['path']);physical=b['physical_identity'];cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_177.json';cp=load(cp_path)
assert sha(old_ref['path'])==old_ref['sha256'] and old['status']=='running' and 'returncode' not in old
assert t['conversion_status']=='completed' and t['frames']==836 and t['particles']==179208 and t['output_sha256']==b['h5_producer_attestation']['producer_reported_sha256'] and Path(h5).is_file()
assert n['status']=='completed' and n['returncode']==0 and n['request']['case_id']==b['expected']['case_id'] and n['request']['physical_case_id']==physical['physical_case_id'] and n['request']['physical_condition_sha256']==physical['canonical_scope_sha256']
assert n['request']['expected_saved_frames']==836 and old['request']['native_full836_binding']['expected_saved_frames']==836
assert 'expected_saved_frames' not in old['request'] and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames'])
assert all(f['missing_particles']==0 and f['active_particles']==179208 for f in t['lifecycle']['frame_summary']) and len(t['lifecycle']['frame_summary'])==836
for p,digest in q0['input_sha256'].items():assert sha(p)==digest,p
assert h5 not in q0['input_sha256'] and b['source_only'] and not b['execution_allowed'] and not b['launch_allowed']
accepted=[load(p) for p in cp['accepted_decisions']];assert physical['physical_case_id'] not in {a.get('physical_case_id',a['case_id']) for a in accepted} and physical['canonical_scope_sha256'] not in {a['physical_condition_sha256'] for a in accepted}
def probe():
 raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);matches=[a for a in ledger['reservations'] if oldid in a.get('id','')];handles=[]
 for pid in [2367173,2367325]:
  p=Path(f'/proc/{pid}/stat');exists=p.exists();handles.append({'historical_pid':pid,'currently_present':exists,'historical_start_ticks':None,'not_fabricated':True});assert not exists
 assert not matches
 return {'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'historical_processes':handles,'matching_current_reservations':matches,'resource_ledger_sha256_observed':hashlib.sha256(raw).hexdigest(),'original_receipt_hash_unchanged':sha(old_ref['path'])==old_ref['sha256']}
probes=[probe()];before={name:sha(W/name) for name in names};rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(P/'scripts/validate_fresh141.py')],capture_output=True,text=True);put(O/'actual-original141-readonly-validator.json',{'validator':ref(P/'scripts/validate_fresh141.py'),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr});assert rv.returncode==0 and before=={name:sha(W/name) for name in names};probes.append(probe());put(O/'current-double-probe-original-receipt-preserved.json',{'probes':probes,'old_receipt':old_ref,'old_status':'running','returncode_field_absent':True,'old_tool_status':143,'source_unchanged':True})
proof=O/'source141-independent-adoption-and-registered-worker-hash-provenance.json';put(proof,{'source_commit':commit,'adopted_files':[ref(R/name) for name in names],'source_validator':ref(O/'actual-original141-readonly-validator.json'),'current_double_probe':ref(O/'current-double-probe-original-receipt-preserved.json'),'current_checkpoint':ref(cp_path),'full836_metadata_closure':True,'physical_identity':physical,'original_receipt_returncode_field_absent_preserved':True,'old_OS_exit_zero_not_claimed':True,'main_scientific_payload_IO':False,'source_prose_preserved':'Root reads and streams H5 before enabled request','effective_authoritative_interpretation':'Main uses the immutable completed producer report SHA as the expected input SHA. Original registered Root142 strict dispatch and runtime verify the actual H5 hash; the original141 registered scientific worker streams H5 and verifies all836 frames. Main never opens/hashes scientific payloads.','H5_expected_hash_provenance':{'conversion_report':b['metadata_refs']['conversion_report'],'producer_attested_SHA':t['output_sha256'],'observed_by_main':False,'future_worker_observation':None},'case_credit':0,'Q_N':0,'Q_E':0})
controller=O/'batch-audit-controller.py';controller.write_text('''from pathlib import Path
import json,runpy,hashlib
O=Path(__file__).parent;c=json.loads((O/'controller-config.json').read_text());assert hashlib.sha256(Path(c['fair_dispatch']['path']).read_bytes()).hexdigest()==c['fair_dispatch']['sha256'];dispatch=runpy.run_path(c['fair_dispatch']['path'])['dispatch'];results=[]
for qp in c['requests']:
 assert hashlib.sha256(Path(qp).read_bytes()).hexdigest()==c['request_sha256'][qp]
 q=json.loads(Path(qp).read_text());r=dispatch(qp,serial_conversion=True);rp=Path(q['attempt_root'])/'execution-receipt.json';a=json.loads(rp.read_text()) if rp.exists() else {};mp=Path(q['attempt_root'])/'full836-scientific-artifact-audit.json';m=json.loads(mp.read_text()) if mp.exists() else {};p=m.get('physical_identity',{});old=m.get('source_conversion_lifecycle',{})
 passed=r.returncode==0 and a.get('status')=='completed' and a.get('returncode')==0 and m.get('artifact_integrity_status')=='completed' and m.get('worker_returncode')==0 and m.get('case_id')==q['case_id'] and p.get('physical_case_id')==q['physical_case_id'] and p.get('canonical_native_condition_sha256')==q['physical_condition_sha256'] and m.get('producer_attestation',{}).get('verified_trajectory_sha256')==q['H5_expected_SHA_from_completed_producer_report_only'] and m.get('report_frame_ledger',{}).get('frames')==836 and m.get('approved_temporal_kernel',{}).get('checked_transitions')==835 and old.get('source_receipt_edited') is False and old.get('source_conversion_reclassified') is False and old.get('old_os_exit_zero_claim') is False
 z={'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':qp,'actual_receipt':str(rp),'actual_report':str(mp),'status':a.get('status'),'returncode':a.get('returncode'),'launcher_returncode':r.returncode,'actual_full836_readonly_artifact_audit_pass':passed,'stdout_tail':r.stdout[-1800:],'stderr_tail':r.stderr[-1800:],'case_credit':0};results.append(z);(O/'actual-progress.json').write_text(json.dumps({'results':results,'not_submitted':len(c['requests'])-len(results),'case_credit':0},indent=2)+'\\n');print(json.dumps(z),flush=True)
 if not passed:
  (O/'controller-result.json').write_text(json.dumps({'status':'stopped_for_primary_failure_classification','returncode':r.returncode or 1,'case_credit':0},indent=2)+'\\n');raise SystemExit(r.returncode or 1)
(O/'controller-result.json').write_text(json.dumps({'status':'completed','returncode':0,'actual_completed_full836_artifact_audits':len(results),'case_credit':0},indent=2)+'\\n')
''');compile(controller.read_text(),str(controller),'exec')
base=load(next((next(H.glob('root*_1144'))/'requests').glob('*.json')));q=q0.copy();aid='root-stage1-f3-ay0270-old154-artifact-readonly-full836-qualified-recovery-root1166';ar=D/'families/F3'/q['case_id']/aid;assert not ar.exists()
q.update({k:base[k] for k in ['worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256']});q.update(attempt_id=aid,attempt_root=str(ar),physical_case_id=physical['physical_case_id'],physical_condition_sha256=physical['canonical_scope_sha256'],canonical_source_physical_condition_sha256=physical['canonical_scope_sha256'],disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,request_status='enabled_registered_readonly_artifact_audit',depends_on_attempts=[n['request']['attempt_id']],H5_expected_SHA_from_completed_producer_report_only=t['output_sha256'],source_scientific_payload_IO_by_main=False,old_OS_exit_zero_claim=False)
fair=H/'root_stage1_fair_CPU_admission_no_capacity_wait_holds_shared_lock_928/fair_CPU_dispatch.py';approval=H/'root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json';assert sha(fair)=='e2796fb88cc989278bcc4d194493f11e5ded7e6d2fb79ef37349d7ae7d8d679f' and sha(approval)=='2a35e26e36920d8ca40001fd7f28416f27bcf371b8b882eca37868f4a15152b8'
q['root_enablement']={'source_original_requirement_preserved_in_disabled_request':ref(P/'requests/ay0270_full836_scientific_artifact_audit.disabled-request.json'),'registered_worker_only_scientific_IO':True,'main_expected_hash_from_producer_report':True,'strict_dispatch_actual_hash_gate_unmodified':True,'worker_actual_hash_and_full836_checks_required':True}
for p in [fair,approval,controller,proof,cp_path,O/'current-double-probe-original-receipt-preserved.json',*list(R/prefix/p for p in [])]:q['input_sha256'][str(p)]=sha(p)
for name in names:q['input_sha256'][str(R/name)]=sha(R/name)
q['input_sha256'][h5]=t['output_sha256'];q['input_files']=sorted(q['input_sha256']);assert all(Path(p).is_file() for p in q['input_files']);assert q['cpu_threads']==2 and q['max_wall_seconds']==3600 and q['estimated_storage_bytes']==128*1024**2 and b['future_output_contract']['observed_trajectory_h5_sha256'] is None
qp=O/'enabled-full836-readonly-artifact-audit-request.json';put(qp,q);put(O/'controller-config.json',{'requests':[str(qp)],'request_sha256':{str(qp):sha(qp)},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register original141 F3 full836 read-only artifact audit with immutable old lifecycle','--',*paths],cwd=R,check=True);print({'root':1166,'request':str(qp),'source_files':len(names),'H5_hash_provenance':'producer attested only; registered runner and worker will verify','main_payload_IO':False,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
