from pathlib import Path
import json,hashlib,copy,datetime,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_274.json';cp=load(cpfile);assert cp['checkpoint']==274 and cp['stage1_visual_accepted_complete_independent_cases']==309
F=root(1143);pre=F/'actual1117-full401-XMF-and-actual-typed-producer-typed-independent-review.json';j=load(pre)
for e in j.values():
 if isinstance(e,dict) and 'path' in e and 'sha256' in e:check(e)
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);n=load(j['actual_native_receipt']['path']);nq=n['request'];w=load(F/'enabled-render-wrapper.json');assert t['source_provenance']['solver_receipt']==j['actual_native_receipt'];canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert canonical=='7d7c2dc27d0a3c8eaa297a3c48dc4cec27bf075003e2933591a537c755f69e23' and legacy==x['physical_condition_sha256']=='a5892c54ca3899cc592df4ea831290e1baef0ffbee453ea6e1700a41e39e6148' and canonical!=legacy
assert n['status']=='completed' and n['returncode']==0 and nq['case_id']==w['case_id'] and nq['physical_case_id']==x['physical_case_id']==w['physical_case_id']=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX063_RY014_FILL080_ROT090'
mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};assert mask['native']['source_plan_condition_sha256']=={'present':False,'value':None} and mask['native']['source_plan_physical_condition_sha256']=={'present':True,'value':canonical} and all(v=={'present':False,'value':None} for v in mask['XMF'].values())
qa={}
for k in ['initial_qa_receipt','initial_qa_report']:
 e=ref(nq[k]);assert n['input_hashes_at_launch'][e['path']]==n['input_hashes_after_run'][e['path']]==e['sha256'];qa[k]=e
qr=load(qa['initial_qa_receipt']['path']);qq=load(qa['initial_qa_report']['path']);assert qr['status']=='completed' and qr['returncode']==0 and qr['request']['case_id']==w['case_id'] and qq['status']=='pass' and qq['case_id']==w['case_id']
fs=t['lifecycle']['frame_summary'];assert len(fs)==t['frames']==x['frames']==w['expected_frames']==401 and t['particles']==x['particles']==w['expected_particles']==418104 and w['expected_contact_sheets']==17
om={'final_missing_particles':fs[-1]['missing_particles'],'max_missing_per_frame':max(f['missing_particles'] for f in fs),'first_missing_frame':next(f['frame'] for f in fs if f['missing_particles']),'cumulative_particle_frame_omissions':sum(f['missing_particles'] for f in fs),'partial_final_Idp_sample':fs[-1]['missing_id_first'],'sample_is_partial_not_all15':True,'final_missing_Idp_digest':fs[-1]['missing_ids_sha256'],'location_state_cause_unknown':True}
assert (om['final_missing_particles'],om['max_missing_per_frame'],om['first_missing_frame'],om['cumulative_particle_frame_omissions'])==(15,15,158,2278) and om['partial_final_Idp_sample']==[397179,397193,397195,403821,403829,403865,404026,404195] and om['final_missing_Idp_digest']=='ad9911b016add231c106282df411bfe7d038bb26e986c4dbd150c276e3ea92de'
assert all(f['missing_type_counts']=={'0':0,'1':0,'2':0,'3':f['missing_particles']} and f['type_counts']=={'0':372840,'1':24150,'2':0,'3':21114-f['missing_particles']} for f in fs)
live=[]
for original,pid,start in [(1188,613708,'213820080'),(1143,621866,'213876084')]:
 P=Path(f'/proc/{pid}');obs=None
 if P.exists():
  st=(P/'stat').read_text().rsplit(')',1)[1].split();assert st[19]==start;cmd=(P/'cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);obs={'pid':pid,'startticks':start,'state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 live.append({'original':original,'same_actual_process':obs,'actual_controller_terminal':ref(root(original)/'controller-result.json') if (root(original)/'controller-result.json').exists() else None,'no_restart':True,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
for key,p in [('runtime_v2_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
O=H/'root_stage1_nextF2_original1143_RX063ROT090_same_live_fifteen_fluid_omissions_actual_native_XMF_plan_absence_genuine_initialQA_durable401QI_1365';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_275.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1143_terminal_full401_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F2-original1143-full401-own-QI1366.py').read_bytes());pp=O/'next-original1143-actual401-native-typed-XMF-genuineQA-and-fifteen-omission-durable-QI-readiness.json';put(pp,{'at_utc':now.isoformat(),'case_id':w['case_id'],'physical_case_id':w['physical_case_id'],'actual_previsual_scientific_dependency_review':ref(pre),'actual_native_receipt':j['actual_native_receipt'],'actual_typed_report':j['actual_typed_report'],'actual_typed_receipt':j['actual_typed_receipt'],'actual_XMF_manifest':j['actual_XMF_manifest'],'actual_XMF_XML':j['actual_XMF_XML'],'actual_XMF_receipt':j['actual_XMF_receipt'],'native_canonical_condition_sha256':canonical,'typed_XMF_legacy_condition_sha256':legacy,'actual_native_XMF_plan_field_namespaces':mask,'genuine_initial_QA_metadata':qa,'genuine_initial_QA_actual_completed0_and_report_pass':True,'metadataQI_proof_is_not_runner_receipt':True,'actual_particle_axis':418104,'actual_initial_fluid':21114,'actual_terminal_fluid':21099,'actual401_metadata_fluid_omissions':om,'actual_time_window_s':[0.0,4.000030243152287],'same_live_originals':live,'durable_original1143_only_full401_own_QI_entrypoint':ref(entry),'future_QI1366_unexecuted_and_proof_SHA_unknown':True,'command':['python3','-B',str(entry),'1143','1366'],'science_payload_IO':False,'new_jobs':0,'case_credit':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=275,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: next originalF2 1143 actual401/418104 metadata contract pinned with canonical-native versus legacytyped/XMF, exact bothXMF plan absences, nativecondition absent/nativephysicalplan presentcanonical, genuine initialQA0/reportpass, actual15 fluid omissions/cumulative2278/first158 preserved. Durable future own401QI1366 prepared but not executed before actual0/pub; original1143 and1188 handles confirmed live.',authorized_work_state='Active309/336 pending27. Source177 F3original987 andsource211 F5original1164 personally reviewing fullpublished products after actualownQI1355/1359. Source192 F5original1188 waiting ownQI1363. Next F2original1143 durable ownQI1366 prepared, personal17contacts9keys after actual0/pub/QI via next available child. Source176 referencebuilder integrated with explicit main current authority/status proof; final F3 delivery only after real48 and independent primary integrity audit.')
new['actual_progress']['next_originalF2_1143_durable_own401_QI']=ref(pp);new['next_executable_tasks']=['Adopt source177/211 original987/1164 personalreviews after exact finalcommit/read-only validation/ownQI checks; preserve canonical versus SourceDef and plan absences per actualcase.','Wait same original1188 PID613708/start213820080 actualcompleted0/pub; run existing durable ownQI1363 once then supply pathSHA tosource192.','Wait same original1143 PID621866/start213876084 actualcompleted0/pub; run new durable ownQI1366 once then delegate personal17contacts9keys. Preserve fifteenfluid omissions/partial8-ID sample/unknown cause and genuine initialQA roles; no synthetic completion of mainQIproof.','Continue remaining27 originalcases and close final F2/F3/F5 directories only after real48 accepted; source176 utility does not replace independent final full primary/frame/UID/time/namespace/runtimeunknown review.','Keep Home500GiB floor and cumulative534.4086GiB failedoutputcleanup evidence; no repeated same-failure deletion or scientific reruns.'];put(np,new)
ip=root(1364)/'full336-current309-actual-final48-delivery-progress-index.json';idx=load(ip);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,next_originalF2_1143_durable_own401_QI=ref(pp));assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==309;put(O/'full336-current309-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare next F2 original1143 full401 integrity preserving fifteen omissions','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':275,'accepted':309,'live':live,'durable_entry':ref(entry),'future_QI_unexecuted':1366,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
