from pathlib import Path
import json,hashlib,datetime,subprocess,copy,os,collections,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='fa361de59f9d67dc9a460baa2b75bbbe392d5612';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob('root_followup_181_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();expected={'README.md','build_fresh181.py','validate_fresh181.py','package-manifest.json','metadata/actual1194-personal-visual-decision.json','metadata/png-evidence/actual1194.json'};assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
man=load(P/'package-manifest.json');assert {e['path'] for e in man['files']}==expected-{'package-manifest.json'} and man['package_manifest_excluded_from_own_hash']
for e in man['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh181.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1387)/'actual1194-full836-recovery-aware-QI-nativecanonical-typedlegacy-original154-unknown-previsual-proof.json';qi=load(qip);assert sha(qip)=='d580c83cf9ab4ca5e2fd5f09ac3a9f73adfd90dab70115dad035cb1d7ecbde91'
s=load(P/'metadata/actual1194-personal-visual-decision.json');png=load(P/'metadata/png-evidence/actual1194.json');cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_request_condition_sha256'];legacy=qi['actual_converter_condition_sha256'];assert s['case_id']==png['case_id']==cid and s['physical_case_id']==png['physical_case_id']==pid and s['actual_case_family']=='F3' and canonical!=legacy;checked(s['provenance']['qi_proof']);assert s['provenance']['qi_proof']['path']==str(qip)
er=qi['actual_completed_metadata_evidence']
for k,e in er.items():
 checked(e)
 if k.endswith('_receipt') and k not in {'original_conversion_receipt','actual_render_publish_receipt'}:
  rr=load(e['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0
mapping=[(s['actual_chain']['native'],'actual_native_receipt'),(s['actual_chain']['typed']['conversion_report'],'actual_producer_conversion_report'),(s['actual_chain']['artifact_audit']['receipt'],'actual_artifact_audit_receipt'),(s['actual_chain']['artifact_audit']['report'],'actual_artifact_audit_report'),(s['actual_chain']['xmf']['receipt'],'actual_XMF_receipt'),(s['actual_chain']['xmf']['manifest'],'actual_XMF_manifest'),(s['actual_chain']['xmf']['xml'],'actual_XMF_XML'),(s['actual_chain']['render']['receipt'],'actual_render_receipt'),(s['actual_chain']['render']['report'],'actual_render_report'),(s['actual_chain']['render']['atomic_publish'],'actual_render_publish_receipt'),(s['original_conversion_unknown_lifecycle'],'original_conversion_receipt')]
ri=s['reused_initialization'];mapping.extend([(ri['parent_initial_qa_receipt'],'genuine_parent_initial_QA_receipt'),(ri['parent_initial_qa_report'],'genuine_parent_initial_QA_report'),(ri['reused_gencase_receipt'],'typed_source_gencase_receipt'),(ri['exact_initial_clone_preparation_receipt'],'actual_initial_clone_preparation_receipt'),(ri['source_generated_xml'],'typed_source_generated_xml'),(ri['source_owner_metadata'],'typed_source_owner_metadata'),(ri['source_preparation_report'],'actual_preparation_report')])
for e,k in mapping:checked(e);assert e['path']==er[k]['path'] and e['sha256']==er[k]['sha256']
old=load(er['original_conversion_receipt']['path']);assert old['status']=='running' and 'returncode' not in old and qi['original_OS_exit_zero_not_claimed'] and s['original_conversion_unknown_lifecycle']['returncode_field_present'] is False and s['original_conversion_unknown_lifecycle']['reclassified_as_completed'] is False
assert qi['independent_artifact_audit1166_actual_completed0'] and qi['recovery_aware_XMF1193_actual_completed0'] and qi['genuine_parent_initial_QA_and_exact_initial_clone_verified'] and qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIDs_active_each_frame']
assert s['actual_dimensions']=={'fixed':111708,'floating':0,'fluid':67500,'frames':836,'moving':0,'particles':179208,'time_window_s':qi['actual_time_window_s'],'uid_lifecycle':'all native UIDs active each frame per Root1387 QI','vector_shape':'N x 3'}
n=load(er['actual_native_receipt']['path'])['request'];x=load(er['actual_XMF_manifest']['path']);masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces'] and all(v=={'present':False,'value':None} for m in masks.values() for v in m.values());roles=s['physical_condition_roles'];assert roles['native_canonical_condition_sha256']==roles['xmf_physical_condition_sha256']==canonical and roles['typed_legacy_converter_scope_sha256']==roles['xmf_actual_converter_scope_sha256']==legacy
for ns,prefixns in [('native','native'),('XMF','xmf')]:
 for k,mask in masks[ns].items():assert roles['native_and_xmf_plan_fields'][f'{prefixns}_{k}']==mask
visual=s['visual_review'];assert visual['status']=='visual-approved-by-delegated-agent' and visual['screen']=='pass_first_stage' and visual['case_credit']==0 and not visual['q_n_granted'] and not visual['q_e_granted'];assert s['configured_model']=='gpt-5.6-luna/max' and not s['model_substitution'] and not s['recursive_delegation'];reviewed=s['review_completed_at_utc']
contacts=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'sheet_index':i,'viewed':e['personally_viewed_with_view_image']} for i,e in enumerate(s['visual_evidence']['contacts'])];keys=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'frame':int(Path(e['path']).stem.removeprefix('frame_')),'viewed':e['personally_viewed_with_view_image']} for e in s['visual_evidence']['keys']];assert len(contacts)==35 and len(keys)==9 and [e['frame'] for e in keys]==[0,104,208,312,417,521,626,730,835] and png['contacts']==s['visual_evidence']['contacts'] and png['keys']==s['visual_evidence']['keys']
pub=load(er['actual_render_publish_receipt']['path']);report=load(er['actual_render_report']['path']);receipt=load(er['actual_render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['actual_render_report']['path']);pubroot=Path(pub['published_output_root']);pubfiles={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==report['outputs']['contact_sheets']
for e in contacts+keys:checked(e);p=pubfiles[str(Path(e['path']).relative_to(pubroot))];assert e['sha256']==p['sha256'] and e['bytes']==p['bytes'] and e['viewed']
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(receipt['finished_at_utc'])<=datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=[+-]\d\d:\d\d|Z|$)',r'\1',reviewed))<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_295.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==318 and cp['accepted_per_family']['F3']==44 and pid not in {load(p)['physical_case_id'] for p in cp['accepted_decisions']};ip=root(1394)/'full336-current318-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);target=next(z for z in idx['cases'] if z['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source181_actualF3_AY0270_original1194_full836QI_personal44PNG_original154_runtimeunknown_audit1166_recoveryXMF1193_parentQA_visual_acceptance_1395';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_296.json';assert not O.exists() and not np.exists();O.mkdir()
for n0,b0 in blobs.items():p=R/n0;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b0)
ack=O/'source181-personal-viewing-versus-metadata-stat-flag-scope-clarification.json';put(ack,{'schema':'ds02.main.source181.PNG-access-flag-scope-clarification.v1','at_utc':now.isoformat(),'source_commit':commit,'source_immutable':True,'agent_followup_statement':'已核实：44张PNG均已亲自view_image查看，contacts000-034及keys0/104/208/312/417/521/626/730/835。PNG仅stat仅描述构建器与验证器不再读取或自行哈希PNG内容，不代表没有个人视觉。','ambiguous_source_fields':['content_read_or_hashed_by_reviewer:false','publisher_png_sha_source: reviewer only stat-checked PNGs'],'actual_personal_visual_review_did_read_published_derivatives':True,'metadata_builder_validator_only_stat_and_publisher_hash_copy':True,'PNG_content_not_read_or_hashed_is_not_a_literal_personal_viewer_IO_claim':True,'main_personally_viewed_PNGs':False,'main_scientific_payload_IO':False})
proof=O/'source181-byte-exact-readonly-main44publishedPNG-own836QI-original154unknown-true-recovery-parentQA-proof.json';put(proof,{'schema':'ds02.main.F3.source181.personal44PNG-adoption-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n0) for n0 in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'independent_ownQI':ref(qip),'all44_publishedPNG_hashes_match_actual_atomic_publish':True,'actual_personal_review_time_utc':reviewed,'review_after_completed_publication':True,'actual_native_XMF_plan_field_namespaces':masks,'original154_running_no_returncode_field_not_reclassified':True,'actual_audit1166_XMF1193_completed0_verified':True,'genuine_parentQA_and_exact_initial_clone_not_fabricated_percaseQA_verified':True,'actual_chain_refs_all_match_main_ownQI':True,'PNG_access_flag_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F3','source_personal_visual_review':ref(R/prefix/'metadata/actual1194-personal-visual-decision.json'),'independent_full836_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':836,'particle_count':179208,'actual_type_counts':{'fixed':111708,'moving':0,'floating':0,'fluid':67500,'total':179208},'actual_physical_window_s':qi['actual_time_window_s'],'all836_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':masks,'original_typed154_runtime':qi['original_typed154_runtime'],'actual_independent_audit1166_and_recoveryXMF1193_completed0':True,'old_original_OS_exit_zero_not_claimed':True,'genuine_parentQA_GenCase_exactclone_provenance':ri,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':35,'personal_reviewed_keyframes':9,'actual_personal_review_time_utc':reviewed,'contact_sheets':contacts,'keyframes':keys,'visual_observations':visual['observations'],'visual_limits':visual['physical_screen_limits'],'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'historical_outer_expected_fields':s['historical_outer_envelope'],'main_all44_PNG_hashes_match_actual_atomic_publish':True,'source_PNG_access_flag_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source181-actual1194-full836QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(proof),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F3']+=1
new.update(checkpoint=296,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=319,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source181 F3AY0270 original1194 own1387 personal35contacts9keys accepted once; source6 exact/readonly validator/all44pubPNG hash/actual154 running-noRC plus realartifact1166/XMF1193/parentQA-clone provenance checked. Main sidecar clarifies source ambiguous PNG stat flag versus actualview_image after direct agent confirmation.',authorized_work_state='Active319/336 pending17. F2=45 F3=45 F5=37. Nextoriginal1009/1158 same registeredlaunches continue; own1392 future unexecuted. Source196 F3 final gate repair active, source218 F5 final gate repair active replacing earlier planned182 utility; source195 F2 partial repair needs separate197 after196. Source217 visual pending1009 with no package yet.')
new['actual_progress']['source181_F3_actual1194_visual_acceptance']=ref(ap);new['source_agents']['f5_bed_recovery']='fresh218 F5 final gate repair active; fresh217 F2original1009 visual pending no package';new['source_agents']['production_recovery']='fresh181 F3original1194 accepted once; available for next actual personal review';new['next_executable_tasks']=[x for x in new['next_executable_tasks'] if not x.startswith('Adopt source181') and not x.startswith('Assign fresh182')];new['next_executable_tasks'].insert(0,'Complete/audit source218 F5 real final48 gates and source196 F3 gates, then separate197 F2 remaining gates; prepare actual F5original1158 own801QI and resume F2original1009 own1392 after real completed0/publication.');assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==319;put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=319,registered_pending_independent_physical_cases=17,new_case_credit=1);target.update(status='visual-approved-in-checkpoint296',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full836_QI=ref(qip));idx['actual_unaccepted_completed0_published_physical_cases']=[z for z in idx['actual_unaccepted_completed0_published_physical_cases'] if (z if isinstance(z,str) else z['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==319;put(O/'full336-current319-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept AY0270 personal review retaining original154 unknown and real recovery parent QA','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':296,'accepted':319,'F3':45,'pending':17,'decision':ref(dp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
