from pathlib import Path
import json,hashlib,subprocess,datetime,os,copy,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.py','.md','.png','.xml','.xmf','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_196_f5_m090_t095_actual1109_personal_visual_review_v1';commit='a0dbf793f48c24bfcb3ba2bee865248f4bba6f1f';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==9
P=W/prefix;before={n:sha(W/n) for n in names};vld=P/'scripts/validate_fresh196.py';val=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert val.returncode==0 and before=={n:sha(W/n) for n in names}
up=load(P/'metadata/upstream-evidence.json');z=load(P/'metadata/physical-stage-closure.json');visual=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');ar=load(P/'metadata/actual-render-metadata.json');qi_path=root(1245)/'actual1109-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qi_path);refs=qi['actual_completed_metadata_evidence']
assert qi['case_id']==z['case_id']==visual['case_id']==ar['case_id'] and qi['physical_case_id']==z['physical_case_id']==visual['physical_case_id']==ar['physical_case_id']
for e in refs.values():assert sha(e['path'])==e['sha256']
for k,e in up['upstream_chain'].items():
 assert sha(e['path'])==e['sha256'];alias={'render_execution_receipt':'render_receipt'}.get(k,k)
 if alias in refs:assert e['path']==refs[alias]['path'] and e['sha256']==refs[alias]['sha256']
for stage in ('gencase','initial_qa','native','typed','xmf','bed','render'):
 d=load(refs[stage+'_receipt']['path']);assert (d['status'],d['returncode'])==('completed',0) and d['request']['case_id']==z['case_id']
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
roles=up['scope_roles'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert canonical==roles['canonical_native_source_plan_sha256'] and legacy==roles['typed_legacy_h5_scope_sha256'] and qi['bed_declared_source_plan_field_sha256']==roles['source_definition_bed_declared_plan_sha256']==qi['actual_SourceDef']['sha256']
sourceplan=root(823)/'source-plan.json';native=load(refs['native_receipt']['path']);assert native['input_hashes_at_launch'][str(sourceplan)]==native['input_hashes_after_run'][str(sourceplan)]==sha(sourceplan)==roles['source_plan_file_sha256'];assert 'source_plan_file_path' not in roles or roles['source_plan_file_path']==str(sourceplan)
v=visual['decision'];assert v['standalone_first_stage_visual_approved'] and not v['needs_root_image_intervention'] and not v['numerical_precision_accepted'] and not v['q_n_granted'] and v['weak_wave_only'] and not v['large_inundation_or_runup_claim'] and not v['strict_container_guarantee']
rr=load(refs['render_report']['path']);pub=load(refs['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==refs['render_report']['sha256'];assert rr['frames']==rr['source_frames']==801 and rr['all_frames_rendered'] and rr['nonfinite_active_states']==0
assert len(png['contact_sheets'])==34 and len(png['keyframes'])==9 and [e['frame'] for e in png['keyframes']]==[0,100,200,300,400,500,600,700,800];assert [e['path'] for e in png['contact_sheets']]==rr['outputs']['contact_sheets'];pr={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in png['contact_sheets']+png['keyframes']:assert e['reviewed'] and sha(e['path'])==e['producer_attested_sha256']==pr[e['relative_path']]['sha256'] and Path(e['path']).stat().st_size==e['bytes']==pr[e['relative_path']]['bytes']
assert sorted(p.name for p in Path(rr['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(801)]
cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_210.json';cp=load(cpp);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==276;pid=z['physical_case_id'];old=[load(p) for p in cp['accepted_decisions']];assert pid not in {x.get('physical_case_id',x['case_id']) for x in old}
idxp=root(1244)/'full336-current276-role-aware-registration-progress-index.json';idx=load(idxp);target=[x for x in idx['cases'] if x['physical_case_id']==pid];assert len(target)==1 and not target[0].get('accepted_decision') and target[0]['native_request_scope']['sha256']==canonical
O=H/'root_stage1_source196_F5_M090T095_actual1109_personal34contacts_ninekeys_801QI_visual_acceptance_1246';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_211.json').exists();adopted=[]
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'actual-source196-readonly-validator.json';put(vp,{'validator':ref(vld),'returncode':val.returncode,'stdout':val.stdout,'stderr':val.stderr,'original_source_bytes_unchanged':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json')
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':z['case_id'],'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_plan_condition_sha256':qi['actual_native_source_plan_condition_sha256'],'bed_declared_source_plan_field_sha256':qi['bed_declared_source_plan_field_sha256'],'source_definition_sha256':qi['actual_SourceDef']['sha256'],'source_plan_file_sha256':sha(sourceplan),'source_review_commit':commit,'source_visual_review':ref(P/'metadata/visual-decision.json'),'source_review_closure':ref(P/'metadata/physical-stage-closure.json'),'actual_completed_metadata_evidence':refs,'independent_full801_QI_previsual_proof':ref(qi_path),'full_native_frames':801,'particles':194427,'actual_physical_window_s':qi['actual_time_window_s'],'all801_geometry_velocity_N3_times_UID_finite_verified':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':visual['visual_observations'],'actual_contact_count_and_coverage_closure':{'count':34,'tile_batch':24,'total_frames':801,'all_frame_PNG_filenames_present':True,'all43_reviewed_derivative_hashes_match_actual_publish':True},'original_source196_scope_roles':roles,'all801_full_bed_UID_footprint_one_DP_two_DP_diagnostics_checked':True,'positive_depth_below_DP_not_proven_absent_by_zero_bin_counts':True,'large_runup_inundation_or_strict_container_guarantee':False,'initial_qa_numerical_precision_negative':qi['actual_initial_QA_precision_negative'],'historical_A_B_negative_evidence_preserved':z['historical_negative_evidence_preserved'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source196-actual1109-immutable801QI-and-personal-visual-adoption-proof.json';put(proof,{'source_commit':commit,'adopted_files':adopted,'source_validator':ref(vp),'original_QI_proof':ref(qi_path),'all_original_QI_stage_refs_byte_unchanged':True,'actual_personal_png_count':43,'actual_801_frame_filenames_present':True,'new_decision':ref(dp),'source_definition_and_native_condition_and_legacy_roles_separate':True,'actual_root823_source_plan_file':ref(sourceplan),'source196_actual_native_batch_plan_file_role_verified':True,'independent_case_increment':1,'main_scientific_payload_IO':False,'precision_status':'视觉检查通过、数值精度未验收'})
lb=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(lb);lf=O/'resource-ledger-frozen.json';lf.write_bytes(lb);s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize/2**30;counts=collections.Counter(x['kind'] for x in ld['attempts']);cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;assert free>=500 and cpu<=3840 and gpu<=512 and counts['qualification']<=1024 and counts['production']<=720
cp['accepted_per_family']['F5']+=1;cp.update(checkpoint=211,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),stage1_visual_accepted_complete_independent_cases=277,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(lb).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source196 actual1109 full801 QI and personal34contacts9keys accepted277/F5=15. Failed unused storage cleanup rechecked, cumulative534.4086GiB freed.',authorized_work_state='Active277/336. Original1100 completed0: fresh156 F3 personal review. Original1183 running: fresh197 F5 personal review after atomic publication. Fresh172 lastF6original951 sharedcapacity wait, no error or restart. Numerical precision not accepted.')
cp['actual_progress']['source196_F5_actual1109_visual_acceptance']=ref(proof);cp['source_agents'].update(f5_bed_recovery='fresh196 accepted277/F5=15; fresh197 original1183',production_recovery='fresh156 F3original1100 completed0 personal review',f6_endpoint_initial_qa='fresh172 original951 sharedcapacity wait audit complete');cp['next_executable_tasks']=['Adopt source172 immutable lastF6original951 queue mechanism audit; preserve originalhandle and capacity guards.', 'Adopt fresh156 F3original1100 full836 personal35contacts9keys after independent metadata QI closure.', 'Track original1183 F5M105T100 with fresh197; review only completed0 published derivatives.', 'Extend F5 actualfirst24 prefix15 from frozen8 with realaccepted order only, then final48.', 'Preserve Home500GiB floor and cumulative512GPUh/3840CPUcoreh/qual1024/prod720/Oct14deadline; remaining59 realvisualcases.'];assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==277;newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_211.json';put(newcp,cp)
target[0].update(status='visual-approved-in-checkpoint211',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='Own actual native condition retained; SourceDef/typedlegacy separate',precision_status='视觉检查通过、数值精度未验收');idx.update(schema='ds02.stage1.full336.role-aware-progress-index.v6',at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxp),accepted_independent_physical_cases=277,registered_pending_independent_physical_cases=59,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if x!=pid];idx['controller_observations_inherited_not_new_live_probe']=True;idx['actual1109_completion_observation_refs']={'actual1109':refs['render_receipt']};put(O/'full336-current277-role-aware-registration-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())

gp=root(1243)/'F5-actual-first24-growing-prefix14-frozen8-acceptance-order.json';g=load(gp)
assert g['actual_first24_realized_prefix_count']==14 and len(g['physical_case_ids_actual_delivery_order'])==14 and not g['actual_first24_delivered']
for e in g['actual_visual_decisions']:assert sha(e['path'])==e['sha256']
assert g['physical_case_ids_actual_delivery_order'][:8]==g['first8_physical_case_ids'] and pid not in g['physical_case_ids_actual_delivery_order']
g['physical_case_ids_actual_delivery_order'].append(pid);g['actual_visual_decisions'].append(ref(dp));g.update(at_utc=now,current_authoritative_checkpoint=ref(newcp),previous_realized_prefix_preserved=ref(gp),actual_first24_realized_prefix_count=15,actual_first24_delivered=False)
assert len(set(g['physical_case_ids_actual_delivery_order']))==15
accepted_f5={d.get('physical_case_id',d['case_id']) for d in [load(p) for p in cp['accepted_decisions']] if d['family_id']=='F5'}
assert set(g['physical_case_ids_actual_delivery_order'])==accepted_f5 and set(g['first8_physical_case_ids'])<=accepted_f5
final_f5={r['physical_case_id'] for r in idx['cases'] if r['family_id']=='F5'};assert len(final_f5)==48 and accepted_f5<=final_f5
gout=O/'F5-actual-first24-growing-prefix15-frozen8-acceptance-order.json';put(gout,g)
put(O/'source196-scope-field-absence-and-actual-native-plan-binding.json',{'original_source_bytes_unchanged':True,'source196_source_plan_file_path_field_present':'source_plan_file_path' in roles,'actual_native_launch_and_after_source_plan':ref(sourceplan),'role':'Native850 actual producer input file; canonical native and bed SourceDef and typed legacy roles remain distinct','native_receipt':refs['native_receipt'],'canonical_condition_sha256':canonical,'SourceDef_bed_declared_sha256':qi['bed_declared_source_plan_field_sha256'],'typed_legacy_scope_sha256':legacy})
cleanup=load(root(1235)/'cleanup-actual-results-and-retention-proof.json')
for row in cleanup['actual_cleanup_receipts']:
 assert sha(row['actual_receipt'])==row['receipt_sha256'] and sha(row['result'])==row['result_sha256']
 assert load(row['actual_receipt'])['status']=='completed' and load(row['actual_receipt'])['returncode']==0
for f in cleanup['preserved_first_last_CSV_samples']:assert Path(f).is_file()
put(O/'user-cleanup-original-evidence-recheck-and-current-storage.json',{'at_utc':now,'original_cleanup_adoption_proof':ref(root(1235)/'cleanup-actual-results-and-retention-proof.json'),'four_original_completed0_cleanup_receipts_and_result_hashes_still_match':True,'retained_first_last_CSV_filenames_still_exist':True,'cumulative_freed_allocated_GiB':cleanup['cumulative_deleted_allocated_GiB'],'Home_available_GiB':free,'Home_floor_GiB':500,'extra_files_deleted_in_this_verification':0,'scientific_payload_IO':False})
cp['actual_progress']['F5_actual_first24_realized_prefix15']=ref(gout);put(newcp,cp)
idx['source_authoritative_checkpoint']=ref(newcp);put(O/'full336-current277-role-aware-registration-progress-index.json',idx)

paths=[str(Path(x['path']).relative_to(R)) for x in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 M090 T095 complete801 delegated visual review with immutable QI','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':277,'F5':15,'remaining':59,'checkpoint':211,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'Home_free_GiB':free}))
