from pathlib import Path
import json,hashlib,datetime,copy,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_321.json';cp=load(cpfile);ip=root(1433)/'full336-current330-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==330
completed=[]
for n,original,filename,dg in [(1430,1063,'actual1063-full401-own-QI-UID-N3-native-typed-role-two-fluid-omissions-previsual-proof.json','d57f12d02a35ec5bf0a67f81d2319057ea4d3957392f408fa3949a4836eefc00'),(1434,1189,'actual1189-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json','1842851ab604f787bfba37e8b55e68463a8e1a81d94779c05412f0da1cca2652')]:
 p=root(n)/filename;assert sha(p)==dg;q=load(p);er=q['actual_completed_metadata_evidence'];rr=load(er['render_receipt']['path']);pub=load(er['render_publish_receipt']['path']);crp=root(original)/'controller-result.json';cr=load(crp);assert (rr['status'],rr['returncode'])==('completed',0) and (cr['status'],cr['returncode'])==('completed',0) and pub['status']=='published_after_atomic_rename'
 for e in er.values():check(e)
 row=next(z for z in idx['cases'] if z['physical_case_id']==q['physical_case_id']);assert not row.get('accepted_decision');row.update(actual_completed0_published_QI=ref(p),personal_visual_status='pending delegated personal review after own full QI')
 completed.append({'original':original,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'own_completed_QI':ref(p),'actual_completed_controller_result':ref(crp),'actual_render_receipt':er['render_receipt'],'actual_atomic_publish_receipt':er['render_publish_receipt'],'case_credit':0,'visual_accepted':False})
live=[];mutable=[]
for n,pid,start in [(1184,784356,'215400672'),(1175,785291,'215410128')]:
 f=root(n);w=load(f/'enabled-render-wrapper.json');rp=D/'families'/w['current_attempt_id']/'execution-receipt.json';rb=rp.read_bytes();r=json.loads(rb);assert r['status']=='running' and r['pid']==pid;pr=Path('/proc')/str(pid);st=(pr/'stat').read_text().split(') ',1)[1].split();assert st[19]==start and str(f/'enabled-render-wrapper.json').encode() in (pr/'cmdline').read_bytes().split(b'\0')
 live.append({'original':n,'pid':pid,'start_ticks':start,'state':st[0],'actual_registered_wrapper_cmdline_bound':True,'mutable_original_receipt_path':str(rp),'observed_receipt_SHA':hashlib.sha256(rb).hexdigest(),'no_restart':True});mutable.append((n,rb))
qi1194p=root(1387)/'actual1194-full836-recovery-aware-QI-nativecanonical-typedlegacy-original154-unknown-previsual-proof.json';qi1194=load(qi1194p);er=qi1194['actual_completed_metadata_evidence'];orig=er['original_conversion_receipt'];nr=er['typed_source_solver_receipt'];audit=er['actual_artifact_audit_receipt'];xr=er['actual_XMF_receipt']
for e in [orig,nr,audit,xr,er['actual_artifact_audit_report'],er['actual_producer_conversion_report']]:check(e)
oc=load(orig['path']);nc=load(nr['path']);ac=load(audit['path']);xc=load(xr['path']);assert oc['status']=='running' and 'returncode' not in oc and all((j['status'],j['returncode'])==('completed',0) for j in [nc,ac,xc])
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(e['kind'] for e in ld['attempts']);gpu=sum(e.get('gpu_seconds',0) for e in ld['charges'])/3600;cpu=sum(e.get('cpu_core_seconds',0) for e in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current330_original1063_1189_completedQI_lastF2_lastF5_personal_pending_F3_original154_unknown_typed_role_sidecar_live1184_1175_1435';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_322.json';assert not O.exists() and not np.exists();O.mkdir();side=O/'F3-current47-original154-unknown-typed-runtime-and-native-source-role-clarification.json'
put(side,{'schema':'ds02.main.F3.current47.original154.recovery-role-sidecar.v1','at_utc':now.isoformat(),'immutable_current47_primary_product':cp['actual_progress']['F3_current47_actual_primary_delivery'],'actual_own_recovery_QI1387':ref(qi1194p),'physical_case_id':qi1194['physical_case_id'],'original_typed154_receipt':orig,'original_typed154_runtime':qi1194['original_typed154_runtime'],'actual_native_receipt':nr,'typed_source_solver_receipt_has_native_solver_role_not_original_typed_role':True,'actual_readonly_full836_artifact_audit_receipt':audit,'actual_readonly_full836_artifact_audit_report':er['actual_artifact_audit_report'],'actual_typed_producer_conversion_report':er['actual_producer_conversion_report'],'actual_recovery_aware_XMF1193_receipt':xr,'typed_completion_via_independent_artifact_audit_and_recovery_aware_XMF':True,'original_typed_process_returncode_zero_not_claimed':True,'source190_generic_original_conversion_receipts_alias_includes_native_solver_reference_main_roles_are_separated_here':True,'primary_product_field_actual_typed_runtime_boundary_null_not_a_zero_claim_fullQI_remains_authority':True,'source190_and_consumed_primary_product_bytes_unchanged':True,'scientific_payload_IO':False,'new_case_credit':0,'Q_N':0,'Q_E':0})
for n,rb in mutable:
 p=O/f'original{n}-running-render-receipt-immutable-observation-snapshot.json';p.write_bytes(rb);next(z for z in live if z['original']==n)['immutable_observation_snapshot']=ref(p)
proof=O/'current330-two-completed-ownQI-two-live-render-workers-and-original154-role-proof.json';put(proof,{'schema':'ds02.main.current330.actual-runtime-and-typed-role-frontier.v1','at_utc':now.isoformat(),'completed0_published_fullQI_pending_personal_review':completed,'newly_admitted_original_live_workers':live,'F3_original154_recovery_role_clarification':ref(side),'remaining_registered_visual_pending_cases':6,'no_new_simulations_or_restarts':True,'scientific_payload_IO':False,'PNG_payload_IO':False,'case_credit':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=322,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: three actual cases accepted327→330 and F3 actual47 primary delivered; lastF2 original1063 and F5 original1189 naturally completed0/published and fullQI1430/1434 passed, personal225/192 scheduled after immutable224/191. Current1184/1175 workers verified live; original154 typedunknown versus true native solver role clarified without editing consumed bytes.',authorized_work_state='Active330/336 remaining6. F2=47 F3=47 F5=44, four other families48. Two completed0/fullQI await personal reviews; twoF5 original1184/1175 rendering, F3original1101/F5original1149 queued. Familyactual47/44 primary products in parallel; final336 product remains required.')
new['actual_progress']['current330_completed1063_1189_QI_and_live1184_1175']=ref(proof);new['actual_progress']['F3_current47_original154_typed_recovery_role_clarification']=ref(side)
new['source_agents'].update(production_recovery='fresh190 actualF3 primary47 accepted; fresh191 actual1189 metadata then fresh192 personal34+9 fullQI1434',f5_bed_recovery='fresh224 actualF2 primary47 then fresh225 lastF2 actual1063 personal17+9 fullQI1430',f6_endpoint_initial_qa='fresh202 actualF5 primary44 plus4pending product')
new['next_executable_tasks'].insert(0,'Integrate fresh224/202 actual primary products and personal225/192 after immutable packages finish; after original1184/1175 complete verify true native/XMF/SourceDef roles then full801QI and delegated personal review. LastF3original1101 keeps same original queue handle; futureown1427 remains unexecuted until actual0/pub.')
put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);idx['actual_unaccepted_completed0_published_physical_cases']=[e['physical_case_id'] for e in completed];idx['F3_current47_original154_typed_recovery_role_clarification']=ref(side);idx['current330_completed1063_1189_QI_and_live1184_1175']=ref(proof);assert sum(bool(z.get('accepted_decision')) for z in idx['cases'])==330
put(O/'full336-current330-actual-final48-delivery-progress-index.json',idx);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: record last F2 and F5 completed fullQI personal-review frontier and clarify preserved F3 typed recovery roles','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':322,'accepted':330,'per_family':new['accepted_per_family'],'completed_QI_pending_review':[z['original'] for z in completed],'live_render_workers':live,'home_free_GiB':free,'gpu_h':gpu,'cpu_core_h':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
