from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W3=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');W6=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
pre164=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_164_f3_source178_dynamic_entry_catalog_correction_v1');pre178=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_178_f2_f3_f6_first24_dynamic_entry_catalog_v1');commits={str(pre164):'009f55a6b3c47a00c29edfa8795be0f6c8ee6e22',str(pre178):'d2f3c31e1bf694007a79d4b462c003f57e2b3fdb'};blobs={};before={}
for W,pre,num in ((W3,pre164,6),(W6,pre178,4)):
 ns=subprocess.check_output(['git','ls-tree','-r','--name-only',commits[str(pre)],'--',str(pre)],cwd=W,text=True).splitlines();assert len(ns)==num
 for n in ns:
  b=subprocess.check_output(['git','show',f'{commits[str(pre)]}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b;before[str(W/n)]=hashlib.sha256(b).hexdigest()
rv=subprocess.run(['python3','-B',str(W3/pre164/'scripts/validate_fresh164.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(n) for n in before};src=load(W6/pre178/'metadata/dynamic-entry-catalog.json');catalog=copy.deepcopy(load(W3/pre164/'metadata/dynamic-entry-catalog-corrected.json'));assert catalog['membership']==src['membership'] and len(catalog['rows'])==72
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_227.json';cp=load(cpfile);assert cp['checkpoint']==227 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==287;acceptedpaths=set(cp['accepted_decisions']);idxp=root(1273)/'full336-current287-actual-final48-delivery-progress-index.json';idx=load(idxp);final={f:{r['physical_case_id'] for r in idx['cases'] if r['family_id']==f} for f in ('F2','F3','F6')};assert all(len(v)==48 for v in final.values())
f2p=root(1211)/'F2-first8-first24-final48-physical-membership-and-actual24-visual-delivery.json';f3p=root(1252)/'MAIN_F3_ACTUAL_FIRST24_DELIVERED_SUBSET_CURRENT37_FINAL48.json';f6p=root(1238)/'MAIN_ACTUAL_FIRST24_F4_F6_SUBSET_CURRENT_ACCEPTED.json';frozenp=root(1093)/'FIRST8_PER_FAMILY_STAGE1_SUBSET56.json';f2=load(f2p);f3=load(f3p);f6=load(f6p)['families']['F6'];frozen=load(frozenp);auth24={'F2':[r['physical_case_id'] for r in f2['case_refs']],'F3':f3['actual_first24_physical_case_ids'],'F6':[r['physical_case_id'] for r in f6['rows_actual_source_order']]};auth8={f:{load(e['path']).get('physical_case_id',load(e['path'])['case_id']) for e in frozen['cases_by_family'][f]} for f in auth24};families={};cache={};counts=collections.Counter();total_contacts=total_keys=0; membership_corrections=[]; legacy_schema_observations=[]
for f,ids in auth24.items():
 rows=[r for r in catalog['rows'] if r['family_id']==f];assert [r['physical_case_id'] for r in rows]==ids and len(ids)==len(set(ids))==24 and len(auth8[f])==8 and auth8[f]<=set(ids)<=final[f];families[f]=rows
for a in catalog['authorities']:
 e=a['ref'];assert sha(e['path'])==e['sha256']
for row in catalog['rows']:
 cid=row['case_id'];pid=row['physical_case_id'];f=row['family_id'];assert row['accepted_decision']['path'] in acceptedpaths;vd=load(row['accepted_decision']['path']);assert vd['family_id']==f and vd['case_id']==cid and vd.get('physical_case_id',vd['case_id'])==pid;assert row['first24_member']; original_first8=row['first8_member']; actual_first8=(pid in auth8[f]); row['source_catalog_first8_member_snapshot']=original_first8; row['first8_member']=actual_first8; membership_corrections.extend([{'family_id':f,'physical_case_id':pid,'source_first8_member_snapshot':original_first8,'actual_frozen1093_first8_member':actual_first8}] if original_first8!=actual_first8 else []);assert not row['evidence_scope']['new_visual_review'] and row['evidence_scope']['case_credit']==0
 allrefs=row['all_allowed_refs']+row['native_request_role_snapshot']['allowed_evidence_refs']+[row['accepted_decision'],row['actual_render_report']['ref'],row['actual_xmf_manifest'],row['actual_xmf_xml']]+row['contact_png_refs']+row['key_png_refs']
 for e in allrefs:
  p=Path(e['path']);assert p.suffix.lower() in {'.json','.xml','.xmf','.png'};assert p.is_file()
  if str(p) not in cache:cache[str(p)]=(sha(p),p.stat().st_size)
  assert cache[str(p)][0]==e['sha256'];assert 'bytes' not in e or cache[str(p)][1]==e['bytes']
 rr=row['actual_render_report']['ref'];xr=row['actual_xmf_manifest'];xx=row['actual_xmf_xml'];report=load(rr['path']);manifest=load(xr['path']);assert Path(xr['path']).name=='manifest.json' and report['manifest_sha256']==xr['sha256'];assert manifest['xdmf']==xx['path'] and manifest['xdmf_sha256']==xx['sha256']; assert report['input_manifest']==xr['path'];
 if 'xdmf' in report: assert report['xdmf']==xx['path'] and report['xdmf_sha256_after']==xx['sha256']
 else:
  assert cid in {'F3_CELL3_LONG_DP006_AY0P50_ADAPTIVE_CFL05_COEF005','F3_STAGE1_DP006_P1000_AY0750','F3_STAGE1_DP006_P1000_AY0250','F3_STAGE1_DP006_P1000_AY0320','F3_STAGE1_DP006_P1000_AY0390','F3_STAGE1_DP006_P1000_AY0460','F3_STAGE1_DP006_P1000_AY0570'}; assert vd['bindings']['animation_integrity_report']=={'path':rr['path'],'sha256':rr['sha256']}; assert len(report['frame_diagnostics'])==836 and [d['actual_time_s'] for d in report['frame_diagnostics']]==manifest['actual_time_s']; legacy_schema_observations.append({'case_id':cid,'report_xdmf_field_present':False,'report_source_frames_field_present':False,'report_outputs_field_present':False,'actual_own_XMF_binding':'report input_manifest SHA -> manifest xdmf path and SHA','contact_png_binding':'published case-local 35 contacts with actual supplied keys retained by original accepted historical decision','actual_key_count':len(row['key_png_refs'])})
 assert manifest['case_id']==cid and manifest.get('physical_case_id',pid)==pid;assert report['frames']==report.get('source_frames',manifest['frames'])=={'F2':401,'F3':836,'F6':241}[f] and report['all_frames_rendered'] and report['actual_times_preserved_exactly'] and report['native_identity_axis_preserved'] and report['nonfinite_active_states']==0
 assert [e['path'] for e in row['contact_png_refs']]==report['outputs']['contact_sheets'] if 'outputs' in report else (cid in {'F3_CELL3_LONG_DP006_AY0P50_ADAPTIVE_CFL05_COEF005','F3_STAGE1_DP006_P1000_AY0750','F3_STAGE1_DP006_P1000_AY0250','F3_STAGE1_DP006_P1000_AY0320','F3_STAGE1_DP006_P1000_AY0390','F3_STAGE1_DP006_P1000_AY0460','F3_STAGE1_DP006_P1000_AY0570'} and len(row['contact_png_refs'])==35 and [Path(e['path']).name for e in row['contact_png_refs']]==[f'all_frames_{i:03d}.png' for i in range(35)]);assert all(Path(e['path']).is_relative_to(Path(rr['path']).parent) for e in row['contact_png_refs']+row['key_png_refs']);total_contacts+=len(row['contact_png_refs']);total_keys+=len(row['key_png_refs']);counts[f]+=1
assert counts=={'F2':24,'F3':24,'F6':24};changes=catalog['correction_audit']['changed_primary_rows'];assert len(changes)==2 and {r['case_id'] for r in changes}=={'F3_STAGE1_DP006_P1000_AY0540','F3_STAGE1_DP006_P1000_AY0590'}
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);attempts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(c.get('gpu_seconds',0) for c in ld['charges'])/3600;cpu=sum(c.get('cpu_core_seconds',0) for c in ld['charges'])/3600;s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize/2**30;assert gpu<512 and cpu<3840 and attempts['qualification']<=1024 and attempts['production']<=720 and free>=500;now=datetime.datetime.now(datetime.timezone.utc);O=H/'root_stage1_sources178164_actual_F2_F3_F6_first24_delivery72_correct_own_primary_XMF_PNG_8_subset24_subset48_1276';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_228.json';assert not list(H.glob('root*_1276')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
vp=O/'sources178164-byte-exact-readonly-validation.json';put(vp,{'source_commits':commits,'source_files_SHA_before_after':before,'source_original_bytes_preserved':True,'adopted_source_files':adopted,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'main_independent_exact_actual_membership_primary_report_XMF_and_PNG_checks':True,'main_hashed_metadata_and_published_PNG_files':len(cache),'scientific_payload_IO':False})
assert len(membership_corrections)==6 and all(r['family_id']=='F2' for r in membership_corrections); membershipp=O/'F2-source-planned-first8-vs-frozen1093-first8-role-correction.json';put(membershipp,{'frozen_actual_first8_authority':ref(frozenp),'original_actual24_snapshot_authority':ref(f2p),'source164_catalog_preserved':ref(R/pre164/'metadata/dynamic-entry-catalog-corrected.json'),'original_flags_role':'Source planned-first8 labels are historical snapshots; actual frozen-first8 authority is Root1093.','corrections':membership_corrections,'actual_first24_membership_unchanged':True,'source_documents_byte_unchanged':True,'case_credit':0}); familyrefs={}
for f,rows in families.items():
 p=O/f'{f}-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json';put(p,{'family_id':f,'actual_first24_count':24,'frozen_first8_physical_case_ids':sorted(auth8[f]),'actual_first24_physical_case_ids':auth24[f],'registered_final48_physical_case_ids':sorted(final[f]),'first8_subset_actual24_subset_registered48':True,'source_membership_snapshot_preserved':catalog['membership'][f],'source_membership_current_counts_are_historical_not_new_counts':True,'current_accepted_family_count':cp['accepted_per_family'][f],'actual_own_primary_rows':rows,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收','Q_N':0,'Q_E':0});familyrefs[f]=ref(p)
manifestp=O/'MAIN_ACTUAL_F2_F3_F6_FIRST24_DELIVERY72.json';put(manifestp,{'schema':'ds02.main.actual-first24-dynamic-product-delivery.v1','at_utc':now.isoformat(),'stable_predecessor_acceptance_authority':ref(cpfile),'source178_original_catalog':ref(R/pre178/'metadata/dynamic-entry-catalog.json'),'source164_corrected_catalog':ref(R/pre164/'metadata/dynamic-entry-catalog-corrected.json'),'source_validation':ref(vp),'frozen_first8_membership_correction':ref(membershipp),'families':familyrefs,'actual_delivered_cases':72,'unique_accepted_physical_case_ids':72,'first8_subset_actual24_subset_registered48_each_family':True,'actual_own_report_manifest_XMF_sha_bindings_all72_verified':True,'all_primary_contacts_bound_to_own_report_outputs_or_original_anchor_acceptance':True,'legacy_schema_field_absence_preserved':legacy_schema_observations,'primary_contacts':total_contacts,'primary_keys':total_keys,'historical_or_foreign_context_refs_not_primary':True,'two_F3_AY0540_AY0590_wrong_primary_source_refs_corrected_without_mutating_source178':changes,'four_original_F3_native_OS_unknowns_and_recovered065_evidence_roles_preserved':True,'F3_anchor_semantic49_vs_actual_native86562_roles_preserved':True,'native_request_unresolved_snapshot_fields_not_promoted_to_absence_or_new_certificate':True,'source_membership_current_counts_snapshot_not_new_current_counts':True,'new_case_credit':0,'new_visual_review':False,'main_scientific_payload_IO':False,'Q_N':0,'Q_E':0,'precision_status':'视觉检查通过、数值精度未验收'})
lines=['# F2 / F3 / F6：各24例动态数据交付','','72例均已有视觉验收，数值精度未验收。各族冻结的8例属于这里实际交付的24例，24例属于注册的最终48例。每个链接均指向本例完整渲染报告所绑定的XMF；历史审核和原始失败记录保留在清单中。','']
for f,rows in families.items():
 lines.extend([f'## {f}',''])
 for row in rows:lines.append(f"- [{row['physical_case_id']}]({row['actual_xmf_xml']['path']}) — {row['actual_render_report']['metadata']['frames']}帧，{'first8' if row['first8_member'] else 'first24'}")
 lines.append('')
(O/'README.md').write_text('\n'.join(lines));ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp.update(checkpoint=228,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: delivered actual F2/F3/F6 first24 dynamic products72; exact frozen8 subset actual24 subset final48 and all own primary XMF/manifest/render/PNG SHA bindings verified; two source178 nested historical primary errors corrected by immutable source164. No new casecredit. Fresh177 actual1046 full836 metadata +44PNG preflight pass, body-language contradiction held pending fresh179 personal recheck.',authorized_work_state='Active287/336,49 pending; actual first24 F2/F3/F6 delivered72, F1/F4/F7 final48 delivered144. Fresh179 clarifies original177 F3 types and source-template file hash; existing F5render1148/1186 samehandles continue.');newcp['actual_progress']['actual_F2_F3_F6_first24_dynamic_delivery72']=ref(manifestp);newcp['actual_progress']['source163_actual10_F2_controls_restoration_current9pending']=ref(root(1274)/'actual10-F2-controls-restoration-and-current9-pending-own-metadata-proof.json');newcp['actual_progress']['F3_actual1046_full836_previsual_QI']=ref(root(1269)/'actual1046-full836-completed-QI-UID-N3-native-scope-previsual-proof.json');newcp['source_agents']['production_recovery']='fresh164 corrected actualfirst24 delivery72 adopted, ready nexttask';newcp['source_agents']['f6_endpoint_initial_qa']='fresh177 metadata and44actualPNG pass; acceptanceheld for fresh179 personal image/rigid-language and source-template FILE hash clarification';newcp['next_executable_tasks']=['Adopt fresh177 plus fresh179 actual1046 F3P0800AY0640 only after actual published-image clarification; mainQI1269 full836 done.','After original1148 publication run ownfull801QI1272, adopt fresh201 M098T095 personal34contacts9keys.','After original1186 publication run ownfull801QI1275, delegate M115T080 personal34contacts9keys.','Continue original remaining render queue and actual F5prefix19 to24; current actualfirst24 F2/F3/F6 product72 and F1/F4/F7 final48 product144 are delivered without duplicatecredit.'];assert len(newcp['accepted_decisions'])==newcp['stage1_visual_accepted_complete_independent_cases']==sum(newcp['accepted_per_family'].values())==287;put(nextcp,newcp)
idx['previous_index_preserved']=ref(idxp);idx['source_authoritative_checkpoint']=ref(nextcp);idx['at_utc']=now.isoformat();idx['new_case_credit']=0;idx['actual_F2_F3_F6_first24_delivery']=ref(manifestp);assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==287;put(O/'full336-current287-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: deliver real first24 F2 F3 F6 dynamic entries72 with own primary evidence','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':228,'accepted':287,'actual_dynamic_delivery':72,'primary_contacts':total_contacts,'primary_keys':total_keys,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
