from pathlib import Path
import json,hashlib,copy,datetime,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_269.json';cp=load(cpfile);assert cp['checkpoint']==269 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==307
qis=[]
for original,num,source in [(1150,1349,210),(1157,1350,191)]:
 p=root(num)/f'actual{original}-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';j=load(p);assert j['all801_geometry_velocity_N3_times_UID_finite_verified'] and j['all_native_UIDs_active_each_frame'] and j['new_case_credit']==0
 for k in ['render_receipt','render_report','render_publish_receipt']:check(j['actual_completed_metadata_evidence'][k])
 rc=load(j['actual_completed_metadata_evidence']['render_receipt']['path']);pub=load(j['actual_completed_metadata_evidence']['render_publish_receipt']['path']);assert rc['status']=='completed' and rc['returncode']==0 and pub['status']=='published_after_atomic_rename' and pub['case_id']==j['case_id'];qis.append({'original':original,'own_QI':ref(p),'physical_case_id':j['physical_case_id'],'source_personal_review':source,'case_credit':0,'evidence':j['actual_completed_metadata_evidence']})
F=root(1164);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';old=load(pre)
for e in old.values():
 if isinstance(e,dict) and 'path' in e and 'sha256' in e:check(e)
t=load(old['actual_typed_report']['path']);x=load(old['actual_XMF_manifest']['path']);n=load(t['source_provenance']['solver_receipt']['path']);nq=n['request'];q=load(F/'enabled-full801-render-request.json');w=load(F/'enabled-render-wrapper.json');bedrc=load(old['actual_bed_receipt']['path']);b=load(bedrc['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert canonical==x['physical_condition_sha256']==x['canonical_physical_condition_sha256']=='859a739d1f7159e033b57f1842fc18264fcf44140f78483469e11ff4f05aefba' and legacy=='e0074c15b562c6e7eb4d34e3da768b91e522f4f977385b0b972b1a16f26e7360' and sd=='8849139c088a0807e52f796edbf4b0ecaeafa3ac49c80870ced7ad3fcf528eba';assert n['status']=='completed' and n['returncode']==0;assert len({canonical,legacy,sd})==3 and sha(b['source_definition'])==b['source_definition_sha256']==sd
mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};assert mask['native']['source_plan_condition_sha256']==mask['XMF']['source_plan_condition_sha256']=={'present':False,'value':None};assert mask['native']['source_plan_physical_condition_sha256']=={'present':True,'value':canonical} and mask['XMF']['source_plan_physical_condition_sha256']=={'present':True,'value':sd};assert w['expected_frames']==t['frames']==x['frames']==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34;assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
live=[]
for original,pid,start,num in [(987,599335,'213680043',1355),(1164,604869,'213723590',1359)]:
 P=Path(f'/proc/{pid}');ls=None;terminal=root(original)/'controller-result.json'
 if P.exists():
  stat=P.joinpath('stat').read_text().split(') ',1)[1].split();assert stat[19]==start;cmd=P.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);ls={'pid':pid,'startticks':start,'state':stat[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 live.append({'original':original,'same_actual_process':ls,'authoritative_terminal':ref(terminal) if terminal.exists() else None,'future_own_QI_root':num,'future_own_QI_proof':None,'no_restart':True,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_two_F5_actual1150_1157_published_full801QI_nextF3_987_F5_1164_live_exact_native_XMF_SourceDef_roles_durable801QI_1360';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_270.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1164_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1164-full801-own-QI1359.py').read_bytes());pp=O/'two-F5-published801QI-next-original987-1164-live-and-durable1164-QI-readiness.json';put(pp,{'schema':'ds02.current307-twoF5-ownQI-nextF3F5-durable.v1','at_utc':now.isoformat(),'two_actual_completed0_published_F5_own_QI_visual_pending':qis,'next_same_original_actual_live_processes':live,'next_originalF5_1164_physical_case_id':q['physical_case_id'],'next_originalF5_1164_native_canonical_sha256':canonical,'next_originalF5_1164_typed_legacy_sha256':legacy,'next_originalF5_1164_bed_SourceDef_FILE_sha256':sd,'next_originalF5_1164_actual_native_XMF_plan_field_namespaces':mask,'native_physical_plan_canonical_XMF_physical_plan_SourceDef_independently_verified':True,'next_originalF5_1164_own_scientific_dependency_previsual_review':ref(pre),'durable_original1164_only_QI_entrypoint':ref(entry),'commands':[['python3','-B',str(entry),'1164','1359']],'do_not_rerun_finished_QI':True,'scientific_payload_IO':False,'case_credit':0,'no_new_scientific_or_render_jobs':True})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=270,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active307/336: two F5 original1150 M106T095 and1157 M100T080 completed0/published/full801 ownQI1349/1350; source210/source191 personally reviewing. Next originalF3 987 and originalF5 1164 same PV processes live; futureown836QI1355 and801QI1359 durable entrypoints prepared with independent actual namespace presence/roles. Source176 F3 completion-only final48 builder in work; no partial-final48 claim.',previous_goal_turn_classification='PROGRESS: original1150 and1157 F5 full801 actualcompleted0/published and ownQI1349/1350 finished, visual tasks activated; next originalF3 987 real836 scope and both native/XMF plan absences pinned, nextF5 1164 nativephysical canonical versus XMFphysical SourceDef FILE pinned with new durable ownQI1359 entrypoint. No scientific reruns or new visual count yet.')
new['actual_progress']['actual1157_full801_own_QI']=qis[1]['own_QI'];new['actual_progress']['two_actual1150_1157_published_QI_next987_1164_live_durable1164_QI']=ref(pp);new['next_executable_tasks']=['Adopt finalsource210 F5 original1150 personal34contacts9keys and source191 F5original1157 personal34contacts9keys after readonly validation/byte-exact sourcecommit/actualownQI1349/1350 closure; do not infer XMF physical-plan roles from bed filenames.','Observe same actual originalF3 987 PID599335/start213680043; completed0/pub then run Root1356 after_original987_terminal_full836_own_QI.py 987 1355 once; assign next available child personal35contacts9keys, preserving actual native/XMF both plan field absences and original outer801/194427 envelope as historical only.','Observe same actual originalF5 1164 PID604869/start213723590; completed0/pub then run new durable ownQI1359 once; assign next available child personal34contacts9keys with actual nativephysical-plan canonical versus XMFphysical-plan SourceDef FILE.','Integrate fresh176 F3 completion-only final48 builder/readonly validator after scopedcommit and source code audit; current42/48 readiness must not create partial final delivery.','Continue remaining29 originalactual cases and complete F2/F3/F5 final48 directories when each reaches48; Home500GiB floor, cumulative534.4086GiB cleanup and all numerical/external unknown limits remain.'];put(np,new)
ip=root(1356)/'full336-current307-actual-final48-delivery-progress-index.json';index=load(ip)
for obj in qis:
 row=next(r for r in index['cases'] if r['physical_case_id']==obj['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=obj['own_QI'],current_actual_render_receipt=obj['evidence']['render_receipt'],current_atomic_publish_receipt=obj['evidence']['render_publish_receipt'],current_personal_review_source=obj['source_personal_review'],case_credit=0);row['prior_controller_observations_are_historical_not_current']=True
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[z['physical_case_id'] for z in qis],current_two_F5_published_QI_next987_1164_live_durable1164=ref(pp));assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==307;put(O/'full336-current307-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bind two completed F5 own QI and next original F3 F5 recovery','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':270,'accepted':307,'published_own_QI_originals':[1150,1157],'next_live':live,'free_GiB':free,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
