from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'));O=H/'root_stage1_F4_delegated127_actual924_first_full1201_visual_integration_940';O.mkdir(exist_ok=False);load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_122.json')['accepted_decisions']+load(root(933)/'actual-integration-review.json')['decisions'];assert len(prior)==198;priorrows=[load(p) for p in prior];ids={d.get('physical_case_id',d['case_id']).replace('F4_DROP_B08_','F4_DROP_') for d in priorrows};digests={d['physical_condition_sha256'] for d in priorrows};assert sum(d['family_id']=='F4' for d in priorrows)==37
commit=subprocess.check_output(['git','rev-parse','00731590'],cwd=W,text=True).strip();S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_127_*'));rel=S.relative_to(W);refs=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
 src=W/name;blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert src.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==blob;dst.write_bytes(blob);refs.append(ref(dst))
P=R/rel;c=load(P/'metadata/chain-closure.json');v=load(P/'metadata/visual-review.json');png=load(P/'metadata/png-hashes.json');cid=v['physical_case_id'];scope=c['scope_separation'];dg=scope['actual_producer_scope_sha256'];assert cid==c['case_id'] and cid not in ids and dg not in digests;assert c['reviewer']==v['reviewer']=='/root/f6_endpoint_initial_qa';assert c['status']==v['status']=='visual-approved-by-delegated-agent' and v['agent_personally_viewed_all_contact_sheets'] and v['agent_personally_viewed_all_key_frames'] and not v['main_personally_viewed_pngs'];assert len(png['contact_sheets'])==51 and len(png['key_frames'])==9 and all(x['viewed_with_view_image'] for x in png['contact_sheets']+png['key_frames'])
def walk(x):
 if isinstance(x,dict):
  if 'path' in x and 'sha256' in x:assert sha(x['path'])==x['sha256'],x['path']
  for a in x.values():walk(a)
 elif isinstance(x,list):
  for a in x:walk(a)
walk(c);walk(png);chain=c['producer_chain'];ev={}
for name,item in chain.items():
 p=item['receipt']['file'];rr=load(p['path']);assert (rr['status'],rr['returncode'])==('completed',0) and rr['request']['case_id']==cid;ev[name+'_receipt']=ref(p['path'])
assert chain['basic_initial_qa']['pass_result'] and chain['native_frame0_qa']['pass_result'];prep=load(chain['gencase']['prepared_report']['file']['path']);assert prep['actual_total_particles']==83233 and prep['actual_generated_constants']['data2d']['value']=='false' and prep['generated_xml_particle_counts']=={'fixed':24161,'moving':0,'floating':0,'fluid':59072}
t=load(chain['typed']['report']['path']);x=load(chain['xmf']['manifest']['path']);a=load(chain['render']['report']['path']);assert t['conversion_status']=='completed' and t['frames']==1201 and t['particles']==83233 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['hash_scopes']['physical_condition_sha256']==dg and hashlib.sha256(json.dumps(t['hash_scopes']['physical_condition'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg;assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=1.2 and t['time_evidence']['strictly_increasing'];assert x['frames']==1201 and x['particles']==83233 and x['source_h5_sha256']==t['output_sha256'] and x['physical_condition_sha256']==dg;xf=x['xdmf'];assert sha(xf)==x['xdmf_sha256'];grids=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(grids)==1201 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='83233 3' for g in grids)
assert a['frames']==a['source_frames']==1201 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0;assert a['manifest_sha256']==sha(chain['xmf']['manifest']['path']) and a['source_h5_sha256']==t['output_sha256'] and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf)
fs=t['lifecycle']['frame_summary'];ads=a['frame_diagnostics'];assert len(fs)==len(ads)==1201 and all(f['finite_positions_active'] and f['identity_axis_preserved'] and all(z['finite_active'] and z['nonfinite_active']==0 for z in f['finite_fields'].values()) for f in ads);assert all(f['missing_particles']==g['missing'] for f,g in zip(fs,ads));events=sum(f['missing_particles']>0 for f in fs);maximum=max(f['missing_particles'] for f in fs);assert events==167 and maximum==1 and fs[-1]['missing_particles']==1;assert c['lifecycle_metadata']['reported_missing_frame_event_count']==events;assert c['root924_guardian']['guardian_observation']['worker_and_launcher_allowed_to_finish'] and not c['root924_guardian']['guardian_observation']['worker_terminated_or_restarted']
for k,p in [('typed_report',chain['typed']['report']['path']),('xmf_manifest',chain['xmf']['manifest']['path']),('render_report',chain['render']['report']['path']),('prepared_input_report',chain['gencase']['prepared_report']['file']['path'])]:ev[k]=ref(p)
d={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':v['status'],'family_id':'F4','case_id':cid,'physical_case_id':cid,'physical_condition_sha256':dg,'source_review_commit':commit,'source_review_closure':ref(P/'metadata/chain-closure.json'),'source_visual_review':ref(P/'metadata/visual-review.json'),'visual_reviewer':v['reviewer'],'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['observations'],'agent_limitations':v['limitations'],'scope_separation':scope,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':png,'actual_frames':1201,'actual_particles':83233,'actual_fluid_particles':59072,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':maximum,'final_missing_particle_count':fs[-1]['missing_particles'],'final_missing_UIDs':fs[-1]['missing_id_first'],'missing_frame_event_count':events,'delegated_lifecycle_original':c['lifecycle_metadata'],'lifecycle_limitation':'167 transient missing-frame events and final1 are separate facts; final UID list from producer metadata only; exclusion cause unqualified.','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':198,'resulting_count':199};dp=O/(cid+'-delegated-visual-decision.json');put(dp,d);put(O/'actual-integration-review.json',{'source_commit':commit,'adopted_files':refs,'source_adopted_byte_exact':True,'previous_count':198,'resulting_count':199,'independent_case_increment':1,'decisions':[str(dp)],'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'new_cases':1,'accepted':199,'F4':38})
