from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections,copy,sys
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
commit=sys.argv[1];prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_199_f5_m105_t090_actual1182_personal_visual_review_v1';P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==9
blobs={}
for n in names:
 bts=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert bts==(W/n).read_bytes();assert not (R/n).exists() or (R/n).read_bytes()==bts;blobs[n]=bts
before={n:sha(W/n) for n in names};validator=P/'scripts/validate_fresh199.py';rv=subprocess.run(['python3','-B',str(validator)],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
v=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');z=load(P/'metadata/physical-stage-closure.json');up=load(P/'metadata/upstream-evidence.json');qp=root(1263)/'actual1182-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qp);refs=qi['actual_completed_metadata_evidence'];cid=v['case_id'];pid=v['physical_case_id'];assert cid==z['case_id']==up['case_id']==png['case_id']==qi['case_id'] and pid==z['physical_case_id']==up['physical_case_id']==png['physical_case_id']==qi['physical_case_id']
for e in refs.values():assert sha(e['path'])==e['sha256']
for e in z['actual_stage_chain']:assert sha(e['path'])==e['sha256']
assert up['qi_review']['path']==str(qp) and up['qi_review']['sha256']==sha(qp) and up['actual_completed_metadata_evidence']==refs
for k in ['gencase','initial_qa','native','typed','xmf','bed','render']:
 a=load(refs[k+'_receipt']['path']);assert (a['status'],a['returncode'])==('completed',0) and a['request']['case_id']==cid
roles=up['scope_roles'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];native=load(refs['native_receipt']['path']);b=load(load(refs['bed_receipt']['path'])['request']['binding'])
assert canonical==roles['canonical_native_physical_condition_sha256']==native['request']['physical_condition_sha256'];assert legacy==roles['typed_converter_actual_legacy_scope_sha256'];assert roles['historical_source_h5_scope_sha256']==qi['historical_negative_flags']['historical_source_scope_values_preserved']['source_h5_historical']
assert qi['actual_SourceDef']['sha256']==qi['bed_declared_source_plan_field_sha256']==roles['source_definition_and_bed_declared_plan_sha256'];assert sha(qi['actual_SourceDef']['path'])==qi['actual_SourceDef']['sha256']
assert not roles['native_request_source_plan_field_present'] and 'source_plan_physical_condition_sha256' not in native['request'] and roles['native_request_source_plan_physical_condition_sha256'] is None and qi['actual_native_source_plan_condition_sha256'] is None
assert roles['xmf_source_plan_condition_field_present'] and roles['xmf_source_plan_condition_sha256']==qi['XMF_source_plan_condition_field_sha256']==qi['actual_SourceDef']['sha256'] and canonical!=qi['actual_SourceDef']['sha256']
assert roles['actual_native_source_plan_file_sha256'] is None and sha(b['source_plan_file'])==b['source_plan_file_sha256'] and not qi['historical_negative_flags']['original_binding_explicit_AB_retention_field_present'] and not qi['historical_negative_flags']['original_binding_explicit_precision_retention_field_present']
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
dec=v['decision'];assert dec['standalone_first_stage_visual_approved'] and dec['weak_wave_only'] and dec['independent_case_count_increment']==0 and not any(dec[k] for k in ['severe_visual_failure','needs_root_image_intervention','numerical_precision_accepted','q_n_granted','q_e_granted','large_inundation_or_runup_claim','strict_container_guarantee','bed_zero_bins_are_sub_dp_depth_proof'])
r=load(refs['render_report']['path']);pub=load(refs['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==refs['render_report']['sha256'];contacts=png['producer_attested_contact_sheets'];keys=png['producer_attested_keyframes'];assert len(contacts)==34 and len(keys)==9 and [e['frame_index'] for e in keys]==list(range(0,801,100)) and [e['absolute_path'] for e in contacts]==r['outputs']['contact_sheets'];pr={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in contacts+keys:assert e['reviewed'] and sha(e['absolute_path'])==e['sha256']==pr[e['relative_path']]['sha256'] and Path(e['absolute_path']).stat().st_size==e['bytes']==pr[e['relative_path']]['bytes']
cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_223.json';cp=load(cpp);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==283 and cp['accepted_per_family']['F5']==18;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {d.get('physical_case_id',d['case_id']) for d in old}
ixp=root(1264)/'full336-current283-actual-final48-delivery-progress-index.json';idx=load(ixp);rows=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(rows)==1 and not rows[0].get('accepted_decision') and rows[0]['native_request_scope']['sha256']==canonical
gp=root(1260)/'F5-actual-first24-growing-prefix18-frozen8-acceptance-order.json';g=load(gp);assert g['actual_first24_realized_prefix_count']==len(g['physical_case_ids_actual_delivery_order'])==18 and pid not in g['physical_case_ids_actual_delivery_order']
for e in g['actual_visual_decisions']:assert sha(e['path'])==e['sha256']
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;cnt=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;assert free>=500 and gpu<=512 and cpu<=3840 and cnt['qualification']<=1024 and cnt['production']<=720
assert datetime.datetime.fromisoformat(v['reviewed_at_utc'])<=datetime.datetime.now(datetime.timezone.utc)
O=H/'root_stage1_source199_F5_M105T090_actual1182_personal34contacts_ninekeys_full801QI_plan_roles_prefix19_visual_acceptance_1267';assert not list(H.glob('root*_1267')) and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_224.json').exists();O.mkdir();adopted=[]
for n in names:
 bts=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert bts==(W/n).read_bytes();p=R/n;assert not p.exists() or p.read_bytes()==bts;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(bts);adopted.append(ref(p))
put(O/'source199-byte-exact-adoption-readonly-validator.json',{'source_commit':commit,'adopted_files':adopted,'validator_returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr,'source_bytes_unchanged':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat()
assert datetime.datetime.fromisoformat(v['reviewed_at_utc'])<=datetime.datetime.fromisoformat(now)
dp=O/(pid+'-delegated-visual-decision.json');decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_plan_condition_sha256':None,'native_request_source_plan_condition_field_present':False,'native_plan_field_absence_preserved':True,'XMF_source_plan_condition_sha256':qi['XMF_source_plan_condition_field_sha256'],'XMF_and_bed_plan_fields_have_SourceDef_role':True,'bed_declared_source_plan_field_sha256':qi['bed_declared_source_plan_field_sha256'],'source_definition_sha256':qi['actual_SourceDef']['sha256'],'original_binding_explicit_retention_field_absences':qi['historical_negative_flags'],'actual_bed_binding_source_plan_FILE':ref(b['source_plan_file']),'bed_binding_source_plan_FILE_role':'bed worker source-plan JSON file; distinct from absent native request condition field and SourceDef declaration digest','source199_original_scope_roles':roles,'source_review_commit':commit,'source_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'source_review_closure':ref(R/prefix/'metadata/physical-stage-closure.json'),'source_reviewed_at_utc_preserved':v['reviewed_at_utc'],'actual_completed_metadata_evidence':refs,'independent_full801_QI_previsual_proof':ref(qp),'full_native_frames':801,'particles':194427,'actual_physical_window_s':qi['actual_time_window_s'],'all801_geometry_velocity_N3_times_UID_finite_verified':True,'all_native_UIDs_active_each_frame':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['visual_observations'],'contacts_personally_viewed':34,'key_frames_personally_viewed':list(range(0,801,100)),'all43_reviewed_PNGs_main_bound_to_actual_publish_hashes':True,'all801_full_bed_UID_footprint_one_DP_two_DP_diagnostics_checked':True,'positive_depth_below_DP_not_proven_absent_by_zero_bin_counts':True,'large_runup_inundation_or_strict_container_guarantee':False,'initial_qa_numerical_precision_negative':qi['actual_initial_QA_precision_negative'],'historical_AB_negative_evidence_preserved':up['historical_negative_evidence'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source199-actual1182-full801QI-personal-visual-adoption-proof.json';put(proof,{'source_commit':commit,'source_QI':ref(qp),'all_original_QI_stage_hashes_match':True,'source_stage_chain_metadata_hashes_checked':len(z['actual_stage_chain']),'all43_personally_reviewed_PNGs_match_published_hashes':True,'native_plan_absence_XMF_SourceDef_bed_historicalH5_and_typedlegacy_roles_preserved':True,'source_QI_schema_label_not_inferred_as_actual_proof_schema':{'original_source_declared_schema':up['qi_review'].get('schema'),'actual_QI_schema_field_present':'schema' in qi,'actual_QI_schema_value':qi.get('schema')},'new_decision':ref(dp),'new_case_credit':1,'main_scientific_payload_IO':False})
gids=g['physical_case_ids_actual_delivery_order']+[pid];grefs=g['actual_visual_decisions']+[ref(dp)];assert len(set(gids))==19 and gids[:8]==g['first8_physical_case_ids'];gout=O/'F5-actual-first24-growing-prefix19-frozen8-acceptance-order.json';put(gout,{'schema':'ds02.main.F5.actual-first24-growing-delivery-prefix.v3','at_utc':now,'first8_frozen_authority':g['first8_frozen_authority'],'previous_actual_prefix18':ref(gp),'predecessor_authoritative_checkpoint':ref(cpp),'newly_accepted_decision':ref(dp),'authority_role':'stable predecessor223 F5=18 plus new immutable decision; successor224 adopts prefix','first8_physical_case_ids':g['first8_physical_case_ids'],'actual_first24_realized_prefix_count':19,'actual_first24_delivered':False,'target_first24':24,'target_final48':48,'first8_subset_realized_prefix_subset_final48_verified':True,'physical_case_ids_actual_delivery_order':gids,'actual_visual_decisions':grefs,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收'})
lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);cp=copy.deepcopy(cp);cp['accepted_per_family']['F5']+=1;cp.update(checkpoint=224,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),stage1_visual_accepted_complete_independent_cases=284,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts=dict(cnt),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actual1182 full801 QI1263 plus fresh199 personal34contacts9keys accepted284/F5=19; true nativeplanabsence and XMF/bed SourceDef role preserved, original binding explicit AB/precision flagfields remain absent. F2actual1142/RX061 and1065/RX056 continue same original live handles.',authorized_work_state='Active284/336 remaining52. F5 actualfirst24 prefix19 stillnot24; F1/F4/F7 actualfinal48 delivered; F2 original1142/1065 running, no science reruns, QN/QEfalse, Homefloor500GiB.')
assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==284 and set(gids)=={d.get('physical_case_id',d['case_id']) for d in [load(p) for p in cp['accepted_decisions']] if d['family_id']=='F5'}
cp['actual_progress']['source199_F5_actual1182_visual_acceptance']=ref(proof);cp['actual_progress']['F5_actual_first24_realized_prefix19']=ref(gout);cp['source_agents']['f5_bed_recovery']='fresh199 accepted284/F5=19; next actual published F5 original case';cp['next_executable_tasks']=['Own full401 QI1265 + fresh176 personal review of actualF2RX061ROT075 original1142 after atomicpublish.','Own full401 QI1266 + fresh162 personal review of actualF2RX056ROT075 original1065 after atomicpublish.','Continue same original remaining52 render controllers; personally review actual published case next; preserve globalcap2/CPU24 and all original evidence.','Extend F5 actual first24 prefix19 toward24 then48; finalF6original951 same handle waiting capacity.']
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_224.json';put(newcp,cp);rows[0].update(status='visual-approved-in-checkpoint224',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='actual native owner condition; nativeplanfield absent, XMF/bed plan SourceDef separate from historicalH5 and typedlegacy',precision_status='视觉检查通过、数值精度未验收');idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(ixp),accepted_independent_physical_cases=284,registered_pending_independent_physical_cases=52,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[p for p in idx['actual_unaccepted_completed0_published_physical_cases'] if p!=pid];idx['controller_observations_inherited_not_new_live_probe']=True;assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==284;put(O/'full336-current284-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 M105 T090 full801 visual with native plan absence and SourceDef roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':224,'accepted':284,'F5':19,'remaining':52,'Home_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
