from pathlib import Path
import json,hashlib,datetime,shutil,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
old=root(1213);failed=Path('/tmp/ds02-root1213-F5-actual1152-previsual-QI.py');(old/'failed-integration-source.py').write_bytes(failed.read_bytes());put(old/'post-QI-precheckpoint-missing-import-failure.json',{'failure':'Full801 independent QI proof completed and written; os.statvfs call failed because os import absent in copied metadata script header. No scientific job launched, no visual case credit, no checkpoint written.','new_case_credit':0,'science_jobs_started':False,'full801_QI_proof_valid_before_failure':True,'successor_root':1214})
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_191.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==271 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_192.json').exists();proof_path=old/'actual1152-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';proof=load(proof_path);assert proof['all801_geometry_velocity_N3_times_UID_finite_verified'] and proof['all_native_UIDs_active_each_frame'] and proof['new_case_credit']==0 and proof['full_frames']==801
for rr in proof['actual_completed_metadata_evidence'].values():assert sha(rr['path'])==rr['sha256']
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
O=H/'root_stage1_actual1152_F5_full801_QI_checkpoint_metadata_import_successor_no_newscience_1214';O.mkdir(exist_ok=False);put(O/'actual1213-proof-finalization-original-import-failure-preserved.json',{'valid_full801_QI_proof':ref(proof_path),'original_failed_integration_source':ref(old/'failed-integration-source.py'),'all_metadata_refs_still_match':True,'no_original_proof_or_source_mutation':True,'full801_visual_review_pending':True,'new_case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=192,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: actual1152 F5M108T095 complete0published801 independentlyclosedGenQA/native/typed/XMF/bed/render0 allUID/N3/time/finite/bed/scope. ValidQI proof1213 preserved, later metadata missingosimport failure finalized in new1214 withoutnewscience/credit. Source192personalreviewpending, original1130/951live.',authorized_work_state='Active271/336: F5actual1152 published0 all801QI awaiting192personalreview; original1130 M088T085 rendering. All336registered, no extra nativework; lastF6original951waiting; Q-N/Q-E0.')
cp['actual_progress']['actual1152_F5_full801_previsual_QI_verified']=ref(proof_path);cp['actual_progress']['actual1152_previsual_QI_metadata_finalize']=ref(O/'actual1213-proof-finalization-original-import-failure-preserved.json');cp['source_agents'].update(f5_bed_recovery='fresh192 actual1152 published0 personal34contacts9keys thennext1130',f6_endpoint_initial_qa='fresh167 actual13F2native receiptfields/aliasclosure, publishedF2/lastF6personalreviewpriority',production_recovery='fresh149 noeligibleunacceptedF3yet; nextactualpublished0review')
cp['next_executable_tasks']=['Adopt fresh192 personal34contacts9keys actual1152 andacceptonlyifownvisualpasses','Original1130 nextfull801F5real0publishthenpersonalreview','Adopt fresh167 actualF2nativeJSONfields/aliases, nofillmissingconditionsfromacceptedtop','Original951lastF6 and12F3registeredhandleswaiting; no science reruns or repeatedwait-onlypackages','Continue65 realdeliveries andF5actualfirst24subsetextensionpreservingfrozen8; Q-N/Q-E0']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_192.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in old.iterdir() if p.is_file()]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_192.json').relative_to(R)),str((root(1152)/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: retain full801 F5 integrity proof and finalize previsual checkpoint','--',*paths],cwd=R,check=True);print({'checkpoint':192,'accepted':271,'full801_QI':True,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
