from pathlib import Path
import json,hashlib,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(p):
 p=Path(p);assert p.suffix.lower() not in ['.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_163_m086_actual963_bed_binding_disabled_v1';commit='e1d8b395';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();adopted=[]
for name in names:
 assert Path(name).suffix in ['.json','.py','.md'];raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;bp=P/'bindings/M086_T085-actual963-bed-binding.json';b=load(bp);q=load(P/'requests/M086_T085-actual963-bed-request.json');worker=Path(q['command'][1]);assert sha(worker)=='15903c829e994e1847c42a8b12f41b7322ee5b1419f0dd4e74b41ce4110ffa47';assert b['disabled'] and b['source_only'] and not b['execution_allowed'] and not b['full801_authorized'];assert b['case_id']==b['producer_case_id']=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M086_T085_NEXT34'
for k in ['xmf_manifest','xdmf','xmf_receipt']:assert sha(b[k])==b[k+'_sha256']
rc=load(b['xmf_receipt']);assert (rc['status'],rc['returncode'])==('completed',0);xm=load(b['xmf_manifest']);t=load(b['full_typed_conversion_report']);assert xm['frames']==t['frames']==801 and xm['particles']==t['particles']==194427 and xm['source_h5_sha256']==b['trajectory_h5_sha256']==t['output_sha256'];assert xm['case_id']==b['case_id'] and (xm.get('attempt_id') or xm.get('root_actual_XMF_attempt_id'))==b['xmf_attempt_id'] and rc['request']['attempt_id']==b['xmf_attempt_id'];assert xm['physical_condition_sha256']==b['physical_condition_sha256'] and xm['source_h5_physical_condition_sha256']==b['source_h5_physical_condition_sha256'];assert Path(b['trajectory_h5']).is_file()
O=H/'root_stage1_F5_M086_actual963_XMF0_corrected161_original138_full801_bed_fairCPU2_969';O.mkdir(exist_ok=False);put(O/'prelaunch-schema-key-correction.json',{'first_preparation_error':'KeyError attempt_id on actual XMF manifest','actual_key':'root_actual_XMF_attempt_id','actual_receipt_request_attempt_id_independently_matches':True,'jobs_launched_by_failed_preparation':0,'science_payload_IO':False,'original_source':str('/tmp/ds02-root969-original-missing-attempt-key-preparation.py')});(O/'original-missing-attempt-key-preparation.py').write_bytes(Path('/tmp/ds02-root969-original-missing-attempt-key-preparation.py').read_bytes());gate=O/'metadata-original-gate-preflight.py';gate.write_text("from pathlib import Path\nimport sys,json,runpy\nm=runpy.run_path(sys.argv[1])\nb=m['validate_binding'](Path(sys.argv[2]))\no=m['_load_original']()\nm['_bind_original_case_id'](o,b)\nr=o._verify_bound_metadata(b)\nPath(sys.argv[3]).write_text(json.dumps(r,indent=2)+'\\n')\nprint(json.dumps({'real_original_metadata_gate':'pass','case_id':r['case_id'],'scientific_payload_IO':False}))\n");s=subprocess.run([str(L/'.venv/bin/python'),str(gate),str(worker),str(bp),str(O/'actual161-original-gate-to-real963-XMF.json')],capture_output=True,text=True);put(O/'actual-metadata-preflight-result.json',{'returncode':s.returncode,'stdout':s.stdout,'stderr':s.stderr,'main_science_payload_IO':False});assert s.returncode==0,(s.stdout,s.stderr)
controller=O/'fair-bed-controller.py';controller.write_bytes((root(963)/'fair-XMF-controller.py').read_bytes());fair=root(928)/'fair_CPU_dispatch.py';aid='root-stage1-f5-m086-t085-actual963-full801-original138-bed-adapter161-root969';ar=D/'families/F5'/b['case_id']/aid;assert not ar.exists();md=q['input_sha256'].copy()
for p,d in md.items():assert sha(p)==d
for p in [bp,controller,fair,O/'actual-metadata-preflight-result.json',O/'actual161-original-gate-to-real963-XMF.json',root(962)/'actual161-adoption-and-main-regression-review.json']:md[str(p)]=sha(p)
md[b['trajectory_h5']]=t['output_sha256'];base=load(root(963)/'enabled-XMF-request.json');q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','science_input_policy']});q.update(attempt_id=aid,attempt_root=str(ar),binding=str(bp),binding_sha256=sha(bp),command=[str(L/'.venv/bin/python'),str(worker),'--binding',str(bp),'--trajectory-h5',b['trajectory_h5'],'--xdmf',b['xdmf'],'--output-dir','{attempt_root}/audit-output'],input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,full801_authorized=True,case_credit=0);qp=O/'enabled-bed-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(fair),'case_credit':0});put(O/'source163-adoption-and-main-review.json',{'source_commit':subprocess.check_output(['git','rev-parse',commit],cwd=W,text=True).strip(),'adopted_files':adopted,'source_byte_exact':True,'real_original138_metadata_gate_with_CASE_ID_rebind_passed':True,'binding_bytes_unchanged':ref(bp),'binding_execution_source_science_flags_unchanged':True,'outer_runner_only_authorizes_actual801_bed_audit':True,'source_H5_SHA_from_producer_report_only':True,'main_science_payload_IO':False,'case_credit':0,'no_precision_claim':True});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(p['path']).relative_to(R)) for p in adopted]+[str(p.relative_to(R)) for p in O.iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register M086 real full801 bed audit after actual XMF identity gate','--',*paths],cwd=R,check=True);print({'root':str(O),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'actual_metadata_gate':s.stdout.strip()})
