from pathlib import Path
import json,hashlib,datetime,shutil,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.jsonl','.py','.xml','.xmf','.log','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_222_visual_F4full48_failed439GiB_cleanup_verified_F5_GPU11_F2typed20_F3downstream_checkpoint_1021';O.mkdir(exist_ok=False);cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_146.json');assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==222 and cp['accepted_per_family']['F4']==48
cleanup=O/'actual-failed-native-cleanup-reverified-439GiB.json';cleanup.write_bytes(Path('/tmp/ds02-failed-cleanup-20261006T1725-verification.json').read_bytes());a=load(cleanup);assert a['actual_deleted_files']==a['deleted_files_still_absent']==15995 and a['actual_failed_attempts_cleaned']==14 and not a['new_failed_attempts_with_native_frames'] and all(a['receipts_and_plan_unchanged'].values())
observations=[]
for n in [951,972,978,983,984,987,988,991,998,1002,1003,1004,1006,1008,1009,1010,1012,1013,1014,1015,1016,1017,1020]:
 o=root(n);e={'root':n,'live':False,'case_credit':0}
 for p in o.glob('*launch*.json'):
  x=load(p)
  if not isinstance(x,dict) or not x.get('pid'):continue
  st=Path(f"/proc/{x['pid']}/stat")
  if st.exists():
   f=st.read_text().split(') ',1)[1].split()
   if f[0]!='Z' and f[19]==str(x.get('proc_start_ticks',x.get('start_ticks'))):e.update(live=True,pid=x['pid'],start_ticks=f[19],actual_launch_receipt=ref(p))
 for name in ['actual-progress.json','controller-result.json']:
  p=o/name
  if p.exists():
   z=O/f'root{n}-{name}-frozen.json';z.write_bytes(p.read_bytes());e[name]=ref(z)
 if n>=1012 and (o/'controller-config.json').exists():
  c=load(o/'controller-config.json');rr=[]
  for qp in c.get('requests',[]):
   q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json'
   if rp.exists():
    r=load(rp);row={'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':ref(qp),'actual_receipt':ref(rp),'status':r['status'],'returncode':r.get('returncode'),'case_credit':0}
    if n==1017:row.update(gpu=r.get('gpu'),native_saved_frame_file_count=len(list((rp.parent/'solver_output/data').glob('Part_[0-9]*.bi4'))))
    rr.append(row)
  e['actual_registered_scientific_receipts']=rr
 observations.append(e)
put(O/'actual-producer-and-live-handle-observation.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'processes':observations,'original1012_dispatch_never_occurred':True,'original1012_syntax_failure_preserved':ref(root(1016)/'actual1012-pre-dispatch-terminal-failure-and-controller-only-repair.json'),'old850_and871_conclusively_terminal_before_new1017':True,'no_live_scientific_worker_restart':True,'scientific_payload_IO':False,'case_credit':0})
put(O/'current_registered_downstream-summary.json',{'F5_original138_full801_bed_three_corrected_controller1016':ref(root(1016)/'controller-config.json'),'F5_genuinely_missing_native11_no_completed_case_rerun':ref(root(1017)/'source170-adoption-independent11-native-absence-and-own-input-review.json'),'F2_existing_native0_typed12_source140':ref(root(1013)/'source140-adoption-twelve-actual812-native-independent-review.json'),'F2_remaining_existing_native0_typed8_source142':ref(root(1020)/'source142-adoption-eight-actual812-native-independent-review.json'),'F3_source128_three_actual_typed0_XMF_full836':ref(root(1014)/'source128-adoption-three-actual978991-independent-QI-review.json'),'F3_actual1002_XMF0_to_complete836_render':ref(root(1015)/'actual1002-full836-XMF-and978-typed-independent-review.json'),'actual_F3_two_full836_new_visuals':ref(root(1018)/'source129-adoption-two-full836-independent-QI-and-visual-review.json'),'actual_F4_three_full1201_last_visuals_F4now48':ref(root(1019)/'adoption-and-three-case-independent-review.json'),'all_registered_conversion_outputs_Home4GiB_cap_and_original142':True,'all_full_render_outputs_Home_bounded_and_shared2':True,'Q_N_Q_E_not_granted':True,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);a=json.loads(raw);free=shutil.disk_usage('/home/jade').free;assert free>=500*2**30;cp.update(checkpoint=147,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_146.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_146.json'),new_accepted_decisions=[],home_free_gib=free/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),active_reservations=a['reservations'],attempt_counts={k:sum(v['kind']==k for v in a['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(v.get('gpu_seconds',0) for v in a['charges'])/3600,cpu_core_hours_charged=sum(v.get('cpu_core_seconds',0) for v in a['charges'])/3600,previous_goal_turn_classification='Progress: exact failed439GiB cleanup remains verified, no new failed native frames. Five more true complete visuals accepted to222, including F4 full48. Additional3 typed0 F3 XMF1014 and full836 render1015 admitted; F5 three bed1016 corrected only pre-dispatch controller syntax and tag metadata, original kernel unchanged; F2 all remaining20 existing native0 now typed12+8 bounded requests1013/1020 admitted; F5 missing11 fully producer-bound native1017 queue launched, six actual shared GPU leased workers running. No budget reset or precision grant.')
cp['actual_progress']['storage439GiB_recovery_F4full48_222_visual_shared_native_and_bounded_downstream']=ref(O/'current_registered_downstream-summary.json');cp['actual_progress']['actual_process_handles_and_frozen_producer_results']=ref(O/'actual-producer-and-live-handle-observation.json');cp['actual_progress']['storage_cleanup_reverification']=ref(cleanup)
cp['source_agents']={'f5_bed_recovery':'fresh170 exact adopted1017/native11 launched; fresh171 real972 full801 personal34contacts7keys bed0 ready for primary independent closure; fresh172 actual984 personal plus1016 bed observation and1017 genuine native0 typed successors active','f6_endpoint_initial_qa':'fresh141 exact adopted1019 all1201 times/N3/UID/raw velocity independently accepted, F4=48; fresh142 exact adopted1020 remaining8 F2 typed157 registered, prospective scope derived only from immutable converter metadata helper actual scope left null; fresh143 F6 realfull241 angular/state closure and personal visual active','production_recovery':'fresh128 exact adopted1014 three genuine typed0 full836 original104 XMF admitted; fresh129 realexisting full836 legacy/canonical two cases personally reviewed and primary closed1018 accepted, wrong duplicate source chain ref preserved and grounded sidecar; fresh130 oldest first24 real pipeline gaps and next personal/XMF handoff active'}
cp['next_executable_tasks']=['Adopt fresh171 actual972 M086T085 full801 originalbed0 visual package, independently verify all801 thresholds, exact times, same UID axis and real render receipts before raising222.','Observe existing984 full801 M095T080 render and new1016 three original138 bed jobs; no restart for quiet or queued handles. Only actual bed0 full801 independent negative-aware closure enables next116023 render.','Observe six actual1017 GPU leased F5 workers and pending five fair native requests. Only true native801 completed0 may produce fresh172 typed successor, no scientific failed or completed attempts rerun.','Integrate fresh143 F6 full241 only true angular-state0, actual independent typed H5 audit and personal contacts/keys, preserve all omission and physical/native mass-role distinctions.','F2 remaining20 known native0 now12+8 CPU2 globalserial1 typed1574GiB; only actualtyped0 bind unchanged108/104 N3 XMF then full401 bounded render. Existing995→1007→1009 remains same process, no duplicate.','F3 realtyped97812 completed0 and991 correctdecoder repairs continue; existing1002/1010/1014 XMF original104, existing987/1003/1004/1015 full836 renders continue. New actual0 only enables nextstage.','Use fresh130 authoritative full48 actualcensus to fill oldP1000 first24 gaps, preserving mother alias and no duplicate physical-case credit; complete336goal remains active, numerical Q-N/Q-E still0.','Failed unused intermediate cleanup done439GiB; preserve complete accepted/pending/live reusable products and failure receipts/header/first-last evidence, maintain Home500GiB minimum.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_147.json',cp);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_147.json').relative_to(R))]
for n in [1013,1014,1015,1016,1017,1020]:paths.extend(str(p.relative_to(R)) for p in root(n).glob('*launch*.json'))
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: checkpoint222 F4full48 cleaned439GiB and actual fair F5 GPU F2 bounded downstream','--',*paths],cwd=R,check=True);print({'accepted':222,'counts':cp['accepted_per_family'],'home_free_GiB':cp['home_free_gib'],'gpu_h_charged':cp['gpu_hours_charged'],'CPU_core_h_charged':cp['cpu_core_hours_charged'],'attempts':cp['attempt_counts'],'live_roots':[v['root'] for v in observations if v['live']],'actual_native1017_receipts':len(next(v for v in observations if v['root']==1017)['actual_registered_scientific_receipts']),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
