from pathlib import Path
import json,hashlib,subprocess,copy,collections,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='204a65d3858c2663496cb5b87f5634629ef0ea66';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_181_f5_m114_t095_root1177_personal_visual_acceptance_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==3;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh181.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/personal-visual-decision.json');ev=s['evidence'];qip=root(1282)/'actual1177-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip);c=s['case'];pid=c['physical_case_id'];cid=c['case_id'];assert (pid,cid)==(qi['physical_case_id'],qi['case_id']);assert s['actual_family']=='F5' and s['assigned_family']=='F6' and s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max';assert s['decision']['status']=='visual-approved-by-delegated-agent' and s['decision']['case_credit']==0 and not s['decision']['global_acceptance'] and not s['decision']['q_n_granted'] and not s['decision']['q_e_granted'];assert ev['main_process_qi_proof']['path']==str(qip) and ev['main_process_qi_proof']['sha256']==sha(qip)
for k,e in ev.items():
 assert sha(e['path'])==e['sha256'] and Path(e['path']).stat().st_size==e['bytes']
for k,e in qi['actual_completed_metadata_evidence'].items():
 sourcekey={'render_publish_receipt':'publish_receipt'}.get(k,k);a=ev[sourcekey];assert a['path']==e['path'] and a['sha256']==e['sha256'];assert sha(e['path'])==e['sha256']
 if k.endswith('_receipt') and k!='render_publish_receipt':r=load(e['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid
canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];source=qi['actual_SourceDef']['sha256'];assert canonical==c['canonical_native_physical_condition_sha256']==c['actual_native_source_plan_physical_condition_sha256'] and legacy==c['typed_legacy_and_actual_converter_scope_sha256'] and source==c['xmf_source_plan_and_SourceDef_sha256'];assert len({canonical,legacy,source})==3 and qi['actual_native_source_plan_condition_field_present'] and qi['actual_native_source_plan_condition_sha256']==canonical and qi['XMF_source_plan_condition_field_sha256']==qi['bed_declared_source_plan_field_sha256']==source
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all_native_UIDs_active_each_frame'] and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'];assert c['actual_time_s']==qi['actual_time_window_s'] and c['declared_counts']=={'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'total':194427}
vr=s['visual_review'];contacts=vr['contact_sheets'];keys=vr['key_frames'];assert vr['personally_viewed_with']=='view_image' and len(contacts)==34 and len(keys)==9 and [e['sheet_index'] for e in contacts]==list(range(34)) and [e['frame'] for e in keys]==list(range(0,801,100));pub=load(ev['publish_receipt']['path']);report=load(ev['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==ev['render_report']['sha256'];out=Path(pub['published_output_root']);published={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==report['outputs']['contact_sheets']
for e in contacts+keys:
 p=Path(e['path']);a=published[str(p.relative_to(out))];assert sha(p)==e['sha256']==a['sha256'] and p.stat().st_size==e['bytes']==a['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_234.json';cp=load(cpfile);assert cp['checkpoint']==234 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==291 and cp['accepted_per_family']['F5']==22;assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};ip=root(1288)/'full336-current291-actual-final48-delivery-progress-index.json';idx=load(ip);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;ss=os.statvfs('/home/jade');free=ss.f_bavail*ss.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720;now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(vr['review_completed_at_utc'].replace('Z','+00:00'))<=now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source181_assignedF6_actualF5_M114T095_actual1177_full801QI_personal43PNG_distinct_native_XMF_SourceDef_visual_acceptance_1290';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_235.json';assert not list(H.glob('root*_1290')) and not nextcp.exists();O.mkdir();adopted=[]
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
vp=O/'source181-byte-exact-readonly-validator-and-main43publishedPNG-proof.json';put(vp,{'source_commit':commit,'source_files':adopted,'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'source_assigned_family':'F6','actual_family':'F5','main_all43_png_bound_to_atomic_publish':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_SourceDef_scope_sha256':source,'source_review_commit':commit,'source_review_assigned_family':'F6','actual_review_family':'F5','source_visual_review':ref(R/prefix/'metadata/personal-visual-decision.json'),'independent_full801_QI':ref(qip),'actual_completed_metadata_evidence':qi['actual_completed_metadata_evidence'],'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_type_counts':c['declared_counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_and_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_bins_are_diagnostics_not_precision_thresholds':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'actual_native_plan_field_present':True,'actual_native_plan_field_value':canonical,'actual_XMF_plan_field_value':source,'actual_bed_plan_field_value':source,'canonical_legacy_SourceDef_roles_are_distinct':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':vr['observations'],'visual_limits':s['lifecycle_and_limits'],'no_strong_runup_or_inundation_magnitude_claim_from_visual_screen':True,'source_personal_visual_decision':s['decision'],'original_AB_penetration_and_precision_negatives_preserved_by_predecessor_and_own_QI':True,'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source181-actual1177-full801QI-personal-visual-adoption.json';put(proof,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'actual43PNG_bound_to_atomic_publish':True,'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=1;new.update(checkpoint=235,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=292,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source202 actual1156 accepted291; source166 remaining9F3 readiness adopted; own1177 full801QI1282 and source181 personal43PNG now accepted292/F5=23. Native plan canonical differs XMF/bed SourceDef roles preserved, no scientific payload IO. Original1127 and1099 PV rendering, lastF6 original951 live waiting CPU/render-cap admission.',authorized_work_state='Active292/336,44 pending. F1/F4/F7=48,F2/F3=39,F5=23,F6=47; original1127 personalfresh203 afterpublish, original1099 actualF2 personalfresh182 afterpublish; F6fullmotioncoverage fresh167.')
new['actual_progress']['source181_F5_actual1177_visual_acceptance']=ref(proof);new['source_agents']['f6_endpoint_initial_qa']='fresh181 actualF5 accepted F5=23; fresh182 actualF2 RX058ROT090 original1099 live then personal17contacts9keys';new['next_executable_tasks']=['After original1127 publication run prepared ownfull801QI1284 or unused1291 (1287 already used), adopt fresh203 personal43PNG and close F5 actual24 product.','After original1099 publication run prepared ownfull401QI1289 and adopt fresh182 personal17contacts9keys preserving quantified5fluid omissions.','Audit fresh167 existing fullF6 rigid-motion coverage and prepare needed separately named official export only if no full export evidence.','Continue exact original44 queues and periodic current-process checks without solver reruns; preserve Home500GiB floor.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==292;put(nextcp,new)
idx.update(previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nextcp),at_utc=now.isoformat(),accepted_independent_physical_cases=292,registered_pending_independent_physical_cases=44,new_case_credit=1);targets[0].update(status='visual-approved-in-checkpoint235',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qip));idx['actual_unaccepted_completed0_published_physical_cases']=[e for e in idx['actual_unaccepted_completed0_published_physical_cases'] if e['physical_case_id']!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==292;put(O/'full336-current292-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir()]+[str(nextcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 m114 t095 full801 preserving native versus XMF bed scope roles','--',*paths],cwd=R,check=True);print({'checkpoint':235,'accepted':292,'F5':23,'pending':44,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
