from pathlib import Path
import json, hashlib, subprocess, importlib.util, datetime, copy, collections, os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics'); W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics'); H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003'; D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02'); root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_180_f3_assigned_f5_completion_only_final48_fulltime_bed_primary_builder_v1'); P=W/prefix
commit=subprocess.check_output(['git','rev-parse','1e82b35a6'],cwd=W,text=True).strip()
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();expected={'build_fresh180.py','validate_fresh180.py','README.md','package-manifest.json','tests/test_fresh180_contract.py'};assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};val=['python3','-B',str(P/'validate_fresh180.py'),'--package',str(P)];rv=subprocess.run(val,capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr)
spec=importlib.util.spec_from_file_location('fresh180_audit',P/'build_fresh180.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
row={'family_id':'F5','case_id':'TOY','physical_case_id':'TOY_PHYSICAL'}
toy={'schema':'ds02.runner-request.v3','status':'completed','returncode':0,'request':row,'request_sha256':'toy','runner_source':'toy','runner_sha256':'toy','input_hashes_at_launch':{},'input_hashes_after_run':{}}
toy_request_result=m.status_gate(toy,'toy_not_execution_receipt',row);assert toy_request_result[0]
toy_t={'frames':1,'particles':2,'lifecycle':{'frame_summary':[{'frame':0,'active_particles':2,'missing_particles':0,'type_counts':{},'time':float('nan')}]}}
toy_x={'frames':1,'particles':2,'actual_time_s':[float('nan')],'fields':{}}
toy_r={'frame_diagnostics':[{'actual_time_s':float('nan')}]}; toy_d={'full_native_frames':1,'particle_count':2}
toy_shape_result=m.sequence_consistency(toy_t,toy_x,toy_r,{'time_values':[float('nan')]},toy_d,row);assert toy_shape_result[0]
toy_bed_result=m.bed_fulltime_gate({'frame_reports':[{}]*801,'time_provenance':{}},{'full_native_frames':801});assert toy_bed_result[0]
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_291.json';cp=load(cpfile);ip=root(1389)/'full336-current317-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);assert cp['accepted_per_family']['F5']==37
mp=root(1293)/'F5-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json';lp=root(1344)/'F5-FINAL48-CURRENT30ACCEPTED18PENDING-ACTUAL801-PRIMARY-BED-DELIVERY.json'
now=datetime.datetime.now(datetime.timezone.utc);O=H/'root_stage1_source180_F5_current37_readiness_metadata_schema_N3_finite_UID_bed_provenance_gate_defects_repair182_required_1390';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_292.json';assert not O.exists() and not np.exists();O.mkdir()
out=O/'current37-readiness';build=['python3','-B',str(P/'build_fresh180.py'),'--checkpoint',str(cpfile),'--current-index',str(ip),'--membership',str(mp),'--legacy-catalog',str(lp),'--output-dir',str(out)];br=subprocess.run(build,capture_output=True,text=True);assert br.returncode==0,(br.stdout,br.stderr)
vr=subprocess.run(val+['--output-dir',str(out)],capture_output=True,text=True);assert vr.returncode==0,(vr.stdout,vr.stderr);assert before=={n:sha(W/n) for n in names}
cat=load(out/'readiness.json');assert cat['accepted_count']==37 and cat['pending_count']==11 and not cat['complete'] and not (out/'final48.json').exists();gaps=[r for r in cat['cases'] if r['accepted'] and not r['fulltime_gate']['pass']]
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
pp=O/'source180-byte-exact-readonly-current37-assembly-and-final-gate-defect-audit.json'
put(pp,{'schema':'ds02.main.source180.F5.assembly-only-final-gate-defect-audit.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_sha':before,'full_builder_and_validator_read_by_main':True,'readonly_source_validator':{'command':val,'stdout':rv.stdout,'stderr':rv.stderr},'actual_current_readiness_build':{'command':build,'stdout':br.stdout,'stderr':br.stderr,'output':ref(out/'readiness.json'),'accepted':37,'pending':11,'accepted_rows_with_gate_gaps':len(gaps),'reason_counts':dict(collections.Counter(reason for r in gaps for reason in r['fulltime_gate']['reasons']))},'readonly_output_validator':{'stdout':vr.stdout,'stderr':vr.stderr},'toy_only_false_positive_gate_evidence':{'non_execution_schema_with_lookalike_fields_status_gate_accepted':toy_request_result[0],'missing_N3_shapes_and_nonfinite_time_sequence_accepted':toy_shape_result[0],'empty801_bed_frame_objects_and_empty_time_provenance_accepted':toy_bed_result[0],'no_actual_receipts_or_data_modified':True},'independently_identified_code_defects':['runtime status_gate never requires execution receipt schema; launch/after digests present but not actually joined','decision status prefix admits unrecognized visual-approved statuses; missing identity fields bypass comparison','typed UID composite/initial exclusion/introduced rejection/type ledger not gated','XMF XYZ/Vector shape and required field shape absence are not rejected; XML SHA is not joined to producer manifest/render','finite time/strict ordering/exact actual time not guaranteed; NaN can evade tolerance comparisons','render UID preserved/diagnostic-only/source-readonly flags not enforced; primary PNG presence and contact/key cardinality not gates','bed validates only801 list length and time_provenance object, not actual full bed UID/footprint diagnostics/time joins/SourceDef binding','initialQA report loaded but pass/case/particles/provenance not gated; genuine GC/QA often recoverable through typed source_provenance/native request','native canonical vs typedlegacy vs XMF plan masks vs bed SourceDef recorded but not validated independently','four true old publication-receipt absences must remain distinct from missing actual render; no new fabricated publication','empty existing output directory is reused instead of strict nonexistence guard'],'source180_approved_only_as_readiness_assembly':True,'source180_not_approved_as_standalone_final48_builder':True,'source180_completed_source_bytes_immutable':True,'fresh182_repair_required_after_current_personal_visual181':'Resolve actual primary refs from genuine provenance, enforce full801 UID/N3/finite/time/runtime/schema/case/QA/bed/roles with meaningful negative checks, immutable output and real future cp/index authority. No payload IO/jobs/shared mutation.','new_case_credit':0,'Q_N':0,'Q_E':0,'main_scientific_payload_IO':False,'PNG_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=292,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source215 accepted F5 once reaching317 in previous turn; actual full401 QI1385/full836 recovery-aware QI1387 completed and delegated source216/181 personal PNG reviews started. Source180 fullcode/current37-readiness audit proves schema/N3/nonfinite/bed false-positive gates and assigns separate182 repair; source195 complete and source196 F3 repair assigned.',authorized_work_state='Active317/336 pending19. F2original1097 and F3original1194 actual renders completed0/published, ownQIs1385/1387 complete; source216/181 personal reviews running. Source196 F3 final gate repair active. Source195 F2 final repair awaits main independent full audit; source180 F5 readiness only, separate182 final gate repair required.')
new['actual_progress']['source180_current37_assembly_only_gate_defect_audit']=ref(pp);new['actual_progress']['completed_ownQI1385']=ref(root(1385)/'actual1097-full401-own-QI-UID-N3-native-typed-role-three-fluid-omissions-previsual-proof.json');new['actual_progress']['completed_ownQI1387']=ref(root(1387)/'actual1194-full836-recovery-aware-QI-nativecanonical-typedlegacy-original154-unknown-previsual-proof.json');new['source_agents']['f6_endpoint_initial_qa']='fresh195 completed immutable; fresh196 F3 fulltime/runtime/actualprimary repair active'
new['next_executable_tasks']=['Adopt source216 F2original1097 and source181 F3original1194 after completed commits/read-only source validation/personal publishedPNG evidence/primary ownQI closure.','Assign fresh182 F5 actual full801/bed/runtime/primary gate repair after source181 completed; source180 remains immutable readiness assembly only.','Audit completed source195 F2 final gates and resolve actual accepted primary lookup gaps; audit source196 F3 repair after completion.','Observe actual next registered original F5/F2/F3 renders, prepare no-repeat ownQI against real next cases, delegate personal visuals once published.','Finish true F2/F3/F5 48-case deliveries and full336 objective audit without numerical precision claims; retain Home500GiB/budgets/deadline.'];put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,source180_current37_assembly_only_gate_defect_audit=ref(pp));put(O/'full336-current317-actual-final48-delivery-progress-index.json',idx);(O/'audit-source.py').write_bytes(Path(__file__).read_bytes())
paths=names+[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: audit F5 readiness final gates and bind completed F2 F3 integrity reviews','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':292,'accepted':317,'source180_F5_readiness':{'accepted':37,'pending':11,'accepted_gate_gaps':len(gaps)},'false_positive_gates':3,'proof':ref(pp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
