from pathlib import Path
import json,hashlib,datetime,copy,subprocess,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
cf=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_236.json';cp=load(cf);ip=root(1292)/'full336-current293-actual-final48-delivery-progress-index.json';idx=load(ip);fp=root(1293)/'F5-ACTUAL_FIRST24_DYNAMIC_DELIVERY.json';f=load(fp)
assert idx['source_authoritative_checkpoint']==ref(cf) and cp['stage1_visual_accepted_complete_independent_cases']==293 and cp['accepted_per_family']['F5']==24
assert f['stable_predecessor_acceptance_authority']==ref(cf) and f['source_full336_current_index']==ref(ip) and f['actual_first24_count']==f['canonical_native_request_conditions_distinct']==24 and f['first8_subset_actual24_subset_registered48'] and f['primary_contacts']==816 and f['primary_navigation_keys']==216 and f['new_case_credit']==0 and f['Q_N']==f['Q_E']==0
assert len(f['source_index_null_native_scope_recoveries'])==4
recovered=[]
for a in f['source_index_null_native_scope_recoveries']:
 rr=next(r for r in idx['cases'] if r['physical_case_id']==a['physical_case_id']);assert rr['native_request_scope']==a['prior_index_scope_preserved'] and rr['native_request_scope']['sha256'] is None
 nr=a['own_completed_native_scope']['actual_native_receipt'];assert sha(nr['path'])==nr['sha256'];n=load(nr['path']);assert n['status']=='completed' and n['returncode']==0 and n['request']['physical_case_id']==rr['physical_case_id'] and n['request']['physical_condition_sha256']==a['own_completed_native_scope']['sha256'];recovered.append(a)
 rr['prior_index_native_scope_absence_preserved']=rr['native_request_scope'];rr['native_request_scope']=a['own_completed_native_scope'];rr['own_native_scope_recovery_authority']=ref(fp)
now=datetime.datetime.now(datetime.timezone.utc);live=[]
for pid,ticks,target,total in [(483492,212587099,1131,801),(485641,212609825,1180,801),(4004579,207142232,951,None)]:
 p=Path('/proc')/str(pid)
 try:
  fields=(p/'stat').read_text().split(') ',1)[1].split();args=[b.decode(errors='replace') for b in (p/'cmdline').read_bytes().split(b'\0') if b];assert int(fields[19])==ticks
  v={'pid':pid,'start_ticks':ticks,'state':fields[0],'original_root':target,'confirmed_live_now':True,'command_line_sha256':hashlib.sha256((p/'cmdline').read_bytes()).hexdigest(),'private_PNG_contents_read_or_hashed':False}
  if '--output-dir' in args:
   op=Path(args[args.index('--output-dir')+1]);v.update(private_output_root=str(op),private_frame_filenames_count=len(list((op/'frames').glob('frame_*.png'))),expected_full_frames=total)
  live.append(v)
 except (OSError,AssertionError,ValueError) as e:live.append({'pid':pid,'original_root':target,'live_reprobe_failed':repr(e),'terminal_inferred':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
O=H/'root_stage1_F5_actual24_product_four_old_null_native_scopes_recovered_full336293_current_original_render_handles_checkpoint_1296';nf=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_237.json';assert not list(H.glob('root*_1296')) and not nf.exists();O.mkdir();proof=O/'F5actual24-product-membership-four-own-native-scope-recoveries-and-current-original-processes.json';put(proof,{'schema':'ds02.main.F5actual24.delivery-and-old-native-scope-recovery.v1','at_utc':now.isoformat(),'stable_prior_checkpoint':ref(cf),'actual24_product':ref(fp),'canonical_native_conditions_distinct':24,'frozen8_subset_actual24_subset_final48_verified':True,'actual_own_preview_bindings':{'contacts':816,'navigation_keys':216},'prior_null_native_scope_snapshots_preserved':recovered,'old_source_index_bytes_unchanged':True,'current_original_process_metadata':live,'source167_pending_lastF6_planned_manifest_absence_preserved':{'source_snapshot_not_patched':True,'actual_completed_chain_authority':ref(root(1283)/'actual-lastF6-full241-own-UID-N3-state0-scope-readiness-with-quantified3fluid-omissions.json')},'F6fulltime47rigid_history_gaps_authority':ref(root(1294)/'F6-final48-fulltime-rigid-state-delivery-evidence-audit.json'),'new_case_credit':0,'main_scientific_payload_IO':False,'numeric_reference_accepted':0})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);ncp=copy.deepcopy(cp);ncp.update(checkpoint=237,at_utc=now.isoformat(),predecessor=str(cf),predecessor_sha256=sha(cf),new_accepted_decisions=[],ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,home_free_gib=free,authorized_work_state='Active293/336; F5actual24 product delivered with frozen8 membership and24 own native conditions.43 visual reviews remain; original1131/1180 live; F6fulltime47 rigid export evidence gaps being addressed by fresh168.',previous_goal_turn_classification='PROGRESS: accepted fresh203 actual1127 F5total24/overall293; delivered actualF5first24 own801 XMF +816contacts216keys, recovered four old index null native scopes using actual typed producer solver receipts without patching history; fresh204 next1131 running.')
ncp['actual_progress']['F5_actual24_dynamic_delivery']=ref(fp);ncp['actual_progress']['F5actual24_four_old_null_native_scopes_and_current_live_processes']=ref(proof);ncp['source_agents']['production_recovery']='fresh167 actualF6 coverage independently adopted1294; fresh168 fulltime FloatingInfo export/inventory worker in progress';ncp['next_executable_tasks']=['Adopt fresh182 actualF2 original1099 full401 ownQI1289 + personal17contacts9keys, preserving five-fluid omissions.','Observe original1131 and1180 using confirmed live PID/ticks; run ownfull801QI on terminalpublication and continue fresh204/next personalreview.','Integrate fresh168 worker, register tiny PartFloatInfo.ibi4 input inventory if no producer fileSHA, then full241 official rigid-motion pilot and remaining46.','Extend actual F2/F3/F5/F6 final48 products as their original complete sequences and child personal reviews finish.'];put(nf,ncp)
idx.update(at_utc=now.isoformat(),previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nf),new_case_credit=0,actual_F5_first24_delivery=ref(fp),current_F5actual24_four_own_native_scope_recoveries=ref(proof),current_original_process_metadata=live);idx['native_request_field_digest_available']=sum(bool(r.get('native_request_scope',{}).get('sha256')) for r in idx['cases']);idx['native_request_field_digest_not_available']=len(idx['cases'])-idx['native_request_field_digest_available'];assert sum(bool(r.get('accepted_decision')) for r in idx['cases'])==293;put(O/'full336-current293-actual-final48-delivery-progress-index.json',idx);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(O.relative_to(R)),str(nf.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: attach F5actual24 delivery and recover four own native scope absences','--',*paths],cwd=R,check=True);print({'checkpoint':237,'accepted':293,'F5':24,'home_GiB':free,'GPU_h':gpu,'CPU_core_h':cpu,'native_scope_recoveries':len(recovered),'live':live,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
