from pathlib import Path
import json,hashlib,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));O=H/'root_stage1_F5_M095T080_actual808_first_NVMe4GiB_typed157_fair_serial_CPU2_939';O.mkdir(exist_ok=False);load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,indent=2)+'\n')
SCI={'.h5','.hdf5','.bi4','.ibi4','.csv','.dat','.vtk','.vtu','.npy','.npz'}
def sha(p):
 p=Path(p);assert p.suffix.lower() not in SCI;return hashlib.sha256(p.read_bytes()).hexdigest()
oldp=root(854)/'requests/M095_T080-typed-request.json';old=load(oldp);retire=root(938)/'metadata-only-conversion-waiters-retirement-proof.json';assert load(retire)['metadata_retired']==10;assert not Path(old['attempt_root']).exists()
P=L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_157_nvme_typed_home_cap_publish_cleanup_fix_v1';worker=P/'scripts/nvme_convert_home_capped_v2.py';assert sha(worker)=='37fe7eaff4405e9ba6d9b7f666a53d7c02ee65fc6f30992fc1a8fdb0d8a61b11';fair=root(928)/'fair_CPU_dispatch.py';aid='root-stage1-f5-m095_t080-actual808-full801-typed157-NVMe4GiB-root939';ar=D/'families/F5'/old['case_id']/aid;assert not ar.exists();rid='/'.join([old['family_id'],old['case_id'],aid]);direct=old['command'][old['command'].index('--')+1:];direct[direct.index('--output')+1]='{attempt_root}/trajectory.h5';direct[direct.index('--report')+1]='{attempt_root}/conversion-report.json';ix=direct.index('--validation-dir');del direct[ix:ix+2]
for k in ['--solver-receipt','--gencase-receipt']:
 rr=load(direct[direct.index(k)+1]);assert (rr['status'],rr['returncode'])==('completed',0)
controller=O/'first-typed-controller.py';controller.write_text('''from pathlib import Path
import json,runpy
O=Path(__file__).parent;cfg=json.loads((O/'controller-config.json').read_text());dispatch=runpy.run_path(cfg['fair_dispatch'])['dispatch'];p=dispatch(cfg['request'],serial_conversion=True);q=json.loads(Path(cfg['request']).read_text());ar=Path(q['attempt_root']);r=json.loads((ar/'execution-receipt.json').read_text()) if (ar/'execution-receipt.json').exists() else {};c=json.loads((ar/'conversion-report.json').read_text()) if (ar/'conversion-report.json').exists() else {};passed=(r.get('status'),r.get('returncode'))==('completed',0) and c.get('frames')==801 and c.get('particles')==194427 and c.get('partvtk_validation',{}).get('all_passed') is True and c.get('solver_dimension',{}).get('solver_dimension')==3 and c.get('storage_protocol',{}).get('planned_publish_bytes',2**63)<=4*1024**3
row={'actual_receipt':str(ar/'execution-receipt.json'),'status':r.get('status'),'returncode':r.get('returncode'),'launcher_returncode':p.returncode,'launcher_stdout_tail':p.stdout[-16384:],'launcher_stderr_tail':p.stderr[-16384:],'full801_typed_pass':passed,'case_credit':0,'no_H5_payload_IO_by_controller':True};(O/'controller-result.json').write_text(json.dumps(row,indent=2)+'\\n');print(json.dumps(row),flush=True);raise SystemExit(0 if passed else 1)
''');put(O/'controller-config.json',{'request':str(O/'enabled-first-typed-request.json'),'fair_dispatch':str(fair),'case_credit':0})
inputs=dict(old['input_sha256']);checked=skipped=0
for name,digest in inputs.items():
 p=Path(name);assert p.is_file()
 if p.suffix.lower() in SCI:skipped+=1;continue
 assert sha(p)==digest,(name,'old non-science binding changed');checked+=1
for p in [worker,P/'scripts/home_publish_math.py',oldp,retire,root(936)/'actual157-source-and-publication-adoption-review.json',fair,controller,O/'controller-config.json']:
 inputs[str(p)]=sha(p)
q={k:old[k] for k in ['schema','family_id','case_id','physical_case_id','physical_condition_sha256','root_prospective_legacy_scope_sha256','actual_counts','canonical_physical_scope','actual_native_dependency','depends_on_attempt','depends_on_attempts','expected_counts','expected_frames','expected_particles','expected_dimension','cpu_task_kind','kind','cpu_threads','max_wall_seconds','launch_owner','worktree_root','cwd','strict_dispatch_sha256','strict_dispatch_entrypoint','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256'] if k in old}
q.update(attempt_id=aid,attempt_root=str(ar),estimated_storage_bytes=4*1024**3,command=[str(L/'.venv/bin/python'),str(worker),'--staging-root','/tmp/ds02-nvme-typed-cache-root939','--staging-limit-bytes',str(24*1024**3),'--nvme-free-reserve-bytes',str(100*1024**3),'--home-publish-cap-bytes',str(4*1024**3),'--home-floor-bytes',str(500*1024**3),'--home-publish-headroom-bytes',str(2*1024**3),'--current-attempt-id',rid,'--',*direct],input_files=sorted(inputs),input_sha256=inputs,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,independent_case_count_increment=0,conversion_allowed=True,full801_authorized=True,root_distinct_successor_of_unlaunched_request=str(oldp),root_original_source_request_sha256=sha(oldp),root_actual_new_output_layout='flat existing attempt_root only',root_future_downstream_hashes_claimed=False)
assert q['kind']=='cpu' and q['cpu_threads']==2 and q['max_wall_seconds']==5400;put(O/'enabled-first-typed-request.json',q)
put(O/'metadata-only-preflight.json',{'source_worker157_sha256':sha(worker),'old_unlaunched854_request_preserved':True,'source_inputs_nonscience_hashed':checked,'science_attestations_retained_without_main_payload_IO':skipped,'actual_native_and_Gen_receipts_completed0':True,'actual_frames':801,'actual_N3_particles':194427,'Home_reservation_and_hard_publish_cap_GiB':4,'NVMe_private_limit_GiB':24,'NVMe_free_floor_GiB':100,'Home_floor_GiB':500,'Home_headroom_GiB':2,'full_reservation_id':rid,'Home_free_GiB':shutil.disk_usage('/home/jade').free/1024**3,'case_credit':0,'scientific_jobs_started':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());print({'request':str(O/'enabled-first-typed-request.json'),'CPU2':True,'science_main_IO':False})
