from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,xml.etree.ElementTree as ET,re,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.txt','.log','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
F=next(H.glob('root*_1183'))
if not (F/'controller-result.json').exists():
 print('WAIT: original1183 no authoritative terminal yet; no outputs or shared state written.');raise SystemExit(0)
old_review=load(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json');q=load(F/'enabled-full801-render-request.json');cr=load(F/'controller-result.json');assert (cr['status'],cr['returncode'])==('completed',0);z={'case_id':q['case_id'],'physical_case_id':q['physical_case_id']};cid=z['case_id'];rp=Path(cr['actual_receipt']);attempt=rp.parent
lineage={'case_id':cid,'physical_condition_sha256':old_review['source_canonical_scope'],'actual_converter_scope_sha256':old_review['actual_H5_legacy_scope'],'input_sha256':{}}
for k,orig in [('bed_receipt','actual_bed_receipt'),('bed_report','actual_bed_report'),('typed_receipt','actual_typed_receipt'),('typed_conversion_report','actual_typed_report'),('xmf_receipt','actual_XMF_receipt'),('xmf_manifest','actual_XMF_manifest')]:
 e=old_review[orig];assert sha(e['path'])==e['sha256'];lineage[k]=e['path'];lineage['input_sha256'][e['path']]=e['sha256']
ti=load(lineage['typed_conversion_report']);xi=load(lineage['xmf_manifest']);e=ti['source_provenance']['solver_receipt'];assert sha(e['path'])==e['sha256'];lineage['native_receipt']=e['path'];lineage['input_sha256'][e['path']]=e['sha256'];lineage.update(xdmf=xi['xdmf'],xdmf_sha256=xi['xdmf_sha256'],trajectory_h5_sha256_producer_attested=ti['output_sha256'])
bedq=load(lineage['bed_receipt'])['request'];b=load(bedq['binding']);refs={}
for key,lkey in [('bed_receipt','bed_receipt'),('bed_report','bed_report'),('native_receipt','native_receipt'),('typed_receipt','typed_receipt'),('typed_report','typed_conversion_report'),('xmf_receipt','xmf_receipt'),('xmf_manifest','xmf_manifest')]:
 path=lineage[lkey];expected=lineage['input_sha256'][path];assert sha(path)==expected;refs[key]={'path':path,'sha256':expected}
for key,bkey in [('gencase_receipt','gencase_receipt'),('initial_qa_receipt','initial_qa_receipt'),('initial_qa_report','initial_qa_report'),('generated_xml','canonical_generated_xml')]:
 path=b[bkey];expected=b[bkey+'_sha256'];assert sha(path)==expected;refs[key]={'path':path,'sha256':expected}
xml=lineage['xdmf'];assert sha(xml)==lineage['xdmf_sha256'];refs['xmf_xml']={'path':xml,'sha256':lineage['xdmf_sha256']};refs['render_receipt']=ref(rp);refs['render_report']=ref(attempt/'render/paraview-full-animation-report.json');refs['render_publish_receipt']=ref(attempt/'render/render-publish-receipt.json');pub=load(refs['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==refs['render_report']['sha256'];assert load(rp)['request_sha256']==sha(F/'enabled-full801-render-request.json')
source_def=ref(b['source_definition']);assert source_def['sha256']==b['source_definition_sha256'];up={'scope_roles':{'canonical_physical_owner_sha256':lineage['physical_condition_sha256'],'actual_converter_legacy_scope_sha256':lineage['actual_converter_scope_sha256'],'typed_h5_sha256_producer_attested_only':lineage['trajectory_h5_sha256_producer_attested']}}
receipts={k:load(refs[k+'_receipt']['path']) for k in ['gencase','initial_qa','native','typed','xmf','bed','render']};assert all((r['status'],r['returncode'])==('completed',0) for r in receipts.values());assert all(r['request']['case_id']==z['case_id'] for r in receipts.values())
t=load(refs['typed_report']['path']);x=load(refs['xmf_manifest']['path']);r=load(refs['render_report']['path']);bed=load(refs['bed_report']['path']);qa=load(refs['initial_qa_report']['path']);pid=z['physical_case_id'];canonical=receipts['native']['request']['physical_condition_sha256'];actual=t['hash_scopes']['physical_condition_sha256'];assert pid==receipts['native']['request']['physical_case_id']==t['hash_scopes']['physical_condition']['physical_case_id']==x['physical_case_id']==bed['bound_actual_inputs']['physical_case_id'];assert canonical==x['physical_condition_sha256']==x['canonical_physical_condition_sha256']==bed['physical_condition_sha256']==up['scope_roles']['canonical_physical_owner_sha256'];assert actual==x['source_h5_physical_condition_sha256']==bed['source_h5_physical_condition_sha256']==up['scope_roles']['actual_converter_legacy_scope_sha256'];assert t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0'
assert qa['all_basic_placement_checks_pass'] and all(qa['checks'].values()) and not qa['numerical_precision_result_accepted'];assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']) and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected';assert t['solver_dimension']['solver_dimension']==3
for key in ['gencase_receipt','solver_receipt','generated_xml','owner_metadata']:
 p=t['source_provenance'][key];assert sha(p['path'])==p['sha256']
assert t['source_provenance']['solver_receipt']==ref(refs['native_receipt']['path']);assert t['source_provenance']['gencase_receipt']==ref(refs['gencase_receipt']['path']);assert t['source_provenance']['generated_xml']==ref(refs['generated_xml']['path'])
assert t['frames']==x['frames']==r['frames']==r['source_frames']==len(bed['frame_reports'])==bed['scan']['frames_scanned']==801 and t['particles']==x['particles']==bed['scan']['particle_axis_count']==194427;assert bed['scan']['initial_fluid_uid_count']==31658 and bed['status']=='completed_worker_output_pending_root_review' and not bed['source_arrays_modified'] and not bed['source_arrays_dropped_or_masked']
h5=t['output_hdf5'];assert Path(h5).is_file() and t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256']==up['scope_roles']['typed_h5_sha256_producer_attested_only']
for key in ['xmf','bed','render']:
 rr=receipts[key];assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
xml=refs['xmf_xml']['path'];assert sha(xml)==x['xdmf_sha256']==r['xdmf_sha256_before']==r['xdmf_sha256_after'] and sha(refs['xmf_manifest']['path'])==r['manifest_sha256'];assert r['frame_selection']==list(range(801)) and r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['source_h5_read_only'] and r['nonfinite_active_states']==0
fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==801;assert times==[f['time'] for f in fs]==[d['actual_time_s'] for d in ds]==[f['time_s'] for f in bed['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=16 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
for i,(f,d,g,bf) in enumerate(zip(fs,ds,grids,bed['frame_reports'])):
 assert f['frame']==d['frame']==bf['frame']==i and f['active_particles']==d['active']==194427 and f['missing_particles']==d['missing']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';vv=next(a for a in g.findall('Attribute') if a.get('Name')=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='194427 3'
 assert bf['initial_fluid_uid_count']==bf['current_valid_type3_fluid_count']==bf['finite_mass_current_fluid_count']==bf['finite_position_current_fluid_count']==31658 and bf['uid_tracking']['missing_initial_uid']['count']==bf['uid_tracking']['unexpected_current_uid']['count']==bf['nonfinite_mass_current_fluid_count']==bf['nonfinite_position_current_fluid_count']==0 and not bf['uid_tracking']['unexplained'];assert bf['bed_domain']['x_outside_exact_profile_domain_count']==bf['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']==bf['penetration']['depth_unevaluable_current_fluid_count']==0
 for k,threshold in [('one_dp',.02),('two_dp',.04)]:assert bf['penetration'][k]['threshold_m']==threshold and bf['penetration'][k]['count']==0 and bf['penetration'][k]['deepest_depth_m'] is None
assert bed['source_plan_physical_condition_sha256']==source_def['sha256'];assert 'source_plan_physical_condition_sha256' not in receipts['native']['request'];assert x['source_plan_physical_condition_sha256']==source_def['sha256'];assert len(r['outputs']['contact_sheets'])==34 and sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(801)]
for rec in bed['bound_actual_inputs']['records']:assert sha(rec['path'])==rec['sha256']
O=H/'root_stage1_F5_M105T100_actual1183_full801_complete_QI_UID_N3_bed_scope_previsual_checkpoint_1250';O.mkdir(exist_ok=False);proof=O/'actual1183-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';put(proof,{'case_id':cid,'physical_case_id':pid,'actual_completed_metadata_evidence':refs,'full_frames':801,'particles':194427,'fluid_initial_UIDs':31658,'all801_geometry_velocity_N3_times_UID_finite_verified':True,'all_native_UIDs_active_each_frame':True,'all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked':True,'depth_diagnostic_bins_not_numerical_thresholds':True,'subDP_positive_depth_not_quantified_by_zero_bins':True,'canonical_actual_native_request_condition_sha256':canonical,'actual_converter_legacy_scope_sha256':actual,'actual_native_source_plan_condition_sha256':None,'actual_native_source_plan_condition_field_present':False,'actual_native_source_plan_field_absence_not_filled_from_XMF_or_SourceDef':True,'XMF_source_plan_condition_field_sha256':x['source_plan_physical_condition_sha256'],'XMF_source_plan_condition_field_has_SourceDef_role':True,'actual_SourceDef':source_def,'bed_declared_source_plan_field_sha256':bed['source_plan_physical_condition_sha256'],'bed_declared_source_plan_field_has_SourceDef_role':True,'actual_time_window_s':[times[0],times[-1]],'actual_initial_QA_precision_negative':qa['numerical_precision'],'historical_negative_flags':{'original_binding':ref(bedq['binding']),'original_binding_explicit_AB_retention_field_present':'historical_A_B_penetration_failures_retained' in b,'original_binding_explicit_precision_retention_field_present':'historical_precision_negative_retained' in b,'actual_initial_QA_precision_not_accepted':True,'historical_source_scope_values_preserved':b['scope_roles']},'published_contacts':34,'visual_status':'pending source197 personal34contacts9keys','original1183_previsual_dependency_review':ref(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json'),'normalized_lineage_is_new_main_view_not_original_source_mutation':True,'new_case_credit':0,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_214.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==278 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_215.json').exists()
assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500
cp.update(checkpoint=215,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='PROGRESS: preceding214 accepted278/F3=37. Newly completed original1183 F5M105T100 full801 native UID N3 finite time bed-footprint scope QI closed; sharedmother case_id is not duplicatephysicalID; native source_plan_condition field is truly absent, XMF/bed field declares SourceDef hash. No visualcredit until personal197.',authorized_work_state='Active278/336. F5original1183 completed0 full801 QI awaits personal197 review; F2original1169 real401 rendering. LastF6original951 unchanged originalhandle, faircapacity guards preserved. F3fresh157 freezes actualfirst24 from immutable8 and realaccepted decisions. Numericalprecision unaccepted; no duplicate scientific job.')
cp['actual_progress']['actual1183_F5_full801_previsual_QI_verified']=ref(proof);cp['next_executable_tasks'][0]='Adopt fresh196 M105T100 actual1183 personal34contacts9keys if visual-approved; main full801QI closed1245. Continue original1100/1183 currentrender handles without restarts.'
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_215.json';put(newcp,cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R)),str((F/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close original F5 M105 T100 full801 integrity preserving native absent plan field','--',*paths],cwd=R,check=True);print({'accepted':278,'checkpoint':215,'actual1183_full801_QI_verified':True,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
