from pathlib import Path
import json,hashlib,subprocess,datetime,os,re,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.xml','.xmf','.png','.py','.md','.log','.txt'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_164_f2_rx058_rot105_delegated_visual_acceptance_v1';commit='7a94ed643433130246b06237924ce3fdaaaae87b';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==10
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw)
P=W/prefix;O=H/'root_stage1_source164_F2_RX058ROT105_actual1120_full401_independent_UID_scope_lifecycle_visual_acceptance_1206';O.mkdir(exist_ok=False);before={name:sha(W/name) for name in names};vld=P/'scripts/validate_fresh164.py';rv=subprocess.run(['python3','-B',str(vld)],capture_output=True,text=True);put(O/'actual-original164-readonly-validator.json',{'validator':ref(vld),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr});assert rv.returncode==0 and before=={name:sha(W/name) for name in names}
binding=load(P/'metadata/source-binding.json');original_decision=load(next((P/'decisions').glob('*-decision.json')));vr=load(P/'metadata/visual-review.json');png=load(P/'metadata/png-evidence.json');cid=binding['reviewed_case']['case_id'];pid=binding['reviewed_case']['physical_case_id'];assert cid==original_decision['case_id']==vr['case_id'] and pid==original_decision['physical_case_id']==vr['physical_case_id'];assert original_decision['case_credit']==0 and not original_decision['global_acceptance']
meta={a['role']:a for a in binding['producer_metadata']};
def m(role):
 a=meta[role];assert sha(a['path'])==a['sha256'];return {'path':a['path'],'sha256':a['sha256']}
s={
'genuine_gencase':{'stage':'genuine_gencase','receipt':m('genuine GenCase execution receipt'),'generated_xml':m('generated XML')},
'initial_native_qa':{'stage':'initial_native_qa','receipt':m('actual initial QA execution receipt'),'report':m('actual initial QA report')},
'full_native_solver':{'stage':'full_native_solver','receipt':m('actual full401 native execution receipt')},
'typed_conversion':{'stage':'typed_conversion','receipt':m('actual typed conversion receipt'),'report':m('actual typed conversion report')},
'n3_xmf':{'stage':'n3_xmf','receipt':m('actual N3 XMF execution receipt'),'manifest':m('actual N3 XMF manifest'),'xmf_xml':m('actual N3 XMF XML')},
'full_render_root1120':{'stage':'full_render_root1120','receipt':{'path':next(a['path'] for a in load(P/'metadata/chain-integrity.json')['metadata_chain'] if a['role']=='renderer'),'sha256':next(a['sha256'] for a in load(P/'metadata/chain-integrity.json')['metadata_chain'] if a['role']=='renderer')},'animation_report':m('actual full401 renderer report'),'publish_receipt':m('actual atomic publish receipt')}}
assert vr['agent_personally_viewed_all_contacts_and_keys'] and png['all_pngs_read_with_view_image'];assert all(a['viewed_with_view_image'] for a in png['contact_sheets']+png['key_frames']);assert all(Path(a['path']).name==f"frame_{a['index']:04d}.png" for a in png['key_frames']);png={**png,'key_frames':[{**a,'frame':a['index'],'personally_viewed':a['viewed_with_view_image']} for a in png['key_frames']],'contact_sheets':[{**a,'personally_viewed':a['viewed_with_view_image']} for a in png['contact_sheets']]}
v={'status':original_decision['status'],'observations':vr['observations']};assert v['status']=='visual-approved-by-delegated-agent';assert original_decision['contact_sheet_count']==17 and original_decision['key_frame_count']==9
sc=binding['scope_roles'];c={'scope_separation':{'canonical_source_physical_condition_sha256':sc['source_plan_and_canonical_scope_sha256'],'actual_converter_legacy_scope_sha256':sc['actual_converter_scope_sha256'],'source_plan_scope_sha256':sc['source_plan_and_canonical_scope_sha256'],'source_original_scope_separation':sc},'lifecycle_omissions':original_decision['producer_limits']}
put(O/'new-main-source164-role-and-keyframe-alias-normalization.json',{'source_binding':ref(P/'metadata/source-binding.json'),'originals_unchanged':True,'source163_is_pattern_reference_not_current_case_review':binding['source_chain'],'actual_personal_review_source164':{'commit':commit,'decision':ref(next((P/'decisions').glob('*-decision.json')))},'scope_roles':c['scope_separation'],'derived_stage_refs':s,'derived_keyframes':png['key_frames'],'new_case_credit':0,'scientific_payload_IO':False})
receipts={}
for role,a in s.items():
 rr=a['receipt'];assert sha(rr['path'])==rr['sha256'];r=load(rr['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;receipts[role]=r
 for k in ['report','generated_xml','manifest','xmf_xml','animation_report','publish_receipt']:
  if k in a:assert sha(a[k]['path'])==a[k]['sha256']
t=load(s['typed_conversion']['report']['path']);x=load(s['n3_xmf']['manifest']['path']);r=load(s['full_render_root1120']['animation_report']['path']);qa=load(s['initial_native_qa']['report']['path']);checks=qa.get('audit',qa)['checks'];assert checks and all(checks.values());canonical=c['scope_separation']['canonical_source_physical_condition_sha256'];actual=c['scope_separation']['actual_converter_legacy_scope_sha256'];nq=receipts['full_native_solver']['request'];assert nq['physical_case_id']==pid and nq['physical_condition_sha256']==canonical
assert t['frames']==x['frames']==r['frames']==r['source_frames']==401 and t['particles']==x['particles']==418104 and t['solver_dimension']['solver_dimension']==3 and x.get('dimension',3)==3
assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
assert t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0' and t['hash_scopes']['physical_condition']['physical_case_id']==pid==x['physical_case_id'];assert actual==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']==x['actual_converter_legacy_scope_sha256'] and x['canonical_source_physical_condition_sha256']==canonical and canonical!=actual
assert t['source_provenance']['solver_receipt']==ref(s['full_native_solver']['receipt']['path']) and t['source_provenance']['gencase_receipt']==ref(s['genuine_gencase']['receipt']['path']) and t['source_provenance']['generated_xml']==ref(s['genuine_gencase']['generated_xml']['path'])
assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256'];h5=t['output_hdf5'];assert Path(h5).is_file();assert r['all_frames_rendered'] and r['actual_times_preserved_exactly'] and r['native_identity_axis_preserved'] and r['source_h5_read_only'] and r['nonfinite_active_states']==0 and not r['diagnostic_only'];assert r['manifest_sha256']==sha(s['n3_xmf']['manifest']['path']) and x['xdmf_sha256']==sha(s['n3_xmf']['xmf_xml']['path'])==r['xdmf_sha256_before']==r['xdmf_sha256_after']
for role in ['n3_xmf','full_render_root1120']:
 a=receipts[role];assert a['input_hashes_at_launch'][h5]==a['input_hashes_after_run'][h5]==t['output_sha256']
for key in ['generated_xml','owner_metadata']:
 a=t['source_provenance'][key];assert sha(a['path'])==a['sha256']
fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(s['n3_xmf']['xmf_xml']['path']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==401 and times==[f['time'] for f in fs]==[f['actual_time_s'] for f in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=4 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[401,418104,3];counts={'0':372840,'1':24150,'2':0,'3':21114}
for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
 assert f['frame']==d['frame']==i and f['active_particles']==d['active'] and f['missing_particles']==d['missing'] and f['active_particles']+f['missing_particles']==418104 and f['missing_type_counts'].get('3',0)==f['missing_particles'];assert all(f['type_counts'][k]+f['missing_type_counts'].get(k,0)==n for k,n in counts.items());assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='418104 3';vv=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='418104 3'
life={'final_missing_particles':fs[-1]['missing_particles'],'final_missing_fraction_initial_fluid':fs[-1]['missing_particles']/21114,'final_missing_id_first_producer_attested':fs[-1]['missing_id_first'],'final_missing_ids_sha256_producer_attested':fs[-1]['missing_ids_sha256'],'first_missing_frame':next(f['frame'] for f in fs if f['missing_particles']),'max_missing_per_frame':max(f['missing_particles'] for f in fs),'frames_with_any_missing_particle':sum(f['missing_particles']>0 for f in fs),'cumulative_particle_frame_omissions':sum(f['missing_particles'] for f in fs),'unknown_missing_locations_states_and_causes':True,'omission_frame_events_not_unique_final_UID_count':True,'all_fixed_moving_floating_native_UIDs_active_every_frame':True,'original_source_omission_report':c['lifecycle_omissions']};assert life['final_missing_particles']==4 and life['max_missing_per_frame']==4 and life['frames_with_any_missing_particle']==236 and life['cumulative_particle_frame_omissions']==791 and life['first_missing_frame']==165;derived=load(P/'metadata/producer-limits-derived.json')['derived'];assert derived['actual_conversion_report_sha256']==sha(s['typed_conversion']['report']['path']);assert derived['final_missing_particles']==life['final_missing_particles'] and derived['frames_with_any_missing_particles']==life['frames_with_any_missing_particle'] and derived['particle_frame_omissions_sum']==life['cumulative_particle_frame_omissions'] and derived['first_missing_frame']==life['first_missing_frame'];assert c['lifecycle_omissions']['final_missing_particles']==4 and c['lifecycle_omissions']['frames_with_any_missing_particles']==236 and c['lifecycle_omissions']['particle_frame_omissions_sum']==791 and c['lifecycle_omissions']['maximum_missing_particles_single_frame']==4
nativefiles=[p.name for p in Path(t['source_provenance']['data_root']).glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name)];assert len(nativefiles)==401 and sorted(nativefiles)[-1]=='Part_0400.bi4';assert len(png['contact_sheets'])==17 and len(png['key_frames'])==9 and [a['path'] for a in png['contact_sheets']]==r['outputs']['contact_sheets']
assert [a['frame'] for a in png['key_frames']]==list(range(0,401,50));assert [Path(a['path']).name for a in png['contact_sheets']]==[f'all_frames_{i:03d}.png' for i in range(17)];pub=load(s['full_render_root1120']['publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(s['full_render_root1120']['animation_report']['path']);rq=ref(next(H.glob('root*_1120'))/'enabled-full401-render-request.json');assert sha(rq['path'])==rq['sha256']==receipts['full_render_root1120']['request_sha256'];framepaths=sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'));assert framepaths==[f'frame_{i:04d}.png' for i in range(401)]
for a in png['contact_sheets']+png['key_frames']:assert a['personally_viewed'] and sha(a['path'])==a['sha256']
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_186.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==269 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_187.json').exists();old=[load(p) for p in cp['accepted_decisions']];assert pid not in {a.get('physical_case_id',a['case_id']) for a in old}
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',next(H.glob('root*_142'))/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':v['status'],'family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':actual,'producer_scope_schema_verified_from_actual_report':'legacy-owner-scope.v0','source_review_commit':commit,'source_visual_review':ref(next((P/'decisions').glob('*-decision.json'))),'source_review_closure':ref(P/'metadata/source-binding.json'),'source_png_evidence':ref(P/'metadata/png-evidence.json'),'pattern_source163_reference_preserved_separately':binding['source_chain'],'scope_separation':c['scope_separation'],'manifest_dimension_alias_absent_preserved':('dimension' not in x),'actual_3D_proof':'actual GenCase/native/typed solver_dimension3 and all401 actual XMF geometry+velocity dimensions418104x3','lifecycle':life,'actual_completed_metadata_evidence':s,'full_native_frames':401,'particles':418104,'actual_physical_window_s':[times[0],times[-1]],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['observations'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1}
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500;assert sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600<=512 and sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600<=3840;assert sum(a['kind']=='qualification' for a in ledger['attempts'])<=1024 and sum(a['kind']=='production' for a in ledger['attempts'])<=720
dp=O/(pid+'-delegated-visual-decision.json');put(dp,decision);proof=O/'source164-full401-independent-QI-scope-lifecycle-and-visual-adoption.json';put(proof,{'source_commit':commit,'adopted_files':[ref(R/name) for name in names],'actual_source_validator':ref(O/'actual-original164-readonly-validator.json'),'new_accepted_decision':ref(dp),'previous_accepted':269,'new_accepted':270,'lifecycle':life,'main_scientific_payload_IO':False,'case_credit':1})
cp['accepted_per_family']['F2']+=1;cp.update(checkpoint=187,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),stage1_visual_accepted_complete_independent_cases=270,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: source164 actual1120 full401 F2RX058ROT105 personally17contacts9keys; ownGenQA/native/typed/XMF/render0 UID/N3/time/scope/publish closed. Actual final/max4 missingfluid /236frames /791particleframeevents /first165 unknowncause preserved. Accepted270/F2=33; precision unaccepted.',authorized_work_state='Active270/336, F2=33,F3=35,F5=11,F6=47,F1/F4/F7=48. Root1205 full336 role-aware registration preserved. Remaining66 registeredrenders and personalreviews; no duplicatedscience.')
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==270;cp['actual_progress']['fresh164_actual1120_F2_independent_acceptance']=ref(proof);cp['source_agents']['f6_endpoint_initial_qa']='fresh164 actual1120 accepted270/F2=33; fresh165 F2first8/24membership ornextactualpublished0 personalreview';cp['next_executable_tasks']=[z for z in cp['next_executable_tasks'] if 'fresh164' not in z]+['Fresh165 F2authoritativefirst8/24physicalmembership andnextpublished0unacceptedF2 personalreview','Remaining66 real render deliveries and personalvisualreviews; original951lastF6 remainsqueued, no restart']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_187.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_187.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 RX058 rotation105 full401 visual with exact omission limits','--',*paths],cwd=R,check=True);print({'accepted':270,'families':cp['accepted_per_family'],'omission_events':791,'Home_free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
