from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,collections,re,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
root=lambda n:next(H.glob(f'root*_{n:03d}'))
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_187.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==270 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_188.json').exists()
prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_190_f5_first8_first24_current48_membership_audit_v1');commit='0e1048a9a4c540fb81a82a190602c3bc41c2be9b';files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(files)==11
source_hashes={}
for rel in files:
 raw=subprocess.check_output(['git','show',commit+':'+rel],cwd=W);assert (W/rel).read_bytes()==raw;dst=R/rel
 if dst.exists():assert dst.read_bytes()==raw
 else:dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(raw)
 source_hashes[str(W/rel)]=sha(W/rel);source_hashes[str(dst)]=sha(dst)
P=W/prefix;rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh190.py')],cwd=P,text=True,capture_output=True);assert rv.returncode==0,rv.stderr;assert json.loads(rv.stdout)['all_checks_pass'];assert source_hashes=={p:sha(p) for p in source_hashes}
for s in load(P/'metadata/evidence-sources.json')['sources']:assert sha(s['path'])==s['sha256']
current=load(P/'metadata/current48-membership.json')['rows'];visual=load(P/'metadata/first8-visual-subset.json')['cases'];first24=load(P/'metadata/first24-source-set.json')['all_members'];key=lambda x:(x['physical_case_id'],x.get('physical_condition_sha256',x.get('key',{}).get('canonical_physical_condition_sha256')));currentkeys={key(x) for x in current};assert len(currentkeys)==48 and {key(x) for x in visual}<=currentkeys
accepted=[load(p) for p in cp['accepted_decisions']];a5={key(a) for a in accepted if a['family_id']=='F5'};assert len(a5)==11 and a5<=currentkeys
for a in visual:
 assert sha(a['decision_metadata_path'])==a['decision_metadata_sha256_declared'];assert key(load(a['decision_metadata_path']))==key(a) and key(a) in a5
old_roster=load(root(1205)/'full336-role-aware-physical-registration-progress-index.json');assert {a['physical_case_id'] for a in current}=={a['physical_case_id'] for a in old_roster['cases'] if a['family_id']=='F5'}
missing=[x for x in first24 if key(x) not in currentkeys];assert len(missing)==10
# Independently inspect completed actual F3 render metadata; visual credit awaits child.
F=root(1128);q=load(F/'enabled-full836-render-request.json');z=load(F/'actual1076-full836-XMF-and-producer-typed-independent-review.json');cr=load(F/'controller-result.json');assert (cr['status'],cr['returncode'])==('completed',0);cid=q['case_id'];pid=q['physical_case_id'];attempt=Path(cr['actual_receipt']).parent
s={'native':z['actual_native_receipt'],'typed':z['actual_typed_receipt'],'xmf':z['actual_XMF_receipt'],'render':ref(attempt/'execution-receipt.json')};receipts={}
for role,rr in s.items():
 assert sha(rr['path'])==rr['sha256'];n=load(rr['path']);assert (n['status'],n['returncode'])==('completed',0) and n['request']['case_id']==cid;receipts[role]=n
for key0 in ('actual_typed_report','actual_XMF_manifest','actual_XMF_XML'):assert sha(z[key0]['path'])==z[key0]['sha256']
t=load(z['actual_typed_report']['path']);x=load(z['actual_XMF_manifest']['path']);xml=Path(z['actual_XMF_XML']['path']);report=attempt/'render/paraview-full-animation-report.json';r=load(report);pub=attempt/'render/render-publish-receipt.json';pubj=load(pub);assert pubj['status']=='published_after_atomic_rename' and pubj['case_id']==cid and pubj['report_sha256_after_rebind']==sha(report)
assert t['frames']==x['frames']==r['frames']==r['source_frames']==836 and t['particles']==x['particles']==179208 and t['solver_dimension']['solver_dimension']==x['dimension']==3
assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(a['passed'] and a['identity_type_mk_exact'] for a in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
assert r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0 and not r['diagnostic_only'] and r['source_h5_read_only'];assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256'];assert r['manifest_sha256']==sha(z['actual_XMF_manifest']['path']);assert x['xdmf_sha256']==sha(xml)==r['xdmf_sha256_before']==r['xdmf_sha256_after'];h5=t['output_hdf5'];assert Path(h5).is_file()
for role in ('xmf','render'):assert receipts[role]['input_hashes_at_launch'][h5]==receipts[role]['input_hashes_after_run'][h5]==t['output_sha256']
for name in ('solver_receipt','gencase_receipt','generated_xml','owner_metadata'):
 a=t['source_provenance'][name];assert sha(a['path'])==a['sha256']
assert t['source_provenance']['solver_receipt']==s['native'];gc=load(t['source_provenance']['gencase_receipt']['path']);assert (gc['status'],gc['returncode'])==('completed',0)
o=load(t['source_provenance']['owner_metadata']['path']);nq=receipts['native']['request'];canonical=nq['physical_condition_sha256'];actual=t['hash_scopes']['physical_condition_sha256'];assert nq['physical_case_id']==pid==x['physical_case_id']==o['physical_case_id']==t['hash_scopes']['physical_condition']['physical_case_id'];assert t['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1' and canonical==actual==x['physical_condition_sha256']==o['physical_condition_sha256'];assert o['physical_binding']==nq['physical_binding']==t['hash_scopes']['physical_condition']
prep=o['root704_preparation_provenance'];assert sha(prep['original_report_path'])==prep['original_report_sha256'];prepared=load(prep['original_report_path']);assert prepared['xml_byte_identical_to_baseline'] and prepared['initial_bi4_byte_identical_to_baseline'] and prepared['physical_condition_sha256']==canonical and prepared['forcing_transform']['status']=='success';assert prepared['forcing_transform']['source_sha256_before']==prepared['forcing_transform']['source_sha256_after'];pp=nq['actual_preparation_receipt'];assert sha(pp['path'])==pp['sha256'];pr=load(pp['path']);assert (pr['status'],pr['returncode'])==('completed',0)
qr=nq['genuine_parent_initial_QA'];assert sha(qr['path'])==qr['sha256'];qa=load(qr['path']);qareceipt=Path(qr['path']).parent/'execution-receipt.json';qar=load(qareceipt);assert (qar['status'],qar['returncode'])==('completed',0);qa0=next(a for a in qa['cases'] if a['role']=='twoaxis_dp006');assert qa0['passed'] and qa0['actual_3d'] and qa0['native_particles']==179208 and qa0['native_fixed']==111708 and qa0['native_fluid']==67500
inputs=o['producer_attested_inputs']
for name in ('forcing','generated_xml','initial_bi4'):
 a=inputs[name];assert receipts['native']['input_hashes_at_launch'][a['path']]==receipts['native']['input_hashes_after_run'][a['path']]==a['sha256']
assert qa0['generated_xml_sha256']==inputs['generated_xml']['sha256']==sha(inputs['generated_xml']['path']);assert qa0['native_initial_BI4_sha256']==inputs['initial_bi4']['sha256'];assert nq['nominal_pitch_multiplier']==1.2 and nq['transverse_amplitude_m_s2']==.5
fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==836;assert times==[f['time'] for f in fs]==[f['actual_time_s'] for f in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=8.35 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[836,179208,3]
for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
 assert f['frame']==d['frame']==i and f['active_particles']==d['active']==179208 and f['missing_particles']==d['missing']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='179208 3';vv=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='179208 3'
frames=sorted(p.name for p in Path(t['source_provenance']['data_root']).glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name));assert len(frames)==836 and frames[0]=='Part_0000.bi4' and frames[-1]=='Part_0835.bi4';assert sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(836)];assert len(r['outputs']['contact_sheets'])==35
for key0,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key0]
O=H/'root_stage1_source190_F5_batch_membership_discrepancy_preserved_actual1128_F3_full836_QI0_visual_pending_checkpoint_1208';O.mkdir(exist_ok=False)
put(O/'source190-exact-adoption-readonly-validator-and-membership-proof.json',{'source_commit':commit,'exact_adopted_files':[ref(R/f) for f in files],'source_and_adopted_hashes_preserved':source_hashes,'validator_returncode':rv.returncode,'validator_stdout':rv.stdout,'F5_accepted_first8_in_final48':8,'historical_fresh117_first24_in_final48':14,'historical_fresh117_unmatched10':missing,'historical_candidate_plan_is_not_completed_visual_delivery':True,'F5_current_visual_accepted':11,'F5_actual_visual_second24_not_yet_complete':True,'first8_must_remain_subset_of_future_actual_visual24':True,'semantic_discrepancy_assigned_fresh191':True,'new_case_credit':0,'scientific_payload_IO':False})
proof=O/'actual1128-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';put(proof,{'case_id':cid,'physical_case_id':pid,'native_request_condition_sha256':canonical,'actual_converter_condition_sha256':actual,'scope_schema':'ds-data-02.physical-binding.v1','actual_completed_receipts':s,'typed_report':z['actual_typed_report'],'XMF_manifest':z['actual_XMF_manifest'],'XMF_XML':z['actual_XMF_XML'],'render_report':ref(report),'publish':ref(pub),'all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified':True,'all_native_UIds_active_each_frame':True,'actual_time_window_s':[times[0],times[-1]],'initial_parent_QA_report':qr,'initial_parent_QA_receipt':ref(qareceipt),'source_preparation_report':ref(prep['original_report_path']),'native_changed_forcing_initial_input_digests_unchanged':True,'visual_status':'pending source148 personal35contacts9keys','new_case_credit':0,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=188,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: actual1128 F3full836 native/typed/XMF/render0 QI independently verified all836 UID/finite/N3/time/scopes/publish, awaitingpersonalreview148 with no casecredit. Exact source190 adopted, F5acceptedfirst8 subsetfinal48 closed and historical117 prospectivefirst24 10unmatched retained, actualvisual24 notyetcompleted.',authorized_work_state='Active270/336: F3actual1128 publishedcompleted0 awaitingpersonalreview148; F5actual1152 and1130 rendering. Source190 historicalfirst24 discrepancy requires191 classification; first8physicalmembership preserved, no fake second24 claim. Original951lastF6 unchanged.')
cp['actual_progress']['source190_F5_staged_membership_discrepancy_preserved']=ref(O/'source190-exact-adoption-readonly-validator-and-membership-proof.json');cp['actual_progress']['F3_actual1128_full836_previsual_QI_verified']=ref(proof);cp['source_agents'].update(f5_bed_recovery='fresh191 actual1152 M108T095 full801personalreview after0/publish and classification of10historical117unmatchedprospectivecases',production_recovery='fresh148 actual1128 P1200AY0500 personal35contacts9keys plus originalnative semanticclosure',f6_endpoint_initial_qa='fresh165 F2first8/24physicalmembership ornextpublishedunacceptedF2personalreview')
cp['next_executable_tasks']=['Adopt fresh148 personal35contacts9keys actual1128, independentlybind latestoriginalreceiptmetadata andacceptonlyifvisualpasses','Fresh191 afteractual1152 F5publish0 personal34contacts9keys; classify10historical117missingmembership andpreservefirst8 inactualfuturevisual24','Fresh165 F2actualfirst8/24membership; original951lastF6 samehandlepending','Continue66 registeredpendingdeliveries; recordQ-N/Q-E0 and numeric/label limits']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_188.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=files+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_188.json').relative_to(R)),str((F/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close actual F3 full836 integrity and preserve F5 staged membership discrepancies','--',*paths],cwd=R,check=True);print({'checkpoint':188,'accepted':270,'F3full836QI':True,'F5first8subset48':True,'historical117unmatched':10,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
