from pathlib import Path
import json,hashlib,subprocess,datetime,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.log','.txt','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='72079b5690b966fa6541642db35accec036199b8';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_162_f3_assigned_f2_rx056_rot075_personal_visual_review_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==7;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh162.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
vr=Path('metadata/visual-review/F2_STAGE1_FIRST48_EXPANSION_RX056_RY014_FILL080_ROT075-delegated-visual-decision.json');pr=Path('metadata/png-hashes/F2_STAGE1_FIRST48_EXPANSION_RX056_RY014_FILL080_ROT075.json');ar=Path('metadata/chain-audit/F2_STAGE1_FIRST48_EXPANSION_RX056_RY014_FILL080_ROT075.json');v=load(P/vr);png=load(P/pr);chain=load(P/ar);cid=v['case_id'];pid=v['physical_case_id'];canonical=v['scope_roles']['native_canonical'];legacy=v['scope_roles']['actual_converter_legacy'];qp=root(1266)/'actual1065-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qp)
assert v['assigned_family_id']==chain['assigned_family_id']=='F3' and v['actual_family_id']==chain['actual_family_id']=='F2';assert qi['case_id']==chain['case_id']==cid and qi['physical_case_id']==chain['physical_case_id']==pid
assert chain['qi_proof']['path']==str(qp) and chain['qi_proof']['sha256']==sha(qp)==v['chain_evidence']['qi_proof_sha256'];assert canonical==qi['canonical_actual_native_request_condition_sha256']==chain['scope_roles']['native_canonical']['physical_condition_sha256'] and legacy==qi['actual_converter_legacy_scope_sha256']==chain['scope_roles']['actual_converter_legacy']['physical_condition_sha256'] and canonical!=legacy
assert v['status']=='visual-approved-by-delegated-agent' and v['visual_reviewer']=='/root/production_recovery' and v['limits']['case_credit']==0 and not v['limits']['q_n_granted'] and not v['limits']['q_e_granted'];assert chain['review_boundaries']['scientific_payload_opened_or_hashed_by_reviewer'] is False
stage=qi['actual_completed_metadata_evidence'];mapping={'genuine_gencase':{'receipt':'gencase_receipt','generated_xml':'gencase_xml'},'initial_native_qa':{'receipt':'initial_qa_receipt','report':'initial_qa_report'},'full_native_solver':{'receipt':'native_receipt'},'typed_conversion':{'receipt':'typed_receipt','report':'typed_report'},'n3_xmf':{'receipt':'xmf_receipt','manifest':'xmf_manifest','xmf_xml':'xmf_xml'},'full_render_root1065':{'receipt':'render_receipt','animation_report':'render_report','publish_receipt':'publish_receipt'}}
for key,fields in mapping.items():
 for field,name in fields.items():
  e=stage[key][field];assert e['path']==chain['actual_paths'][name]['path'] and e['sha256']==chain['actual_paths'][name]['sha256']==sha(e['path'])
 z=load(stage[key]['receipt']['path']);assert (z['status'],z['returncode'])==('completed',0) and z['request']['case_id']==cid
assert chain['actual_paths']['registered_request']['path']==qi['registered_request']['path'] and chain['actual_paths']['registered_request']['sha256']==qi['registered_request']['sha256']==sha(qi['registered_request']['path']);outer=load(qi['registered_request']['path']);assert outer['expected_frames']==801 and outer['expected_particles']==194427 and outer['expected_contact_sheets']==34
assert qi['frames']==401 and qi['particles']==418104 and qi['all_actual_times_exact_typed_XMF_XML_render'] and qi['all_frames_geometry_velocity_N3_identity_and_finite_active_fields'] and qi['stage1_QI_full_native_identity_and_state_verified'];life=chain['lifecycle_omission_evidence'];ql=qi['lifecycle'];assert life['final_missing_particles']==ql['final_missing_particles']==ql['max_missing_per_frame']==40 and life['first_missing_frame']==ql['first_missing_frame']==137 and life['frames_with_any_missing_particle']==ql['frames_with_any_missing_particle']==264 and life['cumulative_particle_frame_omissions']==ql['cumulative_particle_frame_omissions']==9182 and len(ql['final_missing_id_first_producer_attested'])==8 and life['unknown_missing_locations_states_and_causes'];assert qi['native_source_plan_field_present'] and qi['native_source_plan_field_sha256']==canonical==v['scope_roles']['source_plan'];assert chain['condition_metadata']['physical_window_s']==v['chain_evidence']['time_window_s']==qi['actual_time_window_s']
sourcebase=D/'families/F2/F2_FIRST48_REMAINING24_SOURCE_ROOT801/root-stage1-f2-first48-remaining24-registered-source-generation-root801/source';mp=sourcebase/'source'/f'{cid}.metadata.json';op=sourcebase/'owners'/f'{cid}.owner.json';meta=load(mp);owner=load(op);gcr=load(stage['genuine_gencase']['receipt']['path']);typed=load(stage['typed_conversion']['report']['path']);legacyowner=load(typed['source_provenance']['owner_metadata']['path']);assert sha(mp)==gcr['request']['input_sha256'][str(mp)]==legacyowner['provenance']['source_metadata']['sha256'];assert sha(op)==gcr['request']['input_sha256'][str(op)]==legacyowner['provenance']['source_owner']['sha256'];assert meta['case_id']==owner['case_id']==cid and meta['physical_case_id']==owner['physical_case_id']==pid and meta['physical_condition_sha256']==owner['physical_condition_sha256']==canonical
params=meta['parameter_values'];motion=meta['motion'];assert params['receiver_x_m']==.56 and params['receiver_y_m']==.14 and params['rotation_duration_s']==motion['rotation_duration_s']==.75 and motion['static_hold_start_s']==.5 and motion['rotation_stop_s']==1.25 and motion['final_angle_deg']==-105 and meta['physical_condition']['motion_file_sha256']==motion['sha256'];assert chain['condition_metadata']['receiver_x_grid_index_dp010']==56 and chain['condition_metadata']['rotation_duration_s']==.75
pub=load(chain['actual_paths']['publish_receipt']['path']);render=load(chain['actual_paths']['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==chain['actual_paths']['render_report']['sha256'];published={e['relative_path']:e for e in pub['files_excluding_receipt']};out=Path(pub['published_output_root']);contacts=sorted((e for e in png['entries'] if e['role']=='contact_sheet'),key=lambda e:e['contact_index']);keys=sorted((e for e in png['entries'] if e['role']=='event_keyframe'),key=lambda e:e['frame_index']);assert len(png['entries'])==26 and [e['contact_index'] for e in contacts]==list(range(17)) and [e['frame_index'] for e in keys]==list(range(0,401,50));assert [e['path'] for e in contacts]==render['outputs']['contact_sheets']
for e in png['entries']:
 pe=published[str(Path(e['path']).relative_to(out))];assert e['viewed'] and e['view_method']=='view_image' and sha(e['path'])==e['sha256']==pe['sha256'] and Path(e['path']).stat().st_size==e['bytes']==pe['bytes']
assert v['physical_screen']['unknown_omissions_not_reclassified'] and not any(v['physical_screen'][k] for k in ('gross_scene_loss','initial_state_abnormal','obvious_severe_bed_or_wall_penetration','obvious_whole_domain_explosion','strict_containment_assertion','sudden_truncation')) and len(v['visual_observations'])>=5
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_225.json';cp=load(cpfile);assert cp['checkpoint']==225 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==285 and cp['accepted_per_family']['F2']==37;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {r.get('physical_case_id',r['case_id']) for r in old};idxp=root(1268)/'full336-current285-actual-final48-delivery-progress-index.json';idx=load(idxp);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical
for row in idx['cases']:
 if row.get('accepted_decision'):assert row.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(v['reviewed_at_utc'].replace('Z','+00:00'))<=now and now<datetime.datetime(2026,10,14,7,23,48,tzinfo=datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and free>=500
O=H/'root_stage1_source162_assignedF3_actualF2_RX056ROT075_actual1065_full401QI_personal26PNG_quantified40fluid_visual_acceptance_1270';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_226.json';assert not list(H.glob('root*_1270')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'source162-byte-exact-readonly-validation.json';put(vp,{'source_commit':commit,'adopted_source_files':adopted,'source_SHA_before_after':before,'source_bytes_unchanged':True,'validator_returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr})
ctrl=O/'actual801-controls-and-historical-wrapper-role-sidecar.json';put(ctrl,{'source_metadata':ref(mp),'source_owner':ref(op),'own_gencase_receipt':stage['genuine_gencase']['receipt'],'source_metadata_and_owner_bound_to_GenCase_launch_and_typed_provenance':True,'parameter_values':params,'motion_metadata':motion,'motion_DAT_digest_is_producer_attested_no_payload_IO':True,'actual_native_condition_sha256':canonical,'legacy_typed_render_scope_sha256':legacy,'actual_native_plan_field_present':qi['native_source_plan_field_present'],'actual_native_plan_field_sha256':qi['native_source_plan_field_sha256'],'actual_XMF_plan_field_present':qi['XMF_source_plan_field_present'],'actual_XMF_plan_field_sha256':qi['XMF_source_plan_field_sha256'],'original_outer_request_envelope':{'frames':801,'particles':194427,'contact_sheets':34},'actual_chain':{'frames':401,'particles':418104,'contact_sheets':17},'original_outer_bytes_preserved':True,'native_rotation_hold_start_is_0_5_not_rotation_stop':True,'legacy_owner_not_promoted_to_actual_native_control':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_assigned_agent_family':'F3','source_family_id_F3_is_assignment_not_actual_case_family':True,'source_review_commit':commit,'source_visual_review':ref(P/vr),'source_review_closure':ref(P/ar),'source_review_PNG_evidence':ref(P/pr),'actual_control_and_wrapper_roles':ref(ctrl),'independent_full401_QI_proof':ref(qp),'actual_completed_metadata_evidence':stage,'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'lifecycle':ql,'final_UID_sample_count_not_full40':8,'missing_UID_cause_location_state_unknown_preserved':True,'native_and_XMF_plan_field_observations':{k:qi[k] for k in ['native_source_plan_field_present','native_source_plan_field_sha256','XMF_source_plan_field_present','XMF_source_plan_field_sha256']},'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['visual_observations'],'personal_visual_failure_screen':v['physical_screen'],'contact_sheets':contacts,'keyframes':keys,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'all26_PNG_hashes_match_actual_publish':True,'no_zero_fluid_loss_or_strict_container_claim':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source162-actual1065-full401-QI-and-personal-visual-adoption.json';put(proof,{'source_commit':commit,'source_validator':ref(vp),'source_original_bytes_preserved':True,'independent_QI':ref(qp),'new_visual_decision':ref(dp),'actual_controls_and_wrapper_roles':ref(ctrl),'actual_missing40fluid_and9182_events_unknowns_retained':True,'eight_sample_UIDs_not_complete40':True,'actual26PNG_bound_to_atomic_publish':True,'source_assignment_family_F3_vs_actual_F2_preserved':True,'new_case_credit':1,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp['accepted_per_family']['F2']+=1;newcp.update(checkpoint=226,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=286,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: integrated actual F2 RX056ROT075 full401 mainQI1266 + fresh162 personal17contacts9keys; 40UID omissions/137first/264frames/9182events and8sample unknowns retained. Own Source801 control metadata and stale outer801 wrapper roles verified without scientificpayload IO. Actual1154 now published0 and mainQI1271 completed awaiting fresh200 personalreview.',authorized_work_state='Active286/336: F2=38,F3=38,F5=19,F6=47,F1/F4/F7=48. Fifty cases remain. Existing original render queue globalcap2/CPU24 and Homefloor500GiB maintained.');assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==286;newcp['actual_progress']['source162_F2_actual1065_full401_visual_acceptance']=ref(proof);newcp['actual_progress']['F2_actual1154_full401_previsual_QI']=ref(root(1271)/'actual1154-full401-independent-UID-N3-time-scope-QI-proof.json');newcp['source_agents']['production_recovery']='fresh162 accepted286/F2=38; fresh163 own-control and typed/XMF readiness for remaining10actualF2';newcp['source_agents']['f5_bed_recovery']='fresh200 original1154 completed0 atomicpublished, mainQI1271 ready, personalvisual active';newcp['next_executable_tasks']=['Adopt fresh200 actualF2RX061ROT105 original1154 personal17contacts9keys with mainQI1271.','After original1046 publication, main ownfull836QI and fresh177 assignedF6 actualF3P0800AY0640 personal35contacts9keys.','Integrate fresh178 actual first24 F2/F3/F6 72case dynamic delivery, without duplicatecredit.','Continue original remaining render controllers globalcap2/CPU24; finalF6original951 pending capacity; F5 actualfirst24 prefix19 growing.'];put(nextcp,newcp)
idx['previous_index_preserved']=ref(idxp);idx['source_authoritative_checkpoint']=ref(nextcp);idx['at_utc']=now.isoformat();idx['accepted_independent_physical_cases']=286;idx['registered_pending_independent_physical_cases']=50;idx['new_case_credit']=1;targets[0].update(status='visual-approved-in-checkpoint226',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qp));idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if (x.get('physical_case_id') if isinstance(x,dict) else x)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==286;put(O/'full336-current286-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R)),str((root(1065)/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 rx056 rot075 full401 with40 quantified fluid omissions','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':286,'per_family':newcp['accepted_per_family'],'checkpoint':226,'remaining':50,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
