from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');O=H/'root_stage1_F3_P1200AY0250_delegated101_actual836_visual_integration_843';O.mkdir();load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_108.json')['accepted_decisions']+load(next(H.glob('root*842'))/'actual-integration-review.json')['decisions'];assert len(prior)==152;ids={load(p).get('physical_case_id',load(p)['case_id']) for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior};commit=subprocess.check_output(['git','rev-parse','c4accb63'],cwd=W,text=True).strip();S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_101_f3_corner_visual_decisions_v1';rel=S.relative_to(W);adopted=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
 p=W/name;assert p.suffix in {'.json','.md','.py'};blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert p.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists();dst.write_bytes(blob);adopted.append(ref(dst))
P=R/rel;sp=next((P/'decisions').glob('*.json'));d=load(sp);e=load(P/'metadata/root796_render_evidence.json');cid=d['case_id'];pid=d['physical_case_id'];dg=d['physical_condition_sha256'];assert pid not in ids and dg not in hashes and d['status']=='visual-approved-by-delegated-agent';ev={};b=d['bindings']
for k in ['native_receipt','typed_receipt','xmf_receipt','render_receipt']:
 v=b[k];assert sha(v['path'])==v['sha256'];r=load(v['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;ev[k]=ref(v['path'])
for k in ['typed_report','xmf_manifest','render_report']:
 v=b[k];assert sha(v['path'])==v['sha256'];ev[k]=ref(v['path'])
sc=d['physical_scope_provenance'];v=sc['actual_converter_scope']['owner'];assert sha(v['path'])==v['sha256'];own=load(v['path']);assert dg==sc['actual_converter_scope']['sha256']==sc['actual_native_physical_condition_sha256'];assert hashlib.sha256(json.dumps(own['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg
for k in ['source_condition_template','source_owner_template']:
 v=sc[k];assert sha(v['path'])==v['sha256']
t=load(b['typed_report']['path']);assert t['conversion_status']=='completed' and t['frames']==836 and t['particles']==179208 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and t['hash_scopes']['physical_condition_sha256']==dg and t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=8.35 and t['time_evidence']['strictly_increasing'];assert t['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1'
for k in ['gencase_receipt','solver_receipt']:
 v=t['source_provenance'][k];assert sha(v['path'])==v['sha256'];r=load(v['path']);assert (r['status'],r['returncode'])==('completed',0);ev['typed_bound_'+k]=ref(v['path'])
v=t['source_provenance']['generated_xml'];assert sha(v['path'])==v['sha256'];ev['generated_xml']=ref(v['path'])
x=load(b['xmf_manifest']['path']);assert x['frames']==836 and x['particles']==179208 and x['source_h5_sha256']==t['output_sha256'] and x['physical_condition_sha256']==dg;xf=x['xdmf'];assert sha(xf)==x['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==836 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='179208 3' for g in gs)
a=load(b['render_report']['path']);assert a['frames']==a['source_frames']==836 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(b['xmf_manifest']['path']) and a['source_h5_sha256']==t['output_sha256'] and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf);fs=a['frame_diagnostics'];assert len(fs)==836 and all(f['active']==179208 and f['missing']==0 and f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in fs)
review=d['review'];assert review['reviewer']=='production_recovery' and review['contact_sheets_reviewed']==35 and review['fullsize_keyframes_reviewed']==[0,1,65,115,200,300,400,500,600,700,800,835];png=e['render'];contacts=png['contact_sheets'];keys=png['keyframe_images'];assert len(contacts)==35 and len(keys)==12
for p in contacts+keys:assert sha(p['path'])==p['sha256']
out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':d['status'],'family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'source_review_commit':commit,'source_review':ref(sp),'visual_reviewer':'/root/production_recovery','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':review['observations'],'scope_separation':sc,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':{'contact_sheets':contacts,'key_frames':keys},'actual_frames':836,'actual_particles':179208,'actual_fluid_particles':67500,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','remaining_corner_not_approved':True,'case_local_only_no_premature_2D_range_release':True,'independent_case_increment':1,'previous_count':152,'resulting_count':153};dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);put(O/'actual-integration-review.json',{'source_commit':commit,'adopted_files':adopted,'source_adopted_byte_exact':True,'previous_count':152,'resulting_count':153,'independent_case_increment':1,'decisions':[str(dp)],'science_payload_not_read_or_hashed':True,'F3_parameter_2D_range_release':'pending last P1200 AY0750 actual completed render plus delegated visual acceptance'});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'new_cases':1,'accepted':153})
