from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def same(a,b):return a['path']==b['path'] and a['sha256']==b['sha256']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='c9ad7dc9b057fd51df3e6dff506126564811910d';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_179_f3_assigned_f5_m102_t095_root1174_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==6
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh179.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
sp=P/'metadata/m102-t095-personal-visual-decision.json';s=load(sp);c=s['actual_chain'];v=s['visual_evidence'];vr=s['visual_review'];roles=s['physical_condition_roles'];rcfg=s['reviewer_configuration'];dims=s['actual_dimensions']
assert s['assigned_worktree_family']=='F3' and s['actual_case_family']=='F5' and rcfg['model']=='gpt-5.6-luna' and rcfg['reasoning_effort']=='max' and not rcfg['model_substitution'] and not rcfg['recursive_delegation']
assert vr['status']=='visual-approved-by-delegated-agent' and vr['screen']=='pass_first_stage' and vr['new_case_credit']==0 and not vr['q_n_granted'] and not vr['q_e_granted'] and not vr['scientific_payload_opened_or_hashed_by_reviewer'] and not vr['scientific_jobs_started_or_restarted'] and not vr['shared_state_modified']
qip=root(1371)/'actual1174-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip);check(s['root_qi']);assert same(s['root_qi'],ref(qip));cid=qi['case_id'];pid=qi['physical_case_id'];assert s['case_id']==cid and s['physical_case_id']==pid
e=qi['actual_completed_metadata_evidence'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];sd=qi['actual_SourceDef']['sha256']
source_refs={'gencase_receipt':c['gencase']['receipt'],'generated_xml':c['gencase']['generated_xml'],'initial_qa_receipt':c['initial_qa']['receipt'],'initial_qa_report':c['initial_qa']['report'],'native_receipt':c['native'],'typed_receipt':c['typed']['receipt'],'typed_report':c['typed']['conversion_report'],'xmf_receipt':c['xmf']['receipt'],'xmf_manifest':c['xmf']['manifest'],'xmf_xml':c['xmf']['xml'],'bed_receipt':c['bed']['receipt'],'bed_report':c['bed']['report'],'render_receipt':c['render']['receipt'],'render_report':c['render']['report'],'render_publish_receipt':c['render']['atomic_publish']}
for k,a in source_refs.items():check(a);assert same(a,e[k]);assert same(s['provenance']['metadata_evidence'][k],e[k])
receipts={}
for role in ['gencase','initial_qa','native','typed','xmf','bed','render']:
 j=load(source_refs[role+'_receipt']['path']);assert j['schema']=='ds02.execution-receipt.v1' and j['status']=='completed' and j['returncode']==0 and j['request']['case_id']==cid;receipts[role]=j
nq=receipts['native']['request'];x=load(e['xmf_manifest']['path']);rawmask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
assert rawmask==qi['actual_native_XMF_plan_field_namespaces'];nf=roles['native_and_xmf_plan_fields']
for ns,pfx in [('native','native'),('XMF','xmf')]:
 for k,value in rawmask[ns].items():assert nf[pfx+'_'+k]==value
assert roles['native_request_condition_sha256']==roles['actual_native_canonical_scope_sha256']==canonical and roles['actual_converter_legacy_scope_sha256']==legacy and roles['source_definition_bed_role_sha256']==sd and len({canonical,legacy,sd})==3
check(roles['actual_SourceDef']);assert same(roles['actual_SourceDef'],qi['actual_SourceDef']);assert nf['xmf_source_plan_physical_condition_has_native_canonical_role'] and not nf['xmf_source_plan_physical_condition_has_SourceDef_role']
assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['XMF_source_plan_physical_condition_field_has_native_canonical_role'] and not qi['XMF_source_plan_physical_condition_field_has_SourceDef_role']
assert dims['frames']==801 and dims['particles']==194427 and dims['fluid']==31658 and dims['time_window_s']==qi['actual_time_window_s']==[0.0,16.00010761371514]
assert s['provenance']['actual_initial_QA_precision_negative']==qi['actual_initial_QA_precision_negative'] and s['provenance']['depth_diagnostic_bins_not_numerical_thresholds'] and s['provenance']['subDP_positive_depth_not_quantified_by_zero_bins'] and s['root_qi_is_independent_metadata_proof_not_runner_receipt'] and 'status' not in qi and 'returncode' not in qi
r=load(e['render_report']['path']);pub=load(e['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(e['render_report']['path']);out=Path(pub['published_output_root']);published={a['relative_path']:a for a in pub['files_excluding_receipt']}
contacts=v['contacts'];keys=v['keys'];assert len(contacts)==34 and len(keys)==9 and [a['path'] for a in contacts]==r['outputs']['contact_sheets'];assert [int(Path(a['path']).stem.split('_')[-1]) for a in keys]==list(range(0,801,100));assert r['frames']==r['source_frames']==801 and r['all_frames_rendered']
side=load(P/'metadata/png-evidence/m102-t095.json');assert side['contacts']==contacts and side['keys']==keys and side['reviewed_at_utc']==rcfg['reviewed_at_utc']
for a in contacts+keys:
 p=Path(a['path']);rel=str(p.relative_to(out));assert rel==a['relative_path'] and sha(p)==a['declared_sha256']==published[rel]['sha256'] and p.stat().st_size==a['bytes']==published[rel]['bytes'] and a['personally_viewed_with_view_image']
parse=lambda z:datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',z).replace('Z','+00:00'));reviewed=rcfg['reviewed_at_utc'];now=datetime.datetime.now(datetime.timezone.utc);assert parse(receipts['render']['finished_at_utc'])<=parse(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_285.json';cp=load(cpfile);assert cp['checkpoint']==285 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==313 and cp['accepted_per_family']['F5']==34
ip=root(1381)/'full336-current313-actual-final48-delivery-progress-index.json';idx=load(ip);row=next(a for a in idx['cases'] if a['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_source179_actualF5_M102T095_original1174_full801QI_personal43PNG_native_XMF_physicalplan_canonical_SourceDef_FILE_distinct_visual_acceptance_1382';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_286.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source179-byte-exact-readonly-validator-main43publishedPNG-full801QI-native-XMF-canonical-SourceDef-distinct-proof.json';put(vp,{'schema':'ds02.source179.main.actualF5.adoption-integrity.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'own_QI':ref(qip),'personal_reviewed_at_utc':reviewed,'review_after_completed_publication':True,'all43_publishedPNG_SHA_match_atomic_publish':True,'actual_native_XMF_plan_namespaces':rawmask,'XMFphysical_has_nativecanonical_not_SourceDefFILE_role':True,'initial_QA_precision_negative_preserved':True,'source_role_correction_needed':False,'main_scientific_payload_IO':False})
dp=O/(pid+'-delegated-visual-decision.json');normcontacts=[{**a,'sha256':a['declared_sha256'],'producer_sha256':a['declared_sha256'],'index':i,'viewed':True,'view_method':'view_image'} for i,a in enumerate(contacts)];normkeys=[{**a,'sha256':a['declared_sha256'],'producer_sha256':a['declared_sha256'],'frame':int(Path(a['path']).stem.split('_')[-1]),'viewed':True,'view_method':'view_image'} for a in keys]
put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_SourceDef_scope_sha256':sd,'source_review_commit':commit,'source_review_assigned_family':'F3','actual_review_family':'F5','source_personal_visual_review':ref(R/prefix/'metadata/m102-t095-personal-visual-decision.json'),'independent_full801_QI':ref(qip),'actual_completed_metadata_evidence':e,'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_type_counts':dims,'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_bins_are_diagnostics_not_precision_thresholds':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'actual_native_XMF_plan_field_namespaces':rawmask,'actual_native_source_plan_condition_field_present':False,'actual_native_source_plan_condition_field_value':None,'actual_native_source_plan_physical_condition_field_present':True,'actual_native_source_plan_physical_condition_field_value':canonical,'actual_XMF_source_plan_condition_field_present':False,'actual_XMF_source_plan_condition_field_value':None,'actual_XMF_source_plan_physical_condition_field_present':True,'actual_XMF_source_plan_physical_condition_field_value':canonical,'actual_XMF_physical_plan_has_native_canonical_role':True,'actual_XMF_physical_plan_has_SourceDef_role':False,'actual_bed_plan_field_value':sd,'binding_source_definition_field_present':qi['binding_source_definition_field_present'],'canonical_legacy_SourceDef_roles_are_distinct':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':normcontacts,'keyframes':normkeys,'visual_observations':vr['observations'],'visual_limits':vr['limitations'],'no_strong_runup_or_inundation_magnitude_claim_from_visual_screen':True,'original_precision_negative':qi['actual_initial_QA_precision_negative'],'historical_negative_flags':qi['historical_negative_flags'],'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source179-actual1174-full801QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=1
new.update(checkpoint=286,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=314,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active314/336; F1/F4/F6/F7=48,F2=44,F3=43,F5=35. Source179 actualF5original1174 personal43PNG/full801QI1371 accepted with real native/XMF canonical physicalplan and distinct bedSourceDefFILE/typedlegacy. Source213 actualF3original1033 personalreview active; source195 F2 finalgate repair active. NextsameF5original1160/1151 registeredrenders/durableQI1377/1380 continue.',previous_goal_turn_classification='PROGRESS: source194 mainaudit confirms4 actualrequest-as-receipt/fulltime/runtime/immutableoutput gaps; fresh195 repairing separately. Source179 exact6 committedfiles readonlyvalidator/own801QI and actual43publishedPNG SHA/timestamp closed; accepted314/F5=35 without numerical qualification.')
new['actual_progress']['source179_F5_actual1174_visual_acceptance']=ref(ap);new['source_agents']['production_recovery']='fresh179 accepted F5original1174; available for F5 completion-only final48 builder or next actualpublished personalreview'
new['next_executable_tasks']=['Adopt source213 F3original1033 personal35contacts9keys after exactcommit/readonlyvalidation/full836QI1373 and native/XMF bothplanabsences closure.','Audit source195 F2 fulltime/runtime/4 correctedrequest roles and outputimmutable gates; fresh194 remainsassembly only.','Observe sameF5original1160 PID648352/start214140469 and1151 PID650123/start214158617; actual0/pub then durableownQI1377/1380 once, assign freechild personalreviews.','Prepare F5 completion-only final48 primarybed delivery builder with real full801/N3/UID/time/bed/receipt gates, preserve4 historicalpublicationreceiptabsences and originalscopealiascorrection.','Continue remaining22 independent visual cases and finalF2/F3/F5 catalogs/global336 audit; Home500GiB/negativehistory/QNQE0 preserved.']
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==314;put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=314,registered_pending_independent_physical_cases=22,new_case_credit=1);row.update(status='visual-approved-in-checkpoint286',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qip))
idx['actual_unaccepted_completed0_published_physical_cases']=[a for a in idx['actual_unaccepted_completed0_published_physical_cases'] if (a if isinstance(a,str) else a['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(a.get('accepted_decision')) for a in idx['cases'])==314;put(O/'full336-current314-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F5 M102T095 personal43PNG with canonical XMF and distinct bed SourceDef','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':286,'accepted':314,'F5':35,'pending':22,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
