from pathlib import Path
import json,hashlib,datetime,subprocess,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_250.json';cp=load(cpfile);assert cp['checkpoint']==250 and cp['stage1_visual_accepted_complete_independent_cases']==300
ip=root(1323)/'full336-current300-actual-final48-delivery-progress-index.json';index=load(ip)
O=H/'root_stage1_nextF3_original1141_1135_full836_live_actual_native_plan_absence_XMF_namespace_durable_future_QI_preparation_1326';assert not O.exists();rows=[]
for original,pid,starts,outnum in [(1141,535136,213051955,1324),(1135,536560,213065155,1325)]:
 F=root(original);q=load(F/'enabled-full836-render-request.json');z=load(F/'actual1076-full836-XMF-and-producer-typed-independent-review.json');m=load(z['actual_XMF_manifest']['path']);t=load(z['actual_typed_report']['path']);nat=load(z['actual_native_receipt']['path']);nq=nat['request']
 for k in ['actual_XMF_receipt','actual_XMF_manifest','actual_XMF_XML','actual_typed_report','actual_typed_receipt','actual_native_receipt']:assert ref(z[k]['path'])==z[k]
 for k in ['actual_XMF_receipt','actual_typed_receipt','actual_native_receipt']:r=load(z[k]['path']);assert r['status']=='completed' and r['returncode']==0
 assert q['case_id']==m['case_id']==nq['case_id'] and q['physical_case_id']==m['physical_case_id']==nq['physical_case_id']
 canonical=nq['physical_condition_sha256'];assert canonical==t['hash_scopes']['physical_condition_sha256']==m['physical_condition_sha256']
 assert t['frames']==m['frames']==q['expected_frames']==836 and t['particles']==m['particles']==q['expected_particles']==179208
 assert 'source_plan_condition_sha256' not in nq and 'source_plan_physical_condition_sha256' not in nq
 assert 'source_plan_condition_sha256' in m and 'source_plan_physical_condition_sha256' not in m and m['source_plan_condition_sha256']!=canonical
 procp=Path(f'/proc/{pid}');statp=procp/'stat';ss=statp.read_text() if statp.exists() else None;parts=ss[ss.rfind(')')+2:].split() if ss else []
 live=bool(parts and int(parts[19])==starts and parts[0] not in ['Z','X']);framecount=None;private=None
 if live:
  a=[x.decode() for x in (procp/'cmdline').read_bytes().split(b'\x00') if x];assert a[a.index('--manifest')+1]==z['actual_XMF_manifest']['path'];private=Path(a[a.index('--output-dir')+1]);framecount=len(list((private/'frames').glob('frame_*.png')))
 crp=F/'controller-result.json';cr=load(crp) if crp.exists() else None
 rows.append({'original_root':original,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'actual_original_request':ref(F/'enabled-full836-render-request.json'),'actual_original_wrapper':ref(F/'enabled-render-wrapper.json'),'actual_existing_previsual_XMF_typed_review':ref(F/'actual1076-full836-XMF-and-producer-typed-independent-review.json'),'actual_native_receipt':z['actual_native_receipt'],'actual_typed_report':z['actual_typed_report'],'actual_XMF_manifest':z['actual_XMF_manifest'],'native_canonical_condition_sha256':canonical,'actual_native_and_XMF_plan_field_namespaces':{'native':{k:{'present':k in nq,'value':nq.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']},'XMF':{k:{'present':k in m,'value':m.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']}},'actual_frames':836,'actual_particles':179208,'actual_saved_window_s':[m['actual_time_s'][0],m['actual_time_s'][-1]],'original_controller_terminal':cr,'current_renderer':{'pid':pid,'expected_startticks':starts,'actual_startticks':int(parts[19]) if parts else None,'same_handle_live':live,'state':parts[0] if parts else None,'private_render_dir_filename_only':str(private) if private else None,'private_frame_PNG_filenames_count':framecount,'private_PNG_content_read_or_hashed':False,'restart':False},'future_full836_QI_root':outnum,'future_QI_proof':None,'future_QI_SHA256':None,'future_QI_runs_only_after_original_completed0_and_atomic_publication':True,'source_review_assignment':'fresh207 W5' if original==1141 else 'fresh186 W6','new_case_credit':0,'main_scientific_payload_IO':False})
cleanup=root(1327)/'current-storage-cleanup-verification.json';cl=load(cleanup);assert cl['floor_pass'] and cl['all_deleted_paths_still_absent'] and cl['all_preserved_samples_present'] and cl['original_failed_receipts_bytes_unchanged'] and cl['new_deletions_this_verification']==0
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc)
assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc']);np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_251.json';assert not np.exists();O.mkdir()
entry=O/'after_original_terminal_full836_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F3-next1135-1141-original-full836-own-QI.py').read_bytes())
proof=O/'actual-original1141-1135-current-live-scope-preflight-and-futureQI-entrypoints.json'
put(proof,{'schema':'ds02.main.nextF3-originals.durable-future836QI-preparation.v1','at_utc':now.isoformat(),'current_preparation_only_not_future_completed_QI':True,'original_controller_and_pv_processes_not_restarted':True,'actual_rows':rows,'durable_future_QI_script':ref(entry),'entrypoints':[{'original':r['original_root'],'future_QI_root':r['future_full836_QI_root'],'command':['python3','-B',str(entry),str(r['original_root']),str(r['future_full836_QI_root'])]} for r in rows],'contacts35_and_keys9_review_only_after_original_publication':True,'source_review_keyframe_indices':[0,100,200,300,400,500,600,700,835],'native_plan_absence_not_filled_from_XMF_namespace':True,'main_scientific_payload_IO':False,'case_credit':0,'Q_N':0,'Q_E':0})
(O/'README.md').write_text('两例原始F3 full836作业持续运行；已核对本例真实native/typed/XMF receipt、179208粒子与原生保存时间，并保留native两个plan字段真实缺失、XMF source_plan_condition字段独立命名空间。这里只保存未来ownQI可执行入口和当前live证据，future proof/SHA保持null；原始完成0且原子发布后再运行入口，随后子代理个人35contact+9key视觉检查。未重启/新增科学作业，不读科学载荷或私有PNG。\n')
(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw)
new=copy.deepcopy(cp);new.update(checkpoint=251,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source171 actual finalF6 particle/rigid directory47accepted/onepending delivered; source206 and185 actualF5 original801 personal43PNG accepted, total300/336. OriginalF3 full836 1141/1135 actual live metadata roles independently verified, durable ownQI entrypoints saved and personalreviews delegated. User534GiB failed-output cleanup reverified; no unsafe new deletion.',authorized_work_state='Active300/336: F1/F4/F7=48 F2=42 F3=39 F5=28 F6=47. Same original1141 and1135 full836 rendering; sourcefresh207/186 awaiting originalpublication and futureownQI. Source172 currentF3final48 39accepted/ninepending catalog in progress; finalF6 original951 samehandle live awaiting faircapacity.')
new['actual_progress']['nextF3_original1141_1135_exact_scope_live_and_durable_QI_preparation']=ref(proof);new['actual_progress']['latest_user_storage_reverification']=ref(cleanup);new['actual_progress']['user_failed_storage_cleanup534GiB_current_retention_verification']=ref(cleanup)
put(np,new);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0)
index['nextF3_original1141_1135_previsual_preparation']=ref(proof);put(O/'full336-current300-actual-final48-delivery-progress-index.json',index)
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(p.relative_to(R)) for p in root(1327).iterdir()]+[str(np.relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: checkpoint300 and durable nextF3 original836 QI with safe cleanup retention','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':251,'accepted':300,'current_render_frame_filename_counts':[(r['original_root'],r['current_renderer']['private_frame_PNG_filenames_count']) for r in rows],'home_free_GiB':free,'safe_cleanup_cumulative_GiB':cl['cumulative_released_allocated_GiB'],'durable_preparation':ref(proof),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
