from pathlib import Path
import json,hashlib,copy,datetime,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
PO=root(1303);stock=load(PO/'enabled-pilot-runner-request.json');cr=load(PO/'controller-result.json');assert (cr['status'],cr['returncode'])==('completed',0);rp=Path(cr['actual_receipt']);rr=load(rp);assert (rr['status'],rr['returncode'])==('completed',0) and rr['request_sha256']==sha(PO/'enabled-pilot-runner-request.json')
for p,v in stock['input_sha256'].items():assert rr['input_hashes_at_launch'][p]==rr['input_hashes_after_run'][p]==v
reportp=rp.parent/'floatinginfo/fulltime-rigid-motion-report.json';report=load(reportp);pa=report['parse'];pilotpid=report['case']['physical_case_id'];assert report['status']=='completed' and report['returncode']==0 and pa['rows_examined']==pa['rigid_fields_finite_rows']==241 and pa['required_rigid_field_count']==17 and pa['part_values_observed']==list(range(241));part=pa['part_column_contract'];assert part['mode']=='frame_index' and part['observed_values']==list(range(241)) and part['frame_identity_from_part'];nt=pa['native_time_comparison'];assert nt['provided'] and nt['within_tolerance'] and nt['max_abs_delta_s']<=nt['tolerance_s']==1e-6
P=R/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_168_f3_assigned_f6_fulltime_floatinginfo_worker_v1';src=load(P/'requests/f6-final48-fulltime-floatinginfo-disabled-request-index.json')['requests'];bm=load(root(1300)/'47-own-full241-native-time-bindings-for-official-rigid-export.json');bindings={x['physical_case_id']:x for x in bm['cases']};inventorypath=Path(load(PO/'actual47-small-IBI4-inventory-independent-metadata-closure.json')['inventory_report']['path']);inventory=load(inventorypath);entries={e['physical_case_id']:e for e in inventory['entries']};assert len(entries)==47 and len(src)==47
O=H/'root_stage1_F6_remaining46_full241_official_rigid_motion_exports_actual_Part0to240_pilot_native_time_inventory_closed_Root142928_CPU2_1304';assert not list(H.glob('root*_1304'));O.mkdir();(O/'requests').mkdir();(O/'specs').mkdir();proof=O/'actual-full241-pilot-independent-closure-and-Part-frame-contract.json';put(proof,{'schema':'ds02.main.F6.full241-rigid-pilot-closure.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pilot_runner_request':ref(PO/'enabled-pilot-runner-request.json'),'actual_pilot_receipt':ref(rp),'actual_pilot_report':ref(reportp),'native_input_hashes_match_before_after':True,'physical_case_id':pilotpid,'actual_required_rigid_fields_finite_rows':241,'actual_Part_column_mode':'frame_index','actual_Part_first_last':[part['observed_values'][0],part['observed_values'][-1]],'actual_Part_unique_count':len(set(part['observed_values'])),'native_time_tolerance_s':nt['tolerance_s'],'max_actual_time_delta_s':nt['max_abs_delta_s'],'official_actual_time_window_s':[pa['first_time_s'],pa['last_time_s']],'actual_CSV_output_producer_attestation':report['output'],'own47_scientific_input_inventory':ref(inventorypath),'first_fulltime_pilot_adds_no_independent_case':True,'main_scientific_payload_IO':False,'case_credit':0,'Q_N':0,'Q_E':0})
controller=O/'registered-remaining46-controller.py';controller.write_text("from pathlib import Path\nimport json,runpy,hashlib,datetime\nO=Path(__file__).parent\nc=json.loads((O/'controller-config.json').read_text())\ndispatch=runpy.run_path(c['fair_dispatch'])['dispatch']\nresults=[]\nfor item in c['requests']:\n p=Path(item['path']);assert hashlib.sha256(p.read_bytes()).hexdigest()==item['sha256']\n q=json.loads(p.read_text());r=dispatch(p,serial_conversion=True)\n rp=Path(q['attempt_root'])/'execution-receipt.json';a=json.loads(rp.read_text()) if rp.exists() else {}\n z={'physical_case_id':q['physical_case_id'],'request':item,'launcher_returncode':r.returncode,'status':a.get('status'),'returncode':a.get('returncode'),'actual_receipt':str(rp),'stdout_tail':r.stdout[-1500:],'stderr_tail':r.stderr[-1500:]}\n results.append(z)\n v={'schema':'ds02.F6.fulltime.remaining46.batch-result.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'completed' if len(results)==len(c['requests']) else 'running','requests':len(c['requests']),'processed':len(results),'completed_zero':sum(x['status']=='completed' and x['returncode']==0 for x in results),'results':results,'case_credit':0}\n t=O/'batch-result.json.tmp';t.write_text(json.dumps(v,indent=2)+'\\n');t.replace(O/'batch-result.json')\n print(json.dumps({'processed':v['processed'],'completed_zero':v['completed_zero'],'physical_case_id':z['physical_case_id'],'status':z['status']}),flush=True)\nraise SystemExit(0 if all(x['status']=='completed' and x['returncode']==0 for x in results) else 1)\n")
requests=[]
for source in src:
 pid=source['case']['physical_case_id']
 if pid==pilotpid:continue
 q=copy.deepcopy(source);b=bindings[pid];e=entries[pid];tag=pid.lower().replace('_','-');ar=D/'families/F6'/q['case']['case_id']/f'root-stage1-{tag}-full241-rigid-history-source168-root1304';assert not ar.exists();q.update(disabled=False,source_only=False,execution_allowed=True,status='root_enabled_fulltime_export_after_actual_matching_pilot');q['native']['rigid_state_input']['inventory_binding'].update(report_path=str(inventorypath),report_sha256=sha(inventorypath),entry_source_sha256=e['sha256']);q['time_contract'].update(native_times_s=b['native_times_s'],native_time_tolerance_s=b['native_time_tolerance_s'],native_time_source=b['manifest']);q['official_export']['part_contract'].update(pilot_required=True,mode='frame_index',expected_values=list(range(241)),actual_pilot_report=ref(reportp),actual_pilot_Part_authority=ref(proof));q['output'].update(directory=str(ar/'floatinginfo'),report_path=str(ar/'floatinginfo/fulltime-rigid-motion-report.json'));q['worker']['path']=str(P/'workers/run_fulltime_floatinginfo_fresh168.py');q['worker']['sha256']=sha(q['worker']['path']);q['main_actual_time_binding']=b;sp=O/'specs'/f'{pid}-fulltime-spec.json';put(sp,q)
 inputs={p:v for p,v in stock['input_sha256'].items() if p.endswith(('fair_CPU_dispatch.py','launch.py','root_home_floor_inventory_policy.py','ds_data02_runtime_v2.py','ds_data02_strict_dispatch_v1.py','resource-window-approval.json'))};inputs.update({str(sp):sha(sp),str(controller):sha(controller),str(proof):sha(proof),str(reportp):sha(reportp),str(inventorypath):sha(inventorypath),e['path']:e['sha256'],q['worker']['path']:q['worker']['sha256'],q['official_export']['binary_path']:q['official_export']['binary_sha256'],q['official_export']['help_path']:q['official_export']['help_sha256']})
 for k in ['native_receipt','manifest','typed_report','xdmf']:inputs[b[k]['path']]=b[k]['sha256']
 a={k:copy.deepcopy(stock[k]) for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']};a.update(schema='ds02.runner-request.v2',family_id='F6',case_id=q['case']['case_id'],physical_case_id=pid,attempt_id=ar.name,attempt_root=str(ar),kind='cpu',cpu_task_kind='audit',launch_owner='root',cpu_threads=2,estimated_storage_bytes=536870912,max_wall_seconds=600,cwd=str(L),worktree_root=str(R),command=[str(L/'.venv/bin/python'),q['worker']['path'],'--request',str(sp),'--report','{attempt_root}/floatinginfo/fulltime-rigid-motion-report.json'],input_files=sorted(inputs),input_sha256=inputs,input_sha256_required=True,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,physical_condition_sha256=q['case']['physical_condition_sha256'],case_credit=0);qp=O/'requests'/f'{pid}-fulltime-runner-request.json';put(qp,a);requests.append(ref(qp))
assert len(requests)==46;put(O/'controller-config.json',{'fair_dispatch':str(root(928)/'fair_CPU_dispatch.py'),'requests':requests,'registered_serial_CPU_threads':2,'part_pilot_evidence':ref(proof)});(O/'registration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(O.relative_to(R)),str((PO/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close actualfull241 rigid pilot and register remaining46 official exports','--',*paths],cwd=R,check=True);print({'batch_controller':str(controller),'registered_exports':46,'pilot_actual':ref(reportp),'case_credit':0})
