from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,math,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_313.json';cp=load(cpfile);assert cp['checkpoint']==313 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==327
F=root(1176);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre);refs={k:e for k,e in j.items() if isinstance(e,dict) and 'path' in e and 'sha256' in e}
for e in refs.values():assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);native_ref=t['source_provenance']['solver_receipt'];assert sha(native_ref['path'])==native_ref['sha256'];n=load(native_ref['path']);nq=n['request'];bedr=load(j['actual_bed_receipt']['path']);b=load(bedr['request']['binding']);bed=load(j['actual_bed_report']['path']);refs['actual_native_receipt']=native_ref;refs['actual_bed_binding']=ref(bedr['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert (canonical,legacy,sd)==('83831d4fc2150e22f79c5bc6d4a6e655c2ab6c43b517288c531b490ed3563877','c7a06c6bdcbf126b3758317aabda1815621e3b2368d9ad546c14ef95d4e0aae1','c4e0a0ad9924c53eba206011b0bac762a8babc706fc1bf101e1ca2e1f6450965')
mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
for m in mask.values():assert m=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}}
defs=[(p,v) for p,v in bedr['request']['input_sha256'].items() if p.endswith('_Def.xml') and v==sd];assert len(defs)==1
source_def=ref(defs[0][0]);assert source_def['sha256']==sd==bed['source_plan_physical_condition_sha256'];assert bedr['input_hashes_at_launch'][source_def['path']]==bedr['input_hashes_after_run'][source_def['path']]==sd
assert b['source_definition']==source_def['path'] and b['source_definition_sha256']==sd and b['source_plan_file_sha256']=='366adc5200604490871116a0a5b8503c9bef4bfb1e72195df94995605fa7d324'
plan=ref(root(823)/'source-plan.json');assert plan['sha256']=='366adc5200604490871116a0a5b8503c9bef4bfb1e72195df94995605fa7d324' and len({canonical,legacy,sd,plan['sha256']})==4
assert b['source_plan_file']==plan['path'] and b['source_plan_file_sha256']==plan['sha256'];assert all(rec['input_hashes_at_launch'][plan['path']]==rec['input_hashes_after_run'][plan['path']]==plan['sha256'] for rec in [n,bedr])
native_defs=[(p,v) for p,v in n['input_hashes_at_launch'].items() if p.endswith('_Def.xml') and v==sd];assert len(native_defs)==1 and n['input_hashes_after_run'][native_defs[0][0]]==sd==sha(native_defs[0][0])
q=load(F/'enabled-full801-render-request.json');w=load(F/'enabled-render-wrapper.json');cid=q['case_id'];pid=q['physical_case_id'];assert pid=='F5_COMPACT_RUNUP_RECOVERY_C082S1_M104_T095' and cid=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M104_T095_NEXT34'
for k,bkey in [('gencase_receipt','gencase_receipt'),('initial_qa_receipt','initial_qa_receipt'),('initial_qa_report','initial_qa_report'),('generated_xml','canonical_generated_xml')]:
 e=ref(b[bkey]);assert e['sha256']==b[bkey+'_sha256'];refs[k]=e
for k in ['gencase_receipt','initial_qa_receipt','actual_native_receipt','actual_typed_receipt','actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
qa=load(refs['initial_qa_report']['path']);assert qa['all_basic_placement_checks_pass'] and all(qa['checks'].values()) and not qa['numerical_precision_result_accepted'];assert t['source_provenance']['gencase_receipt']==refs['gencase_receipt'] and t['source_provenance']['generated_xml']==refs['generated_xml']
assert w['expected_frames']==t['frames']==x['frames']==len(bed['frame_reports'])==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
assert t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected' and t['partvtk_validation']['all_passed'];assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];xp=Path(x['xdmf']);refs['XMF_XML']=ref(xp);assert refs['XMF_XML']['sha256']==x['xdmf_sha256'];grids=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]');assert len(fs)==len(times)==len(grids)==801 and times==[f['time'] for f in fs]==[f['time_s'] for f in bed['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert [times[0],times[-1]]==[0,16.00012550006781] and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
for i,(f,bf,g) in enumerate(zip(fs,bed['frame_reports'],grids)):
 assert f['frame']==bf['frame']==i and f['active_particles']==194427 and f['missing_particles']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658}
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';v=next(z for z in g.findall('Attribute') if z.get('Name')=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='194427 3'
 assert bf['initial_fluid_uid_count']==bf['current_valid_type3_fluid_count']==bf['finite_mass_current_fluid_count']==bf['finite_position_current_fluid_count']==31658 and bf['uid_tracking']['missing_initial_uid']['count']==bf['uid_tracking']['unexpected_current_uid']['count']==bf['nonfinite_mass_current_fluid_count']==bf['nonfinite_position_current_fluid_count']==0 and not bf['uid_tracking']['unexplained'];assert bf['bed_domain']['x_outside_exact_profile_domain_count']==bf['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']==bf['penetration']['depth_unevaluable_current_fluid_count']==0
 for k,th in [('one_dp',.02),('two_dp',.04)]:assert bf['penetration'][k]['threshold_m']==th and bf['penetration'][k]['count']==0 and bf['penetration'][k]['deepest_depth_m'] is None
h5=t['output_hdf5'];assert t['output_sha256']==x['source_h5_sha256']
for k in ['actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
pp=Path('/proc/749459');obs=None
if pp.exists():
 st=(pp/'stat').read_text().rsplit(')',1)[1].split();args=(pp/'cmdline').read_bytes().split(b'\0');assert st[19]=='215077434' and str(F/'enabled-render-wrapper.json').encode() in args;obs={'registered_launch_pid':749459,'startticks':'215077434','state':st[0],'original_request_bound_to_actual_cmdline':True,'no_restart':True}
assert obs is not None or (F/'controller-result.json').exists()
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current327_nextF5_original1176_full801_UID_bed_native_XMF_canonical_actual_SourceDef_planFILE_present_realQA_durable1423_1422';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_314.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1423'));O.mkdir();entry=O/'after_original1176_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1159-1176-full801-own-QI1421-1423.py').read_bytes());compile(entry.read_text(),str(entry),'exec');proof=O/'next1176-full801-UID-bed-namespace-realQA-and-durableQI-readiness.json'
put(proof,{'schema':'ds02.current327-next1176-durable801QI.v1','at_utc':now.isoformat(),'next_original1176_upstream_primary_refs':refs,'prior_previsual_proof':ref(pre),'case_id':cid,'physical_case_id':pid,'canonical_native':canonical,'typed_legacy':legacy,'bed_SourceDef_FILE':source_def,'source_plan_JSON_FILE':plan,'actual_native_XMF_plan_field_namespaces':mask,'native_and_XMF_physical_plan_canonical_not_SourceDef':True,'source_plan_JSON_launch_after_native_verified':True,'bed_source_plan_JSON_input_present_launch_after_verified':True,'binding_source_definition_and_plan_file_fields_present_and_actual_values_verified':True,'actual_bed_SourceDef_XML_input_launch_after_verified':True,'genuine_GenCase_initialQA_completed0_and_basicplacement_pass':True,'initialQA_precision_negative_retained':qa['numerical_precision'],'full801_typed_UID_type_N3_exact_times_and_bed_UID_footprint_bins_verified':True,'render_finite_states_await_actual_complete_publication_and_own1423':True,'actual_time_window_s':[times[0],times[-1]],'same_original_worker_current_live':obs,'actual_terminal':ref(F/'controller-result.json') if (F/'controller-result.json').exists() else None,'future_ownQI1423_UNEXECUTED_SHA_unknown':True,'durable_entry':ref(entry),'command':['python3','-B',str(entry),'1176','1423'],'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=314,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source186+187 F3 accepted325, source199 F5 accepted326 and source221 F5 accepted327. Actual1159 completed0 atomicpub independently passed full801 own1421; delegated personal review active. Next original1176 actualtyped full801UID/N3/XML times/bed footprint/realQA verified, allfour binding SourceDef/planFILE fields genuinely present, actualcanonical83831 vslegacyc7a06 vsSourceDefc4e0 vsplanJSON366adc separately verified. Sameworker749459/start215077434 lives; durableown1423 prepared without new render or solver.',authorized_work_state='Active327/336 remaining9. F1/F4/F6/F7=48 F2=46 F3=47 F5=42. Production188 original1159 personal34+9 after own1421 active; F6fresh200 original1176 preflight then personal34+9 waits actual0/pub and futureown1423. Final196/197/218 bounded readiness only; finalactualprimary manual percase joins still required.')
new['actual_progress']['next_original1176_durable_full801_QI']=ref(proof)
new['actual_progress']['actual1159_completed_full801_ownQI1421']=ref(root(1421)/'actual1159-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json')
new['source_agents'].update(production_recovery='fresh188 original1159 personal34+9 after actual0/pub/own1421',f6_endpoint_initial_qa='fresh200 original1176 metadata preflight then personal34+9 awaits0/pub and own1423',f5_bed_recovery='fresh221 original1139 accepted327; available next actual case')
new['next_executable_tasks']=['Integrate actual1159 only after genuine delegated43PNG review; own1421 completed no rerun.','After original1176 natural0/pub execute durableown1423 once, then authorize F6 fresh200/new personal package.','Observe same registered remaining controllers, prepare next admitted actual case; never duplicate render or solver.','Complete remaining9 cases then genuine actual48 F2/F3/F5 primary and global336 delivery preserving all runtime unknowns and numerical precision limits.'];put(np,new)
ip=root(1420)/'full336-current327-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);row=next(z for z in idx['cases'] if z['physical_case_id']==pid);assert not row.get('accepted_decision');row.update(current_same_original_live_previsual_preparation=ref(proof),future_independent_QI_root=1423,current_personal_review_source=200,case_credit=0,prior_controller_observations_are_historical_not_current=True)
completed1159=load(root(1421)/'actual1159-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json');r1159=next(z for z in idx['cases'] if z['physical_case_id']==completed1159['physical_case_id']);assert not r1159.get('accepted_decision');r1159.update(status='actual-render-completed0-published-ownQI1421-personal-review-pending',actual_full801_QI=ref(root(1421)/'actual1159-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json'));idx['actual_unaccepted_completed0_published_physical_cases']=[completed1159['physical_case_id']]
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,next_original1176_durable_full801_QI=ref(proof));assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==327;put(O/'full336-current327-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare M104T095 durable full801 integrity with actual present SourceDef and plan FILE roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':314,'accepted':327,'next_original1176_live':obs,'future1423_unexecuted':True,'proof':ref(proof),'free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
