from pathlib import Path
import json,hashlib,subprocess,datetime,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_163_f3_assigned_f2_remaining_metadata_readiness_v1');P=W/prefix;load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='fb79e5b8740df188e992a2805509d883aa89b280';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh163.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names};source=load(P/'metadata/f2-remaining-metadata-readiness.json');cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_227.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==287;accepted={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};rows=[]
for c in source['cases']:
 cid=c['case_id'];pid=c['physical_case_id'];mp=c['source_roles']['source_metadata'];op=c['source_roles']['owner'];md=load(mp['path']);assert sha(mp['path'])==mp['sha256'] and sha(op['path'])==op['sha256'];gc_ref=c['gencase']['receipt'];nr_ref=c['native']['receipt'];gc=load(gc_ref['path']);nr=load(nr_ref['path']);assert sha(gc_ref['path'])==gc_ref['sha256'] and sha(nr_ref['path'])==nr_ref['sha256'];assert (gc['status'],gc['returncode'])==(nr['status'],nr['returncode'])==('completed',0);assert md['physical_condition_sha256']==nr['request']['physical_condition_sha256']==c['native']['request_condition_sha256'];assert md['case_id']==nr['request']['case_id']==cid and md['physical_case_id']==nr['request']['physical_case_id']==pid;assert gc['request']['input_sha256'][mp['path']]==mp['sha256'] and gc['request']['input_sha256'][op['path']]==op['sha256']
 qa=c['initial_qa'];assert sha(qa['receipt']['path'])==qa['receipt']['sha256'] and sha(qa['report']['path'])==qa['report']['sha256'];qar=load(qa['receipt']['path']);assert (qar['status'],qar['returncode'])==('completed',0)
 prep=Path(gc_ref['path']).parent/'prepared/prepared-input-report.json';pr=load(prep);assert pr['actual_total_particles']==418104 and pr['generated_xml_particle_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21114};assets=pr['assets'];assert len(assets)==1;asset=assets[0];digest=md['motion']['sha256'];assert asset['sha256']==asset['verified_post_gencase_sha256']==digest and asset['restored_after_gencase'] and asset['post_gencase_size_before_restoration']==0;ap=asset['copied_to'];assert nr['input_hashes_at_launch'][ap]==nr['input_hashes_after_run'][ap]==digest
 tc=c['typed'][0];xc=c['xmf'][0];tp=tc['conversion_report'];xp=xc['manifest'];assert sha(tp['path'])==tp['sha256'] and sha(xp['path'])==xp['sha256'];t=load(tp['path']);x=load(xp['path']);assert (load(tc['execution_receipt']['path'])['status'],load(tc['execution_receipt']['path'])['returncode'])==('completed',0);assert sha(tc['execution_receipt']['path'])==tc['execution_receipt']['sha256'] and sha(xc['execution_receipt']['path'])==xc['execution_receipt']['sha256'];assert (load(xc['execution_receipt']['path'])['status'],load(xc['execution_receipt']['path'])['returncode'])==('completed',0);fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];assert t['frames']==x['frames']==len(fs)==len(times)==401 and t['particles']==x['particles']==418104 and times==[f['time'] for f in fs] and x['fields']['position']['shape']==x['fields']['velocity']['shape']==[401,418104,3];assert t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert x['actual_converter_legacy_scope_sha256']==t['hash_scopes']['physical_condition_sha256']!=nr['request']['physical_condition_sha256']
 for f in fs:
  assert f['active_particles']+f['missing_particles']==418104 and f['missing_type_counts'].get('3',0)==f['missing_particles'] and f['type_counts']['0']==372840 and f['type_counts']['1']==24150 and f['type_counts']['2']==0
 missing=[f for f in fs if f['missing_particles']];request=c['registered_render']['request'];assert sha(request['path'])==request['sha256'];outer=load(request['path']);terminal=Path(request['path']).parent/'controller-result.json';terminal_ref=ref(terminal) if terminal.exists() else None
 rows.append({'case_id':cid,'physical_case_id':pid,'source_metadata':mp,'source_owner':op,'native_receipt':nr_ref,'gencase_receipt':gc_ref,'prepared_input_report':ref(prep),'source_parameter_values':md['parameter_values'],'source_motion_metadata':md['motion'],'GenCase_control_asset_was_truncated_to_zero_then_restored':True,'restoration_metadata':{k:asset[k] for k in ('post_gencase_size_before_restoration','post_gencase_sha256_before_restoration','restored_after_gencase','verified_post_gencase_sha256')},'native_launch_after_motion_digest':digest,'DAT_bytes_not_read_or_hashed':True,'actual_native_condition_sha256':nr['request']['physical_condition_sha256'],'native_plan_field_present':'source_plan_physical_condition_sha256' in nr['request'],'native_plan_field_sha256':nr['request'].get('source_plan_physical_condition_sha256'),'actual_converter_legacy_scope_sha256':t['hash_scopes']['physical_condition_sha256'],'XMF_plan_field_present':'source_plan_physical_condition_sha256' in x,'XMF_plan_field_sha256':x.get('source_plan_physical_condition_sha256'),'typed_report':tp,'XMF_manifest':xp,'full401_typed_XMF_time_N3_identity_counts_previsual_checked':True,'actual_time_window_s':[times[0],times[-1]],'fluid_omissions':{'final':fs[-1]['missing_particles'],'max':max(f['missing_particles'] for f in fs),'frames':len(missing),'first':missing[0]['frame'] if missing else None,'events':sum(f['missing_particles'] for f in fs),'location_state_cause_unknown':True},'source_render_controller_absence_snapshot_not_current_runtime_authority':True,'accepted_at_current_checkpoint':pid in accepted,'current_completed_controller':terminal_ref,'registered_original_render_request':request,'new_case_credit':0})
assert len(rows)==10 and sum(r['accepted_at_current_checkpoint'] for r in rows)==1;assert next(r for r in rows if r['accepted_at_current_checkpoint'])['physical_case_id']=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX061_RY014_FILL080_ROT105';assert not list(H.glob('root*_1274'));O=H/'root_stage1_source163_remaining_F2_actual_controls_restored_motion_native_legacy_scopes10_currentpending9_independent_adoption_1274';O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
put(O/'source163-byte-exact-readonly-validation.json',{'source_commit':commit,'source_files_SHA_before_after':before,'source_original_bytes_preserved':True,'stdout':rv.stdout,'stderr':rv.stderr,'adopted_source_files':adopted});put(O/'actual10-F2-controls-restoration-and-current9-pending-own-metadata-proof.json',{'schema':'ds02.main.own-native-F2-control-restoration-previsual-readiness.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_commit':commit,'source_package':str(R/prefix),'current_authority':ref(cpfile),'actual_cases_audited':10,'current_pending_of_these':9,'source_controller_claims_are_historical_observations_only':True,'all10_control_assets_zero_truncation_then_restoration_metadata_verified':True,'all10_actual_native_launch_after_asset_digest_equals_restored_producer_digest':True,'rows':rows,'scientific_payload_IO':False,'new_scientific_job':False,'new_case_credit':0,'Q_N':0,'Q_E':0,'precision_status':'not accepted','new_personal_visual_review':False});(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: bind10 F2 own controls and GenCase restoration evidence for9 pending renders','--',*paths],cwd=R,check=True);print({'adopted_cases':10,'pending_now':9,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
