from pathlib import Path
import json,hashlib,subprocess,datetime,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.xml','.xmf','.py','.md','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_208.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==276
items=[('ds-data-02-f5','F5',195,'c5e6a9650','root_followup_195_f5_cleanup_audit_v1','validate_fresh195.py'),('ds-data-02-f3','F3',154,'e8f20e52a','root_followup_154_f3_registered_render_handles_live_audit_v1','validate_registered_render_handle_audit.py'),('ds-data-02-f3','F3',155,'ccc90bbdb1349436ebbf651074cb7dccfbb765a7','root_followup_155_f3_1100_live_and_frame_role_sidecar_v1','validate_live_and_frame_role_sidecar.py')];packages=[]
for wt,fam,n,short,dirname,vname in items:
 W=Path('/home/jade/.codex/worktrees')/wt/'DualSPHysics';commit=subprocess.check_output(['git','rev-parse',short],cwd=W,text=True).strip();prefix=f'lagrangian-fluid-lab/campaigns/ds-data-02/families/{fam}/handoff_20261003/{dirname}';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==(5 if n==195 else 4);P=W/prefix;before={name:sha(W/name) for name in names};vld=P/'scripts'/vname;v=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert v.returncode==0 and before=={name:sha(W/name) for name in names};packages.append({'n':n,'W':W,'prefix':prefix,'commit':commit,'names':names,'validator':ref(vld),'validation':{'returncode':v.returncode,'stdout':v.stdout,'stderr':v.stderr},'source_bytes_unchanged':True})
f5=load(Path(packages[0]['W'])/packages[0]['prefix']/'metadata/fresh195-audit-report.json');assert not f5['decision']['safe_to_delete_now'] and f5['decision']['immediate_deletion_candidates']==[];f3=load(Path(packages[2]['W'])/packages[2]['prefix']/'metadata/live-and-frame-role-sidecar.json');assert len(f3['frame_role_cases'])==5
for row in f3['frame_role_cases']:assert row['request_contract']['expected_frames']==801 and row['loaded_wrapper_contract']['expected_frames']==836
O=H/'root_stage1_source195154155_storage_retention_live_render836_roles_F5_actual14_delivery_prefix_checkpoint_1243';O.mkdir(exist_ok=False);adopted=[]
for pkg in packages:
 for name in pkg['names']:
  b=subprocess.check_output(['git','show',f"{pkg['commit']}:{name}"],cwd=pkg['W']);assert (pkg['W']/name).read_bytes()==b;p=R/name;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
now=datetime.datetime.now(datetime.timezone.utc).isoformat();live=[]
for n in (1100,1109):
 origin=root(n);launchp=origin/'controller-launch-process.json';a=load(launchp);pid=a['pid'];ps=Path(f'/proc/{pid}');chain=[];todo=[pid];seen=set()
 while todo and len(seen)<12:
  current=todo.pop(0)
  if current in seen:continue
  seen.add(current);p=Path(f'/proc/{current}')
  try:
   st=(p/'stat').read_text().split(') ',1)[1].split();cmd=(p/'cmdline').read_bytes().replace(b'\0',b' ').decode(errors='replace');child=(p/'task'/str(current)/'children').read_text().split();chain.append({'pid':current,'state':st[0],'start_ticks':int(st[19]),'cmdline':cmd,'children':[int(x) for x in child]});todo.extend(int(x) for x in child)
  except OSError:continue
 terminal=origin/'controller-result.json';valid_same=bool(chain) and chain[0]['start_ticks']==int(a['proc_start_ticks']) and chain[0]['state'] not in ('Z','X');q=load(a['request']);receipt=Path(q['attempt_root'])/'execution-receipt.json';d=load(receipt) if receipt.exists() else {};live.append({'root':n,'actual_current_controller_launch':ref(launchp),'actual_current_controller_result_path':str(terminal),'actual_current_controller_result':ref(terminal) if terminal.exists() else None,'same_original_controller_PID_startticks_currently_live':valid_same,'process_chain':chain,'receipt_status':d.get('status'),'receipt_returncode':d.get('returncode'),'receipt_hash_observation_not_immutable_producer':ref(receipt) if receipt.exists() else None,'actual_published_report':str(Path(q['attempt_root'])/'render/paraview-full-animation-report.json'),'published_report_exists':(Path(q['attempt_root'])/'render/paraview-full-animation-report.json').exists(),'no_restart_or_stop':True})
assert all(x['same_original_controller_PID_startticks_currently_live'] or x['actual_current_controller_result'] for x in live)
lf=O/'original1100-1109-actual-live-handle-observations.json';put(lf,{'at_utc':now,'observations':live,'private_science_or_PNG_contents_read':False})
oldcontractp=root(1209)/'F5-actual-visual-first8-to-first24-to-final48-delivery-contract.json';old=load(oldcontractp);decisions=[(p,load(p)) for p in cp['accepted_decisions']];frozen=load(old['first8_frozen_authority']['path']);ids8=[];ref8=[]
for e in frozen['cases_by_family']['F5']:
 assert sha(e['path'])==e['sha256'];d=load(e['path']);ids8.append(d.get('physical_case_id',d['case_id']));ref8.append(ref(e['path']))
accepted=[(p,d) for p,d in decisions if d['family_id']=='F5'];assert len(accepted)==cp['accepted_per_family']['F5']==14;accepted_map={d.get('physical_case_id',d['case_id']):(p,d) for p,d in accepted};assert len(accepted_map)==14 and set(ids8)<=set(accepted_map);prefix=ids8+[d.get('physical_case_id',d['case_id']) for p,d in accepted if d.get('physical_case_id',d['case_id']) not in ids8];assert len(prefix)==14 and set(prefix)<=set(old['final48_physical_case_ids']);delivery=O/'F5-actual-first24-growing-prefix14-frozen8-acceptance-order.json';put(delivery,{'schema':'ds02.main.F5.actual-first24-growing-delivery-prefix.v1','at_utc':now,'first8_frozen_authority':old['first8_frozen_authority'],'previous_contract_preserved':ref(oldcontractp),'current_authoritative_checkpoint':ref(cpfile),'first8_physical_case_ids':ids8,'actual_first24_realized_prefix_count':14,'actual_first24_delivered':False,'target_first24':24,'target_final48':48,'first8_subset_realized_prefix_subset_final48_verified':True,'physical_case_ids_actual_delivery_order':prefix,'actual_visual_decisions':[ref(accepted_map[p][0]) for p in prefix],'extension_rule':'retain frozen source-order first8 and append real accepted independent physicalIDs in actual checkpoint acceptance order until24','old_historical_candidate_exact24_roles_preserved':True,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收'})
proof=O/'source195154155-immutable-adoption-retention-and-actual836-role-proof.json';put(proof,{'at_utc':now,'source_packages':[{'n':p['n'],'commit':p['commit'],'validator':p['validator'],'validation':p['validation'],'source_original_bytes_unchanged':True} for p in packages],'adopted_files':adopted,'F5_immediately_deletable_payload_files':0,'F5_6_prospective_review_candidates_retained_and8_negative_or_recovery_groups_protected':True,'F3_source153_recovered_half_save_H5_andCSV9downstream_refs_retained':ref(root(1239)/'actual153-consumed-F3-recovery-artifact-retention-proof.json'),'F3_request801_top_envelope_not_actual_render_frame_count':True,'F3_five_loaded_wrappers_actual836_N179208_contacts35':True,'original_loaded_requests_receipts_guards_sourcebytes_preserved':True,'source154155_process_and_running_receipt_fields_are_historical_observations_not_new_terminal_certificate':True,'source155_controller_result_path_alias_preserved_not_used_as_terminal_authority':{'original_declared_path':f3['live_handle_1100']['controller_result_path'],'actual_controller_result_path':str(root(1100)/'controller-result.json'),'render_manifest_alias_not_used_as_XMF_or_publication_authority':f3['live_handle_1100']['manifest_path']},'actual_current_live_handle_observations':ref(lf),'F5_actual_delivery_prefix_grown14':ref(delivery),'user_actual_completed_cleanup_proof':ref(root(1235)/'cleanup-actual-results-and-retention-proof.json'),'new_case_credit':0,'new_deletion_files':0,'main_scientific_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);z=os.statvfs('/home/jade');cp=copy.deepcopy(cp);cp.update(checkpoint=209,at_utc=now,predecessor=str(cpfile),predecessor_sha256=sha(cpfile),home_free_gib=z.f_bavail*z.f_frsize/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(collections.Counter(x['kind'] for x in ld['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600,new_accepted_decisions=[],previous_goal_turn_classification='Progress: two realF2actual1069/1068 full401QI and26personalPNG each accepted276/F2=35. Source195154155 exact adopted: F5negative/residual immediate0delete, source153usedF3recovery retained; F3five801envelope vs actual836loadedwrapper role closed, current11001109samePIDticks verifiedlive; F5realfirst24prefix8->14 accepted grown, notclaimed24.')
cp['actual_progress']['source195154155_retention_frame_roles_actual_live_F5growing14']=ref(proof);cp['authorized_work_state']='Active276/336. F2=35,F5=14,F3=36,F6=47,F1/F4/F7=48. OriginalF31100 andF51109 samePID/startticks actuallive with dispatcher/worker chains, no terminal report yet; retain originals untilcompleted0published personal review. Usercleanup cumulative534.4GiB verified,Home791GiB. F5actualfirst24 only14realized, no numerical certification.';cp['next_executable_tasks']=['Watch same original1109 F5M090T095 actual801 render and1100 F3P1200AY0360 actual836 render; collect only realpublishedcompleted0 and personally review through existing children.','Use existing registered nextF2/lastF6original951 handles; no duplicatedscientific reruns or sourceguard changes.','Continue actualfirst24F5 frozen8plusrealaccepted order14->24 and final48, each only afterfullnative/render/visualclosure.','Preserve activeHome500GiB floor,cumulative512GPUh/3840CPUcoreh/qualification1024/production720 and originalOct14deadline; currentremaining60actualvisualcases.'];put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_209.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_209.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: preserve negative evidence and close loaded836 frame roles with actual F5 delivery prefix','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':209,'accepted':276,'F5actual_first24_prefix':14,'live':[x['root'] for x in live if x['same_original_controller_PID_startticks_currently_live']],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
