from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'));O=H/'root_stage1_actual939_full801_typed4GiB_publication_independent_review_and158_source_adoption_949';O.mkdir(exist_ok=True);assert not list(O.iterdir());load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ['.json','.py','.md','.xml','.xmf','.log'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)};q=load(root(939)/'enabled-first-typed-request.json');ar=Path(q['attempt_root']);r=load(ar/'execution-receipt.json');t=load(ar/'conversion-report.json');assert (r['status'],r['returncode'])==('completed',0);assert t['conversion_status']=='completed' and t['frames']==801 and t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['solver_dimension']['xml_data2d']=='false';assert t['partvtk_validation']['all_passed'] and [x['frame'] for x in t['partvtk_validation']['frames']]==[0,400,800] and all(x['passed'] and x['identity_type_mk_exact'] and x['rows']==194427 for x in t['partvtk_validation']['frames']);assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=16 and t['time_evidence']['strictly_increasing'];fs=t['lifecycle']['frame_summary'];assert len(fs)==801 and all(f['missing_particles']==0 and f['active_particles']==194427 for f in fs);assert t['lifecycle']['introduced_ids']=='rejected';actual=t['hash_scopes']['physical_condition_sha256'];assert actual==q['root_prospective_legacy_scope_sha256'];assert hashlib.sha256(json.dumps(t['hash_scopes']['physical_condition'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==actual;canonical=q['canonical_physical_scope']['physical_condition_sha256'];assert canonical!=actual;storage=t['storage_protocol'];h5=Path(t['output_hdf5']);assert h5==ar/'trajectory.h5' and h5.stat().st_size==storage['staged_h5_bytes'];assert (ar/'conversion-report.json').stat().st_size==storage['final_report_bytes'];assert h5.stat().st_size+(ar/'conversion-report.json').stat().st_size==storage['planned_publish_bytes']<=4*1024**3;assert storage['home_floor_bytes']>=500*1024**3 and storage['remaining_after_publish_and_reservations']>=500*1024**3 and storage['verified_published_output_sha256']==t['output_sha256'] and storage['private_staging_removed'];assert load(root(939)/'controller-result.json')['full801_typed_pass']
W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob('root_followup_158_*'));commit=subprocess.check_output(['git','rev-parse','0b85ee36'],cwd=W,text=True).strip();refs=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines():
 src=W/name;blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert src.read_bytes()==blob and src.suffix in ['.json','.py','.md'];dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==blob;dst.write_bytes(blob);refs.append(ref(dst))
proof={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual939_request':ref(root(939)/'enabled-first-typed-request.json'),'actual939_receipt':ref(ar/'execution-receipt.json'),'actual939_typed_report':ref(ar/'conversion-report.json'),'actual_native_dependency':q['actual_native_dependency'],'actual_frames':801,'actual_particles':194427,'actual_solver_dimension':3,'actual_first_time_s':t['time_evidence']['first_s'],'actual_last_time_s':t['time_evidence']['last_s'],'PartVTK0_400_800_all_true':True,'all801_missing0_and_identity_axis_complete':True,'Home_published_bytes':storage['planned_publish_bytes'],'Home_hard4GiB_and500GiB_floor_verified_from_producer_and_file_stats':True,'canonical_physical_condition_sha256':canonical,'actual_converter_legacy_scope_sha256':actual,'source_plan_sha256':q['canonical_physical_scope']['source_plan_sha256'],'scope_equality_claim':False,'actual_H5':{'path':str(h5),'producer_sha256':t['output_sha256'],'main_only_stat_bytes':h5.stat().st_size,'main_payload_read_or_hash':False},'source158_commit':commit,'adopted_source158_files':refs,'source_adopted_byte_exact':True,'source158_only_disabled_templates_not_actual_downstream':True,'required_XMF_materialization_adjustments':['Add native_receipt alias pointing to exact full_native_receipt; reused129worker requires native_receipt, typed_receipt, not onlyfull_native_receipt.','Use actual producer case ID M086_NEXT34 in runner/binding while keeping canonicalphysicalcase separate; bed identityadapter159 pending.','M095 originaltemplate typednulls must bind terminal939 actualreport/receipt/H5; sourceforecast legacydigest equals actual here only after producerverification.'],'science_payload_IO_by_main':False,'case_credit':0,'precision_status':'not accepted; native/typed alone is not visual acceptance'};(O/'actual939-and158-review.json').write_text(json.dumps(proof,indent=2)+'\n');(O/'adoption-and-review-source.py').write_bytes(Path(__file__).read_bytes());print({'actual939_completed0':True,'published_GiB':storage['planned_publish_bytes']/1024**3,'source158_files':len(refs),'case_credit':0})
