from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.py','.md','.xml','.xmf','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
packages=[('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_150_cross_family_first8_first24_final48_membership_audit_v1','469eea6f4bea271d2f608ee271fdb9f55fc01402',150),('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_151_f4_frozen_actual_first8_authority_reconciliation_v1','69d6bbd21bf44979b0ba21d13b22e77b7f427c60',151)];checks=[];sources=[]
for prefix,commit,no in packages:
 names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==4;before={n:sha(W/n) for n in names};vld=W/prefix/f'scripts/validate_fresh{no}.py';vr=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],capture_output=True,text=True);assert vr.returncode==0 and before=={n:sha(W/n) for n in names};checks.append({'source':no,'commit':commit,'validator':ref(vld),'returncode':vr.returncode,'stdout':vr.stdout,'stderr':vr.stderr,'source_original_bytes_unchanged':True});sources.append((prefix,commit,names))
a=load(W/packages[0][0]/'audit.json');b=load(W/packages[1][0]/'metadata/f4-first8-authority-reconciliation.json');fp=root(1093)/'FIRST8_PER_FAMILY_STAGE1_SUBSET56.json';f=load(fp);cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_202.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==273;accepted=[(Path(p),load(p)) for p in cp['accepted_decisions']];subsets={};proofs={}
for fam in ('F1','F4','F7'):
 actual=[(p,d) for p,d in accepted if d['family_id']==fam];assert len(actual)==48;byid={d.get('physical_case_id',d['case_id']):(p,d) for p,d in actual};bycase={d['case_id']:(p,d) for p,d in actual};assert len(byid)==len(bycase)==48
 for z in a['families'][fam]['accepted_final48']['rows']:
  p=Path(z['decision_path']);assert str(p) in cp['accepted_decisions'] and sha(p)==z['decision_sha256'] and load(p).get('physical_case_id',load(p)['case_id'])==z['physical_case_id']
 frozen=[]
 for r in f['cases_by_family'][fam]:
  assert sha(r['path'])==r['sha256'];d=load(r['path']);pid=d.get('physical_case_id',d['case_id']);assert pid in byid and str(Path(r['path']))==str(byid[pid][0]);frozen.append({'family_id':fam,'case_id':d['case_id'],'physical_case_id':pid,'accepted_visual_decision':r})
 assert len({x['physical_case_id'] for x in frozen})==8
 rows=[]
 for z in a['families'][fam]['first24']['rows']:
  if fam=='F1':p,d=bycase[z['case_id']]
  else:p,d=byid[z['physical_case_id']]
  assert d['status'] in ('visual-approved-by-root','visual-approved-by-delegated-agent') and cp['numeric_reference_accepted_independent_products']==0 and cp['precision_status']=='视觉检查通过、数值精度未验收'
  rows.append({'family_id':fam,'case_id':d['case_id'],'physical_case_id':d.get('physical_case_id',d['case_id']),'accepted_visual_decision':ref(p),'original_source24_row':z,'source_physical_ID_not_overridden':z.get('source_physical_case_id',z.get('physical_case_id')),'accepted_semantic_condition_sha256':d['physical_condition_sha256'],'accepted_semantic_hash_not_native_override':True,'original_precision_status_field_present':'precision_status' in d,'original_precision_status_field_value':d.get('precision_status'),'actual_delivery_dataset_precision_label':cp['precision_status'],'original_Q_N_fields_preserved':{k:v for k,v in d.items() if k in ('q_n','q_n_granted','numerical_precision_status','numerical_reference_accepted')}})
 assert len({x['physical_case_id'] for x in rows})==24
 frozenids={x['physical_case_id'] for x in frozen};stageids={x['physical_case_id'] for x in rows};inter=len(frozenids&stageids);assert inter==(5 if fam=='F4' else 8)
 proofs[fam]={'actual_frozen_first8':frozen,'actual_source24_all_already_visual_accepted':rows,'accepted_final48_count':48,'actual_frozen8_intersection_source24':inter,'actual_frozen8_subset_source24':frozenids<=stageids,'old_source150_first8_same_as_frozen_actual8_by_case_id':{z.get('case_id') for z in a['families'][fam]['first8']['rows']}=={x['case_id'] for x in frozen},'old_source150_native_or_candidate_first8_snapshot_preserved':a['families'][fam]['first8']}
 if fam!='F4':subsets[fam]={'actual_first8':frozen,'actual_first24':rows,'first8_subset_first24':True,'first24_subset_accepted_final48':True,'first8_source':ref(fp),'first24_source_order_preserved':True,'actual_first24_delivered':24,'new_case_credit':0}
assert proofs['F4']['actual_frozen8_intersection_source24']==b['set_comparisons']['frozen_actual_first8_vs_current_exact24']['intersection_count']==5
O=H/'root_stage1_source150151_F1_F7_actual_frozen8_subset_visual24_final48_F4_three_missing_source24_preserved_checkpoint_1232';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_203.json').exists();adopt=[]
for prefix,commit,names in sources:
 for n in names:
  raw=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert raw==(W/n).read_bytes();p=R/n;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopt.append(ref(p))
put(O/'actual-source150151-readonly-validators.json',{'sources':checks,'exact_adopted_files':adopt});put(O/'MAIN_ACTUAL_FIRST24_F1_F7_SUBSET48.json',{'schema':'ds02.actual-first24-visual-delivery-subsets.F1F7.v1','families':subsets,'precision_status':'视觉检查通过、数值精度未验收','source_authority':ref(fp),'no_new_native_compute_or_case_credit':True,'actual24_per_family_completed_visual':True,'Q_N':0,'Q_E':0});proof=O/'actual-staged-membership-roles-and-F4-source-plan-gap.json';put(proof,{'source150151_preserved':True,'family_actual_sets_and_source_roles':proofs,'new_F1_F7_actual24_deliveries':ref(O/'MAIN_ACTUAL_FIRST24_F1_F7_SUBSET48.json'),'F4_actual_delivery_contract':'Preserve frozen Root1093 actual8 in order; append different physical IDs in current checkpoint F4 acceptance order within accepted48 until actual24; source152 preparing this actual delivery. Old historicalcandidate8/source-plan exact24 retained separately.','main_scientific_payload_IO':False,'new_case_credit':0})
now=datetime.datetime.now(datetime.timezone.utc).isoformat();lb=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(lb);lf=O/'resource-ledger-frozen.json';lf.write_bytes(lb);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500
cp.update(checkpoint=203,at_utc=now,predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(lb).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ld['reservations'],attempt_counts=dict(collections.Counter(x['kind'] for x in ld['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600,previous_goal_turn_classification='Progress: real F5source192193 accepted273/F5=13; actual1137full801QI0closed awaiting194. Source150151 exact adopted; frozen actual F1/F7first8 both8/8in realvisual24/48, F4old source-plan24 excludes3frozen8 cases; source152 forming actual24delivery preserving8 and original source plans.',authorized_work_state='Active273/336. F5actual1137 published0 all801QI closed, personal194active; F2actual1069 original render live. ActualF1F7visual24 delivery subsets closed; actualF4first24delivery152 preparing; F6first24actual169auditactive. All63remaining cases await actualpersonalvisualdeliveries.');cp['actual_progress']['source150151_actual_staged_subsets_and_F4_sourceplan_gap']=ref(proof);cp['source_agents']['production_recovery']='source150151 adopted; fresh152 actualF4first24 preservingfrozen8 + acceptanceorder';cp['next_executable_tasks']=['Adopt fresh194 actual1137 M090T100 personal34contacts9keys after122? actual1230 full801QI proof byte closure; count only if ownvisualapproved.','Adopt source152 F4 actual first24 delivery preserving frozen8; do not relabel historicalsource24 plan.','Finish source169 F6 actual first8/24/final48; actual1069 published0 F2personalreviewpriority.','Continue original same registered63 remaining render handles; no duplicate native compute; actual F5first24 pending13/24, precision not accepted.'];newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_203.json';put(newcp,cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in root(1231).iterdir() if p.is_file()]+[str(Path(e['path']).relative_to(R)) for e in adopt]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: deliver actual F1 F7 visual24 subsets and preserve F4 planned24 membership gap','--',*paths],cwd=R,check=True);print({'accepted':273,'checkpoint':203,'F1actual24':24,'F7actual24':24,'F4frozen8_in_source24':5,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
