from pathlib import Path
import json,hashlib,datetime,subprocess,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit=subprocess.check_output(['git','rev-parse','c551799ff'],cwd=W,text=True).strip();P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob('root_followup_216_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();expected={'README.md','manifest.json','metadata/actual-render-metadata.json','metadata/physical-stage-closure.json','metadata/png-visual-evidence.json','metadata/upstream-evidence.json','metadata/visual-decision.json','scripts/validate_fresh216.py'};assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
man=load(P/'manifest.json');assert {e['path'] for e in man['files']}==expected-{'manifest.json'} and man['manifest_excludes_self']
for e in man['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh216.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1385)/'actual1097-full401-own-QI-UID-N3-native-typed-role-three-fluid-omissions-previsual-proof.json';qi=load(qip);assert sha(qip)=='310c89eb480db6c2fc55eebd296ea2c37ac42a7dc7e67ec9f3d5918e2411330d'
s=load(P/'metadata/visual-decision.json');a=load(P/'metadata/actual-render-metadata.json');u=load(P/'metadata/upstream-evidence.json');v=load(P/'metadata/png-visual-evidence.json');cl=load(P/'metadata/physical-stage-closure.json');cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_canonical_condition_sha256'];legacy=qi['typed_XMF_actual_legacy_producer_condition_sha256']
for j in [s,a,u,v,cl]:assert j['case_id']==cid and j['physical_case_id']==pid and j['family_id']=='F2'
assert pid=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX056_RY014_FILL080_ROT090' and canonical!=legacy
checked(u['main_qi']);assert u['main_qi']['path']==str(qip) and u['main_qi']['root_QI_is_independent_proof_not_runner_receipt'];er=qi['actual_completed_metadata_evidence'];assert u['actual_completed_metadata_evidence']==er
for k,e in er.items():
 checked(e)
 if k.endswith('_receipt') and k not in {'render_publish_receipt'}:
  rr=load(e['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
assert qi['all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified'] and qi['genuine_initial_QA_receipt_completed0_and_report_pass'] and qi['frames']==401 and qi['particles']==418104
lifecycle=qi['lifecycle_omissions'];assert lifecycle['final_missing_particles']==3 and lifecycle['first_missing_frame']==154 and lifecycle['cumulative_particle_frame_omissions']==635 and lifecycle['producer_attested_final_Idp_sample']==[397194,403829,404024] and not lifecycle['final_Idp_sample_is_partial_not_all3'] and lifecycle['missing_location_state_cause_unknown'];assert cl['typed_lifecycle']['final_missing_Idp_digest_producer_attested']==lifecycle['final_missing_Idp_digest_producer_attested']
assert a['expected_and_actual']['time_window_s']==u['main_qi']['time_window_s']==cl['dimension_and_time']['time_window_s']==qi['actual_time_window_s'];assert cl['initial_native_counts']==qi['actual_initial_type_counts'] and cl['terminal_native_counts']==qi['actual_terminal_type_counts']
n=load(er['native_receipt']['path'])['request'];x=load(er['XMF_manifest']['path']);masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n),('XMF',x)]};assert masks==qi['actual_native_XMF_plan_field_namespaces'];assert n['physical_condition_sha256']==canonical and x['physical_condition_sha256']==legacy
sr=u['producer_scope_roles'];assert sr['canonical_native_request_condition_sha256']==canonical and sr['actual_converter_legacy_scope_sha256']==legacy and not sr['scope_equality_claimed']
for ns,src in [('native','native'),('XMF','xmf')]:
 for name in ['condition','physical_condition']:
  assert sr[f'{src}_source_plan_{name}_field_present']==masks[ns][f'source_plan_{name}_sha256']['present'] and sr[f'{src}_source_plan_{name}_sha256']==masks[ns][f'source_plan_{name}_sha256']['value']
assert not u['source_definition_role']['field_present_in_this_qi_evidence'] and u['source_definition_role']['sha256'] is None and not u['source_definition_role']['source_agent_inference']
dec=s['decision'];assert dec['standalone_first_stage_visual_approved'] and not dec['severe_visual_failure'] and not dec['needs_root_image_intervention'] and dec['independent_case_count_increment']==0
for k in ['q_n_granted','q_e_granted','strict_container_guarantee','sub_dp_penetration_absence_claim','numerical_precision_accepted','large_inundation_or_runup_claim']:assert dec[k] is False
assert s['review_model']==man['model']=='GPT-5.6 Luna max' and not s['recursive_delegation'] and not man['recursive_delegation'];reviewed=s['reviewed_at_utc'];assert reviewed==a['personal_review_scope']['reviewed_at_utc']==man['visual_review']['reviewed_at_utc']
contacts=[{'path':e['absolute_path'],'sha256':e['sha256'],'bytes':e['bytes'],'sheet_index':e['index'],'viewed':e['reviewed']} for e in v['producer_attested_contact_sheets']];keys=[{'path':e['absolute_path'],'sha256':e['sha256'],'bytes':e['bytes'],'frame':e['frame_index'],'viewed':e['reviewed']} for e in v['producer_attested_keyframes']];assert len(contacts)==17 and len(keys)==9 and [e['sheet_index'] for e in contacts]==list(range(17)) and [e['frame'] for e in keys]==list(range(0,401,50))
pub=load(er['render_publish_receipt']['path']);report=load(er['render_report']['path']);receipt=load(er['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['render_report']['path']);pubroot=Path(pub['published_output_root']);pubfiles={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==report['outputs']['contact_sheets']
for e in contacts+keys:
 checked(e);pr=pubfiles[str(Path(e['path']).relative_to(pubroot))];assert e['sha256']==pr['sha256'] and e['bytes']==pr['bytes'] and e['viewed']
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(receipt['finished_at_utc'])<=datetime.datetime.fromisoformat(reviewed.replace('Z','+00:00'))<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_294.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==317 and cp['accepted_per_family']['F2']==44 and pid not in {load(p)['physical_case_id'] for p in cp['accepted_decisions']};ip=root(1393)/'full336-current317-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);target=next(z for z in idx['cases'] if z['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source216_actualF2_RX056ROT090_original1097_full401QI_personal26PNG_three_fluid_omissions_genuineQA_native_XMF_roles_visual_acceptance_1394';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_295.json';assert not O.exists() and not np.exists();O.mkdir()
for n0,b0 in blobs.items():p=R/n0;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b0)
proof=O/'source216-byte-exact-readonly-validator-main26publishedPNG-own401QI-review-time-and-genuineQA-proof.json';put(proof,{'schema':'ds02.main.F2.source216.personal26PNG-adoption-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n0) for n0 in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'independent_ownQI':ref(qip),'all26_publishedPNG_hashes_match_actual_atomic_publish':True,'actual_personal_review_time_utc':reviewed,'review_after_completed_publication':True,'actual_native_XMF_plan_field_namespaces':masks,'canonical_native_and_typed_XMF_legacy_separate_roles_verified':True,'all_actual_primary_refs_and_genuine_QA_receipts_verified':True,'lifecycle_omissions_retained':lifecycle,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F5','source_personal_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':401,'particle_count':418104,'actual_initial_type_counts':qi['actual_initial_type_counts'],'actual_terminal_type_counts':qi['actual_terminal_type_counts'],'actual_type_counts':qi['actual_initial_type_counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all401_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':False,'lifecycle_omissions':lifecycle,'actual_native_XMF_plan_field_namespaces':masks,'nativecanonical_and_typedlegacy_distinct_roles':True,'SourceDef_role_absent_in_QI_not_inferred_from_generated_XML':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'actual_personal_review_time_utc':reviewed,'contact_sheets':contacts,'keyframes':keys,'visual_observations':v['visual_observations'],'visual_limits':s['visual_limitations'],'open_rim_spread_and_sparse_boundary_points_observed':True,'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'historical_negative_flags':cl['historical_negative_evidence'],'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source216-actual1097-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(proof),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1
new.update(checkpoint=295,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=318,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source216 personal17contacts9keys F2 RX056ROT090 original1097 accepted once after full401 own1385/genuineQA/all26pubPNG/mainimmutable-source audit; 3fluid omissions154/635 retained, nativecanonical-typedlegacy-planabsence roles separate.',authorized_work_state='Active318/336 pending18. F2=45 F3=44 F5=37. Source181 F3original1194 personal review active; source217 F2original1009 boundedwait publication/mainown1392; original1158 F5 registeredlaunch continues. Source196 F3 repair active, separate197 F2 and182 F5 required after partial builder audits.')
new['actual_progress']['source216_F2_actual1097_visual_acceptance']=ref(ap);new['source_agents']['f5_bed_recovery']='fresh216 F2original1097 accepted once; fresh217 F2original1009 waiting publication and actualown1392';new['next_executable_tasks']=[x for x in new['next_executable_tasks'] if not x.startswith('Adopt source216')];new['next_executable_tasks'].insert(0,'Adopt source181 F3original1194 personal visual after completed source/validator/own1387/publishedPNG audit, preserve original154 runtimeunknown and actualaudit1166/XMF1193.');assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==318;put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=318,registered_pending_independent_physical_cases=18,new_case_credit=1);target.update(status='visual-approved-in-checkpoint295',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip));idx['actual_unaccepted_completed0_published_physical_cases']=[z for z in idx['actual_unaccepted_completed0_published_physical_cases'] if (z if isinstance(z,str) else z['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==318;put(O/'full336-current318-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX056 ROT090 personal review preservingthree fluid omissions','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':295,'accepted':318,'F2':45,'pending':18,'decision':ref(dp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
