from pathlib import Path
import hashlib,json,subprocess,datetime,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=next(H.glob('root*_1095'));load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)}
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_166.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==256 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_167.json').exists()
dps=sorted(O.glob('*-delegated-visual-decision.json'));assert len(dps)==2
old=[load(p) for p in cp['accepted_decisions']];ids={p.get('physical_case_id',p['case_id']) for p in old};scopes={p['physical_condition_sha256'] for p in old}
for p in dps:
 d=load(p);assert d['physical_case_id'] not in ids and d['physical_condition_sha256'] not in scopes and d['all836_geometry_velocity_N3_times_UIDs_finite_verified'] and d['independent_case_increment']==1
 ids.add(d['physical_case_id']);scopes.add(d['physical_condition_sha256'])
proof=load(O/'source136-two-full836-independent-QI-and-visual-adoption.json');assert proof['previous_accepted']==256 and proof['new_accepted']==258
preflight={'reason':'Late checkpoint observer asserted obsolete live status for Root1083; all scientific and delegated visual case checks completed before failure, two new decisions preserved, no prior case credit was written.','Root1083_terminal_result':ref(next(H.glob('root*_1083'))/'controller-result.json'),'Root1083_real_failure':'Strict pre-launch digest mismatch on mutable Root1055 actual-progress.json; no native/typed/bed rerun required.','Root1083_scientific_render_attempt_receipt_absent':not Path(load(next(H.glob('root*_1083'))/'controller-result.json')['actual_receipt']).exists()}
(O/'original-precredit-observer-failure-and-continuation.json').write_text(json.dumps(preflight,ensure_ascii=False,indent=2)+'\n')
(O/'integration-source-preflight.py').write_bytes(Path('/tmp/ds02-root1095-f3-source136-accept.py').read_bytes())
cp['accepted_per_family']['F3']+=2;cp.update(checkpoint=167,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),stage1_visual_accepted_complete_independent_cases=258,new_accepted_decisions=[str(p) for p in dps],accepted_decisions=cp['accepted_decisions']+[str(p) for p in dps],previous_goal_turn_classification='Progress: independently accepted two fresh136 full836 F3 cases, 258 total/F3=32; scope roles and genuine initial clone+native forcing beforeafter proof retained. Previous turn cleanup515.503GiB current verification1094. Root1083 terminal prelaunch mutable-progress digest mismatch preserved for bounded frozen-record successor; no scientific render started.')
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500
cp.update(home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(z['kind']==k for z in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(z.get('gpu_seconds',0) for z in ledger['charges'])/3600,cpu_core_hours_charged=sum(z.get('cpu_core_seconds',0) for z in ledger['charges'])/3600)
cp['actual_progress']['source136_two_F3_independently_accepted']=ref(O/'source136-two-full836-independent-QI-and-visual-adoption.json');cp['actual_progress']['actual1083_terminal_prelaunch_failed']=ref(next(H.glob('root*_1083'))/'controller-result.json');cp['actual_progress']['cleanup515GiB_current_reverification1094']=ref(next(H.glob('root*_1094'))/'current-cleanup-reverification.json')
p=next(H.glob('root*_1082'))/'controller-launch-process.json';j=load(p);st=Path(f"/proc/{j['pid']}/stat");assert st.exists();fields=st.read_text().split(') ',1)[1].split();assert fields[0]!='Z' and fields[19]==str(j['proc_start_ticks']);cp['actual_progress']['actual1082_same_controller_live']=ref(p)
cp['source_agents'].update(production_recovery='fresh136 accepted258/F3=32; next genuine completed unaccepted full836',f5_bed_recovery='fresh178 acceptedM095T080; fresh179 bed5/render1 disabled handoff active',f6_endpoint_initial_qa='fresh151 bounded incremental failed storage audit active; finalF6Root951 pending realrender')
cp['next_executable_tasks']=[s for s in cp['next_executable_tasks'] if 'fresh136' not in s and 'fresh178' not in s]+['Prepare bounded successor to actual1083 prelaunch digest mismatch with original1055 actual-progress frozen into new immutable path; preserve originals and reuse native/typed/XMF/bed completed outputs.','Integrate fresh179 actual XMF0 owncase disabled bed5/render1 through unchanged registered admission; lastF6onlyafterRoot951realrender0 andpersonalvisual.']
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==258
(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_167.json').write_text(json.dumps(cp,ensure_ascii=False,indent=2)+'\n');(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(Path(x['path']).relative_to(R)) for x in proof['adopted_files']]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_167.json').relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept two F3 full836 visuals and record prelaunch render digest failure','--',*paths],cwd=R,check=True);print({'accepted':258,'families':cp['accepted_per_family'],'Home_free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
