from pathlib import Path
import json,hashlib,xml.etree.ElementTree as ET,datetime,runpy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';O=H/'root_stage1_F2_actual827_three_and_F5_actual832_one_full_event_independent_render_ready_audit_927';O.mkdir(exist_ok=False)
load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix in ['.json','.py','.xml','.xmf','.md'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_122.json');accepted=[load(p) for p in cp['accepted_decisions']];ids={r.get('physical_case_id',r['case_id']) for r in accepted};dig={r['physical_condition_sha256'] for r in accepted};pre=runpy.run_path(str(root(23)/'render.py'))['load_manifest'];rows=[]
for n in [827,832]:
 for qp in sorted((root(n)/'requests').glob('*-xmf-request.json')):
  q=load(qp);ap=Path(q['attempt_root']);rp=ap/'execution-receipt.json';rr=load(rp) if rp.exists() else {}
  if (rr.get('status'),rr.get('returncode'))!=('completed',0):continue
  assert rr['request_sha256']==sha(qp);mp=ap/'xdmf/manifest.json';m=pre(mp);f=m['family_id'];frames,N,last=(401,418104,4) if f=='F2' else (801,194427,16);assert f in ['F2','F5'];cp=Path(m['conversion_report']);c=load(cp);tr=Path(m['typed_receipt']);nr=Path(m['native_receipt']);assert all((load(p)['status'],load(p)['returncode'])==('completed',0) for p in [tr,nr]);assert c['conversion_status']=='completed' and c['frames']==frames and c['particles']==N and c['solver_dimension']['solver_dimension']==3 and c['partvtk_validation']['all_passed'] and c['time_evidence']['last_s']>=last;assert m['frames']==frames and m['particles']==N and m['source_h5_read_only'] and m['source_h5_sha256']==c['output_sha256'] and m['trajectory_h5']==c['output_hdf5'];legacy=c['hash_scopes']['physical_condition_sha256'];canonical=m['canonical_source_physical_condition_sha256'] if f=='F2' else m['physical_condition_sha256'];assert (m['physical_condition_sha256'] if f=='F2' else m['source_h5_physical_condition_sha256'])==legacy;assert canonical!=legacy and m['physical_case_id'] not in ids and canonical not in dig;xf=Path(m['xdmf']);assert sha(xf)==m['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==frames and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')==f'{N} 3' for g in gs);bed=[]
  if f=='F5':
   bqp=qp.with_name(qp.name.replace('-xmf-request.json','-bed-request.json'));bq=load(bqp);br=Path(bq['attempt_root'])/'execution-receipt.json';brr=load(br);assert (brr['status'],brr['returncode'])==('completed',0) and brr['request_sha256']==sha(bqp);bp=Path(bq['attempt_root'])/'audit-output/c082s1-full-event-bed-footprint-audit.json';b=load(bp);assert len(b['frame_reports'])==801 and b['physical_condition_sha256']==canonical and b['source_h5_physical_condition_sha256']==legacy;assert bq['physical_case_id']==m['physical_case_id'];bed=[ref(p) for p in [bqp,br,bp]]
  rows.append({'family_id':f,'case_id':m['case_id'],'physical_case_id':m['physical_case_id'],'source_root':n,'xmf_request':ref(qp),'actual_xmf_receipt':ref(rp),'actual_manifest':ref(mp),'actual_xdmf':ref(xf),'actual_native_receipt':ref(nr),'actual_typed_receipt':ref(tr),'actual_conversion_report':ref(cp),'frames':frames,'particles':N,'N3_grid_count':len(gs),'actual_last_time_s':c['time_evidence']['last_s'],'canonical_source_physical_condition_sha256':canonical,'actual_converter_legacy_scope_sha256':legacy,'source_manifest_scope_sha256':m['physical_condition_sha256'],'scope_equality_not_claimed':True,'producer_h5_sha256':c['output_sha256'],'bed_evidence':bed,'bed_diagnostic_only':bool(bed),'full_event_render_required':True,'visual_approval_required':True,'scientific_payload_IO_by_main':False,'case_credit':0});ids.add(m['physical_case_id']);dig.add(canonical)
assert len(rows)==4 and sum(r['family_id']=='F2' for r in rows)==3
old=root(887);lc=load(old/'controller-launch-process.json');pr=Path('/proc')/str(lc['pid']);ps=(pr/'stat').read_text().split(') ',1)[1].split() if pr.exists() else [];alive=bool(ps and ps[0]!='Z' and ps[19]==lc['proc_start_ticks']);assert sha(lc['controller'])==lc['controller_sha256'];oldobs={'launch':ref(old/'controller-launch-process.json'),'live_same_handle':alive,'state':ps[0] if ps else None,'original_terminal_result_present':(old/'controller-result.json').exists(),'root860_retirement_proof':ref(root(920)/'metadata-only-original860-retirement-proof.json'),'no_old_result_fabricated':True,'old_cross_family_gate_replacement_must_be_distinct':True}
proof={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_ready_full_event_cases':4,'cases':rows,'old887_observation':oldobs,'shared_registration_required':True,'next_step':'Use reviewed capped generic NVMe Root023 renderer as distinct percase actual requests; preserve old832/827 completed artifacts and original source scopes. Never wait for entire unrelated F6 batch.','scientific_payload_not_read_or_hashed':True,'case_credit':0};(O/'actual-independent-four-ready-audit.json').write_text(json.dumps(proof,indent=2)+'\n');(O/'ready-audit-source.py').write_bytes(Path(__file__).read_bytes());print({'actual_ready4':True,'F2':3,'F5':1,'no_count_increment_before_full_visual':True,'old887_live':alive})
