from pathlib import Path
import json,hashlib,datetime,subprocess,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_F5_actual1006_5_own_completed_typed_full801_original129_N3_XMF_fairCPU2_1071';O.mkdir(exist_ok=True);assert not (O/'controller-config.json').exists();(O/'requests').mkdir(exist_ok=True);(O/'bindings').mkdir(exist_ok=True)
base=load(root(968)/'enabled-XMF-request.json');worker=Path(base['command'][1]);expected=base['input_sha256'][str(worker)];assert sha(worker)==expected
fair=root(928)/'fair_CPU_dispatch.py';controller=O/'batch-xmf-controller.py';text=(root(990)/'batch-xmf-controller.py').read_text().replace('==836','==801').replace('==179208','==194427').replace('actual_full836_N3_XMF_pass','actual_full801_N3_XMF_pass').replace("/'xdmf/manifest.json'","/'xmf/manifest.json'");controller.write_text(text)
progress=load(root(1006)/'actual-progress.json');rows=[r for r in progress['results'] if r['tag'] in ['M106_T085', 'M106_T095', 'M108_T085', 'M108_T095', 'M110_T085']];assert len(rows)==5 and {r['tag'] for r in rows}=={'M106_T095', 'M108_T095', 'M106_T085', 'M110_T085', 'M108_T085'};cfg=load(root(1006)/'controller-config.json');sourceqs={load(p)['tag']:p for p in cfg['requests']};cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_163.json');ids={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};qs=[];proofs=[]
for row in rows:
 assert (row['status'],row['returncode'])==('completed',0) and row['actual_full801_typed_pass'];sp=Path(sourceqs[row['tag']]);q0=load(sp);ar=Path(q0['attempt_root']);tr=ar/'execution-receipt.json';tp=ar/'conversion-report.json';rec=load(tr);t=load(tp);np=Path(q0['actual_native_receipt']);nr=load(np);gp=Path(q0['gencase_receipt']);gr=load(gp);qap=Path(q0['actual_initial_qa_report']);qar=Path(q0['actual_initial_qa_receipt']);qa=load(qap)
 assert rec['request_sha256']==sha(sp) and all((r['status'],r['returncode'])==('completed',0) for r in [rec,nr,gr,load(qar)]) and q0['physical_case_id'] not in ids
 assert t['conversion_status']=='completed' and t['frames']==801 and t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames'])
 assert t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0' and t['hash_scopes']['physical_condition_sha256']==q0['expected_converter_scope_sha256'] and t['hash_scopes']['physical_condition']['physical_case_id']==q0['physical_case_id']
 assert nr['request']['physical_condition_sha256']==q0['physical_condition_sha256'] and t['source_provenance']['solver_receipt']==ref(np) and t['source_provenance']['gencase_receipt']==ref(gp) and t['source_provenance']['generated_xml']==ref(q0['generated_xml'])
 assert t['output_hdf5']==str(ar/'trajectory.h5') and Path(t['output_hdf5']).stat().st_size<4*1024**3 and qa['all_basic_placement_checks_pass'] and not qa['numerical_precision_result_accepted']
 fs=t['lifecycle']['frame_summary'];assert len(fs)==801 and fs[0]['time']==0 and fs[-1]['time']>=16 and all(a['time']<z['time'] for a,z in zip(fs,fs[1:])) and t['lifecycle']['introduced_ids']=='rejected'
 for i,f in enumerate(fs):assert f['frame']==i and f['active_particles']==194427 and f['missing_particles']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658}
 aid='root-stage1-f5-'+q0['tag'].lower()+'-actual1006-full801-N3-xmf129-root1071';out=D/'families/F5'/q0['case_id']/aid;assert not out.exists();actualscope=t['hash_scopes']['physical_condition_sha256'];canonical=q0['physical_condition_sha256'];plan=q0['source_plan_physical_condition_sha256'];assert actualscope!=canonical and plan in [canonical,sha(q0['source_definition'])]
 source_scope_note={'original_immutable_typed_request':ref(sp),'original_inherited_nested_scope_not_used_as_identity_evidence':q0['canonical_physical_scope'],'actual_native_canonical_scope':nr['request']['physical_condition_sha256'],'actual_converter_legacy_scope':actualscope,'outer_typed_request_plan_role':plan,'actual_native_request_plan_role':nr['request'].get('source_plan_physical_condition_sha256'),'source_plan_roles_may_differ_and_both_original_values_preserved':True,'source_definition_current_file_sha256':sha(q0['source_definition']),'actual_roles_verified_from_own_native_typed_receipts':True,'science_payload_IO_by_primary':False}
 assert sha(q0['source_definition'])==q0['source_definition_sha256'];put(O/(q0['tag']+'-original-inherited-nested-scope-closure.json'),source_scope_note)
 b={k:v for k,v in q0.items() if k not in ['command','input_files','input_sha256','input_sha256_categories','input_sha256_provenance','environment_policy','attempt_root']}
 b['root_original_nested_scope_preserved']=source_scope_note
 b['canonical_physical_scope']={'schema':'ds02.f5.actual-native-canonical-physical-scope.v1','physical_condition_sha256':canonical,'source_plan_physical_condition_sha256':plan,'source_definition_sha256':sha(q0['source_definition']),'canonical_and_source_plan_are_distinct':canonical!=plan,'actual_native_receipt':ref(np),'old_nested_other_scope_not_used':True}
 b.update(schema='ds02.f5.actual1006-full801-typed-to-N3-XMF-binding.v1',disabled=False,source_only=False,execution_allowed=True,launch_allowed=True,case_id=q0['case_id'],physical_case_id=q0['physical_case_id'],physical_condition_sha256=canonical,source_plan_physical_condition_sha256=plan,trajectory_h5=t['output_hdf5'],trajectory_h5_sha256=t['output_sha256'],source_h5_physical_condition_sha256=actualscope,source_h5_scope_schema='legacy-owner-scope.v0',source_h5_scope_status='legacy_incomplete; no cross-resolution physical claim',source_h5_legacy_scope={'schema':'legacy-owner-scope.v0','sha256':actualscope,'status':'legacy_incomplete; no cross-resolution physical claim'},physical_condition_hash_semantics={'canonical_owner_sha256':canonical,'source_h5_sha256':actualscope,'source_h5_scope_schema':'legacy-owner-scope.v0','source_h5_scope_status':'legacy_incomplete; no cross-resolution physical claim','source_plan_sha256':plan,'roles_remain_distinct':True},typed_receipt=str(tr),typed_receipt_sha256=sha(tr),typed_request=str(sp),typed_request_sha256=sha(sp),conversion_report=str(tp),conversion_report_sha256=sha(tp),full_typed_conversion_report=str(tp),full_typed_conversion_report_sha256=sha(tp),full_typed_receipt=str(tr),full_typed_receipt_sha256=sha(tr),full_typed_attempt_id=q0['attempt_id'],native_receipt=str(np),native_receipt_sha256=sha(np),full_native_receipt=str(np),full_native_receipt_sha256=sha(np),initial_qa_receipt=str(qar),initial_qa_receipt_sha256=sha(qar),initial_qa_report=str(qap),initial_qa_report_sha256=sha(qap),canonical_generated_xml=q0['generated_xml'],canonical_generated_xml_sha256=sha(q0['generated_xml']),expected_frames=801,expected_particles=194427,expected_particle_axis=194427,physical_window_s=[0.0,16.0],root_actual_XMF_attempt_id=aid,full801_authorized=True,future_output_hashes={'xmf_manifest_sha256':None,'xdmf_sha256':None,'execution_receipt_sha256':None},xdmf=str(out/'xmf/case.xmf'),xmf_manifest=str(out/'xmf/manifest.json'),xmf_receipt=str(out/'execution-receipt.json'),xmf_receipt_sha256=None,xmf_manifest_sha256=None,xdmf_sha256=None)
 bp=O/'bindings'/(q0['tag']+'-actual1006-full801-binding.json');put(bp,b);md={}
 for p,d in q0['input_sha256'].items():
  if Path(p).suffix in {'.json','.xml','.py','.md'}:assert sha(p)==d;md[p]=d
 for p in [sp,bp,worker,controller,fair,tp,tr,np,gp,qap,qar,L/'scripts/ds_data02_strict_dispatch_v1.py',L/'scripts/ds_data02_runtime_v2.py',root(142)/'launch.py',root(142)/'root_home_floor_inventory_policy.py',root(64)/'resource-window-approval.json']:md[str(p)]=sha(p)
 py=str(L/'.venv/bin/python');md[py]=rec['input_hashes_at_launch'][str(Path(py).resolve())];assert md[py]==rec['input_hashes_after_run'][str(Path(py).resolve())];md[t['output_hdf5']]=t['output_sha256']
 q={k:base[k] for k in ['schema','launch_owner','cwd','worktree_root','environment_policy','root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','science_input_policy']};q.update(kind='cpu',cpu_task_kind='audit',cpu_threads=2,max_wall_seconds=7200,estimated_storage_bytes=1024**3,family_id='F5',case_id=q0['case_id'],physical_case_id=q0['physical_case_id'],physical_condition_sha256=canonical,attempt_id=aid,attempt_root=str(out),command=[py,str(worker),'--binding',str(bp),'--output-dir','{attempt_root}/xmf'],disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,input_files=sorted(md),input_sha256=md,actual_typed_H5_SHA_from_producer_only=t['output_sha256'],q_n_granted=False,q_e_granted=False,case_credit=0)
 qp=O/'requests'/(q0['tag']+'-enabled-XMF-request.json');put(qp,q);qs.append(str(qp));proofs.append({'tag':q0['tag'],'physical_case_id':q0['physical_case_id'],'actual_typed_receipt':ref(tr),'actual_typed_report':ref(tp),'actual_native_receipt':ref(np),'actual_GenCase_receipt':ref(gp),'actual_initial_QA_receipt':ref(qar),'all801_original_native_UIDs_retained':True,'final_time_s':fs[-1]['time'],'source_canonical_scope':canonical,'actual_converter_legacy_scope':actualscope,'source_plan_scope':plan,'H5_SHA_producer_only':t['output_sha256'],'source_H5_bytes_stat_only':Path(t['output_hdf5']).stat().st_size,'enabled_request':ref(qp),'binding':ref(bp),'scientific_payload_IO_by_primary':False})
put(O/'controller-config.json',{'requests':qs,'request_sha256':{p:sha(p) for p in qs},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'case_credit':0});put(O/'three-actual1006-full801-independent-QI-and-XMF-registration.json',{'cases':proofs,'original129_legacy_aware_XMF_worker':ref(worker),'actual_basic_placement_QA_pass':True,'historical_precision_negatives_retained':True,'future_XMF_hashes_null':True,'science_payload_IO_by_primary':False,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close three actual full801 F5 conversions and register original legacy-aware N3 XMF products','--',*paths],cwd=R,check=True);print({'root':str(O),'cases':len(qs),'worker_sha':expected,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
