from pathlib import Path
import json,hashlib,subprocess,datetime,runpy,re,os,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.jsonl','.py','.md','.xml','.xmf','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
old=root(816);progress=load(old/'controller-result.json');assert progress['requested']==24 and progress['completed0']==3 and progress['pending_held']==20;failed=Path(progress['results'][-1]['actual_receipt']);fr=load(failed);assert fr['status']=='failed' and fr.get('returncode') is None and fr['error']=='RuntimeError: Home free-space floor would be crossed'
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_138.json');accepted={load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']};sources=[p for p in sorted((old/'requests').glob('*.json')) if load(p)['physical_case_id'] not in accepted];assert len(sources)==21
O=H/'root_stage1_F2_actual816_Home_floor_failure_after_cleanup_21_full401_typed157_hard4GiB_fairCPU2_995';O.mkdir(exist_ok=False);(O/'requests').mkdir();proof=O/'actual816-HOME-floor-failure-and-cleanup-recovery.json';free=shutil.disk_usage('/home/jade').free/1024**3;assert free>=500;put(proof,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_original_controller':ref(old/'controller-result.json'),'actual_home_floor_failure_receipt':ref(failed),'failed_original_attempt_not_reclassified':True,'actual_cleanup_reclaimed_GiB':439.00610971078277,'cleanup_independent_review':ref(root(966)/'actual-cleanup-independent-review.json'),'Home_free_GiB_live':free,'Home_floor_GiB':500,'new_conversion_wrapper':'Existing unchanged registered157 hard4GiB home/NVMe24GiB/100GiB reserve; direct scientific converter unchanged.','full401_native_simulations_reused':True,'native_solver_not_repeated':True,'science_payload_IO_by_primary':False,'case_credit':0})
base=load(root(974)/'enabled-typed-request.json');worker=Path(base['command'][1]);assert sha(worker)=='37fe7eaff4405e9ba6d9b7f666a53d7c02ee65fc6f30992fc1a8fdb0d8a61b11';fair=root(928)/'fair_CPU_dispatch.py';controller=O/'batch-typed-controller.py';text=(root(988)/'batch-typed-controller.py').read_text().replace("t.get('frames')==801","t.get('frames')==401").replace("t.get('particles')==194427","t.get('particles')==q['expected_particles']").replace("'tag':q['tag'],","'tag':q['case_id'],").replace('actual_full801_typed_pass','actual_full401_typed_pass');controller.write_text(text)
conv=runpy.run_path(str(L/'scripts/ds_data02_direct_convert.py'));actual974=load(Path(base['attempt_root'])/'execution-receipt.json');toolpaths=[str(L/'.venv/bin/python'),'/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/campaigns/l1-resume/artifacts/bi4_dump','/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/vendor/official/DualSPHysics_v5.4/bin/linux/PartVTK_linux64'];toolmd={}
for tool in toolpaths:
 resolved=str(Path(tool).resolve());h=actual974['input_hashes_at_launch'][resolved];assert actual974['input_hashes_after_run'][resolved]==h and hashlib.sha256(Path(tool).read_bytes()).hexdigest()==h;toolmd[tool]=h
qs=[];rows=[];scopes=set()
for sp in sources:
 q=load(sp);assert q['expected_frames']==401 and q['cpu_threads']==2 and q['kind']=='cpu';nr=load(q['native_receipt']);gr=load(q['gencase_receipt']);assert (nr['status'],nr['returncode'])==(gr['status'],gr['returncode'])==('completed',0);assert nr['request']['case_id']==q['case_id'] and nr['request']['physical_case_id']==q['physical_case_id'] and nr['request']['physical_condition_sha256']==q['physical_condition_sha256']
 owner=Path(q['owner_metadata']);ow=load(owner);assert ow['physical_case_id']==q['physical_case_id'];scope=conv['canonical_hash'](conv['_physical_condition_scope'](ow));assert scope==q['actual_converter_scope_sha256_prospective'] and q['physical_case_id'] not in scopes;scopes.add(q['physical_case_id'])
 argv=q['command'];rawargs=argv[argv.index('--')+1:];dr=Path(rawargs[rawargs.index('--data-root')+1]);frames=sorted(p.name for p in dr.iterdir() if re.fullmatch(r'Part_[0-9]+\.bi4',p.name));assert frames==[f'Part_{i:04d}.bi4' for i in range(401)]
 xml=Path(rawargs[rawargs.index('--generated-xml')+1]);assert nr['input_hashes_at_launch'][str(xml)]==nr['input_hashes_after_run'][str(xml)]==sha(xml)
 aid=q['attempt_id'].replace('typed-nvme-root816','typed157-home4gib-after-cleanup-root995');ar=D/'families/F2'/q['case_id']/aid;assert not ar.exists();current=f"F2/{q['case_id']}/{aid}";cache='/tmp/ds02-nvme-typed-cache-root995-'+q['case_id'].lower();assert not Path(cache).exists()
 assert rawargs[rawargs.index('--decoder')+1]==toolpaths[1] and rawargs[rawargs.index('--partvtk')+1]==toolpaths[2]
 cmd=[str(L/'.venv/bin/python'),str(worker),'--staging-root',cache,'--staging-limit-bytes',str(24*1024**3),'--nvme-free-reserve-bytes',str(100*1024**3),'--home-publish-cap-bytes',str(4*1024**3),'--home-floor-bytes',str(500*1024**3),'--home-publish-headroom-bytes',str(2*1024**3),'--home-root','/home/jade','--resource-ledger',str(D/'runtime/resource-ledger.json'),'--resource-ledger-lock',str(D/'runtime/resource-ledger.lock'),'--current-attempt-id',current,'--',*rawargs]
 md={}
 for p,h in q['input_sha256'].items():
  if Path(p).suffix in {'.json','.xml','.py','.md'}:assert sha(p)==h;md[p]=h
 for p in [worker,controller,fair,sp,proof,owner,Path(q['native_receipt']),Path(q['gencase_receipt'])]:md[str(p)]=sha(p)
 md.update(toolmd);q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']});q.update(attempt_id=aid,attempt_root=str(ar),current_attempt_id=current,command=cmd,input_files=sorted(md),input_sha256=md,estimated_storage_bytes=4*1024**3,expected_converter_scope_sha256=scope,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,root_recovered_HOME_floor_original_request=ref(sp),case_credit=0)
 qp=O/'requests'/(q['case_id']+'-enabled-typed-request.json');put(qp,q);qs.append(str(qp));rows.append({'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'source_native_condition_sha256':q['physical_condition_sha256'],'prospective_actual_converter_v0_scope':scope,'expected_frames':401,'expected_particles':q['expected_particles'],'native_full401_filenames_verified':True,'actual_native_receipt':ref(q['native_receipt']),'actual_GenCase_receipt':ref(q['gencase_receipt']),'owner_metadata':ref(owner),'enabled_request':ref(qp),'no_future_H5_hash_claim':True,'scientific_payload_IO_by_primary':False})
put(O/'controller-config.json',{'requests':qs,'request_sha256':{p:sha(p) for p in qs},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'cooperative_yield_between_admitted_jobs_seconds':4,'case_credit':0});put(O/'twentyone-actual812-native-independent-recovery-registration.json',{'cases':rows,'actual816failure_preserved':ref(failed),'existing_home4GiB_converter_worker_unchanged':ref(worker),'native_solver_repeats':0,'actual_tool_binary_digests_match974_before_after':True,'full401_frames_and_particle_count_not_reduced':True,'strict142928_sources_unchanged':True,'science_payload_IO_by_primary':False,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: resume twenty-one real full401 F2 cases with capped unchanged typed converter after storage recovery','--',*paths],cwd=R,check=True);print({'root':str(O),'cases':len(qs),'Home_free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
