from pathlib import Path
import json,hashlib,datetime,shutil,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.xml','.xmf','.md','.log'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_231_visual_failed439GiB_cleanup_preserved_F5typed5_F3render2_live_downstream_checkpoint_1030';O.mkdir(exist_ok=False);cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_152.json');accepted=[load(p) for p in cp['accepted_decisions']];assert len(accepted)==sum(cp['accepted_per_family'].values())==231
ids=[a.get('physical_case_id',a['case_id']) for a in accepted];assert len(ids)==len(set(ids));assert all(not a.get('q_n_granted',False) and not a.get('q_e_granted',False) for a in accepted)
cleanup=load(root(966)/'actual-cleanup-independent-review.json');checks={}
for key in ['actual_registered_cleanup_receipt','actual_cleanup_result','deletion_journal','manifest']:
 a=cleanup[key];checks[key]=sha(a['path'])==a['sha256'];assert checks[key]
journal=[json.loads(line) for line in Path(cleanup['deletion_journal']['path']).read_text().splitlines()];assert len(journal)==15995 and all(not Path(z['path']).exists() for z in journal)
put(O/'cleanup439GiB-original-receipts-and15995-absences-reverified.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_cleanup_independent_review':ref(root(966)/'actual-cleanup-independent-review.json'),'checks':checks,'failed_attempts_cleaned':14,'actual_deleted_files':15995,'deleted_files_still_absent':15995,'allocated_GiB_freed':cleanup['deleted_allocated_bytes']/2**30,'no_additional_deletions':True,'valid_accepted_pending_live_reusable_scientific_data_preserved':True,'main_scientific_payload_IO':False})
observations=[]
for n in [951,972,978,983,984,987,988,991,998,1002,1003,1004,1006,1008,1009,1010,1012,1013,1014,1015,1016,1017,1020,1025,1026,1028]:
 o=root(n);e={'root':n,'live':False,'case_credit':0}
 for p in o.glob('*launch*.json'):
  a=load(p)
  if not isinstance(a,dict) or not a.get('pid'):continue
  st=Path(f"/proc/{a['pid']}/stat")
  if st.exists():
   f=st.read_text().split(') ',1)[1].split()
   if f[0]!='Z' and f[19]==str(a.get('proc_start_ticks',a.get('start_ticks'))):e.update(live=True,pid=a['pid'],start_ticks=f[19],actual_launch_receipt=ref(p))
 for name in ['actual-progress.json','controller-result.json']:
  p=o/name
  if p.exists():
   z=O/f'root{n}-{name}-frozen.json';z.write_bytes(p.read_bytes());e[name]=ref(z)
 if (o/'controller-config.json').exists():
  cfg=load(o/'controller-config.json');rr=[];pending=[]
  for qp in cfg.get('requests',[cfg['request']] if cfg.get('request') else []):
   q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';item={'case_id':q['case_id'],'physical_case_id':q.get('physical_case_id'),'request':ref(qp),'actual_receipt_path':str(rp),'case_credit':0}
   if rp.exists():
    r=load(rp);item.update(actual_receipt=ref(rp),status=r['status'],returncode=r.get('returncode'));rr.append(item)
   else:pending.append(item)
  e['actual_scientific_receipts']=rr;e['pending_no_terminal_receipt']=pending
 observations.append(e)
put(O/'actual_live_handles_and_terminal_metadata_observations.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'processes':observations,'no_quiet_or_live_workers_restarted':True,'main_scientific_payload_IO':False,'case_credit':0})
put(O/'actual_new_downstream_registrations_and_acceptances.json',{'accepted231':{'F5_M086T085':ref(root(1023)/'actual969-full801-bed-QI-972-render-source171-independent-closure.json'),'F6_two_delegated143':ref(root(1024)/'adoption-and-two-case-independent-review.json'),'F3_P0800AY0320_delegated131':ref(root(1027)/'source131-adoption-one-full836-independent-QI-and-visual-review.json'),'F6_two_delegated144':ref(root(1029)/'adoption-and-two-case-independent-review.json')},'F3_actual_XMF0_two_full836_render_registrations':[ref(root(n)/'enabled-full836-render-request.json') for n in [1025,1026]],'F5_real_native1017_five_typed157_Home4GiB_requests':ref(root(1028)/'controller-config.json'),'F5_source172_incorrect_subset_scope_preserved_actual_full_converter_metadata_scope_expected':[ref(p) for p in sorted(root(1028).glob('*-scope-subset-correction.json'))],'F5_source171_false_positive_dedup_original_preserved_actual_physical_id_scope_new_case':True,'F5_complete_native48_does_not_imply_visual48':True,'conversion_global_serial_cap':1,'render_shared_cap':2,'Home_floor_GiB':500,'Q_N_Q_E_granted':False,'no_new_native_jobs_this_turn':True})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free;assert free>=500*2**30
cp.update(checkpoint=153,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_152.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_152.json'),new_accepted_decisions=[],home_free_gib=free/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),active_reservations=ledger['reservations'],attempt_counts={k:sum(v['kind']==k for v in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(v.get('gpu_seconds',0) for v in ledger['charges'])/3600,cpu_core_hours_charged=sum(v.get('cpu_core_seconds',0) for v in ledger['charges'])/3600,previous_goal_turn_classification='Progress: full existing F5 one, F6 four and F3 one actual visual chains independently accepted231; original failed439GiB cleanup receipts/journal/plan unchanged and15995deleted files remain absent. Actual native0 two F3 XMF full836 renders1025/1026 and five F5 typed157 capped outputs1028 registered and same fair handles live. Source172 incomplete prospective scope fixed before dispatch using unchanged actual converter metadata helper; originalsource immutable, no scientific reruns or numerical grant.')
cp['actual_progress']['231_visual_live_downstream_storage439GiB_reverification']=ref(O/'actual_new_downstream_registrations_and_acceptances.json');cp['actual_progress']['actual_process_handles_and_frozen_producer_results']=ref(O/'actual_live_handles_and_terminal_metadata_observations.json');cp['actual_progress']['storage_cleanup_reverification']=ref(O/'cleanup439GiB-original-receipts-and15995-absences-reverified.json')
cp['source_agents']={'f5_bed_recovery':'fresh172 actual1017 native0 five typed157 accepted toRoot1028 after original converter complete metadata scope correction; fresh173 remaining6 actual1017 typed disabled requests plus same984/1016 observations active','f6_endpoint_initial_qa':'fresh143/144 four F6 full241 personal and independent native/omega/H5 closure accepted toF6=35; fresh145 next completed951 full241 personal visuals plus actual F2 typed0 census active','production_recovery':'fresh131 actual1004 full836 personal and independent initialclone/forcing/scope closure accepted F3=18; fresh132 three uncounted original P1000 full836 ready visual cases active'}
cp['next_executable_tasks']=['Adopt fresh173 remaining6 actual1017 F5 native0 typed157 requests only upon real full801/QA/GenCase/tool/prospective full converter scope closure; keep all future product hashes null.','Observe same984 full801 M095T080 renderer; delegate allcontacts/keys only upon actual completed0. Observe1016 original138 bed three; actualall801 diagnostic closure enables subsequent bounded116023 render.','Integrate fresh132 up to3 original P1000 realfull836 complete pipeline visuals, legacy079/sourcecanonical scopes exactinitial056/058 genuineQA plus unchangedforcing realbefore/after digest; avoid motheralias duplicate.','Integrate fresh145 completed951 F6 full241 personal visual with actual omega-state0 and H5audit, exacttimes and allUID lifecycle exclusions; retain128physical/256native mass distinction andunknown missingUIDstates.','F2 real812native0 conversions1013/1020 sharedserialCPU2 remain same handles; truecompletedtyped0 only to original108 N3 XMF then full401 bounded render, noGPU rerun.','F3 original1002 full3 XMF nowactual0, actual1010/1014 genuine downstream continue; two new1025/1026 and old987/1003/1015 sameboundedfull836 render handles preserve live workers, next readycases delegatedreview.','Finish actualF5source169+1017 complete48 native downstream conversion/bed/N3XMF/full801 renderer and personalvisual, do not count rawworker0 as visual pass.','Preserve failed-native receipts/header/firstlast evidence and validaccepted/pending/reusable outputs. User-authorized failed439GiB cleanup complete; Home≥500GiB checked live, attemptbudget/timecumulative unchanged; goal336 staysactive.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_153.json',cp);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_153.json').relative_to(R))]
for n in [1025,1026,1028]:paths.extend(str(p.relative_to(R)) for p in root(n).glob('*launch*.json'))
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: checkpoint231 full visual cases cleanup439GiB and actual capped downstream dispatch','--',*paths],cwd=R,check=True);print({'accepted':231,'counts':cp['accepted_per_family'],'Home_free_GiB':cp['home_free_gib'],'GPU_h':cp['gpu_hours_charged'],'CPU_core_h':cp['cpu_core_hours_charged'],'attempts':cp['attempt_counts'],'live_roots':[v['root'] for v in observations if v['live']],'cleanup_deleted_files_still_absent':15995,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
