from pathlib import Path
import json,hashlib,copy,datetime,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_267.json';cp=load(cpfile);assert cp['checkpoint']==267 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==307
entry=root(1351)/'after_original_terminal_full801_own_QI.py';front=[]
for original,pid,start,qi,source in [(1150,580550,'213516990',1349,210),(1157,584196,'213555954',1350,191)]:
 F=root(original);term=F/'controller-result.json';live=None;p=Path(f'/proc/{pid}')
 if p.exists():
  stat=p.joinpath('stat').read_text().split(') ',1)[1].split();assert stat[19]==start;cmd=p.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);live={'pid':pid,'startticks':start,'state':stat[0],'private_frame_filenames_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 front.append({'original':original,'same_live_process':live,'actual_terminal':ref(term) if term.exists() else None,'durable_own_QI_command':['python3','-B',str(entry),str(original),str(qi)],'future_own_QI_root':qi,'future_own_QI_proof':None,'personal_review_source':source,'no_restart':True,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
O=H/'root_stage1_current307_F6_actual_final48_particle_rigid_delivery_closed_next_original1150_1157_same_live_QI1349_1350_storage534GiB_preserved_1354';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_268.json';assert not O.exists() and not np.exists();O.mkdir();pp=O/'current307-completed-F6-final48-next-two-original-F5-same-live-and-storage-proof.json';put(pp,{'schema':'ds02.main.current307-completedF6-nextF5-frontier.v1','at_utc':now.isoformat(),'actual_F6_complete48_primary_delivery':cp['actual_progress']['F6_final48_complete_particle_rigid_primary_delivery'],'actual_F3_source209_personal44PNG_adoption':cp['actual_progress']['source209_F3_actual1102_visual_acceptance'],'actual_F2_source175_personal26PNG_adoption':cp['actual_progress']['source175_actualF2_1155_visual_acceptance'],'next_original_F5_actual_processes':front,'durable_own_QI_entrypoint':ref(entry),'cleanup_status_ref_no_new_failed_outputs_at_prior_refresh':cp['actual_progress']['current_user_storage_no_new_failed_results'],'current_Home_free_GiB':free,'current_storage_floor_GiB':500,'case_credit':0,'scientific_payload_IO':False,'scope_corrections_preserved':['source209 render-report digest transcription in two sourcefields explicitly corrected by main sidecar; source bytes preserved','source175 initial_qa stage pointed at metadata QI with synthetic completed/0; genuine same-native initialQA receipt recovered','source190 baseline native/typed/XMF refs and three other typed-group omissions recovered from existing same-case manifests; true nativeconditionabsence and baseline fullCSVTimevector/Part uncertainty retained']})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=268,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active307/336,29pending: F1/F4/F6/F7 complete48 each; F2=43,F3=42,F5=30. F6 final48 actual particle-rigid primary delivery integrated and baseline receipt/typed omissions recovered without filling true scope or CSV/Part absences. Next originalF5 1150/1157 same-process renderer advancement, ownQI1349/1350 durable commands ready, personalfresh210/191 assigned. User cleanup cumulative534.4086GiB, Home floor500 protected, no new safe deletion identified.',previous_goal_turn_classification='PROGRESS: actualF3 own836QI plus source209 personal44PNG and actualF2 own401QI plus source175 personal26PNG accepted306 then307. CompleteF6 final48 particle/rigid primary delivery integrated with4 existing-primary reference recoveries, preserving genuine absence and numerical limitations. Next two F5 same-process handles advance and ownQI1349/1350 recovery entrypoints registered; storage safe cleanup534.4086GiB unchanged.')
new['actual_progress']['current307_F6_complete48_next_originalF5_live']=ref(pp);new['next_executable_tasks']=['Observe same actual originalF5 1150 PID580550/start213516990 and 1157 PID584196/start213555954; if handles exit, read actual authoritative terminal/pub metadata. Never restart due to polling timeout.','Execute durable Root1351 after_original_terminal_full801_own_QI.py 1150 1349 or 1157 1350 once only AFTER real completed0/pub; actual native and XMF physical-plan canonical are distinct from bed SourceDef FILE and typed legacy.','Supply exact ownQI proof path/SHA to source210 F5 M106T095 and reactivate source191 F5 M100T080 for personal34contacts9keys; source191 bounded earlier poll returned pending with no package, not a render failure.','Adopt next personal reviews and continue remaining29 original cases; use idle production_recovery for next newly published case, avoid repeating existing mothers/SCI or partial-family catalogs.','After F2/F3/F5 reach48, produce their complete48 own-primary catalogs and integrate all7 final336 delivery; preserve frozen8/actual24 subsets, numerical/external unknown status, all raw namespace/legacy/orphan/omission boundaries.','Preserve Home500GiB and cumulative534.4086GiB cleanup; only fresh failed-unused evidence permits new deletion, retain consumed and diagnostic assets.'];put(np,new)
ip=root(1353)/'full336-current307-actual-final48-delivery-progress-index.json';index=load(ip);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,current307_F6_complete48_next_originalF5_live=ref(pp));assert sum(bool(x.get('accepted_decision')) for x in index['cases'])==307;put(O/'full336-current307-actual-final48-delivery-progress-index.json',index);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: checkpoint307 completed F6 delivery and next two original F5 live recovery','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':268,'accepted':307,'pending':29,'home_free_GiB':free,'frontier':front,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
