from pathlib import Path
import json,hashlib,subprocess,datetime,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def check(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def check_refs(d):
 if isinstance(d,dict):
  if 'path' in d and 'sha256' in d:check(d)
  else:
   for v in d.values():check_refs(v)
 elif isinstance(d,list):
  for v in d:check_refs(v)
commit='345798b7bbc9806bdf27dbfaa263537cf9b71610';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_203_f5_m090_t080_actual1127_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==8;blobs={};before={}
for name in names:
 b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert (W/name).read_bytes()==b;assert not (R/name).exists() or (R/name).read_bytes()==b;blobs[name]=b;before[name]=sha(W/name)
rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh203.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={name:sha(W/name) for name in names}
v=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');closure=load(P/'metadata/physical-stage-closure.json');up=load(P/'metadata/upstream-evidence.json');sr=load(P/'metadata/actual-render-metadata.json');man=load(P/'manifest.json')
qp=root(1291)/'actual1127-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qp);cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];source_def=qi['actual_SourceDef']['sha256']
assert all(x['case_id']==cid and x['physical_case_id']==pid and x['family_id']=='F5' for x in (v,png,closure,up,sr))
assert png['review_coverage']['reviewer']=='f5_bed_recovery'
assert v['decision']['standalone_first_stage_visual_approved'] and not any(v['decision'][k] for k in ('severe_visual_failure','needs_root_image_intervention','numerical_precision_accepted','q_n_granted','q_e_granted','independent_case_count_increment','strict_container_guarantee','sub_dp_penetration_absence_claim','large_runup_or_inundation_established'))
assert v['decision']['weak_wave_response'] and closure['historical_failures_retained']['A_and_B_geometric_repair_failures_retained'] and closure['historical_failures_retained']['exact_lattice_threshold_negative_retained'] and not closure['numerical_precision_negative']['pass_at_original_threshold']
assert up['main_qi']['path']==str(qp) and up['main_qi']['sha256']==sha(qp);check_refs(up['actual_completed_metadata_evidence'])
for k,e in qi['actual_completed_metadata_evidence'].items():
 check(e);assert up['actual_completed_metadata_evidence'][k]==e
 if k.endswith('_receipt'):
  rr=load(e['path'])
  if k!='render_publish_receipt':assert (rr['status'],rr['returncode'])==('completed',0) and rr['request']['case_id']==cid
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all_native_UIDs_active_each_frame'] and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and qi['all801_native_Part_BI4_filenames_stat_checked']
scopes=up['producer_scope_roles'];assert canonical==scopes['canonical_native_request_condition_sha256'] and legacy==scopes['actual_converter_legacy_scope_sha256'] and source_def==scopes['bed_source_definition_sha256']
assert len({canonical,legacy,source_def})==3 and qi['actual_native_source_plan_condition_field_present'] and qi['actual_native_source_plan_condition_sha256']==qi['XMF_source_plan_condition_field_sha256']==canonical and qi['bed_declared_source_plan_field_sha256']==source_def
assert scopes['native_source_plan_field_present'] and scopes['native_source_plan_field_sha256']==canonical and not scopes['scope_equality_claimed'];assert up['source_definition_roles']['source_definition_sha256']==source_def and up['source_definition_roles']['canonical_owner_physical_condition_sha256']==canonical;check(qi['actual_SourceDef'])
assert closure['bed_diagnostic']['one_dp_below_count_all_frames']==closure['bed_diagnostic']['two_dp_below_count_all_frames']==0 and not closure['bed_diagnostic']['strict_container_guarantee'] and not closure['bed_diagnostic']['sub_dp_penetration_claim']
for k in ('execution_receipt','render_report','publish_receipt'):check(sr[k])
assert sr['execution_receipt']['path']==qi['actual_completed_metadata_evidence']['render_receipt']['path'];assert sr['render_report']['path']==qi['actual_completed_metadata_evidence']['render_report']['path'];assert sr['publish_receipt']['path']==qi['actual_completed_metadata_evidence']['render_publish_receipt']['path']
pub=load(sr['publish_receipt']['path']);report=load(sr['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sr['render_report']['sha256'];published={e['relative_path']:e for e in pub['files_excluding_receipt']};out=Path(pub['published_output_root'])
assert report['frames']==report['source_frames']==801 and report['all_frames_rendered'] and report['actual_times_preserved_exactly'] and report['native_identity_axis_preserved'] and report['nonfinite_active_states']==0
contacts=png['producer_attested_contact_sheets'];keys=png['producer_attested_keyframes'];assert len(contacts)==34 and [e['index'] for e in contacts]==list(range(34)) and len(keys)==9 and [e['frame_index'] for e in keys]==list(range(0,801,100));assert [e['absolute_path'] for e in contacts]==report['outputs']['contact_sheets'];assert png['review_coverage']['published_png_derivatives_read'] and not png['review_coverage']['source_agent_computed_png_hashes']
assert png['review_coverage']['contact_sheets_reviewed']==34 and png['review_coverage']['keyframes_reviewed']==9 and v['decision']['reviewed_all_contact_sheets'] and v['decision']['reviewed_all_keyframes']
for e in contacts+keys:
 path=Path(e['absolute_path']);pe=published[str(path.relative_to(out))];assert e['reviewed'] and sha(path)==e['sha256']==pe['sha256'] and path.stat().st_size==e['bytes']==pe['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_235.json';cp=load(cpfile);assert cp['checkpoint']==235 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==292 and cp['accepted_per_family']['F5']==23;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {r.get('physical_case_id',r['case_id']) for r in old}
ip=root(1290)/'full336-current292-actual-final48-delivery-progress-index.json';idx=load(ip);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical;assert all(r.get('native_request_scope',{}).get('sha256')!=canonical for r in idx['cases'] if r.get('accepted_decision'))
for k,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][k]
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',png['review_coverage']['reviewed_at_utc']).replace('Z','+00:00'))<=now;raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
O=H/'root_stage1_source203_F5_M090T080_actual1127_full801QI_personal43PNG_actual24_weak_response_historical_negatives_visual_acceptance_1292';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_236.json';assert not list(H.glob('root*_1292')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
vp=O/'source203-byte-exact-readonly-validation-and-main-actual43PNG-proof.json';put(vp,{'source_commit':commit,'source_SHA_before_after':before,'source_validator_stdout':rv.stdout,'source_validator_stderr':rv.stderr,'source_validator_only_checks_package_and_claims_main_actual43PNG_and_completed_stage_refs_independently_verified':True,'adopted_source_files':adopted,'source_original_bytes_preserved':True,'source_main_QI_field_presence_preserved':{'source_schema_claim_present':'schema' in up['main_qi'],'actual_main_QI_schema_field_present':'schema' in qi,'source_at_utc_field_present':'at_utc' in up['main_qi'],'actual_main_QI_at_utc_field_present':'at_utc' in qi,'actual_authority':ref(qp)},'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'bed_SourceDef_scope_sha256':source_def,'source_review_commit':commit,'source_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'source_review_closure':ref(R/prefix/'metadata/physical-stage-closure.json'),'source_review_PNG_evidence':ref(R/prefix/'metadata/png-visual-evidence.json'),'independent_full801_QI':ref(qp),'actual_completed_metadata_evidence':qi['actual_completed_metadata_evidence'],'full_native_frames':801,'particle_count':194427,'initial_fluid_particles':31658,'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'all801_bed_footprint_and_oneDP_twoDP_diagnostic_counts_zero_verified':True,'bed_bins_are_diagnostics_not_precision_thresholds':True,'subDP_positive_depth_not_quantified':True,'actual_native_plan_field_present':True,'actual_native_plan_field_value':canonical,'actual_XMF_plan_field_value':canonical,'actual_bed_plan_field_value':source_def,'canonical_legacy_SourceDef_roles_are_distinct':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':png['visual_observations'],'visual_limits':v['evidence_limits'],'weak_or_limited_visual_mechanism_preserved':True,'large_runup_or_inundation_event_not_established':True,'original_AB_penetration_failures_and_precision_negative_retained':True,'source_personal_visual_decision':v['decision'],'main_all43_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source203-actual1127-full801-QI-personal-visual-adoption.json';put(proof,{'source_validation':ref(vp),'independent_QI':ref(qp),'new_visual_decision':ref(dp),'weak_visual_response_and_original_precision_negatives_preserved':True,'actual43PNG_bound_to_atomic_publish':True,'case_credit':1,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp['accepted_per_family']['F5']+=1;newcp.update(checkpoint=236,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=293,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: original1127 full801 ownQI1291 completed; source203 personal34contacts9keys independently accepted, F5actual24/total293. Cleanup reverified cumulative534.4086GiB and Home788GiB; fresh204 next1131 review delegated; source167 F6rigid47fulltime gaps ownmetadata adopted1294 and fresh168 export worker in progress.',authorized_work_state='Active293/336,43 pending; F5=24,F1/F4/F7=48,F2/F3=39,F6=47. Original1099 F2 completed awaiting fresh182, original1131 and1180 rendering, lastF6 original951 still requires original completion.')
newcp['actual_progress']['source203_F5_actual1127_visual_acceptance']=ref(proof);newcp['actual_progress']['F6_fulltime_rigid_gap_audit']=ref(root(1294)/'F6-final48-fulltime-rigid-state-delivery-evidence-audit.json');newcp['actual_progress']['latest_user_storage_reverification']=ref(root(1295)/'current-storage-cleanup-verification.json');newcp['source_agents']['f5_bed_recovery']='fresh203 accepted F5actual24; fresh204 original1131 M088T095 personal43PNG after publication';newcp['next_executable_tasks']=['Build F5actual24 dynamic delivery root1293 with frozen8 subset24 subset48 and ownfull801 XMF/contacts/navigation bindings.','Adopt fresh182 actualF2 RX058ROT090 original1099 against ownQI1289 retaining five UID fluid omissions and distinct scope roles.','Observe original1131 M088T095 and1180 M095T100 through actualprocess handles, run ownQI on terminalpublication, continue child personalreview.','Integrate fresh168 F6 fulltime FloatingInfo worker; register small IBI4 input inventory and then pilot+remaining exports without rerunning solver.'];assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==293;put(nextcp,newcp)
idx.update(previous_index_preserved=ref(ip),source_authoritative_checkpoint=ref(nextcp),at_utc=now.isoformat(),accepted_independent_physical_cases=293,registered_pending_independent_physical_cases=43,new_case_credit=1);targets[0].update(status='visual-approved-in-checkpoint236',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qp));idx['actual_unaccepted_completed0_published_physical_cases']=[e for e in idx['actual_unaccepted_completed0_published_physical_cases'] if (e.get('physical_case_id') if isinstance(e,dict) else e)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==293;put(O/'full336-current293-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=list(blobs)+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 m090 t080 full801 retaining weak response and precision negatives','--',*paths],cwd=R,check=True);print({'checkpoint':236,'accepted':293,'F5':24,'remaining':43,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
