from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,re,copy,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.png','.log','.txt'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_131_f3_p0800_ay0320_delegated_visual_review_v1';commit='d1744b8d9e7e60b884387332e840d8bda8738e9c';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==9;adopted=[]
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_delegated131_F3_P0800AY0320_actual997_1004_explicitv1_full836_clone_QI_visual_acceptance_1027';O.mkdir(exist_ok=True);assert not list(O.glob('*delegated-visual-decision.json'));assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_151.json').exists();vld=P/'scripts/validate_fresh131.py';rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],capture_output=True,text=True);put(O/'actual-original-source131-validator.json',{'validator':ref(vld),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr});assert rv.returncode==0
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_150.json');old=[load(p) for p in cp['accepted_decisions']];assert len(old)==sum(cp['accepted_per_family'].values())==228;ids={a.get('physical_case_id',a['case_id']) for a in old};cids={a['case_id'] for a in old};scopes={a['physical_condition_sha256'] for a in old};decisions=[];proofs=[]
for suffix in ['0320']:
 cid=f'F3_STAGE1_DP006_P0800_AY{suffix}';zp=P/f'metadata/chain-audit/{cid}.json';vp=P/f'metadata/visual-review/{cid}-delegated-visual-decision.json';z=load(zp);v=load(vp);assert v['status']=='visual-approved-by-delegated-agent' and v['agent_personally_viewed_all_contacts_and_keys'] and not v['main_personally_viewed_pngs'];assert cid==v['case_id']==z['case_id'] not in cids
 s=copy.deepcopy(z['stages']);receipts={}
 for role in ['typed','render']:s[role]['report']={'path':s[role]['report_path'],'sha256':s[role]['report_sha256']}
 s['xmf']['manifest']={'path':s['xmf']['manifest_path'],'sha256':s['xmf']['manifest_sha256']};s['xmf']['xdmf_sha256']=s['xmf']['xml_sha256']
 put(O/'source131-original-stage-schema-adapter.json',{'original':ref(zp),'normalized_actual_stages':s,'metadata_representation_only':True,'scientific_payload_IO':False})
 for role,p in s.items():
  assert sha(p['path'])==p['sha256'];a=load(p['path']);assert (a['status'],a['returncode'])==('completed',0) and a['request']['case_id']==cid;receipts[role]=a
  if 'report' in p:assert sha(p['report']['path'])==p['report']['sha256']
 t=load(s['typed']['report']['path']);r=load(s['render']['report']['path']);xp=Path(s['xmf']['manifest']['path']);assert sha(xp)==s['xmf']['manifest']['sha256'];x=load(xp);xml=Path(x['xdmf']);assert x['xdmf_sha256']==sha(xml)==s['xmf']['xdmf_sha256'] and r['xdmf_sha256_before']==r['xdmf_sha256_after']==sha(xml)
 assert t['frames']==x['frames']==r['frames']==r['source_frames']==836 and t['particles']==x['particles']==179208 and t['solver_dimension']['solver_dimension']==x['dimension']==3
 assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(a['passed'] and a['identity_type_mk_exact'] for a in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
 assert r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['nonfinite_active_states']==0 and not r['diagnostic_only'] and r['source_h5_read_only']
 assert t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256'] and sha(xp)==r['manifest_sha256'];h5=t['output_hdf5'];assert Path(h5).is_file()
 legacy_xmf_closure=[]
 for role in ['xmf','render']:
  a=receipts[role]
  if h5 in a['input_hashes_at_launch']:
   assert a['input_hashes_at_launch'][h5]==a['input_hashes_after_run'][h5]==t['output_sha256']
  else:
   assert role=='xmf'
   cmd=a['request']['command'];bp=Path(cmd[cmd.index('--binding')+1]);xb=load(bp);assert a['input_hashes_at_launch'][str(bp)]==a['input_hashes_after_run'][str(bp)]==sha(bp)
   assert xb['trajectory_h5']==h5 and xb['trajectory_h5_sha256']==t['output_sha256'] and xb['conversion_report']==s['typed']['report']['path'] and xb['typed_receipt']==s['typed']['path']
   legacy_xmf_closure.append({'actual_XMF_binding':ref(bp),'older_runner_did_not_declare_H5_as_direct_input':True,'actual_completed_XMF_worker_bound_H5_producer_SHA':xb['trajectory_h5_sha256'],'actual_full_renderer_runner_H5_before_after_SHA_matches_producer':True,'no_fake_old_runner_H5_hash_claim':True})
 for key in ['solver_receipt','gencase_receipt','generated_xml','owner_metadata']:
  p=t['source_provenance'][key];assert sha(p['path'])==p['sha256']
 assert t['source_provenance']['solver_receipt']==ref(s['native']['path']);o=load(t['source_provenance']['owner_metadata']['path']);scope=z['owner_and_scope'];assert sha(scope['canonical_source_owner']['path'])==scope['canonical_source_owner']['sha256']==t['source_provenance']['owner_metadata']['sha256'];assert load(scope['canonical_source_owner']['path'])==o
 canonical=scope['canonical_physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];pid=x['physical_case_id'];nq=receipts['native']['request'];assert pid==v['physical_case_id']==nq['physical_case_id']==t['hash_scopes']['physical_condition']['physical_case_id']==o['physical_case_id'];assert canonical==x['source_physical_condition_sha256']==x['physical_condition_sha256']==legacy==nq['physical_condition_sha256']==v['physical_condition_sha256']==scope['actual_converter_scope']['sha256'];assert t['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1' and scope['source_plan_condition_sha256'] is None
 assert pid not in ids and z['census_physical_case_id'] not in ids and canonical not in scopes
 qp=Path(scope['parent_initial_qa']['path']);assert sha(qp)==scope['parent_initial_qa']['sha256'];qa=load(qp);qar=qp.parent/'execution-receipt.json';qarec=load(qar);assert (qarec['status'],qarec['returncode'])==('completed',0);a=next(y for y in qa['cases'] if y['role']=='twoaxis_dp006');assert a['passed'] and a['actual_3d'] and a['native_particles']==179208 and a['native_fluid']==67500 and a['native_fixed']==111708
 prepref=nq['actual_preparation_report'];assert prepref==scope['source_prepared_input_report'] and sha(prepref['path'])==prepref['sha256'];prepared=load(prepref['path']);prref=nq['actual_preparation_receipt'];assert sha(prref['path'])==prref['sha256'];pr=load(prref['path']);assert (pr['status'],pr['returncode'])==('completed',0)
 assert prepared['case_id']==cid and prepared['physical_case_id']==pid and prepared['physical_condition_sha256']==canonical and prepared['xml_byte_identical_to_baseline'] and prepared['initial_bi4_byte_identical_to_baseline']
 assert prepared['initial_native_reference']['initial_native_verified']['native_initial_BI4_sha256']==a['native_initial_BI4_sha256']==prepared['bi4_sha256'];assert prepared['xml_sha256']==a['generated_xml_sha256']==sha(t['source_provenance']['generated_xml']['path'])
 for path,digest in [(t['source_provenance']['generated_xml']['path'],prepared['xml_sha256']),(prepared['prepared_prefix']+'.bi4',prepared['bi4_sha256']),(prepared['forcing_path'],prepared['forcing_sha256'])]:
  assert receipts['native']['input_hashes_at_launch'][path]==receipts['native']['input_hashes_after_run'][path]==digest
 clone=nq['initial_QA_exact_clone_evidence'];assert sha(clone['path'])==clone['sha256'];assert nq['genuine_parent_initial_QA']==scope['parent_initial_qa']
 assert nq['nominal_pitch_multiplier']==prepared['nominal_pitch_multiplier']==0.8 and nq['transverse_amplitude_m_s2']==prepared['transverse_amplitude_m_s2']==int(suffix)/1000
 assert prepared['forcing_transform']['output_sha256']==prepared['physical_binding']['parameters']['actual_forcing_sha256']==prepared['forcing_sha256'] and prepared['forcing_transform']['source_sha256_before']==prepared['forcing_transform']['source_sha256_after']
 data=Path(t['source_provenance']['data_root']);frames=sorted(p.name for p in data.glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name));assert len(frames)==836 and frames[0]=='Part_0000.bi4' and frames[-1]=='Part_0835.bi4'
 fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==836;assert times==[f['time'] for f in fs]==[d['actual_time_s'] for d in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=8.35 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[836,179208,3]
 for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
  assert f['frame']==d['frame']==i and f['active_particles']==d['active']==179208 and f['missing_particles']==d['missing']==0 and f['type_counts']=={'0':111708,'1':0,'2':0,'3':67500};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='179208 3';vv=next(a for a in g.findall('Attribute') if a.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='179208 3'
 png=v['verified_PNG_hashes'];assert len(png['contact_sheets'])==35 and len(png['keyframes'])==6;assert [a['path'] for a in png['contact_sheets']]==r['outputs']['contact_sheets']
 for p in png['contact_sheets']+png['keyframes']:assert sha(p['path'])==p['sha256']
 assert v['source_review']['sha256']==sha(zp);stale=v['actual_completed_metadata_evidence']['chain_audit'];assert stale['path']==v['source_review']['path'];correction={'source131_original_duplicate_chain_audit_reference':stale,'actual_same_source_chain_review_reference':ref(zp),'source131_original_source_review_commit':v['source_review_commit'],'actual_source131_git_commit':commit,'source_package_bytes_unchanged':True,'duplicate_reference_matches_current_chain':stale['sha256']==sha(zp),'main_source_commit_bound_to_actual_adopted130_commit':True};ch=copy.deepcopy(v['actual_completed_metadata_evidence']);ch['chain_audit']=ref(zp);ch['parent_initial_qa_receipt']=ref(qar)
 decision={**v,'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_review_commit':commit,'source_visual_decision':ref(vp),'source_review':ref(zp),'actual_completed_metadata_evidence':ch,'source131_immutable_metadata_alias_closure':correction,'physical_case_aliases':[pid,z['census_physical_case_id']],'canonical_scope_sha256':canonical,'actual_converter_scope_sha256':legacy,'full_native_frames':836,'particles':179208,'actual_physical_window_s':[times[0],times[-1]],'all836_geometry_and_velocity_N3_exact_times_UIDs_and_finite_fields_verified':True,'stage1_QI_full_native_identity_and_state_verified':True,'actual_parent_initial_clone_QA_closure':{'actual_receipt':ref(qar),'actual_report':ref(qp),'same_GenCase_geometry_XML_and_initial_BI4_producer_digests':True,'changed_forcing_digest_bound_by_actual_native_runner_before_after':True},'actual104_explicitv1_manifest_scope_matches_actual_native_and_converter':True,'actual104_source_physical_condition_field_preserved_distinct_semantic_role_same_scope_value':True,'actual_XMF_and_renderer_H5_producer_digest_closure':legacy_xmf_closure,'actual_typed_owner_and_source131_owner_path_aliases':{'producer_owner':t['source_provenance']['owner_metadata'],'source131_alias':scope['canonical_source_owner'],'canonical_scope_resolved_from_actual_native_request_and_manifest_separate_source_field':True},'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'precision_status':'视觉检查通过、数值精度未验收','q_n_granted':False,'q_e_granted':False,'independent_case_increment':1};decision.pop('previous_count',None);decision.pop('resulting_count',None);dp=O/(cid+'-delegated-visual-decision.json');put(dp,decision);decisions.append(str(dp));proofs.append({'case_id':cid,'actual_identity_aliases':decision['physical_case_aliases'],'decision':ref(dp),'canonical_scope':canonical,'legacy_scope':legacy,'frames':836,'all836_UID_active':True,'original_source131_metadata_alias_notes':correction,'scientific_payload_IO':False});ids.add(pid);ids.add(z['census_physical_case_id']);cids.add(cid);scopes.add(canonical)
put(O/'source131-adoption-one-full836-independent-QI-and-visual-review.json',{'source_commit':commit,'adopted_files':adopted,'actual_original_validator':ref(O/'actual-original-source131-validator.json'),'cases':proofs,'all35_contact_pages_and6_keyframes_personally_viewed_by_delegated_agent':True,'source_original_duplicate_metadata_reference_kept_and_actual_closure_separate':True,'new_case_credit':1,'scientific_payload_IO':False})
cp['accepted_per_family']['F3']+=1;cp.update(checkpoint=151,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_150.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_150.json'),stage1_visual_accepted_complete_independent_cases=229,new_accepted_decisions=decisions,accepted_decisions=cp['accepted_decisions']+decisions,previous_goal_turn_classification='Progress: actual full836 F3 P0800 AY0320 complete native839, typed978, XMF997, render1004 and source131 delegated35contacts6keys personally inspected, exact real704 clone preparation plus genuine056/058 QA, forcing producer digests and full UID/time/N3 scope closure independently accepted229; F3=18. New actual full836 XMF0 AY0430/0460 renders1025/1026 registered and fair dispatch running, no raw rerun. Precision not granted.')
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==229;raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);a=json.loads(raw);cp.update(home_free_gib=shutil.disk_usage('/home/jade').free/2**30,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),active_reservations=a['reservations'],attempt_counts={k:sum(z['kind']==k for z in a['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(z.get('gpu_seconds',0) for z in a['charges'])/3600,cpu_core_hours_charged=sum(z.get('cpu_core_seconds',0) for z in a['charges'])/3600);cp['actual_progress']['delegated131_one_F3_explicitv1_full836_independently_closed']=ref(O/'source131-adoption-one-full836-independent-QI-and-visual-review.json');put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_151.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(x['path']).relative_to(R)) for x in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_151.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F3 pitch080 AY0320 full836 visuals with actual clone QA forcing and explicit-v1 scope closure','--',*paths],cwd=R,check=True);print({'accepted':229,'counts':cp['accepted_per_family'],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
