from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.py','.md','.png','.xml','.xmf','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_192_f5_m108_t095_actual1152_personal_visual_review_v1';commit='2fa99fbd5968513be7338d8cde90a670f92ed806';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==9
P=W/prefix;before={n:sha(W/n) for n in names};vld=P/'scripts/validate_fresh192.py';v=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],text=True,capture_output=True);assert v.returncode==0 and before=={n:sha(W/n) for n in names}
up=load(P/'metadata/upstream-evidence.json');z=load(P/'metadata/physical-stage-closure.json');visual=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');ar=load(P/'metadata/actual-render-metadata.json');qi_path=root(1213)/'actual1152-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qi_path);refs=qi['actual_completed_metadata_evidence']
assert qi['case_id']==z['case_id']==visual['case_id']==ar['case_id'] and qi['physical_case_id']==z['physical_case_id']==visual['physical_case_id']==ar['physical_case_id']
for k,e in refs.items():assert sha(e['path'])==e['sha256']
for k,e in up['upstream_chain'].items():
 assert sha(e['path'])==e['sha256']
 alias={'render_execution_receipt':'render_receipt'}.get(k,k)
 if alias in refs:assert e['path']==refs[alias]['path'] and e['sha256']==refs[alias]['sha256']
for stage in ('gencase','initial_qa','native','typed','xmf','bed','render'):
 d=load(refs[stage+'_receipt']['path']);assert (d['status'],d['returncode'])==('completed',0) and d['request']['case_id']==z['case_id']
assert qi['full_frames']==801 and qi['particles']==194427 and qi['fluid_initial_UIDs']==31658 and qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
roles=up['scope_roles'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert canonical==roles['canonical_native_source_plan_sha256'] and legacy==roles['typed_legacy_h5_scope_sha256'] and qi['bed_declared_source_plan_field_sha256']==roles['source_definition_bed_declared_plan_sha256']==qi['actual_SourceDef']['sha256']
sourceplan=up['upstream_chain']['source_plan'];assert sourceplan['sha256']==roles['source_plan_file_sha256']
q=visual['decision'];assert q['standalone_first_stage_visual_approved'] and not q['needs_root_image_intervention'] and not q['numerical_precision_accepted'] and not q['q_n_granted'] and q['weak_wave_only'] and not q['large_inundation_or_runup_claim'] and not q['strict_container_guarantee']
rr=load(refs['render_report']['path']);pub=load(refs['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==refs['render_report']['sha256'];assert rr['frames']==rr['source_frames']==801 and rr['all_frames_rendered'] and rr['nonfinite_active_states']==0
assert len(png['contact_sheets'])==34 and len(png['keyframes'])==9 and [e['frame'] for e in png['keyframes']]==[0,100,200,300,400,500,600,700,800]
assert [e['path'] for e in png['contact_sheets']]==rr['outputs']['contact_sheets'] and [e['relative_path'] for e in png['contact_sheets']]==[f'all_frames_{i:03d}.png' for i in range(34)]
pr={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in png['contact_sheets']+png['keyframes']:assert e['reviewed'] and sha(e['path'])==e['sha256']==e['producer_receipt_sha256']==pr[e['relative_path']]['sha256'] and Path(e['path']).stat().st_size==e['bytes']==pr[e['relative_path']]['bytes']
assert sorted(p.name for p in Path(rr['outputs']['frames_dir']).glob('frame_*.png'))==[f'frame_{i:04d}.png' for i in range(801)]
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_196.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==271;old=[load(p) for p in cp['accepted_decisions']];pid=z['physical_case_id'];assert pid not in {x.get('physical_case_id',x['case_id']) for x in old}
idxpath=root(1216)/'full336-current271-native-request-roles-with-actual167-F2-closure.json';idx=load(idxpath);target=[x for x in idx['cases'] if x['physical_case_id']==pid];assert len(target)==1 and not target[0].get('accepted_decision') and target[0]['native_request_scope']['sha256']==canonical
for x in idx['cases']:
 if x.get('accepted_decision'):assert x.get('native_request_scope',{}).get('sha256')!=canonical
O=H/'root_stage1_source192_F5_M108T095_actual1152_personal34contacts_ninekeys_801QI_proof_adoption_visual_acceptance_1223';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_197.json').exists();adopted=[]
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;put(O/'actual-source192-readonly-validator.json',{'validator':ref(vld),'returncode':v.returncode,'stdout':v.stdout,'stderr':v.stderr,'original_source_bytes_unchanged':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json')
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':z['case_id'],'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_plan_condition_sha256':qi['actual_native_source_plan_condition_sha256'],'bed_declared_source_plan_field_sha256':qi['bed_declared_source_plan_field_sha256'],'source_definition_sha256':qi['actual_SourceDef']['sha256'],'source_plan_file_sha256':roles['source_plan_file_sha256'],'source_review_commit':commit,'source_visual_review':ref(P/'metadata/visual-decision.json'),'source_review_closure':ref(P/'metadata/physical-stage-closure.json'),'actual_completed_metadata_evidence':refs,'independent_full801_QI_previsual_proof':ref(qi_path),'full_native_frames':801,'particles':194427,'actual_physical_window_s':qi['actual_time_window_s'],'all801_geometry_velocity_N3_times_UID_finite_verified':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':visual['visual_observations'],'actual_contact_count_and_coverage_closure':{'count':34,'tile_batch':24,'total_frames':801,'all_frame_PNG_filenames_present':True,'all43_reviewed_derivative_hashes_match_actual_publish':True},'original_source192_scope_roles':roles,'all801_full_bed_UID_footprint_one_DP_two_DP_diagnostics_checked':True,'positive_depth_below_DP_not_proven_absent_by_zero_bin_counts':True,'large_runup_inundation_or_strict_container_guarantee':False,'initial_qa_numerical_precision_negative':qi['actual_initial_QA_precision_negative'],'historical_A_B_negative_evidence_preserved':z['historical_negative_evidence_preserved'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source192-actual1152-immutable801QI-and-personal-visual-adoption-proof.json';put(proof,{'source_commit':commit,'adopted_files':adopted,'source_validator':ref(O/'actual-source192-readonly-validator.json'),'original_QI_proof':ref(qi_path),'all_original_QI_stage_refs_byte_unchanged':True,'actual_personal_png_count':43,'actual_801_frame_filenames_present':True,'new_decision':ref(dp),'source_definition_and_native_condition_and_legacy_roles_separate':True,'independent_case_increment':1,'main_scientific_payload_IO':False,'precision_status':'视觉检查通过、数值精度未验收'})
lb=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(lb);lf=O/'resource-ledger-frozen.json';lf.write_bytes(lb);s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize/2**30;assert free>=500;counts=collections.Counter(x['kind'] for x in ld['attempts']);cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;assert cpu<=3840 and gpu<=512 and counts['qualification']<=1024 and counts['production']<=720
cp['accepted_per_family']['F5']+=1;cp.update(checkpoint=197,at_utc=now,predecessor=str(cp_path),predecessor_sha256=sha(cp_path),stage1_visual_accepted_complete_independent_cases=272,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(lb).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='Progress: source192 actual1152 full801 and personal34contacts9keys adopted; original1213QI refs unchanged; accepted272/F5=12. User storage cleanup completed, all accepted/pending scientific data retained.',authorized_work_state='Active272/336. F5M108T095 weak-wave visual-approved, precision not accepted. Source193 reviewing newly completed1130. F4frozenfirst8 membership source151 and F2native chain168 active. Original registered remaining64 render handles preserved.');cp.pop('resource_scalar_observation_authority',None);cp['actual_progress']['source192_F5_actual1152_visual_acceptance']=ref(proof);cp['source_agents']['f5_bed_recovery']='fresh192 accepted272/F5=12; fresh193 actual1130 full801 personal review';cp['next_executable_tasks'][0]='Accept source193 actual1130 F5M088T085 after independent full801QI metadata closure and personal review; continue original1137 render.';assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==272;newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_197.json';put(newcp,cp)
row=target[0];row.update(status='visual-approved-in-checkpoint197',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='Own actual native condition retained; other source/legacy roles separate',precision_status='视觉检查通过、数值精度未验收');idx.update(schema='ds02.stage1.full336.role-aware-progress-index.v5',at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxpath),accepted_independent_physical_cases=272,registered_pending_independent_physical_cases=64,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if x.get('physical_case_id')!=pid];idx['newly_published1130_not_yet_reprobed_in_index']=True;idx['controller_observations_inherited_from1215_not_new_live_probe']=True;put(O/'full336-current272-role-aware-registration-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 M108 T095 complete801 personal visual review with original QI and limits','--',*paths],cwd=R,check=True);print({'accepted':272,'F5':12,'remaining':64,'checkpoint':197,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'Home_free_GiB':free})
