from pathlib import Path
import json,hashlib,collections,datetime,os,subprocess,ast
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_actual142_F3_corner_F4_24_F5_source34_F2_XMF_queue_checkpoint_829';O.mkdir();load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
def proc(pid):
 p=Path('/proc')/str(pid)
 if not p.exists():return {'pid':pid,'live':False}
 f=(p/'stat').read_text().split(') ',1)[1].split();return {'pid':pid,'live':f[0]!='Z','state':f[0],'proc_start_ticks':f[19],'ppid':int(f[1]),'wchan':(p/'wchan').read_text().strip(),'cmdline':(p/'cmdline').read_bytes().replace(b'\0',b' ').decode(errors='replace')}
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_104.json';cp=load(prev);new=sum([load(root(n)/'actual-integration-review.json')['decisions'] for n in [825,826,828]],[]);accepted=cp['accepted_decisions']+new;rows=[load(p) for p in accepted];assert len(accepted)==142 and len(new)==5;assert len({x.get('physical_case_id',x['case_id']).replace('F4_DROP_B08_','F4_DROP_') for x in rows})==142 and len({x['physical_condition_sha256'] for x in rows})==142;counts=dict(collections.Counter(x['family_id'] for x in rows));assert counts=={'F1':48,'F2':16,'F3':9,'F4':24,'F5':4,'F6':24,'F7':17};assert all(load(p)['status']=='visual-approved-by-delegated-agent' and load(p)['main_personally_viewed_pngs'] is False for p in new)
controllers=[];observations=[]
for n in [773,774,796,812,816,820,824,827]:
 p=root(n);c=load(p/'controller-launch-process.json');pr=proc(c['pid']);assert not pr['live'] or pr['proc_start_ticks']==c['proc_start_ticks'];assert not pr['live'] or c['controller'] in pr['cmdline'];codehash=sha(c['controller']);assert not c.get('controller_sha256') or codehash==c['controller_sha256'];result=p/'controller-result.json';controllers.append({'number':n,'source_launch':ref(p/'controller-launch-process.json'),'code_sha256':codehash,'actual_handle':pr,'terminal_result':ref(result) if result.exists() else None})
 for qp in list(p.glob('*request.json'))+list((p/'requests').glob('*request.json')):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';entry={'root':n,'request':ref(qp),'actual_receipt_path':str(rp),'independent_case_count_increment':0}
  if rp.exists():
   r=load(rp);entry.update(status=r['status'],returncode=r.get('returncode'),receipt_sha256_at_observation=sha(rp),actual_worker=proc(r['pid']) if r.get('pid') else None)
  else:entry['status']='not_registered; future request only'
  observations.append(entry)
assert any(x['root']==816 and ((x['status']=='running' and x['actual_worker']['live']) or (x['status']=='completed' and x['returncode']==0)) for x in observations);assert any(x['root']==796 and x['status']=='completed' for x in observations);assert next(x for x in controllers if x['number']==820)['actual_handle']['live']
lp=D/'runtime/resource-ledger.json';b=lp.read_bytes();ledger=json.loads(b);assert ledger['limits']==cp['limits'] and ledger['adopted_at_utc']==cp['adopted_at_utc'] and ledger['deadline_utc']==cp['deadline_utc'];assert sum(x.get('cpu_threads',0) for x in ledger['reservations'])<=64;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize;assert free>=500*1024**3
for p,e in [(L/'scripts/ds_data02_runtime_v2.py',cp['unmodified_guards']['runtime_v2_sha256']),(L/'scripts/ds_data02_strict_dispatch_v1.py',cp['unmodified_guards']['strict_dispatch_sha256']),(H/'root_stage1_home_floor_inventory_dispatch_142/launch.py',cp['unmodified_guards']['Root142_launch_sha256'])]:assert sha(p)==e
inventory=subprocess.check_output(['nvidia-smi','--query-compute-apps=gpu_uuid,pid,used_memory','--format=csv,noheader'],text=True);put(O/'actual-readonly-GPU-process-inventory.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'compute_apps':inventory,'foreign_processes_protected':True,'foreign_process_outputs_not_inspected':True});put(O/'actual-same-handle-worker-observations.json',{'controllers':controllers,'requests':observations,'no_restart_for_observation_timeout':True})
progress={'new_visual_accepted_cases':{'total':5,'F4_increment':4,'F3_increment':1,'decisions':[ref(p) for p in new],'delegated_full1201_contact_sheets_and_keys_review':True,'main_personal_PNG_review_claim':False},'F2_new24_native_observed_states':dict(collections.Counter(x['status'] for x in observations if x['root']==812)),'F2_full401_typed_actual_registered_live':ref(root(816)/'controller-launch-process.json'),'F5_fresh138_exact_adoption_and_own_native_GenCase_QA_actual0_ten':ref(root(819)/'adoption-review.json'),'F5_typed_controller_actual_live_waiting_same_shared_conversion_lock':ref(root(820)/'controller-launch-process.json'),'F5_prelaunch_stale_unused_bed_worker_hash_failure_and_one_scoped_repair':ref(root(817)/'prelaunch-failure-evidence.json'),'conversion_scope_note':'Each own original125 legacy owner scope is calculated from unchanged converter keys; canonical physical condition remains separate. Actual typed producer report must confirm scope; future science hashes remain unclaimed.','CPU_conversion_global_new_cap':1,'CPU_per_conversion':2,'same_coordination_lock_for_F2_F5':str(D/'runtime/stage1-fullnative-conversion-dispatch.lock'),'shared_CPU_reservation_cap':64,'renderer_global_cap':2,'actual_same_handle_observations':ref(O/'actual-same-handle-worker-observations.json'),'actual_GPU_inventory':ref(O/'actual-readonly-GPU-process-inventory.json'),'scientific_payloads_read_or_hashed_by_main':False,'numeric_precision_not_accepted':True,'F3_first_full836_corner_case_local_visual_acceptance':ref(root(826)/'actual-integration-review.json'),'F3_2D_range_release':'pending remaining3 actual completed renders plus delegated visual approval','F5_next34_static_source_plan':ref(root(823)/'source-plan.json'),'F5_next34_static_geometry_and_control_validation':ref(root(823)/'static-source-validation.json'),'F5_source_generation34_actual_live_queue':ref(root(824)/'controller-launch-process.json'),'F2_dynamic_actual_typed_to_XMF_controller':ref(root(827)/'controller-launch-process.json'),'extra_persistent_storage_path_question':'pending user path information; existing computations continue; actual Home free floor guard unchanged'}
out={k:cp[k] for k in ['schema','target_stage1_independent_cases','numeric_reference_accepted_independent_products','precision_status','limits','user_cumulative_window','latest_user_resource_window_confirmation','deadline_utc','adopted_at_utc','effective_visual_review_policy','effective_agent_model_policy','unmodified_guards']};out.update(checkpoint=105,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(prev),predecessor_sha256=sha(prev),historical_records_preserved_by_reference_no_repeated_snapshot_expansion=True,authorized_work_state='active; same live native, conversion, renderer handles and shared-lock queue; no approval blocker',previous_goal_turn_classification='progress: four unique F4 and one actual full836 F3 corner visually accepted;34 distinct F5 source definitions validated and actual generation controller queued; F2 actual typed to XMF controller waiting each own report0; budgets/counters/deadline preserved',stage1_visual_accepted_complete_independent_cases=142,accepted_per_family=counts,accepted_decisions=accepted,new_accepted_decisions=new,attempt_counts=dict(collections.Counter(x['kind'] for x in ledger['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ledger['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ledger['charges'])/3600,active_reservations=ledger['reservations'],ledger_sha256_at_checkpoint=hashlib.sha256(b).hexdigest(),home_free_gib=free/1024**3,actual_progress=progress,source_agents={'/root/production_recovery':'fresh100 next3 actual796 full836 corners as each completes, plus remaining F2 stock; source099 first corner accepted','/root/f6_endpoint_initial_qa':'fresh118 next Root638 .24/-x/+y pair or next actual completed unique pair;116/117 accepted','/root/f5_bed_recovery':'fresh139 F7 A037P5/A038P5 full601 visual evidence pending'},next_executable_tasks=['Poll same actual Root816 typed, Root827 awaits each actual0 then registers full401 normalN3 XMF; afterward schedule bounded renderer slots; canonical and legacy scopes remain distinct','Poll Root820 same shared lock, verify first actual801 typed0 then remaining10; bind actual producer hashes to fresh138 XMF/bed/render using committed worker digests','F3 Root796 remaining full836 corner render0 plus delegated visual release immediately triggers20 independent native cases; do not wait long F4/F6 backlog','Integrate fresh100/118/139 as full-window delegated evidence is submitted; no duplicate or supporting-sidecar credit','Continue native Root812 actual24 cases; no duplicate dispatch or restart on slow HDD preflight','Poll same actual Root824 queued source generation34; bind each own source producer hash to registered GenCase and initial QA; no source/GenCase counts fabricated; T120 held','Remain inside original cumulative512GPUh/3840CPUcoreh/1024qual/720prod and original deadline; Home>=500GiB'])
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_105.json',out);(O/'checkpoint-validation-and-build.py').write_bytes(Path(__file__).read_bytes());paths=[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_105.json').relative_to(R)),str((root(820)/'controller-launch-process.json').relative_to(R))]
for p in list(O.rglob('*'))+[root(823)/'static-source-validation.json',root(824)/'controller-launch-process.json',root(827)/'controller-launch-process.json']+list(root(828).rglob('*'))+list((L/'campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_117_f4_delegated_visual_acceptance_v1').rglob('*')):
 if p.is_file() and p.suffix in {'.json','.py','.md'}:
  if p.suffix=='.json':load(p)
  if p.suffix=='.py':ast.parse(p.read_text())
  paths.append(str(p.relative_to(R)))
assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: checkpoint142 visual cases and actual F5 source F2 XMF queues'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'checkpoint':105,'accepted':142,'families':counts,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'used_GPUh':out['gpu_hours_charged'],'used_CPUcoreh':out['cpu_core_hours_charged'],'attempts':out['attempt_counts'],'home_free_gib':out['home_free_gib']}))
