from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_273.json';cp=load(cpfile);assert cp['checkpoint']==273 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==309
qis=[]
for original,qnum,agent in [(987,1355,177),(1164,1359,211)]:
 p=next(root(qnum).glob('*proof.json'));qi=load(p);cr=root(original)/'controller-result.json';r=load(cr);assert r['status']=='completed' and r['returncode']==0
 rc=load(r['actual_receipt']);assert rc['status']=='completed' and rc['returncode']==0
 pub=Path(r['actual_receipt']).parent/'render/render-publish-receipt.json';pu=load(pub);assert pu['status']=='published_after_atomic_rename' and pu['case_id']==qi['case_id'];assert pu['report_sha256_after_rebind']==sha(pub.parent/'paraview-full-animation-report.json')
 assert qi['new_case_credit']==0;qis.append({'original':original,'physical_case_id':qi['physical_case_id'],'main_own_QI':ref(p),'controller_result':ref(cr),'actual_render_receipt':ref(r['actual_receipt']),'actual_atomic_publish_receipt':ref(pub),'source_personal_review':agent,'case_credit':0})
live=[]
for original,pid,start in [(1188,613708,'213820080'),(1143,621866,'213876084')]:
 F=root(original);w=load(F/'enabled-render-wrapper.json');P=Path(f'/proc/{pid}');obs=None
 if P.exists():
  st=(P/'stat').read_text().rsplit(')',1)[1].split();assert st[19]==start;cmd=(P/'cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);obs={'pid':pid,'startticks':start,'state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 x=load(w['manifest']);assert x['frames']==w['expected_frames'] and x['particles']==w['expected_particles'];assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
 live.append({'original':original,'case_id':w['case_id'],'physical_case_id':w['physical_case_id'],'actual_loaded_wrapper':ref(F/'enabled-render-wrapper.json'),'actual_XMF_manifest':ref(w['manifest']),'actual_wrapper_expected_frames':w['expected_frames'],'actual_wrapper_expected_particles':w['expected_particles'],'same_actual_process':obs,'actual_controller_terminal':ref(F/'controller-result.json') if (F/'controller-result.json').exists() else None,'no_restart':True,'case_credit':0})
builder=next(root(1361).glob('*proof.json'));bp=load(builder);assert bp['actual_final48_emitted'] is False and bp['actual_observed_readiness_counts']=={'registered_final48':48,'accepted_visual':42,'pending_visual':6}
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);attempts=collections.Counter(r['kind'] for r in ld['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ld['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and attempts['qualification']<=1024 and attempts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current309_F3_987_F5_1164_published_full_QI_personal_pending_nextF5_1188_F2_1143_same_live_F3_builder_readiness_only_storage534GiB_preserved_1364';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_274.json';assert not O.exists() and not np.exists();O.mkdir();pp=O/'current309-two-published-own-QI-personal-pending-next-originalF5F2-live-builder-source176-audited.json';put(pp,{'at_utc':now.isoformat(),'published_completed0_full_QI_personal_pending':qis,'next_same_original_live':live,'source176_builder_byte_exact_adoption':ref(builder),'source176_current42_readiness_only_not_final48':True,'current_storage_home_free_GiB':free,'prior_cumulative_failed_output_cleanup_allocated_GiB':534.4085998535156,'prior_deleted_failed_intermediate_files':17203,'new_deletions_this_observation':0,'scientific_payload_IO':False,'no_new_solver_or_render_jobs':True,'case_credit':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=274,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: accepted two F5 distinct physical cases through actual801 QI and personal43PNG, total309; actualF3 987 own836 QI and F5 1164 own801 QI done and delegated personalreviews active. Source176 reference builder byte-exactly integrated with independent current authority/status gates; actual42/readiness only. New originalF2 1143 starts through unchanged registered queue, same handle tracked with F5 1188. Prior failedoutput534GiB cleanup preserved; no unnecessary repeated cleanup.',authorized_work_state='Active309/336, pending27: F1/F4/F6/F7=48 each, F2=43 F3=42 F5=32. Source177 F3original987 andsource211 F5original1164 personally reviewing after ownQI1355/1359. Source192 F5original1188 waits ownQI1363 after actualcompleted0/publication. Next originalF2 1143 RX063ROT090 actual401 renderer live; prepare durable metadataQI then delegated review. Source176 is assembly utility only; future final48 must separately pass actual primary integrity/runtime-unknown review.')
new['actual_progress']['actual1164_full801_own_QI']=qis[1]['main_own_QI'];new['actual_progress']['source176_completion_only_reference_builder_adoption']=ref(builder);new['actual_progress']['current309_two_published_QI_nextF5F2_live']=ref(pp);new['next_executable_tasks']=['Adopt source177 F3original987 personal35contacts9keys andsource211 F5original1164 personal34contacts9keys once finalcommit/read-only validation/ownQI refs available; do not rerun completedQI1355/1359.','Observe originalF5 1188 PID613708/start213820080; actualcompleted0/pub then Root1362 durable after_original1188_terminal_full801_own_QI.py 1188 1363 once, supply source192 pathSHA.','Prepare future own401 metadataQI for next originalF2 1143 RX063ROT090 actual1117 XMF andactual1013 typed, pin genuine native receipt/initialQA roles and actualloaded wrapper rather than old outer envelope; then completed0/pub→ownQI→available child personal17contacts9keys.','Continue registered queues toward336, complete F2/F3/F5 final48 only after real48 acceptance; use source176 as reference assembly utility followed by independent full primary integrity closure, preserve 4 F3 original native/typed154 unknown runtime states.','Home500GiB floor; existing cumulative cleanup534.4086GiB/17203files retained, no additional cleanup needed while current floor met and no changed eligible failures.'];put(np,new)
ip=root(1362)/'full336-current309-actual-final48-delivery-progress-index.json';idx=load(ip)
for obj in qis:
 row=next(r for r in idx['cases'] if r['physical_case_id']==obj['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=obj['main_own_QI'],current_actual_render_receipt=obj['actual_render_receipt'],current_atomic_publish_receipt=obj['actual_atomic_publish_receipt'],current_personal_review_source=obj['source_personal_review'],case_credit=0,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[z['physical_case_id'] for z in qis],current309_two_published_QI_nextF5F2_live=ref(pp),source176_completion_only_reference_builder_adoption=ref(builder));assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==309;put(O/'full336-current309-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: checkpoint309 two published QI personal reviews and next F5 F2 originals','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':274,'accepted':309,'pending':27,'published_QI':[987,1164],'next_live':live,'home_free_GiB':free,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
