from pathlib import Path
import json,hashlib,datetime,copy,collections,subprocess,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_256.json';cp=load(cpfile);assert cp['checkpoint']==256 and cp['stage1_visual_accepted_complete_independent_cases']==302;ip=root(1330)/'full336-current302-actual-final48-delivery-progress-index.json';index=load(ip);rows={r['physical_case_id']:r for r in index['cases']};qis=[]
for orig,out in [(1181,1331),(1191,1332)]:
 p=root(out)/f'actual{orig}-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';j=load(p);assert j['all801_geometry_velocity_N3_times_UID_finite_verified'] and j['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked'] and j['full_frames']==801 and j['particles']==194427 and not rows[j['physical_case_id']].get('accepted_decision');qis.append({'original':orig,'own_QI':ref(p),'physical_case_id':j['physical_case_id'],'still_personal_visual_pending':True,'case_credit':0})
live=[]
for orig,pid,start,physical in [(1102,565610,'213371315','F3_TWOAXIS_P1200_AY0430_STAGE1_FIRST48_PITCH_VARIANT'),(951,566175,'213374697','F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025')]:
 proc=Path(f'/proc/{pid}');assert proc.exists();parts=proc.joinpath('stat').read_text().split(') ',1)[1].split();assert parts[19]==start;cmd=proc.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython') and b'--manifest' in cmd and b'--output-dir' in cmd;mp=Path(cmd[cmd.index(b'--manifest')+1].decode());private=Path(cmd[cmd.index(b'--output-dir')+1].decode());m=load(mp);assert m['physical_case_id']==physical and not rows[physical].get('accepted_decision');count=len(list((private/'frames').glob('frame_*.png')))
 if orig==1102:
  F=root(orig);q=load(F/'enabled-full836-render-request.json');z=load(F/'actual1075-full836-XMF-and-producer-typed-independent-review.json');assert q['physical_case_id']==physical and m['frames']==836 and m['particles']==179208 and m['dimension']==3;assert q['expected_frames']==836;source=ref(F/'actual1075-full836-XMF-and-producer-typed-independent-review.json'); future=1340
 else:
  binding=rows[physical]['actual_wrapper_contract_and_live_observation'];w=load(binding['actual_loaded_wrapper']['path']);assert sha(binding['actual_loaded_wrapper']['path'])==binding['actual_loaded_wrapper']['sha256'];assert Path(w['manifest'])==mp and w['expected_frames']==m['frames']==241 and w['expected_particles']==m['particles']==417505;source=ref(root(1283)/'actual-lastF6-full241-own-UID-N3-state0-scope-readiness-with-quantified3fluid-omissions.json');future=1341
 live.append({'original':orig,'physical_case_id':physical,'actual_pvpython_pid':pid,'actual_startticks':start,'process_state':parts[0],'actual_same_handle_live':True,'actual_manifest':ref(mp),'private_frame_filenames_stat_count':count,'private_output_root':str(private),'private_PNG_payload_IO':False,'prior_completed_scientific_integrity_proof':source,'future_own_QI_root':future,'future_own_QI_proof':None,'future_visual_decision':None,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_twoF5_actual1181_1191_published_full801QI_nextF3_original1102_F6last_original951_live_F3_durable_future836QI_1342';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_257.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1102_terminal_full836_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F3-original1102-full836-own-QI1340.py').read_bytes());proof=O/'two-published-F5-personal-visual-pending-nextF3-F6-current-live-process-and-ownQI-entrypoints.json';put(proof,{'schema':'ds02.two-completed-F5-next-actual-F3-F6-live-continuation.v1','at_utc':now.isoformat(),'two_actual_completed_F5_full801_QI_personal_pending':qis,'current_next_original_renderers_live':live,'F3_original1102_durable_QI_entry':ref(entry),'F3_after_terminal_command':['python3','-B',str(entry),'1102','1340'],'lastF6_fulltime_rigid_product':ref(root(1305)/'F6-FINAL48-FULLTIME-RIGID-MOTION-DELIVERY.json'),'lastF6_next_QI_requires_own241_render_plus_rigid_Time_tolerance1e-6_and_disclosed_three_fluid_omissions':True,'no_finished_QI_rerun':True,'no_original_simulation_or_renderer_restart':True,'scientific_payload_IO':False,'new_case_credit':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=257,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active302/336; full801 F5 originals1181/1191 both actualcompleted0/published ownQI1331/1332 complete, source188/208 personal43PNG in progress. Next same automatic F3 original1102 actual836 and lastF6 original951 actual241 now rendering; actualsource173 F2 final48 primary42/sixpending adopted with four explicit actualreceipt-role corrections.',previous_goal_turn_classification='PROGRESS: actual originalF5 1181/1191 both801 completed0/published and independently ownQI1331/1332 verified. Main source173 F2 final48 product42correct actualprimary joins and four request-receipt misclassifications repaired via immutable sidecars. Next actual original1102/951 same live PV PID/startticks reverified with advancing private frame filenames only.')
new['actual_progress']['actual1191_full801_own_QI']=qis[1]['own_QI'];new['actual_progress']['two_F5_completed_own801_QI_nextF3_F6_same_live_handles_durableF3_QI']=ref(proof);new['next_executable_tasks']=['Adopt source188 personal F5 M105T080 original1181 ownQI1331 and source208 personal F5 M112T095 original1191 ownQI1332 after exactsource finalcommit, personal43 publishedPNG and role checks; sourcecredit0 only main grants distinct1 each.','Observe same original F3 1102 PID565610/start213371315 and lastF6 original951 PID566175/start213374697; do not restart on observation timeout. After actualcompleted0/pub run F3 durableQI1340 once; bind F6 own241 particle fulltime rigid metadata before assigned personal11contacts10keys.','Adopt fresh174 F5 final48 28accepted20pending source catalog with own actualexecutionreceipt classification and mothercase-id alias/physical-id uniqueness.','Continue original registered queues and final336 delivery; protect current500GiB Home floor and534.4086GiB cleanup evidence; no repeated scientificQI for completed cases.'];put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);index['two_actual_completed_F5_own_QI_and_next_actual_F3_F6_current_live']=ref(proof);put(O/'full336-current302-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: close two F5 own801 QI and preserve next F3 F6 live original handles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':257,'accepted':302,'current_live_private_frame_counts':[(x['original'],x['private_frame_filenames_stat_count']) for x in live],'two_F5_actual_completed_QI':qis,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
