from pathlib import Path
import json,hashlib,datetime,subprocess,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.log','.xml','.xmf','.jsonl'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_252_visual_nine_new_cases_seven_F2render_six_F5XMF_two_bed_observer_recovery_live_checkpoint_1070';O.mkdir(exist_ok=True);assert not (H/"ROOT_LIVE_RESUMPTION_CHECKPOINT_163.json").exists();cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_162.json');assert cp['stage1_visual_accepted_complete_independent_cases']==252 and len(cp['accepted_decisions'])==252
actual=[load(p) for p in cp['accepted_decisions']];assert len({(z['family_id'],z.get('physical_case_id',z['case_id'])) for z in actual})==252;assert sum(cp['accepted_per_family'].values())==252 and all(not z.get('q_n_granted',False) and not z.get('q_e_granted',False) for z in actual)
guards=[(root(928)/'fair_CPU_dispatch.py','e2796fb88cc989278bcc4d194493f11e5ded7e6d2fb79ef37349d7ae7d8d679f'),(root(142)/'launch.py','708c4c83d22257f7b59bad93cd19915fb66a199a2a5b1291d6ada71bb467ea76'),(L/'scripts/ds_data02_runtime_v2.py','5098262e26dc5560487760181466b0a93a0e66239e5e54047dce5e761ae67a60'),(L/'scripts/ds_data02_strict_dispatch_v1.py','81bdd60e5de4fec362807043ab632864405f1667a0658560fb9349025aab75ec')]
for p,h in guards:assert sha(p)==h
rows=[];launchfiles=[]
for n in [951,983,984,987,988,1003,1009,1013,1020,1025,1028,1031,1032,1033,1034,1035,1037,1038,1045,1046,1047,1055,1058,1059,1060,1063,1064,1065,1066,1067,1068,1069]:
 o=root(n);p=o/'controller-launch-process.json';j=load(p);st=Path(f"/proc/{j['pid']}/stat");live=False
 if st.exists():
  s=st.read_text().split(') ',1)[1].split();live=s[0]!='Z' and s[19]==str(j['proc_start_ticks'])
 row={'root':n,'actual_launch':ref(p),'pid':j['pid'],'start_ticks':j['proc_start_ticks'],'same_handle_live_now':live,'restarted_by_observation':False};launchfiles.append(p)
 for name in ['controller-result.json','actual-progress.json']:
  f=o/name
  if f.exists():
   dst=O/f'root{n}-{name}-frozen.json';dst.write_bytes(f.read_bytes());row[name]=ref(dst)
 if not live and not(o/'controller-result.json').exists():row['primary_followup']='Handle absent requires original actual receipt/log classification before any successor; no restart inferred.'
 rows.append(row)
assert all(z['same_handle_live_now'] for z in rows if z['root'] in [1058,1059,1060,1063,1064,1065,1066,1067,1068,1069])
put(O/'actual-controller-handles-and-terminal-snapshots.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'controllers':rows,'guards_unchanged':[ref(p) for p,h in guards],'conversion_cap':1,'render_shared_cap':2,'scientific_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);a=json.loads(raw);attemptcounts={k:sum(z['kind']==k for z in a['attempts']) for k in ['qualification','production','cpu']};gpu=sum(z.get('gpu_seconds',0) for z in a['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in a['charges'])/3600;free=shutil.disk_usage('/home/jade').free/2**30
assert free>=500 and gpu<512 and cpu<3840 and attemptcounts['qualification']<1024 and attemptcounts['production']<720
cp.update(checkpoint=163,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_162.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_162.json'),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=a['reservations'],attempt_counts=attemptcounts,gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='Progress: 243 to252 nine new independent full-native visual products accepted in1057/1061/1062; source175/176 six F5 XMF1059/1060 enabled and genuinely live; source1016 first true bed0 preserved and remaining2 observer-only repair1058 genuinely live; seven F2 actual completed XMF products advanced to registered original full401 renders1063..1069. Cumulative515.503GiB failed cleanup retained, Home floor500 safe; no GPU rerun, recipe change or numerical precision credit. Last response cleanup revalidation was verification of completed cleanup; this goal continuation changes actual authoritative accepted state and real launch state.')
cp['actual_progress']['current_live_controller_snapshot']=ref(O/'actual-controller-handles-and-terminal-snapshots.json');cp['actual_progress']['F5_source175176_registered_six_original129_XMF']=[ref(root(n)/'controller-launch-process.json') for n in [1059,1060]];cp['actual_progress']['F2_seven_actual_XMF0_registered_full401_original116023_render']=[ref(root(n)/'controller-launch-process.json') for n in range(1063,1070)]
cp['next_executable_tasks']=['Integrate fresh135 genuinely completed full836 F3 visual after exact native forcing/initial clone QA/producer scope/UID/times independent closure; Root1032 AY0540 newly completed reported to reviewer.', 'Integrate fresh177 actual completed bed diagnostics for M086T095 and only real completed1055 M090T085/T095; preserve penetration/beyond footprint negatives and prepare bounded original116023 render, no worker0 physical pass.', 'Observe original951 same live handle for last F6 DZXY S1375YAWP18 full241 render; fresh150 no early credit/restart, F6 currently47.', 'Observe actual1058 two previously unsubmitted M088 bed jobs and six XMF1059/1060 same live handles; completed first1016 M086T095 never rerun.', 'Continue seven new F2 renders1063..1069 and existing1009; upon real full401 completion delegate all17contacts9keys visual and independent original native/typed UID/scopes closure.', 'Advance further actually completed typed/XMF outputs under unchanged CPU2 cap1 and render24/env2 sharedcap2; protect accepted/pending/live/reusable outputs and cumulative515.503GiB cleanup evidence.', 'Keep full336 target, seven48 unique physical cases, QN/QE unaccepted, approved cumulative512GPUh/3840CPUcoreh/1024qual/720prod and originaldeadline unchanged.']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_163.json',cp);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_163.json').relative_to(R))]+[str(p.relative_to(R)) for p in launchfiles]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: checkpoint 252 visual cases with seven real F2 renders and preserved bounded F5 recovery','--',*paths],cwd=R,check=True);print({'accepted':252,'families':cp['accepted_per_family'],'Home_free_GiB':round(free,2),'charged_GPU_h':gpu,'charged_CPU_core_h':cpu,'attempt_counts':attemptcounts,'verified_live_handles':sum(z['same_handle_live_now'] for z in rows),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
