from pathlib import Path
import json,hashlib,subprocess,runpy,datetime,difflib
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'));O=H/'root_stage1_grounded116_manifest_CLI_repair1_and_delegated_failure129_adoption_950';O.mkdir(exist_ok=False);load=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();refs=[];packages=[]
for fn,cid,prefix in [('F3','08e88508','root_followup_116_'),('F3','866c2ffe','root_followup_115_'),('F6','e9a71df6','root_followup_129_f6_root945_')]:
 W=Path('/home/jade/.codex/worktrees/ds-data-02-'+fn.lower()+'/DualSPHysics');S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families'/fn/'handoff_20261003').glob(prefix+'*'));commit=subprocess.check_output(['git','rev-parse',cid],cwd=W,text=True).strip();rel=S.relative_to(W)
 for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
  src=W/name;blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert src.read_bytes()==blob and src.suffix in ['.json','.py','.md'];dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==blob;dst.write_bytes(blob);refs.append({'path':str(dst),'sha256':sha(dst)})
 packages.append({'family':fn,'commit':commit,'package':str(R/rel)})
worker=Path(packages[0]['package'])/'workers/nvme_render_successor.py';base=Path(load(root(944)/'actual114-and128-adoption-review.json')['packages'][0]['package'])/'workers/nvme_render_successor.py';diff=''.join(difflib.unified_diff(base.read_text().splitlines(True),worker.read_text().splitlines(True)));(O/'source114-to116.diff.txt').write_text(diff);api=runpy.run_path(str(worker));q=load(load(root(945)/'controller-config.json')['outer_requests'][0]);w=load(root(945)/'wrapper-requests'/(q['physical_case_id']+'-enabled-wrapper.json'));w['schema']=api['SCHEMA'];meta=api['_manifest_metadata'](w);assert meta['manifest']==w['manifest'] and Path(meta['manifest']).is_absolute() and load(meta['manifest'])['schema']=='ds02.stage1.paraview-temporal-product.v1';assert meta['frames']==241 and meta['particles']==417505;assert 'manifest_path = _absolute(' in worker.read_text() and '"manifest": str(manifest_path),' in worker.read_text();proof={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'packages':packages,'adopted_files':refs,'source_adopted_byte_exact':True,'worker116':str(worker),'worker116_sha256':sha(worker),'worker116_schema':api['SCHEMA'],'independent_actual_manifest_metadata_path_equality_pass':True,'original023_scientific_renderer_unchanged':True,'failure_classification946':{'path':str(root(946)/'actual-cli-manifest-failure-classification.json'),'sha256':sha(root(946)/'actual-cli-manifest-failure-classification.json')},'grounded_repair_number':1,'max_grounded_repairs_for_class':2,'independent_source_review':'Diff114→116 separates originalabsolute manifest_path fromparsedJSON metadata andreturnsoriginalpath; keepsboundedlogs/successpublication/budgetfloors. Source114/112 andfailed934/945 allimmutable.','fresh115_disabled_successor_superseded_by_registered948_remaining9':True,'fresh129_delegated_actual945_failed1_noPNG_casecredit0_retained':True,'main_scientific_payload_IO':False,'case_credit':0};(O/'actual116-grounded-path-repair-adoption.json').write_text(json.dumps(proof,indent=2)+'\n');(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'adopted_files':len(refs),'worker116_sha':sha(worker),'correct_actual_manifest_path':True});print(diff[:3300])
