from pathlib import Path
import json,hashlib,datetime,subprocess,copy,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit='60ee64c0fad0415f1f98db833323879db373810c';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_175_f3_assigned_f2_rx063_rot105_root1155_personal_visual_review_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==7;blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh175.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1346)/'actual1155-full401-own-QI-UID-N3-native-typed-role-three-fluid-omissions-previsual-proof.json';qi=load(qip);cid=qi['case_id'];pid=qi['physical_case_id'];relc=Path('metadata/chain-audit')/(pid+'.json');relp=Path('metadata/png-evidence')/(pid+'.json');c=load(P/relc);v=load(P/relp);pr=load(P/'metadata/source-review-provenance.json');m=load(P/'metadata/package-manifest.json');assert all(j['case_id']==cid and j['physical_case_id']==pid for j in [c,v,m]);assert c['actual_family_id']=='F2' and c['assigned_worktree_family_id']=='F3'
assert c['visual_review_status']=='visual-approved-by-delegated-agent_pending_main_adoption' and c['review_limits']['case_credit']==c['review_limits']['independent_case_increment']==0 and not c['review_limits']['q_n_granted'] and not c['review_limits']['q_e_granted'] and not c['review_limits']['numerical_precision_accepted']
assert all(not c['review_limits'][k] for k in ['global_state_written','shared_index_or_ledger_modified','scientific_payload_opened_or_hashed_by_this_agent','h5_bi4_csv_dat_vtk_payload_opened_or_hashed_by_this_agent','jobs_started','jobs_restarted','jobs_stopped','source_or_science_files_modified'])
assert all(not pr['read_boundary'][k] for k in ['h5_opened_or_hashed','bi4_opened_or_hashed','csv_opened_or_hashed','dat_opened_or_hashed','vtk_opened_or_hashed','scientific_payload_opened_or_hashed','jobs_started','jobs_restarted','jobs_stopped','shared_state_modified']);assert pr['main_qi_proof']['path']==str(qip);check(pr['main_qi_proof'])
e=qi['actual_completed_metadata_evidence']
for k,x in c['actual_paths'].items():
 check(x)
 if k=='qi_proof':assert x==ref(qip)
 else:assert x==e[{'xmf_receipt':'XMF_receipt','xmf_manifest':'XMF_manifest','xmf_xml':'XMF_XML'}.get(k,k)]
for stage,key in [('gencase','typed_source_gencase_receipt'),('native','native_receipt'),('typed','typed_receipt'),('xmf','XMF_receipt'),('render','render_receipt')]:
 x=c['stages'][stage];assert x['path']==e[key]['path'] and x['sha256']==e[key]['sha256'];check(x);j=load(x['path']);assert j['status']=='completed' and j['returncode']==0 and j['request']['case_id']==cid
canonical=qi['native_canonical_condition_sha256'];legacy=qi['typed_XMF_actual_legacy_producer_condition_sha256'];assert c['scope_roles']['native_canonical_condition_sha256']==canonical and c['scope_roles']['typed_xmf_actual_legacy_producer_condition_sha256']==legacy and canonical!=legacy
for ns,pfx in [('native','native'),('XMF','xmf')]:
 for key,val in qi['actual_native_XMF_plan_field_namespaces'][ns].items():assert c['scope_roles'][pfx+'_'+key.removesuffix('_sha256')]==val
assert c['counts']['frames']==qi['frames']==401 and c['counts']['particles']==qi['particles']==418104 and c['counts']['initial_type_counts']==qi['actual_initial_type_counts'] and c['counts']['terminal_type_counts']==qi['actual_terminal_type_counts'];assert c['actual_time_window_s']==qi['actual_time_window_s'] and c['lifecycle_omissions']==qi['lifecycle_omissions'] and not qi['all_native_UIDs_active_each_frame']
# The source stage named initial_qa references main QI metadata, not an actual runner receipt.
source_initial=c['stages']['initial_qa'];assert source_initial['path']==str(qip) and source_initial['sha256']==sha(qip) and source_initial['status']=='completed' and source_initial['returncode']==0;assert 'status' not in qi and 'returncode' not in qi
nrc=load(e['native_receipt']['path']);nq=nrc['request'];genuine={}
for k in ['initial_qa_receipt','initial_qa_report']:
 x=ref(nq[k]);assert x['sha256']==nrc['input_hashes_at_launch'][x['path']]==nrc['input_hashes_after_run'][x['path']];genuine[k]=x
qa_rc=load(genuine['initial_qa_receipt']['path']);qa=load(genuine['initial_qa_report']['path']);assert qa_rc['status']=='completed' and qa_rc['returncode']==0 and qa_rc['request']['case_id']==qa['case_id']==cid and qa['status']=='pass'
correction={'source_json_pointer':'/stages/initial_qa','source_original_stage':source_initial,'source_role':'main metadata QI summary incorrectly serialized with synthetic runner completed/0 fields','main_QI_metadata_status_and_returncode_fields_present':False,'actual_initial_qa_receipt_and_report':genuine,'actual_initial_qa_completed0_and_report_pass':True,'genuine_QA_refs_bound_to_same_native_launch_and_after_SHA':True,'source_bytes_preserved':True}
r=load(e['render_report']['path']);pub=load(e['render_publish_receipt']['path']);rc=load(e['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(e['render_report']['path']);out=Path(pub['published_output_root']);published={x['relative_path']:x for x in pub['files_excluding_receipt']};entries=v['entries'];contacts=[x for x in entries if x['role']=='contact_sheet'];keys=[x for x in entries if x['role']=='event_keyframe'];assert len(entries)==26 and len(contacts)==17 and len(keys)==9 and [x['index'] for x in contacts]==list(range(17)) and [x['frame_index'] for x in keys]==list(range(0,401,50));assert [x['path'] for x in contacts]==r['outputs']['contact_sheets']
for x in entries:
 p=Path(x['path']);a=published[x['relative_path']];assert p==out/x['relative_path'] and sha(p)==x['producer_sha256']==a['sha256'] and p.stat().st_size==x['bytes']==a['bytes'] and x['viewed'] and x['view_method']=='view_image'
reviewed=c['reviewed_at_utc'];assert reviewed==pr['reviewed_at_utc'];parse=lambda s:datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',s).replace('Z','+00:00'));now=datetime.datetime.now(datetime.timezone.utc);assert parse(rc['finished_at_utc'])<=parse(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_265.json';cp=load(cpfile);assert cp['checkpoint']==265 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==306 and cp['accepted_per_family']['F2']==42;ip=root(1351)/'full336-current306-actual-final48-delivery-progress-index.json';index=load(ip);row=next(x for x in index['cases'] if x['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_source175_F2_RX063ROT105_original1155_full401QI_personal26PNG_three_fluid_omissions_genuine_initialQA_receipt_role_correction_visual_acceptance_1352';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_266.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source175-byte-exact-readonly-validator-main26publishedPNG-own401QI-genuine-initialQA-stage-role-proof.json';put(vp,{'schema':'ds02.source175.main.actualF2.adoption-integrity.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'source_explicit_review_timestamp_original_bytes':reviewed,'nine_fractional_timestamp_trimmed_for_parser_only':True,'actual_review_after_completed_atomic_publication':True,'all26_PNG_actual_SHA_match_atomic_publish':True,'source_initial_qa_stage_role_correction':correction,'all_other_source_listed_actual_chain_refs_equal_own_QI':True,'main_scientific_payload_IO':False,'new_case_credit':1})
dp=O/(pid+'-delegated-visual-decision.json');normcontacts=[{**x,'sha256':x['producer_sha256']} for x in contacts];normkeys=[{**x,'sha256':x['producer_sha256'],'frame':x['frame_index']} for x in keys];put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F3','actual_review_family':'F2','source_personal_visual_review':ref(R/prefix/relc),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':{**e,**genuine},'source_initial_qa_stage_role_correction':correction,'full_native_frames':401,'particle_count':418104,'initial_fluid_particles':21114,'actual_type_counts':c['counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all401_UID_N3_actual_times_finite_active_states_verified':True,'actual_quantified_missing_fluid':qi['lifecycle_omissions'],'all_native_UIDs_active_each_frame':False,'missing_fluid_locations_states_causes_unknown':True,'missing_fluid_states_not_reconstructed':True,'no_user_numeric_threshold_inferred':True,'actual_native_XMF_plan_field_namespaces':qi['actual_native_XMF_plan_field_namespaces'],'strict_container_guarantee':False,'subDP_precision_not_claimed':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'contact_sheets':normcontacts,'keyframes':normkeys,'visual_observations':c['visual_observations'],'visual_limits':c['review_limits'],'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source175-actual1155-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1;new.update(checkpoint=266,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=307,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active307/336; F1/F4/F6/F7=48,F2=43,F3=42,F5=30. ActualF2 original1155 full401 ownQI1346 plus source175 personal26PNG accepted with3 fluid omissions/652 cumulative unknown cause and genuine initialQA receipt recovered separately from source metadata QI stage. Source190 completeF6 catalog pending adoption; originalF5 1150/1157 sameprocess render with durable ownQI1349/1350 and personalfresh210/191 assigned.',previous_goal_turn_classification='PROGRESS: actualF3 original1102 own836QI and personal44PNG accepted306; nextF5 original1150/1157 durable own801 metadata QI entrypoints and actual plan namespaces pinned; F2 original1155 full401 ownQI plus source175 personal26PNG now accepted307/F2=43 with truthful original3fluid omissions and initialQA metadata-vs-runner role correction.')
new['actual_progress']['source175_actualF2_1155_visual_acceptance']=ref(ap);new['source_agents']['production_recovery']='fresh175 actualF2 accepted43/48; idle until next published case or finaldelivery integration task.';new['next_executable_tasks']=['Adopt source190 F6 full48 particle-rigid catalog metadata; recover existing baseline native/typed primary refs without filling true nativeconditionabsence, preserve oldbaseline rigid Part/time uncertainty.','Observe same F5 original1150/1157; execute durable ownQI1349/1350 once after actualcompleted0/pub, supply source210/191 personal34contacts9keys.','Continue registeredremaining29 originalrenders/personalreviews; update completedF2/F3/F5 family catalogs once all48 actualaccepted.','Preserve Home500GiB floor and cumulative534.4086GiB safe cleanup; new failure/output changes trigger bounded safe cleanup review.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==307;put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=307,registered_pending_independent_physical_cases=29,new_case_credit=1);row.update(status='visual-approved-in-checkpoint266',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip));index['actual_unaccepted_completed0_published_physical_cases']=[r for r in index['actual_unaccepted_completed0_published_physical_cases'] if (r if isinstance(r,str) else r['physical_case_id'])!=pid];assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==307;put(O/'full336-current307-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX063ROT105 preserving3fluid omissions and genuine initial QA roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':266,'accepted':307,'F2':43,'pending':29,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
