from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,collections,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_192.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==271 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_193.json').exists();base_path=root(1205)/'full336-role-aware-physical-registration-progress-index.json';base=load(base_path);accepted={}
for p in cp['accepted_decisions']:
 a=load(p);assert a['physical_case_id'] not in accepted;accepted[a['physical_case_id']]=(Path(p),a)
assert len(accepted)==271
rows=[];frontier=[];actual0=[]
for oldrow in base['cases']:
 row=copy.deepcopy(oldrow);pid=row['physical_case_id'];row['source_previous_role_aware_row']=ref(base_path);row['new_case_credit']=0
 if pid in accepted:
  p,a=accepted[pid];row.update(status='visual-approved-in-checkpoint192',accepted_decision=ref(p),case_credit_already_in_authoritative_checkpoint=1,accepted_decision_top_condition_sha256=a['physical_condition_sha256'],accepted_decision_top_hash_role='preserved accepted semantic declaration; never overrides actual native request scope',precision_status='视觉检查通过、数值精度未验收');row.pop('case_credit',None)
 else:
  qr=row['latest_registered_render_request'];assert sha(qr['path'])==qr['sha256'];q=load(qr['path']);assert q['physical_case_id']==pid and q['case_id']==row['case_id'];controller=Path(qr['path']).parent
  if controller.name=='requests':controller=controller.parent
  launch=load(controller/'controller-launch-process.json');sp=Path('/proc')/str(launch['pid'])/'stat';same=False;state=None
  if sp.exists():parts=sp.read_text().rsplit(')',1)[1].split();state=parts[0];same=state!='Z' and parts[19]==str(launch['proc_start_ticks'])
  receipt=Path(q['attempt_root'])/'execution-receipt.json';r=load(receipt) if receipt.exists() else {};terminal=controller/'controller-result.json';done=r.get('status')=='completed' and r.get('returncode')==0
  assert same or done or terminal.exists(),(pid,'missing originalhandlewithoutactualterminal')
  published=False;publication=None
  if done:
   pp=receipt.parent/'render/render-publish-receipt.json';assert pp.is_file();pj=load(pp);assert pj['status']=='published_after_atomic_rename' and pj['case_id']==q['case_id'];published=True;publication=ref(pp);actual0.append(pid)
  row.update(status='complete-published-render-awaiting-personal-review' if done else 'original-render-registered-still-pending',case_credit=0,current_controller_observation={'launch':ref(controller/'controller-launch-process.json'),'same_actual_PID_startticks_live':same,'proc_state':state,'actual_receipt':ref(receipt) if receipt.exists() else None,'actual_worker_status':r.get('status','no_actual_receipt'),'actual_worker_returncode':r.get('returncode'),'controller_terminal':ref(terminal) if terminal.exists() else None,'published0':published,'publish_receipt':publication,'receipt_hash_is_observation_only_not_future_stable_input':True,'wait_is_not_restart':True});frontier.append({'family_id':row['family_id'],'physical_case_id':pid,'controller_root':str(controller),'expected_frames':q['expected_frames'],**row['current_controller_observation']})
 rows.append(row)
counts=collections.Counter(r['family_id'] for r in rows);assert len(rows)==len({r['physical_case_id'] for r in rows})==336 and counts=={f'F{i}':48 for i in range(1,8)};assert len(frontier)==65 and len(accepted)==271
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
O=H/'root_stage1_271_visual_full336_role_aware_registration_actual65_pending_controller_frontier_checkpoint_1215';O.mkdir(exist_ok=False);index=O/'full336-current271-role-aware-registration-progress-index.json';put(index,{'schema':'ds02.stage1.full336.role-aware-progress-index.v3','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_authoritative_checkpoint':ref(cp_path),'old_role_aware_index_preserved':ref(base_path),'accepted_independent_physical_cases':271,'registered_pending_independent_physical_cases':65,'union_distinct_physical_case_ids':336,'per_family_union_counts':dict(counts),'actual_unaccepted_completed0_published_physical_cases':actual0,'delivery_complete':False,'Q_N':0,'Q_E':0,'native_request_role_closure_snapshot_inherited_from1205_not_new_native_certificate':True,'old_original_scope_absences_and_aliases_preserved':True,'cases':rows,'new_case_credit':0,'main_scientific_payload_IO':False})
put(O/'current65-original-controller-and-actual-render-frontier.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'frontier':frontier,'all_have_same_original_live_handle_or_actual_terminal':True,'new_case_credit':0,'main_scientific_payload_IO':False})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=193,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: full336 role-aware index updated from immutable1205 to actual271 accepted/65pending, eachfamily48physicalIDs, all65pending currentoriginalPID/startticks oractualterminal directlyverified. Actual1152 F5full801published0 andQIclosed remainsawaitingpersonal192, no automaticcredit from0. Original1130/1137 full801F5live.',authorized_work_state='Active271/336: full336 registration currentroleaware index verified271accepted+65pending. F5actual1152published0 awaiting192personalreview; otheroriginalrenderhandlesprotected, no duplicatednativejobs. Source167F2actualnativealiasclosure and150F1F4F7stagedmembershipaudit ongoing.')
cp['actual_progress']['full336_current271_role_aware_registered_progress_index']=ref(index);cp['actual_progress']['current65_original_registered_render_handles']=ref(O/'current65-original-controller-and-actual-render-frontier.json');cp['source_agents']['production_recovery']='fresh150 F1F4F7 explicitfirst8/24/final48metadataaudit whilewaitingnewF3personalreview';cp['next_executable_tasks']=['Adopt source192 actual1152 F5personal34contacts9keys; no creditbeforeownvisualpasses','Actual1130/1137 F5full801originalhandleslive, after0publish nextpersonalreviews','Adopt source167 F2rawownnativeJSON condition/IDaliasclosure withoutcopyingacceptedtop','Adopt source150 F1F4F7 authoritativefirst8/24/final48physicalmembership, noinventedsubsets','Continue65 cases fromalreadyregisteredfull336; original951lastF6pending, Q-N/Q-E0']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_193.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_193.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: refresh full physical registry and verify all original pending render handles','--',*paths],cwd=R,check=True);print({'checkpoint':193,'accepted':271,'pending':65,'union':336,'published0_unaccepted':actual0,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
