from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections,copy,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
pre='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/';p159=pre+'root_followup_159_f3_assigned_f5_m096_t095_personal_visual_review_v1';p160=pre+'root_followup_160_f3_assigned_f5_m096_t095_physical_screen_sidecar_v1';c159='ad50960f6aa1043e3b8de35be744a7366cf9b876';c160='64291b92ccf206e7d84f9904ea462d125c33dbaf';packages=[];validators=[]
for prefix,commit,num,count in [(p159,c159,159,7),(p160,c160,160,4)]:
 names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==count
 assert all(subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W)==(W/n).read_bytes() for n in names), 'source worktree must match selected stable commit before any mutation'
 before={n:sha(W/n) for n in names};vp=W/prefix/f'scripts/validate_fresh{num}.py';v=subprocess.run(['python3','-B',str(vp)],capture_output=True,text=True);assert v.returncode==0,(v.stdout,v.stderr);assert before=={n:sha(W/n) for n in names};packages.append((commit,names));validators.append({'validator':ref(vp),'returncode':v.returncode,'stdout':v.stdout,'stderr':v.stderr,'source_bytes_unchanged':True})
pid='F5_COMPACT_RUNUP_RECOVERY_C082S1_M096_T095';vrel=f'metadata/visual-review/{pid}-delegated-visual-decision.json';crel=f'metadata/chain-audit/{pid}.json';prel=f'metadata/png-evidence/{pid}.json';srel='metadata/f5-m096-t095-physical-screen-sidecar.json';v=load(W/p159/vrel);ch=load(W/p159/crel);png=load(W/p159/prel);sc=load(W/p160/srel);qp=root(1257)/'actual1163-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qp);refs=qi['actual_completed_metadata_evidence'];cid=v['case_id']
assert all(x['case_id']==cid and x['physical_case_id']==pid and x['actual_family_id']=='F5' and x['assigned_worktree_family_id']=='F3' for x in [v,ch,png,sc])
assert v['status']=='visual-approved-by-delegated-agent' and sc['status']=='physical-screen-reviewed-by-delegated-agent' and not any(sc['non_claims'].values());assert v['review_limits']['case_credit']==sc['case_credit']==0 and not v['review_limits']['q_n_granted'] and not v['review_limits']['q_e_granted']
assert sc['main_qi_binding']['path']==str(qp) and sc['main_qi_binding']['sha256']==sha(qp)
for key,rel in [('decision',vrel),('chain',crel),('png_evidence',prel)]:assert sc['source_fresh159'][key+'_path']==str(W/p159/rel) and sc['source_fresh159'][key+'_sha256']==sha(W/p159/rel)
for e in refs.values():assert sha(e['path'])==e['sha256']
for k,e in ch['actual_paths'].items():
 if k=='actual_qi_proof':assert e['path']==str(qp) and not re.fullmatch(r'[0-9a-f]{64}',e['sha256'])
 else:assert sha(e['path'])==e['sha256']
for k,e in refs.items():assert ch['actual_paths'][k]['path']==e['path'] and ch['actual_paths'][k]['sha256']==e['sha256']
cor=sc['role_corrections_from_fresh159'];assert cor['actual_qi_proof_sha256']['fresh159_value']==ch['actual_paths']['actual_qi_proof']['sha256'] and cor['actual_qi_proof_sha256']['correct_sha256']==sha(qp)
xmlcor=cor['source_def_vs_generated_xml'];assert xmlcor['true_source_def_path']==qi['actual_SourceDef']['path'] and xmlcor['true_source_def_sha256']==qi['actual_SourceDef']['sha256'];assert sha(xmlcor['true_source_def_path'])==xmlcor['true_source_def_sha256']
assert xmlcor['generated_xml_path']==ch['actual_paths']['source_def']['path']==refs['generated_xml']['path'] and xmlcor['generated_xml_sha256']==refs['generated_xml']['sha256'];assert sha(xmlcor['generated_xml_path'])==xmlcor['generated_xml_sha256']
canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];roles=v['scope_roles'];assert roles==ch['scope_roles'] and roles['native_canonical_owner_condition_sha256']==roles['native_source_plan_condition_sha256']==canonical and roles['actual_converter_legacy_scope_sha256']==legacy and roles['source_def_sha256']==qi['actual_SourceDef']['sha256']
assert qi['XMF_source_plan_condition_field_sha256']==canonical and qi['actual_native_source_plan_condition_field_present'] and qi['actual_native_source_plan_condition_sha256']==canonical and qi['bed_declared_source_plan_field_sha256']==qi['actual_SourceDef']['sha256'] and canonical!=qi['actual_SourceDef']['sha256']
assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
for k in ['gencase','initial_qa','native','typed','xmf','bed','render']:
 a=load(refs[k+'_receipt']['path']);assert (a['status'],a['returncode'])==('completed',0) and a['request']['case_id']==cid
r=load(refs['render_report']['path']);pub=load(refs['render_publish_receipt']['path']);assert pub['status']=='published_after_atomic_rename';entries=png['entries'];assert len(entries)==43 and len({e['path'] for e in entries})==43;contacts=[e for e in entries if e['role']=='contact_sheet'];keys=[e for e in entries if e['role']=='event_keyframe'];assert len(contacts)==34 and [e['path'] for e in contacts]==r['outputs']['contact_sheets'] and [e['frame_index'] for e in keys]==list(range(0,801,100));pm={e['relative_path']:e for e in pub['files_excluding_receipt']}
assert {(e['path'],e['sha256'],e['bytes']) for e in sc['png_evidence_binding']['entries']}=={(e['path'],e['sha256'],e['bytes']) for e in entries}
for e in entries:assert e['viewed'] and e['view_method']=='view_image' and sha(e['path'])==e['sha256']==pm[e['relative_path']]['sha256'] and Path(e['path']).stat().st_size==e['bytes']==pm[e['relative_path']]['bytes']
cpp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_220.json';cp=load(cpp);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==281 and cp['accepted_per_family']['F5']==17;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {d.get('physical_case_id',d['case_id']) for d in old}
ixp=root(1258)/'full336-current281-actual-wrapper-contract-role-aware-registration-progress-index.json';idx=load(ixp);rows=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(rows)==1 and not rows[0].get('accepted_decision') and rows[0]['native_request_scope']['sha256']==canonical
gp=root(1258)/'F5-actual-first24-growing-prefix17-frozen8-acceptance-order.json';g=load(gp);assert g['actual_first24_realized_prefix_count']==len(g['physical_case_ids_actual_delivery_order'])==17 and pid not in g['physical_case_ids_actual_delivery_order']
for e in g['actual_visual_decisions']:assert sha(e['path'])==e['sha256']
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;cnt=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;assert free>=500 and gpu<=512 and cpu<=3840 and cnt['qualification']<=1024 and cnt['production']<=720
assert not list(H.glob('root*_1260')) and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_221.json').exists();O=H/'root_stage1_source159160_assignedF3_actualF5_M096T095_full801QI_43personalPNG_physical_screen_role_closure_prefix18_visual_acceptance_1260';O.mkdir();adopted=[]
for commit,names in packages:
 for n in names:
  bts=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert bts==(W/n).read_bytes();p=R/n;assert not p.exists() or p.read_bytes()==bts;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(bts);adopted.append(ref(p))
put(O/'source159160-exact-adoption-readonly-validators.json',{'source_commits':[c159,c160],'adopted_files':adopted,'validators':validators,'source_original_bytes_unchanged':True,'main_independently_verified_both_XML_paths_and_digests':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat()
alias=O/'source159-original-placeholder-and-generatedXML-alias-role-closure.json';put(alias,{'original_source_chain':ref(R/p159/crel),'original_QI_ref_preserved':ch['actual_paths']['actual_qi_proof'],'original_QI_placeholder_is_not_SHA256':True,'actual_QI_proof':ref(qp),'original_source_def_named_reference':ch['actual_paths']['source_def'],'actual_original_alias_role':'GenCase prepared generated XML; not true SourceDef','actual_generated_XML':refs['generated_xml'],'actual_SourceDef':qi['actual_SourceDef'],'both_actual_XML_paths_and_digests_independently_verified':True,'delegated_clarification':ref(R/p160/srel),'original_metadata_bytes_preserved':True,'new_case_credit':0})
dp=O/(pid+'-delegated-visual-decision.json');decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_plan_condition_sha256':canonical,'native_request_source_plan_condition_field_present':True,'native_and_XMF_plan_fields_have_canonical_owner_role':True,'bed_declared_source_plan_field_sha256':qi['bed_declared_source_plan_field_sha256'],'source_definition_sha256':qi['actual_SourceDef']['sha256'],'source_review_assigned_worktree_family_id':'F3','source_review_actual_physical_family_id':'F5','source_review_commit':c159,'source_physical_screen_commit':c160,'source_visual_review':ref(R/p159/vrel),'source_review_closure':ref(R/p159/crel),'source_physical_visual_screen':ref(R/p160/srel),'source_alias_role_closure':ref(alias),'actual_completed_metadata_evidence':refs,'independent_full801_QI_previsual_proof':ref(qp),'full_native_frames':801,'particles':194427,'actual_physical_window_s':qi['actual_time_window_s'],'all801_geometry_velocity_N3_times_UID_finite_verified':True,'all_native_UIDs_active_each_frame':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':sc['physical_screen'],'original_render_integrity_observations':v['visual_observations'],'contacts_personally_viewed':34,'key_frames_personally_viewed':list(range(0,801,100)),'all43_reviewed_PNGs_main_bound_to_actual_publish_hashes':True,'all801_full_bed_UID_footprint_one_DP_two_DP_diagnostics_checked':True,'positive_depth_below_DP_not_proven_absent_by_zero_bin_counts':True,'large_runup_inundation_or_strict_container_guarantee':False,'initial_qa_numerical_precision_negative':qi['actual_initial_QA_precision_negative'],'historical_AB_negative_evidence_preserved':ch['historical_negative_evidence'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source159160-actual1163-full801QI-personal-physical-visual-adoption-proof.json';put(proof,{'source_commits':[c159,c160],'source_QI':ref(qp),'all_original_QI_stage_hashes_match':True,'all43_personally_reviewed_PNGs_match_published_hashes':True,'physical_visual_screen_explicit_not_only_render_damage':True,'source_family_assignment_F3_not_physical_F5_case_counter':True,'source_placeholder_and_generatedXML_alias_preserved_with_actual_role_closure':ref(alias),'new_decision':ref(dp),'new_case_credit':1,'main_scientific_payload_IO':False})
gids=g['physical_case_ids_actual_delivery_order']+[pid];grefs=g['actual_visual_decisions']+[ref(dp)];assert len(set(gids))==18 and gids[:8]==g['first8_physical_case_ids'];gout=O/'F5-actual-first24-growing-prefix18-frozen8-acceptance-order.json';put(gout,{'schema':'ds02.main.F5.actual-first24-growing-delivery-prefix.v3','at_utc':now,'first8_frozen_authority':g['first8_frozen_authority'],'previous_actual_prefix17':ref(gp),'predecessor_authoritative_checkpoint':ref(cpp),'newly_accepted_decision':ref(dp),'authority_role':'stable predecessor220 F5=17 plus new immutable decision; successor221 adopts prefix','first8_physical_case_ids':g['first8_physical_case_ids'],'actual_first24_realized_prefix_count':18,'actual_first24_delivered':False,'target_first24':24,'target_final48':48,'first8_subset_realized_prefix_subset_final48_verified':True,'physical_case_ids_actual_delivery_order':gids,'actual_visual_decisions':grefs,'new_case_credit':0,'precision_status':'视觉检查通过、数值精度未验收'})
lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);cp=copy.deepcopy(cp);cp['accepted_per_family']['F5']+=1;cp.update(checkpoint=221,at_utc=now,predecessor=str(cpp),predecessor_sha256=sha(cpp),stage1_visual_accepted_complete_independent_cases=282,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts=dict(cnt),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: actual1163 full801QI1257 plus source159 personally43PNG and source160 explicit physicalscreen accepted282/F5=18. OriginalQIplaceholder notSHA and source_def aliasactuallygeneratedXML preserved, actualQP/SourceDef digests independently closed. AssignmentF3 stays distinct actualF5. Source198 timestampclarification1259 adopted.',authorized_work_state='Active282/336 remaining54; F5actualfirst24 prefix18 not24. Current originalF3P1200AY0320 andF5M105T090 rendering through same handles. Source175 F1/F4/F7 actualfinal48 formalmetadata delivery pending; numerical precision unaccepted and Home500GiB floor protected.')
assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==282 and set(gids)=={d.get('physical_case_id',d['case_id']) for d in [load(p) for p in cp['accepted_decisions']] if d['family_id']=='F5'}
cp['actual_progress']['source159160_F5_actual1163_visual_acceptance']=ref(proof);cp['actual_progress']['F5_actual_first24_realized_prefix18']=ref(gout);cp['actual_progress']['source198_clock_placeholder_clarification']=ref(root(1259)/'source198-clock-clarification-immutable-adoption-proof.json');cp['source_agents']['production_recovery']='fresh159160 accepted actualF5=18; fresh161 original1047 F3P1200AY0320 personal full836 after publish';cp['next_executable_tasks']=['Adopt source175 actualF1/F4/F7 final48 delivery with realfrozen8/actual24 subset proof and actual native roles, no duplicatecredit.','Continue same original1047 F3P1200AY0320 full836 and1182 F5M105T090 full801 render handles; personally review after actualpublish.','Extend F5realfirst24 prefix18 to24 then48, preserve originalnegative precision and fullscientific provenance.']
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_221.json';put(newcp,cp);rows[0].update(status='visual-approved-in-checkpoint221',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='actual native owner condition; generatedXML vs SourceDef and typedlegacy roles separate',precision_status='视觉检查通过、数值精度未验收');idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(ixp),accepted_independent_physical_cases=282,registered_pending_independent_physical_cases=54,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[p for p in idx['actual_unaccepted_completed0_published_physical_cases'] if p!=pid];idx['controller_observations_inherited_not_new_live_probe']=True;put(O/'full336-current282-actual-wrapper-contract-role-aware-registration-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 M096 T095 full801 with explicit physical screen and source roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':221,'accepted':282,'F5':18,'remaining':54,'Home_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
