from pathlib import Path
import json,hashlib,copy,datetime,collections,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_268.json';cp=load(cpfile);assert cp['checkpoint']==268 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==307
qip=root(1349)/'actual1150-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip);assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['new_case_credit']==0;rq=qi['actual_completed_metadata_evidence'];pub=load(rq['render_publish_receipt']['path']);rc=load(rq['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and rc['status']=='completed' and rc['returncode']==0
F=root(987);oldp=F/'actual977-full836-XMF-and974-typed-independent-review.json';old=load(oldp);refs={k:v for k,v in old.items() if isinstance(v,dict) and 'path' in v and 'sha256' in v}
for e in refs.values():check(e)
n=load(old['actual_native_receipt']['path']);t=load(old['actual_typed_report']['path']);x=load(old['actual_XMF_manifest']['path']);q=load(F/'enabled-full836-render-request.json');w=load(F/'enabled-render-wrapper.json');canonical=n['request']['physical_condition_sha256'];assert canonical==t['hash_scopes']['physical_condition_sha256']==x['physical_condition_sha256']=='7560a18fa29742681ee567b06567ed4052da8ceb138b601e94b5223df22660f5';assert t['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1';mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n['request']),('XMF',x)]};assert all(not z['present'] and z['value'] is None for obj in mask.values() for z in obj.values());assert n['status']=='completed' and n['returncode']==0 and q['physical_case_id']==w['physical_case_id']==n['request']['physical_case_id']==x['physical_case_id'];assert w['expected_frames']==t['frames']==x['frames']==836 and w['expected_particles']==t['particles']==x['particles']==179208
assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
front=[]
for original,pid,start,ownqi in [(1157,584196,'213555954',1350),(987,599335,'213680043',1355)]:
 P=Path(f'/proc/{pid}');live=None;terminal=root(original)/'controller-result.json'
 if P.exists():
  stat=P.joinpath('stat').read_text().split(') ',1)[1].split();assert stat[19]==start;cmd=P.joinpath('cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert f'root{original}' in str(out);live={'pid':pid,'startticks':start,'state':stat[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
 front.append({'original':original,'live_process':live,'actual_terminal':ref(terminal) if terminal.exists() else None,'future_own_QI_root':ownqi,'future_own_QI_proof':None,'no_restart':True,'case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_F5_actual1150_published_full801QI_next_F5_1157_and_F3_987_same_live_native_XMF_both_plan_absence_durable836QI_1356';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_269.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original987_terminal_full836_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F3-original987-full836-own-QI1355.py').read_bytes());pp=O/'actual1150-published801QI-next-original1157-987-same-live-durable987-QI-readiness.json';put(pp,{'schema':'ds02.current307-publishedF5-nextF3-durable-QI.v1','at_utc':now.isoformat(),'actual_F5_original1150_full801_own_QI':ref(qip),'source210_personal_review_pending_case_credit_zero':True,'next_same_original_actual_processes':front,'original_F3_987_outer_request_expected_fields_preserved_as_historical_envelope':{k:q[k] for k in ['expected_frames','expected_particles']},'original_F3_987_actual_loaded_wrapper_expected_fields':{k:w[k] for k in ['expected_frames','expected_particles']},'original_F3_987_outer_fields_not_actual_render_selection_authority':True,'original_F3_987_case_id':q['case_id'],'original_F3_987_physical_case_id':q['physical_case_id'],'original_F3_987_completed_scientific_previsual_review':ref(oldp),'original_F3_987_native_typed_XMF_actual_canonical':canonical,'original_F3_987_actual_plan_namespace_presence_masks':mask,'original_F3_987_canonical_not_inferred_from_other_cases_XMF_plan_matching_digest':True,'durable_original987_only_QI_entrypoint':ref(entry),'commands':[['python3','-B',str(entry),'987','1355']],'do_not_rerun_finished_QI':True,'scientific_payload_IO':False,'no_new_scientific_jobs_or_render_restarts':True,'case_credit':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=269,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active307/336; F5 original1150 M106T095 completed0/pub, full801/194427 ownQI1349 complete and source210 personally reviewing. Next same F5original1157 and F3original987 PV handles live, durable ownF3QI1355 created for actual native/XMF BOTH plan field absences. F3 final48 completion-only builder fresh176 preparing independently while no partial final directory is published.',previous_goal_turn_classification='PROGRESS: preceding turn integrated F3/F2 personalreviews reaching307, fullF6final48 primary catalog delivered. This turn originalF5 1150 completed/published and own801QI1349 finished; current nextF3 original987 samehandle and genuine836/179208 native/typed/XMF rawmask metadata pinned with durable ownQI1355 recovery entrypoint.')
new['actual_progress']['actual1150_full801_own_QI']=ref(qip);new['actual_progress']['actual1150_published_next1157_987_live_durableF3_QI']=ref(pp);new['source_agents']['production_recovery']='fresh176 F3 completion-only final48 builder/readonly validator in source worktree; current42/48 readiness only, preserve4 native orphan runtime unknowns and typed154 runtime unknown';new['next_executable_tasks']=['Adopt source210 originalF5 1150 personal34contacts9keys after sourcefinalcommit and ownQI1349 metadata/actualpub closure; native and XMF physical-plan canonical distinct from typedlegacy/bed SourceDef FILE.','Observe same originalF5 1157 PID584196/start213555954; after completed0/pub run durable ownQI1350 once and reactivate source191 personal34contacts9keys.','Observe same originalF3 987 PID599335/start213680043; after completed0/pub run new durable own836QI1355 once then assign available child personal35contacts9keys with true native+XMF both plan fields absent.','Integrate fresh176 F3 completion-only final48 builder source after commit/read-only code audit; no current partial-final48 publication or new case credit.','Continue remaining29 actual originalrenders/personalreviews and final family deliveries to336; Home500GiB floor and cumulative534.4086GiB cleanup preserved.'];put(np,new)
ip=root(1354)/'full336-current307-actual-final48-delivery-progress-index.json';index=load(ip);row=next(r for r in index['cases'] if r['physical_case_id']==qi['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=ref(qip),current_actual_render_receipt=rq['render_receipt'],current_atomic_publish_receipt=rq['render_publish_receipt'],current_personal_review_source=210,case_credit=0);row['prior_controller_observations_are_historical_not_current']=True;index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[qi['physical_case_id']],current_published1150_next1157_987_live_durable987_QI=ref(pp));assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==307;put(O/'full336-current307-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bind published F5 ownQI and same original F3 durable absent-plan QI','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':269,'accepted':307,'ownQI1349':ref(qip),'frontier':front,'free_GiB':free,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
