from pathlib import Path
import json,hashlib,subprocess,datetime,sys,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_168_f3_assigned_f6_fulltime_floatinginfo_worker_v1');P=R/prefix;idx=load(P/'requests/f6-final48-fulltime-floatinginfo-disabled-request-index.json');inv=load(P/'requests/partfloatinfo-inventory-disabled-request.json');tb=root(1300)/'47-own-full241-native-time-bindings-for-official-rigid-export.json';bindings=load(tb);bm={x['physical_case_id']:x for x in bindings['cases']};proof=root(1301)/'source168-byte-exact-readonly-validator-toy-tests-and-main47-native-binding-adoption.json';commit=load(proof)['source_commit'];assert commit=='c1a39540e7cf00b084404a9cd383b32a8e1f1834'
G=H/'root_stage1_F6_47small_PartFloatInfo_IBI4_metadata_bound_inventory_registered_Root142928_CPU2_1302';G.mkdir(exist_ok=True);assert not (G/'enabled-inventory-runner-request.json').exists();stock=load(root(1220)/'enabled-cleanup-request.json');ar=D/'families/infra/F6-fulltime-rigid-inventory/root-stage1-F6-47small-IBI4-inventory-source168-root1302';assert not ar.exists();spec=copy.deepcopy(inv);spec.update(disabled=False,source_only=False,execution_allowed=True,status='root_enabled_metadata_bound_scientific_input_inventory');spec['output'].update(directory=str(ar/'inventory'),report_path=str(ar/'inventory/inventory-report.json'));spec['worker']['path']=str(R/prefix/'workers/run_partfloatinfo_inventory_fresh168.py');spec['worker']['sha256']=sha(spec['worker']['path']);spec['main_bootstrap_provenance']=ref(proof);spec['own_complete_native_bindings']=ref(tb);sp=G/'enabled-partfloatinfo-inventory-spec.json';put(sp,spec)
controller=G/'registered-inventory-controller.py';controller.write_text("from pathlib import Path\nimport json,runpy\nO=Path(__file__).parent\nc=json.loads((O/'controller-config.json').read_text())\nr=runpy.run_path(c['fair_dispatch'])['dispatch'](c['request'],serial_conversion=True)\nq=json.loads(Path(c['request']).read_text())\nrp=Path(q['attempt_root'])/'execution-receipt.json'\na=json.loads(rp.read_text()) if rp.exists() else {}\nv={'launcher_returncode':r.returncode,'status':a.get('status'),'returncode':a.get('returncode'),'actual_receipt':str(rp),'stdout_tail':r.stdout[-2500:],'stderr_tail':r.stderr[-2500:],'case_credit':0}\n(O/'controller-result.json').write_text(json.dumps(v,indent=2)+'\\n')\nprint(json.dumps(v),flush=True)\nraise SystemExit(r.returncode)\n")
fair=root(928)/'fair_CPU_dispatch.py';guardpaths=[Path(stock['root_actual_launch_source']),root(142)/'root_home_floor_inventory_policy.py',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',next(H.glob('root*_064'))/'resource-window-approval.json',fair];guardshas={str(p):stock['input_sha256'][str(p)] for p in guardpaths};assert all(sha(p)==s for p,s in guardshas.items());inputs={**guardshas,str(sp):sha(sp),str(controller):sha(controller),str(tb):sha(tb),str(proof):sha(proof),spec['worker']['path']:spec['worker']['sha256']}
for x in bm.values():inputs[x['native_receipt']['path']]=x['native_receipt']['sha256']
q={k:copy.deepcopy(stock[k]) for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']};q.update(schema='ds02.runner-request.v2',family_id='infra',case_id='F6-fulltime-rigid-inventory',attempt_id=ar.name,attempt_root=str(ar),kind='cpu',cpu_task_kind='audit',launch_owner='root',cpu_threads=2,estimated_storage_bytes=67108864,max_wall_seconds=600,cwd=str(L),worktree_root=str(R),command=[str(L/'.venv/bin/python'),spec['worker']['path'],'--request',str(sp),'--report','{attempt_root}/inventory/inventory-report.json'],input_files=sorted(inputs),input_sha256=inputs,input_sha256_required=True,disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,physical_condition_sha256=sha(sp),physical_condition_hash_semantics='Metadata-bound scientific input inventory specification, no physical case credit or numerical certification',case_credit=0);qp=G/'enabled-inventory-runner-request.json';put(qp,q);put(G/'controller-config.json',{'fair_dispatch':str(fair),'request':str(qp)});put(G/'registered-input-provenance.json',{'source_worker_adoption':ref(proof),'enabled_inventory_spec':ref(sp),'own_complete_native_bindings':ref(tb),'registered_request':ref(qp),'scientific_input_sha_before_first_registered_inventory':None,'scientific_files_metadata_bound_not_pretended_strict_prehashed':True,'explicit_files':47,'total_expected_IBI4_bytes':8477672,'main_scientific_payload_IO':False,'case_credit':0});put(G/'metadata-preparation-recovery.json',{'original_preparation_failure':'Approval guard path root64 lookup did not match zero-padded Root064; no scientific task launched. Source1301 adoption already completed and preserved; unconsumed inventory spec/controller resumed with exact Root064 guard.','source_adoption_unchanged':ref(proof),'main_scientific_payload_IO':False});(G/'registration-source.py').write_bytes(Path(__file__).read_bytes());rel=str(G.relative_to(R));subprocess.run(['git','add','--',rel],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register CPU2 metadata-bound47 small rigid IBI4 SHA inventory','--',rel],cwd=R,check=True);print({'source_commit':commit,'inventory_controller':str(controller),'registered_request':ref(qp),'input_files':len(inputs),'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
