#!/usr/bin/env python3
"""Build fresh102 disabled runtime-shaped requests from validated bindings."""
from __future__ import annotations
import hashlib, json
from pathlib import Path

PKG=Path(__file__).resolve().parents[1]
F5ROOT=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics')
LAB=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics/lagrangian-fluid-lab')
CASE='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1'
DATA=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02/families/F5')
ROOT142=LAB/'handoff_20261003/root_stage1_home_floor_inventory_dispatch_142/root_home_floor_inventory_policy.py'
ROOT230_DIR=LAB/'campaigns/ds-data-02/handoff_20261003/root_stage1_native_home_floor_eight_solver_dispatch_230'
ROOT230_LAUNCH=ROOT230_DIR/'launch.py'; ROOT230_POLICY=ROOT230_DIR/'root_native_home_floor_inventory_policy.py'
RES=LAB/'handoff_20261003/root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json'
RUNTIME=LAB/'scripts/ds_data02_runtime_v2.py'; STRICT=LAB/'scripts/ds_data02_strict_dispatch_v1.py'
GENW=LAB/'campaigns/ds-data-02/handoff_20261003/root_native_source_preflight_tools_003/gencase.py'
MOTIONW=F5ROOT/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_099_stage1_f5_c082s1_bounded_excitation_recovery_v1/workers/scale_compact_motion.py'
BASE_MOTION=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02/families/F5/F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050/root-compact-equilibrium-runup_coarse-clip-direction-fix-gencase-050/prepared/assets/f5_compact_packet_motion.dat')
GENBIN=Path('/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/vendor/official/DualSPHysics_v5.4/bin/linux/GenCase_linux64')
SOLVER=Path('/home/jade/Projects/DualSPHysics/lagrangian-fluid-lab/vendor/official/DualSPHysics_v5.4/bin/linux/DualSPHysics5.4_linux64')
GENBIN_SHA='a1b6414e0f716669363d1a80a05e133085c04995e15716e3c1f0406e0d023226'; SOLVER_SHA='0415b10e5e32af8b8b7ad2a703f9043dca67dfcf7626eb98f1c05a50856fde29'
BASE_MOTION_SHA='51e197f0831915a73534c619704658b06812c9d52c38c470ab4cbb8d59f5614a'; RES_SHA='2a35e26e36920d8ca40001fd7f28416f27bcf371b8b882eca37868f4a15152b8'
ROOT142_SHA='2649eedbcf4816f8d2fa7b2182828ea8b3ce107ef47f25c56780d29c5138def5'; ROOT230_LAUNCH_SHA='7f703fb94e17c2e2800873f4fcc021f9cd5f8201076afd8e10e3bc6a2d03396e'; ROOT230_POLICY_SHA='c9103e306f87bb5af871c5de28d9939aa05f0c95c72e1630778f4bcf50e91ab5'
SCIENCE={'.dat','.bi4','.h5','.hdf5','.csv','.vtk','.vtu','.xmf','.xdmf'}
RESOURCE={'approval_sha256':RES_SHA,'cpu_core_hours':3840,'gpu_hours':512,'qualification_attempts':1024,'production_attempts':720,'home_min_free_bytes':536870912000,'deadline_utc':'2026-10-14T07:23:48+00:00','launch_owner':'root','profile':'root_home_floor_no_legacy_dataset_walk_v1'}
ROOT230_META={'entrypoint':str(ROOT230_DIR/'launch.py'),'entrypoint_sha256':ROOT230_LAUNCH_SHA,'policy_source':str(ROOT230_DIR/'root_native_home_floor_inventory_policy.py'),'policy_source_sha256':ROOT230_POLICY_SHA,'profile':'root_home_floor_no_legacy_dataset_walk_native_v1','launch_owner':'root','solver_kinds_only':['qualification','production']}

def load(p): return json.loads(Path(p).read_text())
def dump(p,x): Path(p).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def sha(p):
 p=Path(p)
 if p.suffix.lower() in SCIENCE: raise RuntimeError('science payload hash forbidden: '+str(p))
 h=hashlib.sha256();
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''): h.update(b)
 return h.hexdigest()
def input_files(cid,binding=None,*,gen=False,solver=False,motion=False,extra=()):
 ps=[RUNTIME,STRICT,ROOT142,RES,PKG/'scripts/build_explicit_physical_binding.py',PKG/'scripts/build_disabled_stage_requests.py',PKG/'scripts/preflight_fresh102.py',PKG/'inputs'/f'{cid}-Definition.xml',PKG/'inputs'/f'{cid}-owner.json',PKG/'bindings'/f'{cid}-physical-binding.json']
 if binding: ps.append(binding)
 if gen: ps += [GENW,GENBIN]
 if solver: ps += [ROOT230_DIR/'launch.py',ROOT230_DIR/'root_native_home_floor_inventory_policy.py',SOLVER]
 if motion: ps += [MOTIONW,BASE_MOTION]
 ps += list(extra)
 ss=[str(x) for x in ps]; hs={}
 for s,p in zip(ss,ps):
  if s.startswith('<root-bind:') or not p.exists() or p.suffix.lower() in SCIENCE: hs[s]=BASE_MOTION_SHA if p==BASE_MOTION else None
  else: hs[s]=sha(p)
 return ss,hs
def common(cid,o,ph,attempt,kind,task,depends=None,storage=2**31,maxwall=3600):
 d={'schema':'ds02.runner-request.v2','status':'disabled_until_root_review_and_actual_upstream_receipts','kind':kind,'cpu_task_kind':task,'disabled':True,'launch':False,'launch_allowed':False,'execution_allowed':False,'solver_allowed':False,'conversion_allowed':False,'arrays_allowed':False,'array_edit_allowed':False,'shared_registry_write_allowed':False,'source_only':True,'root_review_required':True,'launch_owner':'root','family_id':'F5','candidate_id':o['candidate_id'],'case_id':CASE,'physical_case_id':o['physical_case_id'],'condition_id':o['condition_id'],'physical_condition_sha256':ph,'canonical_physical_binding_sha256':ph,'source_plan_physical_condition_sha256':o['source_plan_physical_condition_sha256'],'attempt_id':attempt,'cwd':str(LAB),'cpu_threads':2,'max_wall_seconds':maxwall,'estimated_storage_bytes':storage,'independent_case_count_increment':0,'full16_authorized':False,'full801_authorized':False,'q_n_granted':False,'production_approval':'none','resource_window':RESOURCE,'root_dataset_inventory_profile':'root_home_floor_no_legacy_dataset_walk_v1','root_inventory_policy_source_sha256':ROOT142_SHA,'root230_dispatch_provenance':ROOT230_META,'root230_gpu_protection_required_for_native_solver':True,'input_sha256_provenance':'static source/metadata hashes only; base DAT digest is producer-declared and copied without source-agent DAT read; future products remain null','old_attempt_modification_forbidden':True,'worktree_root':str(F5ROOT),'future_output_hashes':{'receipt_sha256':None,'prepared_input_report_sha256':None,'generated_xml_sha256':None,'generated_bi4_sha256':None,'scaled_motion_sha256':None,'initial_qa_report_sha256':None,'short_native_receipt_sha256':None,'typed_h5_sha256':None,'xmf_manifest_sha256':None,'bed_audit_report_sha256':None}}
 if depends: d['depends_on_attempt']=depends
 return d
def build(cid):
 o=load(PKG/'inputs'/f'{cid}-owner.json'); ph=load(PKG/'metadata'/f'{cid}-explicit-physical-binding-report.json')['canonical_physical_binding_sha256']; bpath=PKG/'bindings'/f'{cid}-physical-binding.json'; bsha=sha(bpath); dpath=PKG/'inputs'/f'{cid}-Definition.xml'; dsha=sha(dpath); opath=PKG/'inputs'/f'{cid}-owner.json'; osha=sha(opath); scale=o['motion_transform']['scale']; short='080' if cid=='A080' else '120'; motion=f'root-stage1-f5-c082s1-A{short}-motion-transform-102'; gen=f'root-stage1-f5-c082s1-A{short}-genuine-gencase-102'; qa=f'root-stage1-f5-c082s1-A{short}-initial-qa-mk50-102'; sn=f'root-stage1-f5-c082s1-A{short}-short-native-qualification-102'; bed=f'root-stage1-f5-c082s1-A{short}-short-bed-audit-102'; asset=f'assets/f5_c082s1_motion_s{short}.dat'
 gbpath=PKG/'bindings'/f'{cid}-gencase-binding.json'
 gb={'schema':'ds02.f5.c082s1.explicit-binding-gencase.fresh102.v1','case_id':CASE,'candidate_id':o['candidate_id'],'condition_id':o['condition_id'],'physical_case_id':o['physical_case_id'],'physical_condition_sha256':ph,'canonical_physical_condition_sha256':ph,'source_plan_physical_condition_sha256':o['source_plan_physical_condition_sha256'],'definition':str(dpath),'definition_sha256':dsha,'owner_metadata':str(opath),'owner_metadata_sha256':osha,'physical_binding':str(bpath),'physical_binding_sha256':bsha,'gencase':str(GENBIN),'gencase_sha256':GENBIN_SHA,'threads':2,'dp_m':0.02,'source_mkbound':40,'native_bed_mk':50,'solver_dimension_required':3,'expected_fluid':None,'actual_counts':None,'predictions':None,'assets':[{'source':'<root-bind:scaled_motion_asset>','relative_name':asset,'sha256':None,'producer_attempt_id':motion,'producer_report':'<root-bind:motion_transform_receipt>','scale':scale,'future_hash':None}],'base_motion':{'path':str(BASE_MOTION),'sha256':BASE_MOTION_SHA,'sha256_provenance':'registered producer metadata only; source prep did not read/hash DAT'},'future_outputs':{'receipt_sha256':None,'prepared_input_report_sha256':None,'generated_xml_sha256':None,'generated_bi4_sha256':None},'source_only':True,'solver_allowed':False,'conversion_allowed':False,'independent_case_count_increment':0}
 dump(gbpath,gb); gbsha=sha(gbpath)
 ps,hs=input_files(cid,motion=True,extra=('<root-bind:scaled_motion_output>','<root-bind:motion_transform_receipt>'))
 r=common(cid,o,ph,motion,'cpu','audit',storage=2**26,maxwall=600); r.update({'candidate_source_definition':str(dpath),'candidate_source_definition_sha256':dsha,'source_owner':str(opath),'source_owner_sha256':osha,'scale':scale,'base_motion_path':str(BASE_MOTION),'base_motion_sha256':BASE_MOTION_SHA,'base_motion_sha256_provenance':'registered C082S1 GenCase producer metadata; source agent did not read/hash DAT','motion_output_path':'<root-bind:scaled_motion_output>','motion_output_sha256':None,'motion_transform_receipt':'<root-bind:motion_transform_receipt>','command':[str(LAB/'.venv/bin/python'),str(MOTIONW),'--base-motion',str(BASE_MOTION),'--output','{attempt_root}/prepared/assets/'+asset,'--receipt','{attempt_root}/motion-transform-report.json','--scale',str(scale)],'input_files':ps,'input_sha256':hs,'worker_kind':'fresh099 scale_compact_motion.py; Root must bind fresh output before GenCase','future_scaled_control':{'path':None,'sha256':None,'receipt_sha256':None}}); dump(PKG/'requests'/f'{cid}-motion-transform-request.json',r)
 ps,hs=input_files(cid,gbpath,gen=True,motion=True,extra=('<root-bind:scaled_motion_asset>','<root-bind:motion_transform_receipt>'))
 r=common(cid,o,ph,gen,'cpu','gencase',storage=5*2**30,maxwall=1800); r.update({'binding':str(gbpath),'binding_sha256':gbsha,'command':[str(LAB/'.venv/bin/python'),str(GENW),'--binding',str(gbpath),'--output-dir','{attempt_root}/prepared'],'input_files':ps,'input_sha256':hs,'genuine_gencase':True,'genuine_gencase_required':True,'definition':str(dpath),'definition_sha256':dsha,'physical_binding_path':str(bpath),'physical_binding_sha256':bsha,'motion_transform_attempt':motion,'motion_transform_receipt':'<root-bind:motion_transform_receipt>','motion_asset_path':'<root-bind:scaled_motion_asset>','motion_asset_sha256':None,'generated_xml':None,'generated_bi4':None,'actual_counts':None,'expected_fluid':None,'solver_dimension_required':3,'generated_xml_data2d_required':'false','native_bed_mk':50,'source_mkbound':40,'output_root':f'<root-bind:{cid}_gencase_output_root>','future_producer_fields':{'receipt_output_root':None,'actual_total_particles':None,'generated_xml_particle_counts':None,'solver_dimension_from_gencase':None,'prepared_input_report_sha256':None,'generated_xml_sha256':None,'generated_bi4_sha256':None}}); dump(PKG/'requests'/f'{cid}-gencase-request.json',r)
 qabpath=PKG/'bindings'/f'{cid}-initial-qa-mk50-binding.json'; qab={'schema':'ds02.f5.c082s1.initial-qa-mk50-binding.fresh102.v1','candidate_id':o['candidate_id'],'case_id':CASE,'condition_id':o['condition_id'],'physical_case_id':o['physical_case_id'],'physical_binding_path':str(bpath),'physical_binding_sha256':bsha,'physical_condition_sha256':ph,'gencase_attempt_id':gen,'gencase_receipt':'<root-bind:gencase_receipt>','prepared_input_report':'<root-bind:prepared_input_report>','generated_xml':'<root-bind:generated_xml>','generated_bi4':'<root-bind:generated_bi4>','actual_counts':None,'solver_dimension':None,'source_mkbound':40,'native_bed_mk':50,'placement_checks':{'uid_unique_and_consecutive':True,'finite_rows':True,'integral_zone_type_mk':True,'positive_mass_density':True,'zero_initial_velocity':True,'fixed_moving_floating_fluid_no_overlap':True,'fluid_inside_source_box':True,'fluid_above_exact_continuous_bed':True,'required_transverse_y_levels':15,'central_mk50_support_positive_in_each_x_segment':True,'counts_copied_from_actual_producer':True,'dimension_copied_from_actual_generated_xml':True},'numerical_precision':{'exact_dp_lattice_threshold':1e-6,'diagnostic_only':True,'no_threshold_relaxation':True,'cannot_be_labelled_pass':True,'historical_failure_preserved':True},'bed_profile':{'nodes_xz_m':load(bpath)['parameters']['bed_profile_upper_xz_m'],'x_bounds_m':[-0.2,4.8],'y_bounds_m':[-0.22,0.22]},'future_report_sha256':None,'source_agent_did_not_read_arrays':True}; dump(qabpath,qab); qabsha=sha(qabpath)
 ps,hs=input_files(cid,qabpath,extra=('<root-bind:initial_qa_worker>','<root-bind:official_particle_csv>','<root-bind:gencase_receipt>','<root-bind:prepared_input_report>','<root-bind:generated_xml>','<root-bind:generated_bi4>'))
 r=common(cid,o,ph,qa,'cpu','audit',depends=gen,storage=2*2**30,maxwall=3600); r.update({'command':[str(LAB/'.venv/bin/python'),'<root-bind:initial_qa_worker>','--binding',str(qabpath),'--output-dir','{attempt_root}/initial-qa'],'binding':str(qabpath),'binding_sha256':qabsha,'gencase_attempt_id':gen,'gencase_receipt':'<root-bind:gencase_receipt>','prepared_input_report':'<root-bind:prepared_input_report>','generated_xml':'<root-bind:generated_xml>','generated_bi4':'<root-bind:generated_bi4>','official_particle_csv':'<root-bind:official_particle_csv>','actual_counts':None,'expected_particles':None,'expected_fluid_particles':None,'expected_fixed_particles':None,'expected_moving_particles':None,'expected_floating_particles':None,'expected_dimension':3,'native_bed_mk':50,'source_mkbound':40,'input_files':ps,'input_sha256':hs,'worker_kind':'Root-owned producer-bound placement/Mk50 audit; worker must not infer candidate counts','placement_gate':'basic placement/Mk50 only; numerical precision remains diagnostic'}); dump(PKG/'requests'/f'{cid}-initial-qa-mk50-request.json',r)
 ps,hs=input_files(cid,qabpath,solver=True,extra=('<root-bind:gencase_prepared_root>','<root-bind:gencase_prefix>','<root-bind:gencase_receipt>','<root-bind:generated_xml>','<root-bind:generated_bi4>','<root-bind:actual_initial_qa_report>','<root-bind:scaled_motion_asset>'))
 r=common(cid,o,ph,sn,'qualification','solver',depends=qa,storage=10*2**30,maxwall=1800); r.update({'cwd':'<root-bind:gencase_prepared_root>','command':[str(SOLVER),'<root-bind:gencase_prefix>','{attempt_root}/solver_output','-tmax:1.0','-tout:0.02'],'input_files':ps,'input_sha256':hs,'estimated_peak_gpu_mib':4096,'expected_frames':51,'expected_dimension':3,'expected_particle_axis':None,'expected_particles':None,'expected_fixed_particles':None,'expected_moving_particles':None,'expected_floating_particles':None,'expected_fluid_particles':None,'event_window_s':[0.0,1.0],'save_interval_s':0.02,'gencase_attempt_id':gen,'gencase_receipt':'<root-bind:gencase_receipt>','generated_xml':'<root-bind:generated_xml>','generated_xml_sha256':None,'generated_bi4':'<root-bind:generated_bi4>','generated_bi4_sha256':None,'motion_asset_path':'<root-bind:scaled_motion_asset>','motion_asset_sha256':None,'root_dataset_inventory_profile':'root_home_floor_no_legacy_dataset_walk_native_v1','root_inventory_policy_source_sha256':ROOT230_POLICY_SHA,'root_actual_launch_source':str(ROOT230_LAUNCH),'root_actual_launch_source_sha256':ROOT230_LAUNCH_SHA,'root_gpu_selection_profile':'root_live_all_idle_uuid_leased_eight_solver_v2','root_solver_concurrency_cap':8,'root_effective_reservation_function_sha256':'46e62ea197862a833797556d09350126b3632b2e3b1d496d08816ee42f7abecf','root230_entrypoint':str(ROOT230_DIR/'launch.py'),'root230_entrypoint_sha256':ROOT230_LAUNCH_SHA,'root230_policy_source':str(ROOT230_DIR/'root_native_home_floor_inventory_policy.py'),'root230_policy_source_sha256':ROOT230_POLICY_SHA,'cwd_semantics':'Actual GenCase prepared root is required so the relative scaled motion asset resolves; root must bind this before enablement.','actual_initial_qa_report':'<root-bind:actual_initial_qa_report>','short_right_censored':True}); dump(PKG/'requests'/f'{cid}-short-native-qualification-request.json',r)
 babpath=PKG/'bindings'/f'{cid}-short-dynamic-bed-audit-binding.json'; bab={'schema':'ds02.f5.c082s1.short-dynamic-bed-audit-binding.fresh102.v1','candidate_id':o['candidate_id'],'case_id':CASE,'condition_id':o['condition_id'],'physical_case_id':o['physical_case_id'],'physical_binding_path':str(bpath),'physical_binding_sha256':bsha,'physical_condition_sha256':ph,'source_plan_physical_condition_sha256':o['source_plan_physical_condition_sha256'],'short_native_attempt_id':sn,'expected_frames':51,'time_window_s':[0.0,1.0],'nominal_save_interval_s':0.02,'actual_time_axis_must_be_read_from_producer':True,'actual_counts':None,'expected_particle_axis':None,'source_marker_mapping':{'source_mkbound':40,'native_bed_mk':50,'fluid_type_code':3},'profile':{'nodes_xz_m':load(bpath)['parameters']['bed_profile_upper_xz_m'],'x_bounds_m':[-0.2,4.8],'y_bounds_m':[-0.22,0.22]},'penetration_bins_m':[0.02,0.04],'checks':{'all_51_saved_states':True,'all_initial_fluid_uids_full_denominator':True,'missing_uid_count_per_frame':True,'nonfinite_count_per_frame':True,'inside_exact_profile_and_y_footprint_only':True,'one_dp_count_fraction_depth_per_frame':True,'two_dp_count_fraction_depth_per_frame':True,'no_threshold_relaxation':True,'dynamic_acceptance_requires_root_visual_review':True},'future_inputs':{'typed_h5':None,'xmf':None,'typed_receipt_sha256':None,'xmf_manifest_sha256':None,'audit_report_sha256':None},'full801_authorized':False,'case_credit':False,'source_agent_did_not_read_science_payloads':True}; dump(babpath,bab); babsha=sha(babpath)
 ps,hs=input_files(cid,babpath,extra=('<root-bind:bed_audit_worker>','<root-bind:typed_h5>','<root-bind:xmf>','<root-bind:typed_receipt>','<root-bind:xmf_manifest>'))
 r=common(cid,o,ph,bed,'cpu','audit',depends=sn,storage=3*2**30,maxwall=3600); r.update({'command':[str(LAB/'.venv/bin/python'),'<root-bind:bed_audit_worker>','--binding',str(babpath),'--trajectory-h5','<root-bind:typed_h5>','--xdmf','<root-bind:xmf>','--output-dir','{attempt_root}/audit-output'],'binding':str(babpath),'binding_sha256':babsha,'expected_frames':51,'expected_dimension':3,'expected_particle_axis':None,'expected_particles':None,'expected_fixed_particles':None,'expected_moving_particles':None,'expected_floating_particles':None,'expected_fluid_particles':None,'native_bed_marker_mk':50,'source_bed_marker_mkbound':40,'bed_y_bounds_m':[-0.22,0.22],'bed_x_bounds_m':[-0.2,4.8],'penetration_bins_m':[0.02,0.04],'diagnostic_only':True,'dynamic_acceptance':'not granted by worker; Root reviews metrics and focused visual output','typed_receipt':'<root-bind:typed_receipt>','xmf_manifest':'<root-bind:xmf_manifest>','future_output_hashes':{'typed_h5_sha256':None,'xmf_manifest_sha256':None,'audit_report_sha256':None},'input_files':ps,'input_sha256':hs,'worker_kind':'Root-owned full-fluid UID-preserving dynamic bed audit'}); dump(PKG/'requests'/f'{cid}-short-dynamic-bed-audit-request.json',r)
 return {'candidate_id':o['candidate_id'],'physical_binding_sha256':ph,'attempts':{'motion_transform':motion,'gencase':gen,'initial_qa_mk50':qa,'short_native':sn,'short_dynamic_bed_audit':bed}}
summary=[build('A080'),build('A120')]
dump(PKG/'metadata/disabled-stage-contract.json',{'schema':'ds02.f5.c082s1.disabled-motion-to-bed-stage-contract.fresh102.v1','source_only':True,'candidates':summary,'stage_order':['motion_transform','genuine_gencase','initial_qa_and_mk50_coverage','short_native_1s_51frames','short_dynamic_bed_audit'],'future_candidate_counts_and_hashes_null':True,'counts_policy':'A080/A120 counts are unknown until their own producer; baseline 194427/158559/4210/0/31658 is provenance only and is never an expected candidate count.','semantic_gencase_contract':{'dimension':3,'generated_xml_data2d':'false','total_particles':'actual producer field, null before GenCase','fluid_particles':'actual producer field, null before GenCase','fixed_particles':'actual producer field, null before GenCase','moving_particles':'actual producer field, null before GenCase','floating_particles':'actual producer field, null before GenCase'},'root230_gpu_protection':ROOT230_META,'full801_enabled':False,'case_credit':False})
print(json.dumps({'status':'built','package':str(PKG),'candidates':[x['candidate_id'] for x in summary]},sort_keys=True))
