from pathlib import Path
import json,hashlib,datetime,subprocess,runpy,xml.etree.ElementTree as ET,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.jsonl','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_168_f5_m085_t090_actual820_832_bed_evidence_disabled_v1';commit='01c23aa6fcc4eed3eead412723bccbbe6220b085';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==7;adopted=[]
for name in names:
 assert Path(name).suffix in {'.json','.py','.md'};raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_F5_M085T090_delegated137_existing832_full801_bed168_independent_visual_acceptance_994';O.mkdir(exist_ok=False)
validator=P/'scripts/validate_fresh168.py';report=P/'metadata/fresh168-validator-report.json';original_report=ref(report);v=runpy.run_path(str(validator));original_write=Path.write_text;writes=[]
def redirect_report(self,data,*args,**kwargs):
 assert self==report,'Validator attempted unexpected mutation';writes.append(str(self));return original_write(O/'independent-source168-validator-output.json',data,*args,**kwargs)
try:
 Path.write_text=redirect_report;rc=v['main']()
finally:Path.write_text=original_write
assert rc==0 and writes==[str(report)] and ref(report)==original_report
put(O/'actual-source168-validator-preserved-report.json',{'status':'pass','validator':ref(validator),'unchanged_validator_main_all_original_asserts_executed':True,'only_default_report_write_redirected_to_independent_output':ref(O/'independent-source168-validator-output.json'),'original_consumed_source_report_preserved':original_report,'scientific_payload_IO':False})
e=load(P/'metadata/m085-t090-actual-bed-evidence.json');prod=e['actual_producers'];bedp=Path(prod['bed_audit']['report']);bedr=Path(prod['bed_audit']['receipt']);bed=load(bedp);br=load(bedr);t=load(prod['typed']['report']);x=load(prod['xmf']['manifest']);bp=load(root(989)/'adoption-and-two-case-independent-review.json')['pending_F5_no_credit'][0];assert bp['physical_case_id']==e['physical_case_id'];ch=bp['actual_completed_metadata_evidence'];visp=Path(bp['source_visual_review']['path']);assert sha(visp)==bp['source_visual_review']['sha256'];vis=next(z for z in load(visp)['cases'] if z['physical_case_id']==e['physical_case_id']);assert vis['status']=='visual-approved-by-delegated-agent' and vis['agent_personally_viewed_all_contact_sheets'] and vis['agent_personally_viewed_all_key_frames']
visualpkg=visp.parents[1]
for z in load(visualpkg/'metadata/evidence-files.json')['files']:assert sha(z['path'])==z['sha256'] and Path(z['path']).stat().st_size==z['bytes']
for role,item in ch.items():
 rp=item.get('receipt',item.get('execution_receipt'))
 if rp:a=load(rp);assert (a['status'],a['returncode'])==('completed',0)
assert ch['typed']['conversion_report']==prod['typed']['report'] and ch['typed']['execution_receipt']==prod['typed']['receipt'] and ch['xmf']['manifest']==prod['xmf']['manifest']
for role,p in prod.items():
 if p.get('receipt'):assert sha(p['receipt'])==p['receipt_sha256'] and (load(p['receipt'])['status'],load(p['receipt'])['returncode'])==('completed',0)
 for k in ['report','manifest','xdmf','prepared_report']:
  if p.get(k) and p.get(k+'_sha256'):assert sha(p[k])==p[k+'_sha256']
for z in bed['bound_actual_inputs']['records']:assert sha(z['path'])==z['sha256']
sc=e['physical_scope'];canonical=sc['canonical_physical_condition_sha256'];actual=sc['source_h5_legacy_scope_sha256'];plan=sc['source_plan_physical_condition_sha256'];assert len({canonical,actual,plan})==3 and bed['physical_condition_sha256']==canonical==x['physical_condition_sha256'] and bed['source_h5_physical_condition_sha256']==actual==t['hash_scopes']['physical_condition_sha256'] and bed['source_plan_physical_condition_sha256']==plan
assert br['request']['physical_case_id']==bed['bound_actual_inputs']['physical_case_id']==e['physical_case_id'] and bed['source']['trajectory_h5_sha256']==prod['typed']['producer_attested_h5_sha256']==t['output_sha256']==x['source_h5_sha256']==bp['source_h5_sha256_producer_attested']
h=t['output_hdf5'];assert bed['source']['trajectory_h5']==h and br['input_hashes_at_launch'][h]==br['input_hashes_after_run'][h]==br['request']['input_sha256'][h]==t['output_sha256']
assert bed['source']['xdmf']==ch['xmf']['case_xmf'] and bed['source']['xdmf_sha256']==sha(ch['xmf']['case_xmf']) and bed['scan']['frames_scanned']==801 and bed['scan']['particle_axis_count']==194427 and bed['scan']['initial_fluid_uid_count']==31658
assert not bed['source_arrays_modified'] and not bed['source_arrays_dropped_or_masked'] and bed['q_n_status']=='not_granted' and bed['repair_success']=='unknown_until_full_event_bed_audit_review'
fs=t['lifecycle']['frame_summary'];rs=load(ch['render']['report']);grids=ET.parse(ch['xmf']['case_xmf']).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];bf=bed['frame_reports'];assert len(fs)==len(bf)==len(grids)==len(rs['frame_diagnostics'])==801 and times==[z['time'] for z in fs]==[f['time_s'] for f in bf]==[f['actual_time_s'] for f in rs['frame_diagnostics']]==[float(g.find('Time').get('Value')) for g in grids]
assert times[0]==0 and times[-1]>=16 and all(a<b for a,b in zip(times,times[1:])) and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames'])
maxima={'one_dp':0,'two_dp':0,'missing_initial_fluid':0,'unexpected_uid':0,'nonfinite_position':0,'nonfinite_mass':0,'all_missing':0}
for i,(f,g,z,d) in enumerate(zip(bf,grids,fs,rs['frame_diagnostics'])):
 assert f['frame']==z['frame']==d['frame']==i and f['particle_axis_count']==194427 and f['initial_fluid_uid_count']==31658 and f['current_valid_type3_fluid_count']==31658
 vals={'one_dp':f['penetration']['one_dp']['count'],'two_dp':f['penetration']['two_dp']['count'],'missing_initial_fluid':f['uid_tracking']['missing_initial_uid']['count'],'unexpected_uid':f['uid_tracking']['unexpected_current_uid']['count'],'nonfinite_position':f['nonfinite_position_current_fluid_count'],'nonfinite_mass':f['nonfinite_mass_current_fluid_count'],'all_missing':z['missing_particles']}
 for k,value in vals.items():maxima[k]=max(maxima[k],value)
 assert z['active_particles']==d['active']==194427 and not any(vals.values()) and not f['unexplained_state']['nonfinite_or_lost_initial_uid_present'] and d['identity_axis_preserved'] and d['finite_positions_active'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in d['finite_fields'].values())
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';vv=next(v for v in g.findall('Attribute') if v.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='194427 3'
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_137.json');old=[load(p) for p in cp['accepted_decisions']];assert len(old)==210 and e['physical_case_id'] not in {z.get('physical_case_id',z['case_id']) for z in old} and canonical not in {z['physical_condition_sha256'] for z in old}
proof=O/'actual832-all801-bed-and137-visual-independent-closure.json';put(proof,{'physical_case_id':e['physical_case_id'],'actual_bed_receipt':ref(bedr),'actual_bed_report':ref(bedp),'actual_H5_digest_before_after_runner_matches_typed_producer':True,'all801_actual_times_exact_bed_typed_XMF_XML_render':True,'all31658_initial_fluid_UIDs_retained_finite_every_saved_frame':True,'diagnostic_maxima':maxima,'original_bed_pending_root_review_and_precision_flags_preserved':True,'source168_adopted_files':adopted,'actual_validator':ref(O/'actual-source168-validator-preserved-report.json'),'source_delegated_personal_visual':ref(visp),'no_duplicate_scientific_job_started':True,'main_scientific_payload_IO':False,'q_n_granted':False,'q_e_granted':False})
ch['bed_audit']={'execution_receipt':str(bedr),'report':str(bedp)};decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':e['case_id'],'physical_case_id':e['physical_case_id'],'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':actual,'source_plan_physical_condition_sha256':plan,'producer_scope_schema_verified_from_actual_report':'legacy-owner-scope.v0','source_visual_review':ref(visp),'source_visual_review_commit':'9762deedf606832b8d84b747a191b836eb33f66d','source_bed_evidence_commit':commit,'actual_completed_metadata_evidence':ch,'full_native_frames':801,'particles':194427,'actual_physical_window_s':[times[0],times[-1]],'lifecycle':bp['lifecycle'],'family_specific_proof':ref(proof),'stage1_QI_full_native_identity_and_state_verified':True,'all_actual_times_exact_typed_XMF_XML_render_bed':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':vis['observations'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};dp=O/(e['physical_case_id']+'-delegated-visual-decision.json');put(dp,decision);cp['accepted_per_family']['F5']+=1
cp.update(checkpoint=138,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_137.json'),predecessor_sha256=sha(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_137.json'),stage1_visual_accepted_complete_independent_cases=211,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=shutil.disk_usage('/home/jade').free/1024**3,previous_goal_turn_classification='Progress: three true F5 actual983 full801 typed0 independently closed and original129 XMF993 registered/launched; source168 finds reusable exact full801 bed832, now allframes UID/bed/finite/native source and delegated137 personal visual independently closed to211 without any new scientific rerun.')
assert sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==211;cp['actual_progress']['F5_M085T090_actual832_bed0_delegated137_visual_integrated211']=ref(proof);cp['source_agents']['f5_bed_recovery']='fresh167remaining5ready, fresh168exactexisting832bed reused toaccept211; fresh169full48 authoritative Mother+NEXT34 census and downstream993 actualXMF0 bed bindings active';cp['source_agents']['f6_endpoint_initial_qa']='fresh1383case personal visual ready pending main QI integration; fresh139 remainingactual951visual plus F2gap21metadata census active';cp['next_executable_tasks']=['Integrate fresh138 F4two full1201 and F6DYXZ full241 genuine angular visual evidence independently to214 only upon actual fullframe QI/uniqueness closure.','Adopt fresh167remaining5 actualF5full801 native-ready correcttool typed requests, exclude98312/98812/accepted211.','Close actual990F3 and993F5 fullnative XMF0; register original116023 renders and actualF5bed138 audits as appropriate.','Adopt fresh126 newF3true typed0 downstream and full48 census; include actual991decoderCLIrepair1truefirsttyped0.','Complete F2 remaining21 native/typed/XMF/render metadata census using realreceipt observations; no duplicate native simulations when exact reusable completed assets exist.'];put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_138.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(z['path']).relative_to(R)) for z in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_138.json').relative_to(R)),str((root(993)/'controller-launch-process.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F5 full801 M085T090 visual using existing exact full-event bed audit','--',*paths],cwd=R,check=True);print({'accepted':211,'counts':cp['accepted_per_family'],'diagnostic_maxima':maxima,'Home_free_GiB':cp['home_free_gib'],'no_new_scientific_rerun':True,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
