from pathlib import Path
import json,hashlib,datetime,copy,collections,subprocess,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
rows=[]
for original,out,pid,start in [(1150,1349,580550,'213516990'),(1157,1350,584196,'213555954')]:
 F=root(original);old=load(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json');w=load(F/'enabled-render-wrapper.json');q=load(F/'enabled-full801-render-request.json');refs={k:v for k,v in old.items() if isinstance(v,dict) and 'path' in v and 'sha256' in v}
 for e in refs.values():assert ref(e['path'])['sha256']==e['sha256']
 t=load(old['actual_typed_report']['path']);x=load(old['actual_XMF_manifest']['path']);native=t['source_provenance']['solver_receipt'];assert ref(native['path'])==native;nq=load(native['path'])['request'];bedrc=load(old['actual_bed_receipt']['path']);b=load(bedrc['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];source=b['source_plan_physical_condition_sha256']
 assert nq['physical_case_id']==w['physical_case_id']==q['physical_case_id'] and canonical==old['source_canonical_scope']==x['physical_condition_sha256']==x['canonical_physical_condition_sha256'];assert legacy==old['actual_H5_legacy_scope']==x['source_h5_physical_condition_sha256'];assert len({canonical,legacy,source})==3 and x['source_plan_physical_condition_sha256']==canonical
 masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};assert masks['native']['source_plan_condition_sha256']=={'present':False,'value':None};assert masks['native']['source_plan_physical_condition_sha256']=={'present':True,'value':canonical};assert masks['XMF']==masks['native'];assert 'source_definition' in b and ref(b['source_definition'])['sha256']==b['source_definition_sha256']==source
 assert w['expected_frames']==q['expected_frames']==x['frames']==801 and w['expected_particles']==q['expected_particles']==x['particles']==194427 and w['expected_contact_sheets']==34
 assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
 pp=Path(f'/proc/{pid}');live=None
 if pp.exists():
  stat=pp.joinpath('stat').read_text().split(') ',1)[1].split();assert stat[19]==start;cmd=pp.joinpath('cmdline').read_bytes().split(b'\0');assert b'--output-dir' in cmd and str(original).encode() in cmd[cmd.index(b'--output-dir')+1];p=Path(cmd[cmd.index(b'--output-dir')+1].decode());frames=list((p/'frames').glob('frame_*.png'));assert all(f.is_file() and not f.is_symlink() for f in frames);live={'pid':pid,'starttick':start,'private_output_root':str(p),'private_frame_filenames_stat_count':len(frames),'private_PNG_payloads_opened_or_hashed':False}
 terminal=F/'controller-result.json';observed=ref(terminal) if terminal.exists() else None
 rows.append({'original':original,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'actual_native_canonical_scope':canonical,'actual_typed_legacy_scope':legacy,'actual_SourceDef_role':source,'actual_native_XMF_plan_field_namespaces':masks,'native_presence_XMF_canonical_plan_and_bed_SourceDef_FILE_roles_independent':True,'binding_source_definition_present':True,'native_receipt':native,'previsual_review':ref(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json'),'same_original_request':ref(F/'enabled-full801-render-request.json'),'same_original_wrapper':ref(F/'enabled-render-wrapper.json'),'observed_controller_terminal':observed,'live_process_filename_stat_snapshot':live,'snapshot_is_historical_not_future_terminal':True,'future_own_QI_root':out,'future_own_QI_proof':None,'source_review_assignment':'fresh210' if original==1150 else 'fresh191','case_credit':0,'QN_QE':0})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_264.json';cp=load(cpfile);assert cp['checkpoint']==264 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==306
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);attempts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and attempts['qualification']<=1024 and attempts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
audit=root(1347)/'current-user-storage-cleanup-status-and-new-failure-check.json';cleanup=load(audit);assert cleanup['floor_pass'] and not cleanup['new_failed_receipts'] and not cleanup['changed_failed_receipts'] and cleanup['new_deletions_this_update']==0
O=H/'root_stage1_nextF5_original1150_1157_actual_native_and_XMF_plan_canonical_bed_SourceDef_FILE_distinct_live_durable_future801QI_1351';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_265.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1150-1157-full801-own-QI1349-1350.py').read_bytes());proof=O/'actual-original1150-1157-current-live-independent-plan-roles-and-futureQI-entrypoints.json';put(proof,{'schema':'ds02.original-F5-same-handles-durable-ownQI-readiness.v1','at_utc':now.isoformat(),'cases':rows,'durable_same_original_only_QI':ref(entry),'do_not_rerun_finished_QI':True,'commands':[['python3','-B',str(entry),'1150','1349'],['python3','-B',str(entry),'1157','1350']],'scientific_payload_IO':False,'no_simulation_restart':True,'case_credit':0,'cleanup534GiB_current_proof':ref(audit)})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=265,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active306/336; F3=42 after original1102 ownQI1340 and source209 personal44PNG adoption, explicit source report digest typo corrections preserve source bytes. Next F5 original1150/1157 same-process full801 renders live; new durable ownQI1349/1350 checks actual native and XMF physical-plan canonical separately from bed SourceDef FILE. Source175 F2 personalreview and source190 F6 final48 catalog completed awaiting main adoption. User cleanup cumulative534.4086GiB, no new/changed failed attempts, Home500GiB floor protected.',previous_goal_turn_classification='PROGRESS: source209 actualF3 full836 personal44PNG adopted; completed originalF2 full401 ownQI1346 supplied and source175 complete. Next F5 original1150/1157 exact same-process frame progression and new durable own801 QI entrypoints pin native/XMF canonical-plan roles independently from bed SourceDef FILE; source190 completed F6 full48 catalog pending adoption.')
new['actual_progress']['nextF5_original1150_1157_durable_future801_QI_native_XMF_canonical_plan_and_bed_FILE_roles']=ref(proof);new['actual_progress']['user_cleanup534GiB_current1347_no_new_failures']=ref(audit);new['source_agents']['production_recovery']='fresh175 F2 original1155 personal17contacts9keys completed60ee64c awaiting main adoption; source174 F5 catalog already adopted with current30/18 main actualrole corrections';put(np,new)
ip=root(1348)/'full336-current306-actual-final48-delivery-progress-index.json';index=load(ip);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==306;index['current_next_original_F5_renderer_to_QI_preparation']=ref(proof);put(O/'full336-current306-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('原始1150/1157同一渲染进程的801帧验收恢复入口；不重跑模拟。native source-plan字段实际存在状态与XMF physical-plan canonical以及bed SourceDef FILE哈希角色分开核查；QI1349/1350只有原进程completed0和实际发布后生成。保留534.4086GiB失败输出清理的当前复核记录，未删除被使用和诊断材料。\n')
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: preserve cleanup proof and durable F5 own801 QI after two F3 accepts','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':265,'accepted':306,'per_family':new['accepted_per_family'],'free_GiB':free,'live_F5':[x['live_process_filename_stat_snapshot'] for x in rows],'GPUh':gpu,'CPUh':cpu,'attempts':dict(attempts),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
