from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf','.png'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256']
def same(a,b):return a['path']==b['path'] and a['sha256']==b['sha256']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='817b51d3de10eb9bf236ff325d13508dccbddfb3';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_213_f5_assigned_f3_p0800_ay0570_root1033_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==8
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh213.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
u=load(P/'metadata/upstream-evidence.json');a=load(P/'metadata/actual-render-metadata.json');cl=load(P/'metadata/physical-stage-closure.json');v=load(P/'metadata/png-visual-evidence.json');s=load(P/'metadata/visual-decision.json');man=load(P/'manifest.json')
qip=root(1373)/'actual1033-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';qi=load(qip);check(u['main_qi']);check(s['qi_reference']);assert same(u['main_qi'],ref(qip)) and same(s['qi_reference'],ref(qip));cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['native_request_condition_sha256']
assert all(j['case_id']==cid and j['physical_case_id']==pid for j in [u,a,cl,v,s]);assert a['assigned_agent_family']=='F5' and a['family_id']=='F3' and man['stored_under_source_family']=='F5'
for k in ['raw_h5_bi4_csv_dat_vtk_hash','raw_h5_bi4_csv_dat_vtk_read','raw_science_payload_copied','scientific_job_started','shared_state_written']:assert not a['source_agent_science_payload_io'][k]
assert s['decision']['standalone_first_stage_visual_approved'] and not s['decision']['severe_visual_failure'] and not s['decision']['needs_root_image_intervention'] and not s['decision']['numerical_precision_accepted'] and not s['decision']['q_n_granted'] and not s['decision']['q_e_granted'] and s['decision']['independent_case_count_increment']==0
ue=u['actual_completed_metadata_evidence'];receipts={}
for role,e in qi['actual_completed_receipts'].items():
 se=ue['actual_completed_receipts'][role];check(se);assert same(se,e);j=load(e['path']);assert j['schema']=='ds02.execution-receipt.v1' and j['status']=='completed' and j['returncode']==0 and j['request']['case_id']==cid;receipts[role]=j
mapped={'typed_report':'typed_report','xmf_manifest':'XMF_manifest','xmf_xml':'XMF_XML','render_report':'render_report','publish_receipt':'publish','initial_parent_QA_receipt':'initial_parent_QA_receipt','initial_parent_QA_report':'initial_parent_QA_report','source_preparation_report':'source_preparation_report'}
for source,key in mapped.items():check(ue[source]);assert same(ue[source],qi[key])
for source,key in [('execution_receipt','render'),('render_report','render_report'),('publish_receipt','publish')]:
 target=qi['actual_completed_receipts'][key] if key=='render' else qi[key];check(a[source]);assert same(a[source],target)
nq=receipts['native']['request'];x=load(qi['XMF_manifest']['path']);rawmask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
assert rawmask==qi['actual_native_XMF_plan_field_namespaces'];assert all(not e['present'] and e['value'] is None for m in rawmask.values() for e in m.values())
sc=u['producer_scope_roles'];assert sc==a['scope_roles']==cl['scope_roles']
for ns,pfx in [('native','native'),('XMF','xmf')]:
 for k in ['source_plan_condition','source_plan_physical_condition']:assert not sc[pfx+'_'+k+'_field_present'] and sc[pfx+'_'+k+'_sha256'] is None
assert canonical==qi['actual_converter_condition_sha256']==x['physical_condition_sha256']==sc['native_request_condition_sha256']==sc['actual_converter_condition_sha256']==sc['typed_canonical_role']==sc['xmf_canonical_role']
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'];assert a['expected_and_actual']['time_window_s']==cl['counts_and_time']['time_window_s']==u['main_qi']['actual_time_window_s']==qi['actual_time_window_s']==[0.0,8.350005258058488]
assert a['expected_and_actual']['frames']==836 and a['expected_and_actual']['particles']==179208 and a['producer_counts']['fluid_initial']==67500
parentqa=load(qi['initial_parent_QA_receipt']['path']);assert parentqa['status']=='completed' and parentqa['returncode']==0;assert u['negative_retention']['historical_A_and_B_negative_evidence_retained'] and u['negative_retention']['historical_exact_lattice_or_precision_negative_retained']
r=load(qi['render_report']['path']);pub=load(qi['publish']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(qi['render_report']['path']);out=Path(pub['published_output_root']);published={e['relative_path']:e for e in pub['files_excluding_receipt']};contacts=v['producer_attested_contact_sheets'];keys=v['producer_attested_keyframes'];assert len(contacts)==35 and len(keys)==9 and [e['index'] for e in contacts]==list(range(35)) and [e['frame_index'] for e in keys]==[0,100,200,300,400,500,600,700,835];assert [e['absolute_path'] for e in contacts]==r['outputs']['contact_sheets']
for e in contacts+keys:
 p=Path(e['absolute_path']);assert p==out/e['relative_path'] and sha(p)==e['sha256']==published[e['relative_path']]['sha256'] and p.stat().st_size==e['bytes']==published[e['relative_path']]['bytes'] and e['reviewed'] and e['review_mode']=='view_image'
reviewed=a['personal_review_scope']['reviewed_at_utc'];assert reviewed==v['reviewer']['reviewed_at_utc']==s['reviewer']['reviewed_at_utc'] and a['personal_review_scope']['reviewer_model']=='gpt-5.6-luna/max' and not a['personal_review_scope']['recursive_delegation'];parse=lambda z:datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+(?=Z|[+-])',r'\1',z).replace('Z','+00:00'));now=datetime.datetime.now(datetime.timezone.utc);assert parse(receipts['render']['finished_at_utc'])<=parse(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_286.json';cp=load(cpfile);assert cp['checkpoint']==286 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==314 and cp['accepted_per_family']['F3']==43
ip=root(1382)/'full336-current314-actual-final48-delivery-progress-index.json';idx=load(ip);row=next(e for e in idx['cases'] if e['physical_case_id']==pid);assert not row.get('accepted_decision') and row['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(e['kind'] for e in ld['attempts']);gpu=sum(e.get('gpu_seconds',0) for e in ld['charges'])/3600;cpu=sum(e.get('cpu_core_seconds',0) for e in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<parse(cp['deadline_utc'])
O=H/'root_stage1_source213_actualF3_P0800AY0570_original1033_full836QI_personal44PNG_native_XMF_both_plan_absence_true_parentQA_visual_acceptance_1383';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_287.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source213-byte-exact-readonly-validator-main44publishedPNG-own836QI-true-plan-absences-parentQA-proof.json';put(vp,{'schema':'ds02.source213.main.actualF3.adoption-integrity.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'own_QI':ref(qip),'actual_reviewed_at_utc':reviewed,'review_after_completed_publication':True,'all44_publishedPNG_SHA_match_atomic_publish':True,'actual_native_XMF_plan_namespaces':rawmask,'actual_native_typed_XMF_same_canonical_digest':canonical,'source_conditions_and_plan_namespaces_are_separate_roles':True,'parent_QA_and_source704_reused_initialization_preserved_not_fabricated_percase_receipt':True,'source_role_correction_needed':False,'main_scientific_payload_IO':False})
dp=O/(pid+'-delegated-visual-decision.json');nc=[{**e,'path':e['absolute_path'],'producer_sha256':e['sha256'],'viewed':True,'view_method':'view_image','role':'contact_sheet'} for e in contacts];nk=[{**e,'path':e['absolute_path'],'producer_sha256':e['sha256'],'frame':e['frame_index'],'viewed':True,'view_method':'view_image','role':'event_keyframe'} for e in keys]
evidence={'actual_completed_receipts':qi['actual_completed_receipts'],'native_receipt':qi['actual_completed_receipts']['native'],'typed_receipt':qi['actual_completed_receipts']['typed'],'XMF_receipt':qi['actual_completed_receipts']['xmf'],'render_receipt':qi['actual_completed_receipts']['render'],'typed_report':qi['typed_report'],'XMF_manifest':qi['XMF_manifest'],'XMF_XML':qi['XMF_XML'],'render_report':qi['render_report'],'render_publish_receipt':qi['publish'],'initial_parent_QA_receipt':qi['initial_parent_QA_receipt'],'initial_parent_QA_report':qi['initial_parent_QA_report'],'source_preparation_report':qi['source_preparation_report']}
put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':canonical,'producer_scope_schema':'ds-data-02.physical-binding.v1','source_review_commit':commit,'source_review_assigned_family':'F5','actual_review_family':'F3','source_personal_visual_review':ref(R/prefix/'metadata/visual-decision.json'),'independent_full836_QI':ref(qip),'actual_completed_metadata_evidence':evidence,'full_native_frames':836,'particle_count':179208,'initial_fluid_particles':67500,'actual_type_counts':a['producer_counts'],'actual_physical_window_s':qi['actual_time_window_s'],'all836_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':rawmask,'native_and_XMF_plan_fields_true_absence_not_filled_from_canonical':True,'original_outer_envelope_801194427_not_actual836179208_authority':True,'true_genuine_parent_initial_QA_reused_not_fabricated_percase_runner_receipt':True,'registered_decoder_CLI_repair_actual_typed_completed0_old_failed_receipt_history_preserved':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':35,'personal_reviewed_keyframes':9,'personal_reviewed_at_utc':reviewed,'contact_sheets':nc,'keyframes':nk,'visual_observations':v['personal_observation'],'visual_limits':s['evidence_limits'],'strict_container_guarantee':False,'subDP_positive_depth_not_quantified':True,'no_strong_runup_or_inundation_magnitude_claim_from_visual_screen':True,'historical_negative_flags':u['negative_retention'],'main_all44_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source213-actual1033-full836QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F3']+=1
new.update(checkpoint=287,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=315,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active315/336; F1/F4/F6/F7=48,F2=44,F3=44,F5=35. Source213 actualF3original1033 full836QI1373/personal44PNG accepted with native/XMF BOTH plan trueabsences and genuine parentQA/source704 initialization retained. Source195 F2 fulltime/runtimegate repair and source180 F5 completion-only fulltime/bed builder active. NextsameoriginalF5 renders1160/1151, durableownQI1377/1380 prepared.',previous_goal_turn_classification='PROGRESS: main194 audit exposes4 actualrenderrequests asreceipts and finalgaps, source195 repairing. Actualsource179 F5original1174 personal43PNG accepted314; actualsource213 F3original1033 full836QI/personally44PNG exact8files validated and trueplanabsence bound accepted315/F3=44. No newnativeSCI jobs/precisioncredit.')
new['actual_progress']['source213_F3_actual1033_visual_acceptance']=ref(ap);new['source_agents'].update(f5_bed_recovery='fresh213 F3original1033 accepted; available for nextoriginal1160/1151 after actual0/pub and ownQI',production_recovery='fresh180 F5 completion-only final48 fulltime/native/typed/XMF/bed/runtime primary builder current35 readiness only',f6_endpoint_initial_qa='fresh195 F2 fulltime/runtime4renderrole/outputimmutable gate repair active')
new['next_executable_tasks']=['Observe sameF5original1160 PID648352/start214140469 and1151 PID650123/start214158617; actual0/pub then durableownQI1377/1380 once, assign freef5 personal34contacts9keys.','Audit source195 F2 fulltime/runtime4 renderrole/outputimmutable gates then mainindependent closure; originalP03typed runtimeunknown notpromoted.','Audit source180 F5 completion-only fulltime/bed/native-XMFroles and runtimeactualgates; historical4 publishreceiptabsences disclosed notfilled.','Complete remaining21 actualindependent visualcases then actual48 F2/F3/F5 catalogs and global336 delivery; source176 F3assembly needs ownmainfulltime/runtimeaudit.']
assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==315;put(np,new);idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=315,registered_pending_independent_physical_cases=21,new_case_credit=1);row.update(status='visual-approved-in-checkpoint287',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full836_QI=ref(qip))
idx['actual_unaccepted_completed0_published_physical_cases']=[e for e in idx['actual_unaccepted_completed0_published_physical_cases'] if (e if isinstance(e,str) else e['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(e.get('accepted_decision')) for e in idx['cases'])==315;put(O/'full336-current315-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F3 P0800AY0570 personal44PNG retaining both native XMF plan absences','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':287,'accepted':315,'F3':44,'pending':21,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
