from pathlib import Path
import json, hashlib, subprocess, datetime, math, xml.etree.ElementTree as ET, copy, collections, os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.md','.py'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):
 with Path(p).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
F=root(1119);basep=F/'actual1105-full401-XMF-and-actual-typed-producer-typed-independent-review.json';b=load(basep);refs={k:e for k,e in b.items() if isinstance(e,dict) and 'path' in e and 'sha256' in e}
for e in refs.values():assert sha(e['path'])==e['sha256']
q=load(F/'enabled-full401-render-request.json');w=load(F/'enabled-render-wrapper.json');cid=q['case_id'];pid=q['physical_case_id'];assert pid=='F2_STAGE1_FIRST48_OFFSET_OPEN_RIM_RX061_RY014_FILL080_ROT090'
receipts={k:load(refs['actual_'+k+'_receipt']['path']) for k in ['native','typed','XMF']}
for rr in receipts.values():assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
t=load(refs['actual_typed_report']['path']);x=load(refs['actual_XMF_manifest']['path']);n=receipts['native']['request'];xp=Path(refs['actual_XMF_XML']['path']);fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];g=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]')
assert t['frames']==x['frames']==w['expected_frames']==len(fs)==len(times)==len(g)==401 and t['particles']==x['particles']==w['expected_particles']==418104
assert t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected' and t['partvtk_validation']['all_passed']
assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[401,418104,3] and x['source_h5_sha256']==t['output_sha256']
assert times==[z['time'] for z in fs]==[float(z.find('Time').get('Value')) for z in g] and [times[0],times[-1]]==[0,4.000022778759003] and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
for i,(z,grid) in enumerate(zip(fs,g)):
 assert z['frame']==i and z['active_particles']+z['missing_particles']==418104 and z['type_counts']=={'0':372840,'1':24150,'2':0,'3':21114-z['missing_particles']} and z['missing_type_counts']=={'0':0,'1':0,'2':0,'3':z['missing_particles']}
 assert grid.find('Geometry').get('GeometryType')=='XYZ' and grid.find('Geometry/DataItem').get('Dimensions')=='418104 3';v=next(a for a in grid.findall('Attribute') if a.get('Name').lower()=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='418104 3'
canonical=n['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert canonical=='d5554e9607723d41638618937d2c681cfdec3084b54297bf0e75b4f82a9885bc' and legacy==x['physical_condition_sha256']==b['physical_condition_sha256']=='cb836db0de7dd6e6b9e2beef7f8dbffb85a461af59aa8db10feccdcde9ec11e7'
masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',n),('XMF',x)]};assert masks['native']=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}} and all(v=={'present':False,'value':None} for v in masks['XMF'].values())
for key in ['gencase_receipt','generated_xml','owner_metadata','solver_receipt']:
 e=t['source_provenance'][key];assert sha(e['path'])==e['sha256'];refs['typed_source_'+key]=e
assert t['source_provenance']['solver_receipt']==refs['actual_native_receipt'];gc=load(refs['typed_source_gencase_receipt']['path']);assert gc['status']=='completed' and gc['returncode']==0 and gc['request']['case_id']==cid
for key in ['initial_qa_receipt','initial_qa_report']:
 e=ref(n[key]);assert receipts['native']['input_hashes_at_launch'][e['path']]==receipts['native']['input_hashes_after_run'][e['path']]==e['sha256'];refs[key]=e
qa=load(refs['initial_qa_receipt']['path']);qr=load(refs['initial_qa_report']['path']);assert qa['status']=='completed' and qa['returncode']==0 and qa['request']['case_id']==qr['case_id']==cid and qr['status']=='pass'
assert fs[-1]['missing_particles']==1 and max(z['missing_particles'] for z in fs)==1 and next(z['frame'] for z in fs if z['missing_particles'])==157 and sum(z['missing_particles'] for z in fs)==244
assert fs[-1]['missing_id_first']==[403829] and fs[-1]['missing_ids_sha256']=='d2de423b42c04526d6035c4f481e10d8ac1a6660fecf720023ea2f41bbd710f0'
assert not (F/'controller-result.json').exists();observed=[]
for original,pid0,start in [(1119,759177,'215152319'),(1176,749459,'215077434')]:
 pp=Path('/proc')/str(pid0);stat=(pp/'stat').read_text().rsplit(')',1)[1].split();args=(pp/'cmdline').read_bytes().split(b'\0');assert stat[19]==start and str(root(original)/'enabled-render-wrapper.json').encode() in args
 observed.append({'original':original,'actual_registered_launch_pid':pid0,'startticks':start,'state':stat[0],'launch_cmdline_bound_to_original_request':True,'no_restart':True})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_314.json';cp=load(cpfile);ip=root(1422)/'full336-current327-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile) and cp['stage1_visual_accepted_complete_independent_cases']==327
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(z['kind'] for z in ld['attempts']);gpu=sum(z.get('gpu_seconds',0) for z in ld['charges'])/3600;cpu=sum(z.get('cpu_core_seconds',0) for z in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current327_nextF2_original1119_full401_one_fluid_omission_actual_native_XMF_roles_genuineQA_durableQI1425_1424';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_315.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1425'));O.mkdir();entry=O/'after_original1119_terminal_full401_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F2-original1119-full401-own-QI1425.py').read_bytes());proof=O/'next-original1119-actual401-one-omission-genuineQA-durableQI-readiness.json'
put(proof,{'schema':'ds02.main.next-original1119.full401.QI-readiness.v1','at_utc':now.isoformat(),'case_id':cid,'physical_case_id':q['physical_case_id'],'upstream_full401_metadata_refs':refs,'prior_previsual_review':ref(basep),'canonical_native_sha256':canonical,'typed_XMF_legacy_sha256':legacy,'actual_native_XMF_plan_field_namespaces':masks,'actual_time_window_s':[times[0],times[-1]],'full401_typed_UID_type_N3_and_XMF_exact_time_verified':True,'genuine_initial_QA_and_GenCase_completed0':True,'fluid_omissions':{'final':1,'first_frame':157,'cumulative_particle_frames':244,'attested_Idp_sample':fs[-1]['missing_id_first'],'sample_is_all_one_missing_Idp':True,'attested_final_missing_Idp_digest':fs[-1]['missing_ids_sha256'],'state_location_cause_unknown':True},'same_live_original_registered_launches':observed,'future_ownQI1425_UNEXECUTED_SHA_unknown':True,'durable_entry':ref(entry),'command':['python3','-B',str(entry),'1119','1425'],'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=315,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: accepted325 then326 then327. Actual1159 independent full801QI1421 complete and personal review active. Next actual1176 durable1423 prepared. Newly admitted F2 RX061ROT090 original1119 worker759177/start215152319 genuine401 UID/N3/XML exacttimes/nativecanonical typedlegacy namespaces/genuineQA checked; one fluid UID403829 missing first157/cumulative244, state location cause unknown; futureown1425 prepared. No new science or render jobs.',authorized_work_state='Active327/336 remaining9. Production fresh188/new personal original1159 after own1421 active; F6fresh200 original1176 preflight waits0/pub/own1423; F5fresh222 original1119 preflight waits0/pub/own1425. Registered queue unchanged and no duplicate runs; final tools readiness only and actual primary joins remain required.')
new['actual_progress']['next_original1119_durable401_QI']=ref(proof)
new['source_agents']['f5_bed_recovery']='fresh222 assignedF2original1119 preflight then personal17+9 after0/pub and own1425'
new['next_executable_tasks']=['Integrate source actual1159 personal43PNG after immutable review package, completed own1421 no rerun.','After original1176 natural0/pub run durableown1423 once then F6source personal34+9.','After original1119 natural0/pub run durableown1425 once then F5source personal17+9 retaining fluid UID403829 omission with unknown cause/state/location.','Continue registered queue and actual remaining9 distinct cases, then actual48 F2/F3/F5 primary and global336 delivery; QN/QE not granted.'];put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,next_original1119_durable401_QI=ref(proof));put(O/'full336-current327-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare next F2 full401 integrity preserving one fluid omission and live original launches','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':315,'accepted':327,'future_ownQI1425_unexecuted':True,'proof':ref(proof),'live':observed,'free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
