from pathlib import Path
import json,hashlib,runpy,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in {'.h5','.bi4','.dat','.csv','.vtk','.vtu','.npy','.npz'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,o):Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
old=root(1083);q=load(old/'enabled-full801-render-request.json');w=load(old/'enabled-render-wrapper.json');res=load(old/'controller-result.json');assert res['launcher_returncode']==1 and res['status'] is None and res['returncode'] is None and 'Input differs from registered digest:' in res['stderr_tail'];assert not Path(res['actual_receipt']).exists();proc=load(old/'controller-launch-process.json');assert not Path(f"/proc/{proc['pid']}").exists();ledger=load(D/'runtime/resource-ledger.json');assert not any(a.get('attempt_id')==q['attempt_id'] or a.get('id')==w['reservation_id'] for a in ledger['attempts'])
proof=load(old/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json');assert proof['all801_UID_fluid31658_finite_and_footprint_checked'];cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_167.json');assert w['physical_case_id'] not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
O=H/'root_stage1_F5_M090T085_actual1083_prelaunch_volatile_progress_frozen_original_worker_full801_expected34_repair1_1096';O.mkdir(exist_ok=False)
volatile=[p for p in q['input_files'] if Path(p).name=='actual-progress.json'];assert len(volatile)==1;vp=Path(volatile[0]);assert vp==root(1055)/'actual-progress.json';frozen=O/'root1055-completed-progress-frozen.json';frozen.write_bytes(vp.read_bytes());assert sha(vp)!=q['input_sha256'][str(vp)];assert (root(1055)/'controller-result.json').exists();terminal=load(root(1055)/'controller-result.json')
# Immutable actual bed receipt/report are the scientific upstream proof; a changing controller observer is provenance only.
for k in ['actual_bed_receipt','actual_bed_report','actual_typed_receipt','actual_typed_report','actual_XMF_receipt','actual_XMF_manifest']:
 item=proof[k];assert sha(item['path'])==item['sha256']
for k in ['actual_bed_receipt','actual_typed_receipt','actual_XMF_receipt']:
 a=load(proof[k]['path']);assert (a['status'],a['returncode'])==('completed',0)
controller=O/'fair-render-controller.py';controller.write_bytes((old/'fair-render-controller.py').read_bytes());aid='root-stage1-f5-m090_t085-source177-full801-original116023-frozen-progress-repair1-root1096';ar=Path(q['attempt_root']).parent/aid;rid=f"F5/{q['case_id']}/{aid}";assert not ar.exists()
sidecar=O/'prelaunch-failure-original-evidence-and-frozen-observer-repair.json';put(sidecar,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_failed_controller':ref(old/'controller-result.json'),'original_registered_request':ref(old/'enabled-full801-render-request.json'),'original_wrapper':ref(old/'enabled-render-wrapper.json'),'original_scientific_upstream_independent_proof':ref(old/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json'),'failed_before_scientific_render_attempt':True,'volatile_original_path':str(vp),'original_registered_observer_sha256':q['input_sha256'][str(vp)],'current_observer_frozen':ref(frozen),'actual1055_terminal':ref(root(1055)/'controller-result.json'),'root_cause':'Mutable actual-progress observer changed when second bed finished; freeze provenance into new immutable path.','repair_number':1,'scientific_kernels_and_completed_outputs_reused_unchanged':True,'source177_original_future_planning_preserved':True,'actual_enabled_contact_count':34,'original_source_expected_contact_count':35,'contact_count_evidence':'Actual unchanged Root023 renderer groups24 chronological tiles perpage; ceil801/24=34, existing Root984 actual full801 output independently closed in Root1093.','main_scientific_payload_IO':False,'case_credit':0})
md={}
for p,h in w['input_sha256'].items():
 if p==str(vp):md[str(frozen)]=sha(frozen)
 else:assert sha(p)==h;md[p]=h
md.pop(str(old/'fair-render-controller.py'),None)
for p in [controller,sidecar,old/'enabled-full801-render-request.json',old/'enabled-render-wrapper.json',old/'controller-result.json']:md[str(p)]=sha(p)
w.update(attempt_id=aid,reservation_id=rid,current_attempt_id=rid,home_output=str(ar/'render'),nvme_root='/tmp/ds02-visual-render-cache-root1096',input_files=sorted(md),input_sha256=md,expected_contact_sheets=34)
api=runpy.run_path(w['renderer_worker']);assert sha(w['renderer_worker'])=='5d577e4b28e62906472bfba30ad445685f804be4ba5d8bab44b4bab3d32e1621';api['validate_request'](w,execution=True);assert api['_manifest_metadata'](w)['frames']==801
wp=O/'enabled-render-wrapper.json';put(wp,w);h5=[p for p in q['input_files'] if Path(p).suffix=='.h5'];assert len(h5)==1;t=load(proof['actual_typed_report']['path']);assert h5[0]==t['output_hdf5'] and q['input_sha256'][h5[0]]==t['output_sha256'];outer={**md,str(wp):sha(wp),h5[0]:t['output_sha256']}
q.update(attempt_id=aid,attempt_root=str(ar),command=[str(L/'.venv/bin/python'),q['command'][1],'--worker',w['renderer_worker'],'--request',str(wp)],input_files=sorted(outer),input_sha256=outer,expected_contact_sheets=34,root_grounded_failure_class='prelaunch-volatile-observer-digest-mismatch',root_grounded_repair_number=1,root_scope='Only observer provenance frozen; original116023944 full801 renderer and original scientific inputs unchanged; 34 actual chronological contact pages expected; no visual or numerical credit until output review.')
qp=O/'enabled-full801-render-request.json';put(qp,q);put(O/'controller-config.json',{'request':str(qp),'fair_dispatch':ref(root(928)/'fair_CPU_dispatch.py'),'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: freeze completed bed observer for bounded F5 render prelaunch repair','--',*paths],cwd=R,check=True);print({'root':1096,'physical_case_id':w['physical_case_id'],'expected_contacts':34,'case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
