from pathlib import Path
import json,hashlib,datetime,copy,collections,subprocess,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.xml','.xmf','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
rows=[]
for original,out,pid,start in [(1181,1331,549174,'213202106'),(1191,1332,550125,'213210951')]:
 F=root(original);old=load(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json');w=load(F/'enabled-render-wrapper.json');q=load(F/'enabled-full801-render-request.json');refs={k:v for k,v in old.items() if isinstance(v,dict) and 'path' in v and 'sha256' in v}
 for e in refs.values():assert ref(e['path'])['sha256']==e['sha256']
 t=load(old['actual_typed_report']['path']);x=load(old['actual_XMF_manifest']['path']);native=t['source_provenance']['solver_receipt'];assert ref(native['path'])==native;nq=load(native['path'])['request'];bedrc=load(old['actual_bed_receipt']['path']);b=load(bedrc['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];source=b['source_plan_physical_condition_sha256']
 assert nq['physical_case_id']==w['physical_case_id']==q['physical_case_id'] and canonical==old['source_canonical_scope']==x['physical_condition_sha256']==x['canonical_physical_condition_sha256'];assert legacy==old['actual_H5_legacy_scope']==x['source_h5_physical_condition_sha256'];assert len({canonical,legacy,source})==3 and x['source_plan_physical_condition_sha256']==source
 masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};assert masks['native']['source_plan_condition_sha256']=={'present':False,'value':None};assert masks['native']['source_plan_physical_condition_sha256']=={'present':original==1191,'value':canonical if original==1191 else None};assert 'source_definition' in b and ref(b['source_definition'])['sha256']==b['source_definition_sha256']==source
 assert w['expected_frames']==q['expected_frames']==x['frames']==801 and w['expected_particles']==q['expected_particles']==x['particles']==194427 and w['expected_contact_sheets']==34
 assert w['cpu_threads']==w['declared_cpu_cores']==24 and w['environment_threads']==2 and w['global_renderer_cap']==2 and w['home_free_floor_bytes']==500*2**30
 pp=Path(f'/proc/{pid}');live=None
 if pp.exists():
  stat=pp.joinpath('stat').read_text().split(') ',1)[1].split();assert stat[19]==start;cmd=pp.joinpath('cmdline').read_bytes().split(b'\0');assert b'--output-dir' in cmd and str(original).encode() in cmd[cmd.index(b'--output-dir')+1];p=Path(cmd[cmd.index(b'--output-dir')+1].decode());frames=list((p/'frames').glob('frame_*.png'));assert all(f.is_file() and not f.is_symlink() for f in frames);live={'pid':pid,'starttick':start,'private_output_root':str(p),'private_frame_filenames_stat_count':len(frames),'private_PNG_payloads_opened_or_hashed':False}
 terminal=F/'controller-result.json';observed=ref(terminal) if terminal.exists() else None
 rows.append({'original':original,'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'actual_native_canonical_scope':canonical,'actual_typed_legacy_scope':legacy,'actual_SourceDef_role':source,'actual_native_XMF_plan_field_namespaces':masks,'native_presence_and_XMF_SourceDef_role_independent':True,'binding_source_definition_present':True,'native_receipt':native,'previsual_review':ref(F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json'),'same_original_request':ref(F/'enabled-full801-render-request.json'),'same_original_wrapper':ref(F/'enabled-render-wrapper.json'),'observed_controller_terminal':observed,'live_process_filename_stat_snapshot':live,'snapshot_is_historical_not_future_terminal':True,'future_own_QI_root':out,'future_own_QI_proof':None,'source_review_assignment':'fresh188' if original==1181 else 'fresh208','case_credit':0,'QN_QE':0})
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_254.json';cp=load(cpfile);assert cp['checkpoint']==254 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==302
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);attempts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and attempts['qualification']<=1024 and attempts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
audit=root(1336)/'current-storage-cleanup-verification.json';cleanup=load(audit);assert cleanup['all_deleted_paths_still_absent'] and cleanup['all_preserved_samples_present'] and cleanup['original_failed_receipts_bytes_unchanged'];assert cleanup['new_deletions_this_verification']==0
O=H/'root_stage1_nextF5_original1181_1191_live_independent_native_presence_XMF_SourceDef_roles_durable_future801QI_cleanup534GiB_1333';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_255.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-next1181-1191-original-full801-own-QI.py').read_bytes());proof=O/'actual-original1181-1191-current-live-independent-plan-roles-and-futureQI-entrypoints.json';put(proof,{'schema':'ds02.original-F5-same-handles-durable-ownQI-readiness.v1','at_utc':now.isoformat(),'cases':rows,'durable_same_original_only_QI':ref(entry),'do_not_rerun_finished_QI':True,'commands':[['python3','-B',str(entry),'1181','1331'],['python3','-B',str(entry),'1191','1332']],'scientific_payload_IO':False,'no_simulation_restart':True,'case_credit':0,'cleanup534GiB_current_proof':ref(audit)})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=255,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ledger['reservations'],attempt_counts=dict(attempts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active302/336; F3 two actual836/179208 cases newly visually accepted with ownQI and exact44 publishedPNG. F5 original1181/1191 same-process full801 renders remain pending visual, new durable QI1331/1332 independently checks native field presence vs XMF SourceDef. User cleanup cumulative534.4086GiB reverified; Home500GiB floor protected.',previous_goal_turn_classification='PROGRESS: source207 and186 actualF3 full836 personal44PNG adoption +2; originalF5 live same-handle actual frame advancement and new durable ownQI entrypoints, exact namespace-presence independence preserved. Storage deletion audit534GiB reverified with no new unused failed outputs.')
new['actual_progress']['nextF5_original1181_1191_durable_future801_QI_independent_native_XMF_roles']=ref(proof);new['actual_progress']['user_cleanup534GiB_current1336_verification']=ref(audit);new['source_agents']['production_recovery']='source173 F2 final48 catalog42accepted/sixpending completed6580568 awaiting mainbyte-exactadoption; fresh174 F5 final48 28accepted20pending source catalog assigned';put(np,new)
ip=root(1335)/'full336-current302-actual-final48-delivery-progress-index.json';index=load(ip);index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0);assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==302;index['current_next_original_F5_renderer_to_QI_preparation']=ref(proof);put(O/'full336-current302-actual-final48-delivery-progress-index.json',index);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());(O/'README.md').write_text('原始1181/1191同一渲染进程的801帧验收恢复入口；不重跑模拟。native source-plan字段实际存在状态与XMF SourceDef哈希角色分开核查；QI1331/1332只有原进程completed0和实际发布后生成。保留534.4086GiB失败输出清理的当前复核记录，未删除被使用和诊断材料。\n')
paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))]+[str(p.relative_to(R)) for p in root(1336).iterdir()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: preserve cleanup proof and durable F5 own801 QI after two F3 accepts','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':255,'accepted':302,'per_family':new['accepted_per_family'],'free_GiB':free,'live_F5':[x['live_process_filename_stat_snapshot'] for x in rows],'GPUh':gpu,'CPUh':cpu,'attempts':dict(attempts),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
