from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,xml.etree.ElementTree as ET,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.txt','.log','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_189_f5_m102_t085_actual1173_visual_review_v1';commit='85d29069fd3c317c392bbccdd376d5cb4999157d';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==8;adopted=[]
for name in names:
 raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists() or p.read_bytes()==raw;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_source189_F5_M102T085_actual1173_full801_34contacts_ninekeys_independent_visual_acceptance_1201';O.mkdir(exist_ok=False);assert not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_185.json').exists();before={name:sha(W/name) for name in names};vld=W/prefix/'scripts/validate_fresh189.py';rv=subprocess.run([str(L/'.venv/bin/python'),'-B',str(vld)],capture_output=True,text=True);assert rv.returncode==0 and before=={name:sha(W/name) for name in names};put(O/'actual-source189-validator-preserved-output.json',{'validator':ref(vld),'returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr,'source_bytes_unchanged':True})
z=load(P/'metadata/physical-stage-closure.json');v=load(P/'metadata/visual-decision.json');png=load(P/'metadata/png-visual-evidence.json');up=load(P/'metadata/upstream-evidence.json');ar=load(P/'metadata/actual1173-render-metadata.json');refs={}
for k,entry in up['upstream_chain'].items():
 key={'typed_conversion_report':'typed_report','xdmf':'xmf_xml'}.get(k,k);refs[key]={'path':entry['path'],'sha256':entry['sha256'],'bytes':Path(entry['path']).stat().st_size}
bedq=load(refs['bed_receipt']['path'])['request'];b=load(bedq['binding'])
for key,bkey in [('gencase_receipt','gencase_receipt'),('initial_qa_receipt','initial_qa_receipt'),('initial_qa_report','initial_qa_report'),('generated_xml','canonical_generated_xml')]:
 p=b[bkey];assert sha(p)==b[bkey+'_sha256'];refs[key]={**ref(p),'bytes':Path(p).stat().st_size}
for key,mkey in [('render_receipt','execution_receipt'),('render_report','render_report'),('render_publish_receipt','publish_receipt')]:
 entry=ar[mkey];refs[key]={'path':entry['path'],'sha256':entry['sha256'],'bytes':Path(entry['path']).stat().st_size}
renderq=next(H.glob('root*_1173'))/'enabled-full801-render-request.json';refs['render_enabled_request']={**ref(renderq),'bytes':renderq.stat().st_size}
assert load(refs['render_receipt']['path'])['request_sha256']==sha(renderq)
put(O/'normalized-current-source189-stage-refs-originals-preserved.json',{'actual_stage_refs':refs,'original_upstream':ref(P/'metadata/upstream-evidence.json'),'original1173_render_metadata':ref(P/'metadata/actual1173-render-metadata.json'),'original_stage_closure':ref(P/'metadata/physical-stage-closure.json'),'source_bytes_unchanged':True,'case_credit':0})
assert v['decision']['standalone_first_stage_visual_approved'] and not v['decision']['needs_root_image_intervention'] if 'needs_root_image_intervention' in v['decision'] else v['decision']['standalone_first_stage_visual_approved'];assert v['actual_producer_evidence_reviewed']['all_actual_contact_sheets_reviewed'] and v['actual_producer_evidence_reviewed']['all_nine_keyframes_reviewed']
for key,p in refs.items():assert sha(p['path'])==p['sha256'] and Path(p['path']).stat().st_size==p['bytes']
receipts={k:load(refs[k+'_receipt']['path']) for k in ['gencase','initial_qa','native','typed','xmf','bed','render']};assert all((r['status'],r['returncode'])==('completed',0) for r in receipts.values());assert all(r['request']['case_id']==z['case_id'] for r in receipts.values())
t=load(refs['typed_report']['path']);x=load(refs['xmf_manifest']['path']);r=load(refs['render_report']['path']);bed=load(refs['bed_report']['path']);qa=load(refs['initial_qa_report']['path']);pid=z['physical_case_id'];canonical=receipts['native']['request']['physical_condition_sha256'];actual=t['hash_scopes']['physical_condition_sha256'];assert pid==receipts['native']['request']['physical_case_id']==t['hash_scopes']['physical_condition']['physical_case_id']==x['physical_case_id']==bed['bound_actual_inputs']['physical_case_id'];assert canonical==x['physical_condition_sha256']==x['canonical_physical_condition_sha256']==bed['physical_condition_sha256']==up['scope_roles']['canonical_physical_owner_sha256'];assert actual==x['source_h5_physical_condition_sha256']==bed['source_h5_physical_condition_sha256']==up['scope_roles']['actual_converter_legacy_scope_sha256'];assert t['hash_scopes']['physical_condition']['schema']=='legacy-owner-scope.v0'
assert qa['all_basic_placement_checks_pass'] and all(qa['checks'].values()) and not qa['numerical_precision_result_accepted'];assert t['conversion_status']=='completed' and t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']) and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected';assert t['solver_dimension']['solver_dimension']==3
for key in ['gencase_receipt','solver_receipt','generated_xml','owner_metadata']:
 p=t['source_provenance'][key];assert sha(p['path'])==p['sha256']
assert t['source_provenance']['solver_receipt']==ref(refs['native_receipt']['path']);assert t['source_provenance']['gencase_receipt']==ref(refs['gencase_receipt']['path']);assert t['source_provenance']['generated_xml']==ref(refs['generated_xml']['path'])
assert t['frames']==x['frames']==r['frames']==r['source_frames']==len(bed['frame_reports'])==bed['scan']['frames_scanned']==801 and t['particles']==x['particles']==bed['scan']['particle_axis_count']==194427;assert bed['scan']['initial_fluid_uid_count']==31658 and bed['status']=='completed_worker_output_pending_root_review' and not bed['source_arrays_modified'] and not bed['source_arrays_dropped_or_masked']
h5=t['output_hdf5'];assert Path(h5).is_file() and t['output_sha256']==x['source_h5_sha256']==r['source_h5_sha256']==up['scope_roles']['typed_h5_sha256_producer_attested_only']
for key in ['xmf','bed','render']:
 rr=receipts[key];assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
xml=refs['xmf_xml']['path'];assert sha(xml)==x['xdmf_sha256']==r['xdmf_sha256_before']==r['xdmf_sha256_after'] and sha(refs['xmf_manifest']['path'])==r['manifest_sha256'];assert r['frame_selection']==list(range(801)) and r['all_frames_rendered'] and r['native_identity_axis_preserved'] and r['actual_times_preserved_exactly'] and r['source_h5_read_only'] and r['nonfinite_active_states']==0
fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xml).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==801;assert times==[f['time'] for f in fs]==[d['actual_time_s'] for d in ds]==[f['time_s'] for f in bed['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=16 and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
for i,(f,d,g,bf) in enumerate(zip(fs,ds,grids,bed['frame_reports'])):
 assert f['frame']==d['frame']==bf['frame']==i and f['active_particles']==d['active']==194427 and f['missing_particles']==d['missing']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658};assert d['identity_axis_preserved'] and d['finite_positions_active'] and all(a['finite_active'] and a['nonfinite_active']==0 for a in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';vv=next(a for a in g.findall('Attribute') if a.get('Name')=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='194427 3'
 assert bf['initial_fluid_uid_count']==bf['current_valid_type3_fluid_count']==bf['finite_mass_current_fluid_count']==bf['finite_position_current_fluid_count']==31658 and bf['uid_tracking']['missing_initial_uid']['count']==bf['uid_tracking']['unexpected_current_uid']['count']==bf['nonfinite_mass_current_fluid_count']==bf['nonfinite_position_current_fluid_count']==0 and not bf['uid_tracking']['unexplained'];assert bf['bed_domain']['x_outside_exact_profile_domain_count']==bf['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']==bf['penetration']['depth_unevaluable_current_fluid_count']==0
 for k,threshold in [('one_dp',.02),('two_dp',.04)]:assert bf['penetration'][k]['threshold_m']==threshold and bf['penetration'][k]['count']==0 and bf['penetration'][k]['deepest_depth_m'] is None
assert len(png['contact_sheets'])==len(r['outputs']['contact_sheets'])==34 and [p['path'] for p in png['contact_sheets']]==r['outputs']['contact_sheets'];assert [p['name'] for p in png['contact_sheets']]==[f'all_frames_{i:03d}.png' for i in range(34)];assert len(png['keyframes'])==9 and [p['frame'] for p in png['keyframes']]==[0,100,200,300,400,500,600,700,800]
for p in png['contact_sheets']+png['keyframes']:assert p['reviewed'] and sha(p['path'])==p['sha256'] and Path(p['path']).stat().st_size==p['bytes']
framepaths=sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'));assert framepaths==[f'frame_{i:04d}.png' for i in range(801)]
sourceq=load(refs['render_enabled_request']['path']);wrapper_path=sourceq['command'][-1];w=load(wrapper_path);core=Path(w['renderer']);assert sha(core)=='5e78f7b92ad7c6f1d15902e3ccacc9099affb04b1b992a42f540eb88241bde66';assert receipts['render']['input_hashes_at_launch'][str(core)]==receipts['render']['input_hashes_after_run'][str(core)]==sha(core);assert 'if len(contact_tiles) == 24 or selection_index == len(selection) - 1:' in core.read_text()
coverage=[{'page':i,'frame_start':i*24,'frame_end':min(800,i*24+23),'count':min(24,801-i*24)} for i in range(34)];assert sum(c['count'] for c in coverage)==801;contactnote={'original_task_and_enabled_wrapper_expected_contacts':w['expected_contact_sheets'],'actual_count':34,'source023_batch_size':24,'computed_ceil_801_over24':34,'all801_actual_frame_PNG_filenames_present':True,'coverage':coverage,'source_wrapper_and_reports_unchanged':True,'no_extra35th_page_generated_or_credit_inferred':True}

oldcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_184.json';cp=load(oldcp);old=[load(p) for p in cp['accepted_decisions']]
assert len(old)==sum(cp['accepted_per_family'].values())==268 and cp['numeric_reference_accepted_independent_products']==0
assert pid not in {d.get('physical_case_id',d['case_id']) for d in old} and z['case_id'] not in {d['case_id'] for d in old} and canonical not in {d['physical_condition_sha256'] for d in old}
now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json')
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':z['case_id'],'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':actual,'source_plan_condition_sha256':bed['source_plan_physical_condition_sha256'],'source_review_commit':commit,'source_visual_review':ref(P/'metadata/visual-decision.json'),'source_review_closure':ref(P/'metadata/physical-stage-closure.json'),'actual_completed_metadata_evidence':refs,'full_native_frames':801,'particles':194427,'actual_physical_window_s':[times[0],times[-1]],'all801_geometry_velocity_N3_times_UID_finite_verified':True,'stage1_QI_full_native_identity_and_state_verified':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['visual_observations'],'actual_contact_count_and_coverage_closure':contactnote,'original_source189_scope_roles':up['scope_roles'],'all801_full_bed_UID_footprint_one_DP_two_DP_diagnostics_checked':True,'positive_depth_below_DP_not_proven_absent_by_zero_bin_counts':True,'large_runup_inundation_or_strict_container_guarantee':False,'initial_qa_numerical_precision_negative':qa['numerical_precision'],'historical_A_B_negative_evidence_preserved':z['historical_negative_evidence_preserved'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1}
# Prepare all mutable runtime observations before committing the acceptance transaction.
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);lf=O/'resource-ledger-frozen.json';lf.write_bytes(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']};gpu=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
launchrefs=[]
for n in [1173,1174,1175,1176,1177,1180,1181,1182,1183,1184,1186,1187,1188,1189,1190,1191,1194]:
 p=next(H.glob(f'root*_{n}'))/'controller-launch-process.json';j=load(p);proc=Path('/proc')/str(j['pid'])/'stat';same=False
 if proc.exists():
  st=proc.read_text().split(') ',1)[1].split();same=st[0]!='Z' and st[19]==str(j['proc_start_ticks'])
 launchrefs.append({'root':n,'actual_launch':ref(p),'same_PID_start_ticks_live_now':same})
put(O/'actual-seventeen-current-full-render-controller-handles.json',{'at_utc':now,'new_registered_render_controllers':launchrefs,'no_restart_from_observation_timeout':True})
put(dp,decision)
proof=O/'source189-M102T085-actual1173-full801-independent-visual-adoption-review.json'
put(proof,{'source_commit':commit,'adopted_files':adopted,'source_validator':ref(O/'actual-source189-validator-preserved-output.json'),'actual_new_decision':ref(dp),'normalized_actual_stage_refs':ref(O/'normalized-current-source189-stage-refs-originals-preserved.json'),'all801_UID_N3_times_fields_and_bed_diagnostics_checked':True,'actual34contact_full801_coverage':contactnote,'actual1173_complete0_only_render_evidence_old1083_excluded':True,'scope_roles_canonical_plan_and_actual_legacy_separate_preserved':True,'science_payload_IO':False,'new_case_credit':1})
cp['accepted_per_family']['F5']+=1
cp.update(checkpoint=185,at_utc=now,predecessor=str(oldcp),predecessor_sha256=sha(oldcp),stage1_visual_accepted_complete_independent_cases=269,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(lf),active_reservations=ledger['reservations'],attempt_counts=counts,gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='Progress: fresh189 F5M102T085 actual1173 full801 personally34contacts9keys and independentlyclosedGenQA/native/typed/XMF/bed/render0 fullUID/N3/time/finite/footprint/scopes; accepted269/F5=11. Source162 actual1064 F2personalreview +163correctedlimits accepted268/F2=32 with7finalfluidmissing/236frames/1051particleframeevents/first165 unknowncause. Full336registeredphysicalcoverage verified; F2actual1120/F3actual1128 realrendering; no numericalcertification or duplicate science.')
assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==269
cp['actual_progress'].update(source189_F5_M102T085_independent_visual_closed=ref(proof),seventeen_current_actual_render_launches=ref(O/'actual-seventeen-current-full-render-controller-handles.json'))
cp['source_agents']['f5_bed_recovery']='fresh189 actual1173 accepted269/F5=11; source190 first8/24physicalmembership and next actualcompleted0 full801visual'
cp['authorized_work_state']='Active269/336: F2=32,F3=35,F5=11,F6=47,F1/F4/F7=48. Full336 actualphysicalregistration verified, remaining67 deliverables require actualcomplete render andpersonalreview. F2actual1120/F3actual1128 active; source147 canonical/native vs legacy role closure and190 F5first8/24subset audit pending. Originalqueuesincl951lastF6 preserved.';cp['next_executable_tasks']=['Adopt nextactualcompleted0 F2RX058ROT105 Root1120 personal17contacts9keys with own actualframeledgerderivedstats','Adopt nextactualcompleted0 F3P1200AY0500 Root1128 personal35contacts9keys and full836scope/UID/timeclosure','Adopt source147 F3all48 actualnative scope roles, preserve originalsource146 andoldRoot1198index; newrole-awareglobalindexno casecredit','Finish source190 F5first8/first24subsetmembership vs48, no newscenecatalogue or duplicates','Observe alloriginalregisteredqueuedrendersincluding951lastF6, preserveactualsamehandles, no restart from wait','Continue remaining67 cases; precisionlabelsnotaccepted and Q-N/Q-E0, Home500GiBfloor']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_185.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes())
paths=[str(Path(x['path']).relative_to(R)) for x in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_185.json').relative_to(R))]+[str((next(H.glob(f'root*_{n}'))/'controller-launch-process.json').relative_to(R)) for n in [1173,1174,1175,1176,1177,1180,1181,1182,1183,1184,1186,1187,1188,1189,1190,1191,1194]]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept eleventh F5 full801 visual from actual1173 preserving weakwave and numerical limits','--',*paths],cwd=R,check=True)
print({'checkpoint':185,'accepted':269,'families':cp['accepted_per_family'],'remaining':67,'actual_contacts':34,'Home_free_GiB':free,'GPUh':gpu,'CPUcoreh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
