"""Additive root verifier: bind systemd memory to the actual request.
All scientific metadata verification remains the frozen V1 implementation.
"""
from pathlib import Path
import json,subprocess,hashlib,importlib.util,math
exec((Path(__file__).parent/'root_common_verification.py').read_text(),globals())
def sha(path):
 path=Path(path);assert path.suffix.lower() not in {'.h5','.hdf5','.bi4','.obi4','.ibi4','.vtk','.jsonl'} and path.stat().st_size<=10485760
 return hashlib.sha256(path.read_bytes()).hexdigest()
import sys
num=sys.argv[1];family=sys.argv[2];name='typed-lifecycle-batch-v1-'+family.lower();qp=S/f'requests/{name}-root-forward-{num}-001.json';q,b,r,p=common(qp);vp=b/'typed-lifecycle-batch/batch-summary.json';v=load(vp);assert v['status'] in ['COMPLETED_WITH_CASE_RESULTS','COMPLETED_WITH_CASE_FAILURES'];mp=Path(q['manifest_contract']['path']);m=load(mp);assert sha(mp)==q['manifest_contract']['sha256']==v['manifest']['sha256'];assert v['manifest']['path']==str(mp);cases={x['physical_case_id']:x for x in m['cases']};assert 0<len(cases)<=8 and set(cases)==set(q['physical_case_ids'])==set(x['physical_case_id'] for x in v['case_results']);assert v['batch_scope']['sequential_one_case_at_a_time'] and v['counts']['cases_requested']==len(cases);verified=[];failed=[]
for item in v['case_results']:
 case=cases[item['physical_case_id']];rp=Path(item['receipt']);assert rp.is_relative_to(b);cr=load(rp);assert sha(rp)==item['receipt_sha256'];assert cr['physical_case_id']==item['physical_case_id'] and cr['status']==item['status'];assert cr['case_manifest']==case['case_manifest'] and cr['case_manifest_sha256']==case['case_manifest_sha256']==sha(Path(case['case_manifest']))
 if cr['status']!='COMPLETED':
  failed.append({'physical_case_id':item['physical_case_id'],'receipt':str(rp),'receipt_sha256':sha(rp),'status':cr['status'],'error_type':cr.get('error_type'),'error_message':cr.get('error_message'),'saved_mask_credit':False});continue
 sr=cr['output_summary'];sp=Path(sr['path']);assert sp.is_relative_to(b) and sha(sp)==sr['sha256'] and sp.stat().st_size==sr['bytes']<=2097152;sv=load(sp);assert sv['status']=='COMPLETED_TYPED_LIFECYCLE_NO_PHYSICAL_CREDIT' and sv['physical_case_id']==case['physical_case_id'];src=sv['source'];assert src['current336_sha256']=='df7ea3229efed933aab1e1219823b151218427cb22c024a70b12f9513304c62b'==sha(Path(src['current336_path']));assert src['scientific_scan_sha256']==case['scan']['sha256']==sha(Path(src['scientific_scan_path']));z=src['trajectory_h5'];assert z['path']==case['trajectory_h5']['path'] and z['known_sha256']==z['pre_sha256']==z['post_sha256']==case['trajectory_h5']['sha256'];assert z['pre_stat']==z['post_stat'];h=Path(z['path']);st=h.stat();actual={'path':str(h),'bytes':st.st_size,'mtime_ns':st.st_mtime_ns,'ctime_ns':st.st_ctime_ns,'st_dev':st.st_dev,'st_ino':st.st_ino};assert actual==z['pre_stat'];assert cr['h5_pre_post_sha256_equal'] is True
 t=sv['timeline'];assert t['frames']==case['frames'] and t['particles']==case['particles'];ts=t['time_s'];assert len(ts)==t['frames'] and all(math.isfinite(x) for x in ts) and all(a<c for a,c in zip(ts,ts[1:]));roles=sv['role_ledgers'];assert set(roles)=={'fixed','moving','floating','fluid'} and sum(z['initial_count'] for z in roles.values())==t['particles']
 for z in roles.values():
  assert len(z['active_count_by_frame'])==len(z['active_mass_kg_by_frame'])==t['frames'];assert all(isinstance(x,int) and 0<=x<=z['initial_count'] for x in z['active_count_by_frame']);assert all(math.isfinite(x) and x>=0 for x in z['active_mass_kg_by_frame'])
 rec=sv['records'];rr=Path(rec['path']);rst=rr.stat();assert rr.is_relative_to(b) and rst.st_size==rec['bytes']==cr['output_records']['bytes']<=536870912;assert rec['sha256']==cr['output_records']['sha256'] and rec['rows']==t['particles']==cr['output_records']['rows'];assert sv['scientific_qualification']=={'QI':'UNKNOWN','QN':'UNKNOWN','QE':'UNKNOWN'}
 verified.append({'physical_case_id':case['physical_case_id'],'family_id':family,'status':'VERIFIED_SAVED_MASK_DIAGNOSTIC_ONLY','case_manifest':case['case_manifest'],'case_manifest_sha256':case['case_manifest_sha256'],'receipt':str(rp),'receipt_sha256':sha(rp),'summary':str(sp),'summary_sha256':sha(sp),'source_trajectory':src['trajectory_h5'],'source_H5_prepost_known_SHA_and_current_stat_equal':True,'records_stat_only':{**rec,'mtime_ns':rst.st_mtime_ns,'ctime_ns':rst.st_ctime_ns,'st_dev':rst.st_dev,'st_ino':rst.st_ino},'actual_timeline':t,'actual_role_ledgers':roles,'metadata':sv['metadata'],'source_read_cost':sv['source_read_cost'],'scientific_qualification':sv['scientific_qualification'],'native_cause_fate_legal_flux_dynamics':'UNKNOWN'})
assert len(verified)==v['counts']['completed'] and len(failed)==v['counts']['failed'];p.update(status=f'VERIFIED_ACTUAL_{family}_TYPED_LIFECYCLE_BATCH_SAVED_MASK_DIAGNOSTICS_NO_PHYSICAL_CREDIT',report=str(vp),report_sha256=sha(vp),batch_summary=str(vp),batch_summary_sha256=sha(vp),manifest=str(mp),manifest_sha256=sha(mp),counts=v['counts'],case_verifications=verified,failed_cases=failed,H5_or_large_records_content_read_by_root=False,known_source_read_passes_minimum=3,original_CURRENT118_cases_complete=False,scientific_qualification={'QI':'UNKNOWN','QN':'UNKNOWN','QE':'UNKNOWN'},next='Exact non-overlap CURRENT continuation batches and separate native-cause/fate evidence; failures retain new-attempt recovery')
footer=(Path(__file__).parent/'root_cpu_verification_footer.py').read_text().replace('1073741824',str(q['max_memory_bytes'])).replace('F7_S1_SOURCE_SUPPORT_ACTUAL_SCOPE_ROOT_VERIFICATION_137.json',f'TYPED_LIFECYCLE_BATCH_{family}_ACTUAL_ROOT_VERIFICATION_{num}.json');exec(footer,globals())
