from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_109_f7_a049p5_a050p5_visual_review_v1';O=H/'root_stage1_F7_delegated109_A049P5_A050P5_actual601_visual_integration_913';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
commit=subprocess.check_output(['git','rev-parse','cf24090d'],cwd=W,text=True).strip();names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines();assert names;adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert p.read_bytes()==b;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==b;dst.write_bytes(b);adopted.append(ref(dst))
P=R/S.relative_to(W);sp=P/'metadata/fresh109-visual-review.json';d=load(sp);assert d['model_profile']=='gpt-5.6-luna/max';prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_119.json')['accepted_decisions'];assert len(prior)==193;ids={load(p).get('physical_case_id',load(p)['case_id']) for p in prior};digests={load(p)['physical_condition_sha256'] for p in prior};auditp=next(H.glob('root*_909'))/'actual-delivery-and-completion-audit.json';stock={x['case_id']:x for x in load(auditp)['cases']};decisions=[]
for c in d['cases']:
 cid=c['case_id'];assert cid in ['F7_OBSTACLE_QUINTIC_B08_A049P5','F7_OBSTACLE_QUINTIC_B08_A050P5'] and cid not in ids;dc=load(P/(cid+'-delegated-visual-decision.json'));assert dc['decision_status']=='visual-approved-by-delegated-agent' and dc['agent_personally_viewed_all_contact_sheets_and_keyframes'] and dc['main_personally_viewed_pngs'] is False;v=c['render_evidence'];assert v['reviewed_all_contact_sheets'] and v['reviewed_all_event_keyframes'] and len(v['contact_sheets'])==26 and len(v['event_keyframes'])==10
 for x in v['contact_sheets']+v['event_keyframes']:assert sha(x['path'])==x['sha256']
 f=stock[cid];ev=f['actual_completed_receipts'];assert not f['visual_accepted']
 for x in ev.values():assert sha(x['path'])==x['sha256'] and (load(x['path'])['status'],load(x['path'])['returncode'])==('completed',0)
 for k in ['typed_report','xmf_manifest','render_report','paraview_open_file']:assert sha(f[k]['path'])==f[k]['sha256']
 t,m,a=[load(f[k]['path']) for k in ['typed_report','xmf_manifest','render_report']];sc=c['scope_separation'];src=c['source_inputs'];own=load(src['corrected_converter_owner']['path']);old=load(src['original_owner']['path']);actual=hashlib.sha256(json.dumps(own['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert actual==f['physical_condition_sha256']==sc['actual_converter_scope_sha256']==t['hash_scopes']['physical_condition_sha256']==m['physical_condition_sha256']==m['canonical_physical_binding_sha256'] and actual not in digests
 for key in ['original_owner','corrected_converter_owner','source_definition','selected_motion_module_attested']:assert sha(src[key]['path'])==src[key]['sha256']
 assert src['corrected_converter_owner']['sha256']==sc['actual_converter_owner_sha256']==m['actual_provenance_owner_sha256'];plan=src['source_plan'];assert sha(plan['path'])==plan['sha256_actual_file']==plan['sha256_historical_owner_field']==sc['source_plan_sha256_recorded']==sc['source_plan_sha256_actual_file'];assert len(plan['sha256_actual_file'])==64 and plan['erratum'] is None;assert sc['source_plan_condition_sha256']==sc['original_owner_physical_condition_sha256']==old['physical_condition_sha256']==m['source_plan_condition_sha256'];assert sc['original_owner_canonical_physical_binding_sha256']==old['canonical_physical_binding_sha256'];assert c['half_degree_amplitude']==f['amplitude_deg']==own['physical_binding']['parameters']['amplitude_deg']
 pc=c['producer_chain'];assert pc['all_stage_receipts_completed_zero']
 for k in ['gencase_prepared_report','generated_xml','generated_definition','native_initial_qa_report','typed_conversion_report','xmf_manifest','xmf','render_report']:
  x=pc[k];assert sha(x['path'])==x['sha256']
 qa=load(m['initial_qa_report']);assert sha(m['initial_qa_report'])==m['initial_qa_report_sha256'];qc=next(x for x in qa['cases'] if x['case_id']==cid);assert qc['passed'] and qc['native_particles']==70179 and {k:x['count'] for k,x in qc['checks']['native_type_mk_blocks'].items()}=={'fixed':27495,'moving':1984,'fluid':40700};assert all(qc['checks'][k] for k in ['actual_3d','all_13_fields_finite','no_initial_overlap','uid_exact_sorted_unique','xml_contract']);assert qc['physical_condition_sha256']==sc['source_plan_condition_sha256'] and qc['canonical_physical_binding_sha256']==sc['original_owner_canonical_physical_binding_sha256']
 out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F7','case_id':cid,'physical_case_id':cid,'physical_condition_sha256':actual,'source_review_commit':commit,'source_review':ref(sp),'visual_reviewer':'/root/production_recovery','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['visual_observations'],'visual_limitations':'Sparse out-of-envelope blue points preserved in open-top geometry; strict containment and individual exit routes unqualified. Native interpolation piecewise-linear, no native C2 claim.','scope_separation':{**sc,'canonical_owner':src['corrected_converter_owner'],'legacy_source_owner':src['original_owner'],'actual_batch_plan':{'path':plan['path'],'sha256':plan['sha256_actual_file']},'canonical_recomputed_from_metadata_only':True,'new074_batch_has_no_63_character_digest_erratum':True},'actual_completed_metadata_evidence':{**ev,'initial_qa_report':ref(m['initial_qa_report'])},'independent_full_pipeline_audit':ref(auditp),'verified_PNG_hashes':{'contact_sheets':v['contact_sheets'],'key_frames':v['event_keyframes']},'actual_frames':601,'actual_particles':70179,'actual_fluid_particles':40700,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'native_control_interpolation':'piecewise linear; no native C2 claim','source_control':{'actual_bound_parameters':own['physical_binding']['parameters']},'scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':193+len(decisions),'resulting_count':194+len(decisions)};dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);decisions.append(str(dp));ids.add(cid);digests.add(actual)
assert len(decisions)==2;put(O/'actual-integration-review.json',{'source_commit':commit,'source_adopted_byte_exact':True,'adopted_files':adopted,'previous_count':193,'resulting_count':195,'independent_case_increment':2,'decisions':decisions,'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'new_cases':2,'accepted':195}))
