from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os,math,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_296.json';cp=load(cpfile);assert cp['checkpoint']==296 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==319
qip=root(1392)/'actual1009-full401-own-QI-UID-N3-native-typed-role-thirtyfive-fluid-omissions-previsual-proof.json';qi=load(qip);assert sha(qip)=='486e2a2446d4e0ccc7785d966cd4f0dea016691efadd33ce244f943bb62a71a0' and qi['all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified'];er=qi['actual_completed_metadata_evidence']
for e in er.values():assert sha(e['path'])==e['sha256']
r=load(er['render_receipt']['path']);pub=load(er['render_publish_receipt']['path']);assert r['status']=='completed' and r['returncode']==0 and pub['status']=='published_after_atomic_rename' and pub['report_sha256_after_rebind']==er['render_report']['sha256']
F=root(1158);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre);refs={k:e for k,e in j.items() if isinstance(e,dict) and 'path' in e and 'sha256' in e}
for e in refs.values():assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);native_ref=t['source_provenance']['solver_receipt'];assert sha(native_ref['path'])==native_ref['sha256'];n=load(native_ref['path']);nq=n['request'];bedr=load(j['actual_bed_receipt']['path']);b=load(bedr['request']['binding']);bed=load(j['actual_bed_report']['path']);refs['actual_native_receipt']=native_ref;refs['actual_bed_binding']=ref(bedr['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert (canonical,legacy,sd)==('1a04363bffefde127740d3da87de48ba66db566b7ae0cdf44d6c6f4b73137cf3','80039c17cc7a088b7bc0fdc5c7a74d9051aa72763652261e2823635fcd5ad93d','6c74924feda21861f0a15d1259871f3a536ae2a2264acc4047a60caee1b5d451')
mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]}
for m in mask.values():assert m=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}}
source_def=ref(b['source_definition']);assert source_def['sha256']==b['source_definition_sha256']==sd==bed['source_plan_physical_condition_sha256'];plan=ref(b['source_plan_file']);assert plan['sha256']==b['source_plan_file_sha256'] and len({canonical,legacy,sd,plan['sha256']})==4
for rr in [n,bedr]:assert rr['input_hashes_at_launch'][plan['path']]==rr['input_hashes_after_run'][plan['path']]==plan['sha256']
q=load(F/'enabled-full801-render-request.json');w=load(F/'enabled-render-wrapper.json');cid=q['case_id'];pid=q['physical_case_id'];assert pid=='F5_COMPACT_RUNUP_RECOVERY_C082S1_M101_T100' and cid=='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M101_T100_NEXT34'
for k,bkey in [('gencase_receipt','gencase_receipt'),('initial_qa_receipt','initial_qa_receipt'),('initial_qa_report','initial_qa_report'),('generated_xml','canonical_generated_xml')]:
 e=ref(b[bkey]);assert e['sha256']==b[bkey+'_sha256'];refs[k]=e
for k in ['gencase_receipt','initial_qa_receipt','actual_native_receipt','actual_typed_receipt','actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
qa=load(refs['initial_qa_report']['path']);assert qa['all_basic_placement_checks_pass'] and all(qa['checks'].values()) and not qa['numerical_precision_result_accepted'];assert t['source_provenance']['gencase_receipt']==refs['gencase_receipt'] and t['source_provenance']['generated_xml']==refs['generated_xml']
assert w['expected_frames']==t['frames']==x['frames']==len(bed['frame_reports'])==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
assert t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected' and t['partvtk_validation']['all_passed'];assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[801,194427,3]
fs=t['lifecycle']['frame_summary'];times=x['actual_time_s'];xp=Path(x['xdmf']);refs['XMF_XML']=ref(xp);assert refs['XMF_XML']['sha256']==x['xdmf_sha256'];grids=ET.parse(xp).findall('.//Grid[@GridType="Uniform"]');assert len(fs)==len(times)==len(grids)==801 and times==[f['time'] for f in fs]==[f['time_s'] for f in bed['frame_reports']]==[float(g.find('Time').get('Value')) for g in grids];assert [times[0],times[-1]]==[0,16.00015600764587] and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
for i,(f,bf,g) in enumerate(zip(fs,bed['frame_reports'],grids)):
 assert f['frame']==bf['frame']==i and f['active_particles']==194427 and f['missing_particles']==0 and f['type_counts']=={'0':158559,'1':4210,'2':0,'3':31658}
 assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='194427 3';v=next(z for z in g.findall('Attribute') if z.get('Name')=='velocity');assert v.get('AttributeType')=='Vector' and v.find('DataItem').get('Dimensions')=='194427 3'
 assert bf['initial_fluid_uid_count']==bf['current_valid_type3_fluid_count']==bf['finite_mass_current_fluid_count']==bf['finite_position_current_fluid_count']==31658 and bf['uid_tracking']['missing_initial_uid']['count']==bf['uid_tracking']['unexpected_current_uid']['count']==bf['nonfinite_mass_current_fluid_count']==bf['nonfinite_position_current_fluid_count']==0 and not bf['uid_tracking']['unexplained'];assert bf['bed_domain']['x_outside_exact_profile_domain_count']==bf['bed_domain']['y_outside_actual_bed_footprint_with_x_in_domain_count']==bf['penetration']['depth_unevaluable_current_fluid_count']==0
 for k,th in [('one_dp',.02),('two_dp',.04)]:assert bf['penetration'][k]['threshold_m']==th and bf['penetration'][k]['count']==0 and bf['penetration'][k]['deepest_depth_m'] is None
h5=t['output_hdf5'];assert t['output_sha256']==x['source_h5_sha256']
for k in ['actual_XMF_receipt','actual_bed_receipt']:
 rr=load(refs[k]['path']);assert rr['input_hashes_at_launch'][h5]==rr['input_hashes_after_run'][h5]==t['output_sha256']
pp=Path('/proc/682554');obs=None
if pp.exists():
 st=(pp/'stat').read_text().rsplit(')',1)[1].split();args=(pp/'cmdline').read_bytes().split(b'\0');assert st[19]=='214459220' and str(F/'enabled-full801-render-request.json').encode() in args;obs={'registered_launch_pid':682554,'startticks':'214459220','state':st[0],'original_request_bound_to_actual_cmdline':True,'no_restart':True}
assert obs is not None or (F/'controller-result.json').exists()
for key,p in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(a['kind'] for a in ld['attempts']);gpu=sum(a.get('gpu_seconds',0) for a in ld['charges'])/3600;cpu=sum(a.get('cpu_core_seconds',0) for a in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current319_F2_original1009_own1392_published_nextF5_original1158_full801_UID_bed_native_XMF_canonical_SourceDefFILE_durable1397_1396';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_297.json';assert not O.exists() and not np.exists() and not list(H.glob('root*_1397'));O.mkdir();entry=O/'after_original1158_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1158-full801-own-QI1397.py').read_bytes());compile(entry.read_text(),str(entry),'exec');proof=O/'current319-actual1009-own401QI-next1158-true-full801-bed-namespace-durableQI-readiness.json'
put(proof,{'schema':'ds02.current319-ownF2-nextF5-durable801QI.v1','at_utc':now.isoformat(),'actual_completed_published_F2_ownQI1392':ref(qip),'F2_personal_review_source183_pending_no_newcredit':True,'next_original1158_upstream_primary_refs':refs,'prior_previsual_proof':ref(pre),'case_id':cid,'physical_case_id':pid,'canonical_native':canonical,'typed_legacy':legacy,'bed_SourceDef_FILE':source_def,'source_plan_JSON_FILE':plan,'actual_native_XMF_plan_field_namespaces':mask,'native_and_XMF_physical_plan_canonical_not_SourceDef':True,'source_plan_JSON_launch_after_native_and_bed_verified':True,'genuine_GenCase_initialQA_completed0_and_basicplacement_pass':True,'initialQA_precision_negative_retained':qa['numerical_precision'],'full801_typed_UID_type_N3_exact_times_and_bed_UID_footprint_bins_verified':True,'render_finite_states_await_actual_complete_publication_and_own1397':True,'actual_time_window_s':[times[0],times[-1]],'same_original_launch_current_live':obs,'actual_terminal':ref(F/'controller-result.json') if (F/'controller-result.json').exists() else None,'future_ownQI1397_UNEXECUTED_SHA_unknown':True,'durable_entry':ref(entry),'command':['python3','-B',str(entry),'1158','1397'],'case_credit':0,'scientific_payload_IO':False,'PNG_payload_IO':False,'new_jobs':0})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=297,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: preceding turn F2source216/F3source181 accepted reaching319, actualF2original1009 own1392 completed0/pub; this turn nextF5original1158 actualfull801 upstream UID/N3/native-XMF exacttimes/bed footprint diagnostics/realQA/canonical-vs-legacy-SourceDef-planJSON checked, same registeredlaunch682554/start214459220 live and durable futureown1397 prepared.',authorized_work_state='Active319/336 pending17. Source183 F2original1009 personal visual queued after source182 F5original1158 metadata preflight; own1392 completed/published. Source196 F3 and218 F5 final gates repair active; next197 F2 repair planned. Original1158 same registeredlaunch continues, futureown1397 unexecuted. Source217 uncreated pending assignment superseded bysource183.')
new['actual_progress']['actual1009_completed_full401_ownQI']=ref(qip);new['actual_progress']['next_original1158_durable_full801_QI']=ref(proof);new['source_agents']['production_recovery']='fresh182 F5actual1158 metadata-only preflight thenfresh183 F2actual1009 personal17contacts9keys after own1392';new['next_executable_tasks'].insert(0,'After original1158 actual completed0/publication execute Root1396 durable own1397 once then delegate personal34contacts9keys, preserving M101 actualnative/XMF physicalcanonical and separate bedSourceDefFILE/planJSON. Adopt source183 F2actual1009 personal review after source commit/readonlyvalidator/own1392/pubPNG closure.');put(np,new)
ip=root(1395)/'full336-current319-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);row=next(z for z in idx['cases'] if z['physical_case_id']==qi['physical_case_id']);assert not row.get('accepted_decision');row.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=ref(qip),current_actual_render_receipt=er['render_receipt'],current_atomic_publish_receipt=er['render_publish_receipt'],current_personal_review_source=183,case_credit=0,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[qi['physical_case_id']],next_original1158_durable_full801_QI=ref(proof));assert len(idx['cases'])==336 and sum(bool(z.get('accepted_decision')) for z in idx['cases'])==319;put(O/'full336-current319-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: prepare M101 T100 full801 integrity with actual bed and native XMF roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':297,'accepted':319,'next_original1158_live':obs,'future1397_unexecuted':True,'proof':ref(proof),'free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
