from pathlib import Path
import json,hashlib,subprocess,datetime,copy,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n}'));load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.log','.txt','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
commit='eba68f926ce4fae030f1eb2b27ab2d6f7d976060';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_176_f2_rx061_rot075_actual1142_personal_visual_acceptance_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={}
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;assert not (R/n).exists() or (R/n).read_bytes()==b;blobs[n]=b
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh176.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
v=load(P/'metadata/personal-visual-decision.json');png=load(P/'metadata/png-evidence.json');chain=load(P/'metadata/chain-closure.json');c=v['case'];cid=c['case_id'];pid=c['physical_case_id'];canonical=c['canonical_native_physical_condition_sha256'];legacy=c['typed_render_legacy_actual_converter_scope_sha256'];qp=root(1265)/'actual1142-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qp);assert v['family_id']=='F6' and v['actual_case_family']=='F2' and c['assigned_family']=='F6' and c['actual_physical_family']=='F2' and v['model']=='gpt-5.6-luna' and v['reasoning_effort']=='max' and not v['recursive_delegation'];assert qi['case_id']==chain['case_id']==cid and qi['physical_case_id']==chain['physical_case_id']==pid
assert canonical==qi['canonical_actual_native_request_condition_sha256']==chain['canonical_native_scope_sha256'] and legacy==qi['actual_converter_legacy_scope_sha256']==chain['typed_render_legacy_scope_sha256'] and canonical!=legacy and not c['scope_roles']['equality_claimed'];assert v['decision']['status']=='visual-approved-by-delegated-agent' and v['decision']['case_credit']==0 and not any(v['decision'][k] for k in ['global_acceptance','q_n_granted','q_e_granted','visual_zero_fluid_loss_claim','strict_container_guarantee'])
for e in v['evidence'].values():assert sha(e['path'])==e['sha256'] and Path(e['path']).stat().st_size==e['bytes']
assert v['evidence']==chain['evidence'] and v['evidence']['main_qi_proof']['path']==str(qp) and v['evidence']['main_qi_proof']['sha256']==sha(qp)
stage=qi['actual_completed_metadata_evidence'];mapkeys={'genuine_gencase':'gencase_receipt','initial_native_qa':'initial_qa_receipt','full_native_solver':'native_receipt','typed_conversion':'typed_receipt','n3_xmf':'xmf_receipt','full_render_root1142':'render_receipt'}
for key,sourcekey in mapkeys.items():
 e=stage[key]['receipt'];assert e['path']==v['evidence'][sourcekey]['path'] and e['sha256']==v['evidence'][sourcekey]['sha256'];z=load(e['path']);assert (z['status'],z['returncode'])==('completed',0) and z['request']['case_id']==cid
assert qi['frames']==401 and qi['particles']==418104 and qi['all_actual_times_exact_typed_XMF_XML_render'] and qi['all_frames_geometry_velocity_N3_identity_and_finite_active_fields'] and qi['stage1_QI_full_native_identity_and_state_verified'];life=v['lifecycle_and_render_metadata'];ql=qi['lifecycle'];assert life['final_missing_particles']==ql['final_missing_particles']==ql['max_missing_per_frame']==39 and life['first_missing_frame']==ql['first_missing_frame']==137 and life['transient_missing_frame_count']==ql['frames_with_any_missing_particle']==264 and life['particle_frame_omission_events']==ql['cumulative_particle_frame_omissions']==8748 and life['final_missing_id_sample_count']==len(ql['final_missing_id_first_producer_attested'])==8 and life['final_missing_ids_sample_not_complete'] and life['missing_locations_states_and_causes_unknown'];assert life['fluid_missing_fraction_of_initial_fluid']['numerator']==39 and life['fluid_missing_fraction_of_initial_fluid']['denominator']==21114
assert c['time_recipe']['producer_time_window_s']==life['actual_time_window_s']==qi['actual_time_window_s'];assert all(v['observations'][k] for k in ['initial_state','release_and_impact','mid_event','late_event','visual_failure_screen','visual_limit'])
pub=load(v['evidence']['publish_receipt']['path']);render=load(v['evidence']['render_report']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==v['evidence']['render_report']['sha256'];published={e['relative_path']:e for e in pub['files_excluding_receipt']};out=Path(pub['published_output_root']);contacts=[e for e in png['items'] if 'sheet_index' in e];keys=[e for e in png['items'] if 'frame' in e];assert len(png['items'])==26 and [e['sheet_index'] for e in contacts]==list(range(17)) and [e['frame'] for e in keys]==list(range(0,401,50)) and png['personally_viewed_with']=='view_image';assert [e['path'] for e in contacts]==render['outputs']['contact_sheets']
for e in png['items']:
 relative=str(Path(e['path']).relative_to(out));pe=published[relative];assert sha(e['path'])==e['sha256']==pe['sha256'] and Path(e['path']).stat().st_size==e['bytes']==pe['bytes']
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_224.json';cp=load(cpfile);assert cp['checkpoint']==224 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==284 and cp['accepted_per_family']['F2']==36;old=[load(p) for p in cp['accepted_decisions']];assert pid not in {r.get('physical_case_id',r['case_id']) for r in old};idxp=root(1267)/'full336-current284-actual-final48-delivery-progress-index.json';idx=load(idxp);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical
for row in idx['cases']:
 if row.get('accepted_decision'):assert row.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(v['created_at_utc'])<=now;raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and free>=500
O=H/'root_stage1_source176_assignedF6_actualF2_RX061ROT075_actual1142_full401QI_personal26PNG_quantified39fluid_visual_acceptance_1268';nextcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_225.json';assert not list(H.glob('root*_1268')) and not nextcp.exists();O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'source176-byte-exact-readonly-validation.json';put(vp,{'source_commit':commit,'adopted_source_files':adopted,'source_SHA_before_after':before,'source_bytes_unchanged':True,'validator_returncode':rv.returncode,'stdout':rv.stdout,'stderr':rv.stderr})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_assigned_agent_family':'F6','source_family_id_F6_is_assignment_not_actual_case_family':True,'source_review_commit':commit,'source_visual_review':ref(P/'metadata/personal-visual-decision.json'),'source_review_closure':ref(P/'metadata/chain-closure.json'),'source_review_PNG_evidence':ref(P/'metadata/png-evidence.json'),'independent_full401_QI_proof':ref(qp),'actual_completed_metadata_evidence':stage,'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'lifecycle':ql,'final_UID_sample_count_not_full39':8,'missing_UID_cause_location_state_unknown_preserved':True,'legacy_alias_control_fields_not_promoted_to_actual_native_ROT075_control':True,'native_and_XMF_plan_field_observations':{k:qi[k] for k in ['native_source_plan_field_present','native_source_plan_field_sha256','XMF_source_plan_field_present','XMF_source_plan_field_sha256']},'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':v['observations'],'personal_visual_failure_screen':v['observations']['visual_failure_screen'],'contact_sheets':contacts,'keyframes':keys,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'all26_PNG_hashes_match_actual_publish':True,'no_zero_fluid_loss_or_strict_container_claim':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
proof=O/'source176-actual1142-full401-QI-and-personal-visual-adoption.json';put(proof,{'source_commit':commit,'source_validator':ref(vp),'source_original_bytes_preserved':True,'independent_QI':ref(qp),'new_visual_decision':ref(dp),'actual_missing39fluid_and8748_events_unknowns_retained':True,'eight_sample_UIDs_not_complete39':True,'actual26PNG_bound_to_atomic_publish':True,'source_assignment_family_F6_vs_actual_F2_preserved':True,'new_case_credit':1,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);newcp=copy.deepcopy(cp);newcp['accepted_per_family']['F2']+=1;newcp.update(checkpoint=225,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=285,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: accepted F2RX061ROT075 actual1142 full401 with mainQI1265 and fresh176 personal17contacts9keys; actual39UID/137first/264frames/8748events and8sample IDs retained, no numericgrant. Original1065RX056ROT075 now completed0 with ownfull401QI1266, awaiting fresh162. Original1046 F3P0800AY0640 newly admitted and assigned fresh177; original1154 F2RX061ROT105 continues fresh200.',authorized_work_state='Active285/336 F2=37,F3=38,F5=19,F6=47,F1/F4/F7=48;51 cases remain. Actual1065full401 QI complete pending personalreview. Existingrender queue active samehandles cap2; Homefloor500GiB protected.');assert len(newcp['accepted_decisions'])==sum(newcp['accepted_per_family'].values())==285;newcp['actual_progress']['source176_F2_actual1142_full401_visual_acceptance']=ref(proof);newcp['actual_progress']['F2_actual1065_full401_previsual_QI']=ref(root(1266)/'actual1065-full401-independent-UID-N3-time-scope-QI-proof.json');newcp['source_agents']['f6_endpoint_initial_qa']='fresh176 accepted285/F2=37; fresh177 actualF3P0800AY0640 original1046';newcp['source_agents']['production_recovery']='fresh162 actualF2RX056ROT075 original1065 published0 mainQI1266, personalreview pending';newcp['source_agents']['f5_bed_recovery']='fresh200 assignedF5 actualF2RX061ROT105 original1154 samehandle';newcp['next_executable_tasks']=['Adopt fresh162 actualF2RX056ROT075 original1065 personal17contacts9keys with mainQI1266.','After original1154 publication, main ownfull401QI and fresh200 assignedF5 actualF2RX061ROT105 personal17contacts9keys.','After original1046 publication, main ownfull836QI and fresh177 assignedF6 actualF3P0800AY0640 personal35contacts9keys.','Continue same original remainingrender controllers, globalcap2/CPU24, finalF6original951 awaiting capacity; F5 actualfirst24 prefix19 growing.'];put(nextcp,newcp)
idx['previous_index_preserved']=ref(idxp);idx['source_authoritative_checkpoint']=ref(nextcp);idx['at_utc']=now.isoformat();idx['accepted_independent_physical_cases']=285;idx['registered_pending_independent_physical_cases']=51;idx['new_case_credit']=1;targets[0].update(status='visual-approved-in-checkpoint225',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qp));idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx['actual_unaccepted_completed0_published_physical_cases'] if (x.get('physical_case_id') if isinstance(x,dict) else x)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==285;put(O/'full336-current285-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(nextcp.relative_to(R)),str((root(1142)/'controller-result.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F2 rx061 rot075 full401 with39 quantified fluid omissions','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':285,'F2':37,'checkpoint':225,'remaining':51,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
