from pathlib import Path
import json,hashlib,datetime,shutil,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text())
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def ref(p):
 p=Path(p);assert p.suffix in {'.json','.jsonl','.py','.md','.xml','.txt','.log'};return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
old=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_138.json';cp=load(old);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==211
O=H/'root_stage1_actual211_F5_visual_XMF993_F2_floor_recovery995_full_native_census_scoped_checkpoint_996';O.mkdir(exist_ok=False);rows=[];paths=[]
for n in [948,951,972,977,978,981,983,984,987,988,990,991,993,995]:
 f=root(n);lp=f/'controller-launch-process.json';j=load(lp);ps=Path(f"/proc/{j['pid']}/stat");s=ps.read_text().split(') ',1)[1].split() if ps.exists() else [];live=bool(s and s[0]!='Z' and s[19]==j['proc_start_ticks']);z={'root_number':n,'launch_process':ref(lp),'controller_pid':j['pid'],'proc_start_ticks':j['proc_start_ticks'],'same_PID_start_live':live}
 cfg=load(f/'controller-config.json');qs=cfg.get('requests',cfg.get('outer_requests',[cfg.get('request')]))
 for name in ['actual-progress.json','controller-result.json']:
  p=f/name
  if p.exists():
   raw=p.read_bytes();snap=O/f'actual{n}-{name}-immutable-snapshot.json';snap.write_bytes(raw);a=json.loads(raw);z[name]=ref(snap)
   if name=='actual-progress.json':z.update(actual_completed0=sum(x.get('status')=='completed' and x.get('returncode')==0 for x in a.get('results',[])),not_submitted=a.get('not_submitted',a.get('pending_not_submitted')))
   else:z['terminal_controller_result']=a
 active=[]
 for qp in qs:
  if not qp:continue
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json'
  if not rp.exists():continue
  a=load(rp)
  if a['status'] in ['running','reserved']:
   pid=a.get('pid');pstat=Path(f'/proc/{pid}/stat') if pid else None;st=pstat.read_text().split(') ',1)[1].split() if pstat and pstat.exists() else []
   entry={'request':str(qp),'receipt_path':str(rp),'status':a['status'],'producer_pid':pid,'producer_proc_stat_observed':bool(st and st[0]!='Z')}
   if st:entry['producer_proc_start_ticks_observed']=st[19]
   active.append(entry)
 z['observed_actual_active_science_receipts']=active;rows.append(z)
 if n in [995]:paths.append(str(lp.relative_to(R)))
free=shutil.disk_usage('/home/jade').free/1024**3;assert free>=500
for source_name in ['ds02-f2-unaccepted-full-native-observation.json','ds02-f2-unaccepted21-stage-receipt-observation.json']:
 raw=Path('/tmp',source_name).read_bytes();(O/source_name).write_bytes(raw)
report=O/'actual-progress-and-next-actions.json';put(report,{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'accepted':211,'accepted_per_family':cp['accepted_per_family'],'live_verified_handles_and_actual_terminal_statuses':rows,'Home_free_GiB':free,'Home_floor_GiB':500,'actual_failed_unused_cleanup14_reclaimed_GiB':439.00610971078277,'cleanup_independent_review':ref(root(966)/'actual-cleanup-independent-review.json'),'delegated137_two_F6_visual_integrated_F5_bed_pending':ref(root(989)/'adoption-and-two-case-independent-review.json'),'source16612_F5_actual_native0_typed_registered':ref(root(988)/'source166-adoption-and-primary-12case-metadata-review.json'),'source125_two_F3_actual_typed0_XMF_registered':ref(root(990)/'source125-adoption-two-actual978-independent-QI-review.json'),'actual981_decoder_wrong_path_failure_and_grounded991_repair1':ref(root(991)/'actual981-failure-and-grounded974-decoder-CLI-repair.json'),'source125_original_binding_snapshot_sha_failure_grounded_sidecar_rebind':ref(root(990)/'actual-source125-AY0320-stale-snapshot-binding-failure-and-grounded-rebind.json'),'F5_M085T090_existing832_bed_delegated137_visual_integrated211':ref(root(994)/'actual832-all801-bed-and137-visual-independent-closure.json'),'F5_three_actual983_full801_XMF993_registered':ref(root(993)/'three-actual983-full801-independent-QI-and-XMF-registration.json'),'F2_original_HOME_floor_failure_recovery995':ref(root(995)/'actual816-HOME-floor-failure-and-cleanup-recovery.json'),'F2_first_recovery_registered':ref(root(995)/'single-actual812-native-independent-recovery-registration.json'),'F2_remaining21_actual_full401_native0_observation':ref(O/'ds02-f2-unaccepted-full-native-observation.json'),'F2_remaining20_typed_metadata_materialization_needed_after995':True,'scientific_payload_IO_by_primary':False,'main_personal_PNG_review':False,'numeric_precision_certified':0,'case_credit_from_job_registration_or_scoped_repair':0,'next_executable_tasks':['Close first actual983 F5 M086T095 full801 typed0 and register original104 XMF then true all801 bed audit, full801 renderer, delegated visual.','Observe actual990 two full836 XMF producers; only actual0 manifest may feed original116023 full836 render.','Adopt fresh126 actual978 AY0390 typed0 handoff and complete F3 full48 authoritative assets census.','Adopt fresh167 remaining F5 true native-ready metadata; prioritize fresh168 M085T090 existing exact bed0 evidence or original138 audit binding for pending visual137 case.','Integrate fresh138 next bounded completed personal visuals independently; retain all genuine failed/precision-negative evidence and omission limitations.','Continue same live conversion/render process handles, shared CPU928 serial1 and render cap2; never restart solely from observation timeout.']})
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);ls=O/'resource-ledger-at-checkpoint-immutable-snapshot.json';ls.write_bytes(raw)
cp.update(checkpoint=139,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(old),predecessor_sha256=ref(old)['sha256'],home_free_gib=free,new_accepted_decisions=[],ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ls),active_reservations=ledger['reservations'],attempt_counts={k:sum(z['kind']==k for z in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(z.get('gpu_seconds',0) for z in ledger['charges'])/3600,cpu_core_hours_charged=sum(z.get('cpu_core_seconds',0) for z in ledger['charges'])/3600,previous_goal_turn_classification='Progress: three actual983 full801 F5 typed0 independently closed, unchanged legacy-aware129 XMF993 registered/launched. Reused exact existing832 all801 bed audit and delegated137 full801 personal visual to accept211. Authoritative metadata found21 missing F2full401 conversions allnative812completed0; original816 blocked by realHomefloorfailure, preservefailure and registerlaunch995 first capped typed157 successor while remaining20 metadata handoff delegated. Fresh1383visual and1263typeddownstream sources are ready for independent adoption.')
cp['actual_progress']['current996_full211_live_handles_F2_recovery_and_storage']=ref(report);cp['next_executable_tasks']=load(old)['next_executable_tasks']+['After delegated139 visual, adopt140 bounded remaining20 true F2 native0 typed157 regular-file-only metadata handoff; exclude already registered995RX049ROT075.'];cp['source_agents'].update(f5_bed_recovery='fresh167remaining5actualnative0 ready pending main adoption; fresh168 exact832bed adopted and F5M085T090 accepted211 with137personalvisual; fresh169full48Mother+NEXT34 census and actual993bed handoff active',production_recovery='fresh126true3typed0 originalXMF handoff ready039004300570; full48sourcecensus47dirs+missingP1000AY0500 recorded; fresh127 exactmotheralias/case identity recheck and nexttrue3typed0 handoff active',f6_endpoint_initial_qa='fresh138 ready3 actual personal visual pending main independent adoption; fresh139 visual active, fresh140 bounded F2remaining20 true native0 typed157 metadata handoff queued')
checkpoint=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_139.json';assert not checkpoint.exists();put(checkpoint,cp);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes());paths.extend(str(p.relative_to(R)) for p in O.iterdir() if p.is_file());paths.append(str(checkpoint.relative_to(R)));subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: checkpoint211 actual F5 visual and F2 native asset recovery without duplicate simulations','--',*paths],cwd=R,check=True);print({'checkpoint':137,'accepted':211,'Home_free_GiB':free,'gpu_hours':cp['gpu_hours_charged'],'cpu_core_hours':cp['cpu_core_hours_charged'],'attempt_counts':cp['attempt_counts'],'handles':[(x['root_number'],x['same_PID_start_live'],x.get('actual_completed0')) for x in rows],'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
