from pathlib import Path
import json,hashlib,datetime,subprocess,copy,os,collections,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.xml','.xmf','.png','.py','.md'}
 if p.suffix.lower()=='.png':assert p.is_relative_to(D) and not p.is_symlink()
 return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def checked(e):
 assert sha(e['path'])==e['sha256']
 if 'bytes' in e:assert Path(e['path']).stat().st_size==e['bytes']
def put(p,j):
 with Path(p).open('x') as f:json.dump(j,f,ensure_ascii=False,indent=2);f.write('\n')
commit='7225e2b83ab25f0016787ce1a47e017f7fa61fa3';P=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003').glob('root_followup_184_*'));prefix=P.relative_to(W);names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();expected={'README.md','build_fresh184.py','validate_fresh184.py','package-manifest.json','metadata/actual1158-personal-visual-decision.json','metadata/png-evidence/actual1158.json'};assert {str(Path(n).relative_to(prefix)) for n in names}==expected
blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
man=load(P/'package-manifest.json');assert {e['path'] for e in man['files']}==expected-{'package-manifest.json'} and man['package_manifest_excluded_from_own_hash']
for e in man['files']:assert sha(P/e['path'])==e['sha256'] and (P/e['path']).stat().st_size==e['bytes']
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'validate_fresh184.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
qip=root(1397)/'actual1158-full801-independent-QI-UID-N3-bed-scope-previsual-proof.json';qi=load(qip);assert sha(qip)=='3749c247bcb282e93e73d659f557c067446685d0f79d7b72dbeffb89ef194ed1'
s=load(P/'metadata/actual1158-personal-visual-decision.json');png=load(P/'metadata/png-evidence/actual1158.json');cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert s['case_id']==png['case_id']==cid and s['physical_case_id']==png['physical_case_id']==pid and s['actual_case_family']=='F5' and s['assigned_worktree_family']=='F3'
assert s['configured_model']=='gpt-5.6-luna/max' and not s['model_substitution'] and not s['recursive_delegation'];checked(s['provenance']['qi_proof']);assert s['provenance']['qi_proof']['path']==str(qip)
er=qi['actual_completed_metadata_evidence']
for k,e in er.items():
 checked(e)
 if k.endswith('_receipt') and k!='render_publish_receipt':
  rr=load(e['path']);assert rr['schema']=='ds02.execution-receipt.v1' and rr['status']=='completed' and rr['returncode']==0 and rr['request']['case_id']==cid
for k,e in s['actual_chain'].items():
 checked(e)
 if k in er:assert e['path']==er[k]['path'] and e['sha256']==er[k]['sha256']
assert qi['all801_geometry_velocity_N3_times_UID_finite_verified'] and qi['all_native_UIDs_active_each_frame'] and qi['full_frames']==801 and qi['particles']==194427 and qi['all801_full_bed_UID_footprint_one_DP_two_DP_bins_checked']
dims=s['actual_dimensions'];assert dims['time_window_s']==qi['actual_time_window_s'] and dims['frames']==801 and dims['particles']==194427 and dims['initial_fluid_UIDs']==31658
nreceipt=load(er['native_receipt']['path']);nq=nreceipt['request'];x=load(er['xmf_manifest']['path']);masks={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',x)]};roles=s['physical_condition_roles'];assert masks==qi['actual_native_XMF_plan_field_namespaces']==roles['native_and_xmf_plan_fields'];assert nq['physical_condition_sha256']==canonical==roles['native_canonical_condition_sha256'] and x['physical_condition_sha256']==canonical==roles['xmf_physical_condition_sha256'] and legacy==roles['typed_legacy_converter_scope_sha256']==x['source_h5_physical_condition_sha256']
assert roles['bed_source_definition_sha256']==qi['actual_SourceDef']['sha256'] and roles['source_plan_file_sha256']=='366adc5200604490871116a0a5b8503c9bef4bfb1e72195df94995605fa7d324' and roles['xmf_actual_converter_legacy_scope_sha256'] is None and 'actual_converter_legacy_scope_sha256' not in x
br=load(er['bed_receipt']['path']);binding=load(br['request']['binding']);plan=ref(binding['source_plan_file']);assert plan['sha256']==binding['source_plan_file_sha256']==roles['source_plan_file_sha256'] and len({canonical,legacy,qi['actual_SourceDef']['sha256'],plan['sha256']})==4
for rr in [nreceipt,br]:assert rr['input_hashes_at_launch'][plan['path']]==rr['input_hashes_after_run'][plan['path']]==plan['sha256']
assert s['precision_and_limits']['actual_initial_QA_precision_negative']==qi['actual_initial_QA_precision_negative'] and s['precision_and_limits']['historical_negative_flags']==qi['historical_negative_flags']
visual=s['visual_review'];assert visual['status']=='visual-approved-by-delegated-agent' and visual['screen']=='pass_first_stage' and visual['contact_sheets_viewed']==34 and visual['key_frames_viewed']==list(range(0,801,100)) and visual['case_credit']==0 and not visual['q_n_granted'] and not visual['q_e_granted'] and not visual['scientific_payload_opened_or_hashed_by_reviewer']
contacts=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'sheet_index':i,'viewed':e['personally_viewed_with_view_image']} for i,e in enumerate(s['visual_evidence']['contacts'])];keys=[{'path':e['path'],'sha256':e['declared_sha256'],'bytes':e['bytes'],'frame':f,'viewed':e['personally_viewed_with_view_image']} for f,e in zip(range(0,801,100),s['visual_evidence']['keys'])];assert len(contacts)==34 and len(keys)==9 and png['contacts']==s['visual_evidence']['contacts'] and png['keys']==s['visual_evidence']['keys'] and png['personally_viewed_after_atomic_publish']
pub=load(er['render_publish_receipt']['path']);report=load(er['render_report']['path']);receipt=load(er['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(er['render_report']['path']);pubroot=Path(pub['published_output_root']);pubfiles={e['relative_path']:e for e in pub['files_excluding_receipt']};assert [e['path'] for e in contacts]==report['outputs']['contact_sheets']
for e in contacts+keys:
 checked(e);pr=pubfiles[str(Path(e['path']).relative_to(pubroot))];assert e['sha256']==pr['sha256'] and e['bytes']==pr['bytes'] and e['viewed']
reviewed=s['review_completed_at_utc'];now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(receipt['finished_at_utc'])<=datetime.datetime.fromisoformat(reviewed)<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_300.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==320 and cp['accepted_per_family']['F5']==37 and pid not in {load(p)['physical_case_id'] for p in cp['accepted_decisions']};ip=root(1402)/'full336-current320-actual-final48-delivery-progress-index.json';idx=load(ip);assert idx['source_authoritative_checkpoint']==ref(cpfile);target=next(v for v in idx['cases'] if v['physical_case_id']==pid);assert not target.get('accepted_decision') and target['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);ct=collections.Counter(v['kind'] for v in ld['attempts']);gpu=sum(v.get('gpu_seconds',0) for v in ld['charges'])/3600;cpu=sum(v.get('cpu_core_seconds',0) for v in ld['charges'])/3600;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and ct['qualification']<=1024 and ct['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source184_actualF5_M101T100_original1158_full801QI_personal43PNG_native_XMF_physicalcanonical_SourceDef_FILE_planJSON_visual_acceptance_1405';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_301.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
ack=O/'source184-personal-PNG-viewing-versus-stat-SHA-flag-scope-clarification.json';put(ack,{'source_commit':commit,'source_bytes_preserved':True,'source_ambiguous_content_read_or_hashed_by_reviewer_false_preserved':True,'source_agent_explicit_final_confirmed_personally_viewed_all34contacts9keys_with_view_image':True,'personal_review_time_utc':reviewed,'stat_and_declared_SHA_only_scope_is_builder_validator_not_personal_visual_view':True,'actual_visual_review_reads_published_PNG_derivatives':True,'main_all43_PNG_hashes_verified':True,'main_personally_viewed_PNGs':False,'main_scientific_payload_IO':False})
proof=O/'source184-byte-exact-readonly-main43publishedPNG-own801QI-bed-realQA-scope-proof.json';put(proof,{'schema':'ds02.main.F5.source184.personal43PNG-adoption-proof.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'independent_ownQI':ref(qip),'all43_publishedPNG_hashes_match_actual_atomic_publish':True,'actual_personal_review_time_utc':reviewed,'review_after_completed_publication':True,'actual_native_XMF_plan_field_namespaces':masks,'all_actual_primary_refs_and_genuine_QA_receipts_verified':True,'source_plan_FILE_JSON_launch_after_native_and_bed_verified':plan,'source_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_review_assigned_family':'F3','source_personal_visual_review':ref(R/prefix/'metadata/actual1158-personal-visual-decision.json'),'independent_full801_QI':ref(qip),'actual_completed_metadata_evidence':er,'full_native_frames':801,'particle_count':194427,'actual_type_counts':{'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'total':194427},'actual_physical_window_s':qi['actual_time_window_s'],'all801_UID_N3_actual_times_finite_states_verified':True,'all_native_UIDs_active_each_frame':True,'actual_native_XMF_plan_field_namespaces':masks,'native_and_XMF_physical_plan_canonical_roles_and_separate_SourceDef_FILE':True,'SourceDef_FILE':qi['actual_SourceDef'],'source_plan_JSON_FILE':plan,'full801_bed_UID_footprint_diagnostics_verified':True,'bed_one_DP_two_DP_zero_bins_not_precision_thresholds':True,'subDP_positive_depth_not_quantified':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':34,'personal_reviewed_keyframes':9,'actual_personal_review_time_utc':reviewed,'contact_sheets':contacts,'keyframes':keys,'visual_observations':visual['observations'],'visual_limits':visual['physical_screen_limits'],'strict_container_guarantee':False,'historical_negative_flags':qi['historical_negative_flags'],'actual_initial_QA_precision_negative':qi['actual_initial_QA_precision_negative'],'main_all43_PNG_hashes_match_actual_atomic_publish':True,'source_scope_clarification':ref(ack),'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source184-actual1158-full801QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(proof),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new['accepted_per_family']['F5']+=1
new.update(checkpoint=301,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=321,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(ct),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: source184 actualF5 M101T100 original1158 personal34contacts9keys accepted once after own1397 full801/source6exact/readonlyvalidation/all43pubPNG/genuineQA/bed closure. Native-XMFphysicalplan canonical separate from typedlegacy, bedSourceDefFILE,planJSONFILE; historical precisionnegative and beddiagnostic limitations retained.',authorized_work_state='Active321/336 pending15. F2=46 F3=45 F5=38. F5child219 original1190 personal43 active after actualown1399 completed; production185 F3original1031 boundedwait actual0/pub/own1401. Original1162 actualworker707983/start214704796 live. Source196/218 finaltools completed await main audit; source197 F2 repair active.')
new['actual_progress']['source184_F5_actual1158_visual_acceptance']=ref(ap);new['source_agents']['production_recovery']='fresh184 original1158 accepted once; fresh185 F3original1031 personal35+9 boundedwait actual0/pub/own1401';new['source_agents']['f6_endpoint_initial_qa']='fresh196 completed91d3a98c5 pendingmainaudit; fresh197 separateF2 final gate repair active';new['next_executable_tasks'].insert(0,'Adopt source219 F5actual1190 personal43 after source/validator/own1399/publishedPNG closure; executeF3own1401 after1031 completed0/pub and resume185. Prepare original1162 full801 ownQI and continue next15. Audit196/218 boundedfinaltool repairs; source197 separateF2 repair underway.');assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==321;put(np,new)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=321,registered_pending_independent_physical_cases=15,new_case_credit=1);target.update(status='visual-approved-in-checkpoint301',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full801_QI=ref(qip));idx['actual_unaccepted_completed0_published_physical_cases']=[v for v in idx['actual_unaccepted_completed0_published_physical_cases'] if (v if isinstance(v,str) else v['physical_case_id'])!=pid];assert len(idx['cases'])==336 and sum(bool(v.get('accepted_decision')) for v in idx['cases'])==321;put(O/'full336-current321-actual-final48-delivery-progress-index.json',idx);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F5 M101 T100 personal review with full801 bed and genuine scope roles','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':301,'accepted':321,'F5':38,'pending':15,'decision':ref(dp),'home_free_GiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
