from pathlib import Path
import json,hashlib,copy,xml.etree.ElementTree as ET,ast
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_F5_next34_distinct_inside_visual_range_source_preparation_823';C=H/'root_stage1_F5_source34_registered_generation_shared_CPU2_queue_824';S=L/'campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_125_stage1_f5_c082s1_full801_native_qualification_disabled_v1';baseowner=S/'candidates/M105_T080/owner.json';basexml=S/'candidates/M105_T080/F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_M105_T080_Def.xml';SCI={'.dat','.bi4','.h5','.hdf5','.csv','.vtk','.vtu','.npy','.npz'};load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() not in SCI;return hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def digest(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
assert not O.exists() and not C.exists();O.mkdir();C.mkdir();(O/'candidates').mkdir();(O/'workers').mkdir();base=load(baseowner);basis=base['canonical_hash_basis'];amplitudes=[86,88,90,92,94,96,98,102,104,106,108,110,112,114];specs=[(a,t) for a in amplitudes for t in [85,95]]+[(90,80),(90,100),(100,80),(101,100),(110,80),(110,100)];assert len(specs)==len(set(specs))==34
existing={(a,t) for a in [85,95,105,115] for t in [80,90,100,120]}|{(80,90),(80,110),(100,90),(100,110),(120,90),(120,110),(80,100),(120,100),(100,100)};assert not set(specs)&existing;rows=[]
for a,t in specs:
 tag=f'M{a:03d}_T{t:03d}';cid='F5_REF_RUNUP_DP020_EQUILIBRIUM_ROOT050_C082S1_'+tag+'_NEXT34';pid='F5_COMPACT_RUNUP_RECOVERY_C082S1_'+tag;src=O/'candidates'/tag;src.mkdir();motion=f'f5_c082s1_motion_{tag.lower()}.dat';duration=16*t/100
 tree=ET.parse(basexml);root=tree.getroot()
 root.find('.//motion/objreal/begin').set('finish',str(duration));root.find('.//motion/objreal/mvpredef').set('duration',str(duration));root.find('.//motion/objreal/mvpredef/file').set('name','assets/'+motion)
 for e in root.findall('.//execution/parameters/parameter'):
  if e.get('key')=='TimeMax':e.set('value','16')
  if e.get('key')=='TimeOut':e.set('value','0.02')
 for e in root.findall('.//_computetime')+root.findall('.//_outputtime'):e.set('end','16')
 xp=src/(cid+'_Def.xml');tree.write(xp,encoding='utf-8',xml_declaration=True)
 # Count/model state expectations are prospective; no native count claim before each actual GenCase.
 params=copy.deepcopy(base['parameters']);params['piston_motion'].update(amplitude_scale=a/100,time_scale=t/100,duration_s=duration,asset_relative_name='assets/'+motion)
 physical={'schema':'ds02.f5.stage1.c082s1.physical-condition.next34.v1','family_id':'F5','mechanism_id':base['mechanism_id'],'geometry_family_id':base['geometry_family_id'],'geometry':basis['geometry'],'parameters':params,'initial_state_policy':base['initial_state_policy'],'gravity_m_s2':base['gravity_m_s2'],'density_kg_m3':base['density_kg_m3'],'prescribed_control':{'base_motion_sha256_producer_attested':base['base_motion_sha256'],'amplitude_scale':a/100,'time_scale':t/100,'rows':641,'source_window_s':[0,16],'scaled_window_s':[0,duration],'interpolation':'native piecewise linear','transform':'t_scaled=t*time_scale; x_scaled=x*amplitude_scale; no clipping or source interpolation'},'observation_window_s':[0,16]};dg=digest(physical)
 owner={'schema':'ds02.f5.stage1.next34.source-owner.v1','family_id':'F5','case_id':cid,'physical_case_id':pid,'candidate_id':'C082S1_MOTION_'+tag,'mechanism_id':base['mechanism_id'],'geometry_family_id':base['geometry_family_id'],'geometry':basis['geometry'],'parameters':params,'initial_state':{'policy':base['initial_state_policy'],'fluid_continuum_region':basis['geometry']['fluid_continuum_region']},'continuum_geometry':basis['geometry'],'gravity_m_s2':base['gravity_m_s2'],'density_kg_m3':base['density_kg_m3'],'physical_condition_sha256':dg,'source_canonical_physical_condition':physical,'source_definition':str(xp),'source_definition_sha256':sha(xp),'full_window_s':[0,16],'expected_frames':801,'dp_m':.02,'tout_s':.02,'prospective_expected_counts':{'total':194427,'fixed':158559,'moving':4210,'floating':0,'fluid':31658},'actual_counts':None,'native_bed_marker_mk':50,'source_bed_marker_mkbound':40,'q_n_granted':False,'q_e':'not_assessed','future_motion_sha256':None,'future_native_receipt':None,'future_typed_report':None,'future_visual_acceptance':None,'independent_case_count_increment':0,'historical_A_B_penetration_failures_retained':True,'historical_precision_negative_retained':True,'source_preparation_science_payload_accessed':False};op=src/'owner.json';put(op,owner);rows.append({'tag':tag,'case_id':cid,'physical_case_id':pid,'amplitude_percent':a,'time_percent':t,'amplitude_scale':a/100,'time_scale':t/100,'motion_duration_s':duration,'motion_filename':motion,'physical_condition_sha256':dg,'physical_condition':physical,'source_xml':str(xp),'source_xml_sha256':sha(xp),'source_owner':str(op),'source_owner_sha256':sha(op)})
assert len({r['physical_condition_sha256'] for r in rows})==34
plan={'schema':'ds02.f5.stage1.next34.source-plan.v1','candidate_count':34,'candidates':rows,'range_gate':str(H/'root_stage1_F5_two_full801_endpoints_delegated134136_visual_bed_integration_807/actual-integration-review.json'),'range_gate_status':'two actual endpoint full801 visual passes; numeric precision not accepted','visual_parameter_range':{'amplitude_scale':[.85,1.15],'time_scale':[.8,1.0]},'T120_held':True,'full_window_s':[0,16],'expected_frames':801,'actual_source_generation_report':None,'parent_definition':str(basexml),'parent_definition_sha256':sha(basexml),'parent_owner':str(baseowner),'parent_owner_sha256':sha(baseowner),'base_motion':base['base_motion_path'],'base_motion_sha256_producer_attested':base['base_motion_sha256'],'zero_amplitude_scaling_or_mass_rescale':False,'source_arrays_read_or_hashed':False,'source_claim_only_no_scientific_execution':True,'independent_case_count_increment':0};gate=Path(plan['range_gate'])
if not gate.exists():gate=next(H.glob('root*807'))/'actual-integration-review.json';plan['range_gate']=str(gate)
assert load(gate)['independent_case_increment']==2;put(O/'source-plan.json',plan)
worker=r'''from pathlib import Path
from decimal import Decimal
import argparse,json,hashlib,shutil,os
ap=argparse.ArgumentParser();ap.add_argument('--plan',type=Path,required=True);ap.add_argument('--output-root',type=Path,required=True);ap.add_argument('--report',type=Path,required=True);a=ap.parse_args();plan=json.loads(a.plan.read_text());root=a.output_root;assert not root.exists();root.mkdir(parents=True)
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for block in iter(lambda:f.read(1048576),b''):h.update(block)
 return h.hexdigest()
base=Path(plan['base_motion']);before=sha(base);assert before==plan['base_motion_sha256_producer_attested'];data=[]
for raw in base.read_text().splitlines():
 raw=raw.strip()
 if not raw or raw.startswith(('#',';')):continue
 fields=raw.replace(',',' ').split();assert len(fields)==2;t,x=map(Decimal,fields);assert t.is_finite() and x.is_finite();data.append((t,x))
assert len(data)==641 and data[0][0]==0 and data[-1][0]==16 and all(x[0]<y[0] for x,y in zip(data,data[1:]));out=[];seen=set()
for c in plan['candidates']:
 amp=Decimal(c['amplitude_percent'])/100;ts=Decimal(c['time_percent'])/100;assert Decimal('.85')<=amp<=Decimal('1.15') and Decimal('.8')<=ts<=1;assert (amp,ts) not in seen;seen.add((amp,ts));p=root/c['tag'];(p/'assets').mkdir(parents=True);motion=p/'assets'/c['motion_filename'];lines=[format(t*ts,'f')+'\t'+format(x*amp,'f') for t,x in data];motion.write_text('\n'.join(lines)+'\n');xml=p/(c['case_id']+'_Def.xml');owner=p/'owner.json';assert sha(c['source_xml'])==c['source_xml_sha256'] and sha(c['source_owner'])==c['source_owner_sha256'];shutil.copyfile(c['source_xml'],xml);shutil.copyfile(c['source_owner'],owner);out.append({'tag':c['tag'],'case_id':c['case_id'],'physical_case_id':c['physical_case_id'],'physical_condition_sha256':c['physical_condition_sha256'],'amplitude_scale':float(amp),'time_scale':float(ts),'rows':641,'output_time_first_s':float(data[0][0]*ts),'output_time_last_s':float(data[-1][0]*ts),'motion':{'path':str(motion),'sha256':sha(motion),'bytes':motion.stat().st_size},'definition':{'path':str(xml),'sha256':sha(xml)},'owner':{'path':str(owner),'sha256':sha(owner)},'actual_native_counts':None})
assert len(out)==34 and sha(base)==before;a.report.write_text(json.dumps({'schema':'ds02.f5.next34.registered-source-generation-report.v1','status':'completed','cases':out,'base_motion':{'path':str(base),'sha256_before':before,'sha256_after':sha(base)},'candidate_count':34,'native_control_interpolation':'piecewise linear','geometry_unchanged_from_registered_parent_xml_except_control_and_window':True,'native_GenCase_required_per_condition':True,'independent_case_count_increment':0},indent=2)+'\n')
'''
ast.parse(worker);wp=O/'workers/generate_source34_registered.py';wp.write_text(worker)
baseq=load(H/'root_stage1_f2_first48_remaining24_registered_source_generation_801/registered-source-generation-request.json');profile={k:v for k,v in baseq.items() if k.startswith('root_') or k=='resource_window'};attempt='root-stage1-f5-next34-inside-visual-range-registered-source-generation-root824';ap=D/'families/F5/F5_NEXT34_SOURCE_ROOT824'/attempt;md={str(p):sha(p) for p in [O/'source-plan.json',wp,basexml,baseowner,gate,L/'.venv/bin/python',L/'scripts/ds_data02_runtime_v2.py',L/'scripts/ds_data02_strict_dispatch_v1.py',H/'root_stage1_home_floor_inventory_dispatch_142/launch.py',H/'root_stage1_home_floor_inventory_dispatch_142/root_home_floor_inventory_policy.py',H/'root_user_resource_window_512gpu_3840cpu_064/resource-window-approval.json']};md[base['base_motion_path']]=base['base_motion_sha256']
for r in rows:
 for pathkey,hashkey in [('source_xml','source_xml_sha256'),('source_owner','source_owner_sha256')]:md[r[pathkey]]=r[hashkey]
q={**profile,'schema':'ds02.runner-request.v2','family_id':'F5','case_id':'F5_NEXT34_SOURCE_ROOT824','attempt_id':attempt,'attempt_root':str(ap),'kind':'cpu','cpu_task_kind':'audit','cpu_threads':2,'launch_owner':'root','worktree_root':str(R),'cwd':str(L),'command':[str(L/'.venv/bin/python'),str(wp),'--plan',str(O/'source-plan.json'),'--output-root','{attempt_root}/source','--report','{attempt_root}/source-generation-report.json'],'input_files':sorted(md),'input_sha256':md,'max_wall_seconds':300,'estimated_storage_bytes':1024**3,'disabled':False,'source_only':False,'launch':True,'launch_allowed':True,'execution_allowed':True,'root_review_required':False,'production_approval':'none','q_n_granted':False,'independent_case_count_increment':0};qp=C/'registered-source-generation-request.json';put(qp,q)
controller=r'''from pathlib import Path
import fcntl,json,time,subprocess,datetime
O=Path(__file__).parent;R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());qp=O/'registered-source-generation-request.json';q=load(qp)
with (D/'runtime/stage1-fullnative-conversion-dispatch.lock').open('a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);print(json.dumps({'state':'acquired shared CPU2 lock','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}),flush=True)
 while sum(x.get('cpu_threads',0) for x in load(D/'runtime/resource-ledger.json')['reservations'])+2>64:time.sleep(3)
 p=subprocess.run([str(L/'.venv/bin/python'),str(H/'root_stage1_home_floor_inventory_dispatch_142/launch.py'),str(qp)],cwd=L,capture_output=True,text=True)
ap=Path(q['attempt_root']);rp=ap/'execution-receipt.json';cp=ap/'source-generation-report.json';r=load(rp) if rp.exists() else {};c=load(cp) if cp.exists() else {};passed=(r.get('status'),r.get('returncode'))==('completed',0) and p.returncode==0 and c.get('status')=='completed' and c.get('candidate_count')==34 and len(c.get('cases',[]))==34;out={'request':str(qp),'actual_receipt':str(rp),'actual_source_generation_report':str(cp),'status':r.get('status'),'returncode':r.get('returncode'),'launcher_returncode':p.returncode,'actual34_motion_generation_pass':passed,'independent_case_count_increment':0,'launcher_error':p.stderr[-1500:]};(O/'controller-result.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out),flush=True);raise SystemExit(0 if passed else 1)
'''
ast.parse(controller);(C/'batch-controller.py').write_text(controller);(O/'source-preparation.py').write_bytes(Path(__file__).read_bytes());put(C/'dispatch-plan.json',{'shared_CPU2_lock':str(D/'runtime/stage1-fullnative-conversion-dispatch.lock'),'queued_source_job':str(qp),'actual_future_inputs_unknown_until_registered_worker':True,'source_scientific_payloads_read_or_hashed_by_main':False,'source_candidates':34,'accepted_case_increment':0});print(json.dumps({'source_conditions':34,'source_package':str(O),'controller':str(C/'batch-controller.py'),'scientific_payload_accessed':False}))
