from pathlib import Path
import json,hashlib,subprocess,copy,collections,datetime,os,re
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.xml','.xmf','.py','.md','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
def dt(s):return datetime.datetime.fromisoformat(re.sub(r'(\.\d{6})\d+',r'\1',s.replace('Z','+00:00')))
commit='57c64338dfed299f67aa79c372aaff3028b77519';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_184_f6_assigned_f2_rx051_rot105_root1110_personal_visual_review_v1');P=W/prefix
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==3;blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh184.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/personal-visual-decision.json');e=s['evidence'];c=s['case'];qip=root(1308)/'actual1110-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qip);cid=qi['case_id'];pid=qi['physical_case_id'];canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256']
assert s['assigned_family']=='F6' and s['actual_family']=='F2' and s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and not s['recursive_delegation']
assert (c['case_id'],c['physical_case_id'])==(cid,pid) and c['canonical_native_physical_condition_sha256']==canonical and c['typed_legacy_actual_converter_and_xmf_physical_scope_sha256']==legacy and canonical!=legacy
assert s['decision']['status']=='visual-approved-by-delegated-agent' and s['decision']['case_credit']==0 and not s['decision']['global_acceptance'] and not s['decision']['q_n_granted'] and not s['decision']['q_e_granted']
assert e['qi_proof']['path']==str(qip) and e['qi_proof']['sha256']==sha(qip)
for k,v in e.items():assert sha(v['path'])==v['sha256'] and Path(v['path']).stat().st_size==v['bytes']
own_refs={e['path']:e for g in qi['actual_completed_metadata_evidence'].values() for e in g.values()}
for k in ['gencase_receipt','generated_xml','initial_qa_receipt','initial_qa_report','native_receipt','typed_receipt','typed_report','xmf_receipt','xmf_manifest','xmf_xml','render_receipt','render_report','publish_receipt']:
 assert e[k]['path'] in own_refs and e[k]['sha256']==own_refs[e[k]['path']]['sha256']
 if k.endswith('_receipt') and k!='publish_receipt':r=load(e[k]['path']);assert r['status']=='completed' and r['returncode']==0 and r['request']['case_id']==cid
assert qi['frames']==401 and qi['particles']==418104 and qi['all_actual_times_exact_typed_XMF_XML_render'] and qi['all_frames_geometry_velocity_N3_identity_and_finite_active_fields']
assert c['actual_time_s']==qi['actual_time_window_s'] and c['declared_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21114,'total':418104} and c['terminal_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21111,'total':418101}
ns=qi['native_and_XMF_plan_field_namespaces'];assert c['source_plan_field_presence']['native']==ns['native'] and c['source_plan_field_presence']['xmf']==ns['XMF']
life=qi['lifecycle'];limits=s['lifecycle_and_limits'];assert limits['frames']==limits['source_frames']==401 and limits['time_window_s']==qi['actual_time_window_s'] and limits['initial_counts']==c['declared_counts'] and limits['terminal_counts']==c['terminal_counts'];assert limits['final_missing_fluid_particles']==life['final_missing_particles']==3
for k in ['final_missing_fraction_initial_fluid','first_missing_frame','max_missing_per_frame','frames_with_any_missing_particle','cumulative_particle_frame_omissions']:assert limits[k]==life[k]
assert life['first_missing_frame']==165 and life['frames_with_any_missing_particle']==236 and life['cumulative_particle_frame_omissions']==652 and not limits['uid_closure_claimed'] and not limits['strict_containment_claimed'] and not limits['precision_claimed']
assert limits['producer_attested_missing_ids']==life['final_missing_id_first_producer_attested']
vr=s['visual_review'];contacts=vr['contact_sheets'];keys=vr['key_frames'];assert vr['personally_viewed_with']=='view_image' and len(contacts)==17 and len(keys)==9 and [r['sheet_index'] for r in contacts]==list(range(17)) and [r['frame'] for r in keys]==list(range(0,401,50))
pub=load(e['publish_receipt']['path']);render=load(e['render_report']['path']);receipt=load(e['render_receipt']['path']);assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==e['render_report']['sha256'];out=Path(pub['published_output_root']);pubfiles={r['relative_path']:r for r in pub['files_excluding_receipt']};assert [r['path'] for r in contacts]==render['outputs']['contact_sheets']
for r in contacts+keys:
 p=Path(r['path']);v=pubfiles[str(p.relative_to(out))];assert sha(p)==r['sha256']==v['sha256'] and p.stat().st_size==r['bytes']==v['bytes']
now=datetime.datetime.now(datetime.timezone.utc);assert dt(receipt['finished_at_utc'])<=dt(vr['review_completed_at_utc'])<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_244.json';cp=load(cpfile);assert cp['checkpoint']==244 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==297 and cp['accepted_per_family']['F2']==41
assert pid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in cp['accepted_decisions']}
ip=root(1314)/'full336-current297-actual-final48-delivery-progress-index.json';index=load(ip);targets=[r for r in index['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision') and targets[0]['native_request_scope']['sha256']==canonical
raw=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(raw);counts=collections.Counter(r['kind'] for r in ledger['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ledger['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ledger['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source184_F2_RX051ROT105_original1110_full401QI_personal26PNG_actual3fluid_omissions_all_lifecycle_blocks_checked_visual_acceptance_1317';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_245.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source184-byte-exact-readonly-validator-own401QI-all-case-limits-and-main26publishedPNG-proof.json';put(vp,{'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'validator_stdout':rv.stdout,'validator_stderr':rv.stderr,'all_case_lifecycle_limits_blocks_match_actualF2':True,'source_personal_review_time_after_actual_publication':True,'main_all26_PNG_bound_to_actual_atomic_publish':True,'main_scientific_payload_IO':False})
dp=O/f'{pid}-delegated-visual-decision.json';put(dp,{'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F2','assigned_review_family':'F6','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'source_review_commit':commit,'source_visual_review':ref(R/prefix/'metadata/personal-visual-decision.json'),'source_metadata_authority_proof':ref(vp),'independent_full401_QI':ref(qip),'actual_completed_metadata_evidence':qi['actual_completed_metadata_evidence'],'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'stage1_QI_full_native_identity_and_state_verified':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'native_and_XMF_plan_field_namespaces':ns,'initial_native_type_counts':qi['initial_native_type_counts'],'lifecycle':life,'visual_lifecycle_and_limits':limits,'all_fluid_UIDs_active_or_closed_container_claimed':False,'no_missing_particle_state_reconstructed':True,'no_user_numeric_threshold_inferred':True,'agent_personally_viewed_all_contacts_and_keys':True,'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'contact_sheets':contacts,'keyframes':keys,'visual_observations':vr['observations'],'main_all26_PNG_hashes_match_actual_atomic_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1})
ap=O/'source184-actual1110-full401QI-personal-visual-adoption.json';put(ap,{'source_validation':ref(vp),'independent_QI':ref(qip),'new_visual_decision':ref(dp),'case_credit':1,'main_scientific_payload_IO':False});snapshot=O/'ledger-immutable-snapshot.json';snapshot.write_bytes(raw)
new=copy.deepcopy(cp);new['accepted_per_family']['F2']+=1;new.update(checkpoint=245,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=298,new_accepted_decisions=[str(dp)],accepted_decisions=cp['accepted_decisions']+[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snapshot),active_reservations=ledger['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: ownfull401 QI1307/1308 and both originalF2 published renders closed; source205 RX063ROT075 accepted297 with35fluid omissions; source184 RX051ROT105 personal26PNG now accepted298/F2=42 with3fluid omissions/unknown causes. Fixedactual24 F6 particle+fulltime rigid joined delivery complete. Current originalF5 1126/1187 PV live, nextQI helper prepared without execution.',authorized_work_state='Active298/336,38 pending. F1/F4/F7=48,F2=42,F3=39,F5=26,F6=47. F5 originals1126 and1187 renderlive; source171 F6 final48 particle+rigid47accepted/onepending catalog in progress; source206 firstoriginal1126 personalreview waits atomicpub.')
new['actual_progress']['source184_F2_actual1110_visual_acceptance']=ref(ap);new['source_agents']['f6_endpoint_initial_qa']='fresh184 actualF2 accepted F2=42; nextfresh185 actualF5 M115T090 original1187 rendering then personal43PNG';new['next_executable_tasks']=['Observe sameoriginalF5 1126/1187 livePV and execute prepared own801QI1315/1316 after authoritative actualterminal/publication, then adopt personalfresh206/fresh185 43PNG.','Integrate fresh171 actualF6 final48 particle+rigid47accepted/onepending catalog; lastF6 original951 remains registered live waiter, never fake visual approval.','Continue remaining38 original full renders and personalreviews toward all336 distinct complete visual cases.'];assert len(new['accepted_decisions'])==sum(new['accepted_per_family'].values())==298;put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),accepted_independent_physical_cases=298,registered_pending_independent_physical_cases=38,new_case_credit=1);targets[0].update(status='visual-approved-in-checkpoint245',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status='视觉检查通过、数值精度未验收',actual_full401_QI=ref(qip));index['actual_unaccepted_completed0_published_physical_cases']=[r for r in index['actual_unaccepted_completed0_published_physical_cases'] if r['physical_case_id']!=pid];assert len(index['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in index['cases'])==298;put(O/'full336-current298-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: accept F2 RX051ROT105 full401 preserving3fluid omissions and actual scope gaps','--',*paths],cwd=R,check=True);print({'checkpoint':245,'accepted':298,'F2':42,'pending':38,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
