from pathlib import Path
import json,hashlib,datetime,subprocess,copy,collections,os,math,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def check(e):assert sha(e['path'])==e['sha256'];assert 'bytes' not in e or Path(e['path']).stat().st_size==e['bytes']
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
commit='98b16fa5dcc6f20446010694d7d4d61efe531ae3';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_190_f6_final48_complete_particle_rigid_primary_delivery_v1');P=W/prefix;names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(names)==5;blobs={n:subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W) for n in names}
for n,b in blobs.items():assert (W/n).read_bytes()==b and (not (R/n).exists() or (R/n).read_bytes()==b)
before={n:sha(W/n) for n in names};rv=subprocess.run(['python3','-B',str(P/'scripts/validate_final48.py')],capture_output=True,text=True);assert rv.returncode==0,(rv.stdout,rv.stderr);assert before=={n:sha(W/n) for n in names}
s=load(P/'metadata/final48-delivery.json');assert s['family_id']=='F6' and s['model']=='gpt-5.6-luna' and s['reasoning_effort']=='max' and not s['recursive_delegation'] and s['delivery']['final48_count']==s['delivery']['accepted_visual_count_at_checkpoint262']==48 and s['delivery']['pending_visual_count']==s['delivery']['new_case_credit']==0
for e in s['authoritative_sources'].values():check(e)
fixed=load(s['authoritative_sources']['root1276_actual_first24_dynamic']['path']);mem=s['membership'];assert mem['frozen_first8_physical_case_ids']==fixed['frozen_first8_physical_case_ids'] and mem['actual_first24_physical_case_ids']==fixed['actual_first24_physical_case_ids'] and mem['final48_physical_case_ids']==fixed['registered_final48_physical_case_ids'];assert len(set(mem['final48_physical_case_ids']))==48 and set(mem['frozen_first8_physical_case_ids'])<=set(mem['actual_first24_physical_case_ids'])<=set(mem['final48_physical_case_ids'])
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_266.json';cp=load(cpfile);assert cp['checkpoint']==266 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==307 and cp['accepted_per_family']['F6']==48;ip=root(1352)/'full336-current307-actual-final48-delivery-progress-index.json';index=load(ip);current={r['physical_case_id']:r for r in index['cases']};rigid=load(s['authoritative_sources']['root1305_full48_rigid_product']['path']);rr={r['physical_case_id']:r for r in rigid['rows']};assert len(rr)==48
rows=copy.deepcopy(s['rows']);proofrows=[];baseline='F6_STAGE1_ANGULAR_RELEASE_OMEGA_BASELINE';last='F6_STAGE1_ANGULAR_RELEASE_DZXY_S1375_YAWP18_DP025';recoveries=[];contacts=0;keys=0
for row in rows:
 pid=row['physical_case_id'];prim=row['primary_refs'];de=row['current_accepted_decision_summary']['accepted_decision'];check(de);assert de['path']==current[pid]['accepted_decision']['path'] and de['sha256']==current[pid]['accepted_decision']['sha256'];dec=load(de['path']);assert dec['physical_case_id']==pid and 'visual-approved' in dec['status'];m=load(prim['xmf']['manifest']['path']);check(prim['xmf']['manifest']);check(prim['xmf']['xml']);assert m['physical_case_id']==pid and m['frames']==m['particles']*0+241 and m['particles']==417505 and m['fields']['position']['shape']==m['fields']['velocity']['shape']==[241,417505,3]
 if pid==baseline:
  assert prim['native']==prim['typed']==[] and prim['xmf']['receipt'] is None
  for group,keylist in [('native',['native_receipt']),('typed',['typed_receipt','conversion_report']),('gencase_or_definition',['gencase_receipt','generated_xml'])]:
   prim[group]=[{**ref(m[k]),'role':'main-recovered-existing-baseline-'+k,'source_authority':'same actual baseline XMF manifest'} for k in keylist]
  xp=Path(prim['xmf']['manifest']['path']).parent/'execution-receipt.json';assert xp.is_file();prim['xmf']['receipt']=ref(xp)
  recoveries.append({'physical_case_id':pid,'source_original_empty_primary_groups':{'native':[],'typed':[],'xmf_receipt':None},'recovered_existing_native_receipt':prim['native'][0],'recovered_existing_typed_receipt_and_report':prim['typed'],'recovered_existing_XMF_receipt':prim['xmf']['receipt'],'native_condition_field_still_absent_null':True,'no_jobs_or_new_receipts_created':True})
 typed_source_paths={e['path'] for e in prim['typed']}
 typed_recovered=[]
 for key in ['typed_receipt','conversion_report']:
  if m[key] not in typed_source_paths:
   e=ref(m[key]);assert key+'_sha256' not in m or e['sha256']==m[key+'_sha256'];prim['typed'].append({**e,'role':'main-recovered-existing-'+key,'source_authority':'same actual XMF manifest'});typed_recovered.append(e)
 if typed_recovered:recoveries.append({'physical_case_id':pid,'source_typed_primary_refs_snapshot':[e for e in s['rows'] if e['physical_case_id']==pid][0]['primary_refs']['typed'],'existing_typed_refs_recovered_from_same_actual_XMF_manifest':typed_recovered,'source_bytes_preserved':True,'no_jobs_or_new_receipts_created':True})
 for group in ['native','typed','gencase_or_definition','initial_qa_or_audit','owner_or_source']:
  for e in prim[group]:check(e)
 nr=[e for e in prim['native'] if Path(e['path']).name=='execution-receipt.json'];tr=[e for e in prim['typed'] if Path(e['path']).name=='execution-receipt.json'];treps=[e for e in prim['typed'] if Path(e['path']).name=='conversion-report.json'];assert len(nr)==len(tr)==len(treps)==1
 n=load(nr[0]['path']);t_rc=load(tr[0]['path']);t=load(treps[0]['path']);r=load(prim['render']['report']['path']);render_rc=load(prim['render']['receipt']['path'])
 for e in [prim['render']['receipt'],prim['render']['report'],prim['xmf']['receipt']]:
  if e:check(e)
 for receipt in [n,t_rc,render_rc]:assert receipt['status']=='completed' and receipt['returncode']==0 and receipt['request']['case_id']==row['case_id']
 if prim['xmf']['receipt']:
  xmfrc=load(prim['xmf']['receipt']['path']);assert xmfrc['status']=='completed' and xmfrc['returncode']==0 and xmfrc['request']['case_id']==row['case_id']
 nq=n['request'];assert (pid==baseline)==('physical_condition_sha256' not in nq)
 assert t['frames']==t['particles']*0+241 and t['particles']==417505 and t['conversion_status']=='completed' and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['source_provenance']['solver_receipt']['path']==nr[0]['path'] and t['source_provenance']['solver_receipt']['sha256']==nr[0]['sha256'];assert t['output_sha256']==m['source_h5_sha256']==r['source_h5_sha256'];assert r['frames']==r['source_frames']==241 and r['all_frames_rendered'] and r['actual_times_preserved_exactly'] and r['native_identity_axis_preserved'] and r['nonfinite_active_states']==0;assert m['xdmf_sha256']==sha(prim['xmf']['xml']['path'])==r['xdmf_sha256_before']==r['xdmf_sha256_after']
 times=m['actual_time_s'];grids=ET.parse(prim['xmf']['xml']['path']).findall('.//Grid[@GridType="Uniform"]');assert len(times)==len(grids)==241 and times==[float(g.find('Time').get('Value')) for g in grids]==[f['time'] for f in t['lifecycle']['frame_summary']]==[f['actual_time_s'] for f in r['frame_diagnostics']];assert times[0]==0 and times[-1]>=12 and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]))
 assert row['rigid_motion_join']==rr[pid]
 for key in ['actual_export_receipt','actual_export_report','actual_rigid_audit_receipt']:
  if isinstance(rr[pid].get(key),dict):check(rr[pid][key])
 assert rr[pid]['frames']==241 and rr[pid]['case_credit']==0
 if pid!=baseline:assert rr[pid]['required_rigid_fields_finite_all241'] and rr[pid]['native_time_tolerance_s']==1e-6
 else:assert not rr[pid]['legacy_Part_column_validation_field_present'] and rr[pid]['legacy_Part_unique_count'] is None
 for png in prim['png']['contacts']+prim['png']['navigation_previews']:
  p=Path(png['path']);assert p.is_relative_to(D) and not p.is_symlink() and p.is_file();actual_size=p.stat().st_size
  if 'bytes' in png:assert actual_size==png['bytes']
  else:png['bytes']=actual_size;png['main_added_current_filename_stat_bytes_with_source_field_absence_preserved']=True
  assert len(png.get('sha256',png.get('producer_sha256','')))==64
 contacts+=len(prim['png']['contacts']);keys+=len(prim['png']['navigation_previews']);mask={ns:{k:{'present':k in obj,'value':obj.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,obj in [('native',nq),('XMF',m)]};row['main_actual_native_condition_field']={'present':'physical_condition_sha256' in nq,'value':nq.get('physical_condition_sha256')};row['main_actual_native_XMF_plan_field_namespaces']=mask;proofrows.append({'physical_case_id':pid,'native_receipt':nr[0],'typed_receipt':tr[0],'typed_report':treps[0],'actual_native_condition_field':row['main_actual_native_condition_field'],'actual_native_XMF_plan_field_namespaces':mask,'full241_actual_native_typed_XMF_XML_render_times_verified':True,'full241_UID_geometry_velocity_N3_finite_integrity_inherited_from_own47_and_lastQI':True,'fulltime_rigid_metadata_same_as_actual48_product':True,'baseline_fullCSVTimevector_new_independent_verification':False if pid==baseline else None,'baseline_Part_field_missing_preserved':True if pid==baseline else None})
assert contacts==528 and keys==480
assert s['last_case_limits']['final_missing_fluid']==3 and s['last_case_limits']['cumulative_particle_frame_omissions']==700 and s['last_case_limits']['missing_location_state_cause_unknown'] and not s['last_case_limits']['all_native_uids_active_claim'];assert s['mass_semantics']['physical_mass_kg']==128 and s['mass_semantics']['native_support_mass_kg']==256 and not s['mass_semantics']['mass_equality_claimed'];assert not s['scope_policy']['full_csv_time_vector_independently_reverified_in_this_package']
now=datetime.datetime.now(datetime.timezone.utc);raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(x['kind'] for x in ld['attempts']);gpu=sum(x.get('gpu_seconds',0) for x in ld['charges'])/3600;cpu=sum(x.get('cpu_core_seconds',0) for x in ld['charges'])/3600;vf=os.statvfs('/home/jade');free=vf.f_bavail*vf.f_frsize/2**30;assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_source190_F6_final48_actual_particle_rigid_primary_baseline_native_typed_XMF_receipt_recovery_condition_absence_threefluid_limits_1353';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_267.json';assert not O.exists() and not np.exists();O.mkdir()
for n,b in blobs.items():p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
vp=O/'source190-byte-exact-main48-actual-primary-time-UID-rigid-closure-baseline-ref-recovery-proof.json';put(vp,{'schema':'ds02.source190.main.F6.actual48-primary-closure.v1','at_utc':now.isoformat(),'source_commit':commit,'source_files':[ref(R/n) for n in names],'source_before_after_SHA':before,'readonly_validator_stdout':rv.stdout,'readonly_validator_stderr':rv.stderr,'source_header_created_at_utc_not_used_as_actual_job_or_review_chronology':s['created_at_utc'],'frozen8_actual24_final48_membership_exact':True,'all48_actual_accepted_decisions_equal_current307_index':True,'all48_actual_native_typed_XMF_render_completed0':True,'all48_full241_N3_actual_times_metadata_closure':True,'all48_rigid_join_same_actual48_product':True,'source_baseline_and_three_typed_primary_group_omissions_recovered_from_existing_manifests':recoveries,'source_baseline_nativecondition_absence_does_not_mean_receipt_absence':True,'published528contacts480navigation_previews_stat_checked':True,'prior47_PNG_actual_SHA_certificates_preserved':ref(s['authoritative_sources']['root1321_particle_rigid_47_plus_one_pending']['path']),'lastF6_PNG_actual_SHA_certificate':ref(s['authoritative_sources']['root1345_source189_adoption']['path']),'published_PNG_payloads_not_rehashed_or_personally_viewed_this_catalog_adoption':True,'baseline_fullCSVTimevector_not_newly_independently_verified':True,'baseline_Part_field_actual_absence_not_filled':True,'source_lastF6_limits':s['last_case_limits'],'mass_semantics':s['mass_semantics'],'per_case_actual_primary_bindings':proofrows,'main_scientific_payload_IO':False,'new_case_credit':0,'Q_N':False,'Q_E':False})
product=copy.deepcopy(s);product.update(schema='ds02.main.F6.final48-complete-particle-rigid-primary-delivery.v1',at_utc=now.isoformat(),source_original_exact_package={'source_commit':commit,'source_catalog':ref(R/prefix/'metadata/final48-delivery.json')},main_independent_verification=ref(vp),rows=rows,stable_predecessor_checkpoint=ref(cpfile));product['delivery'].update(all48_actual_native_typed_XMF_receipt_refs_completed0=True,new_case_credit=0,new_visual_credit=0);pp=O/'F6-FINAL48-COMPLETE-PARTICLE-RIGID-ACTUAL-PRIMARY-DELIVERY.json';put(pp,product);snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=267,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,authorized_work_state='Active307/336: F6 final48 complete particle-rigid primary directory adopted; existing baseline native/typed/XMF receipts recovered from same actualmanifest while true nativecondition and baseline rigid Part/fullCSVTime uncertainty remain absent/notnewcertified. F1/F4/F6/F7 complete48 each, F2=43,F3=42,F5=30; originalF5 1150/1157 same-process renders with futureQI1349/1350 personal210/191 underway.',previous_goal_turn_classification='PROGRESS: originalF3 full836 and F2 full401 personalreviews accepted306 then307; source190 finalF6 complete48 primary directory integrated with baseline receipt reference recovery and unchanged nativeconditionabsence/rigid uncertainty/mass semantics/last3fluid omissions. Safe user cleanup534.4086GiB preserved; no new failed outputs.')
new['actual_progress']['F6_final48_complete_particle_rigid_primary_delivery']=ref(pp);new['actual_progress']['F6_final48_main_actual48_primary_closure_proof']=ref(vp);put(np,new)
index.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_F6_final48_complete_particle_rigid_primary_delivery=ref(pp))
for r in index['cases']:
 if r['family_id']=='F6':r['actual_F6_final48_complete_particle_rigid_primary_delivery']=ref(pp)
assert index['accepted_independent_physical_cases']==307 and index['registered_pending_independent_physical_cases']==29;put(O/'full336-current307-actual-final48-delivery-progress-index.json',index);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=names+[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: deliver F6 full48 particle rigid primaries with true baseline absence preserved','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':267,'accepted':307,'F6_final48':48,'published_contacts':contacts,'navigation_previews':keys,'baseline_and_typed_primary_recovery_cases':len(recoveries),'new_case_credit':0,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
