from pathlib import Path
import json,hashlib,datetime,os,subprocess
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p):return json.loads(Path(p).read_text())
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
O=H/'root_stage1_failed_unused_cleanup_actual489CSV16GiB_cumulative532GiB_storage_floor_checkpoint_1221';O.mkdir(exist_ok=False);(O/'checkpoint-source.py').write_bytes(Path(__file__).read_bytes())
checks=[]
for n in (965,1054,1220):
 rr=root(n);c=load(rr/'controller-result.json');assert c['status']=='completed' and c['returncode']==0;rp=Path(c['actual_receipt']);r=load(rp);assert r['status']=='completed' and r['returncode']==0;out=rp.parent/'cleanup';result=load(out/'cleanup-result.json');assert result['status']=='completed';js=[json.loads(x) for x in (out/'deleted-files.jsonl').read_text().splitlines() if x];assert len(js)==result['deleted_files'];assert all(not Path(x['path']).exists() for x in js)
 checks.append({'root':n,'actual_receipt':str(rp),'receipt_sha256':sha(rp),'result':str(out/'cleanup-result.json'),'result_sha256':sha(out/'cleanup-result.json'),'deleted_files':result['deleted_files'],'deleted_payload_bytes':result['deleted_payload_bytes'],'deleted_allocated_bytes':result['deleted_allocated_bytes'],'all_deleted_paths_still_absent':True})
plan=load(root(1220)/'exact-failed-unused-csv-cleanup-plan.json');preserved=[]
for a in plan['attempts']:
 rp=Path(a['attempt_root'])/'execution-receipt.json';assert sha(rp)==a['receipt_sha256']
 for v in a['preserved_files']:
  p=Path(v['path']);s=p.lstat();assert (s.st_dev,s.st_ino,s.st_size,s.st_mtime_ns)==(v['device'],v['inode'],v['bytes'],v['mtime_ns']);preserved.append(str(p))
 assert (rp.parent/'stdout.log').is_file();assert not (rp.parent/'trajectory.h5').exists();assert not (rp.parent/'conversion-report.json').exists()
ledger=D/'runtime/resource-ledger.json';lb=ledger.read_bytes();ld=json.loads(lb);(O/'resource-ledger-frozen.json').write_bytes(lb)
s=os.statvfs('/home/jade');free=s.f_bavail*s.f_frsize;assert free>=500*2**30
proof={'schema':'ds02.failed-unused-storage-cleanup-independent-adoption.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_cleanup_receipts':checks,'this_new_cleanup_files':489,'this_new_cleanup_allocated_GiB':checks[-1]['deleted_allocated_bytes']/2**30,'cumulative_deleted_files':sum(x['deleted_files'] for x in checks),'cumulative_deleted_payload_GiB':sum(x['deleted_payload_bytes'] for x in checks)/2**30,'cumulative_deleted_allocated_GiB':sum(x['deleted_allocated_bytes'] for x in checks)/2**30,'preserved_first_last_CSV_samples':preserved,'old_failed_receipts_byte_unchanged':True,'all336_accepted_pending_native_and_visual_deliverables_retained':True,'scientific_payload_IO':False,'home_available_GiB':free/2**30,'home_floor_GiB':500,'case_credit':0,'failure_classification':'Two converter storage-budget terminations; no physical-failure assertion','additional_failed_attempts_retained':'Used/recovered artifacts and bounded diagnostic/failure samples retained. No blanket deletion by receipt status.'};put(O/'cleanup-actual-results-and-retention-proof.json',proof)
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_194.json';cp=load(prev);assert cp['stage1_visual_accepted_complete_independent_cases']==271;assert len(cp['accepted_decisions'])==271
cp.update(checkpoint=195,at_utc=proof['at_utc'],predecessor=str(prev),predecessor_sha256=sha(prev),home_free_gib=free/2**30,new_accepted_decisions=[],ledger_sha256_at_checkpoint=hashlib.sha256(lb).hexdigest(),ledger_immutable_snapshot={'path':str(O/'resource-ledger-frozen.json'),'sha256':sha(O/'resource-ledger-frozen.json')},active_reservations=ld['reservations'],authorized_work_state='Active271/336: user-authorized failed unused converter CSV cleanup completed0; 489 files freed16GiB, cumulative165? exact total in proof. F5 source192 finished awaiting main acceptance, source193 reviewing actual1130 newly published0. All pending science and accepted products preserved.',previous_goal_turn_classification='Progress: actual registered CPU2 cleanup completed0, 489 temporary failed-converter CSV files removed with stat/receipt/live dependency fences; all prior15997 deleted paths still absent and four first/last samples unchanged; Home floor protected.',actual_progress={'actual_storage_cleanup':{'path':str(O/'cleanup-actual-results-and-retention-proof.json'),'sha256':sha(O/'cleanup-actual-results-and-retention-proof.json')},'previous_scientific_progress_checkpoint':str(prev),'previous_actual_progress_not_reprobed':True},next_executable_tasks=['Adopt source192 actual1152 F5M108T095 personal visual-approved package after main metadata/hash review; independent full801QI already closed1213/1214.','Continue source193 actual1130 F5M088T085 published0 personal review and original1137 render.','Adopt source150 staged membership metadata; source151 checks frozen actual F4first8 Root1093 against exact24 and final48.','Continue source168 own F2RX047 deeper actual native-chain closure and original registered pending renders.'])
cp['authorized_work_state']=cp['authorized_work_state'].replace('cumulative165? exact total in proof','cumulative 16486 files freed about532GiB')
# Retain cumulative scientific charge aliases from the prior checkpoint when the ledger does not provide a canonical counterpart.
for ck,lk in (('attempt_counts','attempt_counts'),('gpu_hours_charged','gpu_hours_charged'),('cpu_core_hours_charged','cpu_core_hours_charged')):
 if lk in ld:cp[ck]=ld[lk]
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_195.json',cp)
(O/'README.md').write_text('已完成用户授权的失败中间产物清理：新增删除489个无人依赖的失败转换临时CSV，约16.03 GiB。保留首末帧、输入、日志、失败收据和原始模拟数据。此前15997个失败中间文件已清理，本次复核全部仍不存在。累计删除16486个文件，约531.54 GiB逻辑数据（约531.54 GiB实际分配空间，以JSON精确值为准）。Home继续保留至少500 GiB。271个已验收案例与所有待验收/运行中产物保留，案例计数未增加。\n')
paths=[str(p.relative_to(R)) for n in (1218,1219,1220,1221) for p in root(n).iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_195.json').relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: verify failed CSV cleanup and retain all accepted pending simulation products','--',*paths],cwd=R,check=True)
print(json.dumps({**{k:v for k,v in proof.items() if k in ('this_new_cleanup_files','this_new_cleanup_allocated_GiB','cumulative_deleted_files','cumulative_deleted_payload_GiB','cumulative_deleted_allocated_GiB','home_available_GiB')},'checkpoint':195,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
