from pathlib import Path
import json,hashlib,subprocess,copy,datetime,collections,os
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,j):p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_278.json';cp=load(cpfile);assert cp['checkpoint']==278 and cp['stage1_visual_accepted_complete_independent_cases']==len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==311
qis=[]
for original,qnum,source,flag in [(1188,1363,212,'all801_geometry_velocity_N3_times_UID_finite_verified'),(1143,1366,193,'all401_UID_axis_identity_N3_finite_active_states_native_actual_times_verified')]:
 p=next(root(qnum).glob('*proof.json'));q=load(p);assert q[flag] is True
 er=q['actual_completed_metadata_evidence']
 for k in ['render_receipt','render_report','render_publish_receipt']:assert sha(er[k]['path'])==er[k]['sha256']
 r=load(er['render_receipt']['path']);pu=load(er['render_publish_receipt']['path']);assert r['status']=='completed' and r['returncode']==0 and pu['status']=='published_after_atomic_rename' and pu['case_id']==q['case_id'];qis.append({'original':original,'physical_case_id':q['physical_case_id'],'main_own_QI':ref(p),'render_receipt':er['render_receipt'],'render_report':er['render_report'],'render_publish_receipt':er['render_publish_receipt'],'actual_native_XMF_plan_field_namespaces':q['actual_native_XMF_plan_field_namespaces'],'source_personal_review':source,'case_credit':0})
F=root(1174);pre=F/'actual-full801-bed-UID-footprint-times-and-scope-independent-review.json';j=load(pre)
for e in j.values():
 if isinstance(e,dict) and 'path' in e and 'sha256' in e:assert sha(e['path'])==e['sha256']
t=load(j['actual_typed_report']['path']);x=load(j['actual_XMF_manifest']['path']);n=load(t['source_provenance']['solver_receipt']['path']);nq=n['request'];b=load(load(j['actual_bed_receipt']['path'])['request']['binding']);canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];sd=b['source_plan_physical_condition_sha256'];assert n['status']=='completed' and n['returncode']==0
assert (canonical,legacy,sd)==('4e06ddfc9c871e619f543397f8faba245de6e24df33950f0561d34ff6a9eb920','e561820d8792eda4b59e77a36cf41b6b9d07953553851b25eba4ad9938dd64e3','7530ddff20117a6d478fba2fc4ec90a05177a2ffccaec383eaf1fe03fc4139a1')
mask={ns:{k:{'present':k in ob,'value':ob.get(k)} for k in ['source_plan_condition_sha256','source_plan_physical_condition_sha256']} for ns,ob in [('native',nq),('XMF',x)]}
for m in mask.values():assert m=={'source_plan_condition_sha256':{'present':False,'value':None},'source_plan_physical_condition_sha256':{'present':True,'value':canonical}}
assert sha(b['source_definition'])==b['source_definition_sha256']==sd and len({canonical,legacy,sd})==3
w=load(F/'enabled-render-wrapper.json');assert w['expected_frames']==t['frames']==x['frames']==801 and w['expected_particles']==t['particles']==x['particles']==194427 and w['expected_contact_sheets']==34
P=Path('/proc/633506');obs=None
if P.exists():
 st=(P/'stat').read_text().rsplit(')',1)[1].split();assert st[19]=='213987092';cmd=(P/'cmdline').read_bytes().split(b'\0');assert cmd[0].endswith(b'/pvpython');out=Path(cmd[cmd.index(b'--output-dir')+1].decode());assert 'root1174' in str(out);obs={'pid':633506,'startticks':'213987092','state':st[0],'private_frame_filename_stat_count':len(list((out/'frames').glob('frame_*.png'))),'private_PNG_payload_IO':False}
for key,p in [('runtime_v2_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',R/'lagrangian-fluid-lab/scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(p)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(r['kind'] for r in ld['attempts']);gpu=sum(r.get('gpu_seconds',0) for r in ld['charges'])/3600;cpu=sum(r.get('cpu_core_seconds',0) for r in ld['charges'])/3600;v=os.statvfs('/home/jade');free=v.f_bavail*v.f_frsize/2**30;now=datetime.datetime.now(datetime.timezone.utc);assert free>=500 and gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and now<datetime.datetime.fromisoformat(cp['deadline_utc'])
O=H/'root_stage1_current311_F5_1188_F2_1143_published_own_QIs_two_personal_reviews_active_nextF5_1174_native_XMF_physicalplan_canonical_durable801QI_1370';np=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_279.json';assert not O.exists() and not np.exists();O.mkdir();entry=O/'after_original1174_terminal_full801_own_QI.py';entry.write_bytes(Path('/tmp/ds02-F5-original1174-full801-own-QI1371.py').read_bytes());pp=O/'current311-two-published-QI-personal-active-next-original1174-live-and-durable801QI-readiness.json'
put(pp,{'at_utc':now.isoformat(),'actual_completed0_published_full_QI_personal_pending':qis,'next_original1174_previsual_dependency_review':ref(pre),'next_original1174_native_canonical':canonical,'next_original1174_typed_legacy':legacy,'next_original1174_bed_SourceDef_FILE':sd,'next_original1174_actual_native_XMF_plan_field_namespaces':mask,'next_original1174_XMF_physical_plan_has_native_canonical_role_and_not_SourceDef_role':True,'next_original1174_same_actual_live_handle':obs,'next_original1174_actual_terminal':ref(F/'controller-result.json') if (F/'controller-result.json').exists() else None,'durable_original1174_only_QI_entrypoint':ref(entry),'future_ownQI1371_unexecuted_no_proof_SHA':True,'command':['python3','-B',str(entry),'1174','1371'],'do_not_rerun_completed_QI':[1349,1350,1355,1359,1363,1366],'case_credit':0,'scientific_payload_IO':False,'no_new_solver_or_render_jobs':True})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);new=copy.deepcopy(cp);new.update(checkpoint=279,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: originalF2 1143 completed0/published/full401 ownQI1366 with genuine initialQA and15 fluidomissions preserved; source193 personalreview reactivated. OriginalF5 1188 completed0/published/full801 ownQI1363 andsource212 personalreview active. NextF5original1174 same actualhandle and both native/XMFphysicalplans canonical pinned, distinctSourceDefFILE/legacy retained, newdurable futureownQI1371 prepared unexecuted. Total311 after two actualcaseacceptances thisturn; no newSCI/renderjobs.',authorized_work_state='Active311/336 pending25. Source212 F5original1188 andsource193 F2original1143 personallyreviewing publishedproducts after ownQI1363/1366. Source179 F5original1174 waitsactual0/pub/durableownQI1371. Next admitted originalrender through unchanged registeredqueue; inspectactualsamehandle. Final F2/F3/F5 delivery onlyafteractual48, numericalprecision unaccepted QNQE0, Homefloor500GiB.')
new['actual_progress']['actual1143_full401_own_QI']=qis[1]['main_own_QI'];new['actual_progress']['current311_two_published_QIs_next1174_durable']=ref(pp);new['source_agents']['f6_endpoint_initial_qa']='fresh193 originalF2 1143 actual0/pub/QI1366 supplied, personal17contacts9keys active';new['source_agents']['production_recovery']='fresh179 originalF5 1174 waitsactual0/pub; durableownQI1371 prepared, XMFphysicalplan nativecanonical ratherthanSourceDefFILE'
new['next_executable_tasks']=['Adopt source212 F5original1188 andsource193 F2original1143 personalreviews after exactfinalcommits/read-only validators/ownQI1363/1366; preserve individual namespace masks, times andF2fifteenfluid omissions with unknowncause.','Observe nextF5original1174 PID633506/start213987092; actual0/pub then newdurable after_original1174_terminal_full801_own_QI.py 1174 1371 once; supplysource179 exactpathSHA forpersonal34contacts9keys.','Inspect next registeredrenderer actuallyadmitted after F2original1143 finishes; preserve PID/startticks and actualtyped/native/XMF roles before future ownQI, neverrestart onobservationtimeout.','Complete remaining25 actualcases then F2/F3/F5final48 primarycatalogs and global336 delivery; source176 assemblyutility requires independent finalintegrity/runtimeunknown review.','Home500GiB floor, cumulative534.4086GiB failedoutputcleanup retained, QNQE0/precision unaccepted.'];put(np,new)
ip=root(1369)/'full336-current311-actual-final48-delivery-progress-index.json';idx=load(ip)
for obj in qis:
 r=next(r for r in idx['cases'] if r['physical_case_id']==obj['physical_case_id']);assert not r.get('accepted_decision');r.update(status='actual-original-render-completed0-published-own-QI-personal-review-pending',current_main_previsual_QI=obj['main_own_QI'],current_actual_render_receipt=obj['render_receipt'],current_atomic_publish_receipt=obj['render_publish_receipt'],current_personal_review_source=obj['source_personal_review'],case_credit=0,prior_controller_observations_are_historical_not_current=True)
idx.update(at_utc=now.isoformat(),source_authoritative_checkpoint=ref(np),previous_index_preserved=ref(ip),new_case_credit=0,actual_unaccepted_completed0_published_physical_cases=[j['physical_case_id'] for j in qis],current311_two_published_QIs_next1174_durable=ref(pp));assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==311;put(O/'full336-current311-actual-final48-delivery-progress-index.json',idx);(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir()]+[str(np.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','DS02: bind two published QI personal reviews and durable next F5 full801 integrity','--',*paths],cwd=R,check=True);print(json.dumps({'checkpoint':279,'accepted':311,'published_own_QI':[1363,1366],'next1174_live':obs,'home_free_GiB':free,'CPUh':cpu,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
