from pathlib import Path
import json,hashlib,datetime,math,re,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.xml','.xmf','.py','.md','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
if not (root(1169)/'controller-result.json').exists():
 print('WAIT: same original1169 has no authoritative terminal; no outputs/sharedstate written.');raise SystemExit(0)
O=H/'root_stage1_F2_RX058_ROT075_actual1169_full401_UID_N3_time_scope_quantified39fluid_omissions_QI_previsual_1251';O.mkdir(exist_ok=False);proofs=[]
try:
 for n in (1169,):
  orig=root(n);reqp=orig/'enabled-full401-render-request.json';q=load(reqp);cr=load(orig/'controller-result.json');assert cr['status']=='completed' and cr['returncode']==0;rp=Path(cr['actual_receipt']);rrp=rp.parent/'render/paraview-full-animation-report.json';pubp=rp.parent/'render/render-publish-receipt.json';r=load(rrp);pub=load(pubp);inputs=q['input_files'];tp=Path(next(p for p in inputs if Path(p).name=='conversion-report.json'));xp=Path(next(p for p in inputs if Path(p).name=='manifest.json'));xmlp=Path(next(p for p in inputs if Path(p).name=='case.xmf'));t=load(tp);x=load(xp);cid=q['case_id'];pid=x['physical_case_id'];pro=t['source_provenance'];qap=Path(next(p for p in x['bound_metadata_sha256'] if Path(p).name=='actual-initial-qa.json'));qar=qap.parent/'execution-receipt.json'
  stage={
   'genuine_gencase':{'receipt':pro['gencase_receipt'],'generated_xml':pro['generated_xml']},
   'initial_native_qa':{'receipt':ref(qar),'report':ref(qap)},
   'full_native_solver':{'receipt':pro['solver_receipt']},
   'typed_conversion':{'receipt':ref(x['typed_receipt']),'report':ref(tp)},
   'n3_xmf':{'receipt':ref(xp.parent.parent/'execution-receipt.json'),'manifest':ref(xp),'xmf_xml':ref(xmlp)},
   f'full_render_root{n}':{'receipt':ref(rp),'animation_report':ref(rrp),'publish_receipt':ref(pubp)}}
  receipts={}
  for key,fields in stage.items():
   for e in fields.values():assert sha(e['path'])==e['sha256']
   receipt=load(fields['receipt']['path']);assert receipt['status']=='completed' and receipt['returncode']==0 and receipt['request']['case_id']==cid;receipts[key]=receipt
  assert sha(qap)==x['bound_metadata_sha256'][str(qap)] and sha(qar)==x['bound_metadata_sha256'][str(qar)]
  qa=load(qap);checks=qa.get('audit',qa)['checks'];assert checks and all(checks.values());native=receipts['full_native_solver'];nq=native['request'];canonical=nq['physical_condition_sha256'];legacy=t['hash_scopes']['physical_condition_sha256'];assert nq['physical_case_id']==pid and canonical==x['canonical_source_physical_condition_sha256'];assert legacy==x['physical_condition_sha256']==x['actual_converter_legacy_scope_sha256']==q['physical_condition_sha256'];scope=t['hash_scopes']['physical_condition'];assert scope['physical_case_id']==pid and scope['schema']=='legacy-owner-scope.v0'
  assert t['conversion_status']=='completed' and t['frames']==x['frames']==r['frames']==r['source_frames']==401 and t['particles']==x['particles']==418104 and t['solver_dimension']['solver_dimension']==3 and x['actual_geometry']['dimension']==3 and not x['actual_geometry']['data2d'];assert t['partvtk_validation']['all_passed'] and all(f['passed'] and f['identity_type_mk_exact'] for f in t['partvtk_validation']['frames']);assert t['typed_identity']['key']=='(Zone,Idp)' and t['typed_identity']['initial_exclusion_ledger']['count']==0 and t['lifecycle']['introduced_ids']=='rejected'
  for k in ('gencase_receipt','solver_receipt','generated_xml','owner_metadata'):
   e=pro[k];assert sha(e['path'])==e['sha256']
  assert pro['gencase_receipt']==stage['genuine_gencase']['receipt'] and pro['solver_receipt']==stage['full_native_solver']['receipt'] and pro['generated_xml']==stage['genuine_gencase']['generated_xml']
  h5=t['output_hdf5'];assert Path(h5).is_file();assert t['output_sha256']==x['source_h5_sha256']==x['trajectory_h5_sha256_producer_attested']==r['source_h5_sha256'];assert r['all_frames_rendered'] and r['actual_times_preserved_exactly'] and r['native_identity_axis_preserved'] and r['source_h5_read_only'] and r['nonfinite_active_states']==0 and not r['diagnostic_only'];assert r['manifest_sha256']==sha(xp) and sha(xmlp)==x['xdmf_sha256']==r['xdmf_sha256_before']==r['xdmf_sha256_after']
  for k in ('n3_xmf',f'full_render_root{n}'):
   a=receipts[k];assert a['input_hashes_at_launch'][h5]==a['input_hashes_after_run'][h5]==t['output_sha256']
  assert receipts[f'full_render_root{n}']['request_sha256']==sha(reqp)
  fs=t['lifecycle']['frame_summary'];ds=r['frame_diagnostics'];grids=ET.parse(xmlp).findall('.//Grid[@GridType="Uniform"]');times=x['actual_time_s'];assert len(fs)==len(ds)==len(grids)==len(times)==401 and times==[f['time'] for f in fs]==[d['actual_time_s'] for d in ds]==[float(g.find('Time').get('Value')) for g in grids];assert times[0]==0 and times[-1]>=4 and all(math.isfinite(v) for v in times) and all(a<b for a,b in zip(times,times[1:]));assert x['fields']['position']['shape']==x['fields']['velocity']['shape']==[401,418104,3];counts={'0':372840,'1':24150,'2':0,'3':21114}
  for i,(f,d,g) in enumerate(zip(fs,ds,grids)):
   assert f['frame']==d['frame']==i and f['active_particles']==d['active'] and f['missing_particles']==d['missing'] and f['active_particles']+f['missing_particles']==418104 and f['missing_type_counts'].get('3',0)==f['missing_particles'];assert all(f['type_counts'][k]+f['missing_type_counts'].get(k,0)==v for k,v in counts.items());assert d['type_counts_active']['fixed']==372840 and d['moving_points']==24150 and d['floating_points']==0 and d['fluid_points']==f['type_counts']['3'] and d['type_counts_active']['unknown']==0;assert d['identity_axis_preserved'] and d['finite_positions_active'] and set(d['finite_fields'])=={'density','mass','pressure','velocity'} and all(e['finite_active'] and e['nonfinite_active']==0 for e in d['finite_fields'].values());assert g.find('Geometry').get('GeometryType')=='XYZ' and g.find('Geometry/DataItem').get('Dimensions')=='418104 3';vv=next(e for e in g.findall('Attribute') if e.get('Name').lower()=='velocity');assert vv.get('AttributeType')=='Vector' and vv.find('DataItem').get('Dimensions')=='418104 3'
  lost=[f for f in fs if f['missing_particles']];life={'final_missing_particles':fs[-1]['missing_particles'],'final_missing_fraction_initial_fluid':fs[-1]['missing_particles']/21114,'final_missing_id_first_producer_attested':fs[-1]['missing_id_first'],'final_missing_ids_sha256_producer_attested':fs[-1]['missing_ids_sha256'],'first_missing_frame':lost[0]['frame'] if lost else None,'max_missing_per_frame':max(f['missing_particles'] for f in fs),'frames_with_any_missing_particle':len(lost),'cumulative_particle_frame_omissions':sum(f['missing_particles'] for f in fs),'unknown_missing_locations_states_and_causes':True,'omission_frame_events_not_unique_final_UID_count':True,'all_fixed_moving_floating_native_UIDs_active_every_frame':True,'no_missing_particle_state_reconstructed':True}
  # First-stage scope preserves quantified loss; the user GOAL does not prescribe a 0.1% numerical-qualification threshold.
  assert life['final_missing_particles']==life['max_missing_per_frame']==39 and life['first_missing_frame']==137 and life['frames_with_any_missing_particle']==264 and life['cumulative_particle_frame_omissions']==9026
  natives=sorted(p.name for p in Path(pro['data_root']).glob('Part_*.bi4') if re.fullmatch(r'Part_\d{4,}\.bi4',p.name));assert natives==[f'Part_{i:04d}.bi4' for i in range(401)];frames=sorted(p.name for p in Path(r['outputs']['frames_dir']).glob('frame_*.png'));assert frames==[f'frame_{i:04d}.png' for i in range(401)];assert len(r['outputs']['contact_sheets'])==17 and [Path(p).name for p in r['outputs']['contact_sheets']]==[f'all_frames_{i:03d}.png' for i in range(17)];assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(rrp)
  proof={'schema':'ds02.main.full401.actual-own-native-typed-XMF-render-QI.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_render_root':n,'case_id':cid,'physical_case_id':pid,'actual_completed_metadata_evidence':stage,'registered_request':ref(reqp),'canonical_actual_native_request_condition_sha256':canonical,'actual_converter_legacy_scope_sha256':legacy,'declared_render_request_condition_role':'Actual converter legacy scope; not native canonical scope','actual_producer_scope_schema':'legacy-owner-scope.v0','legacy_owner_control_metadata_preserved_not_promoted_to_current_native_control':True,'native_request_actual_control_authority':ref(stage['full_native_solver']['receipt']['path']),'manifest_dimension_alias_absent_preserved':'dimension' not in x,'frames':401,'particles':418104,'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'actual_time_window_s':[times[0],times[-1]],'initial_native_type_counts':counts,'lifecycle':life,'producer_attested_immutable_science_hashes_verified_from_stage_metadata_only':{'H5':t['output_sha256'],'raw_tree_before_and_after':pro.get('raw_tree_before_after')},'all401_native_and_render_frame_filenames_present':True,'source_h5_stat_only':True,'actual_contact_sheets':17,'actual_keyframe_indices':list(range(0,401,50)),'personal_visual_review_pending_main_adoption':True,'bounded_omission_scope_note':'39/21114 initial fluid UID missing (about0.1847%) at terminal; all401 counts and mask preserved, locations/states/causes unknown; not a closed-fluid trajectory or strict container guarantee','no_user_numeric_threshold_inferred':True,'new_case_credit':0,'q_n_granted':False,'q_e_granted':False,'numerical_precision_accepted':False,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False}
  p=O/f'actual{n}-full401-independent-UID-N3-time-scope-QI-proof.json';put(p,proof);proofs.append(ref(p));print(json.dumps({'actual':n,'canonical':canonical,'legacy':legacy,'QI_full401':True,'loss':life}),flush=True)
 put(O/'batch-independent-full401-QI-proof-index.json',{'proofs':proofs,'new_case_credit':0,'main_scientific_payload_IO':False});(O/'independent-review-source.py').write_bytes(Path(__file__).read_bytes())
except BaseException as e:
 put(O/'preparation-failure.json',{'error':repr(e),'already_written_valid_proofs':proofs,'no_new_case_credit':True,'main_scientific_payload_IO':False});raise

import subprocess
paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: close F2 rx058 rot075 actual1169 full401 integrity with39 quantified fluid omissions','--',*paths],cwd=R,check=True);print(subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip())
