from pathlib import Path
import json,hashlib,subprocess,datetime,shutil
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n:03d}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.py','.md'};return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
def put(p,d):
 with Path(p).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
cp_path=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_188.json';cp=load(cp_path);assert cp['stage1_visual_accepted_complete_independent_cases']==270 and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_189.json').exists()
prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_191_f5_fresh117_vs_current48_membership_gap_explanation_v1');commit='bae9ea8d5b68b1142029c190e8f607b7a791d1de';files=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(prefix)],cwd=W,text=True).splitlines();assert len(files)==7
before={}
for rel in files:
 raw=subprocess.check_output(['git','show',commit+':'+rel],cwd=W);assert raw==(W/rel).read_bytes();dst=R/rel
 if dst.exists():assert dst.read_bytes()==raw
 else:dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(raw)
 before[str(W/rel)]=sha(W/rel);before[str(dst)]=sha(dst)
P=W/prefix;rv=subprocess.run(['python3','-B',str(P/'scripts/validate_fresh191.py')],cwd=P,text=True,capture_output=True);assert rv.returncode==0 and json.loads(rv.stdout)['all_checks_pass'];assert before=={p:sha(p) for p in before}
sources=load(P/'metadata/evidence-sources.json');source_records=sources['sources'];assert isinstance(source_records,list)
for s in source_records:assert sha(s['path'])==s['sha256']
audit=load(P/'metadata/membership-gap-audit.json');assert len(audit['rows'])==10
registry=load(root(1205)/'full336-role-aware-physical-registration-progress-index.json');final48={a['physical_case_id'] for a in registry['cases'] if a['family_id']=='F5'};assert len(final48)==48
assert all(a['physical_case_id'] not in final48 for a in audit['rows'])
first8_path=root(1093)/'FIRST8_PER_FAMILY_STAGE1_SUBSET56.json';first8src=load(R/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_190_f5_first8_first24_current48_membership_audit_v1/metadata/first8-visual-subset.json');frozen8=[a['physical_case_id'] for a in first8src['cases']];assert len(frozen8)==len(set(frozen8))==8 and set(frozen8)<=final48
ordered=[]
for path in cp['accepted_decisions']:
 a=load(path)
 if a['family_id']=='F5':ordered.append({'physical_case_id':a['physical_case_id'],'accepted_decision':ref(path),'source_condition_declaration':a['physical_condition_sha256']})
assert len(ordered)==11 and set(frozen8)<={a['physical_case_id'] for a in ordered}<=final48
# This is the actual visual delivery stage, not a relabeling of historical disabled recipes.
future24_order=frozen8+[a['physical_case_id'] for a in ordered if a['physical_case_id'] not in frozen8];assert len(future24_order)==11
handles=[]
for n in (1152,1130,951):
 p=root(n);v=load(p/'controller-launch-process.json');sp=Path('/proc')/str(v['pid'])/'stat';same=False;state=None
 if sp.exists():parts=sp.read_text().rsplit(')',1)[1].split();state=parts[0];same=state!='Z' and parts[19]==str(v['proc_start_ticks'])
 result=p/'controller-result.json';assert same or result.exists();handles.append({'root':n,'original_launch':ref(p/'controller-launch-process.json'),'same_PID_startticks_live':same,'proc_state':state,'actual_terminal':ref(result) if result.exists() else None,'wait_is_not_restart':True})
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert hashlib.sha256(path.read_bytes()).hexdigest()==cp['unmodified_guards'][key]
O=H/'root_stage1_source191_F5_historical_disabled_candidates_separate_actual_first8_to_first24_visual_delivery_contract_checkpoint_1209';O.mkdir(exist_ok=False)
put(O/'source191-exact-adoption-readonly-source-classification.json',{'source_commit':commit,'exact_files':[ref(R/f) for f in files],'unchanged_source_and_adopted_hashes':before,'readonly_validator_returncode':rv.returncode,'readonly_validator_stdout':rv.stdout,'actual_source_metadata_refs':source_records,'ten_current48_nonmembers':audit['rows'],'classification':'historical disabled prospective candidates; no accepted-member gap in current checkpoint','not_failed_or_resolution_replicas_by_unsupported_inference':True,'six_fresh110_exclusion_declaration_mismatch_preserved':True,'new_case_credit':0,'main_scientific_payload_IO':False})
batch=O/'F5-actual-visual-first8-to-first24-to-final48-delivery-contract.json';put(batch,{'schema':'ds02.stage1.F5.actual-visual-delivery-subset-contract.v1','first8_frozen_authority':ref(first8_path),'first8_physical_case_ids':frozen8,'final48_physical_case_ids':sorted(final48),'actual_visually_accepted_current':11,'actual_accepted_evidence_in_checkpoint_order':ordered,'first24_status':'incomplete: only11 actual accepted cases; never implied by historical117 candidate count','first24_realized_prefix':future24_order,'first24_extension_policy':'Preserve all frozen first8 physical IDs, then append independently visually accepted distinct physical IDs from current final48 in authoritative checkpoint acceptance order until24. Freeze the actual24 set at that point. Replicas, reruns, temporal slices and view aliases never enter.','arbitrary_sorted_first24_selection':False,'first8_subset_realized_prefix_subset_final48_verified':True,'historical117_candidate_plan_preserved':ref(P/'metadata/membership-gap-audit.json'),'historical_prospective_nonmembers_never_recounted_or_claimed_failed':True,'new_case_credit':0,'Q_N':0,'Q_E':0})
put(O/'original1152-1130-951-current-live-handle-observation.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'handles':handles,'observation_only_no_future_receipt_hash_promise':True,'new_case_credit':0})
raw=(D/'runtime/resource-ledger.json').read_bytes();(O/'resource-ledger-frozen.json').write_bytes(raw);ledger=json.loads(raw);free=shutil.disk_usage('/home/jade').free/2**30;assert free>=500
cp.update(checkpoint=189,at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),predecessor=str(cp_path),predecessor_sha256=sha(cp_path),new_accepted_decisions=[],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(O/'resource-ledger-frozen.json'),active_reservations=ledger['reservations'],attempt_counts={k:sum(a['kind']==k for a in ledger['attempts']) for k in ['qualification','production','cpu']},gpu_hours_charged=sum(a.get('gpu_seconds',0) for a in ledger['charges'])/3600,cpu_core_hours_charged=sum(a.get('cpu_core_seconds',0) for a in ledger['charges'])/3600,previous_goal_turn_classification='Progress: exactsource191 explains10 historicaldisabledprospective F5source117nonmembers; mainverified source110/117/169 refs and preservesdiscrepancy. Actualvisual first8subset final48 frozen; actualfirst24 incomplete11/24 with explicitfrozen8 +newdistinctacceptedcheckpointorder policy, no arbitraryrosterreplacement orfakecompletion. Original1152/1130/951 samehandles reverified.',authorized_work_state='Active270/336: full836actual1128 QI0 andpublish verified, personal148reviewpending. TwoF5full801renderoriginal1152/1130 live, source192 nextpersonalreview after0. F5first24actualvisual batch remains11/24; historicaldisabled10are notdeliveredcases. Original951lastF6waitingunchanged.')
cp['actual_progress']['F5_actual_first8_first24_final48_visual_delivery_contract']=ref(batch);cp['actual_progress']['source191_disabled_prospective_nonmember_classification']=ref(O/'source191-exact-adoption-readonly-source-classification.json');cp['source_agents']['f5_bed_recovery']='fresh192 waitoriginalactual1152 full801 thenpersonal34contacts9keys; next1130, no extra wait-onlypackages';cp['next_executable_tasks']=['Adopt source148 actual1128 F3personal35contacts9keys andcreditonly ifownvisualpasses','Source192 actual1152/1130 F5real0publish personal34contacts9keys; preserveactualUID/bed/scopeweakshoreline limits','Source165 F2actualfirst8/24physicalmembership ornextpublishedpersonalreview','ExtendF5actualfirst24 incheckpointacceptanceorder preservingfrozen8 andcurrentfinal48; incompleteuntil24realacceptedcases','Continue remaining66cases andoriginal951lastF6; Q-N/Q-Eremain0']
put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_189.json',cp);(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=files+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_189.json').relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: separate disabled F5 candidate rosters from actual staged visual delivery','--',*paths],cwd=R,check=True);print({'checkpoint':189,'accepted':270,'F5actualbatch':11,'historicalprospective_nonmembers':10,'HomeGiB':free,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
