from pathlib import Path
import json,hashlib,subprocess,re,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'));load=lambda p:json.loads(Path(p).read_text());put=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
forbidden={'.h5','.hdf5','.bi4','.ibi4','.obi4','.csv','.dat','.vtk','.vtu','.npy','.npz'}
def sha(p):
 p=Path(p);assert p.suffix.lower() not in forbidden;return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)}
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_123_f3_actual884_948_typed157_batch_v1';commit='b1bd45a46f0018dcbaf870276c70555a4d18401b';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert names;adopted=[]
for name in names:
 assert Path(name).suffix in {'.json','.py','.md'};raw=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert raw==(W/name).read_bytes();p=R/name;assert not p.exists();p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw);adopted.append(ref(p))
P=R/prefix;O=H/'root_stage1_F3_actual884948_12_full836_explicit_v1_typed157_Home4GiB_fairCPU2_batch_978';O.mkdir(exist_ok=False)
for name in ['validate_fresh123.py','metadata_preflight_batch.py']:
 report=O/(name+'.actual.json');s=subprocess.run([str(L/'.venv/bin/python'),str(P/'scripts'/name),'--package',str(P),'--output',str(report)],capture_output=True,text=True);put(O/(name+'.result.json'),{'returncode':s.returncode,'stdout':s.stdout[-1800:],'stderr':s.stderr[-1800:]});assert s.returncode==0,(name,s.stdout,s.stderr)
cp=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_132.json');accepted=[load(p) for p in cp['accepted_decisions']];physical_ids={z.get('physical_case_id',z['case_id']) for z in accepted};scopes={z['physical_condition_sha256'] for z in accepted};active974=load(root(974)/'enabled-typed-request.json');physical_ids.add(active974['physical_case_id']);scopes.add(active974['physical_condition_sha256']);controller=O/'batch-typed-controller.py';controller.write_text("from pathlib import Path\nimport json,runpy,time,hashlib,datetime\nO=Path(__file__).parent\nc=json.loads((O/'controller-config.json').read_text())\nassert hashlib.sha256(Path(c['fair_dispatch']['path']).read_bytes()).hexdigest()==c['fair_dispatch']['sha256']\ndispatch=runpy.run_path(c['fair_dispatch']['path'])['dispatch']\nresults=[]\nfor i,qp in enumerate(c['requests']):\n q=json.loads(Path(qp).read_text())\n assert hashlib.sha256(Path(qp).read_bytes()).hexdigest()==c['request_sha256'][qp]\n r=dispatch(qp,serial_conversion=True)\n rp=Path(q['attempt_root'])/'execution-receipt.json'\n a=json.loads(rp.read_text()) if rp.exists() else {}\n report=Path(q['attempt_root'])/'conversion-report.json'\n t=json.loads(report.read_text()) if report.exists() else {}\n passed=(r.returncode==0 and a.get('status')=='completed' and a.get('returncode')==0 and t.get('frames')==836 and t.get('particles')==179208 and t.get('partvtk_validation',{}).get('all_passed') is True and t.get('hash_scopes',{}).get('physical_condition_sha256')==q['actual_converter_scope_sha256'])\n result={'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'request':qp,'actual_receipt':str(rp),'status':a.get('status'),'returncode':a.get('returncode'),'launcher_returncode':r.returncode,'actual_full836_conversion_pass':passed,'stdout_tail':r.stdout[-1800:],'stderr_tail':r.stderr[-1800:],'case_credit':0}\n results.append(result)\n progress={'results':results,'not_submitted':len(c['requests'])-len(results),'case_credit':0,'source_and_science_recipe_unchanged':True}\n (O/'actual-progress.json').write_text(json.dumps(progress,indent=2)+'\\n')\n print(json.dumps(result),flush=True)\n if not passed:\n  (O/'controller-result.json').write_text(json.dumps({'status':'stopped_for_primary_failure_classification','failed_case':q['case_id'],'not_submitted':progress['not_submitted'],'returncode':r.returncode or 1,'case_credit':0},indent=2)+'\\n')\n  raise SystemExit(r.returncode or 1)\n time.sleep(4)\n(O/'controller-result.json').write_text(json.dumps({'status':'completed','returncode':0,'actual_completed_conversions':len(results),'case_credit':0},indent=2)+'\\n')\n")
fair=root(928)/'fair_CPU_dispatch.py';base=load(root(974)/'enabled-typed-request.json');enabled=[];rows=[];hash_cache={};(O/'requests').mkdir()
for source in sorted((P/'requests').glob('*.json')):
 q=load(source);assert q['case_id']!=active974['case_id'] and q['physical_case_id'] not in physical_ids and q['physical_condition_sha256'] not in scopes;physical_ids.add(q['physical_case_id']);scopes.add(q['physical_condition_sha256']);native=q['actual_native_dependency'];assert sha(native['receipt'])==native['receipt_sha256'];rc=load(native['receipt']);assert (rc['status'],rc['returncode'])==('completed',0);assert rc['request']['case_id']==q['case_id'];cmd=q['command'].copy();dr=Path(cmd[cmd.index('--data-root')+1]);files=sorted(p.name for p in dr.iterdir() if re.fullmatch(r'Part_[0-9]+\.bi4',p.name));assert files==[f'Part_{i:04d}.bi4' for i in range(836)];owner=load(q['actual_converter_owner']['path']);actual=hashlib.sha256(json.dumps(owner['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert actual==q['actual_converter_scope_sha256']==q['physical_condition_sha256'];assert q['expected_particles']==179208 and q['expected_frames']==836 and q['expected_dimension']==3 and q['cpu_threads']==2;assert sha(cmd[1])=='37fe7eaff4405e9ba6d9b7f666a53d7c02ee65fc6f30992fc1a8fdb0d8a61b11';md=q['input_sha256'].copy();assert set(md)==set(q['input_files'])
 for p,digest in md.items():
  assert Path(p).is_absolute();actual_hash=hash_cache.setdefault(p,sha(p)) if p not in hash_cache else hash_cache[p];assert actual_hash==digest,(p,actual_hash,digest)
 for p in [controller,fair,O/'validate_fresh123.py.actual.json',O/'metadata_preflight_batch.py.actual.json',source]:md[str(p)]=sha(p)
 aid='root-stage1-f3-'+q['case_id'].lower()+'-actual-native0-full836-typed157-home4gib-root978';ar=D/'families/F3'/q['case_id']/aid;assert not ar.exists();cmd[cmd.index('--staging-root')+1]='/tmp/ds02-nvme-typed-cache-root978-'+q['case_id'].lower();assert not Path(cmd[cmd.index('--staging-root')+1]).exists();cmd[cmd.index('--current-attempt-id')+1]=f"F3/{q['case_id']}/{aid}";q.update({k:base[k] for k in ['root_dataset_inventory_profile','root_inventory_policy_sha256','root_actual_launch_source','root_actual_launch_source_sha256','environment_policy']});q.update(attempt_id=aid,attempt_root=str(ar),command=cmd,input_files=sorted(md),input_sha256=md,worktree_root=str(R),disabled=False,source_only=False,launch=True,launch_allowed=True,execution_allowed=True,root_review_required=False,root_actual_new_output_layout='flat trajectory.h5 and conversion-report.json; unmodified157 private NVMe then capped Home publication',cpu_task_kind='conversion',cpu_threads=2,estimated_storage_bytes=4*1024**3,case_credit=0);qp=O/'requests'/(q['case_id']+'-enabled-typed-request.json');put(qp,q);enabled.append(str(qp));rows.append({'case_id':q['case_id'],'physical_case_id':q['physical_case_id'],'physical_condition_sha256':actual,'native_receipt':ref(native['receipt']),'native_part_filename_count':836,'owner':ref(q['actual_converter_owner']['path']),'future_hashes_null':q['future_input_sha256'],'enabled_request':ref(qp),'actual_typed_case_credit':0})
assert len(enabled)==12;put(O/'controller-config.json',{'requests':enabled,'request_sha256':{p:sha(p) for p in enabled},'fair_dispatch':ref(fair),'effective_shared_serial_conversion_concurrency':1,'source_doc_cap2_is_ceiling_not_claim_of2_actual_conversions':True,'cooperative_yield_between_admitted_jobs_seconds':4,'case_credit':0});put(O/'source123-adoption-and-primary-12case-metadata-review.json',{'source_commit':commit,'adopted_files':adopted,'cases':rows,'actual_native_completed0_full836_each':True,'independent_explicit_v1_owner_scopes':True,'native974_current_case_and_all204_accepted_excluded':True,'metadata_hashes_and_absolute_paths_closed_each':True,'actual_source_scope_metadata_preflight12pass':True,'science_payload_IO_by_main':False,'raw_payload_digest_claimed_by_main':False,'actual_typed_and_visual_credit':0,'Home_floor_GiB':500,'per_actual_output_cap_GiB':4,'serial2CPU_not12simultaneous':True,'case_credit':0});(O/'preparation-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(p['path']).relative_to(R)) for p in adopted]+[str(p.relative_to(R)) for p in O.rglob('*') if p.is_file()];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: register12 distinct actual F3 full836 native cases for unchanged capped157 conversions','--',*paths],cwd=R,check=True);print({'root':str(O),'enabled_cases':len(enabled),'source_files':len(adopted),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()})
