from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');O=H/'root_stage1_F4_delegated125_actual856_two_full1201_visual_integration_921';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_121.json')['accepted_decisions'];assert len(prior)==195;ids={load(p).get('physical_case_id',load(p)['case_id']).replace('F4_DROP_B08_','F4_DROP_') for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior};commit=subprocess.check_output(['git','rev-parse','efe74cd9d4b058eba0fd6552786cdc4cf5947296'],cwd=W,text=True).strip();S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_125_*'));rel=S.relative_to(W);adopted=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
 p=W/name;blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert p.read_bytes()==blob and p.suffix in {'.json','.md','.py'};dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==blob;dst.write_bytes(blob);adopted.append(ref(dst))
P=R/rel;idx=load(P/'metadata/review-index.json');assert idx['reviewer']=='/root/f6_endpoint_initial_qa' and len(idx['cases'])==2;decisions=[]
for row in idx['cases']:
 cl=P/'metadata'/Path(row['metadata_closure_path']).name;c=load(cl);cid=c['case_id'];pid=c['physical_case_id'];raw=c['producer_metadata'];sc=c['scope_separation'];sc={**sc,'actual_owner_metadata_file':sc['converter_owner_file']['path'],'actual_owner_metadata_file_sha256':sc['converter_owner_file']['sha256']};m={'source_files':c['source_files'],'gencase':{'receipt':raw['gencase']['receipt']['file'],'prepared_input_report':raw['gencase']['prepared_report']},'basic_initial_qa':{'receipt':raw['initial_geometry_qa']['receipt']['file'],'pass':raw['initial_geometry_qa']['pass']},'full_native_receipt':raw['full_native']['receipt']['file'],'native_initial_frame0_qa':{'receipt':raw['native_initial_frame0_qa']['receipt']['file'],'pass':raw['native_initial_frame0_qa']['pass']},'typed_receipt':raw['typed_conversion']['receipt']['file'],'xmf_manifest':{'file':raw['xmf']['manifest']},'conversion_report':{'file':raw['typed_conversion']['report']}};c['selected_root715_terminal_evidence']={'root715_execution_receipt':c['root856_terminal_evidence']['render_receipt']['file'],'render_report':c['root856_terminal_evidence']['render_report']['file']};dg=sc['actual_converter_physical_condition_sha256'];assert pid not in ids and dg not in hashes and row['status']==c['visual_decision']['status']=='visual-approved-by-delegated-agent';assert c['visual_decision']['reviewed_all_contact_sheets_and_key_frames'] and not c['visual_decision']['root_personal_inspection_claim'];ev={}
 for v in m['source_files']:assert sha(v['path'])==v['sha256']
 receipts={'gencase':m['gencase']['receipt'],'basic_qa':m['basic_initial_qa']['receipt'],'native':m['full_native_receipt'],'frame0_qa':m['native_initial_frame0_qa']['receipt'],'typed':m['typed_receipt'],'render':c['selected_root715_terminal_evidence']['root715_execution_receipt']}
 xref=m['xmf_manifest']['file'];assert sha(xref['path'])==xref['sha256'];x=load(xref['path']);xr=Path(xref['path']).parent.parent/'execution-receipt.json';receipts['xmf']=ref(xr)
 for k,v in receipts.items():
  assert sha(v['path'])==v['sha256'];r=load(v['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;ev[k+'_receipt']=ref(v['path'])
 assert sha(sc['actual_owner_metadata_file'])==sc['actual_owner_metadata_file_sha256'];assert m['basic_initial_qa']['pass'] and m['native_initial_frame0_qa']['pass'];p=load(m['gencase']['prepared_input_report']['path']);assert sha(m['gencase']['prepared_input_report']['path'])==m['gencase']['prepared_input_report']['sha256'] and p['actual_total_particles']==83233 and p['actual_generated_constants']['data2d']['value']=='false' and p['generated_xml_particle_counts']=={'fixed':24161,'moving':0,'floating':0,'fluid':59072}
 cp=m['conversion_report']['file'];assert sha(cp['path'])==cp['sha256'];t=load(cp['path']);assert t['conversion_status']=='completed' and t['frames']==1201 and t['particles']==83233 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'] and t['hash_scopes']['physical_condition_sha256']==dg;assert hashlib.sha256(json.dumps(t['hash_scopes']['physical_condition'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg;assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=1.2 and t['time_evidence']['strictly_increasing'];assert x['frames']==1201 and x['particles']==83233 and x['source_h5_sha256']==t['output_sha256'] and x['physical_condition_sha256']==dg;xf=x['xdmf'];assert sha(xf)==x['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==1201 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='83233 3' for g in gs)
 rr=c['selected_root715_terminal_evidence']['render_report'];assert sha(rr['path'])==rr['sha256'];a=load(rr['path']);assert a['frames']==a['source_frames']==1201 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(xref['path']) and a['source_h5_sha256']==t['output_sha256'] and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf);fs=t['lifecycle']['frame_summary'];ads=a['frame_diagnostics'];assert len(fs)==len(ads)==1201 and all(f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in ads);assert all(f['missing_particles']==g['missing'] for f,g in zip(fs,ads));maximum=max(f['missing_particles'] for f in fs);events=sum(f['missing_particles']>0 for f in fs);assert maximum==c['lifecycle']['maximum_missing_particles_per_frame'] and events==c['lifecycle']['transient_missing_frame_count'] and fs[-1]['missing_particles']==c['lifecycle']['final_frame_missing_particles'];pngp=P/'metadata'/Path(row['png_hash_manifest_path']).name;png=load(pngp);assert png['computed_after_view_image'] and png['viewed_with']=='view_image' and len(png['contact_sheets'])==51 and len(png['key_frames'])==9
 for v in png['contact_sheets']+png['key_frames']:assert sha(v['path'])==v['sha256']
 ev.update(typed_report=ref(cp['path']),xmf_manifest=ref(xref['path']),render_report=ref(rr['path']),prepared_input_report=ref(m['gencase']['prepared_input_report']['path']))
 d={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':row['status'],'family_id':'F4','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'source_review_commit':commit,'source_review_closure':ref(cl),'visual_reviewer':idx['reviewer'],'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':c['visual_decision']['observations'],'agent_limitations':c['visual_decision']['limitations'],'scope_separation':sc,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':png,'actual_frames':1201,'actual_particles':83233,'actual_fluid_particles':59072,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':maximum,'final_missing_particle_count':fs[-1]['missing_particles'],'final_missing_UIDs':fs[-1]['missing_id_first'],'missing_frame_event_count':events,'delegated_lifecycle_original':c['lifecycle'],'lifecycle_limitation':'Late native identity exclusions retained without filling; cause unqualified; final UID list derives only from actual producer metadata','excluded_original_CPU_prelaunch_failure':{'status':'prior_CPU_capacity_prelaunch_failure_retained_in_original_root856_source_gate','main_did_not_change_prior_requests_or_receipts':True},'scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':195+len(decisions),'resulting_count':196+len(decisions)};dp=O/(cid+'-delegated-visual-decision.json');put(dp,d);decisions.append(str(dp));ids.add(pid);hashes.add(dg)
put(O/'actual-integration-review.json',{'source_commit':commit,'adopted_files':adopted,'source_adopted_byte_exact':True,'previous_count':195,'resulting_count':195+len(decisions),'independent_case_increment':len(decisions),'decisions':decisions,'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'new_cases':len(decisions),'accepted':195+len(decisions)})
