from pathlib import Path
import json,hashlib,subprocess,copy,datetime,os,collections
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02')
load=lambda p:json.loads(Path(p).read_text());root=lambda n:next(H.glob(f'root*_{n}'))
def sha(p):
 p=Path(p);assert p.suffix.lower() in {'.json','.jsonl','.py','.md','.xml','.xmf','.txt','.log','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
commit='7b789d3ebfc63cc770660ce23dcfb137746326c6';prefix=Path('lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_161_f3_p1200_ay0320_personal_visual_review_v1');v=load('/tmp/ds02-source161-main-readonly-validation.json');assert v['source_commit']==commit and v['validator_returncode']==0 and v['source_bytes_unchanged'];blobs={}
files=sorted(p for p in (W/prefix).rglob('*') if p.is_file());assert len(files)==7
for p in files:
 rel=p.relative_to(W);b=subprocess.check_output(['git','show',f'{commit}:{rel}'],cwd=W);assert p.read_bytes()==b and hashlib.sha256(b).hexdigest()==v['source_file_hashes_before_and_after'][str(rel)];assert not (R/rel).exists() or (R/rel).read_bytes()==b;blobs[rel]=b
P=W/prefix;cid='F3_STAGE1_DP006_P1200_AY0320';pid='F3_TWOAXIS_P1200_AY0320_STAGE1_FIRST48_PITCH_VARIANT';visual=load(P/f'metadata/visual-review/{cid}-delegated-visual-decision.json');chain=load(P/f'metadata/chain-audit/{cid}.json');png=load(P/f'metadata/png-hashes/{cid}.json');provenance=load(P/'metadata/source-review-provenance.json');qi_path=root(1262)/'actual1047-full836-completed-QI-UID-N3-native-scope-previsual-proof.json';qi=load(qi_path)
assert all(z['case_id']==cid and z['physical_case_id']==pid for z in (visual,chain,png,provenance,qi));assert visual['status']=='visual-approved-by-delegated-agent' and visual['visual_reviewer']=='/root/production_recovery';assert not visual['limits']['q_n_granted'] and not visual['limits']['q_e_granted'] and visual['limits']['case_credit']==0;assert chain['actual_paths']['qi_proof']['sha256']==sha(qi_path)==visual['chain_evidence']['qi_proof_sha256']
for e in chain['actual_paths'].values():assert sha(e['path'])==e['sha256']
for e in qi['actual_completed_receipts'].values():
 assert sha(e['path'])==e['sha256'];z=load(e['path']);assert z['status']=='completed' and z['returncode']==0 and z['request']['case_id']==cid
native=load(qi['actual_completed_receipts']['native']['path']);typed=load(qi['typed_report']['path']);xm=load(qi['XMF_manifest']['path']);render=load(qi['render_report']['path']);pub=load(qi['publish']['path']);canonical=native['request']['physical_condition_sha256'];actual=typed['hash_scopes']['physical_condition_sha256'];assert canonical==actual==qi['native_request_condition_sha256']==qi['actual_converter_condition_sha256']==visual['scope_roles']['native_canonical'];assert typed['hash_scopes']['physical_condition']['schema']=='ds-data-02.physical-binding.v1' and typed['hash_scopes']['physical_condition']['physical_case_id']==pid
params=typed['hash_scopes']['physical_condition']['parameters'];assert params['nominal_pitch_multiplier']==chain['condition_metadata']['nominal_pitch_multiplier']==1.2 and params['transverse_amplitude_m_s2']==chain['condition_metadata']['transverse_amplitude_m_s2']==.32 and params['actual_forcing_sha256']==chain['condition_metadata']['actual_forcing_sha256'] and params['forcing_source_sha256']==chain['condition_metadata']['forcing_source_sha256'];assert typed['frames']==xm['frames']==render['frames']==836 and typed['particles']==xm['particles']==179208 and render['source_frames']==836
assert qi['all836_uid_type_mk_finite_geometry_velocity_N3_and_actual_times_verified'] and qi['all_native_UIds_active_each_frame'];assert pub['status']=='published_after_atomic_rename' and pub['case_id']==cid and pub['report_sha256_after_rebind']==sha(qi['render_report']['path']);published={e['relative_path']:e for e in pub['files_excluding_receipt']};outdir=Path(pub['published_output_root']);assert len(png['entries'])==44
for e in png['entries']:
 p=Path(e['path']);relative=str(p.relative_to(outdir));assert relative==e['relative_path'] and relative in published;pe=published[relative];assert e['viewed'] and e['view_method']=='view_image' and sha(p)==e['sha256']==pe['sha256'] and p.stat().st_size==e['bytes']==pe['bytes']
contacts=sorted([e for e in png['entries'] if e['role']=='contact_sheet'],key=lambda e:e['contact_index']);keys=sorted([e for e in png['entries'] if e['role']=='event_keyframe'],key=lambda e:e['frame_index']);assert [e['contact_index'] for e in contacts]==list(range(35)) and [e['frame_index'] for e in keys]==[0,104,208,312,417,521,626,730,835]
ps=visual['physical_screen'];assert all(ps[k] is False for k in ['gross_scene_loss','initial_state_abnormal','obvious_bulk_breakup','obvious_severe_bed_penetration','obvious_whole_domain_explosion','sudden_truncation']);assert ps['right_edge_crest_observed'] and ps['display_scale_specks_observed'];assert chain['condition_metadata']['fluid_particles']==67500
now=datetime.datetime.now(datetime.timezone.utc);assert datetime.datetime.fromisoformat(visual['reviewed_at_utc'].replace('Z','+00:00'))<=now
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_222.json';cp=load(cpfile);assert cp['checkpoint']==222 and cp['stage1_visual_accepted_complete_independent_cases']==282 and cp['accepted_per_family']['F3']==37 and len(cp['accepted_decisions'])==282
old=[load(p) for p in cp['accepted_decisions']];assert pid not in {z.get('physical_case_id',z['case_id']) for z in old};idxp=root(1261)/'full336-current282-actual-final48-delivery-progress-index.json';idx=load(idxp);targets=[r for r in idx['cases'] if r['physical_case_id']==pid];assert len(targets)==1 and not targets[0].get('accepted_decision');assert targets[0]['native_request_scope']['sha256']==canonical
for z in idx['cases']:
 if z.get('accepted_decision'):assert z.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(d['kind'] for d in ld['attempts']);gpu=sum(d.get('gpu_seconds',0) for d in ld['charges'])/3600;cpu=sum(d.get('cpu_core_seconds',0) for d in ld['charges'])/3600;sv=os.statvfs('/home/jade');free=sv.f_bavail*sv.f_frsize/2**30;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720 and free>=500
O=H/'root_stage1_source161_F3_P1200AY0320_actual1047_personal35contacts_ninekeys_full836QI_native_typed_plan_role_closure_acceptance_1264';cpnew=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_223.json';assert not O.exists() and not cpnew.exists()
O.mkdir();adopted=[]
for rel,b in blobs.items():
 p=R/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'source161-readonly-validator-observation.json';vp.write_bytes(Path('/tmp/ds02-source161-main-readonly-validation.json').read_bytes());scope=O/'source161-original-unresolved-typed-fields-and-source-plan-label-role-closure.json';put(scope,{'original_chain_typed_scope_null':chain['scope_roles']['actual_typed_converter']['physical_condition_sha256'],'original_provenance_typed_scope_null':provenance['scope_role_boundary']['actual_typed_scope_sha256'],'original_visual_typed_scope_present':visual['scope_roles']['actual_typed_converter'],'original_nulls_are_unresolved_snapshot_not_actual_field_absence':True,'actual_typed_scope_field_present':'physical_condition_sha256' in typed['hash_scopes'],'actual_typed_condition_sha256':actual,'actual_typed_schema':typed['hash_scopes']['physical_condition']['schema'],'actual_typed_report':qi['typed_report'],'original_source_plan_label_sha256':visual['scope_roles']['source_plan'],'original_source_plan_label_role':'review source-condition identifier; not a declaration that runtime native or XMF source_plan fields exist','actual_native_source_plan_field_present':'source_plan_physical_condition_sha256' in native['request'],'actual_native_source_plan_field_value':native['request'].get('source_plan_physical_condition_sha256'),'actual_XMF_source_plan_field_present':'source_plan_physical_condition_sha256' in xm,'actual_XMF_source_plan_field_value':xm.get('source_plan_physical_condition_sha256'),'actual_field_absence_not_filled':True,'no_SourceDef_hash_inferred':True,'original_source_bytes_preserved':True,'new_case_credit':0})
dp=O/f'{cid}-delegated-visual-decision.json';decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now.isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F3','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':actual,'source_review_commit':commit,'source_visual_review':ref(P/f'metadata/visual-review/{cid}-delegated-visual-decision.json'),'source_review_chain':ref(P/f'metadata/chain-audit/{cid}.json'),'source_provenance':ref(P/'metadata/source-review-provenance.json'),'source_scope_roles_clarification':ref(scope),'independent_full836_QI_proof':ref(qi_path),'actual_completed_metadata_evidence':qi['actual_completed_receipts'],'typed_report':qi['typed_report'],'xmf_manifest':qi['XMF_manifest'],'xmf_xml':qi['XMF_XML'],'render_report':qi['render_report'],'render_publish_receipt':qi['publish'],'full_native_frames':836,'particles':179208,'fluid_particles':67500,'actual_time_window_s':qi['actual_time_window_s'],'scope_schema':qi['scope_schema'],'nominal_pitch_multiplier':1.2,'transverse_amplitude_m_s2':.32,'actual_forcing_sha256':params['actual_forcing_sha256'],'forcing_source_sha256':params['forcing_source_sha256'],'all836_UID_N3_finite_actual_times_QI_verified':True,'source_initial_forcing_scope_closed_by_actual_QI':True,'agent_personally_viewed_all_contacts_and_keys':True,'contact_sheets':contacts,'keyframes':keys,'all44_PNG_hashes_match_actual_atomic_publish':True,'personal_visual_failure_screen':ps,'agent_observations':visual['visual_observations'],'right_edge_crest_and_display_specks_preserved_as_visual_limits':True,'original_outer_envelope_vs_actual_wrapper':chain['outer_request_envelope_discrepancy'],'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source161-personal44PNG-full836-QI-independent-adoption-proof.json';put(proof,{'source_commit':commit,'adopted_source_files':adopted,'readonly_validator':ref(vp),'actual_full836_QI':ref(qi_path),'source_scope_role_closure':ref(scope),'new_visual_decision':ref(dp),'actual_completed_native_typed_XMF_render_all0':True,'actual_all44_PNG_hashes_bound_to_atomic_publish':True,'original_outer_request_envelope_preserved':True,'source_original_bytes_preserved':True,'new_case_credit':1,'Q_N':False,'Q_E':False,'main_scientific_payload_IO':False})
ledger=O/'ledger-immutable-snapshot.json';ledger.write_bytes(raw);cpnewdata=copy.deepcopy(cp);cpnewdata['accepted_per_family']['F3']+=1;cpnewdata.update(checkpoint=223,at_utc=now.isoformat(),predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=283,accepted_decisions=cp['accepted_decisions']+[str(dp)],new_accepted_decisions=[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(ledger),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: accepted actual F3 P1200AY0320 original1047 full836 with main Root1262 UID/N3/time/native forcing QI and fresh161 personal35contacts9keys; accepted283/F3=38. Original source null typed fields and source-condition plan label distinct from truly absent runtime plan fields preserved in new sidecar.',authorized_work_state='Active283/336 F3=38; F1/F4/F7 realfinal48 delivered by Root1261. F5actual1182 full801 QI1263 ready pending fresh199 personal visual. F2actual1142/RX061 and1065/RX056 active original renders, child fresh176/fresh162 reviews after publish.');assert len(cpnewdata['accepted_decisions'])==sum(cpnewdata['accepted_per_family'].values())==283;cpnewdata['actual_progress']['source161_actualF3_1047_full836_visual_acceptance']=ref(proof);cpnewdata['source_agents']['production_recovery']='fresh161 accepted283/F3=38; fresh162 actualF2RX056ROT075 original1065';cpnewdata['next_executable_tasks']=['Adopt fresh199 F5 M105T090 original1182 with main full801 QI1263.','Own full401 QI and fresh176 review for F2RX061ROT075 original1142 after completed0 atomic publication.','Own full401 QI and fresh162 review for F2RX056ROT075 original1065 after completed0 atomic publication.','Continue original render controllers, no restarts, globalcap2, finalF6original951 awaiting capacity.'];put(cpnew,cpnewdata)
idx['previous_index_preserved']=ref(idxp);idx['source_authoritative_checkpoint']=ref(cpnew);idx['at_utc']=now.isoformat();idx['accepted_independent_physical_cases']=283;idx['registered_pending_independent_physical_cases']=53;idx['new_case_credit']=1
row=targets[0];row.update(status='visual-approved-in-checkpoint223',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,precision_status=decision['precision_status'],actual_full836_QI=ref(qi_path));idx['actual_unaccepted_completed0_published_physical_cases']=[x for x in idx.get('actual_unaccepted_completed0_published_physical_cases',[]) if (x.get('physical_case_id') if isinstance(x,dict) else x)!=pid];assert len(idx['cases'])==336 and sum(bool(r.get('accepted_decision')) for r in idx['cases'])==283;put(O/'full336-current283-actual-final48-delivery-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(p.relative_to(R)) for p in (R/prefix).rglob('*') if p.is_file()]+[str(cpnew.relative_to(R))];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept F3 pitch1200 ay0320 actual full836 with personal visual review','--',*paths],cwd=R,check=True);print(json.dumps({'accepted':283,'F3':38,'checkpoint':223,'decision':ref(dp),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()},ensure_ascii=False))
