from pathlib import Path
import json,hashlib,subprocess,datetime
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_124_f7_a059p5_delegated_visual_acceptance_v1';O=H/'root_stage1_F7_delegated124_A059P5_actual601_visual_integration_910';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
commit=subprocess.check_output(['git','rev-parse','a0bf24b0'],cwd=W,text=True).strip();names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines();assert names;adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert p.read_bytes()==b;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==b;dst.write_bytes(b);adopted.append(ref(dst))
P=R/S.relative_to(W);sp=P/'metadata/case-visual-closure.json';d=load(sp);v=load(P/'metadata/png-review-evidence.json');idx=load(P/'metadata/review-index.json');cid=d['case_id'];assert cid=='F7_OBSTACLE_QUINTIC_B08_A059P5' and d['decision']=='visual-approved-by-delegated-agent' and d['reviewer_model']=='gpt-5.6-luna/max' and d['reviewer_personally_viewed_images'];assert v['all_listed_images_viewed'] and v['contact_sheet_count']==26 and v['key_frame_count']==10
for p in v['contact_sheets']+v['key_frames']:assert p['viewed_with_view_image'] and sha(p['path'])==p['sha256'] and Path(p['path']).stat().st_size==p['bytes']
prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_118.json')['accepted_decisions'];assert len(prior)==190;assert cid not in {load(p).get('physical_case_id',load(p)['case_id']) for p in prior};digests={load(p)['physical_condition_sha256'] for p in prior}
auditp=next(H.glob('root*_909'))/'actual-delivery-and-completion-audit.json';f=next(x for x in load(auditp)['cases'] if x['case_id']==cid);ev=f['actual_completed_receipts'];assert not f['visual_accepted']
for x in ev.values():assert sha(x['path'])==x['sha256'] and (load(x['path'])['status'],load(x['path'])['returncode'])==('completed',0)
for k in ['typed_report','xmf_manifest','render_report','paraview_open_file']:assert sha(f[k]['path'])==f[k]['sha256']
t,m,a=[load(f[k]['path']) for k in ['typed_report','xmf_manifest','render_report']];sc=d['source_and_canonical_scopes'];ac=sc['actual_converter'];own=load(ac['owner_path']);assert sha(ac['owner_path'])==ac['owner_file_sha256']==sc['canonical_owner_sha256']==m['actual_provenance_owner_sha256'];digest=hashlib.sha256(json.dumps(own['physical_binding'],sort_keys=True,separators=(',',':')).encode()).hexdigest();assert digest==f['physical_condition_sha256']==ac['physical_condition_sha256']==t['hash_scopes']['physical_condition_sha256']==m['physical_condition_sha256']==m['canonical_physical_binding_sha256'] and digest not in digests
ss=sc['source_declared'];so=sc['legacy_source_owner'];assert sha(ss['source_plan_path'])==ss['source_plan_file_sha256'];assert sha(so['path'])==so['sha256'];old=load(so['path']);assert ss['source_plan_condition_sha256']==m['source_plan_condition_sha256']==old['physical_condition_sha256'];assert sc['original_canonical_binding']['sha256']==old['canonical_physical_binding_sha256'];assert len(ss['source_plan_file_sha256'])==64 and ss['source_plan_file_sha256']=='56317e7b475f147979e3dd0242ce1d2591b239e9b276ecd4fc5f3152de87fae2'
for rr in idx['receipt_chain']:assert sha(rr['path'])==rr['file_sha256'] and (load(rr['path'])['status'],load(rr['path'])['returncode'])==('completed',0)
qa=load(m['initial_qa_report']);assert sha(m['initial_qa_report'])==m['initial_qa_report_sha256'];qc=next(x for x in qa['cases'] if x['case_id']==cid);assert qc['passed'] and qc['native_particles']==70179 and {k:x['count'] for k,x in qc['checks']['native_type_mk_blocks'].items()}=={'fixed':27495,'moving':1984,'fluid':40700};assert all(qc['checks'][k] for k in ['actual_3d','all_13_fields_finite','no_initial_overlap','uid_exact_sorted_unique','xml_contract']);assert qc['physical_condition_sha256']==ss['source_plan_condition_sha256'] and qc['canonical_physical_binding_sha256']==sc['original_canonical_binding']['sha256']
out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F7','case_id':cid,'physical_case_id':cid,'physical_condition_sha256':digest,'source_review_commit':commit,'source_review':ref(sp),'visual_reviewer':'/root/f6_endpoint_initial_qa','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':d['observations'],'visual_limitations':'Sparse spray or out-of-envelope points retained as observed in this open-top geometry; individual exit routes and strict containment unqualified. No numerical-reference or external-validation claim.','agent_limitations':d['limitations'],'scope_separation':sc,'actual_completed_metadata_evidence':{**ev,'initial_qa_report':ref(m['initial_qa_report'])},'independent_full_pipeline_audit':ref(auditp),'verified_PNG_hashes':{'contact_sheets':v['contact_sheets'],'key_frames':v['key_frames']},'actual_frames':601,'actual_particles':70179,'actual_fluid_particles':40700,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'native_control_interpolation':'piecewise linear; no native C2 claim','source_control':{'actual_bound_parameters':own['physical_binding']['parameters'],'source':'actual converter physical_binding parameters; no unsupported source_control field asserted'},'scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':190,'resulting_count':191};dp=O/(cid+'-delegated-visual-decision.json');put(dp,out);put(O/'actual-integration-review.json',{'source_commit':commit,'source_adopted_byte_exact':True,'adopted_files':adopted,'previous_count':190,'resulting_count':191,'independent_case_increment':1,'decisions':[str(dp)],'science_payload_not_read_or_hashed':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'new_cases':1,'accepted':191}))
