from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f5/DualSPHysics');O=H/'root_stage1_F5_two_full801_delegated134136_actual_acceptance_and_visual_range_release_807';O.mkdir(exist_ok=True)
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def root(n):return next(H.glob(f'root*_{n}'))
assert not (O/'actual-integration-review.json').exists();prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_102.json')['accepted_decisions'].copy()
for n in [798,799,800,802,803,805,806]:prior+=load(root(n)/'actual-integration-review.json')['decisions']
assert len(prior)==125;ids={load(p).get('physical_case_id',load(p)['case_id']) for p in prior};hashes={load(p)['physical_condition_sha256'] for p in prior};decisions=[];adoptions=[]
for n,short in [(134,'0307cd67'),(136,'3ac0ca13')]:
 commit=subprocess.run(['git','rev-parse',short],cwd=W,capture_output=True,text=True,check=True).stdout.strip();src=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003').glob(f'root_followup_{n}_*'));rel=src.relative_to(W);names=subprocess.run(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,capture_output=True,text=True,check=True).stdout.splitlines();assert names;adopted=[]
 for name in names:
  p=W/name;assert p.suffix in {'.json','.py','.md'};blob=subprocess.run(['git','show',f'{commit}:{name}'],cwd=W,capture_output=True,check=True).stdout;assert p.read_bytes()==blob;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True)
  if dst.exists():assert dst.read_bytes()==blob
  else:dst.write_bytes(blob)
  adopted.append(ref(dst))
 adoptions.append({'source_commit':commit,'source_adopted_byte_exact':True,'adopted_files':adopted});P=R/rel;sp=next((P/'metadata').glob('*visual-review.json'));d=load(sp);assert d['model_profile']=='gpt-5.6-luna/max';sc=d['scope_separation'];dg=sc['canonical_physical_scope_sha256'];ev={}
 assert sha(d['actual_receipt']['path'])==d['actual_receipt']['sha256'];r=load(d['actual_receipt']['path']);assert (r['status'],r['returncode'])==('completed',0);ap=d['actual_render_report']['path'];assert sha(ap)==d['actual_render_report']['sha256'];a=load(ap);mp=a['input_manifest'];m=load(mp);t=load(m['conversion_report']);assert dg==m['physical_condition_sha256']==m['canonical_physical_condition_sha256'] and dg not in hashes and m['physical_case_id'] not in ids;assert m['candidate_id']=='C082S1_MOTION_'+d['candidate_id']
 for k in ['gencase_receipt','initial_qa_receipt','full_native_receipt','root753_receipt']:
  rp=m[k];assert sha(rp)==m[k+'_sha256'];rr=load(rp);assert (rr['status'],rr['returncode'])==('completed',0);ev[k]=ref(rp)
 actual_xmf_receipt=Path(mp).parent.parent/'execution-receipt.json';xr=load(actual_xmf_receipt);assert (xr['status'],xr['returncode'])==('completed',0);ev['actual_xmf_receipt']=ref(actual_xmf_receipt)
 assert sha(m['root753_conversion_report'])==m['root753_conversion_report_sha256'] and m['root753_conversion_report']==m['conversion_report'];assert t['conversion_status']=='completed' and t['frames']==801 and t['particles']==194427 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['hash_scopes']['physical_condition_sha256']==sc['source_h5_legacy_scope_sha256'] and t['output_sha256']==sc['typed_h5_sha256_producer_attested']==m['source_h5_sha256'];assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=16 and t['time_evidence']['strictly_increasing']
 prep=load(m['gencase_prepared_report']);assert sha(m['gencase_prepared_report'])==m['gencase_prepared_report_sha256'];assert prep['actual_total_particles']==194427 and prep['generated_xml_particle_counts']=={'fixed':158559,'moving':4210,'floating':0,'fluid':31658} and prep['actual_generated_constants']['data2d']['value']=='false';qa=load(m['initial_qa_report']);assert sha(m['initial_qa_report'])==m['initial_qa_report_sha256']
 xf=m['xdmf'];assert sha(xf)==m['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==801 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='194427 3' for g in gs);assert a['frames']==a['source_frames']==801 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(mp) and a['xdmf']==xf and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf) and a['source_h5_sha256']==t['output_sha256'];fs=a['frame_diagnostics'];assert len(fs)==801 and all(f['active']==194427 and f['missing']==0 and f['type_counts_active']=={'fixed':158559,'moving':4210,'floating':0,'fluid':31658,'unknown':0} and f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in fs)
 bp=d['bed_audit_metadata']['path'];assert sha(bp)==d['bed_audit_metadata']['sha256'];bed=load(bp);assert d['bed_audit_metadata']['frames_scanned']==801 and all(d['bed_audit_metadata'][k]==0 for k in ['max_one_dp_count','max_two_dp_count','max_missing_initial_uid','max_nonfinite_fluid_state','max_unexpected_current_uid']);assert d['delegated_visual_decision']['decision']=='visual_pass_for_'+d['candidate_id']+'_full801' and d['delegated_visual_decision']['root_adoption_required'];png=d['png_review'];assert png['all_contact_sheets_reviewed'] and len(png['all_34_contact_sheets'])==34 and png['event_keyframes_reviewed']==[0,97,153,219,400,718,800] and [v['frame'] for v in png['event_keyframes']]==[0,97,153,219,400,718,800]
 for v in png['all_34_contact_sheets']+png['event_keyframes']:assert Path(v['path']).suffix=='.png' and sha(v['path'])==v['sha256']
 for k,p in [('render_receipt',d['actual_receipt']['path']),('render_report',ap),('prepared',m['gencase_prepared_report']),('initial_qa_report',m['initial_qa_report']),('typed_report',m['conversion_report']),('xmf_manifest',mp),('xmf',xf),('bed_audit_report',bp)]:ev[k]=ref(p)
 out={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F5','case_id':d['case_id'],'physical_case_id':m['physical_case_id'],'candidate_id':d['candidate_id'],'physical_condition_sha256':dg,'source_review_commit':commit,'source_review':ref(sp),'visual_reviewer':'/root/f5_bed_recovery','main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':png['visual_observation'],'agent_limitations':png['visual_limit'],'source_xmf_receipt_placeholder_preserved':m['xmf_receipt'],'actual_xmf_receipt_bound_by_attempt':ref(actual_xmf_receipt),'scope_separation':sc,'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':{'contact_sheets':png['all_34_contact_sheets'],'key_frames':png['event_keyframes']},'actual_frames':801,'actual_particles':194427,'actual_fluid_particles':31658,'actual_last_time_s':t['time_evidence']['last_s'],'maximum_missing_particles':0,'bed_audit_metadata':d['bed_audit_metadata'],'historical_precision_negative_retained':True,'visible_mechanism_claim':'bounded surface variation and recovery; no unobserved pronounced wave or runup claim','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':125+len(decisions),'resulting_count':126+len(decisions)}
 dp=O/(d['candidate_id']+'-delegated-visual-decision.json');put(dp,out);decisions.append(str(dp));ids.add(m['physical_case_id']);hashes.add(dg)
put(O/'actual-integration-review.json',{'source_adoptions':adoptions,'previous_count':125,'resulting_count':127,'independent_case_increment':2,'decisions':decisions,'science_payload_not_read_or_hashed':True,'stage1_visual_range_release':{'amplitude_scale':[.85,1.15],'time_scale':[.8,1.0],'complete_native_window_s':16,'frames':801,'save_interval_s':.02,'remaining_non_T120_independent_conditions':10,'released_for_bounded_first_stage_native_production_after_each_actual_initial_QA':True,'T120_not_released_due_to_19p2s_forcing_exceeding_original16s_window':True,'q_n':'not_granted','strong_runup_claim':False}});print(json.dumps({'accepted':127,'F5_new_endpoints':2,'remaining10_visual_gate_released':True}))
