from pathlib import Path
import json,hashlib,collections,datetime,os,subprocess,ast
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');O=H/'root_stage1_actual170_F7_original_integer_visual_duplicate_and_scope_erratum_checkpoint_870';O.mkdir();load=lambda p:json.loads(Path(p).read_text())
def root(n):return next(H.glob(f'root*_{n}'))
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.py','.md','.xml','.xmf'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):
 p=Path(p);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');t.replace(p)
prev=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_113.json';cp=load(prev);new=load(root(869)/'actual-integration-review.json')['decisions'];assert len(new)==1;accepted=cp['accepted_decisions']+new;rows=[load(p) for p in accepted];counts=dict(collections.Counter(x['family_id'] for x in rows));assert len(rows)==170 and counts=={'F1':48,'F2':21,'F3':12,'F4':31,'F5':4,'F6':24,'F7':30};assert len({r.get('physical_case_id',r['case_id']).replace('F4_DROP_B08_','F4_DROP_') for r in rows})==170 and len({r['physical_condition_sha256'] for r in rows})==170
observations=[]
for n in [816,827,832,839,850,854,855,856,860,864,865,866]:
 p=root(n);c=load(p/'controller-launch-process.json');pr=Path('/proc')/str(c['pid']);f=(pr/'stat').read_text().split(') ',1)[1].split() if pr.exists() else [];live=bool(f and f[0]!='Z' and f[19]==c['proc_start_ticks']);assert sha(c['controller'])==c['controller_sha256'];assert not live or c['controller'].encode() in (pr/'cmdline').read_bytes();states=collections.Counter();details=[]
 for qp in list(p.glob('*request.json'))+list((p/'requests').glob('*request.json')):
  q=load(qp);rp=Path(q['attempt_root'])/'execution-receipt.json';r=load(rp) if rp.exists() else {};status=r.get('status','future request or launcher preflight pending');states[(status,r.get('returncode'))]+=1;worker=r.get('pid');details.append({'request':ref(qp),'physical_case_id':q.get('physical_case_id'),'actual_receipt_path':str(rp),'actual_receipt':ref(rp) if rp.exists() else None,'status':status,'returncode':r.get('returncode'),'actual_worker_pid':worker,'actual_worker_exists':bool(worker and (Path('/proc')/str(worker)).exists()),'visual_case_credit':0})
 result=p/'controller-result.json';observations.append({'root':n,'actual_launch':ref(p/'controller-launch-process.json'),'pid':c['pid'],'proc_start_ticks':c['proc_start_ticks'],'live_same_handle':live,'state':f[0] if f else None,'terminal_result':ref(result) if result.exists() else None,'request_state_counts':[{'status':k[0],'returncode':k[1],'count':v} for k,v in states.items()],'requests':details,'no_restart_on_IO_or_capacity_wait':True})
ledger_bytes=(D/'runtime/resource-ledger.json').read_bytes();ledger=json.loads(ledger_bytes);assert ledger['limits']==cp['limits'];assert ledger['limits']['gpu_seconds']==512*3600 and ledger['limits']['cpu_core_seconds']==3840*3600 and ledger['limits']['qualification_attempts']==1024 and ledger['limits']['production_attempts']==720;assert ledger['adopted_at_utc']==cp['adopted_at_utc'] and ledger['deadline_utc']==cp['deadline_utc'];assert sum(x.get('cpu_threads',0) for x in ledger['reservations'])<=64;assert sum(x.get('cpu_threads',0)==24 for x in ledger['reservations'])<=2;st=os.statvfs('/home/jade');free=st.f_bavail*st.f_frsize;assert free>=500*1024**3
at=datetime.datetime.now(datetime.timezone.utc).isoformat();put(O/'same-handle-real-pipeline-observations.json',{'at_utc':at,'controllers':observations,'no_Root_scientific_payload_reads_or_hashes':True,'observed_scientific_completion_is_not_visual_approval':True});put(O/'resource-window-confirmation.json',{'limits':ledger['limits'],'adopted_at_utc':ledger['adopted_at_utc'],'deadline_utc':ledger['deadline_utc'],'no_cumulative_usage_or_deadline_reset':True,'home_free_gib':free/1024**3,'CPU_reserved':sum(x.get('cpu_threads',0) for x in ledger['reservations']),'renderer_global_cap':2})
out={k:v for k,v in cp.items() if k not in ['active_reservations','actual_progress','accepted_decisions','new_accepted_decisions','predecessor','predecessor_sha256']};out.update(checkpoint=114,at_utc=at,predecessor=str(prev),predecessor_sha256=sha(prev),stage1_visual_accepted_complete_independent_cases=170,accepted_per_family=counts,accepted_decisions=accepted,new_accepted_decisions=new,attempt_counts=dict(collections.Counter(x['kind'] for x in ledger['attempts'])),gpu_hours_charged=sum(x.get('gpu_seconds',0) for x in ledger['charges'])/3600,cpu_core_hours_charged=sum(x.get('cpu_core_seconds',0) for x in ledger['charges'])/3600,active_reservations=ledger['reservations'],ledger_sha256_at_checkpoint=hashlib.sha256(ledger_bytes).hexdigest(),home_free_gib=free/1024**3,previous_goal_turn_classification='progress: one actual original F7 A031 full601 delegated visual accepted; already accepted A031P5 duplicate not counted; historical63-character owner batch digest preserved with additive actual64 SHA erratum; exact F3 fresh104 downstream source adopted; F5 live downstream and F2/F5 full-window render successor handles retained',actual_progress={'new_accepted_visual_cases':1,'native_typed_XMF_or_bed_results_do_not_grant_case_credit':True,'actual_pipeline_observations':ref(O/'same-handle-real-pipeline-observations.json'),'resource_window_confirmed_without_reset':ref(O/'resource-window-confirmation.json'),'own_F5_next34_typed_consumer':ref(root(864)/'controller-launch-process.json'),'own_F5_next34_XMF_bed_consumer':ref(root(865)/'controller-launch-process.json'),'F2_F5_actual_full_window_renderer_after_actual_F6_drain':ref(root(866)/'controller-launch-process.json'),'F5_original_bed_audit_identity_adapter_algorithm_unchanged':True,'Root_scientific_payload_reads_or_hashes':False,'Root_PNG_personal_review':False,'Home_floor_gib':500,'shared_CPU_reservation_cap':64,'renderer_global_cap':2,'conversion_serial_CPU2':True,'extra_persistent_storage_path_question':'pending user information; no scientific history deleted'})
out['source_agents']={'/root/production_recovery':'fresh104 own F3 actual839 next20 downstream source adopted Root868; fresh105 full401 visual review two F2 original unaccepted cases','/root/f6_endpoint_initial_qa':'fresh122 waits own actual856 two full1201 .6 renders before delegated visual review','/root/f5_bed_recovery':'fresh145 A031 accepted; A031P5 duplicate proof notcounted; fresh146 next two original integer angles with latest accepted-ID and condition hash checks'};out['next_executable_tasks']=cp['next_executable_tasks'].copy();out['next_executable_tasks'].insert(0,'Observe actual864 first next34 typed conversion and actual865 own XMF+bed receipts; actual866 waits actual860 full241 render24 drain before bounded full-window F2/F5 renders. No rerun of live preflight/I/O jobs.');out['next_executable_tasks'].insert(1,'Adopt fresh104 F3 actual839 per-case downstream packet then bind actual native0 only and launch shared CPU2 typed/XMF consumer; final visual approval remains delegated.');out['actual_progress'].update(new_visual_decisions=[ref(p) for p in new], duplicate_review_preserved_zero_credit=ref(root(869)/'actual-integration-review.json'), F3_exact_downstream_source_adoption=ref(root(868)/'actual-source-adoption-review.json'));out['next_executable_tasks'][1]='Enable adopted fresh104 own F3 actual839 per-case typed/XMF only after native0; preserve exact704/705 GenCase/input binding and true v1 condition. Continue fresh105 F2 and fresh146 F7 stock visual review.';put(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_114.json',out);(O/'checkpoint-validation-and-build.py').write_bytes(Path(__file__).read_bytes());paths=[str((H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_114.json').relative_to(R))]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str((root(n)/'controller-launch-process.json').relative_to(R)) for n in [864,865,866]];paths += [str(p.relative_to(R)) for p in root(869).rglob('*') if p.is_file()]+[str(p.relative_to(R)) for p in (R/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F5/handoff_20261003/root_followup_145_f7_a031_a031p5_visual_review_v1').rglob('*') if p.is_file()];note=root(868)/'root-adoption-source.py';target=note.with_suffix('.md');note.rename(target);paths += [str(note.relative_to(R)),str(target.relative_to(R))];assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip();subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-m','ds02: checkpoint170 cases with original F7 visual adoption and scope erratum'],cwd=R,check=True,stdout=subprocess.DEVNULL);print(json.dumps({'checkpoint':114,'accepted':170,'families':counts,'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'GPUh':out['gpu_hours_charged'],'CPUcoreh':out['cpu_core_hours_charged'],'attempts':out['attempt_counts'],'Home_free_GiB':out['home_free_gib']}))
