from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');O=H/'root_stage1_F6_delegated126_actual920_first_full241_visual_integration_933';O.mkdir(exist_ok=True);l=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in ['.json','.md','.py','.xml','.xmf','.png'];return hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':sha(p)};prior=l(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_122.json')['accepted_decisions'];assert len(prior)==197;old=[l(p) for p in prior];ids={d.get('physical_case_id',d['case_id']) for d in old};hashes={d['physical_condition_sha256'] for d in old};commit=subprocess.check_output(['git','rev-parse','fc08990e'],cwd=W,text=True).strip();S=next((W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003').glob('root_followup_126_*'));rel=S.relative_to(W);adopted=[]
for name in subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(rel)],cwd=W,text=True).splitlines():
 p=W/name;blob=subprocess.check_output(['git','show',commit+':'+name],cwd=W);assert p.read_bytes()==blob and p.suffix in ['.json','.md','.py'];dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==blob;dst.write_bytes(blob);adopted.append(ref(dst))
P=R/rel;idx=l(P/'metadata/review-index.json');assert idx['reviewer']=='/root/f6_endpoint_initial_qa' and len(idx['cases'])==1;row=idx['cases'][0];cl=P/'metadata'/Path(row['metadata_closure_path']).name;c=l(cl);cid=c['case_id'];pid=c['physical_case_id'];dg=c['scope_separation']['actual_converter_physical_condition_sha256'];assert pid not in ids and dg not in hashes and c['visual_decision']['status']=='visual-approved-by-delegated-agent' and c['visual_decision']['reviewed_all_contact_sheets_and_key_frames'] and not c['visual_decision']['root_personal_inspection_claim'];raw=c['producer_metadata'];ev={}
for v in c['source_files']:assert sha(v['path'])==v['sha256']
for stage in ['gencase','initial_native_qa','full_native','typed_conversion','xmf']:
 v=raw[stage]['receipt']['file'];assert sha(v['path'])==v['sha256'];r=l(v['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request']['case_id']==cid;ev[stage+'_receipt']=ref(v['path'])
assert raw['initial_native_qa']['pass'] and raw['initial_native_qa']['true_3d_data2d_false'] and raw['initial_native_qa']['physical_mass_kg']==128 and raw['initial_native_qa']['native_support_mass_kg']==256
p=l(raw['gencase']['prepared_report']['path']);assert p['actual_total_particles']==417505 and p['actual_generated_constants']['data2d']['value']=='false' and p['generated_xml_particle_counts']=={'fixed':73441,'moving':0,'floating':16384,'fluid':327680}
t=l(raw['typed_conversion']['report']['path']);m=l(raw['xmf']['manifest']['path']);xf=raw['xmf']['case_xmf']['path'];assert t['conversion_status']=='completed' and t['frames']==241 and t['particles']==417505 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['hash_scopes']['physical_condition_sha256']==dg and hashlib.sha256(json.dumps(t['hash_scopes']['physical_condition'],sort_keys=True,separators=(',',':')).encode()).hexdigest()==dg;assert m['frames']==241 and m['particles']==417505 and m['source_h5_sha256']==t['output_sha256'] and m['physical_condition_sha256']==dg and m['source_h5_read_only'];assert m['xdmf_sha256']==sha(xf);gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==241 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='417505 3' for g in gs)
q=l(c['root920_controller_evidence']['actual_request']['path']);r=l(c['root920_controller_evidence']['actual_receipt']['file']['path']);assert (r['status'],r['returncode'])==('completed',0) and r['request_sha256']==sha(c['root920_controller_evidence']['actual_request']['path']);rp=Path(row['root920_render_report']);assert sha(rp)==row['root920_render_report_sha256'];a=l(rp);assert a['frames']==a['source_frames']==241 and a['all_frames_rendered'] and a['actual_times_preserved_exactly'] and a['native_identity_axis_preserved'] and a['nonfinite_active_states']==0 and a['source_h5_sha256']==t['output_sha256'] and a['manifest_sha256']==sha(raw['xmf']['manifest']['path']) and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf);ads=a['frame_diagnostics'];fs=t['lifecycle']['frame_summary'];assert len(ads)==len(fs)==241 and all(f['finite_positions_active'] and f['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in f['finite_fields'].values()) for f in ads);assert all(f['missing_particles']==v['missing'] for f,v in zip(fs,ads));maximum=max(f['missing_particles'] for f in fs);events=sum(f['missing_particles']>0 for f in fs);assert maximum==3 and events==234 and fs[-1]['missing_particles']==3 and fs[-1]['active_particles']==417502
ad=q['audit658_dependency'];ar=l(ad['execution_receipt']);assert sha(ad['execution_receipt'])==ad['execution_receipt_sha256'] and (ar['status'],ar['returncode'])==('completed',0) and sha(ad['report'])==ad['report_sha256'];audit=l(ad['report']);assert audit['status']=='pass' and all(audit['checks'].values()) and audit['checks']['independent_floatinginfo_state0_pass'];assert audit['producer_physical_condition_sha256']==dg;ev['independent_actual_floatinginfo_state0_and_fullnative_audit658']=ref(ad['report']);ev['audit658_receipt']=ref(ad['execution_receipt'])
pngp=P/'metadata'/Path(row['png_hash_manifest_path']).name;png=l(pngp);assert png['computed_after_view_image'] and png['viewed_with']=='view_image' and len(png['contact_sheets'])==11 and len(png['key_frames'])==9
for v in png['contact_sheets']+png['key_frames']:assert sha(v['path'])==v['sha256']
ev.update(typed_report=ref(raw['typed_conversion']['report']['path']),xmf_manifest=ref(raw['xmf']['manifest']['path']),render_report=ref(rp),render_receipt=ref(c['root920_controller_evidence']['actual_receipt']['file']['path']))
d={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'visual-approved-by-delegated-agent','family_id':'F6','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':dg,'source_review_commit':commit,'source_review_closure':ref(cl),'visual_reviewer':idx['reviewer'],'main_personally_viewed_pngs':False,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':c['visual_observations'],'scope_separation':c['scope_separation'],'actual_completed_metadata_evidence':ev,'verified_PNG_hashes':png,'actual_frames':241,'actual_particles':417505,'actual_fluid_particles':327680,'actual_last_time_s':t['time_evidence']['last_s'],'physical_body_mass_kg':128,'native_support_mass_kg':256,'mass_scope_not_equated':True,'maximum_missing_particles':maximum,'final_missing_particle_count':3,'final_missing_UIDs_from_actual_producer_metadata':fs[-1]['missing_id_first'],'missing_frame_event_count':events,'delegated_lifecycle_original':c['lifecycle'],'lifecycle_limitation':'234 transient missing-frame events are not234 finalUIDs; only producer metadata gives3 finalmissing, cause unqualified. No particle-v0 or PNG-based angular/body state inference.','scientific_payload_not_read_or_hashed_by_main':True,'producer_h5_hash_verified_from_metadata_only':True,'precision_status':'视觉检查通过、数值精度未验收','q_n':'not_granted','q_e':'not_assessed','independent_case_increment':1,'previous_count':197,'resulting_count':198};dp=O/(cid+'-delegated-visual-decision.json');dp.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');review={'source_commit':commit,'adopted_files':adopted,'source_adopted_byte_exact':True,'previous_count':197,'resulting_count':198,'independent_case_increment':1,'decisions':[str(dp)],'scientific_payload_not_read_or_hashed':True};(O/'actual-integration-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n');(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print({'new_case':1,'accepted':198,'F6':25,'audit658_state0_actual_pass':True})
