from pathlib import Path
import json,hashlib,subprocess,datetime,os,collections,copy
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');L=R/'lagrangian-fluid-lab';H=L/'campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f6/DualSPHysics');D=Path('/home/jade/Projects/DualSPHysics-data/ds-data-02');root=lambda n:next(H.glob(f'root*_{n:03d}'))
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix.lower() in ('.json','.jsonl','.xml','.xmf','.png','.py','.md','.log','.txt');return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
prefix='lagrangian-fluid-lab/campaigns/ds-data-02/families/F6/handoff_20261003/root_followup_173_f2_rx058_rot075_personal_visual_acceptance_v1';commit='804ed0f50b40ce88490479c4a548cd23b77e1559'
names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',prefix],cwd=W,text=True).splitlines();assert len(names)==3
P=W/prefix;before={n:sha(W/n) for n in names};vld=P/'scripts/validate_fresh173.py';val=subprocess.run(['python3','-B',str(vld)],text=True,capture_output=True);assert val.returncode==0,(val.stdout,val.stderr);assert before=={n:sha(W/n) for n in names}
source=load(P/'metadata/personal-visual-decision.json');qi_path=root(1251)/'actual1169-full401-independent-UID-N3-time-scope-QI-proof.json';qi=load(qi_path);stage=qi['actual_completed_metadata_evidence'];cid=source['case']['case_id'];pid=source['case']['physical_case_id']
assert qi['case_id']==cid and qi['physical_case_id']==pid and qi['frames']==401 and qi['stage1_QI_full_native_identity_and_state_verified']
canonical=qi['canonical_actual_native_request_condition_sha256'];legacy=qi['actual_converter_legacy_scope_sha256'];assert source['case']['canonical_source_physical_condition_sha256']==canonical and source['case']['typed_legacy_and_actual_converter_scope_sha256']==legacy
assert source['decision']['status']=='visual-approved-by-delegated-agent' and source['decision']['case_credit']==0 and not source['decision']['global_acceptance'] and not source['decision']['q_n_granted'] and not source['decision']['q_e_granted']
for fields in stage.values():
 for e in fields.values():assert sha(e['path'])==e['sha256']
for e in source['evidence'].values():assert sha(e['path'])==e['sha256']
assert sha(source['predecessor']['path'])==source['predecessor']['sha256']
vr=source['visual_review'];assert vr['personally_viewed_with']=='view_image' and vr['contact_sheet_count']==len(vr['contact_sheets'])==17 and vr['key_frame_count']==len(vr['key_frames'])==9
rs=stage['full_render_root1169'];rr=load(rs['animation_report']['path']);pub=load(rs['publish_receipt']['path']);assert [e['path'] for e in vr['contact_sheets']]==rr['outputs']['contact_sheets'] and [e['frame'] for e in vr['key_frames']]==list(range(0,401,50));published={e['relative_path']:e for e in pub['files_excluding_receipt']}
for e in vr['contact_sheets']+vr['key_frames']:
 relative=str(Path(e['path']).relative_to(Path(rs['receipt']['path']).parent/'render'));assert sha(e['path'])==e['sha256']==published[relative]['sha256'] and Path(e['path']).stat().st_size==e['bytes']==published[relative]['bytes']
for i,e in enumerate(vr['contact_sheets']):assert e['sheet_index']==i and e['path'].endswith(f'all_frames_{i:03d}.png')
life=source['lifecycle_and_render_metadata'];ql=qi['lifecycle'];assert life['final_missing_particles']==ql['final_missing_particles']==39 and life['first_missing_frame']==ql['first_missing_frame']==137 and life['transient_missing_frame_count']==ql['frames_with_any_missing_particle']==264 and life['particle_frame_omission_events']==ql['cumulative_particle_frame_omissions']==9026
assert life['final_missing_id_sha256']==ql['final_missing_ids_sha256_producer_attested'] and life['final_missing_ids_sample_not_complete'] and len(ql['final_missing_id_first_producer_attested'])==8
assert life['final_missing_type_counts']=={'0':0,'1':0,'2':0,'3':39} and life['final_missing_mk_counts']=={'1':13,'2':13,'3':13} and life['fluid_missing_fraction_of_initial_fluid']['denominator']==21114
cpfile=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_217.json';cp=load(cpfile);assert cp['stage1_visual_accepted_complete_independent_cases']==sum(cp['accepted_per_family'].values())==len(cp['accepted_decisions'])==279
old=[load(p) for p in cp['accepted_decisions']];assert pid not in {d.get('physical_case_id',d['case_id']) for d in old}
idxp=root(1253)/'full336-current279-role-aware-registration-progress-index.json';idx=load(idxp);target=[d for d in idx['cases'] if d['physical_case_id']==pid];assert len(target)==1 and not target[0].get('accepted_decision') and target[0]['native_request_scope']['sha256']==canonical
for row in idx['cases']:
 if row.get('accepted_decision'):assert row.get('native_request_scope',{}).get('sha256')!=canonical
for key,path in [('runtime_v2_sha256',L/'scripts/ds_data02_runtime_v2.py'),('strict_dispatch_sha256',L/'scripts/ds_data02_strict_dispatch_v1.py'),('Root142_launch_sha256',root(142)/'launch.py')]:assert sha(path)==cp['unmodified_guards'][key]
# Recheck the user-authorized cleanup using only metadata hashes and filename stat.
old_cleanup=root(1235)/'cleanup-actual-results-and-retention-proof.json';cleanup=load(old_cleanup);deleted=[];retained=[];failed=[]
for row in cleanup['actual_cleanup_receipts']:
 assert sha(row['actual_receipt'])==row['receipt_sha256'] and sha(row['result'])==row['result_sha256'];result=load(row['result']);plan=load(result['plan']);assert sha(result['plan'])==result['plan_sha256']
 if row['root']==965:
  for a in plan['eligible_attempts']:deleted.extend(x['path'] for x in a['delete_files']);retained.extend(a['preserved_frame_paths']);failed.append({'path':a['receipt'],'sha256':a['receipt_sha256']})
 elif row['root']==1054:deleted.extend(x['path'] for x in plan['eligible_files']);failed.extend(x['receipt'] for x in plan['eligible_files'])
 else:
  for a in plan['attempts']:deleted.extend(x['path'] for x in a['eligible_files']);retained.extend(x['path'] for x in a['preserved_files'])
  for a in result['attempt_results']:failed.append({'path':a['original_failed_receipt'],'sha256':a['original_failed_receipt_sha256']})
assert len(deleted)==len(set(deleted))==cleanup['cumulative_deleted_files']==17203 and all(not Path(p).exists() for p in deleted) and all(Path(p).is_file() for p in retained)
for e in failed:assert sha(e['path'])==e['sha256']
z=os.statvfs('/home/jade');free=z.f_bavail*z.f_frsize/2**30;assert free>=500
raw=(D/'runtime/resource-ledger.json').read_bytes();ld=json.loads(raw);counts=collections.Counter(d['kind'] for d in ld['attempts']);gpu=sum(d.get('gpu_seconds',0) for d in ld['charges'])/3600;cpu=sum(d.get('cpu_core_seconds',0) for d in ld['charges'])/3600;assert gpu<=512 and cpu<=3840 and counts['qualification']<=1024 and counts['production']<=720
O=H/'root_stage1_source173_F2_RX058ROT075_actual1169_full401_quantified39fluid_personal17contacts_ninekeys_cleanup534GiB_acceptance_1254';assert not O.exists() and not (H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_218.json').exists();O.mkdir();adopted=[]
for n in names:
 b=subprocess.check_output(['git','show',f'{commit}:{n}'],cwd=W);assert (W/n).read_bytes()==b;p=R/n;assert not p.exists() or p.read_bytes()==b;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);adopted.append(ref(p))
P=R/prefix;vp=O/'actual-source173-readonly-validator.json';put(vp,{'validator':ref(vld),'returncode':val.returncode,'stdout':val.stdout,'stderr':val.stderr,'source_original_bytes_unchanged':True});now=datetime.datetime.now(datetime.timezone.utc).isoformat();dp=O/(pid+'-delegated-visual-decision.json')
decision={'schema':'ds02.stage1.delegated-visual-metadata-integration.v1','at_utc':now,'status':'visual-approved-by-delegated-agent','family_id':'F2','case_id':cid,'physical_case_id':pid,'physical_condition_sha256':canonical,'source_canonical_physical_condition_sha256':canonical,'actual_converter_scope_sha256':legacy,'producer_scope_schema_verified_from_actual_report':'legacy-owner-scope.v0','source_assigned_agent_family':'F6','source_family_id_F6_is_assignment_not_physical_case_family':True,'source_review_commit':commit,'source_visual_review':ref(P/'metadata/personal-visual-decision.json'),'source_review_closure':ref(P/'metadata/personal-visual-decision.json'),'independent_full401_QI_proof':ref(qi_path),'actual_completed_metadata_evidence':stage,'full_native_frames':401,'particles':418104,'actual_physical_window_s':qi['actual_time_window_s'],'all_actual_times_exact_typed_XMF_XML_render':True,'all_frames_geometry_velocity_N3_identity_and_finite_active_fields':True,'stage1_QI_full_native_identity_and_state_verified':True,'manifest_dimension_alias_absent_preserved':qi['manifest_dimension_alias_absent_preserved'],'lifecycle':ql,'missing_UID_cause_location_state_unknown_preserved':True,'legacy_alias_control_fields_not_promoted_to_actual_native_ROT075_control':True,'agent_personally_viewed_all_contacts_and_keys':True,'agent_observations':vr['observations'],'personal_visual_failure_screen':vr['observations']['failure_screen'],'personal_reviewed_contacts':17,'personal_reviewed_keyframes':9,'all26_PNG_hashes_match_actual_publish':True,'main_scientific_payload_IO':False,'main_personally_viewed_PNGs':False,'q_n_granted':False,'q_e_granted':False,'precision_status':'视觉检查通过、数值精度未验收','independent_case_increment':1};put(dp,decision)
proof=O/'source173-actual1169-full401-independent-QI-and-personal-visual-adoption.json';put(proof,{'source_commit':commit,'adopted_files':adopted,'source_validator':ref(vp),'original_independent_QI':ref(qi_path),'new_decision':ref(dp),'actual_lifecycle_limits':ql,'source_family_assignment_role_preserved':True,'actual_personal_PNG_count':26,'canonical_and_legacy_scope_roles_separate':True,'original_source172_wait_snapshot_preserved':source['predecessor'],'new_case_credit':1,'main_scientific_payload_IO':False})
put(O/'source173-QI-hold-resolved-by-main-actual1251-quantified39fluid-integrity.json',{'original_source_QI_gate':source['decision']['root_qi_gate'],'original_source_precision_and_QI_hold_preserved_verbatim':True,'resolved_first_stage_QI':ref(qi_path),'resolved_QI_does_not_imply_closed_fluid_UID_survival_or_numeric_precision':True,'all_source39_missingUID_and9026_events_limits_verified_from_actual_report':True,'eight_sample_UIDs_not_full39_list':True,'zero_fluid_loss_or_strict_container_guarantee':False,'new_case_credit_after_personal_visual_and_QI':1})
storage=O/'user-cleanup17203-current-absence-retention-home-proof.json';put(storage,{'at_utc':now,'original_cleanup_proof':ref(old_cleanup),'exact_deleted_paths_stat_checked':len(deleted),'all_deleted_paths_still_absent':True,'all_retained_first_last_filenames_present':True,'retained_samples_count':len(retained),'all_original_failed_receipt_hashes_unchanged':True,'original_failed_receipts_count':len(failed),'cumulative_released_allocated_GiB':cleanup['cumulative_deleted_allocated_GiB'],'current_Home_free_GiB':free,'Home_floor_GiB':500,'no_extra_deletion_this_verification':True,'scientific_payload_IO':False})
snap=O/'ledger-immutable-snapshot.json';snap.write_bytes(raw);cp=copy.deepcopy(cp);cp['accepted_per_family']['F2']+=1
cp.update(checkpoint=218,at_utc=now,predecessor=str(cpfile),predecessor_sha256=sha(cpfile),stage1_visual_accepted_complete_independent_cases=280,accepted_decisions=cp['accepted_decisions']+[str(dp)],new_accepted_decisions=[str(dp)],home_free_gib=free,ledger_sha256_at_checkpoint=hashlib.sha256(raw).hexdigest(),ledger_immutable_snapshot=ref(snap),active_reservations=ld['reservations'],attempt_counts=dict(counts),gpu_hours_charged=gpu,cpu_core_hours_charged=cpu,previous_goal_turn_classification='PROGRESS: ownactual1169 full401 typed/XMF/render UID/N3/time/QI and fresh173 personal17contacts9keys accepted280/F2=36; actual39fluid missing(0.1847115658percent),first137/264frames/9026events unknownlocationcause retained. All17203 deleted files stat checked absent and diagnostics retained.',authorized_work_state='Active280/336 F2=36,F5=16,F3=37,F6=47,F1/F4/F7=48. Original1161/1163 F5 renders continue through same handles; lastF6original951 capacity waiting. User cleanup cumulative534.4086GiB, Home floor500GiB protected; precision not accepted.')
assert len(cp['accepted_decisions'])==sum(cp['accepted_per_family'].values())==280
cp['actual_progress']['source173_F2_actual1169_visual_acceptance']=ref(proof);cp['actual_progress']['user_cleanup17203_current_absence_retention_reverified']=ref(storage);cp['source_agents']['f6_endpoint_initial_qa']='fresh173 accepted280/F2=36; fresh174 original951 lastF6 or first next actualpublished F2';cp['next_executable_tasks']=['Continue original1161 F5 M094T095 render; child fresh198 personally reviews actualpublished full801/34contacts/9keys, main independent metadata QI.','Continue original1163 F5 M096T095 render; production child fresh159 W3/F3 storage role distinct from physical F5, personally review after actualpublish.','Continue lastF6 original951 same controller; fresh174 may review next actualcompleted F2 publication first.','Grow F5 actualfirst24 prefix from16 immutable accepted cases; remaining F3 original11 handles preserved, real first24 delivered.','Continue56 remaining actualvisual deliverables; preserve failure diagnostics and Home500GiB floor.']
newcp=H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_218.json';put(newcp,cp)
target[0].update(status='visual-approved-in-checkpoint218',accepted_decision=ref(dp),case_credit_already_in_authoritative_checkpoint=1,case_credit=1,accepted_decision_top_condition_sha256=canonical,accepted_decision_top_hash_role='Own actual native request condition; typed/render legacy separate',precision_status='视觉检查通过、数值精度未验收')
idx.update(at_utc=now,source_authoritative_checkpoint=ref(newcp),previous_index_preserved=ref(idxp),accepted_independent_physical_cases=280,registered_pending_independent_physical_cases=56,new_case_credit=1);idx['actual_unaccepted_completed0_published_physical_cases']=[p for p in idx['actual_unaccepted_completed0_published_physical_cases'] if p!=pid];idx['actual1169_full401_QI_snapshot']=ref(qi_path);put(O/'full336-current280-role-aware-registration-progress-index.json',idx)
(O/'integration-source.py').write_bytes(Path(__file__).read_bytes());paths=[str(Path(e['path']).relative_to(R)) for e in adopted]+[str(p.relative_to(R)) for p in O.iterdir() if p.is_file()]+[str(newcp.relative_to(R))]
subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','commit','-q','-m','ds02: accept RX058 ROT075 with quantified omissions and verify 534GiB cleanup','--',*paths],cwd=R,check=True)
print(json.dumps({'checkpoint':218,'accepted':280,'F2':36,'remaining':56,'Home_GiB':free,'deleted_files_reverified':len(deleted),'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()}))
