from pathlib import Path
import json,hashlib,subprocess,datetime,xml.etree.ElementTree as ET
R=Path('/home/jade/.codex/worktrees/ds-data-02-integration/DualSPHysics');H=R/'lagrangian-fluid-lab/campaigns/ds-data-02/handoff_20261003';W=Path('/home/jade/.codex/worktrees/ds-data-02-f3/DualSPHysics');S=W/'lagrangian-fluid-lab/campaigns/ds-data-02/families/F3/handoff_20261003/root_followup_106_f2_first24_visual_decisions_v1';O=H/'root_stage1_F2_delegated106_actual_first8_RX063_full401_visual_integration_888';O.mkdir(exist_ok=True);load=lambda p:json.loads(Path(p).read_text())
def sha(p):
 p=Path(p);assert p.suffix in {'.json','.md','.py','.xml','.xmf','.png'};return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'sha256':sha(p)}
def put(p,d):Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
commit='57fe0ff26e25a90fd3c7f2707185add544fdab7e';names=subprocess.check_output(['git','ls-tree','-r','--name-only',commit,'--',str(S.relative_to(W))],cwd=W,text=True).splitlines();adopted=[]
for name in names:
 p=W/name;assert p.suffix in {'.json','.py','.md'};b=subprocess.check_output(['git','show',f'{commit}:{name}'],cwd=W);assert p.read_bytes()==b;dst=R/name;dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists() or dst.read_bytes()==b;dst.write_bytes(b);adopted.append(ref(dst))
P=R/S.relative_to(W);manifest=load(P/'manifest.json');assert manifest['review_boundary']['agent_personally_viewed_all_17_contact_sheets_and_4_key_frames_per_case'];prior=load(H/'ROOT_LIVE_RESUMPTION_CHECKPOINT_114.json')['accepted_decisions']+load(next(H.glob('root*882'))/'actual-integration-review.json')['decisions']+load(next(H.glob('root*883'))/'actual-integration-review.json')['decisions'];old=[load(p) for p in prior];ids={x.get('physical_case_id',x['case_id']) for x in old};hashes={x['physical_condition_sha256'] for x in old};assert len(prior)==173;decisions=[]
for row in manifest['cases']:
 dp=P/'decisions'/Path(row['decision_path']).name;d=load(dp);cid=d['case_id'];pid=d['physical_case_id'];meta=load(P/'metadata'/Path(row['metadata_path']).name);assert d['status']=='visual-approved-by-delegated-agent' and d['agent_personally_viewed_all_contacts_and_keys'] and d['main_personally_viewed_pngs'] is False and pid not in ids;original_agent_labeled_digest=d['physical_condition_sha256'];source_payload=load(meta['source_metadata']['path'])['physical_condition'];canonical=hashlib.sha256(json.dumps(source_payload,sort_keys=True,separators=(',',':')).encode()).hexdigest();assert canonical not in hashes
 ev=meta['actual_completed_metadata_evidence'];assert ev==d['actual_completed_metadata_evidence']
 for alias,key,field in [('gencase_receipt','gencase','path'),('initial_qa_report','initial_qa','report_path'),('native_receipt','native','path'),('typed_report','typed','report_path'),('xmf_manifest','xmf','manifest_path'),('render_report','render','report_path')]:meta[alias]={'path':ev[key][field],'sha256':ev[key]['sha256' if field=='path' else 'manifest_sha256' if field=='manifest_path' else 'report_sha256']}
 for key in ['source_metadata','source_plan_owner','actual_converter_owner','gencase_receipt','initial_qa_report','native_receipt','typed_report','xmf_manifest','render_report']:v=meta[key];assert sha(v['path'])==v['sha256']
 ev=d['actual_completed_metadata_evidence']
 for key in ['gencase','initial_qa','native','typed','xmf','render']:
  v=ev[key];assert sha(v['path'])==v['sha256'];r=load(v['path']);assert (r['status'],r.get('returncode'))==('completed',0)
 for key in ['typed','render']:
  v=ev[key];assert sha(v['report_path'])==v['report_sha256']
 v=ev['xmf'];assert sha(v['manifest_path'])==v['manifest_sha256'];v=ev['initial_qa'];assert sha(v['report_path'])==v['report_sha256'];qa=load(v['report_path']);assert qa['status']=='pass' and all(qa['checks'].values());p=load(ev['prepared_input_report']['path']);assert sha(ev['prepared_input_report']['path'])==ev['prepared_input_report']['sha256'] and p['actual_total_particles']==418104 and p['generated_xml_particle_counts']=={'fixed':372840,'moving':24150,'floating':0,'fluid':21114} and p['actual_generated_constants']['data2d']['value']=='false'
 source=load(meta['source_metadata']['path']);payload=source['physical_condition'];digest=hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(',',':')).encode()).hexdigest();assert digest==canonical==source['physical_condition_sha256'] and pid==source['physical_case_id'] and payload==d['physical_condition'];assert payload['receiver_x_m']==int(cid.split('RX')[1][:3])/100 and payload['rotation_duration_s']==.65 and payload['rotation_final_angle_deg']==-105
 t=load(meta['typed_report']['path']);m=load(meta['xmf_manifest']['path']);a=load(meta['render_report']['path']);legacy=t['hash_scopes']['physical_condition_sha256'];assert legacy==meta['actual_converter_legacy_scope_sha256']==m['physical_condition_sha256'] and legacy!=canonical;assert t['conversion_status']=='completed' and t['frames']==401 and t['particles']==418104 and t['solver_dimension']['solver_dimension']==3 and t['partvtk_validation']['all_passed'];assert t['time_evidence']['first_s']==0 and t['time_evidence']['last_s']>=4 and t['time_evidence']['strictly_increasing'];assert m['frames']==401 and m['particles']==418104 and m['source_h5_sha256']==t['output_sha256'];xf=Path(m['xdmf']);assert sha(xf)==m['xdmf_sha256'];gs=ET.parse(xf).getroot().findall('.//Grid[@GridType="Uniform"]');assert len(gs)==401 and all(g.find('Geometry/DataItem').get('Dimensions')==g.find('Attribute[@Name="velocity"]/DataItem').get('Dimensions')=='418104 3' for g in gs)
 assert a['frames']==a['source_frames']==401 and a['all_frames_rendered'] and a['native_identity_axis_preserved'] and a['actual_times_preserved_exactly'] and a['nonfinite_active_states']==0 and a['manifest_sha256']==sha(meta['xmf_manifest']['path']) and a['xdmf_sha256_before']==a['xdmf_sha256_after']==sha(xf) and a['source_h5_sha256']==t['output_sha256'];fs=t['lifecycle']['frame_summary'];ads=a['frame_diagnostics'];assert len(fs)==len(ads)==401 and t['lifecycle']['introduced_ids']=='rejected';assert max(x['missing_particles'] for x in fs)==d['maximum_missing_particles'] and fs[-1]['missing_particles']==d['final_missing_particle_count'];assert all(x['missing_particles']==y['missing'] for x,y in zip(fs,ads));assert all(x['finite_positions_active'] and x['identity_axis_preserved'] and all(v['finite_active'] and v['nonfinite_active']==0 for v in x['finite_fields'].values()) for x in ads)
 png=d['verified_PNG_hashes'];assert len(png['contact_sheets'])==17 and len(png['key_frames'])==4
 for v in png['contact_sheets']+png['key_frames']:assert sha(v['path'])==v['sha256']
 assert original_agent_labeled_digest==canonical
 out={**d,'physical_condition_sha256':canonical,'source_scope_correction':{**d['source_scope_correction'],'original_agent_physical_digest_label':original_agent_labeled_digest,'actual_converter_legacy_scope_sha256':legacy,'source_canonical_physical_condition_sha256':canonical,'root_scope_confirmation':'Source106 correctly separates actual source payload and converter legacy digests; independently recomputed; no source or scientific bytes modified.'},'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_review_commit':commit,'source_review_original_base_commit':d['source_review_commit'],'source_review_decision':ref(dp),'root_recomputed_source_canonical_digest':True,'root_verified_all_actual_metadata_receipts_and_N3_full401':True,'scientific_payload_not_read_or_hashed_by_main':True,'main_personally_viewed_pngs':False,'independent_case_increment':1,'previous_count':173+len(decisions),'resulting_count':174+len(decisions)};dest=O/(cid+'-delegated-visual-decision.json');put(dest,out);decisions.append(str(dest));ids.add(pid);hashes.add(canonical)
assert len(decisions)==1;put(O/'actual-integration-review.json',{'source_commit':commit,'source_adopted_byte_exact':True,'adopted_files':adopted,'previous_count':173,'resulting_count':174,'independent_case_increment':1,'decisions':decisions,'scientific_payload_not_read_or_hashed':True,'bounded_UID_exclusions_preserved_without_filling_or_qualified_causes':True});(O/'adoption-source.py').write_bytes(Path(__file__).read_bytes());print(json.dumps({'new_cases':1,'accepted':174}))
